### ISSUE TITLE
Forum milestone

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1067]
# Introduction

![](https://user-images.githubusercontent.com/247363/126659373-2782972f-4c68-466c-ac6e-e19e123e38c5.png)

An immutable, auditable, public forum is the main communication and coordination forum among platform members.

*   [Forum chapter](https://joystream.gitbook.io/joystream-handbook/subsystems/forum) in the handbook
*   [Wireframes](https://www.figma.com/file/xP9qdHWamHvV60fm0vvbOz/Forum?node-id=315%3A65528)

# Goals

The forum subsystem will allow users to:

1.  Browse forum (for non-members)
2.  Follow your own threads
3.  Participate in the discussion (for members)

The focus of this milestone is put in allowing non-members and members to create & participate in the discussion. The Forum Working Group Leader actions are put for later implementation.

# Goals details

Each goal has a work scope with links to GH tickets.

*   Tickets with a :purple\_circle: (and "epic" label) are considered to require ~1 week of work).
    *   The rest of the tickets should require a 0.5-1 day of work each.

### Base UI components & integration

*   #1061
*   #1065
*   #1064
*   #1068
*   #1062
*   #1063

### Browse as non-member

*   Overview
    *   #1056
    *   #1057
    *   #1084
    *   #1085
*   Categories & Threads
    *   #1058
    *   #1059
*   Search & archive
    *   #1060
    *   #1081
    *   #1082
    *   #1083

### Browse as a member

*   #1066
*   #1086

### Participate in the discussion

*   Create Thread
    *   #1069
    *   #1072
    *   #1073
*   #1074
*   #1077
*   #1166 

---

[Moved](https://github.com/Joystream/pioneer/issues/1067#issuecomment-886878772) outside the scope of the milestone:

*   #1075 
*   #1122
*   Tags
    *   #1078
    *   #1079
    *   #1080
    *   Create Thread
    *   #1070
    *   #1071
*   #1076
*   #1091 🟣 This might require a considerable effort (defined in #50 )

**Comment by bedeho** [comment]
- How functional would it be to leave out the following for another iteration?
  - polls
  - reactions
  - app resource identifiers
- How much does it impact the estimate?
- If we leave it out, how do we track these so they are not forgotten for later?

**Comment by jodator** [comment]
> How functional would it be to leave out the following for another iteration?

Polls – they are quite big, so the impact might be 1-2 weeks shorter milestone (in total)

Reactions – I'd say that, for what we have ATM, ~2 days max (AFAIR it consider only displaying a reaction(s) + one simple modal to sign & send a transaction).

App resource identifiers – I'd love to leave that for later and work on them later when we'd have all resources links (an ability to link to them). I'd say ~2 weeks or more since I didn't dig into that too much.

> If we leave it out, how do we track these so they are not forgotten for later?

I'm tracking those under two milestones:

1.  [Before release](https://github.com/Joystream/pioneer/milestone/8) – things that were left out, but are essential to use Pioneer app. (e.g. bugs, features omitted due to lack of API support, etc)
2.  [After release](https://github.com/Joystream/pioneer/milestone/7) – anything that is not essential and can be added later. (e.g. Lead actions).

**Comment by bedeho** [comment]
Awesome, thats a full 4 weeks at least, lets cut that out for now then!

**Comment by jodator** [comment]
> Awesome, thats a full 4 weeks at least, lets cut that out for now then!

I'll update the issue description & milestone tasks today.

**Comment by jodator** [comment]
The milestone in the minimal form is done. The Forum open tickets are below:

[Moved](https://github.com/Joystream/pioneer/issues/1067#issuecomment-886878772) outside the scope of the milestone:

*   #1075 
*   #1122
*   Tags
    *   #1078
    *   #1079
    *   #1080
    *   Create Thread
    *   #1070
    *   #1071
*   #1076
*   #1091 🟣 This might require a considerable effort (defined in #50 )
