### ISSUE TITLE
Create Thread: General step

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1069]
@[figma](https://www.figma.com/file/xP9qdHWamHvV60fm0vvbOz/Forum?node-id=315%3A61552)

Requirements:

- [x] Add "Create thread" base modal
  - [ ] #1138
- [ ] Validate topic length (display the length & do not allow more letters to type)
- [x] Description must be a non-empty field

**Comment by p-sad** [comment]
Topic length doesn't seem to be checked on-chain, maybe we don't need to keep it short?
