### ISSUE TITLE
Search forum controls

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1082]
Add dedicated controls for searching in the [archived threads](https://www.figma.com/file/xP9qdHWamHvV60fm0vvbOz/Forum?node-id=315%3A51085):

- [ ] Author
- [ ] Archived date

No search by tags.

**Comment by thesan** [comment]
See [figma comment](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7?node-id=5294:140700#104746410)
