### ISSUE TITLE
Mentioning app resources

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1091]
**Context**

Implement the app resource identifiers in the markdown editor. See #50.

## Scope
**1. List of linkable resources**

* a member :white_check_mark: 
* ~a blog~ **Forum** thread :white_check_mark:
* ~a blog~ **Forum** post :white_check_mark: 
* a proposal :white_check_mark: 
* a proposal discussion entry :white_check_mark: 
* an opening :white_check_mark: 
* an application :white_check_mark: 

⛔  Out of scope:

* a block   ⛔  - follow up 
* a transaction ⛔  - follow up 
* Blog post ⛔  - follow up (blogs poposals: #1880)
* Blog thread - ⛔  follow up (blogs poposals: #1880)

- - -
**2. How to trigger mention**

## [Link To Mentioning resources designs Figma> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=5673%3A154482)
:one: 

Since there might be numerous items to link to (Member, Block, Thread, Post, Opening, etc). Usually an editor would allow to mention different entities by assigning a trigger character like `@` or `#`. However, if we'd like to mention multiple entieties we'd have to consider using only one or two. Having more would require users to learn them and remember which might be poor UX and discoverability.

In #50 I've proposed a `@proposal[]()` notation that extends "standard" Markdown link notation `[]()` (inspired by Stories On Board).

This means that we could use just `@` to trigger the Mentioning Window and fetch all the matching items (probably grouping them by type). We might also combine this with longer trigger character:

1. User types `@` (show mention help with general items
1. User types `@prop` – show general search for "prop"
1. User types `@proposal`  – switch to Proposal only search by searching for anything after the `@proposal`
1. User types `@proposalSlash Anna` – search for "Slashanna" proposals.

This is however tricky in the terms of UX:

* how to show diffent entieties in one list
* I don't recall if it would be easy to implement the extended logic for mention search as described above :warning: Qcza to validate.

:two: 

The other option is to allow mentioning by typing only for a limited set of triggers, like

* `@` for members
* `#` for ... (forum posts?) :warning:  bedeho  to suggest what's most frequent /important to allocate this prefix for.

And for rest of the mentionable items use editor UI buttons.

- - -
**3. A way of encoding this inside Markdown**

[Link to CK editor documentation](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/using-react-in-a-widget.html#demo)

* How to represent this link in markdown?
* How to represent this link in App?
* How to represent this link during the content editing?

Ad. 1. :

It may be something similar to a link markup:

proposal ["Proposal title"] (http://www.somejoystreamsite.com/proposals/id/789)>

or

proposal ["Proposal title"] (789)

I've seen a similar pattern in Stories-on-Board app for Figma embeds. The plus of this is that it provides a nice fall-back for a standard markdown to HTML processor.

Ad. 2.:

This would require a markdown to HTML processor in the Joystream App that will detect such markup and potentially display a rich widget or in-app link to a proposal. AFAIR most of the Markdown processors allow custom extensions.

Ad. 3.:

The editor can detect this link and represent it internally as special objects. This can be also displayed as a "widget", so offering a rich preview. An example of this might be this demo. It renders a widget containing a React component inside the editing area.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958986032406) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
I am not following what specific scope we have for the concepts we will support, so just replicating the partial list I initially provided in another issue in order to close it.

https://github.com/Joystream/pioneer/issues/50

- a block
- a transaction
- a member
- a blog thread
- a blog post
- a proposal
- a proposal discussion entry
- an opening
- an application
... and probably many more.
