### ISSUE TITLE
Forum categories filter

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#1169]
- [ ] Use the search bar to filter categories
- [ ]  Display the number of results on the "categories" tab

**Comment by thesan** [comment]
@jodator if [there is a search bar to filter the categories](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=4409%3A129866), does that mean that the categories should be paginated ?

**Comment by jodator** [comment]
@thesan This is for a general search in forum: #1082, but it looks like I forgot to write the requirements there. Sorry for that.

You can see how's that designed on the [wireframes](https://www.figma.com/file/xP9qdHWamHvV60fm0vvbOz/Forum?node-id=315%3A50814). So there's no need to filter the categories. I'd assume that there will be around 10-20 top categories (there's [12 on the previous testnet](https://testnet.joystream.org/#/forum)).

I'll expand the search forum functionality description, but it should search through posts. I don't see a need for searching categories ATM.

For the forum categories part you can skip adding search for now.
