### ISSUE TITLE
Misc Pioneer UX Fixes

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#1247]
I had a look at the current state of the app, and my understanding of where we are going, and the

1. The authoring experience for free-text, such as forum posts, seems very awkward. It's currently a one line editing box, which is very rough and largely defeats the WYSIWYG ambition. This was not really designed, but just taken off the shelf, so I think it needs some care. Importantly, I'm still not clear on how resource identifiers will work. How will the user do them, how will they learn that they can be done, and how will they be displayed on the consumption end? This needs to be nailed down now I think, as it applies to many places across the app.

2. We need empty states in quite a few places, certainly whenever we are doing any kind of search or filtering which can result in 0 results. Some clear and consistent visual for this is needed.

3. We don't really do any connectivity UX. The only thing we do is to display an alert when a connection is lost, or when it is _attempted_ to be made, not when its actually made. But I think events are actually not the right emphasis for this, what is relevant to the user is to when they are not currently connected, and when they currently are. This arguably requires some consistent impossible to miss visual state which tells you when you are not connected. Here we are also actually talking about two separate connections: the full node and the query node. Arguably, if you loose connection to either, the app should really urge you to stop and wait until everything works. It may also make sense to disable the final button in any flow where a transaction would be submitted, if you currently are not connected to both nodes.

**Comment by natiwa** [comment]
Regarding 2nd point here is what we came up with https://www.figma.com/proto/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?page-id=5239%3A137902&node-id=5239%3A138428&viewport=333%2C48%2C0.37&scaling=min-zoom

Other points, we want to discuss with devs first.

**Comment by jodator** [comment]
Hello, sorry for the delayed answer on this.

1.  I'll try to summarize what I see we could do here in #50 with some examples. Basically, we can extend the editor how by implementing additional features to it.
2.  AFAIK this was already handled in the design (comment above)
3.  This is being worked on to improve the visual states. The idea is to:
    1.  disable the buttons when we lost connectivity to the Joystream Node
    2.  disable browsing the app when the connectivity to the Hydra Node is lost

For the 3rd point, it makes sense to allow the user to browse the app state (from Hydra) but to disallow any actions. It _should_ be the most recent state anyway (even though, the connection to the blockchain might be lost) so it shouldn't be that confusing. It might be also a less common case than losing connection to both (e.g. network problem).

**Comment by dmtrjsg** [comment]
POint 2 

Point 3 superceded by 

- [ ] #2342
