### ISSUE TITLE
Archived `<CategoryListItem />` shouldn't query Moderators

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#1260]
Loading the categories is already a bit slow, so since the archived CategoryListItem don't show the moderators it would be better not to query these categories moderators data.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203239107006407) by [Unito](https://www.unito.io)

**Comment by jodator** [comment]
> So the way to fix is to create and use another query in [ForumArchived](https://github.com/oleksanderkorn/pioneer/blob/c42469f5c461f779b29c40377bbb833750395fb5/packages/ui/src/app/pages/Forum/ForumArchived.tsx#L23) that does not fetch moderators, do you agree with that approach?

I think that this might be a good approach. Just be sure that you follow the [query-node guide](https://github.com/Joystream/pioneer/blob/main/docs/README.md#adding-queries). The change should originate from [`council.graphql` file](https://github.com/Joystream/pioneer/blob/main/packages/ui/src/forum/queries/forum.graphql#L148-L152).

**Comment by oleksanderkorn** [comment]
@jodator as i understand from the docs command `yarn run queries:generate` should also generate hooks, but when i add new Fragment to `forum.graphql` and run the rask, i see that it generates new fragments, but there are no new hook i can use:

![image](https://user-images.githubusercontent.com/9252017/142285027-585b6c35-8956-453f-a477-1cabbd8019c0.png)

![image](https://user-images.githubusercontent.com/9252017/142285149-5e22a13a-6baf-4d98-a52d-0eea7b6f3cb2.png)

Should i add the hook manually, or i am doing something wrong?

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/forum
wss://44.201.112.198.nip.io/ws-rpc

@traumschule @oleksanderkorn  Let me know if there is a specific scenario I need to test

https://user-images.githubusercontent.com/46903215/199476248-0aa3da5d-3f30-4a87-9725-fc1219c567ba.mov
