### ISSUE TITLE
Expand `excludePaths` and `knownRoutes` lists for breadcrumbs

### ISSUE THREAD

**Issue by p-sad** [Joystream/pioneer#1280]
We haven't taken a look at `src/app/constants/breadcrumbs.ts` for a while and a bunch of dead/incorrect routes appeared in breadcrumbs while the site was expanding. I think someone needs to go through available pages and make sure only links to valid pages are left

**Comment by jodator** [comment]
Let's see if anyone submit an issue for this. Looks like handled in #1429
