### ISSUE TITLE
Remove the gray overlay for search results

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#1326]
Or maybe the dark overlay could be removed?

**Comment by jodator** [comment]
Yeah, that's a good question. I see two possible ways:

1.  As you mentioned remove the gray overlay to allow preview
2.  Hide the search window on click

And the first is being the better as it allows to click and preview if the result is actually the one or not. The second would require to re-open the search box which might be frustrating.

If you don't see other options I'd remove the gray overlay for search results.
