### ISSUE TITLE
Period length dashboard stat

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1378]
@[figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=2014%3A595)

- [ ] Determine the current period and its length
- [ ] Display current period length as time left
- [ ] DIsplay current period length as blocks left

Display stat on dashboards:
- [ ] Council
- [ ] Election
- [ ] ...

**Comment by jodator** [comment]
@thesan I think we missed other election rounds in [https://github.com/Joystream/pioneer/blob/a68005d49d5761fed8c187a7e4eea781409d0681/packages/ui/src/council/hooks/useElectionRemainingPeriod.ts#L13-L18](https://github.com/Joystream/pioneer/blob/a68005d49d5761fed8c187a7e4eea781409d0681/packages/ui/src/council/hooks/useElectionRemainingPeriod.ts#L13-L18)

There's only `announcing` but there should be also other stages handled.

**Comment by jodator** [comment]
I think that this should do the trick:

```typescript
  const periodLength = useMemo(() => {
    switch (electionStage) {
      case 'inactive':
        return api?.consts.council.idlePeriodDuration
      case 'announcing':
        return api?.consts.council.announcingPeriodDuration
      case 'revealing':
        return api?.consts.referendum.revealStageDuration
      case 'voting':
        return api?.consts.referendum.voteStageDuration
    }
  }, [api, electionStage])
```

But I'm not sure about `change_at` behavior.

**Comment by thesan** [comment]
Sorry, I had not seen `revealStageDuration` and `voteStageDuration` because I was looking for then under `consts.council` so I thought they were not implemented yet. Then I wanted to keep it in mind and not close this issue but then I completely forgot by the time I updated the PR. I should have at least wrote about this in here.
