### ISSUE TITLE
Council milestone

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1418]
## Introduction

![image](https://user-images.githubusercontent.com/247363/132541034-d8fb5c92-ebce-4ae3-aab4-59d4c49bed7b.png)

The politically selected governance body responsible for managing the proposal system for the benefit of voters.

Resources:
- [handbook](https://joystream.gitbook.io/joystream-handbook/governance/council)
- [wireframes](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu/Council?node-id=1%3A8)
- [design](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1883%3A2427)

## Goals details

The goal of the milestone is to allow Pioneer users to get an overview of the council members, track election progress, and participate in the election as a candidate or voters.

Tickets with a 🟣 (and "epic" label) are considered to require ~1 week of work).
The rest of the tickets should require 1-2 days of work each.

### Components & integration

Technical requirements that bootstrap work on bigger tasks.

#### Module setup
* [x] #1377

#### Base components
* [x] #1381
* [x] #1384

#### Stats
* [x] #1382
* [x] #1379
* [x] #1380
* [x] #1378
* [x] #1383

### Council as non-member

Finishing tasks from this section would allow any Pioneer user to get an overview of the council or the election process.

#### Council preview
* [x] #1385 🟣 
* [ ] #1386 🟣 

#### Election preview
* [x] #1387
* [x] #1388
* [x] #1389
* [x] #1426

### Council as member

Any aspiring member would be enabled to participate in the election process either by announcing their candidacy or by voting on other candidates.

#### Election stage
* [x] #1398
* [x] #1399

#### Announce candidacy
* [x] #1400
* [x] #1401
* [x] #1402
* [x] #1403
* [x] #1404
* [x] #1405
* [x] #1406
* [x] #1407
* [x] #1408
* [x] #1409

#### Voting period
* [x] #1410
* [x] #1411
* [x] #1412

#### Revealing Period
* [x] #1413
* [x] #1414
* [x] #1415

---

## Past council

An optional focus for the milestone.

#### Past councils
* [x] #1390
* [x] #1391
* [x] #1392
* [x] #1393
* [x] #1394
* [ ] #1395

#### Past elections
* [x] #1396
* [x] #1397

#### Stake recovery
* [x] #1416
* [ ] #1417

**Comment by jodator** [comment]
@bedeho Thanks :blush: 

Taking the previous rough estimates taking the Past council, Past Elections and Past Votes should cut the time by 1-1.5 weeks. This would mean that we could finish a week earlier than the milestone goal.

**Comment by bedeho** [comment]
Ok, lets do that then, can we track this pending work somewhere then?

**Comment by jodator** [comment]
Since most of the issues will be done I'm moving all the remaining features (mostly: #1386) and any Council fixes to the Olympia milestone. The two remaining features are on PR review ATM and will be closed soon.

Hereby I'm closing the milestone ticket :tada:
