### ISSUE TITLE
Use isFinalized field to fetch proposals

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1440]
Currently, we can't filter by `statusJSON` in Hydra. However, the schema has a convenient field (`isFinalized`) that allows differentiating from active and past proposals.

Use this field to fetch proposals:

*   [ ] Current proposals page
*   [ ] Past proposals page

**Comment by thesan** [comment]
@jodator is the `isActive` field implemented on `olympia-dev` yet ?
