### ISSUE TITLE
Handle missing member info

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1442]
On the membership info modal we still have missing fields

*   [x] Hired times
*   [x] Applied times
*   [x] Being a lead
*   [x] Being a council member
*   [x] Slashed
*   [x] Initiated leaving
*   [x] Blog posts (forum posts?)

Verify each field if possible to fetch data for it (eg. the council member requires having council schema)

**Comment by jodator** [comment]
@thesan Please check if the updated solution would work with the Olympia testnet (without a Council in the schema).

If not, then we might just need to postpone merging the PR or introduce a temporary feature flag for the testnet.

**Comment by thesan** [comment]
I forgot about that :facepalm:.
I just tried, it doesn't work on the Olympia testnet (i.e only "Hired" and "Being A Lead" show their count, the rest have a "-").

**Comment by jodator** [comment]
> I just tried, it doesn't work on the Olympia testnet (i.e only "Hired" and "Being A Lead" show their count, the rest have a "-").

The app doesn't crash with this query, so I think that we can be optimistic about that. I've created a tracking issue for similar scenarios (schema not yet present on testnet).
