### ISSUE TITLE
Paginated thread queries also fail on Olympia testnet

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#1460]
~~Querying the `ThreadStatusLocked` event from the `ForumThread.status` causes a GraqhQL error: `Cannot return null for non-nullable field ForumThread.status`~~

`[Entity]Connection` type queries don't work correctly when using inline fragments on union types (more details [here](https://github.com/joystream/pioneer/issues/1460#issuecomment-1047989726)).

**Comment by jodator** [comment]
> Querying the `ThreadStatusLocked` event from the `ForumThread.status` causes a GraqhQL error: `Cannot return null for non-nullable field ForumThread.status`

@thesan could you post the query that causes the problem?

**Comment by thesan** [comment]
@jodator I just realized, this fails:
```gql
query {
  forumThreadsConnection {
    edges {
      node {
        status {
              ...on ThreadStatusLocked {
            threadDeletedEvent {
              inBlock
            }
          }
        }
      }
    }
  }
}
```
because of the `threadDeletedEvent` part.

But this works:
```gql
query {
  forumThreads {
    status {
      ...on ThreadStatusLocked {
        threadDeletedEvent {
          inBlock
        }
      }
    }
  }
}
```
So it should work now. Although there is probably an issue with hydra...

**Comment by jodator** [comment]
Thanks! Now I see. Yep, it looks like the same select is treated differently for `connection` type queries :/

For standard, page-based, pagination that's not a problem. I don't recall where we use this query, but it _could_ be useful for the overview widget to load next/previous "cards".

**Comment by thesan** [comment]
This is partially solved, but now:
```gql
query {
  memberMetadataConnection {
    totalCount
    edges {
      node {
        name
        avatar {
          __typename
          ...on AvatarUri { avatarUri }
        }
      }
    }
  }
```
returns:
```js
{
  "data": {
    "memberMetadataConnection": {
      "totalCount": 14,
      "edges": [
        {
          "node": {
            "name": "LazyFish",
            "avatar": null
          }
        },
        ...
      ]
    }
  }
}
```

While:
```gql
query {
  memberMetadata {
    name
    avatar {
      __typename
      ...on AvatarUri { avatarUri }
    }
  }
}
```
Returns the correct result:
```js
{
  "data": {
    "memberMetadata": [
      {
        "name": "LazyFish",
        "avatar": {
          "__typename": "AvatarUri",
          "avatarUri": "https://avatars.dicebear.com/v2/male/c1e82d4d528d39e62d3db310ea068062.svg"
        }
      },
      ...
    ]
  }
}
```

**Comment by dmtrjsg** [comment]
Closing for now and Hydra is the answer to this problem. Nearest future is not impacted by this problem.

Load more instead of Pagination is impossible as a result of this.
