### ISSUE TITLE
Proposal discussion post deposit should be taken from proposal consts

### ISSUE THREAD

**Issue by p-sad** [Joystream/pioneer#1462]
⚠️ **THIS ONLY WORKS BECAUSE IT IS SET TO ZERO ON RUNTIME**

New const is available already
__________
The constant we need is not exposed in the API yet. We need to wait for another API update (there is an open issue for this constant), and base the constant used on whether it's a forum post or a proposal discussion post that we're submitting.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201742955501053) by [Unito](https://www.unito.io)

**Comment by jodator** [comment]
> (there is an open issue for this constant)

Could you link to the said issue?

**Comment by dmtrjsg** [comment]
@p-sad pls link the issue referred so we can pick it up and discuss in the next planning.

**Comment by dmtrjsg** [comment]
@thesan can we have a look and see if the task Piotr was referring to is now unblocked? Also what is the best way to find out which value is now used for Discussion Post deposits?

**Comment by thesan** [comment]
@bedeho the [handbook](https://joystream.gitbook.io/testnet-workspace/system/proposal-system#post-to-thread) doesn't mention any post deposit to create a post in a proposal discussion. However it looks like the runtime is [checking](https://github.com/Joystream/joystream/blob/85c1bb6e4f051402292f658f879870dac168fd05/runtime-modules/proposals/discussion/src/lib.rs#L250) then [taking](https://github.com/Joystream/joystream/blob/85c1bb6e4f051402292f658f879870dac168fd05/runtime-modules/proposals/discussion/src/lib.rs#L259) a `PostDeposit` from the signer's account. Or should the proposal discussion posts not be editable ? (which would solve the problem)

**Comment by bedeho** [comment]
The handbook was just not updated to reflect the introduction of such deposits, thats all, its not fully in-synch with the chain any longer.

**Comment by dmtrjsg** [comment]
@mnaamani  this is the ticket

**Comment by dmtrjsg** [comment]
to test:
create proposal
add a post which is editable
check the value of the deposit that is asked 

dmitry-pioneer playground has discussion deposit is < forum post depost

**Comment by bwhm** [comment]
At least partially fixed! When I had enough, it showed 2k. When I didn't:

![Screen Shot 2022-03-17 at 21 04 00](https://user-images.githubusercontent.com/35237943/158886554-c5d20214-6074-42c9-b2db-3fb70532ca17.png)
