### ISSUE TITLE
The edit post transaction is not working

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1463]
I was using "edit post" action on the [testnet](https://pioneer-2.netlify.app/#/forum/thread/10?post=40) and it produces weird results.

The Post was edited from

> 2 0I might like to edit this post in the future…. 

To:

> 0I might like to edit this post in the future…. aaaand I did

But it produced: 

> 0I might like to edit this post in the future…. 

It needs to be checked whether it is a bug on Pioneer side (e.g. Wrong transaction parameters) or an upstream side.

**Comment by p-sad** [comment]
I tried querying the test query node; it seems like the post text is consistent with the event text.
```json
{
  "data": {
    "postTextUpdatedEvents": [
      {
        "id": "OLYMPIA-141647-5",
        "createdAt": "2021-09-13T14:41:00.000Z",
        "postId": "40",
        "newText": "\n0I might like to edit this post in the future…."
      },
      {
        "id": "OLYMPIA-141774-3",
        "createdAt": "2021-09-13T14:53:42.000Z",
        "postId": "40",
        "newText": "\n2\n0I might like to edit this post in the future…."
      }
    ],
    "forumPosts": [
      {
        "text": "\n2\n0I might like to edit this post in the future…."
      }
    ]
  }
}
```
Also the Joystream Handbook says the post text should be a human-readable text, though that may be extremely out of date.
I guess the next step might be checking if the post text hash on-chain is consistent with the post text that the query node has.
