### ISSUE TITLE
Olympia release milestone

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1475]
## Introduction

The main goal of the initial release of the Pioneer 2 is to allow the community to review the functionality of the new front-end for the Joystream DAO purposes. In this regard, the main focus is to provide a minimal set of features that would allow participation in the governing process of Joystream and gather feedback at the earliest stage possible.

The initial set of supported modules would include:

*   My Profile (accounts & [memberships](https://joystream.gitbook.io/joystream-handbook/subsystems/membership) management)
*   [Working Groups](https://joystream.gitbook.io/joystream-handbook/governance/working-groups)
*   [Proposals](https://joystream.gitbook.io/joystream-handbook/governance/proposals)
*   [Council](https://joystream.gitbook.io/joystream-handbook/governance/council)
*   [Forum](https://joystream.gitbook.io/joystream-handbook/subsystems/forum)
*   Members

## Action plan

To make the Olympia release feasible together with the Pioneer 2 we need to:

1.  Review the current state of the project
2.  Decide with features are essential for the release

### 1\. Review

During the Pioneer 2.0 project development the Olympia runtime and the query node were developed in parallel. The main focus was put on understanding the Joystream project and delivering as much as possible without a fully operational backend. This means that we need to put an effort to review existing features in order to:

*   Remove any stubs or placeholders
*   Missing features from the UI designs perspective
*   Ensure the Pioneer 2 works with the Olympia testnet in regard to
    *   sending extrinsic
    *   reading blockchain state from the query-node

### 2\. Scope of the release

After the review is done, we should have a better understanding of what is needed. 

The list below is a preliminary set of features:

*   list of proposals that can be created using Pioneer 2
*   list of proposals that should be displayed (covering the proposal parameters)
*   notify about opening
*   unread notification indication
*   wait for the transaction update until data is available in the query-node

**Comment by jodator** [comment]
My Profile

*   No information about lock association (My Accounts) ([figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=137%3A8774))

**Comment by jodator** [comment]
WiP...

## Current "Olympia" milestone scope

### General

*   Transaction error reason (#478)

### Forum

*   #1332

### My Profile

*   Staking handling
    *   Recoverable balance (#790)
    *   Recoverable locks (#946)

### Members

*   Filter by council member (#858)

### Working Groups / Opening

*   The "notify me when..." button (#414)
*   The applicants/hiring limit target (#1110) #1499,
*   Add stake (missing stake) #1130
*   Move excess tokens (#1129)
*   Reward periods (#1494)

### Proposals

*   Display proposals
    *   Not all proposal details are displayed
*   Create proposals
    *   Proposal creation issues #1509
*   Use constants from the API
    *   Creating the proposal (for validation) #1510
    *   Discussion post deposit (#1462)

UI & small bugfixes:

*   #1506
*   #1502
*   #1508
*   #1497
*   #1511
*   #1501

## Testnet issues

Some of the queries are not yet supported by the current version of Hydra. Those are tracked by [`testnet`](https://github.com/Joystream/pioneer/labels/testnet) label, as:

*   Pagination queries #1460
*   Search members using dedicated query #499
*   Application question using filter #500

**Comment by thesan** [comment]
@jodator about the testnet issues, Joystream/joystream#2608 probably needs to be solved too for Olympia

**Comment by dmtrjsg** [comment]
Remaining effort is captured in the respective epics:
https://github.com/Joystream/pioneer/issues/1923
https://github.com/Joystream/pioneer/issues/1921
https://github.com/Joystream/pioneer/issues/1924
https://github.com/Joystream/pioneer/issues/1909
https://github.com/Joystream/pioneer/issues/1925
https://github.com/Joystream/pioneer/issues/1919
https://github.com/Joystream/pioneer/issues/1091
https://github.com/Joystream/pioneer/issues/50
https://github.com/Joystream/pioneer/issues/1786
