### ISSUE TITLE
Extension of the previous milestones scope

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1476]
The scope of already coded milestones was limited. Please check the milestone design tickets for open issues:

*   Proposals: https://github.com/Joystream/pioneer/issues/539#issuecomment-885056810
*   Forum: [https://github.com/Joystream/pioneer/issues/1067#issuecomment-920129804](https://github.com/Joystream/pioneer/issues/1067#issuecomment-920129804)
*   Working Groups: [https://github.com/Joystream/pioneer/issues/315#issuecomment-920140805](https://github.com/Joystream/pioneer/issues/315#issuecomment-920140805)

**Comment by dmtrjsg** [comment]
Milestones now reflected in corresponding epics
