### ISSUE TITLE
Make the role banner clickable

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1496]
Click on the whole bar should expand the role details:

![](https://user-images.githubusercontent.com/247363/133793046-cba66aab-9d93-4524-bf3e-8fc80c8cedfe.png)

**Comment by traumschule** [comment]
Implemented

![sidebar-roles](https://user-images.githubusercontent.com/31551045/197422512-3879bf8e-6cf1-435e-ac31-88c8b0853447.png)
