### ISSUE TITLE
Application side-modal updates

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1497]
<img width="607" alt="Screenshot 2021-09-24 at 15 48 06" src="https://user-images.githubusercontent.com/247363/134685348-224bdcae-352a-4857-a599-cb405339a02f.png">

The Application preview modal should:

*   [ ] The title should be "Application" for other member's applications. The word "My Application" should be used only for applications made by the user controller members (`useIsMyMember()`hook).
*   [ ] Add a link to the opening in the "General Detail" tab (click on this link should close the modal)

**Comment by dmtrjsg** [comment]
Done,checked on vercel env.
