### ISSUE TITLE
Restyle the edits history modal

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1508]
The forum post edits history modal does not match the [design](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=4809%3A128851):

*   [x] There should be no numbers, just chevrons ('\<')
*   [x] Properly display edit block & date
*   [x] Posts should be divided using a divider line
*   [x] Add 'show more' button for longer posts.

**Comment by ClumsyVlad** [comment]
3) Resolved in #1552

**Comment by ClumsyVlad** [comment]
4. Resolved in #1576

**Comment by ClumsyVlad** [comment]
2. Resolved in #1577

**Comment by ClumsyVlad** [comment]
1. Resolved in #1727
