### ISSUE TITLE
Forum events do not implement Event interface

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1524]
We're missing this one to have nice events fetching for the Forum.

See: https://github.com/Joystream/pioneer/pull/1523/files#diff-2498817ed659e00be54b8effc5a00b31c33be2fd9c92538b13daeb2af34a6752R332-R351

**Comment by jodator** [comment]
@bedeho FYI:  Assigned @dmtrjsg as we're in a stage where we have multiple PRs waiting that will break a public testnet. So either we're fine with that or we bump the public testnet query-node version.

**Comment by bedeho** [comment]
Can you restate this? I did not follow.

**Comment by jodator** [comment]
@bedeho Sorry for that. It was a quick note during the sprint planning session.

The issue is that we're at the point that Pioneer 2 development is ahead of the `olympia` integration branch from the joystream repository. We have already a few PRs waiting with features that will make the current olympia testnet unusable if we merge them.

For the development team, it is not an issue as we already work with a local instance of the query-node. We also would like to work with all the PRs merged.

We could either:

1.  continue without a working public testnet for some time.
2.  wait for the testnet to be upgraded with all of the breaking features (Council schema, Avatars for members, etc).

We discussed this briefly with @dmtrjsg so he will probably reach out to you about this in the future.

**Comment by bedeho** [comment]
I think a working public net is essential, I think @Lezek123  is the best to consult about fixing this.

> We have already a few PRs waiting with features that will make the current olympia testnet unusable if we merge them.

Unusable in what way, what breaks?

**Comment by jodator** [comment]
> Unusable in what way, what breaks?

Fetching membership data – which is a core entity for the app. If we can't fetch membership-related data, all other components would fail as well.

Example PRs:

*   (community) #1706
*   Avatar URLs: #1907

Both touch member data.
