### ISSUE TITLE
Rescoping Initial Olympia Proposal

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#1531]
# Background

An excellent draft proposal was made for the scope of the Olympia release, and here I attempt to try to clarify and further restrict the scope in the interest of a timely launch.

https://github.com/Joystream/pioneer/issues/1475#issuecomment-921793934

# Proposal

## Investigate
  
- which proposals should we have proposal creation for? Needs review, @bedeho can provide final adjudication. All other proposals can be made into `good-frist-issue`.

## Remove

- working group lead actions.
- everything about app-independent resource idenitifers (#50, #768, #1091).
- leave out user notifications: missing query node support of filtering & not done yet.
- ilter by council member : make it `good-first-issue`.
- UI & small bugfixes: make it `good-first-issue`.
- "notify me when..." button.
- query application question by relation filter.
    
## Add

- onboarding.
- council member proposal voting & discussion.
- display all proposal type parameter values.
- waiting for the transaction to be mined and the outcome to be available in the query node.
- new working groups
  - support for storage working group.
  - support for distributor working group.
  - support for 3 additional operations working groups

**Comment by jodator** [comment]
The rescoped issue comment is here: https://github.com/Joystream/pioneer/issues/1475#issuecomment-928911820.

Closing this as done.
