### ISSUE TITLE
Council schema upgrade tracking issue

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1536]
Because of council schema is not present on the testnet any query that references the unknown entities will fail.

This includes:

*   Any council requests
*   Detailed information about a member on member modal (See https://github.com/Joystream/pioneer/issues/1442#issuecomment-925652155)

**Comment by p-sad** [comment]
We're also probably going to need a `status` field in `Candidate`. It would allow us to tell apart candidates who
* have been elected
* have withdrawn their candidacy
* have failed an election
* are candidates in the current election

**Comment by jodator** [comment]
@DevNikita16 do you remember where you'd like to add this filed?

**Comment by thesan** [comment]
@DevNikita16 `referendumStageRevealingOptionResults` was remove from the schema so it's now replaced by `ElectionRound.endedAtBlock`, `ElectionRound.endedAtTime` and `ElectionRound.endedAtNetwork`. I think this solves the problem.
