### ISSUE TITLE
Account lock origin

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1556]
~Currently, there's no information about lock association on the "My Accounts" page~ ([figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=137%3A8774)).

Only the locks type and amount, and the possibility to recover some stake are implemented on the "My Accounts" page. According to the design there should be more information available:
![Screenshot from 2022-02-16 16-21-57](https://user-images.githubusercontent.com/6571453/154297997-8a4a9f7c-eecc-4045-a089-80981588a681.png)

In order to implement this, we need the query node to return information about locks as there is no information about lock origin in the node's API.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201743007083556) by [Unito](https://www.unito.io)

**Comment by jodator** [comment]
To be discovered: Actually one could search for latest entry for a related query. For instance, for "working group XXX" lock we might search the last working group opening for given group:

```graphql
query {
  workingGroupApplications(where:{stakingAccount_eq:"5DX2K84TJwLFFd82VHCUVbyACVpFry2GwZPsSjEY5CddpcYC"}) {
    id
    stakingAccount
    opening {
      id
      groupId
    }
  }
}
```

This actually returns a proper value:

**Comment by dmtrjsg** [comment]
Currently we see that the lock origin (the locked accounts widget) is showing in the app, but this info most probably taken from chain (and incorrectly). 

We need to add this request to be supported by Query Node.

**Comment by dmtrjsg** [comment]
Superceded by #2300
