### ISSUE TITLE
Miscellaneous tiny design enhancements

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#1602]
Can we make this small tweaks to the design for Olympia?

1. Can we separate out the election related tabs from the council related tabs into two separate areas of the app? The combined Council area is now very big already, and often what people will want to look at is one or the other, in particular elections when they come around, rather than looking at the council.
2. Can we add the bounty tab in the app, and then add a subtle `coming` label to all of the tabs that will not be be live in Olympia, but will come later, so that would be:
   - constitution
   - bounties
   - overview
   - financials
   - validators
   we could also add new tabs we know will come some time in the future
   - gateways
   - storage
   - bandwidth
   - content
   alternatively, if there would be too many tabs with the `coming` label, perhaps it could make sense to group all of these disabled buttons at the bottom in the menu in a section titled `COMING`.
 3. Move the "Recover all" button for stake recovery to the top right corner of the screen - which is the standard action button position across the app, from inside the awkward position in the container currently.

**Comment by jodator** [comment]
Closing this as:

1. Will be handled by https://github.com/Joystream/pioneer/issues/1775.
2. All "coming" tabs are gathered under "Upcoming" as on [figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=6459%3A195361).
3. Already handled.
