### ISSUE TITLE
Expose and backup voting salt

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#1633]
## Background

Currently, the voting [salt](https://joystream.gitbook.io/joystream-handbook/governance/council#reveal-vote) is generated in the browser and stored in local storage. This is obviously not great, because it means that a browser state reset will cause you to loose your ability to reveal your vote, and you also cannot use a different browser or device.

## Proposal

We should make it possible for the user to backup and import their salt when voting. The backup could be to simply display the salt, or to allow a file download - as those likely have an easier time persisting. There also needs to be an input or import step during revealing.

## User Stories

**Backup salt**
- [ ] On the first vote member is displayed with a salt modal
   - Concept of salt (tooltip) "Voting salt is a random string, generated for a given member id and used for securing the vote to be published without exposing the contents of the vote, and contents to be securely revealed during reveal stage. It is stored locally in the browser and all votes submitted on this device and browser can be revealed using this salt. Voting salt is _required_ to reveal your vote. It can be lost forever, if cookies are cleared. Backup your voting salt to ensure your vote can be revealed later, even from a different browser or device."
   - Input for [meta data ](https://joystream.gitbook.io/joystream-handbook/governance/proposals#vote-1)(pre-populated; proposal; The type of vote; rationale; councilor)
   - Preview of filename (using meta inputs as a mask, editable)
   - "Display" Salt -> so can be copy-pasted ❓ 
    - "Checkbox" to acknowledge that vote can be lost if salt is lost, default value = false
   - "Checkbox" Export Voting Salt file, default set = true
   - CTA "view announcement"
   - 💡  would be great if there is some sort of self-validation in the export format, so that it describes what specific vote, voter member id, in what election and so on, the salt is for, so that when the user tries to import, they are warned if they have the wrong salt, and perhaps explains what it is for, e.g. this salt is not for your membership, this salt is not for this vote, etc.

Figma link to the [Vote Submitted Modal](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu/Council?node-id=218%3A32146)

 - [ ] Subsequent votes from same device+browser could have a modification of this window, since salt is already stored by browser and may have been exported.

**Reveal Vote flow when Salt missing**
- [ ] User logged in from a diff browser and device shown an additional modal to import voting salt as part of [reveal vote flow](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu/Council?node-id=218%3A27572) 
- [ ] User can add a string value of salt, instead of file import ❓ 
- [ ]  Validation errors e.g. this salt is not for your membership, this salt is not for this vote,
- [ ]  Salt is vote-specific, bulk salt import not supported.

**Recover**
- [ ] User can "recover" the salt if lost, but still logged in from the browser and device where vote was casted.
- [ ]  Salt backup (repeat backup of salt) can be done from the vote modal (as opposed to [top of the screen CTAs](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu/Council?node-id=156%3A15411)) Shall we just add a tertiary link here? What's best based on design system?

**Comment by jodator** [comment]
I'm adding this as an optional for the Olympia release (just to have it done after all other tasks). The UX design should be available in the meantime.

**Comment by bedeho** [comment]
Tip: would be great if there is some sort of self-validation in the export format, so that it describes what specific vote, in what election and so on, the salt is for, so that when the user tries to import, they are warned if they have the wrong salt, and perhaps explains what it is for.

**Comment by thesan** [comment]
#1766 and  #1800 partially solved this, but IMO it's not really clear to the user when should he backup his votes.

Maybe the option could appear on [the vote casting confirmation modal](https://www.figma.com/file/Z3KcRoAll3JGEY622o0iZu/Council?node-id=218%3A32146) with some brief explanation. WDYT ?

**Comment by traumschule** [comment]
> it's not really clear to the user when should he backup his votes.

Would it be acceptable to have something like a red `!` pill near the `My Votes` counter to remind the user with a tooltip after voting?
Alternatively the reminder could be on `VoteForCouncilSuccessModal.tsx`.

**Comment by dmtrjsg** [comment]
I'm with @traumschule here, best to do it on the confirmation message and add a CTA to start the backup process right from  this modal 👌

**Comment by dmtrjsg** [comment]
Can this be updated to 

"Import your file with voting salt here and submit the transaction to restore votes."

<img width="459" alt="Screenshot 2022-11-24 at 13 16 40" src="https://user-images.githubusercontent.com/93924525/203744763-54bd72c3-53f0-41d3-94be-f50c6c358746.png">

in a separate PR?

**Comment by traumschule** [comment]
[Had sneaked in new text](https://github.com/Joystream/pioneer/commit/02cd4c66b6ed1eb37087cbe901e35995129d0dbd)
> In case of browser storage loss or when switching devices, restoring your votes from a backup file may be necessary to reveal them. Upload your votes backup file to the browser storage here.

Still change?

**Comment by dmtrjsg** [comment]
@traumschule Nah thats cool mate 👍 ready for qa-then no need in follow up PR, thanks for taking ownership of this ⭐

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/election/past-elections/00000255
wss://34.230.5.182.nip.io/ws-rpc

Works as expected 👍

### Made a backup of my votes
<img width="940" alt="Снимок экрана 2023-01-24 в 14 04 44" src="https://user-images.githubusercontent.com/46903215/214291336-42130a0f-d545-4743-a9f8-4c2458fb275e.png">

### Deleted my votes from the local storage
<img width="1206" alt="Снимок экрана 2023-01-24 в 14 09 05" src="https://user-images.githubusercontent.com/46903215/214291351-ce5902b8-3d68-4831-b362-67a58a8966a8.png">

### Successfully restored my votes
<img width="733" alt="Снимок экрана 2023-01-24 в 14 09 21" src="https://user-images.githubusercontent.com/46903215/214291360-4e99d68b-15c5-4abe-9061-59fab6cf34ed.png">
<img width="733" alt="Снимок экрана 2023-01-24 в 14 10 00" src="https://user-images.githubusercontent.com/46903215/214291362-402961b0-cca9-4a6b-8b3c-8f86deda0545.png">
<img width="1203" alt="Снимок экрана 2023-01-24 в 14 11 19" src="https://user-images.githubusercontent.com/46903215/214291367-d1e4f8d2-19b1-4552-b116-536a990fa187.png">

### Revealed my votes
<img width="1204" alt="Снимок экрана 2023-01-24 в 14 12 29" src="https://user-images.githubusercontent.com/46903215/214291372-704e4fe8-be20-4af3-96af-50daa9ec93bf.png">
