### ISSUE TITLE
Onboarding: Handle Free Tokens step and status

### ISSUE THREAD

**Issue by DevNikita16** [Joystream/pioneer#1725]

**Comment by jodator** [comment]
This is blocked by https://github.com/Joystream/atlas/issues/1596

**Comment by DevNikita16** [comment]
I've not succeeded  in finishing onboarding. The issue is that Mirage.js is interrupting Axios requests. I don't receive neither callback nor error.
Pretender.js - tool built-in in Mirage.js is fetching both of them(at least error 100%) even if I use passthrough option. I've found some threads on Stackoverflow, but they don't have any answers :disappointed:
Also I see that in Atlas they migrated from Mirage.js to msw.js
