### ISSUE TITLE
How to run pioneer 2.0 on the local dev chain

### ISSUE THREAD

**Issue by oleksanderkorn** [Joystream/pioneer#1756]
Hello, I have been following the docs here: https://github.com/Joystream/pioneer/tree/main/docs
and was trying to set up the local node to have `sudo` in place to test some fixes.  But I faced one issue. 
If i use this command to run the node in dev mode, the pioneer UI is not working properly:
```
joystream-node --dev --tmp --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all --log runtime
```
When I open the UI it has shown me a white screen and I also found a lot of console errors. 
I think this is probably related to the runtime version. 
I am running `joystream-node` on mac os, version is `version 5.1.0-9d9e77751-x86_64-macos`.

I assume the runtime version is not compatible, so maybe there could be added some instructions of how to run it properly so it will work, e.g. should I build the node from sources of a specific branch, or do we have it as an artifact somewhere ready to be used? 

![image](https://user-images.githubusercontent.com/9252017/141273338-1d1a2016-de65-4eaf-abf0-714e0d5dd9a9.png)

**Comment by jodator** [comment]
@oleksanderkorn Yes, sorry for that. Until the Olympia release, we work using the upcoming runtime version.

You should be able to run the runtime from [https://github.com/Joystream/joystream/tree/olympia](https://github.com/Joystream/joystream/tree/olympia) branch (or the [https://github.com/Joystream/joystream/tree/olympia_dev)](https://github.com/Joystream/joystream/tree/olympia_dev)) – but, IIRC both have the same runtime version.

**Comment by jodator** [comment]
Hello, @oleksanderkorn :wave: 

Sorry for the late response but the setup changed dynamically over the past two weeks. However, the #1879 PR gathers the latest information about the setup that we use internally to check the Pioneer 2.0 with the Joystream ecosystem
