### ISSUE TITLE
The "My Profile" milestone goals

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#178]
## Top-level overview

The goal of this milestone is to enable aspiring members to become active platform users.

With the above assumption, a focus should be put on domains and data closely related to the given goal. With that in mind some information might not be available at this stage:

- Locked balances details.

### Non-member
- As a non-member, I want to get an overview of the state of all of my accounts.
- As a non-member, I want to lookup the balance associated with a given account.
- As a non-member, I want to share my account with others in order to receive funds.
- As a non-member, I want to be able to spend from one of my accounts.
- As a non-member, I want to be able to create a new membership.
- As a non-member, I want to transfer founds.

### Member
- As a member, I want to see my list of memberships in order to select one for usage.
- As a member, I want to logout of one of my memberships.
- As a member, I want to update my profile.
- As a member, I want to be able to login to one of my memberships.
- As a member, I want to invite other members.
- As a member, I want to transfer my invitations to other members.

## Goals to postpone:
- As a non-member, I want to look up a particular member's history and current involvement.
- As a member, I want to recover my recoverable balances.

**Comment by bedeho** [comment]
Can you link to the individual screens or flows on Figma which correspond to the relevant user stories in each case?

**Comment by jodator** [comment]
Closing this one as the milestone have been closed.
