### ISSUE TITLE
The hiring stats fix

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1781]
PR is fine, but I guess It's not the best UI :D Maybe we can make 5 stat columns?
![image](https://user-images.githubusercontent.com/83761318/142182586-07219a80-2764-4d65-a572-90e44909e9f6.png)

_Originally posted by @DevNikita16 in https://github.com/Joystream/pioneer/pull/1768#pullrequestreview-808392014_

**Comment by ClumsyVlad** [comment]
It looks like on the design so let's keep it. I'd like to add possibility of multi columns instead of only two.
