### ISSUE TITLE
Tooltip coverage

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#1784]
This product is extremely conceptually dense, with almost all screens having some new concept a user may never have come across. One of the onboarding features which have the lowest friction, and which also are very contextual and easy to access, are tooltips. Currently, we have many tooltips, but also many places they are missing, and I think we really should err on the side of having too few - and instead perhaps remove later, than clearly too few, like now. Here is an example

![Screenshot 2021-11-18 at 18 22 25](https://user-images.githubusercontent.com/437292/142465196-bf5e2377-1ef9-446f-9b0a-e9aeb2b33d0b.png)

**Comment by dmtrjsg** [comment]
this was addressed in https://github.com/Joystream/pioneer/issues/2201 and in t[his document ](https://www.notion.so/Tool-Tips-and-Copy-e9ad7970fab348cdb16c7d3a3d462a33#5f83451bd6264c53a8a89fdc69afbf60)specifically
