### ISSUE TITLE
Pioneer Product Onboarding: Q4 2021

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#1796]
# Document Purpose

The purpose of this document is to attempt to summarize the current status of work on Pioneer, in a broad sense, for the benefit of all recent incoming and near term incoming team members, and in particular a new product manager to be on boarded very soon.

# Background

The Pioneer product has now been worked on for close to a year, first through an intensive design phase, then a long development phase where the design work has substantially tapered off in intensity. The product is only now reaching a level of feature coverage where it would be feasible to run a fully functional community operated testnet using it and the Command Line Interface ([CLI](https://github.com/Joystream/joystream/tree/master/cli)) in combination. The development process is still in catch up mode to a range of designs which have been prepared, but which have been scoped out of the first release in `Olympia`, as they were not considered blockers for launching. On the team side we are currently in a pivotal transition stage, where the old design and engineering team is transitioning out by end of 2021, and a new team is taking over, and this is taking place precisely when the product is about to launch. Lastly, the `Olympia` version of Pioneer is built on top of a blockchain which alters almost every part of the system, and it has never been part of a live testnet.

# Pioneer

## Introduction

Pioneer is the web based consumer product exposing the governance, operational and communication side of the Josyream system. Currently there is a v1 version of the product available here

https://testnet.joystream.org

Reflecting the version of our system as reflected by the `Sumer` network, described here

https://www.joystream.org/sumer

## Assets

The product is built entirely in the open, so all of our assets are public and transparent, and all assets exists under permissive licenses.

- Handbook: https://joystream.gitbook.io/joystream-handbook/
- Source code:
  - Query Node: https://github.com/Joystream/joystream/tree/master/query-node
  - Hydra: https://github.com/Joystream/hydra
  - Blockchain: https://github.com/Joystream/joystream/tree/master/runtime
- Designs: https://www.figma.com/files/team/948238880377822926/Joystream-%7C-Governance-App%2FUXandUI?fuid=632538047582453662
- Planning
  - Tech Kanban (Olympia): https://github.com/orgs/Joystream/projects/44

## Purpose

Pioneer is meant to be the product used, in conjunction with another command line product for doing more advanced features, to allow people to participate in the DAO that power the Joystream platform. This means they are involved in planning, work, collaboration and deliberation through activities like

- Running for the council
- Participating in the council voting on and discussing proposal
- Submitting proposals
- Applying for and roles and working in working groups
- Interacting on the forum

Before mainnet, the role of Pioneer is to serve as a way for users to learn how to operate the Joystream system once it goes live, by participating in one of our incentivized testnet schemes. The audience is therefore actors with greater than average technical sophistication, and often pre-existing familiarity or commitment to the blockchain space, likely participating in other projects in parallel. It is not a target experience for the average content consumer and creator, however we expect that some subset of more sophisticated users in these categories may be involved in Pioneer related activities as well as their primary content activity.

## Technology

The Pioneer web app itself has a relatively conventional web stack for purpose, see here for details

https://github.com/Joystream/pioneer/blob/main/docs/README.md

Perhaps the only exception being an external extension for key management, as is customary for web applications in Web3. The app makes transactions by talking to a dedicated full node, and it queries the state of the blockchain using a dedicated caching node, called the query node, which serves this through a GrapQL API. The application is not yet integrated with the native Joystream storage and bandwidth system for storing and serving heavy assets, like avatars and attachments to proposals and blog posts. Below, each of these three components are unpacked a bit deeper.

### Joystream Blockchain

**Maintainers**
 - Shamil
 - Ignazio
 - Mokhtar
 - Arsen
 - Gabriel

The Joystream blockchain is the technical centrepiece, serving as both the data, social and economic infrastructure layer for the overall system. It is a standalone Proof-of-Stake (PoS) blockchain (hence not a set of smart contracts, as is often the case for other systems). The native token, or currency, of the system is called JOY, is often denoted by the currency symbol $JOY. A distinguishing feature of the system is that it is upgradable, meaning that it has a built in capability for the community to upgrade the rules that govern the system. The Joystream blockchain is written on top of a blockchain framework called [Substrate](https://docs.substrate.io/), which is a Rust based SDK for developer to build their own blockchains. This means we do not need to deal with very low level concepts, such as peer-to-peer networking, the consensus algorithm or state database. We only need to define the business logic of our specific use case, and this is done in Rust.

### Query Node

**Maintainers**
 - Andy
 - Leszek

When applications need to read the state of the blockchain in some way, for example to see all video channels that exist, this mostly does not work well if you attempt to do so my directly connecting to a validator node. Validator nodes, who are involved in the business of validating the integrity of the system as it evolves, do not have any search indexes that allow for efficient queries of the current state of the system. For this reason, the query node is an intermediate query node layer which maintains various explicit query state that can be accessed through a GraphQL API. Our particular query node is built on top of a framework we built, called _Hydra_, described here

https://www.joystream.org/hydra

A critical issue with the query node infrastructure is that any changes to the blockchain require that infrastructure developers have to define the APIs, through schemas called _input schemas_, and processing code that takes blockchain ledger events and transactions, and updates the underlying query state of the node, these are called _mappings_. Writing such input schemas requires understanding both the underlying business logic of the part of the blockchain you want to expose to applications, and also what the requirements are of the particular application(s) you have in mind. This capability currently does not exist within the Pioneer team itself, and so far they have relied on infrastructure developers to support them.

Currently, there is only a single query node deployed in every test or production deployment for Joystream networks, and it is operated by Jsgenesis in those cases. The likely future scenario is that running a query node will get bundled into the activities of a Gateway, as what particular schemas and queries are relevant to a given product instance may not apply to another. An alternative could be to make it a paid DAO role, or to try to rely on a third party middleware protocol like [Subsquid](https://www.subsquid.io/) eventually will become.

### Polkadotjs Extension - Key Manager

**Maintainers**
 - External

A key design requirement of Pioneer was that the user had full custody of all digital assets, meaning that no third-party (even the future Gateway) should have access to any of the keys that control the $JOY, NFTs, Social Tokens, channels or memberships of the user. This is not the only way to build apps on top of Joystream, someone could - and likely will, build a fully custodied and friction minimised version.

With this constraint in mind, the only robust way to allow users to manage keys, while also using the app in the browser, is to rely on a browser extension for key management. For the Ethereum ecosystem, [Metamask](https://metamask.io/) plays this role. Since Joystream is built on Substrate, we use the extension [Polkadotjs extension](https://github.com/polkadot-js/extension), which is the equivalent for this ecosystem. It is not a full wallet, for example it does not have the ability to speak to a validator node, so ti cannot send transactions or display balances, it only allows for holding keys and signing transactions.

![extension](https://user-images.githubusercontent.com/437292/142620200-8c1a1750-01a3-4277-9ef8-52f89e244c7a.png)

### Design

As stated, the product has been in design and build mode for a substantial period of time, hence it could still be useful to consult the initial design brief that informed the design effort

https://github.com/Joystream/pioneer/issues/48

### `Olympia`

As stated prior, the `Olympia` release is the first production deployment of Pioneer, and here we attempt to summarise the rough feature set targeted for that release. The product is divided into major sections which serve some dedicated purpose, and the following sections are currently, to some significant extent, functional

- **My Profile:** Managing & creating memberships and assocaited funds and staking
- **Working Groups:** Discovery and get an overview of the state of all working groups, including deep diving on each group, viewing opening, applying for a job, viewing past history, etc.
- **Proposals:** Browse and find proposals, and look at detailed history and state of individual proposals. Create proposals and discuss them with members and council members! Council members can also vote on proposals
- **Council:** Browse and find councils, current and in past, as well as getting ad etailed view of each council in terms of who was a participant and what proposals they resolved.
- **Election:**  Browse and find elections, current and in the past, as well as vote on candidates, announce candidacy, and see election outcomes.
- **Forum:** Normal nested category based forum with free text search, labels and on-chain moderation.
- **Members:** Browse and search and view members.
- **Settings:** Control behaviour of app, specifically now just to control what network to connect to.

Outside of these areas there is also a generalised onboarding flow that can be jumped into from multiple parts of the app, and also a transaction submission flow for interacting with the chain.

### Mainnet

It is yet to be determined what is an absolute must feature set for mainnet launch, which is expected Spring 2022.

### Must Haves

- **Missing Proposals:** The handbook as a list of proposals, but even that does not cover all proposals available in the `Olympia` runtime https://joystream.gitbook.io/joystream-handbook/governance/proposals#proposals. The idea was to first focus on supporting the most critical proposals, and then expand coverage in Pioneer over time. Pioneer is able to genericly display all proposals, so that we at least would not miss proposals that are in the chain, however, it cannot allow for creation of all proposal types. So one of the important must haves is full support for creation of all proposal types, but also, since different proposals have quite distinct semantics, custom display should also be developed by the designer, and implemented. We also know that this will be an ongoing activity, as the the number of proposals expected at mainnet will easily surpass 50.
  - https://github.com/Joystream/pioneer/issues/539#issuecomment-885056810
- **App-independent resource identifier:** https://github.com/Joystream/pioneer/issues/1091
- **1-Click deployment**: https://github.com/Joystream/pioneer/issues/1783
- **Tooltip Coverage:** https://github.com/Joystream/pioneer/issues/1784
- **Internationalisation:** https://github.com/Joystream/pioneer/issues/1786
- **Image Safety:** https://github.com/Joystream/joystream/issues/2835
- **Dynamic Fee UX:** https://github.com/Joystream/pioneer/issues/1553

### Design Backlog

There is a backlog of features which have been designed, but were kept out of `Olympia`. It's not obvious how to prioritize these, that requires more explicit planning and user input.

- **User Notifications:** https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=3600%3A73
- **Financials Dashboard:**
  - Brief: https://github.com/Joystream/pioneer/issues/46
  - Design: https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=4191%3A119416
- **Overview:** https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=4078%3A0
- **Bounties:**
  - Brife: https://github.com/Joystream/pioneer/issues/1302
  - Design: https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A109434
- **Constitution:** _could not find designs!_
- **Forum:** Here we are missing certain features, at least viewing and submitting threads with polls, but possibly more.
  - https://github.com/Joystream/pioneer/issues/1067#issuecomment-920129804
- **Working Group Lead Actions:** Currently it is not possible for working group leads to do any of their actions in Pioneer, like hiring and firing someone. All of these actions have to be done through the CLI.
  - https://github.com/Joystream/pioneer/issues/315#issuecomment-920140805

**Critically: A full review is needed of all of the designs and wireframes are needed, as it's certain that many points are likely missing from this list.**

### Enhancements

- **Responsive Design:** https://github.com/Joystream/pioneer/issues/1794
- **External member resources:** https://github.com/Joystream/joystream/issues/2813
- **Avatar images in storage system:** https://github.com/Joystream/pioneer/issues/54
- **Inline images and attachments for texts in storage system:** https://github.com/Joystream/pioneer/issues/55
- **New subsystems:** there are subsystems, such as for content, storage, distribution, forum, gateways, etc., where there is lots of domain specific information and actions that can be faciliated. For example, allowing the forum moderators to do their job in the forum section directly, not the CLI, or allow content curators to see a list of the most recent channels and videos created, do curation, etc. This will be very unique to each subsystem, and mapping out the opportunities here should be informed by problems workers are currently facing trying to do this job.
- **Calendar:** A community calendar for seeing what is going to happenin the future: https://github.com/Joystream/pioneer/issues/51

## Team 🧑‍💻

The team is currently in transition, so here I am only listing expected team members as of Q1 2022.

| Name  | Role  | Association  |
|---|---|---|
| Mateusz Augustynowicz   | Design Lead (DL)  | Elpassion  |
| Theophile Sandoz   | Front-End Engineer  | Jsgenesis  |
| Pawel Kuczynski   | Front-End Tech Lead (TL)  | 4Soft  |
| Michal Krupka | Front-End Engineer  | 4Soft  |
| Radoslaw Wyszynski | Front-End Engineer  | 4Soft  |
| Rafal Ploszka  | Front-End Engineer  | 4Soft  |
| Tomasz Stepien   | Front-End Engineer  | 4Soft  |
|  Szymon Madry  | Delivery Manager  | 4Soft  |
| Dmitry Meltsov  | Product Manager (PM) | Jsgenesis  |
| Bedeho Mender  | Product Owner (PO)  | Jsgenesis  |

## Communication

**Everyone on the team is supposed to be available on RocketChat on short notice during normal working hours.**

- `pioneer@RocketChat`: the primary communication general topic & coordination discussionc hannel, on Jsgenesis RocketChat.
- `pioneer-testing@Discord`: the community testing channel, on public Discord. Link [here](https://discord.com/channels/811216481340751934/910968995379822633)

**Comment by thesan** [comment]
@dmtrjsg I think this one can be closed now!
