### ISSUE TITLE
Display remaining proposal types' details in proposal preview

### ISSUE THREAD

**Issue by p-sad** [Joystream/pioneer#1835]
The importance of details to implement follows order in #1802

### Proposals to implement:
- [x] Signal proposal details
- [x] CancelWorkingGroupLeadOpeningProposalDetails
- [x] FillWorkingGroupLeadOpeningProposalDetails
- [x] TerminateWorkingGroupLeadProposalDetails
- [x] SetWorkingGroupLeadRewardProposalDetails
- [x] UpdateWorkingGroupBudgetProposalDetails
- [x] SetMaxValidatorCountProposalDetails
- [x] SetReferralCutProposalDetails
- [x] SetInitialInvitationCountProposalDetails
- [x] SetInitialInvitationBalanceProposalDetails
- [x] SetCouncilBudgetIncrementProposalDetails
- [x] SetCouncilorRewardProposalDetails
- [x] VetoProposalDetails
- [x] SetMembershipPriceProposalDetails

### Proposal to implement later:

Edit: Moved to: #2037

**Comment by jodator** [comment]
All required details were implemented. Other moved to #2037.
