### ISSUE TITLE
Proposal parameters designs

### ISSUE THREAD

**Issue by p-sad** [Joystream/pioneer#1864]
Edit. See [the comment below](https://github.com/Joystream/pioneer/issues/1864#issuecomment-985520636) for needed changes.
--
I've added params display to a couple of proposal types, but there were no designs for them, so I've fitted them with details that I *felt like* they should contain. The result may be different from what was originally in mind, so I'm screenshooting them all for the design team to check and say if there's anything missing. Also, I suppose some of the more generic labels could be improved if need be.

![image](https://user-images.githubusercontent.com/21345040/144059354-0c86c1cd-2cb7-4f08-b5e6-117ea3ff7a30.png)
![image](https://user-images.githubusercontent.com/21345040/144020638-35eddd81-a5b7-40c8-bade-01e378be716e.png)
![image](https://user-images.githubusercontent.com/21345040/144020900-734e0479-6638-4919-b767-2e3fab06b089.png)
![image](https://user-images.githubusercontent.com/21345040/144021123-69651558-ad15-49bb-8a6a-d7225e071e9a.png)
![image](https://user-images.githubusercontent.com/21345040/144059781-d752faa9-47bb-46ff-aa11-6e515a812ffd.png)
![image](https://user-images.githubusercontent.com/21345040/144022388-06140071-dc77-468b-8711-29a76bfb8f8d.png)
![image](https://user-images.githubusercontent.com/21345040/144025480-bb68d99d-c40c-4d72-a283-940b45f96cc8.png)
![image](https://user-images.githubusercontent.com/21345040/144025864-6b62ed5a-4708-462e-8032-bc5be6404f2f.png)
![image](https://user-images.githubusercontent.com/21345040/144026086-eb892119-54b0-4d6d-8ada-c4f04813f5f5.png)
![image](https://user-images.githubusercontent.com/21345040/144026254-6a2abd29-a560-4743-9398-4d451abbe712.png)
![image](https://user-images.githubusercontent.com/21345040/144026366-60b1bf1d-7335-4a83-84c0-1d3951ae6cf3.png)
![image](https://user-images.githubusercontent.com/21345040/144060002-b3c01ae2-7279-4d16-800b-61afa26d2785.png)
![image](https://user-images.githubusercontent.com/21345040/144026596-85621479-ee75-4a2f-859e-f1f1dd82d881.png)
![image](https://user-images.githubusercontent.com/21345040/144026683-bba07426-c35e-453e-b790-b08aeb485579.png)

**Comment by jodator** [comment]
After quick F2F talk with the design team:

*   [ ] Working group name should be uppercase
*   [ ] Veto should be left-aligned
