### ISSUE TITLE
Tooltip mechanism issue

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#1893]
During the transaction tooltip mechanism doesn’t work. While the user waiting for extension and try to move between tooltips (especially on my profile tab) tooltip doesn’t hide. 
![Screenshot 2021-12-06 at 15 53 12](https://user-images.githubusercontent.com/75029057/144868753-eb91c4d6-3235-4026-8b8c-fec826a8d4bb.png)

**Comment by WRadoslaw** [comment]
After some research found that it's prolly ([react issue](https://github.com/facebook/react/issues/18753)). Seems like disabled buttons do not emit onMouseLeave event, so tooltip doesn't know when to hide. Resolved in linked PR
