### ISSUE TITLE
Remaining Proposals

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#1909]
Epic to encapsulate all issues related to remaining proposals and follow up improvements. Details on proposals  Github milestone: https://github.com/Joystream/pioneer/issues/539#issuecomment-885056810

Amend constitution + misc small issues

Documentation:
https://joystream.gitbook.io/joystream-handbook/governance/proposals

**Comment by traumschule** [comment]
I am closing this although there are interesting ideas out there: #3199
