### ISSUE TITLE
User: Views all bounties

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#1927]
[Link to Figma >](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A119773)

- [x] #1950
- [x] #1952
- [x] #1948
- [x]  #1966

**Comment by jodator** [comment]
- [ ] Add schema for Bounties
- [ ] Fetch bounties from the query-node
- [ ] Display a list of bounties on the page
- [ ] Setup Bounties page
