### ISSUE TITLE
Oracle selects winners

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#1938]
**Context** 

Oracle exercises Judgement

**✅  AC**

- [ ] Select  one winner
- [ ] Select[ multiple winners ](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=248%3A109434)
- [ ] Slash Worker -  slash amount is maximum value for given entry ⚠️ 
- [ ] Validation that all funds were distributed: Disabled button and a line of text. Message display style tbc (tooltip at the very least)
- [ ] Rationale should be ignored for now as it's not supported by runtime

**OOS:**
- [ ] #1937

**Comment by thesan** [comment]
@dmtrjsg the design of the judgement modal looks incompatible with the current runtime.

As it the `submitOracleJudgment` extrinsic always slashes 100% of the rejected entries stakes, and the oracle does not provide any rational.

Should the design change or is the runtime still developed ?

**Comment by dmtrjsg** [comment]
I believe this is an important feature to go into, so I am on the side of creating this change request and add to Runtime team backlog for bounties: https://github.com/Joystream/joystream/issues/3040

**Comment by dmtrjsg** [comment]
@WRadoslaw  

Updates for the open questions:

**1. Splitting odd number for even workers and vice versa -** Let's introduce the logic to_ credit the account of the first worker with an extra_ Joy. So for case of 2 workers and 9 Joys -> 5+4. In case of 10 joys for 3 workers 4+3+3 and so on.
**2. Adding additional workers containers -**  agreed to follow Figma pattern
**3. Validation of form fields** - place errors next to the form fields as opposed to CTA (button)
