### ISSUE TITLE
QN: Bounty mappings

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1955]
- [X] Store bounty on Creation
- [x] #2070
- [x] Register the `BountyCanceled` event
- [x] Register the `BountyVetoed` event
- [x] Store contributions
- [x] Update bounties following `BountyMaxFundingReached` events
- [x] Withdraw contributions
- [x] Withdraw Cherries
- [x] Terminate bounties
- [x] Store announced entries
- [x] Withdraw entries
- [x] Slash entries
- [x] Record the `WorkSubmitted` event
- [x] Update bounties and entries following judgments
- [x] Update bounties and entries following reward claims
- [ ] #2250

**Comment by dmtrjsg** [comment]
Closing, tests will be handled in the backlog
