### ISSUE TITLE
Bounty page components

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#1956]
- [x] #1972
- [x] #1973
- [x] #1974
- [x] #1975
- [x] #1976
- [x] #1959

**Comment by jodator** [comment]
Please edit the initial comment with a list of components to create.

**Comment by Qcza** [comment]
[] TopBar component
[] TilesSection component
[] Refactor of the ProgressBar component 
[] Description section (picture + desc)
[] SideBar section (contributors + periods)
