### ISSUE TITLE
Support Image Safety Features

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2001]
Accomodate https://github.com/Joystream/joystream/issues/2835, which will involve some unique display modes for content with such censoring, or just blockcing the content wholesale. The actual curation is done through CLI, at least on first pass, as described here https://github.com/Joystream/joystream/issues/2937.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201959046715869) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Lighter version was done in 
- #2936 

Adding the full version to backlog
