### ISSUE TITLE
Channel payout proposal

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2006]
**Context**

New runtime release enables channel owners to "receive" incentive payouts. All the details are covered in this brief
- https://github.com/Joystream/atlas/issues/1813#issue-1083054674

Here we attempt to describe how this works at a high level. It has two stages, a first stage where the council is acting - and setting the rewards, then a second stage where a channel owner is interested in cashing out the reward. 

#### The Council
This means that when the council passes a payout proposition, the following happens:

The members on the council come to an agreement, some how, about how much $JOY to credit to different channels. Based on this agreement a `payout document is compiled, encoded in JSON, which simply describes this. This document will reference _what each and every channel has earned in total after this evaluation period_, hence, it should _also include channels which did not earn anything additional in this period_, however, this is not a technical guarantee, but rather how the system ought to be used. 

The payout document is converted into a _payout payload_, using the Joystream CLI, which is a compact representation of all payout information for all creators, and critically, with a Merkle branch precomputed for each channel, for the benefit of the channel owner to use during cashout.

The Joystream CLI is also used to produce a small cryptographic digest, called a Merkle root, which will be stored in the state of the blockchain. _Until a new payout proposal is passed, it constitutes a binding commitment to how much all channels are owed._

The payout payload and merkle root are bundled together in a runtime proposal that the council has to pass, and it is only when this happens that the Merkle root is updated on-chain.

When the proposal has passed, the payout payload is uploaded to the storage bag of the council. This manifest is basically a large archive of points (a), (b), (c) for each channel, and also a special kind of proof, called a Merkle branch, where _this proof enables the channel owner to mint the given amount of $JOY to their channel account_. There is some special state in each channel which prevents the reuse of the same proof multiple times, basically by ensuring that if the channel has already cashed out after the date at which the proposal passed, then they can't do it again.
Its important to realise a few things about doing a cashout:

☝️ _If a channel owner was promised e.g. 10 in a given proposal, but did not cash it out, then _they could be promised any new value in the next one, say 5, and this would be a permanent loss without recourse. It is in other words at the discretion of the council to properly update what a channel is owed over time if the channel does not cash out._ This is largely a moot point in practice, because it is to begin with at the discretion of the council what to pay out in any proposal regardless, at least as a technical matter.

A cashout proposal does not need to address what all channels are owed, it can only cover a subset, or event be empty. For anyone not mentioned, this is equivalent to being owed 0. 

The funding of the $JOY comes out of the budget content directory working group budget, this means that a legitimate attempt to mint $JOY for a channel may fail for no other reason than it being out of funds. This would be quite bad budget management of the council, but it is possible. In this case, the channel owner is best served to just wait until the budget is automatically replenished, something that happens automatically at some known block in the future. Keep in mind that since the council budget is continuously being used, even if you check that there is sufficient amount left to fund an imminent cashout, it could still get exhausted in the small period of time between this check and when the transaction actually gets validated, and so one must be prepared to handle an error.

**Scope**

- [ ] #3073
- [ ] #3074
- [x] #3075
- [x] #3208

### Additional Information

Atlas Designs [can be viewed here](https://www.figma.com/file/c4TB1l0dcftQNlHtE3VDEl/Payouts?node-id=0%3A1)

### Depends on 

* https://github.com/Joystream/joystream/issues/2941
* https://github.com/Joystream/joystream/issues/2943

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202196108918869) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Councils views latest payouts
Council enters csv with mass payout (@dmtrjsg check ticket for bulk funds transfer)
