### ISSUE TITLE
Worker Claims Reward

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2022]
Winning worker claims reward

AC:
- [ ] [Claim reward action](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=319%3A145491)

**Comment by DevNikita16** [comment]
@jodator @Qcza I haven't succeeded to find any method to claim the reward in our api. Also don't see it in handbook extrinsics.
