### ISSUE TITLE
Support staggered rollout

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2025]
# Background
Is described here https://github.com/Joystream/joystream/issues/2948.

# Proposal
Parts of the app need to be disabled, in terms of actions that are available at any given time, and also parts of the app need information or empty states that indicate something about the stage and that things are not fully live yet.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201958995372682) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
We are going with the Maintenance screen instead as per team agreement: 
- #3636
