### ISSUE TITLE
Reverse membership lookup with external resources

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2032]
# Background

Often, I find someone on Discord or Github, and I may have seen them before on that platform, or their content indicates to me that they are quite involved in the project, however, I don't know who they are as a member. 

# Scope

There should be a way to do reverse lookups from such external platform handles, likely on the membership screen which already has handle based lookup.

# Dependencies

https://github.com/Joystream/pioneer/issues/1977

**Comment by MattAugustynowicz** [comment]
In this case, I think it is best if we could add a background with icons and the username/handle we are currently searching for just below our classic members' view. Of course, in order not to show everything at once, I would suggest showing a maximum of three platforms and a link that will show us all the platforms entered (up to 11, but this is a complete edge case that I doubt will happen. 

I assume that if we were using this search to find a user from discord, we would get one result after typing in their handle.

As for the order of these platforms, I propose to collect the data and display them starting with the most popular, the most frequently introduced by the community

[👉 Figma Link (this and the screen on the right)](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8639%3A271611)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/0a4cd411-6b64-4966-883c-b8e10b3e94ed)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/99bbe071-ace1-4293-b886-a9d40926ff20)

**Comment by dmtrjsg** [comment]
@bedeho, this looks solid to me, wdyt re your expectations on the visuals?

**Comment by bedeho** [comment]
1. I think, like in the Atlas case, any idea like this needs a QN based sanity check, I suspect something like this would be very hard. Its also very unclear how to rank different candidate members based on all these partial matches, with multiple matches even for the same member.
2. I don't think this is very functional. The main thing missing here, which is leading to a lot of display complexity, is that you are not capturing a key piece of information the user already knows: what domain does the handle belong to. If I am searching for _tom_, I already know for the purposes of this issue, whether this is their Joystream handle, matrix handle, Discord handle. By def. I know, because its a lookup based on some context. I think basically the search interaction needs to allow the user to specify what domain the handle comes from in some graceful way. Clearly

**Comment by MattAugustynowicz** [comment]
Then, let's add another dropdown with an input called "handle." As a default, we will show Discord as the place from where most people write to us. We can expand the list to see all external platforms as a user. When we select one of them, the "handle" field will become active, and we can search for the user we are looking for. 

This function will be on the same level as "roles" and "council member," which means that if you enter a membership in the main search field (at the top), the handle you are looking for will only match the main search. 

[👉 Figma Link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8859%3A315741)

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/95480823/165515434-86fa9093-d75f-442a-b31f-697875d8fccc.png">

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/95480823/165515504-5f66bde7-f8f7-4d2c-a810-719c63143a18.png">

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/95480823/165515537-635b9792-5e9b-4493-9fa6-1b9d6d65b0bf.png">

**Comment by bedeho** [comment]
# Relocate control

I think the control looks fine, but really this is not a filter, so it seems misplaced. Really you are controlling the meaning of the search term above, so seems like the logical location is something like directly next to the search bar, you could even integrate it if you wanted. Also, not all of the things you are searching by are actually handles, e.g. email. But most importantly, this this "search by" control has to be colocated with the search box, not the filters.


# Search box

I actually also think we should reconsider relocation the entire search bar, because its so easy to miss right now, despite it being the primary way a use would want interact with the members lists. It could be either left aligned under the members heading, or perhaps even centered on the screen, etc. I  know this change is slightly out of scope, but just mentioned it as it since my prior comment started talking about the search box being relevant.

**Comment by dmtrjsg** [comment]
**Relocate control**

Suggesting to integrate it, meaning as user types up and we autosuggest the matches, we indicate the medium with an icon.

**Search Box**

If the problem with discoverability I suggest to try and enhance the visuals around it, perhaps one to A/B test.

**Comment by bedeho** [comment]
> Suggesting to integrate it, meaning as user types up and we autosuggest the matches, we indicate the medium with an icon.

Its just a detail, not worth dwelling over, the point is just to make sure the user does not miss what default property they are searching on, and to invite easily changing this while doing the search in some way. The specifics can be solved in many different ways.

> If the problem with discoverability I suggest to try and enhance the visuals around it, perhaps one to A/B test.

That may also be sensible, for example making it bigger also, but basically its location is incongruent with its actual role, so that would not be the correct full solution.

**Comment by MattAugustynowicz** [comment]
The search bar should be placed right under the headline, in my opinion. So by reading this section, it will be the second thing the user will see. Based on the comments above, I propose to prepare something similar to [Dribbble](https://dribbble.com/search), for example. We search by memberships as a default, but we can easily change the search context to other handles or emails. 

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/95480823/166928978-7c88e8ae-baf4-4ec0-af4c-5dc298bf37d4.png">

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/95480823/166929014-80c8172d-649d-4df1-bba2-2a2f7a2b62b5.png">

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/95480823/166929055-1d2c492e-ee66-4070-be8e-0b5cdf66d2d8.png">

**Comment by bedeho** [comment]
Looks good!

**Comment by MattAugustynowicz** [comment]
The screens have been moved to our main page in Figma. Additionally, I shortened the dropdown and would like the selected item to appear in the middle of the roll. Of course, as @dmtrjsg rightly pointed out, we were missing an icon for clearing search results. Added 🙌

[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=2985%3A111662)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/5e5e69b4-8742-408d-ad0a-5e859c023027)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/7b35ca8e-e772-45f9-a69a-40b4676749db)

**Comment by dmtrjsg** [comment]
There's dependency on the QN PR 
- https://github.com/Joystream/joystream/pull/3862

**Comment by dmtrjsg** [comment]
Resources were mapped inside the membership details in the side bar ✅ 
Search by resource wasn't possible due to QN issue 🚫

**Comment by dmtrjsg** [comment]
⚠️ currently search not supported by Hydra but Theo will magic up a hacky Query 🤞

**Comment by bedeho** [comment]
>  currently search not supported by Hydra but Theo will magic up a hacky Query 

By not supported, do we just mean "it returns bad results", or something else?

**Comment by dmtrjsg** [comment]
The way I understand it is that this feature requires nested filtering which is still in the pipe, but @thesan pls correct me if I'm wrong and pls elaborate on this based on your best understanding.

**Comment by bedeho** [comment]
Intuitively that sounds wrong, we are just querying "give me all members where X handle is sort of equal to <string>", so you are just free text searching on a particular field of the `Membership` entity, but perhaps the representation chosen for this whole external resource thing has some indirection in it for some reason, that seems redundant though.

**Comment by dmtrjsg** [comment]
Env where Faucet and QN are updated with External Memberships: ihttps://54.172.204.195.nip.io/network/config.json

**Comment by dmtrjsg** [comment]
DIscussed and added:
1. Hide empty results form search results (e.g. if hyperlink is empty, don;t show this udner the members component)
2.  Add Search by Membership ID, Add by Account number. 
3. Icons for Membership ID and Account to be added.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/members
wss://44.201.112.198.nip.io/ws-rpc

### Accounts
<img width="548" alt="Снимок экрана 2022-10-07 в 14 45 15" src="https://user-images.githubusercontent.com/46903215/194546370-65a94018-37d8-4b5f-ab09-bfe1ac34e845.png">
<img width="545" alt="Снимок экрана 2022-10-07 в 14 59 58" src="https://user-images.githubusercontent.com/46903215/194548224-ea3ad6b6-9e82-4100-964d-874064e82f85.png">

### Searching results

<img width="1201" alt="Снимок экрана 2022-10-07 в 14 50 55" src="https://user-images.githubusercontent.com/46903215/194546656-8d14a811-a8bb-4be7-ae19-919a680621fc.png">


<img width="1201" alt="Снимок экрана 2022-10-07 в 14 51 46" src="https://user-images.githubusercontent.com/46903215/194546803-04776c6b-3bfe-4950-ac09-174987a3e2d4.png">


<img width="1189" alt="Снимок экрана 2022-10-07 в 15 01 32" src="https://user-images.githubusercontent.com/46903215/194548907-a833758e-8907-4123-a56d-c461e7cdb4a1.png">


<img width="1199" alt="Снимок экрана 2022-10-07 в 14 54 56" src="https://user-images.githubusercontent.com/46903215/194547463-8f3be0c2-8e2a-42c7-9017-26a78539128c.png">


<img width="1191" alt="Снимок экрана 2022-10-07 в 15 04 53" src="https://user-images.githubusercontent.com/46903215/194549507-a5c4d512-ae17-4794-9210-19fe6999958c.png">
