### ISSUE TITLE
Implement metadata support for create_bounty extrinsic

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#2035]
Blocked by: Joystream/joystream#2961, ATM the runtime does not accept metadata. Also, the bounty metadata are not defined yet. So it should be tracked as well.

**Comment by jodator** [comment]
@Qcza It seems that this is not blocking: [https://github.com/Joystream/joystream/issues/2961#issuecomment-1001570297](https://github.com/Joystream/joystream/issues/2961#issuecomment-1001570297)

The API should accept `metadata` as second param of `create_bounty`.

**Comment by dmtrjsg** [comment]
Confirmed by @Qcza this can be closed, as not a blocker and already implemented.
