### ISSUE TITLE
Internationalisation testing on Bounties list page

### ISSUE THREAD

**Issue by Qcza** [Joystream/pioneer#2067]
Here we will conduct manual testing based on the provided translations by @dmtrjsg 

- [x] Pawel to share a dictionary to translate
- [x] Dmitry to populate the list
- [x] Pawel to upload
- [x] Dmitry to test

**Comment by Qcza** [comment]
@dmtrjsg here is `.csv` dictionary to translate
[bounty.csv](https://github.com/Joystream/pioneer/files/7933057/bounty.csv)

**Comment by dmtrjsg** [comment]
[bounty_Rus.csv](https://github.com/Joystream/pioneer/files/7934890/bounty_Rus.csv)
@Qcza  done ✅
