### ISSUE TITLE
Add slashing amount to the bounty schema

### ISSUE THREAD

**Issue by Qcza** [Joystream/pioneer#2072]

**Comment by dmtrjsg** [comment]
Added dependency on riuntime.

**Comment by dmtrjsg** [comment]
Slashing is always in full amount on runtime. So I think this can be now closed? @Qcza

**Comment by dmtrjsg** [comment]
Based on conversation with Bedeho it was confirmed that runtime does not support custom slashing amount and it will always be equal to max amount.
