### ISSUE TITLE
Fix on BountyListItem.tsx

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/pioneer#2084]
![image.png](https://images.zenhubusercontent.com/61b33b1e8ddbc86c62bdcd28/54855e9f-ba39-4c2a-a7ac-a8bc73a923c0)

Expired stage seems not follow the designs.

List item at this stage should look like this
![image](https://user-images.githubusercontent.com/92513933/149514915-d6e01fb7-a42f-4a6f-ae54-445028e756ae.png)

Additionaly when Council is bounty creator/oracle, the QN returns `null` and it needs to be handled by UI. For now it displays empty space. In other component it's handled by simply in case of `null` inserting `Council` label.

**Comment by dmtrjsg** [comment]
1. @WRadoslaw  pls elaborate on what is meant by "expired stage seems not to work"
2. Council can create/fund/ withdraw funds only via proposal mechanics. This is yet to be added to the runtime (not supported rn). [Ticket in joystream repo>](https://github.com/Joystream/joystream/issues/3028)

**Comment by dmtrjsg** [comment]
@WRadoslaw we agreed to leave Council scenarios out of scope for now, before council support is added to Runtime (link above) and QN  (to be created later).
