### ISSUE TITLE
Applying to openings fails

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2095]
When I create an opening with `yarn workspace ui run node-mocks opening:create`, The applications always fail at the 2nd step (`members.StakingAccountConfirmed`) with: `membershipWorkingGroup.InvalidStakingAccountForMember`

~~(Maybe it's just an issue with the mocking commands but it's worth checking).~~

I think the best way to reproduce this is on a local node is:
1. Create the mocked and well known membership with `yarn workspace ui node-mocks members:create`
2. Create the opening with `yarn workspace ui node-mocks opening:create`
3. Create a membership manually and apply to the opening

**Comment by dmtrjsg** [comment]
Seems like staking candidate transaction part is missing (part 1) @thesan  will point the link to the handbook

**Comment by dmtrjsg** [comment]
#2285 may be the _"why"_ of this issue. Linking up to be addressed together.
