### ISSUE TITLE
Fix the Membership Creation Flow for users with empty wallets

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2112]
![Screenshot 2022-01-20 at 15.18.11.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/ed2b5638-9bf1-478a-b1bf-e452f0b1664a)

:question: is this dependent on the Faucet?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710118645535) by [Unito](https://www.unito.io)

**Comment by thesan** [comment]
This probably depends on https://github.com/Joystream/membership-faucet/pull/8. I will look into this PR and the [Joystream/membership-faucet](https://github.com/Joystream/membership-faucet) as a whole later this week.
