### ISSUE TITLE
Forum posts deletion transction fails

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2138]
In [/forum/thread/1](https://pioneer-2-git-feature-bounty-page-components-joystream.vercel.app/#/forum/thread/1)

Deleting the post (id = 1) results in failed transaction:
![Clipboard - 24 stycznia 2022 16!UNITO-UNDERSCORE!50](https://user-images.githubusercontent.com/6571453/150824048-25b3f859-c403-4315-a2ea-493fef914867.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710119644611) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Creating the type that Pioneer has to deliver to Runtime on the creation is failing and losing all the values.  After creation postId and all other attributes reset to 0.
