### ISSUE TITLE
Deleting Forum thread created by member

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2139]
This should work similarly as the design on the moderator section [@figma](https://www.figma.com/file/xP9qdHWamHvV60fm0vvbOz/Forum?node-id=315%3A56824)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201710119872256) by [Unito](https://www.unito.io)

- [ ]  Let's add a bin icon  - link to Figma added in comments
- [ ] Let's re-use the delete post transaction modal
- [ ] Let's try and reuse "global" sign transaction modal component from "bounties module"

**Comment by dmtrjsg** [comment]
This needs to be designed to have the option to be deleted

**Comment by dmtrjsg** [comment]
If we need an icon we can check here > https://thenounproject.com/browse/collection-icon/garbage-trash-bin-waste-delete-61473/?p=1

**Comment by dmtrjsg** [comment]
@MattAugustynowicz  we need an icon for the bin asap :) to delete the forum thread. We are using a placeholder rn. Can we pls prioritise it.

**Comment by MattAugustynowicz** [comment]
@dmtrjsg We have this icon riiight here 👉 [Figma link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1405%3A77095)
<img width="992" alt="image" src="https://user-images.githubusercontent.com/95480823/155102003-9220a8ab-d522-452d-b5cf-6916ff176742.png">

**Comment by dmtrjsg** [comment]
@RafalPloszka moving back to in progress for the icon update only.
