### ISSUE TITLE
Copy button doesn't work as expected 

### ISSUE THREAD

**Issue by CrNeppos** [Joystream/pioneer#2145]
Path: Pioneer -> Toolbox -> Sign message tab

Problem: Copy button doesn't copy hash 

![image](https://user-images.githubusercontent.com/63144564/151122377-fa7dc0bc-60e9-4902-a48c-98318891d5ff.png)

**Comment by dmtrjsg** [comment]
@CrNeppos  thanks for raising this issue! We are currently working on the release of Pioneer v2, so all our team efforts are focussed on the new version rollout. Closing this bug in lieu of approaching new version release.
