### ISSUE TITLE
Reconcile Pioneer with final Olympia query node changes

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2146]
This ticket is to prepare Pioneer for the QN changes listed below which will be done by @ ondratra 

Re https://github.com/Joystream/joystream/issues/2657 > this is the only critical point here.
Lat two points - not critical for Olympia release, but great to be done.

* [ ] https://github.com/Joystream/joystream/issues/3095 ⚫ 
* [ ] https://github.com/Joystream/joystream/issues/2657 🟡 
* [ ] https://github.com/Joystream/joystream/issues/2608 🔴 
* [ ] https://github.com/Joystream/joystream/issues/2599 🟡 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201721605327239) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
We need to accommodate for the change not necessarily build features on top of it before the release. @thesan  to be discussed

**Comment by dmtrjsg** [comment]
Lat two points - not critical for Olympia release, but great to be done. 

Re https://github.com/Joystream/joystream/issues/2657 > this is the only critical point here.

**Comment by dmtrjsg** [comment]
Closing this issue as most of the child issues are done, the only one remains is sorting forum posts by relevance, which is blocked by Hydra and already added to QN board / backlog.
