### ISSUE TITLE
Point to customs query node network from the settings

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2167]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201742930737719) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
This would be very valuable indeed, especially when we have potentially more than testnet and playground.
Given that there are also many variables to configure maybe we can consider feature where user can paste in a .json or text file with all the variables. 

To also not require to keep modifying the custom endpoint, maybe the settings page can allow user to add and delete multiple custom configs.

Another approach could be to support passing a URL in the query path to a .json file containing the setting. eg:

`https://pioneer.joystream.org/#?networkSettings=https://myplayground.joystream.org/config.json`

The old pioneer v1 had support for this approach to pass the rpc endpoint.

**Comment by dmtrjsg** [comment]
@dmtrjsg  to open an issue to add network and qn urls selection to settings (drop downs)
