### ISSUE TITLE
The "See My Proposal" buttons doesn't work

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2188]
When clicking it, it fails with:

```
Uncaught TypeError: Expected "id" to be defined
```

![Screenshot from 2022-02-02 19-46-54](https://user-images.githubusercontent.com/6571453/152218130-9644daa2-5245-4ea4-9d3a-14a7ce8cf6c6.png)

Although it might be because without an elected council proposals get rejected.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201759663880096) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Reestimating based on the group discussion!

**Comment by dmtrjsg** [comment]
Proposal gets auto-rejected when council is not in place. When it is auto-rejected it gets placed to past proposals hence the link breaks.
