### ISSUE TITLE
Rationale on Oracle judgement

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2203]
## Context

ℹ️  This is a qa-task, meaning requires to be tested on staging environment on the test network. 
use this URL to get to the right place> `https://dao-git-staging-joystream.vercel.app/#/overview?network-config=https://3.95.67.177.nip.io/network/config.json`

This bug was potentially fixed by the other task, but we need to ascertain it, meaning test how Oracle judgment is displayed to the workers (in context of checking the outcome of bounty.
## Scope
Capture how oracle judgement is displayed to workers in the following scenarios:

- won
- lost
- slashed 
- judgement expired

## Actual

Submit judgement extrinsic has empty rationale field

## Expected

- Oracle submits judgement extrinsic has rationale
- Oracle judgement is displayed to winners and losers in the side bar component (see screenshots and Figma link below)
⚠️  NB: Oracle rationale is a single input, shown to ALL bounty actors in Withdrawal period stage.

[Link to Figma >](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=7120%3A234537)

<img width="276" alt="Screenshot 2022-04-05 at 12 17 11" src="https://user-images.githubusercontent.com/93924525/161742664-0111f306-4820-487e-b31d-93e1a1ab9c11.png">
<img width="306" alt="Screenshot 2022-04-05 at 12 17 14" src="https://user-images.githubusercontent.com/93924525/161742666-30066ab6-a48b-4c00-8e76-d207e59dc8f1.png">

F

<img width="351" alt="Screenshot 2022-04-05 at 12 17 07" src="https://user-images.githubusercontent.com/93924525/161742659-bf4d6666-3240-43ff-b112-dbc0fba6149d.png">

**Comment by dmtrjsg** [comment]
Rationale submitted for full judgement. We show it for all workers in the outcomes window.

**Comment by dmtrjsg** [comment]
⚠️  Blocked 

- [ ] cannot select winner
https://www.loom.com/share/7c4ab05603f5426282928283ee36a6ef

**Comment by WRadoslaw** [comment]
> ⚠️ Blocked
> 
> * [ ]  cannot select winner
>   https://www.loom.com/share/7c4ab05603f5426282928283ee36a6ef

Problem in here is that on select we fetch only 10 members to display, but they are filtered away as none of them is worker. So if you would type first part on worker member handle it would pop up.

**Comment by dmtrjsg** [comment]
Needs to be re-tested.

**Comment by polikosi** [comment]
does not match templates with figma. 

Oracle judgement isn't displayed to winners and losers in the side bar component.

Participants who have been slashed are not displayed in the sidebar component in the "entrants" field.

https://user-images.githubusercontent.com/80429191/167880750-65db4fce-32b8-4470-bf5f-1179a8c9106a.mp4

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:

1. won
![winner](https://user-images.githubusercontent.com/80429191/168085106-06bcd590-09a8-456a-a685-7bf36b71cc79.png)

2. lost
![lost](https://user-images.githubusercontent.com/80429191/168085138-28254e48-271f-4810-90d9-c789175a2acf.png)

3. slashed
![slash](https://user-images.githubusercontent.com/80429191/168085154-364bb843-c0a5-4f3c-a87a-e084f926b633.png)

4. When judgement expired all workers were slashed
![expired](https://user-images.githubusercontent.com/80429191/168088314-41f7c55f-5087-4279-be95-99cc8eb8eac6.png)
