### ISSUE TITLE
Use global component for sign transaction modals

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2204]
## Context
Sign transaction modals are custom built for each flow.

We do have a version of global sign transaction component used for Bounties withdrawal (:warning:  clarify). 

## Scope
Refactor all sign transaction components to be using same component with states and variations as opposed to separate ones.

Use cases  / Variants:

* [ ] Create new membership transaction modal has creation fee in addition to transaction fee
* [ ] Multiple step transaction component with account binding (3 steps)
* [ ] Multiple step transaction component without account binding (2 steps)

NB: there will need to be the balance for Tx fees and there might be diff balance for Staking.

Out of scope: ⛔ 
* [ ] Bounty withdrawal model with cherry applied #2341 
* [ ] We will not be using generic component for the multi step transactions / flows like Proposals.

## QA

ℹ️ 
- [ ] Complete transaction for creating new membership (from new account, and from existing accounts)
- [ ] Create proposal with new account (so it gets binded to membership in a multi-step tx)
- [ ] Create proposal for an account that is bound
- [ ] Create election candidate with new account (so it gets binded to membership in a multi-step tx)
- [ ] Create election candidate with account that is already bound (you can re-use account from step 2 here)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203149321268939) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Thank you for the input, sending to design backlog to be addressed next week. 

cc @toiletgranny

**Comment by dmtrjsg** [comment]
## Research

#### Mapping the modals

1. Transfer

<img width="614" alt="Screenshot 2022-09-21 at 10 22 06" src="https://user-images.githubusercontent.com/93924525/191484409-39d65e00-756f-4ac2-abd9-f732170ec173.png">


2. Council Candidate

3. Recover Lock

<img width="656" alt="Screenshot 2022-09-21 at 10 17 38" src="https://user-images.githubusercontent.com/93924525/191484394-efab5821-a623-441e-bea8-9a88ba82b12e.png">


4. Create Proposal

5. Apply to role

6. Create Membership

**Comment by dmtrjsg** [comment]
Parking the broader problem of UX optimisation here till later time.. for now agreed to

1. Remove chevron selector from accounts in all modals. Show account as not greyed out. 
2. Keep the account selector on the create membership modal
3. Show total balance instead of transferable balance on all accounts signing modals. This will help avoid extra explanation that Invitation balance is used for TX fees.
4. Fix membership display on create proposal flow (bug).

the rest of the suggestions will be considered based on user feedback after mainnet.

**Comment by dmtrjsg** [comment]
## QA

- [ ] Complete transaction for creating new membership (from new account, and from existing accounts)
- [ ] Create proposal with new account (so it gets binded to membership in a multi-step tx)
- [ ] Create proposal for an account that is bound
- [ ] Create election candidate with new account (so it gets binded to membership in a multi-step tx)
- [ ] Create election candidate with account that is already bound (you can re-use account from step 2 here)

**Comment by polikosi** [comment]
**Creating new membership from new account**
![image](https://user-images.githubusercontent.com/80429191/196241328-e45fb55f-6734-42a9-82e4-6922c0a80690.png)
![image](https://user-images.githubusercontent.com/80429191/196241449-1ff83cba-d46b-4b9a-8bb4-5ac9dd0ba237.png)


**Creating new membership from existing account**
![image](https://user-images.githubusercontent.com/80429191/196235984-c7bdabd7-497d-4733-af18-1d12cfb48fe2.png)

 **Create proposal with new account**

-  Bind acc
![image](https://user-images.githubusercontent.com/80429191/196237657-4fddfcac-58a1-4d16-bff9-cc6b727b436e.png)
- Create proposal
![image](https://user-images.githubusercontent.com/80429191/196237844-d99ab3cc-447e-40cf-bc12-5134fb1dc6b6.png)

**Create proposal for an account that is bound**
![image](https://user-images.githubusercontent.com/80429191/196239531-f53d8e74-cd4a-40e5-9ea5-8f77ca6c9b23.png)

**Create election candidate with new account**
-  Bind acc
![image](https://user-images.githubusercontent.com/80429191/196243750-5d6029f0-6c8b-4e26-8b76-0d23ca689426.png)

- Announce candidacy
![image](https://user-images.githubusercontent.com/80429191/196243876-a4b6834a-0d54-4fed-a12d-5f1471bad7ca.png)

- Set candidacy note
![image](https://user-images.githubusercontent.com/80429191/196244065-21618105-06eb-4181-98f3-4a723c0ba64a.png)


**Create election candidate with account that is already bound**
- Announce candidacy
![image](https://user-images.githubusercontent.com/80429191/196240148-0e038785-2f43-419d-b5f6-181e32b13669.png)

- Set candidacy note
![image](https://user-images.githubusercontent.com/80429191/196240283-6c646e70-cc81-4fbf-ba30-7c37e68c10ff.png)
