### ISSUE TITLE
Create bounty: transaction fails

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2217]
#### Details: :link: environment [ Link> ](https://pioneer-2-bounties.vercel.app/#/bounty/current)

![Screenshot 2022-02-11 at 15.10.37.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/0cd8aa8d-0ab0-4d9c-99e3-e040b7899046)

**Comment by dmtrjsg** [comment]
- potentially problem is with metadata sent bypassing ProtoBuff, need to go via pb.

**Comment by WRadoslaw** [comment]
For now thread will be hard coded to allow further testing of bounty tab. #2225 is responsible to fix that later
