### ISSUE TITLE
Expand drop downs on full panel click 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2220]
Currently user needs to click to teh downward pointing chevron to expand Member application in the sliding panel

![Screenshot 2022-02-11 at 17.17.15.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/915cc820-964d-4b0b-90a7-c348d0caba43)

Same applies for  list cards to details page:
- [ ] Openings
- [ ] Proposals
- [ ] Bounties

**Comment by ytdbuolf** [comment]
Will accept this for fixing

**Comment by ytdbuolf** [comment]
Issue has been resolved

**Comment by ivanturlakov** [comment]
Tested on staging

The panel still opens when you click on the chevron

Openings

https://user-images.githubusercontent.com/46903215/174994876-8c19faa9-c0c4-43e8-ade6-51d61d6dd3f4.mov


Proposals

https://user-images.githubusercontent.com/46903215/174994914-50e3ef83-57e8-427a-8974-aff228dd5935.mov


Bounty

https://user-images.githubusercontent.com/46903215/174994921-1b133ae4-25a7-4a33-ba96-cd8ae8c34651.mov

**Comment by oleksanderkorn** [comment]
Hey maybe it was not deployed to staging? 
Because on my branch pr deployment it works fine:
https://dao-git-fork-oleksanderkorn-bugfix-2220-joystream.vercel.app/#/proposals/preview/310

**Comment by ivanturlakov** [comment]
@oleksanderkorn yes, indeed

Retested on https://pioneer-2.vercel.app/

Dropdown expand on full panel click

https://user-images.githubusercontent.com/46903215/175259986-5189a52d-463a-48c6-9137-5f2661fe8e17.mov


https://user-images.githubusercontent.com/46903215/175260008-e221317c-ad4f-4a58-b80c-f6aef18a2a03.mov


https://user-images.githubusercontent.com/46903215/175260023-f5c880b7-b771-43f3-bffe-0ca5bce8559d.mov
