### ISSUE TITLE
Jumping background page on application details tab 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2221]
Proposals Preview: Jumping background page on application details tab 

https://www.loom.com/share/258bb9fdc1b943f6aacb74462b69734b

![Screenshot 2022-02-11 at 17.22.17.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/56db659b-269e-474f-a828-fb17a74c4188)

**Comment by talentdev0807** [comment]
Could you check again?
I can't see this kind of bug anymore

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/2
wss://44.201.112.198.nip.io/ws-rpc

It looks like this bug has been fixed


https://user-images.githubusercontent.com/46903215/195567401-9fdba46f-f6b1-4626-b50d-4081e5249830.mov

**Comment by traumschule** [comment]
Thanks!
