### ISSUE TITLE
"INVITED" count on `MyMember` is not implemented

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2227]
The ["INVITED" count on the `MyMember` component](https://github.com/Joystream/pioneer/blob/0f194334db6ceed57d710dbb4587de1767f54837/packages/ui/src/memberships/components/MemberListItem/MyMember.tsx#L48) is still missing

_Originally posted by thesan in https://github.com/Joystream/pioneer/issues/2226#issuecomment-1039246559_

Invited:

![](https://user-images.githubusercontent.com/93924525/154665772-31c412fe-4a37-47ee-97db-67892e331c85.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201871804688104) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
+ invitations do not decrease on the chain (supposedly).
