### ISSUE TITLE
Council does not show members in announcing stage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2246]
**TO-DO**
- [ ] Check in during announcing period the widget shows the cards with _Candidates_ (as opposed to council members)

**Mockups:**

![Screenshot 2022-02-17 at 17.32.20.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/150f0e20-651b-4fd5-9195-247032db0a7c)

**Test Env**

![Screenshot 2022-02-17 at 17.32.14.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/1e6b588d-5e45-42ea-8fff-fefdf318e50c)

**Comment by dmtrjsg** [comment]
just tested on prod:


<img width="749" alt="Screenshot 2022-03-31 at 21 33 15" src="https://user-images.githubusercontent.com/93924525/161144488-bee7699c-986a-4007-936c-cb2fb6065a29.png">

Seems to have been addressed with QN fixes. Closing

**Comment by singulart** [comment]
Tested on Prod during Announcement stage <img width="782" alt="Screenshot 2022-04-14 at 11 58 24" src="https://user-images.githubusercontent.com/7863785/163351131-4f35fce4-7fc0-4f1a-99ab-835bb6eba766.png">
