### ISSUE TITLE
Bug: infinite "loading network endpoints" if old endpoint is down

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2265]
I did very early testing on `olympia` and accessed it via https://olympia-staging-a.joystream.app/

The testing relaunched on what is a new network and I got the following when loading:
![image](https://user-images.githubusercontent.com/50830161/154797408-0d513687-b087-45a4-be83-357e9c6a4222.png)

Refreshing didn't fix it, but clearing cookies did.

**Comment by bwhm** [comment]
This was a user-error (mine).
