### ISSUE TITLE
Show endpoint technical information

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2267]
Currently the `settings` page only shows the following:
![image](https://user-images.githubusercontent.com/50830161/154797706-8d24de09-5f1c-4249-bb8f-caf4a309bb59.png)

This isn't sufficient information for various reasons and without knowing what actual endpoint someone is connected to, it can create confusion, make troubleshooting and helping users difficult and result in users having different states shown with no way of easily identifying why.

It should ideally show the URL of the currently connected endpoint (regardless of what a user chooses in the `select network` page, for example:
![image](https://user-images.githubusercontent.com/50830161/154797836-0a3fd44b-c366-481b-a80d-bcada7d0153a.png)

Also to consider is when a user does `select network` they may be put through load balancers or multiple endpoints, if a specific endpoint is having problems it needs to be identified more easily. This is the current case on our live testnet, a community run endpoint actually links to 10-20 different servers and ocassionally some of them are not sync'd properly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201858354198901) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
As we've experience, it can be a nuisance when testing, but shouldn't be an issue after launch.

**Comment by dmtrjsg** [comment]
Based on Martin's comment, the _failed endpoints_ are out of scope?

Since you'd like the faucet to be also displayed in the list, we'd need to go with the extended info panel showing the three endpoints. Will update the related ticket #2275 

Closing this ticket as duplicate.
