### ISSUE TITLE
Show blockheight somewhere

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2269]
In the previous design of Pioneer v1 as well as most Substrate projects the blockheight is shown at least somewhere. It is a very easy and quick way to show if you are on an endpoint that is synchronized.

This should either be shown in the settings page, or maybe in the top left corner of the page as it was in Pioneer v1. It needs to be accessible from somewhere

**Comment by bwhm** [comment]
Agreed!

**Comment by dmtrjsg** [comment]
https://github.com/Joystream/pioneer/issues/2342
