### ISSUE TITLE
Idea: Detect out of sync Query Node

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2270]
Query Nodes in particular seem to suffer from more problems than blockchain nodes. Even with increased reliability, if the QN has issues and a user isn't aware it can lead to expensive problems (such as submitting proposals or other transactions when it isn't needed)

It would seem like Pioneer should be able to detect the most recent blocks a query node has sync'd and issue a UI error or notification in the event the query node is out of sync with the blockchain.

**Comment by bwhm** [comment]
Hey,
I'll say that this is rather part of a much larger issue, which I will create afterwards, and link to :)

**Comment by dmtrjsg** [comment]
Captured in https://github.com/Joystream/pioneer/issues/2342
