### ISSUE TITLE
Design feedback: visibility of "Vote On Proposal"

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2273]
(btw I am creating a lot of issues! this is tomato from the testnet, I hope I am not being too critical! pioneer v2 is overall amazing! great, fantastic work on everything!)

When a council member views an individual proposal the only indication to vote is in the top right corner `Vote On Proposal`
![image](https://user-images.githubusercontent.com/50830161/154819173-cc4e240f-2e48-4ad5-bb13-c93a01845eae.png)

I would suggest that this is kept, but also a section maybe above the `Discussion` area shows the same button (or maybe even just above the proposal information)

**Comment by bwhm** [comment]
Hey @mochet :)
Without addressing whether you have a point or not, changing the design on this is wouldn't be in the cards for quite a while into the future...

@dmtrjsg

**Comment by dmtrjsg** [comment]
I also believe we shall address app features discoverability issues quite some time later. For now let's acknowledge there is future potential to improve some of the workflows and close this one for the time being.
