### ISSUE TITLE
Display Network and QN Ip address in the settings menu

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2275]
### Context

Pioneer app can be pointed to a particular network endpoint (which also includes Query Node as part of the landscape).
To help testing and reporting bugs we need to surface the network in the UI. 

Current view of settings:
<img width="1360" alt="Screenshot 2022-02-21 at 08 48 37" src="https://user-images.githubusercontent.com/93924525/154919910-db3ae7ca-c822-4c26-9ee3-76478ff127c1.png">

### To-do
- [x] Add Network, Query Node and Faucet Server ip addresses to the settings page. 
- [x] Create tabs structure on the network page (to accommodate for future extension w Notifications mgt)

#### Designs

[Link to Figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8187%3A231780)

**Comment by dmtrjsg** [comment]
Currently single drop down select defines both QN and Network so for each state of drop down we need to show an info panel (blue background one? with ℹ icon? and show

Network ip:
Query Node ip:

@MattAugustynowicz  fyi

**Comment by mnaamani** [comment]
It could also be worth showing the faucet url as well.

**Comment by MattAugustynowicz** [comment]
We decided with @dmtrjsg to show links directly under the network name, changing the component from a smaller dropdown, to a larger one with a description. This will make it easier to find the target network by IP without clicking on each network.

Design here 👉 [Figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8184%3A228274)

A few words regarding another version which we rejected here 👉 [Loom Video](https://www.loom.com/share/d47784a1bdfc4a5284bfcf35a03e63f8)

**Comment by dmtrjsg** [comment]
Based on comment in #2267 
"It should ideally show the URL of the currently connected endpoint (regardless of what a user chooses in the select network page, for example:" and "It could also be worth showing the faucet url as well." Does it make more sense to show a standalone info panel? @MattAugustynowicz

**Comment by MattAugustynowicz** [comment]
@dmtrjsg Definitely, in that case we should go with the first version (standalone info panel).
Can you drop me some examples of those url codes? I would like to see how long they are, how to fit them into our view and I'll throw up the finished views in a moment

**Comment by dmtrjsg** [comment]
Agreed, thanks for the quick turnaround! There's nothing too crazy there, so they will def fit to the real estate of this panel, so we can go with the version you've done already ✅ 🏁  

 Posting here just for ref.
<img width="430" alt="Screenshot 2022-02-21 at 16 53 23" src="https://user-images.githubusercontent.com/93924525/154998288-fe6e1a50-d1fe-471e-8eea-12dd27a38788.png">

Dev comment: @thesan let's use Facet Server IP instead of url as pre Mokhtar's suggestion.

**Comment by dmtrjsg** [comment]
Small bug here, need to show RPC endpoint in the top row where Network label is (now duplicates faucet)

Tested on [dmitry-pioneer.](https://dmitry-pioneer.vercel.app/#/settings)

<img width="708" alt="Screenshot 2022-03-02 at 16 17 27" src="https://user-images.githubusercontent.com/93924525/156402627-c58c4b3d-579b-4439-931d-03a7c6f6d2e2.png">

<img width="586" alt="Screenshot 2022-03-02 at 16 17 41" src="https://user-images.githubusercontent.com/93924525/156402637-c0b09bd6-f7ee-4d31-867f-9ba71b29374f.png">
