### ISSUE TITLE
Refreshing required.

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2277]
There's a recurring issue with having to refresh the page to get the latest state.
Not clear whether all aspects of this issue is important enough to warrant inclusion in `olympia` release, but it certainly should be rather high up on the post work if not. 

Here are some examples where it causes a pretty bad user experience, and other where it's just annoying:
1. When you, in pioneer:
   - apply to the council
   - apply on an opening
   - create a proposal
   - vote on a proposal (?)
   - vote on the council (?)
   - create a membership
   - post in proposal discussion #2222  (closing originating issue since captured here)
   - (probably) post on the forum
   - ...
You are shown a box as seen below:
![announced](https://user-images.githubusercontent.com/35237943/154949600-7671b904-cf2f-4166-a049-e5a0f2a66ffe.png)

However, you can't actually click any of these boxes as that would require a page refresh, which again would remove the button.
If you just click the box away, you also have to refresh to see something has "happened".

2. Even if you are not the person actually performing the action, the same issue applies. Unless you manually refresh your page (changing the tab is not sufficient) you will not know what has happened.

~3. Adding this for to #2270: Pioneer doesn't warn you when you are out of sync. Although it shouldn't manifest itself in any other way than 1. or 2. in most situations, some edge cases causes further issues. During testing, we "managed" to break the QN processor, and the only way to figure it out was to compare state with polkadot-js. Related use case is covered here, so perhaps worth doing together #2269~ 

~I won't try to come up with a permanent "fix", but a temporary one could be to add a warning whenever the `websocket_rpc` blockheight is way out of sync with the `graphql_server_websocket`. This would tell a user a refresh is needed, and could also imply the query node is down. Example:
`warning: the UI is currently `x` blocks behind. Try refreshing your browser window`~

Moved to Dedicated issue >

**Comment by bwhm** [comment]
Although not extremely closely connected, adding a reference to #2269 as well.

**Comment by dmtrjsg** [comment]
+ This one as they are related #2211 

The QN sync state and Block height are out of scope.

**Comment by dmtrjsg** [comment]
@bwhm suggested this approach (for some of the screens only):💡  "You can query the chain state for nextProposalId (or similar) to know whether you need to re-request data from the query-node. You don't need a transaction to finalize for that, so you have a "head start" of 6-12s..."  > looks interesting but complicates the codes quite substantiallly..

We discussed it on the morning standup, decided to start with trying to re-query the page after transaction complete.

Our current approach is: _tracking qn status and a hook for transactions so based on that we can fetch the status of proposals and etc.._

**Comment by dmtrjsg** [comment]
<img width="1008" alt="Screenshot 2022-03-10 at 19 23 10" src="https://user-images.githubusercontent.com/93924525/157739088-a1343d13-524c-4f9e-a669-7ca48b604a53.png">

Link to bounty is disabled

**Comment by dmtrjsg** [comment]
Same for proposals>
<img width="858" alt="Screenshot 2022-03-10 at 19 37 43" src="https://user-images.githubusercontent.com/93924525/157741420-ec0dd1c5-4e88-46d4-b1f7-de3b48b07868.png">

**Comment by dmtrjsg** [comment]
Bounty state (from contribute to submit work entry did not happen on its own, had to refresh the page), was this also not part of it?

**Comment by dmtrjsg** [comment]
So far:
Proposals
Bounties

**Comment by dmtrjsg** [comment]
- [ ] Add page refresh and new membership confirmation modal to the New membership creation"

See current versioN [[Loom Videoi]> ](https://www.loom.com/share/8004e137b6cc4ca19ebe96177d716d2e)

**Comment by chrlschwb** [comment]
While fixing issue 2466, I found that changing the function "memo" into "useMemo" with [opening] variable helped execute the code whenever the [opening] variable was changed.

**Comment by traumschule** [comment]
Nice. Saw `memo` too but didn't follow up why it was there.
