### ISSUE TITLE
Proposal Flow Hire WG Lead: Editing proposal title is broken

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2278]
Editing the proposal title. (Minor issue)

Loom [Video Capture of this issue is here > 📹  ](https://www.loom.com/share/3a81fde07732433c94462887c05e1f05)

Howto reproduce:
1. Type `My poposal Title`
2. Click next to, (or mark), the "p", or move back with arrow to edit.
3. Make your correction.

After one edit (eg. deleting the small "p"), the rest of your actions are added to the end. 
So if I want to delete the "p" and replace with "Pr", I get:
`My Poposal Titler` 
or 
`My oposal TitlePr`
Depending on the preferred way of editing :)

**Comment by ivanturlakov** [comment]
Verified on staging.
Proposal title input fixed.

https://user-images.githubusercontent.com/46903215/168128453-cf331e3c-a5fe-4266-85b1-cb8f57d470e4.mov
