### ISSUE TITLE
Update Working Group Icons

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2279]
## Context

Working group icons not implemented on Pioneer rn.

## Scope
- [ ] Rename Operations WGs:
> Alpha - Builders
> Beta - HR
> Gamma - Marketing

- [ ] Add icons to working groups. [Link to Figma > ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=199%3A1252)

Out of scope:
- [ ] #2581
- [ ] #2582
- [ ] Add working group descriptions based on 
>[ link to handbook ](https://joystream.gitbook.io/testnet-workspace/system/working-groups)@dmtrjsg 

Preview:
__________

![Screenshot 2022-02-21 at 11.09.45.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/da2e5728-1b9e-4050-a3b9-71021f9e7de7)

**Comment by stepien4soft** [comment]
it’s almost finished. To cover all cases we need additional 3 types of icons: check screen attached
![Screenshot 2022-03-17 at 14.30.26.png](https://images.zenhubusercontent.com/61b33e89f7b6fc759225d997/a6a2d518-7e25-49f4-9b09-fa36da3ddb11)

**Comment by dmtrjsg** [comment]
@stepien4soft 

Thanks, let's keep it on hold for now, and I will ask @MattAugustynowicz to try and prioritise #2582.
Re naming of the groups pls don't forget checkbox number 1 from description ;)
