### ISSUE TITLE
Create Working Group Lead Opening: Execution Constraints Validation

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2280]
Follows #2278

There are three checks of the inputs here, that are not validated on proposal creation, but on execution (ie. after approval).
1. `Staking amount >= 2000` ref #2272.
2. `Leaving unstaking period >43200`.
3. `Reward amount per Block> 0`.

The former two can be read as `constants` for each WG.
1. `leaderOpeningStake` (note that for regular Worker openings, not created in pioneer, it's `minimumApplicationStake`)
2. `minUnstakingPeriodLimit` (for both Leads and Workers
3. I don't think know if this applies to Workers, nor if it's a parameter. I think it's hardcoded.

Proposed solution:
WARN (if not block) users from creating proposals with values outside of these limits.

Note that more proposals has some of these issues. I'll add them elsewhere, as unlike those, this will likely be the first proposals needed for `olympia`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201859294266014) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
Also mentioned here #2223

**Comment by dmtrjsg** [comment]
@bwhm you're a 🌟 thank you for surfacing these up! Right on time for our work on > 
- #2242  (and this - https://github.com/Joystream/pioneer/issues/2263  is the issue, where each proposal is being unpacked so referencing this ticket there, but we will address is as priority)

**Comment by dmtrjsg** [comment]
"Exeuction constraint of {{asdasd}} is violated" on each input

**Comment by dmtrjsg** [comment]
@WRadoslaw  with additional feedback from Matt and Martin, I've drafted improved wording, updating one of the checks from >= to > and small update on positioning the checkbox. pls see comments in the PR> https://github.com/Joystream/pioneer/pull/2307

**Comment by dmtrjsg** [comment]
@WRadoslaw 

After some deliberation I think we need to reword the validation in favour of non-power users inviting them to enter smth that actually satisfies the constraint. I didn't catch it originally but after a few runs through the wf, it becomes pretty jarring. Let's change it here, also updating description on the epic level to inform other tickets.

**To-do** 
- [ ] Update validation copy "Enter value above {{Constraint value}} to satisfy proposal execution constraint" on both fields
