### ISSUE TITLE
Olympia: Hire Lead Flow - 3

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2284]
Follows #2278 and #2280 
Described in #2223 as well, but not fixed.

We are not at the stage where a user is applying for a (Lead) opening, that was successfully created following an approved proposal. Two issues:

1. I've applied for different (Lead and Worker) roles using both the membership `root/ctrl` account, and a "fresh" account, but regardless, pioneer injects `5C4hrfjw9DjXZTzV3MwzrrAr9P1MJhSrvWGWqi1eSuyUpnhM` as the `stake_parameter.staking_account`. As stated before, this implies a type error here, as it should pass whatever account you choose in the flow.
![Screen Shot 2022-02-21 at 14 01 28](https://user-images.githubusercontent.com/35237943/154960271-22731bcf-d8cd-4d53-a1a5-4ec36f05513d.png)
 
2. I'm not prompted to select a `role_account` nor a `reward_account`. You could argue the latter should default to the membership ctrl (or root) account, but a user should be warned against using the any of the membership accounts (or the `staking_account`) as the `role_account`. For a variety of reasons, these shouldn't be the same.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201859527124568) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@stepien4soft  point number 2️⃣

**Comment by bwhm** [comment]
I'll start with the short answer, then I'll get back to you after confirming the nuances works as I expect :)

Basically, the `role_account_id` and `reward_account_id` can be the same, but in practice, they probably shouldn't be. 
The `role_account_id` allows you to perform all Lead extrinsics, such as creating openings (for all WGs), and all the actions specific for that group.

The `reward_account_id` can be any account really, and is just collecting the rewards you earn for that specific role.

From what I can tell, pioneer will always set your `membership_controller` for both of them. That would mean if you have different roles, or be both the Lead, and one or more Workers in the same group, you'd use the same account to sign for all of them. AFAICT, this is allowed by the runtime, but would certainly allow for confusion.


**This isn't as urgent or important as point 1**, but I'd say that a user should at least be given the choice to set whatever accounts they want here. My thinking would be that for the `role_account_id`, you should be encouraged to choose another account than your `membership_controller`, and for your `reward_account_id` it could default to your `membership_controller`, but with an option to choose another account.

**Comment by stepien4soft** [comment]
I think we can add these improvements but it needs two additional selects. I’m not sure about it from a UX point of view. @dmtrjsg let me know WDYT

**Comment by dmtrjsg** [comment]
I'll have to think about it, since Martin says its less important that point1, let me wrap my head around it and I will re-introduce it back to dev. Assigning to myself now.

**Comment by dmtrjsg** [comment]
@dmtrjsg  to create a separate ticket to adress point 2.

**Comment by dmtrjsg** [comment]
Point 1 merged already , point 2 > moved to  2317
