### ISSUE TITLE
[USERSNAP] Proposal list view: Add Working Group Icons

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2288]
### Scope

- [ ] Add WG icons and names to proposals list where relevant
- [ ] iconography for other proposals tbc

_________________
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/5
**Fields**:
- Discrod Handle: tomato#9464
- Give us some details: The proposal should explain what WG this proposal is for.
- Houston, we have a problem.: WG lead opening proposal doesn&#39;t say what WG it is for
- The proposal should explain what WG this proposal is for.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4d5e3253-8fdc-4938-8505-2624cdf4edf8-annotated_b4f9f1ee-ddbf-417d-b15a-836a9f905b4e.png?etag=663af337136c6d31e6e898840bf5e91f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4d5e3253-8fdc-4938-8505-2624cdf4edf8-annotated_b4f9f1ee-ddbf-417d-b15a-836a9f905b4e.png?etag=663af337136c6d31e6e898840bf5e91f)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1540x994
**[Open #6 in Usersnap](https://app.usersnap.com/l/feedback/2720bf2d-f436-411c-a742-d818413157c1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
Showing which WG should also be on the past propopsals and current proposals pages:
https://pioneer-2.vercel.app/#/proposals/current
https://pioneer-2.vercel.app/#/proposals/past

**Comment by dmtrjsg** [comment]
This ticket is resolved here > 
- #2448
