### ISSUE TITLE
Editing Title in Proposals: Close Modal on click outside/ Disable Click and Drag

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2291]
## Context

Happens on Chrome and Firefox happens for every modal

## Scope

- [ ] Keep modal open if user clicked inside it and dragged cursor (with keypressed) outside of the modal
- [ ] Close modal only on click outside of modal or a cross button for:
--- council candidate
--- proposal
--- forum post / thread
--- opening application
--- proposal vote

- [ ] Make sure same applies to forum / proposal discussion and bounty discussion posts.
- [ ] Add modal on closing:

H1: Are you sure you want to close this modal?
H2: You have unsaved progress in the form, which will be lost.
Cancel / Close 

## Design:

Pls [use this modal for it](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=730%3A5923)

No avatar, only text.

_____________

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Discrod Handle: tomato#9464
- Give us some details: When clicking and dragging text, it sometimes happens the cursor goes out of bounds unintentionally. It currently feels far too strict and appears that even one pixel outside of the pop-in will close the window.
- Houston, we have a problem.: Out of bounds to close pop-in window is too strict
- - The red arrow indicates where a users mouse cursor might go while selecting text
- The yellow box is the area in which the window will close, it seems to be very strict
- The blue box is a suggestion of a larger box.

I don&#39;t know if this is technically possible, but it would be nice at some point since windows closing too easily (and losing work) can be frustrating.

Another suggestion might be to disable the pop-in from closing once text characters have been written in.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c8a68a6c-b690-45dc-97b5-80c6f4c496b0-annotated_8b64ad59-0c2b-4811-951d-8b748201857c.png?etag=9eb8f330b0f1eeb594135f73fedf1b3a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c8a68a6c-b690-45dc-97b5-80c6f4c496b0-annotated_8b64ad59-0c2b-4811-951d-8b748201857c.png?etag=9eb8f330b0f1eeb594135f73fedf1b3a)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 2758x1319
**[Open #7 in Usersnap](https://app.usersnap.com/l/feedback/672b267e-19d3-4600-ab85-343d3a067e21?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
For Matt to review, adding to design bl

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/current
wss://34.230.5.182.nip.io/ws-rpc

https://user-images.githubusercontent.com/46903215/204533985-6c9143a2-a3d7-4c94-945a-b454369a5b89.mov
