### ISSUE TITLE
[USERSNAP]Add proposal ID to proposal card

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2296]
## Scope

- [ ] Add proposal ID to the proposal card (list)
- [ ] Make proposal link easy to copy 
- [ ] Dev comment: When user pastes such iD (copied to buffer) to text box (like forum post) the markdown of proposal is identified and shown correctly
__________

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Discrod Handle: tomato#9464
- Give us some details: the number is an important unique identifier
- Houston, we have a problem.: Current Proposal view should include proposal number
- N/A

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0392b223-d755-452a-a28f-4f9b10f778ee-annotated_c1176b64-0d17-4e3c-b8be-1153866f4799.png?etag=9ec5fa7c8e98235182741d07bb14bed7)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0392b223-d755-452a-a28f-4f9b10f778ee-annotated_c1176b64-0d17-4e3c-b8be-1153866f4799.png?etag=9ec5fa7c8e98235182741d07bb14bed7)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 2022x1319
**[Open #11 in Usersnap](https://app.usersnap.com/l/feedback/06cb4dae-0490-4fc9-9dc3-36e8e7bc08f1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
❓ @mochet where would you normally paste the id/ link?

#50 and 
- #1091
solves some of this problem if proposal needs to be referenced in the chat

**Comment by dmtrjsg** [comment]
@mochet hey did you have a chance to see my question above? We are designing this ticket and need to clarify the use case..

**Comment by MattAugustynowicz** [comment]
Let's put the ID information at the very beginning before the date information, it will be analogous to what we have on working groups. If we want to copy a given proposal even faster, we can add a copy icon to its hover state. Thanks to this we will not have to enter the proposal directly to get the link.

[👉 Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8501%3A245609)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/b31432ba-f7c8-4bca-a7f5-1c2e001cdac8)

We should also add the ID information on the screen of the proposal itself, I propose in the same way to add it before the time information

[👉 Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8501%3A244028)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/4e441671-a500-4e24-b2a9-b90250b3f3e7)

**Comment by freakstatic** [comment]
@freakstatic
