### ISSUE TITLE
Add tooltips to staking in Election Flow: Announce - Vote 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2303]
## Context

Walkthrough of election flow conducted on https://dmitry-pioneer.vercel.app pointing to 3.95.67.177.nip.io

### Announce Candidacy

1. Select account for staking view

![Screenshot 2022-02-22 at 17.07.22.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/04b3dcbf-1e94-4d6d-90b3-a5cbd360031f)

- [ ] Add tooltip to first selector: "Accounts free from [rivalrous](https://joystream.gitbook.io/testnet-workspace/system/accounts-and-staking#locks-1) locks bound to current member required for staking.
[More details](https://joystream.gitbook.io/testnet-workspace/system/council#candidacy-1) > "

- [ ]Add Tooltip to second selector: "Select account for staking". Copy: "When losing an election, your candidacy lock is removed and your steak becomes immediately recoverable. If you win and get elected, your candidacy lock will be automatically removed, and a council specific lock will be applied, with the same amount locked. When that council is replaced, this lock is removed, if you did not get re-elected."

### Vote for Candidate

- [ ] Add tooltip to staking for the vote. Copy: "If someone voted for a candidate in an election, they will and can recover their stake at a later time. Importantly, a vote which was devoted to a losing candidate can be freed the moment the election cycle is over, while a vote which was devoted to a winner can only be freed after the announcing period of the next election begins. The idea behind this asymmetry is to more closely expose the winners to the consequences of their decision.

[More details](https://joystream.gitbook.io/testnet-workspace/system/council) >"

**Comment by dmtrjsg** [comment]
Removed this from teh ticket: - [ ] Vote Again CTA must be shown per member selected (now shows for all members for all wallets at the same time) ❓  Or not? :) 
<img width="455" alt="Screenshot 2022-02-23 at 16 09 26" src="https://user-images.githubusercontent.com/93924525/155359442-f63e6900-f8e8-4b0d-9f28-0bbb89f77e0d.png">

**Comment by singulart** [comment]
@traumschule Please pick this one

**Comment by singulart** [comment]
@traumschule any updates on this one?

**Comment by adovrodion** [comment]
Bounty link: https://dao.joystream.org/#/bounty/preview/43

**Comment by adovrodion** [comment]
Bounty link: https://dao.joystream.org/#/bounty/preview/61

**Comment by adovrodion** [comment]
Bounty link: https://dao.joystream.org/#/bounty/preview/90

**Comment by polikosi** [comment]
@dmtrjsg hi, where this tooltip should appear? Where is the first selector? Thanks)
 "Add tooltip to first selector: "Accounts free from [rivalrous](https://joystream.gitbook.io/testnet-workspace/system/accounts-and-staking#locks-1) locks bound to current member required for staking.
[More details](https://joystream.gitbook.io/testnet-workspace/system/council#candidacy-1) > ""

**Comment by dmtrjsg** [comment]
@polikosi thank you for your question, I should have been more clear -> here is the indication of the suggested positioning

<img width="639" alt="Screenshot 2022-07-25 at 16 09 53" src="https://user-images.githubusercontent.com/93924525/180812657-8a26c456-ada7-4e14-b9ea-23e062d40ab8.png">

**Comment by polikosi** [comment]
Verified on staging
Announce Candidacy:
![Screenshot_165](https://user-images.githubusercontent.com/80429191/180989017-d33d23f1-bbda-43d4-a0a0-e81a8cfd31ea.png)
Vote for Candidate:
![Screenshot_166](https://user-images.githubusercontent.com/80429191/180989250-4f45f6d5-b9ec-4741-9c1b-6db5a259c71b.png)
