### ISSUE TITLE
Filter Applications by Openings

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2308]
Related to: https://github.com/Joystream/pioneer/issues/2340

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Discrod Handle: -
- Give us some details: Given that I have chosen to create a proposal to hire a Lead for the Forum Working Group, I shouldn&#39;t be shown applicants for other Lead roles.
- Houston, we have a problem.: The candidates are not filtered by openings.
- Lack of filtering.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b9380daa-02af-4d3e-843f-bc979513cc32-annotated_fbc96cd3-ebab-43ec-b5bf-4505f0da8e3e.png?etag=819cbc38864a530e36e657804696dd3e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b9380daa-02af-4d3e-843f-bc979513cc32-annotated_fbc96cd3-ebab-43ec-b5bf-4505f0da8e3e.png?etag=819cbc38864a530e36e657804696dd3e)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2560x1304
**[Open #12 in Usersnap](https://app.usersnap.com/l/feedback/fea50570-773f-4039-91ad-9340e5030a93?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
On my screen, the arrows were pointing from the "Opening" selection to the "Applicant" selection.

**Comment by dmtrjsg** [comment]
Perhaps linked with - #2314
