### ISSUE TITLE
Opening card for Fill WGL Proposal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2309]
### Scope

- [ ] Update opening card based on mockups  [Figma >](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=199%3A3016)

<img width="445" alt="Screenshot 2022-03-04 at 15 33 45" src="https://user-images.githubusercontent.com/93924525/156792675-0516bd86-0f8b-4359-87d4-322a1142f387.png">

- [ ] Add padding for ID
- [ ] Add "lead" badge for WGL component variation

Out of scope ⛔ 

- [ ] Add reward 

> for Fill working group lead proposal

#### Usersnap ticket details

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Discrod Handle: -
- Give us some details: Show me something I can relate to.
- Houston, we have a problem.: This isn&#39;t a good way to distinguish the openings.
- -
- 
![Screen Shot 2022-02-23 at 15 07 26](https://user-images.githubusercontent.com/35237943/155335486-30095ac5-4c06-4a73-bd6d-fb8a10e65897.png)
*replaced*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2560x1304
**[Open #13 in Usersnap](https://app.usersnap.com/l/feedback/0c731d09-1a02-4d5a-9415-323630a771e7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
@gyroflaw can you have a look please

**Comment by gyroflaw** [comment]
Ok, I will take a look

**Comment by traumschule** [comment]
Just checked figma and wonder why it shows `LEAD` badge for all openings. Probably  safe to ignore.
![lead-badge](https://user-images.githubusercontent.com/31551045/206426422-160763e6-181f-43f4-bb0a-29fd4eb62806.png)

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/working-groups/openings

### ✅ Opening card
<img width="908" alt="Снимок экрана 2023-02-16 в 17 44 27" src="https://user-images.githubusercontent.com/46903215/219415805-8b288304-c625-4f44-9aaf-4e3a73cbd229.png">

### ⚠️ Fill WGL Proposal - ID wording
<img width="1257" alt="Снимок экрана 2023-02-16 в 17 17 23" src="https://user-images.githubusercontent.com/46903215/219415966-0d50de23-8b9a-48ac-9228-3422073e319f.png">
