### ISSUE TITLE
Caching and Polling Implementation For Pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2311]
## Context
The overall objective is to serve the most up to date state of the platform to users, while ensuring the app works fast and smooth. 

The objective of this task is to rollout a suitable caching and polling approach for the variety of pages, which do not involve a transaction flow.

* [x] Council Page
* [x] Bounty Preview
* [x] Openings Current and Upcoming
* [x] Current Candidates list
* [x] Proposal Page + discussions (preview)
* [x] Current Proposals list
* [x] Forum categories

Out of scope ⛔ :
* [x] ~Current Bounties list~ [deprecated]
* [ ] #3352
* [ ] ~Overview~

## Scope
* [ ] Create a hook to enable polling "useRefetchQueries" (already used in Bounty.tsx, packages/ui/src/app/pages/Council/Council.tsx and Election..)
* [x] Define the polling frequency for each -> Done here: https://github.com/Joystream/pioneer/pull/3221
* [ ] Implement caching and polling for all checkboxes that are in scope for this ticket

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202512541954625) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@ QA: Polling is set to 6 seconds (block time) - just check on each page that it is not flicking / trying to load every 6 seconds (like it is now on prod with council).

**Comment by polikosi** [comment]
Tested on staging. 
✅Council Page
✅Bounty Preview
🚫Openings Current - requests aren't sent
✅Openings Upcoming
✅Current Candidates list
🚫Proposal page + discussions (preview) - requests aren't sent
✅Current Proposals list
✅Forum categories

**Comment by singulart** [comment]
@dmtrjsg Failed in QA, please see outcome

**Comment by dmtrjsg** [comment]
We've triaged it with @WRadoslaw and identified the issue:

1. Proposals page was not done in this PR, so that was skipped (now refetches every second block, so 12 seconds on staging). We will also remove the refetch from past proposals discussion page.  On Carthage site, this worked fine. So once we merge Carthage this would be okay, if not we will re-raise it. 
2. Openings current - just checked on staging, and worked like a charm for us :) 

Based on these comments marking this as QA-passed for this release. Thank you for raising @singulart
