### ISSUE TITLE
Candidacy locks shows as recoverable but transaction fails

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2312]
⚠️ latest iteration:

- Evidence attached here was for unstaking _voting_ stake, while the BUGfix itself addressed _Candidacy lock recovery_.

**ℹ️  What and how to test:**

1️⃣ 
_Condition: Election period stage for council_
Create election candidate with Member1
Vote for this candidate to make it to council (by Member2 and additional members of council)

**As Member1 while in active council seat - recover council candidate stake button is not showing**
**As Member2 (while Member1 is in the council seat) - recover voting stake button is not showing**

2️⃣ 
_Condition: Normal Period stage for council, Member1 is active council member_
**As Member1 while in active council seat - recover council candidate stake button is not showing**
**As Member2 (while Member1 is in the council seat) - recover voting stake button is not showing**

3️⃣
Wait for council to end when Member1 is released from council seat and no longer a council Member.
_Condition: Election Period stage for council (next round)_
**- as Member1, after released from Council - check that candidate stake can be recovered via GUI button "Recover" and transaction can succeed**
**as Member2 - check that voting stake can be recovered via GUI button "Recover" and transaction can succeed**

## Scope

- [ ] Hide Recover candidacy Stake cta for candidates during active announcing voting and revealing periods.

- [ ] Display this lock as non-recoverable
>second point depends on  2300

## Problem
Current behavior. 

Council candidate shows as recoverable even though candidate is active.

https://www.loom.com/share/14cc5e6f90424e55821b195c8bc8ce98

**Comment by dmtrjsg** [comment]
Looks more global for all locks that can be recovered...

**Comment by singulart** [comment]
The bug is still reproducible. Reopening
<img width="1194" alt="Screenshot 2022-04-14 at 16 10 19" src="https://user-images.githubusercontent.com/7863785/163397785-f46e77be-59c4-43da-8eee-16de2ecf5add.png">

**Comment by singulart** [comment]
@traumschule please have a look at this

**Comment by dmtrjsg** [comment]
⚠️ latest iteration:

Evidence attached here was for unstaking voting stake, while the BUGfix itself addressed Candidacy lock recovery.
ℹ️ What and how to test:

1️⃣
Condition: Election period stage for council
Create election candidate with Member1
Vote for this candidate to make it to council (by Member2 and additional members of council)

As Member1 while in active council seat - recover council candidate stake button is not showing
As Member2 (while Member1 is in the council seat) - recover voting stake button is not showing

2️⃣
Condition: Normal Period stage for council, Member1 is active council member
As Member1 while in active council seat - recover council candidate stake button is not showing
As Member2 (while Member1 is in the council seat) - recover voting stake button is not showing

3️⃣
Wait for council to end when Member1 is released from council seat and no longer a council Member.
Condition: Election Period stage for council (next round)
- as Member1, after released from Council - check that candidate stake can be recovered via GUI button "Recover" and transaction can succeed
as Member2 - check that voting stake can be recovered via GUI button "Recover" and transaction can succeed

**Comment by RafalPloszka** [comment]
The reason is probably known and will be addressed here: https://github.com/Joystream/joystream/issues/3573#issuecomment-1121399203

**Comment by ivanturlakov** [comment]
Tested on staging.
Done - "Hide Recover candidacy Stake cta for candidates during active announcing voting and revealing periods."
Done - "Display this lock as non-recoverable"
<img width="1440" alt="Снимок экрана 2022-05-18 в 17 27 40" src="https://user-images.githubusercontent.com/46903215/169069211-f881da0b-31d3-4d72-9b4a-6f56e5f9966d.png">
<img width="1440" alt="Снимок экрана 2022-05-18 в 17 27 33" src="https://user-images.githubusercontent.com/46903215/169069245-41406a14-c5c8-4a76-8354-e233a4f61c81.png">

**Comment by dmtrjsg** [comment]
Closing for Pioneer and awaiting for runtime to deploy.
