### ISSUE TITLE
Apply to opening - ends in the past

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2313]
![Screenshot 2022-02-23 at 16.31.29.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/25426586-cc74-4ff6-b2fd-c98c2c1ec1e0)

**Comment by RafalPloszka** [comment]
+ fix hardcoded value:
`<Subscription>Time left: 6 days 23 minutes</Subscription>`
in `working-groups/components/ApplicationsList.tsx`
