### ISSUE TITLE
Role and Reward Accounts in Application flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2317]
## Context

In the current version of application to a role, user is not prompted to select a _**role_account**_ nor a _**reward_account**_. 

<img width="1017" alt="Screenshot 2022-03-10 at 10 08 25" src="https://user-images.githubusercontent.com/93924525/157639480-03543336-1ced-491b-96ff-eb93303b6dd5.png">

You could argue the latter should default to the membership ctrl (or root) account, but a user should be warned against using the any of the membership accounts (or the staking_account) as the role_account. For a variety of reasons, these shouldn't be the same.

## Scope

**Staking Account**

- [ ] Keep Select Staking account input in GUI.
--- Keep un-populated. Microcopy "Select account or paste account address"
--- Add Tooltip. "Staking account will bear the role-specific lock, meaning you will not be able to re-use this account for  purposes with rivalrous accounts, while the opening is active or you are in the role if your application is accepted.
Learn more> " [locks-1] @dmtrjsg to populate

Same validation as on proposals
1. Sufficient balance for staking > min stake
2. Role bound
3. No rivalrous locks..

**Role Account**

- [ ] Add to GUI.  
--Keep un-populated. Microcopy "Select a new or dedicated account or paste account address"
-- Add tooltip: "We strongly advise you to use a separate role-dedicated account for this application. Role account is used to perform all role-specific actions. This _should not_ be your Controller or Root account, even though this is technically possible."

**Reward Account**
- [ ] Add to GUI.  Microcopy "Select account or paste account address"
  ---  Keep un-populated.
 ---  Add Headline text: Reward account is used to collect the payments for the role rewards. We suggest to use control
  --  Add tooltip "Member controller or root accounts are often chosen for this purpose."

**Comment by dmtrjsg** [comment]
https://github.com/Joystream/pioneer/issues/2284

**Comment by dmtrjsg** [comment]
RN Role Acc and Reward are predefined by us (controller acc of the member). 

Question: Do we want to allow user to select Role account separately? 

> currently we will preselect the Role account with Controller account bound to member.

**Comment by dmtrjsg** [comment]
1. Select Staking Account

2. Stake

3. Select Role Account
Role account is used to perform all role-specific actions.
Input + tooltip

4. Select Reward Account
Reward account is used to collect the payments for the role rewards. We suggest to use control

**Comment by mochet** [comment]
Appears to work fine
- Applied for 3 different roles (both lead / worker types)
- Applied with a variety of parameters. All were successfully recorded in TX.
- Attempted to use an account with insufficient balance for stake requirement - it did not show in list
- Attempted to use role bound account, didn't show or gave error `This account is bound to the another member`
- No rivalrous lock accounts showed
