### ISSUE TITLE
[USERSNAP] Adding New Proposal Button is hidden after Current Proposal Created

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2318]
⚠️  issues with creating proposal, see below. 
___________
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Discrod Handle: tomato#9464
- Give us some details: have tried refreshing but the button won&#39;t appear again
- Houston, we have a problem.: New proposal button gone after submitting a proposal
- have tried refreshing but the button won&#39;t appear again

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f539c380-2974-4857-8465-51f7c64e957d-annotated_4f346a16-957a-4122-9527-8f12494bc08c.png?etag=7416d912c992c27344f98478bc0ccfd3)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f539c380-2974-4857-8465-51f7c64e957d-annotated_4f346a16-957a-4122-9527-8f12494bc08c.png?etag=7416d912c992c27344f98478bc0ccfd3)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1645x1020
**[Open #15 in Usersnap](https://app.usersnap.com/l/feedback/6bc1a84a-8025-402a-9e13-6bf40401f464?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
Problem: when the `Current` proposal page has a proposal, the `new proposal` button won't show

![image](https://user-images.githubusercontent.com/50830161/155531423-cbc6f405-27d4-4578-884a-1dc43d96c293.png)

**Comment by dmtrjsg** [comment]
@mochet pls try to rec ⏺️  the screen with the widget where you're raising the bug, and do a page refresh with a console open.  That would help us get to the root hopefully 🤞

There seems to be some issue with proposals creation when I tested just now

<img width="1431" alt="Screenshot 2022-02-24 at 20 55 47" src="https://user-images.githubusercontent.com/93924525/155606542-16f3bd86-c34a-4473-ad57-ca9869ef5861.png">

**Comment by dmtrjsg** [comment]
❓  did we have anything merged recently that may interfere @thesan @WRadoslaw

**Comment by WRadoslaw** [comment]
Yes, #2306 caused that. Fix -> pass buttons directly to the `PageHeader` component. Before it was compiled to work with video button, commenting it out caused the problem.

**Comment by mochet** [comment]
> @mochet pls try to rec ⏺️ the screen with the widget where you're raising the bug, and do a page refresh with a console open. That would help us get to the root hopefully 🤞
> 
> There seems to be some issue with proposals creation when I tested just now
> 
> <img alt="Screenshot 2022-02-24 at 20 55 47" width="1431" src="https://user-images.githubusercontent.com/93924525/155606542-16f3bd86-c34a-4473-ad57-ca9869ef5861.png">

Sure, will do this going forward whenever its appropriate!

**Comment by dmtrjsg** [comment]
Resolved , see linked PR
