### ISSUE TITLE
Working Group Lead Proposals: cancel opening/ decrease stake/ terminate lead

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2323]
- [x] Terminate Working Group Lead proposal

⚠️ needs to be tested on pioneer-2 env (main branch), network 34.

**Comment by dmtrjsg** [comment]
@ivanturlakov @polikosi guys this one was already on prod, but can you pls kindly test it on staging?

**Comment by ivanturlakov** [comment]
✅ Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/
wss://34.230.5.182.nip.io/ws-rpc

Works as expected

### An account that will be used for proposal creation
<img width="1173" alt="Снимок экрана 2022-12-11 в 14 34 02" src="https://user-images.githubusercontent.com/46903215/206904152-ca6f2612-4ee9-4861-b3d2-5d42577090f2.png">

### Lead that will be terminated
<img width="1174" alt="Снимок экрана 2022-12-11 в 14 34 53" src="https://user-images.githubusercontent.com/46903215/206904153-3251274e-6385-4b20-bab1-1087fef6d0ef.png">

### Proposal created
<img width="1209" alt="Снимок экрана 2022-12-11 в 14 36 17" src="https://user-images.githubusercontent.com/46903215/206904154-ec57078a-522f-495a-a38c-ca05146ec75d.png">

### Proposal lock added
<img width="1175" alt="Снимок экрана 2022-12-11 в 14 36 49" src="https://user-images.githubusercontent.com/46903215/206904156-6da0e43d-a436-47ee-96cc-a3a1d96b31aa.png">

### Proposal approved
<img width="1003" alt="Снимок экрана 2022-12-11 в 14 38 15" src="https://user-images.githubusercontent.com/46903215/206904157-ff87aba7-3838-4b4c-b214-b72ca21f747c.png">

### WG Lead terminated
<img width="1174" alt="Снимок экрана 2022-12-11 в 14 38 51" src="https://user-images.githubusercontent.com/46903215/206904159-6c064379-8512-4d6c-be53-4bd3e64018f8.png">

### Proposal lock recovered
<img width="1175" alt="Снимок экрана 2022-12-11 в 14 39 11" src="https://user-images.githubusercontent.com/46903215/206904160-44a8f361-622b-4613-858a-272f9557473c.png">

### Lead lock recovered automatically
<img width="1175" alt="Снимок экрана 2022-12-11 в 14 39 29" src="https://user-images.githubusercontent.com/46903215/206904161-b5ac1881-21a0-46f7-af05-7cb11dc6d0c8.png">
