### ISSUE TITLE
Set Working Group Lead Reward

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2326]
[ ] Set Working Group Lead Reward
- Same as when updating reward of a worker in group with given inputs, except signer check

**Comment by dmtrjsg** [comment]
Can be tested on dev

**Comment by polikosi** [comment]
Create Proposal
![image](https://user-images.githubusercontent.com/80429191/200583197-767a7f13-d580-4a1f-bef1-6929b51265c3.png)
![image](https://user-images.githubusercontent.com/80429191/200583413-b675f98d-6515-4c49-ae3f-c2138510b4b3.png)
![image](https://user-images.githubusercontent.com/80429191/200583464-0a8849e7-cb2b-4e73-808b-169359245440.png)
[TX](https://polkadot.js.org/apps/?rpc=wss://3.92.226.32.nip.io/ws-rpc#/explorer/query/0x5b0edc45ce857fc6195e26d383f3047fe8ccda9cb872e6c26ac1ab0fe818a37b) 
https://dao-git-dev-joystream.vercel.app/#/proposals/preview/9

Vote on Proposal
![image](https://user-images.githubusercontent.com/80429191/200584385-d92a7f48-1119-485e-93cc-ab59a2952c3f.png)
[TX](https://polkadot.js.org/apps/?rpc=wss://3.92.226.32.nip.io/ws-rpc#/explorer/query/0x7b2e601770fb96983d616d3145f5eab46fe5f0cb2634f4bd883094455bf06576)


Before updating 
![image](https://user-images.githubusercontent.com/80429191/200583947-f3841d52-622b-4f84-823a-2233265ab4ea.png)

After update
![image](https://user-images.githubusercontent.com/80429191/200584696-8f8ee75f-50f5-4dc6-8748-47391611b767.png)


@dmtrjsg Am I understanding this ticket correctly?

**Comment by dmtrjsg** [comment]
@polikosi 


I am sorry, seems I have missed it with the proper description. 

Here what was changed is that execution constraints were set up with the creation constraints. 

here to test the negative scenario one would need to set the reward for the WG where Lead is not set. This would need to trigger a warning message saying that the way how it is set up now the proposal will fail.

__

bases on this: 
https://joystream.gitbook.io/testnet-workspace/system/proposal-system#proposals
And this
https://joystream.gitbook.io/testnet-workspace/system/working-groups#update-reward-amount-for-worker

**Comment by dmtrjsg** [comment]
So we've checked how this works on the QN side, and there isn't much we could do on the Pioneer side to unset lead. The extrinsic has to be called by the engine when the proposal to terminate the lead is executed.  Potentially a runtime bug but we need more time to check.

**Comment by traumschule** [comment]
Ok thanks for checking, then there's no problem.

> here to test the negative scenario one would need to set the reward for the WG where Lead is not set. This would need to trigger a warning message saying that the way how it is set up now the proposal will fail.

Similar case below, it's not possible to select unset lead. Should it still get an extra warning?

![](https://cdn.discordapp.com/attachments/910968995379822633/1041804095712936018/no-group.png)

**Comment by dmtrjsg** [comment]
@traumschule one needs to select the WG and lead is populated automatically..

**Comment by dmtrjsg** [comment]
QN fix is required..

**Comment by dmtrjsg** [comment]
@traumschule how is this tested and ready for prod if QN fix was required?

cc @thesan
