### ISSUE TITLE
Update Working Group Budget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2327]
- [ ] Update Working Group Budget
- If budget_update is non-negative, then this it must be no less than the council budget, otherwise the absolute value must be no less than the current group budget.

**Comment by bwhm** [comment]
@dmtrjsg 
Note that there are some potential pitfalls here. The budget will often change in between the creation and potential execution of the proposal, for more than one reason:
1. The budget may be increased/decreased due to another proposal
   - This would be FAR outside the scope of Olympia, but this can be somewhat accounted for by checking if there are any other active (budget) proposals for this group.
2. The budget will change if there is a payout in between.
   - This change can be estimated, but as a group can hire/fire in between, it won't be correct.

AFAICT, the best we can do here is provide some information and warnings to the user.

**At creation**  
Show:
- the current budget 
   - implemented but incorrect values ref #2443
- the expected size of the (next) payout(s)
- the blockheight + expected time until the (next) payout(s)
Warnings:
- If the user wants to **decrease** - always warn "If the budget is less than this amount at attempted execution, this proposal will fail to execute, and the budget size will not be changed"
- If the user wants to **decrease** more than the current budget warn "Unless the budget is increase between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed"
   - For both, feel free to make the warning better :)

**Proposals page**
Assuming the proposal is created, in the proposal preview page
show:
- the current budget
- expected value of the budget assuming it gets passed?
- if the proposal is to **decrease** more than the current budget warn "Unless the budget is increase between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed"

**Comment by dmtrjsg** [comment]
At creation
Show:

~the current budget for the WG~ ✅  - Already done
~the current budget for the Council~ - ✅  Already done
➕ 👉  the expected size of the (next) payout(s)  + blockheight + expected time until the (next) payout(s).  + message "Expected payouts can be impacted by hiring and firing decisions made before the date of payout."
> WG payouts are done at regular times, and cover Lead and Workers salary. 

➕  👉  Add _custom_ Warnings:
If the user wants to decrease - always warn "If the budget is less than this amount at attempted execution, this proposal will fail to execute, and the budget size will not be changed"

If the user wants to decrease more than the current budget warn "Unless the budget is increase between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed"~ - we have this covered by generic message:


If the user wants to increase - always warn: "If the Councils budget is less than this amount at attempted execution, this proposal will fail to execute, and the budget size will not be changed."

If the user wants to increase - more than the current council budget warn: warn "Unless the Councils budget is increased between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed."


Proposals page
Assuming the proposal is created, in the proposal preview page
show:

the current budget for the WG ( As widget)
expected value of the WG budget assuming it gets passed (As widget)
the current budget for the Council (as widget)
if the proposal is to decrease more than the current budget warn (_similar style to the warning message that we use on Proposal creation, but placed underneath the widgets and above discussion threads) _ "Unless the budget is increase between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed."
if the proposal is to increase - more than the current council budget warn: warn "Unless the Councils budget is increased between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed."

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/current
wss://34.230.5.182.nip.io/ws-rpc

### Creation
✅ the expected size of the (next) payout(s) + blockheight + expected time until the (next) payout(s). + message "Expected payouts can be impacted by hiring and firing decisions made before the date of payout."
✅ If the user wants to increase - always warn: "If the Councils budget is less than this amount at attempted execution, this proposal will fail to execute, and the budget size will not be changed."
<img width="1258" alt="Снимок экрана 2022-12-03 в 19 08 56" src="https://user-images.githubusercontent.com/46903215/205453100-b98258ae-1ff8-4308-9a6a-bfd8123a9f6e.png">

✅ If the user wants to decrease - always warn "If the budget is less than this amount at attempted execution, this proposal will fail to execute, and the budget size will not be changed"
✅ If the user wants to decrease more than the current budget warn "Unless the budget is increase between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed"
<img width="1350" alt="Снимок экрана 2022-12-03 в 19 09 57" src="https://user-images.githubusercontent.com/46903215/205453101-496d20ea-4697-4dbd-afff-abdc57dd7fbb.png">

✅ If the user wants to increase - more than the current council budget warn: warn "Unless the Councils budget is increased between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed."
<img width="683" alt="Снимок экрана 2022-12-03 в 19 18 16" src="https://user-images.githubusercontent.com/46903215/205453363-d0c63e9f-e043-4988-a746-5191fa41e93e.png">


### Proposals page
✅ the current budget for the WG ( As widget)
✅ expected value of the WG budget assuming it gets passed (As widget, title = Expected if passed)
✅ the current budget for the Council (as widget)
✅ If the proposal is to decrease more than the current budget warn "Unless the budget is increase between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed."
<img width="1211" alt="Снимок экрана 2022-12-03 в 19 22 20" src="https://user-images.githubusercontent.com/46903215/205453540-e34a2453-65c0-4e0d-a0ef-4d599d7658e5.png">


@dmtrjsg I faced just one problem here
### 🚫 if the proposal is to increase - more than the current council budget warn: warn "Unless the Councils budget is increased between now and attempted execution, this proposal will fail to execute, and the budget size will not be changed."

### An error occurred while creating a proposal to increase the WG budget(more than the current council budget - 1,028,471,198.3). When trying to open(vote) a proposal.

<img width="1440" alt="Снимок экрана 2022-12-03 в 19 36 24" src="https://user-images.githubusercontent.com/46903215/205454123-81ba2172-89fa-45bb-97fb-774437d6ed0d.png">

But proposals page is ok
<img width="1016" alt="Снимок экрана 2022-12-03 в 19 41 02" src="https://user-images.githubusercontent.com/46903215/205454320-f65f6838-740e-46dc-99a0-da3f19eafc7f.png">
https://dao-git-dev-joystream.vercel.app/#/proposals/preview/28

**Comment by traumschule** [comment]
This shows it needs an upper limit of `1000000000000000` using `new BN()`: 10x that throws
```
> new BN(10000000000000000)
Uncaught Error: Assertion failed
    at assert (/home/debian/pioneer/node_modules/bn.js/lib/bn.js:6:21)
    at BN._initNumber (/home/debian/pioneer/node_modules/bn.js/lib/bn.js:128:7)
    at BN.init [as _init] (/home/debian/pioneer/node_modules/bn.js/lib/bn.js:82:19)
    at new BN (/home/debian/pioneer/node_modules/bn.js/lib/bn.js:39:12)
```
![prop28-amount](https://user-images.githubusercontent.com/31551045/205500259-3145f035-1c4b-42ae-a8bf-9b0c3af11ed7.png)

**Comment by traumschule** [comment]
Considering decimals the limit is awful low: #3920
@dmtrjsg what do we do?

![maxAmount](https://user-images.githubusercontent.com/31551045/205505893-854ceac7-4e02-4152-b656-aba9403c6fb9.png)

**Comment by thesan** [comment]
> needs an upper limit of `1000000000000000` using `new B`

I don't think there is a limit to `BN` values but when the value is more than `Number.MAX_SAFE_INTEGER` it should be passed as a string instead of a JavaScript number like in the screenshot.

**Comment by traumschule** [comment]
@chrlschwb can you please test this solution and create a PR based on #3920.

**Comment by thesan** [comment]
> ![](https://user-images.githubusercontent.com/46903215/205454123-81ba2172-89fa-45bb-97fb-774437d6ed0d.png)

This is out of scope because it was a result of both:
- https://github.com/Joystream/joystream/issues/4503
- https://github.com/Joystream/pioneer/issues/3994

Apart from that the QA looks successful to me.
