### ISSUE TITLE
Indexer problem with diff versions of the network

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2329]
![Screenshot 2022-02-24 at 13.27.13.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/fcf1220a-44af-4c89-966e-d4406b14d52a)

thesan  to specify the issue.

Adding Olympia label since this was identified as a blocker for Create Bounty Flow

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201878937844785) by [Unito](https://www.unito.io)

**Comment by thesan** [comment]
The indexer works fine now on the latest `olympia-playground`
