### ISSUE TITLE
[USERSNAP] Inviting Member Flow is blocked in GUI (inviting member cannot be selected)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2331]
- [x] Auto-populate the actively selected membership to the first input
- [x] Root and Controller accounts  - update the input placeholder text from "type" to  "Enter the account of the person being invited." 
- [x] Membership handle is required
- [x] Meta data should not be required

@bwhm  to create a runtime bug ⚠️  

Here's how it looks like in polkadot transaction:

<img width="553" alt="Screenshot 2022-03-03 at 14 41 49" src="https://user-images.githubusercontent.com/93924525/156588492-1379dc07-a2f0-4c6c-a3da-013d9d7c3fb7.png">

______
**Taken at**: https://pioneer-2.vercel.app/#/profile/memberships
**Fields**:
* Discrod Handle: tomato#9464
* Give us some details: SSIA
* Houston, we have a problem.: After inviting one member, the member page stops working unless refreshed. Will not allow selection of &#34;inviting member&#34;
* SSIA

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/287d79cd-0826-4328-b213-2a2aa438cba4-annotated_be10814e-e23f-49fc-9482-a6b3620426a2.png?etag=d51cd355bfb0f129c27204dd097686ad)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/287d79cd-0826-4328-b213-2a2aa438cba4-annotated_be10814e-e23f-49fc-9482-a6b3620426a2.png?etag=d51cd355bfb0f129c27204dd097686ad)_

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1645x1020
**[Open #17 in Usersnap](https://app.usersnap.com/l/feedback/ee319bb0-8a88-42f2-8754-427d5def2ceb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201892614550630) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
Update: I cannot select any key at all. Presumably this is because the page updated.

**Comment by dmtrjsg** [comment]
Second point from here is most probably going to be fixed by 
- #2277

**Comment by dmtrjsg** [comment]
To be retested after faucet server is confirmed to be fully up and running

**Comment by dmtrjsg** [comment]
@WRadoslaw good idea to add explanation, but perhaps better suited for the tooltip next to Member handle, rather than validation copy or placeholder text.

Tooltip copy: "Membership handle is the primary way of how members are displayed throughout all interfaces of the platform. Membership handle can be updated any time by the account holder."
[Learn more >](https://joystream.gitbook.io/testnet-workspace/system/memberships#membership) 

Hope this makes sense ;)

**Comment by mnaamani** [comment]
Resolved
