### ISSUE TITLE
[USERSNAP] Alphabetical order on `select membership` page is totally random. 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2334]
## Scope

- [ ]  Order members by handle A-Z in select membership modal

⛔  Out of scope
- [ ] Sorting by ID as covered in other ticket.
- [ ] The window could also do with being slightly taller, maybe showing 5 memberships at a time
> Reason, is that it is unlikely that during normal usage the list of memberships for an average member would be >3.

## Context

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Alphabetical order on `select membership` page is totally random. The window could also do with being slightly taller, maybe showing 5 memberships at a time
- Give us some details: SSIA
- SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/59446562-b1fb-4b7b-8126-d9cace4baf10-annotated_1a89120b-081e-470f-913e-e6ac95cc1c75.png?etag=5208ddc97f92038ac5cef9708e9e5762)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/59446562-b1fb-4b7b-8126-d9cace4baf10-annotated_1a89120b-081e-470f-913e-e6ac95cc1c75.png?etag=5208ddc97f92038ac5cef9708e9e5762)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1351x1020
**[Open #18 in Usersnap](https://app.usersnap.com/l/feedback/a7b73a20-621e-4a2b-babc-fc4529822442?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
Recurring issue - it seems the sorting of memberships, proposals, etc. is **somewhat** random. Even if you sort by ID, it's not correct.

**Comment by dmtrjsg** [comment]
Linking up with 
- [ ] #1513

**Comment by adovrodion** [comment]
Bounty was created: https://dao.joystream.org/#/bounty/preview/267
