### ISSUE TITLE
Add Opening Title to the Proposal flow for Create WG Opening and Fill WG Opening

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2336]
## Scope

Opening title needs to be added to this flow > https://github.com/Joystream/pioneer/issues/2395

Namely:
Add opening title as separate widget to Proposal Details Page for 
- Create WG Opening 
- Fill WG Opening

Title of widget: Opening title
Content: opening_title
If title is too long, truncate and show full name on hover in tooltip

⚠️ this field is not required to be added to the proposal modal

## Context

_________

**Taken at**: https://pioneer-2.vercel.app/#/working-groups/membership
**Fields**:
- Houston, we have a problem.: Name of opening not included in openings page
- Give us some details: A name was submitted with the proposal, and it is not shown anywhere.
- A name was submitted with the proposal, and it is not shown anywhere.
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bff009a6-fc74-445d-b4cc-70f6a38cb1c3-annotated_45b947cb-53e8-4c72-95a1-bff89b15b554.png?etag=a7fdce30838a130c611ebbd08a351a6e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bff009a6-fc74-445d-b4cc-70f6a38cb1c3-annotated_45b947cb-53e8-4c72-95a1-bff89b15b554.png?etag=a7fdce30838a130c611ebbd08a351a6e)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1351x1020
**[Open #20 in Usersnap](https://app.usersnap.com/l/feedback/cc5f9332-19e8-471d-9dba-e41f9cba7f3b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
Related to #2309, without any other info than the WG in question and the opening id, it's hard to distinguish and get the needed context. Title should be shown?

**Comment by dmtrjsg** [comment]
⚠️  tbc if we also need Application Process as a separate field. Referring to[ designs here ](https://www.figma.com/file/QSpueQlOQKGbiHig2harPy/Working-groups?node-id=1080%3A4835793) @bwhm wdyt?

**Comment by thesan** [comment]
I think this is done since: https://github.com/Joystream/joystream/pull/3386 and https://github.com/Joystream/pioneer/pull/2528 are merged
