### ISSUE TITLE
[USERSNAP] WG application page has no place for application text

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2337]
**Taken at**: https://pioneer-2.vercel.app/#/working-groups/membership
**Fields**:
- Houston, we have a problem.: WG application page has no place for application text
- Give us some details: There should be a text box here for the person to write their application
- SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/807de7a0-84a2-4614-8904-e22685b71673-annotated_b4838133-30a1-42d9-a51a-a8e11036705d.png?etag=a387bb38fcb70ff88bbf8ad3f7a8f78c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/807de7a0-84a2-4614-8904-e22685b71673-annotated_b4838133-30a1-42d9-a51a-a8e11036705d.png?etag=a387bb38fcb70ff88bbf8ad3f7a8f78c)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1351x1020
**[Open #21 in Usersnap](https://app.usersnap.com/l/feedback/ebbb1ad1-6249-4cfb-b4af-936c684388b6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
Unclear if this is a bug. We need to make "real" openings before evaluating this.

**Comment by dmtrjsg** [comment]
@bwhm what do you mean by "real"? 

Also looks like it was already addressed and fixed here, so closing
- #2314
