### ISSUE TITLE
Display withdraw funds modal when cherry applies.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2341]
## Dev Scope

- [ ]  Use this version for the Withdraw Contribution + Cherry
⚠️  Use copy for CTA and title "Withdraw Contribution"
- [ ] 🆕  Update signer modal with the same design:

<img width="1031" alt="Screenshot 2022-05-06 at 16 37 43" src="https://user-images.githubusercontent.com/93924525/167165975-14486b69-d0eb-46c6-96f0-a5710dd91c6d.png">

## Context

Bounty contribution withdrawal modal needs a state when cherry applies

## Scope
We need a view of [this modal](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=319%3A162726) for the case when cherry applies. 

> if bounty fails, cherry (funds contributed by creator of bounty) gets split across all contributors equally. (if odd number for splitting, the first recipient in the list can get 1 extra Joy)

## More info

Assurance Contracts and Dominant Assurance Contracts
An assurance contract is a funding scheme intended to override the inherent free-riding problem in financing public goods by allowing contributors to enter into binding conditional commitments to provide resources to fund the good if a sufficient level of funding is committed. By setting the level sufficiently high, every public good beneficiary becomes close to pivotal to getting the good produced, which generates a rationale incentive to unilaterally commit. Dominant assurance contracts are such schemes where the funding has to be deployed towards a specific service provider or entrepreneur who will produce the good using the funding, and in exchange for this privileged to possibly generate a profit from this activity, the entrepreneur has to put up an initial bounty, called a cherry, which is split among all contributors pro-rata. This cherry generates an incentive for contributors, as even when the funding fails, they get a benefit.

Link to ✋  📖  > https://joystream.gitbook.io/testnet-workspace/system/bounties#effect-1

**Comment by MattAugustynowicz** [comment]
Using the fact that in this view, we had prepared headings above our accounts (withdrawing, amount), I thought we could either duplicate the box and display the information or fit both staking and cherry information into one. 

[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8795%3A423919)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/24ce08bd-ad82-49ce-aa27-b89a00b185ba)

I'm naturally closer to second version so as not to show the same account twice, but I'm keen to hear what your views are on this now that a version has been created :)

**Comment by dmtrjsg** [comment]
@WRadoslaw https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1373%3A67105 < tagged you on the page as well ;)

**Comment by polikosi** [comment]
verified on staging. Test evidence below:
![Screenshot_103](https://user-images.githubusercontent.com/80429191/173042375-e5bd2134-894a-4be6-a7a8-edc44a68df35.png)
