### ISSUE TITLE
Display Blockheight for RPC and Latest Processed by QN

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2342]
## Scope
- [ ] Show RPC blockheight in settings
- [ ] Show latest that QN has processed
- [ ] Show in alt colour (yellow) if out of sync situation detected and invite user to reload. Example: `warning: the UI is currently `x` blocks behind. Try refreshing your browser window. View details > [points to settings network tab]`~ 

## Context

Pioneer doesn't warn you when QN is out of sync

> Query Nodes in particular seem to suffer from more problems than blockchain nodes. Even with increased reliability, if the QN has issues and a user isn't aware it can lead to expensive problems (such as submitting proposals or other transactions when it isn't needed). It would seem like Pioneer should be able to detect the most recent blocks a query node has sync'd and issue a UI error or notification in the event the query node is out of sync with the blockchain. 
- #2270 
 
> In most situations, some edge cases causes further issues. During testing, we "managed" to break the QN processor, and the only way to figure it out was to compare state with polkadot-js.

> In the previous design of Pioneer v1 as well as most Substrate projects the blockheight is shown at least somewhere. It is a very easy and quick way to show if you are on an endpoint that is synchronized. This should either be shown in the settings page, or maybe in the top left corner of the page as it was in Pioneer v1. It needs to be accessible from somewhere. 
- #2269 

> request to show QN blockheight 
- #2762  
BOTH QN AND CHAIN!

> Plus this
- #2538
 

Additional scope  tbc ⚠️ :
- [x] Show a small connectivuty/ status widget along the lines of 🟢  🟡  🔴 ⚫ 

## Important Info

**Bedeho:**

We don't really do any connectivity UX. The only thing we do is to display an alert when a connection is lost, or when it is attempted to be made, not when its actually made. But I think events are actually not the right emphasis for this, what is relevant to the user is to when they are not currently connected, and when they currently are. This arguably requires some consistent impossible to miss visual state which tells you when you are not connected. Here we are also actually talking about two separate connections: the full node and the query node. Arguably, if you loose connection to either, the app should really urge you to stop and wait until everything works. It may also make sense to disable the final button in any flow where a transaction would be submitted, if you currently are not connected to both nodes.

**From prev dev team** 

The idea is to:
- disable the buttons when we lost connectivity to the Joystream Node
- disable browsing the app when the connectivity to the Hydra Node is lost

For the 3rd point, it makes sense to allow the user to browse the app state (from Hydra) but to disallow any actions. It should be the most recent state anyway (even though, the connection to the blockchain might be lost) so it shouldn't be that confusing. It might be also a less common case than losing connection to both (e.g. network problem).

**Comment by polikosi** [comment]
✅Show RPC blockheight in settings
✅Show latest that QN has processed
![image](https://user-images.githubusercontent.com/80429191/206696581-0181f864-3eb6-49cf-8a5c-864ebe8d65d8.png)

online
![image](https://user-images.githubusercontent.com/80429191/206697406-29a33fe6-7e10-4d1b-9069-bc9864858749.png)

offline
![image](https://user-images.githubusercontent.com/80429191/206696844-5c853320-2f80-4592-bf8a-c341165425f8.png)

**Comment by dmtrjsg** [comment]
Small cosmetic change requests:

For the settings page component: 
1. Update title from "Chain Informations" to "Chain information"
2. RPC blockheigh and QueryNode blockheight need to be not bold, matching the font of "Network details"

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/settings

some problems with formatting
<img width="231" alt="Снимок экрана 2022-12-19 в 23 48 12" src="https://user-images.githubusercontent.com/46903215/208530701-34474e66-f7a9-47a5-888a-71f761d2df57.png">

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-fork-traumschule-fix-settings-2342-joystream.vercel.app/#/settings

<img width="268" alt="Снимок экрана 2022-12-23 в 12 46 32" src="https://user-images.githubusercontent.com/46903215/209322683-87aadbac-eebc-49d9-97b0-30b087b134bb.png">
