### ISSUE TITLE
Tooltip: proposals trigger and discussion

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2346]
## Scope
Add tooltips to proposal creation flow:

- [ ] Optional trigger block for executing proposal. If trigger is provided, it must be no less than current block plus combined duration of GRACING_LIMIT and DECIDING_PERIOD. 
[Learn more >](https://joystream.gitbook.io/testnet-workspace/system/proposal-system#submit-proposal)
- [ ] Proposal thread is created as part of the process to enable discussion before voting. In open mode, any member can post a message, while in closed mode, only the active council, proposer and whitelisted members can post. Mode can be changed by member or council member at any time. 
[Learn More > ](https://joystream.gitbook.io/testnet-workspace/system/proposal-system#discussion)

## Context
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Help tooltip for &#34;Trigger&#34; and &#34;Discussion mode&#34; parameters don&#39;t contain any useful info
- Give us some details: If you pass the mouse over the &#34;help icon&#34; in each parameter you see a tool-tip containing only the name of the parameter. It should have a good description for what the parameter does.
- Probably the text in the tool-top it&#39;s just a placeholder for a future description
- Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c4aef8de-baa3-43a9-8afb-78d402eb0768-annotated_fbb345a9-7d53-41cc-98ee-bbb57ee0da7e.png?etag=6d977bc336503083f52b4f6dea226f10)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c4aef8de-baa3-43a9-8afb-78d402eb0768-annotated_fbb345a9-7d53-41cc-98ee-bbb57ee0da7e.png?etag=6d977bc336503083f52b4f6dea226f10)*

**Browser**: Chrome 98 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1244x1324
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/02c5f061-3dc2-4395-ad8c-b4579d9d576d_screen_recording_de5f0725-1db6-4bbf-957c-1bf5f497c46d.webm?etag=704bd12cabf63b07590436af88d0036c)**
**[Open #26 in Usersnap](https://app.usersnap.com/l/feedback/a7692e7e-cf9d-47e9-8f31-faac43d5dfeb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/current

@traumschule

⚠️ Small typo
<img width="686" alt="Снимок экрана 2022-11-09 в 12 09 28" src="https://user-images.githubusercontent.com/46903215/200803333-7361bfd7-56d7-43f5-aa81-e29bcf28e459.png">
<img width="1438" alt="Снимок экрана 2022-11-09 в 12 05 01" src="https://user-images.githubusercontent.com/46903215/200803373-86430116-ba14-4a1e-b008-25ed61f60873.png">

✅ Discussion title
<img width="1440" alt="Снимок экрана 2022-11-09 в 12 05 17" src="https://user-images.githubusercontent.com/46903215/200803351-0eb9da14-710d-413f-a75b-e4e36cef4d70.png">

**Comment by traumschule** [comment]
Fixed in #3775

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-staging-joystream.vercel.app/#/proposals/current

<img width="1253" alt="Снимок экрана 2022-12-02 в 14 48 01" src="https://user-images.githubusercontent.com/46903215/205296401-b04e48f6-46e8-4ff6-8b2f-20b127e348b7.png">
