### ISSUE TITLE
Bounty entrant has to be stricly more than the minimum value to enable the next step

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2349]
## Scope
- [ ] Update validation message "Minimum entrant stake must be greater than {{X Joy}}"

![Screenshot from 2022-02-25 12-56-43](https://user-images.githubusercontent.com/6571453/155711750-fac40769-2ea8-4b4a-b40e-7d0552518752.png)

**Comment by talentdev0807** [comment]
@talentdev0807

**Comment by polikosi** [comment]
Failed.

Actual: "Entrant stake must be greater than 1000 JOY"

Expected: "Minimum entrant stake must be greater than 1000 JOY"
![Screenshot_24](https://user-images.githubusercontent.com/80429191/169494965-80d9063d-8cb2-43b0-9382-faea6852fa14.png)
