### ISSUE TITLE
Past Elections: show voting pool stake on past candidates

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2353]
### Voting Results

Voting results do not show revealed votes and voted stake

![Screenshot 2022-02-22 at 16.11.21.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/6ef2d0d1-2815-44c1-8fcf-ed8d30a7d0dd)

![Screenshot 2022-02-22 at 15.57.45.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/78cb86d7-175b-4e45-a39d-f1ed972b5370)

**Comment by singulart** [comment]
Tested on Prod, looks fine. This ticket has no PR, so maybe the issue was fixed elsewhere
<img width="1124" alt="Screenshot 2022-04-14 at 16 05 14" src="https://user-images.githubusercontent.com/7863785/163396838-4c941549-0010-480e-a797-538af1e39a80.png">
