### ISSUE TITLE
More lock icons needed 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2354]
## Scope:
- [x] Update icons for all locks shown on account cards and accounts tab.
- [x] Role staking locks are specific per each working group 

## Designs:
[Link to Figma>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design)

## How to test

⚠️  Check with story book as we only need to show

⚠️ In the app accounts is the place where these icons show:
<img width="707" alt="Screenshot 2022-05-05 at 10 32 46" src="https://user-images.githubusercontent.com/93924525/166897250-ad226ad6-0574-4324-a07c-58c627b13d28.png">

_____________
### More info for informing design
- [x] Voting stake. ["Sealed and not sealed"](https://joystream.gitbook.io/testnet-workspace/system/council#conditions-4). Its locked when you vote for a candidate. It remains locked while candidate is a councillor.
- [x] Candidate lock - locked while you're a candidate, also transitions to councillor lock if you win.
- [x] Proposal lock - auto-removed if proposal rejected or executed.
- [x] Role staking account - role-specific lock
- [x] Bounty work entrant staking account - locked while in bounty

(See #2279)
- for all locks covered here>
https://joystream.gitbook.io/testnet-workspace/system/accounts-and-staking#locks-1

**Comment by dmtrjsg** [comment]
WG icons to inform WG-specific locks: https://app.zenhub.com/workspaces/pioneer-603cf0017ea5c9001b428eba/issues/joystream/pioneer/2279

**Comment by MattAugustynowicz** [comment]
[👉 Figma link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1405%3A76780)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/fe3bafbf-dcad-4cac-aa52-abe64df4ef8c)

**Comment by dmtrjsg** [comment]
@MattAugustynowicz can we pls have a list with labels, as otherwise hard to see which is which. 

Thank you 😇

**Comment by MattAugustynowicz** [comment]
Sure thing :) 
[👉 Same link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1405%3A76780)
![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/ace7da0f-806f-4897-9e10-4000dcb55783)

**Comment by RafalPloszka** [comment]
There are no icons for `Vesting` and `Nomination` locks, but I'm not sure if we need them currently

**Comment by dmtrjsg** [comment]
@RafalPloszka let's show them as generic lock icons for the time being. If members have those locks applied, I'd suggest to display them as well. Eventually FE interfaces for those roles will make it to Pioneer :)

**Comment by ivanturlakov** [comment]
Tested on staging.

Voting stake.
<img width="1178" alt="Снимок экрана 2022-06-06 в 12 35 53" src="https://user-images.githubusercontent.com/46903215/172150250-6fb6da54-f156-4474-b540-879b047a7428.png">

Candidate lock
<img width="1176" alt="Снимок экрана 2022-06-06 в 12 48 42" src="https://user-images.githubusercontent.com/46903215/172150406-e8c84835-2cf3-4f16-a423-a110ef99c737.png">

Proposal lock
<img width="1175" alt="Снимок экрана 2022-06-06 в 12 49 21" src="https://user-images.githubusercontent.com/46903215/172150500-ec752aaa-d518-49b3-8da4-22423146bd9b.png">

Role staking account
<img width="1172" alt="Снимок экрана 2022-06-06 в 12 50 13" src="https://user-images.githubusercontent.com/46903215/172150571-59c83d32-66ac-4a20-bdec-467d8adbc839.png">
<img width="1155" alt="Снимок экрана 2022-06-06 в 13 42 37" src="https://user-images.githubusercontent.com/46903215/172151044-7fac2a37-a3ba-4098-9ab3-46b687576f79.png">

Bounty lock
<img width="1173" alt="Снимок экрана 2022-06-06 в 12 51 39" src="https://user-images.githubusercontent.com/46903215/172150618-1ee288a0-9e6d-4ef4-9abd-1572ac6c6d9e.png">
