### ISSUE TITLE
Council normal stage countdown widget shows incorrect value in blocks for guest users

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2362]
## Context

Council in the normal period shows erroneous blocks count till next election

## Details

Actual result: 
![Screenshot 2022-02-28 at 16.53.45.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/cbe3c17b-bec7-4d59-aead-3a068076ac1c)

Expected result:
<img width="422" alt="Screenshot 2022-04-07 at 11 46 34" src="https://user-images.githubusercontent.com/93924525/162182471-ca076115-d81c-4e52-805d-41c6c478a0a4.png">

## Technical Approach

- Review how the election period is implemented and implement similar logic for council election
⚠️  The worker needs to debug the inputs for the component themselves

**Comment by dmtrjsg** [comment]
Linked to #2277 ?

**Comment by talentdev0807** [comment]
@talentdev0807

**Comment by freakstatic** [comment]
@dmtrjsg it seems that this [request](https://github.com/Joystream/pioneer/blob/ca9b298abbb45e157bcb734803345c34926933c9/packages/ui/src/council/hooks/useElectedCouncil.ts#L6) is getting cached by Apollo 

I could be wrong but the "fix" applied [here[(https://github.com/Joystream/pioneer/blob/c3436611bf6120356cd168492e4ea94a1496f578/packages/ui/src/common/providers/transaction/provider.tsx#L25) to refetch queries doesn't work with pages that aren't submitting transactions

**Comment by thesan** [comment]
@freakstatic I just made this [PR](https://github.com/Joystream/pioneer/pull/3117/files) for a similar issue on the election page. I added a hook (`@/common/hooks/useRefetchQueries`) to handle these kind of cases. Once the PR is merge you could use it here too.

**Comment by thesan** [comment]
#3117 is now merged here's how the hook could be used for this issue:
```ts
useRefetchQueries({ when: stage === 'inactive', after: stage !== 'inactive' }, [stage])
```

**Comment by freakstatic** [comment]
> #3117 is now merged here's how the hook could be used for this issue:
> 
> ```ts
> useRefetchQueries({ when: stage === 'inactive', after: stage !== 'inactive' }, [stage])
> ```

thanks very much! 
I will use it

**Comment by freakstatic** [comment]
> #3117 is now merged here's how the hook could be used for this issue:
> 
> ```ts
> useRefetchQueries({ when: stage === 'inactive', after: stage !== 'inactive' }, [stage])
> ```

I notice that the council page has the "council activities" so the cache invalidation needs to be every new election stage. Did a PR that fixes this issue [here](https://github.com/Joystream/pioneer/pull/3221) @thesan please let me know what do you think.
The "council activities" still has issues that I think it's related with getting the data directly from the chain to trigger the cache invalidation and the QN still didn't had the time to update the last blocks

**Comment by freakstatic** [comment]
Would be good to be able to subscribe to QN events so that we could fix this situations properly...

**Comment by dmtrjsg** [comment]
Will be covered in #2311

**Comment by freakstatic** [comment]
> @freakstatic right I forgot about the activities! As @dmtrjsg wrote, the solution for this one too is a poling mechanism just like in #3204 and #3150.
> 
> But this time it should target both the `GetElectedCouncil` and `GetCouncilEvents`:
> 
> ```tsx
> useRefetchQueries({ interval: MILLISECONDS_PER_BLOCK, include: ['GetElectedCouncil', 'GetCouncilEvents'] }, [])
> ```

seems good to go now!

**Comment by polikosi** [comment]
Verified on staging. Test evidence below:
Works as expected
![Screenshot_144](https://user-images.githubusercontent.com/80429191/177953728-efe18710-ff88-4654-b2e1-9b80d803a9a6.png)
