### ISSUE TITLE
Dont allow to recover voting stake / when candidate became councillor (for as long as candidate in the council seat)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2363]
## Problem

Right now the CTA is shown, but transaction fails. 

## To-do

- [ ] Hide Recover voting stake for cases, when voting stake was retained as candidate won the election. 

> So user votes  [cant recover]-> (candidate wins)[cant recover] -> council is in normal state [cant recover] -> council transfers to election state [ becomes REcoverable!] 

###  Additional info

-! Should be solved together with -https://github.com/Joystream/pioneer/issues/2543
-! Design enhancement of this point is handled already in a separate issue > 2354 and 2300

~https://polkadot.js.org/apps/?rpc=wss://3.95.67.177.nip.io/ws-rpc#/explorer/query/0xca5e2866c16837c14c477e76d7fd6021e9c48b15e51f74759ccd8fac0f8d5118~ (chain updated since)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201976887648134) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
Tried re-testing, but when I click the "Recover" button, it simply collapsed the "Locks" view - so I wasn't able to sign any transaction (on chrome).

**Comment by dmtrjsg** [comment]
To do:

- [ ] Hide Recover voting stake for cases, when voting stake was retained as candidate won the election. 

Right now the CTA is shown, but transaction fails. 

Design enhancement of this point is handled already in a separate issue.

**Comment by dmtrjsg** [comment]
Hardcoded line "councilMember is always set to false"
