### ISSUE TITLE
Funding Request Proposal for Multiple Recipients

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2365]
## Context
As can be seen below, the funding request proposal only allows a single recipient + amount.
The use case often covers the need to execute bulk funding request paying multiple accounts different sums of money.

![Screen Shot 2022-02-28 at 23 23 58](https://user-images.githubusercontent.com/35237943/156068501-1c8a9ad2-803d-4a92-8bfe-6c2a129149fd.png)

## Designs

[Link to Figma> ](https://www.figma.com/file/YBfvoRpnduOXxUnA9kvNP5/Pioneer-payment-proposal-for-multiple-recipients?node-id=38%3A78740&t=tIKsgMyAtmQJI9VQ-0)

## Scope

- [ ] Update  Create Funding Proposal with Multiple Recepients option
- [ ] Update View Proposal
- [ ] Test if Voting on this proposal works

### Create Proposal:
* [ ] Add "Pay multiple" toggle which when triggered addds a text are input
* [ ] Add prompt on the format of adding accounts
* [ ] Text are (text box) needs to have label "Destination accounts and transfer amounts"
* [ ] Input must be provided in the CSV format: 
AccountAddress1, Amount; AccountAddress2, Amount;
⚠️ CSV file upload should not be supported we don't need extra effort to spend on this
* [ ] Maximum allowed accounts is 20
* [ ] Add "Preview and Validate" button underneath the input, that triggers the side drawer (see image) displaying Member ID as card (if account bound to member) and Amount

<img width="791" alt="Screenshot 2022-11-25 at 13 48 47" src="https://user-images.githubusercontent.com/93924525/203981273-cacd7f86-5d69-4036-9dec-8cf3fb680828.png">

If "next" is clicked on proposal without preview show warning "Please preview and validate the inputs to proceed"

- [ ] Use this card to display destination payments but change the label to "Amount to pay", instead of trasnferable balance; and Unknown Member isntead of "Unsaved account"
<img width="896" alt="Screenshot 2022-11-25 at 15 57 32" src="https://user-images.githubusercontent.com/93924525/203981566-6d1b54f6-9ad7-4832-8d00-56d6c4748471.png">

- [ ] Add validation if "Max payment amount is exceeded" as yellow info box
- [ ] Add validation if "Incorrect destination account added"

After preview is clicked
- [ ] Display Total Payout in a info field on proposal input screen
In case total payout exceeds the WG budget at the time of Proposal Creation, show warning. 

Use this pattern for the execution violation case (the generic text is already implemented) 

<img width="484" alt="Screenshot 2022-11-25 at 16 08 50" src="https://user-images.githubusercontent.com/93924525/203983095-afa964b9-8564-43a9-ac4c-92e8bb7932f2.png">

### View Proposal
- [ ] Add widget showing Current balance of Content WG
- [ ] Add widget showing Total Payment
- [ ] Add widget to view "Payment details" that slides drawer out (similar to how Signal proposal shows details:

<img width="1224" alt="Screenshot 2022-11-25 at 16 01 10" src="https://user-images.githubusercontent.com/93924525/203981766-5ba14cb1-2f13-4990-b406-ea670cd1a2d8.png">

## More info
Feel free to use the below for inspiration:

![](https://user-images.githubusercontent.com/93924525/156546913-720aa488-53b9-4001-9185-82125c764a01.png)
![](https://user-images.githubusercontent.com/93924525/156546922-8f04bfc8-b17d-44ef-bfd6-0b1bdf7cc639.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203088909656487) by [Unito](https://www.unito.io)

**Comment by thesan** [comment]
See https://github.com/Joystream/joystream/issues/4333 for the validation

**Comment by traumschule** [comment]
Moving this up a bit. Feel free to suggest designs, might give it a go.

**Comment by dmtrjsg** [comment]
👏 Designs are finished for this issue and its ready for dev @traumschule 

## Designs

[Link to Figma> ](https://www.figma.com/file/YBfvoRpnduOXxUnA9kvNP5/Pioneer-payment-proposal-for-multiple-recipients?node-id=38%3A78740&t=tIKsgMyAtmQJI9VQ-0)

## Scope

- [ ] Update  Create Funding Proposal with Multiple Recepients option
- [ ] Update View Proposal
- [ ] Test if Voting on this proposal works

**Comment by vrrayz** [comment]
This is the progress i have made so far #4351

**Comment by traumschule** [comment]
For validation see [this comment](https://github.com/Joystream/pioneer/issues/2321#issuecomment-1054735030) and updated [runtime code](https://github.com/Joystream/joystream/blob/master/runtime-modules/proposals/codex/src/lib.rs#L736). The [restraint per beneficiary](https://github.com/Joystream/pioneer/issues/2365#issuecomment-1264668776) has been removed. Also note [replacement](https://github.com/Joystream/joystream/pull/4133) of MAX_SPENDING_PROPOSAL_VALUE, MAX_VALIDATOR_COUNT, MAX_FUNDING_REQUEST_ACCOUNTS.
