### ISSUE TITLE
[USERSNAP] Clicking this proposal returns a blank page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2375]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Clicking this proposal returns a blank page
- Give us some details: Proposal number 19.
Has been flagged before, but I may have deleted that one thinking it was the query node.
- -
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7ba69dcc-7036-4898-abad-d8e148464d06-annotated_642ed095-3e59-4c54-8004-6bb5a38ab79d.png?etag=f6cbc8989f3d09e853690357dea7caa5)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7ba69dcc-7036-4898-abad-d8e148464d06-annotated_642ed095-3e59-4c54-8004-6bb5a38ab79d.png?etag=f6cbc8989f3d09e853690357dea7caa5)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 1920x1000
**[Open #33 in Usersnap](https://app.usersnap.com/l/feedback/a36d092e-4c50-4b54-8b34-e091181d9418?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
Also related to #2385
