### ISSUE TITLE
[USERSNAP] Selection errors when choosing which opening to fill

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2376]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:

* Houston, we have a problem.: Selection errors when choosing which opening to fill
* Give us some details: When selecting one of the two openings to hire a Lead for said group, there are two errors:

1. Regardless of which I click, it returns the Content Group (I can&#39;t choose the forum).
1. When I &#34;choose&#34; Content, and choose the worker (there are 1 applicant for Content, and none for Forum), the proposal is still for the Forum, with the applicant ID corresponding to the Content (0). Thus, the proposal fails.

Arguably, I shouldn&#39;t even be allowed to choose the wrong thing...

* 
* 
* Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/27a20b4f-d8da-4fa4-b08f-4e962e62af47-annotated_1cc0301b-2f28-4adc-9eed-a4df07587ab4.png?etag=8a7c2990b8e85a5ba6937f3b11f9f19e)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/27a20b4f-d8da-4fa4-b08f-4e962e62af47-annotated_1cc0301b-2f28-4adc-9eed-a4df07587ab4.png?etag=8a7c2990b8e85a5ba6937f3b11f9f19e)_

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 1920x1000
**[Open #34 in Usersnap](https://app.usersnap.com/l/feedback/73266366-9bf6-45fc-9498-2dbd5181bc16?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201905624514544) by [Unito](https://www.unito.io)

**Comment by WRadoslaw** [comment]
> Connected with #2340

Unfortunately no, problem here is that both select to distinct each item utilizes `runtimeId`, but it looks like `runtimeId` only differ between openings in the same group. For example 2 first openings, one in Membership group and second one in Storage will have `runtimeId = 0` if there would be another opening in Storage then it would have `runtimeId = 1`

**Comment by thesan** [comment]
> Unfortunately no, problem here is that both select to distinct each item utilizes `runtimeId`, but it looks like `runtimeId` only differ between openings in the same group. For example 2 first openings, one in Membership group and second one in Storage will have `runtimeId = 0` if there would be another opening in Storage then it would have `runtimeId = 1`

I just checked the [working groups schema](https://github.com/Joystream/joystream/blob/6fe6a973219e9ed0d5a91423ef782fc0bbf39663/query-node/schemas/workingGroups.graphql#L183) and it looks like this is the expected behavior:
```gql
type WorkingGroupOpening @entity {
  "Opening id ({workingGroupName}-{openingId})"
  id: ID!

  "OpeningId in specific working group module"
  runtimeId: Int!

```
It seems `runtimeId` refers to the id of a `WorkingGroupOpening` within it's working group (Pioneer should probably use the `id` over the `runtimeId` in any case I can think of)
