### ISSUE TITLE
[USERSNAP] WG budget incorrectly displaying 0 JOY

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2379]
## Problem
- [ ] All WG budgets (excl council) show 0

> sometimes it shows negative balances..

## Details

**Taken at**: https://pioneer-2.vercel.app/#/working-groups/forum
**Fields**:

* Houston, we have a problem.: Forum budget incorrectly displaying 0 JOY
* Give us some details: It currently has 10M
* .
* Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7383bc2b-1520-442d-ae34-2f09ab1c472a-annotated_03c82e61-741c-4ae3-8709-257bbbd9a500.png?etag=01fbfc4ef2c97d35cb0fa1bcaca89774)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7383bc2b-1520-442d-ae34-2f09ab1c472a-annotated_03c82e61-741c-4ae3-8709-257bbbd9a500.png?etag=01fbfc4ef2c97d35cb0fa1bcaca89774)_

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2166x1093
**[Open #37 in Usersnap](https://app.usersnap.com/l/feedback/00a81db9-5d8d-496f-959c-9bbc69c6fc97?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201905789250342) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
Ref

![Screen Shot 2022-03-01 at 23 52 28](https://user-images.githubusercontent.com/35237943/156262410-e8403780-f916-4709-bb68-4d359cd646bf.png)

**Comment by dmtrjsg** [comment]
- more details in #2327

**Comment by dmtrjsg** [comment]
@RafalPloszka, confirmed with Martin, the negative values and zeros are incorrect..

The way to check what the values must be is below:

<img width="324" alt="Screenshot 2022-03-08 at 09 19 55" src="https://user-images.githubusercontent.com/93924525/157206639-e99acf5f-97d1-45be-a4f9-86306ac3bd9d.png">

**Comment by dmtrjsg** [comment]
Clarified this is not a problem of pioneer..

**Comment by bwhm** [comment]
Confirmed the issue was the query-node :(
![Screen Shot 2022-03-10 at 16 02 51](https://user-images.githubusercontent.com/35237943/157689985-dcea647f-b1b6-4516-91fd-a98a9bda32fd.png)
@dmtrjsg @RafalPloszka
