### ISSUE TITLE
[USERSNAP] When creating "Set Working Group Lead Reward" proposal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2380]
## Scope

- [ ] Increase Reward via GUI results in creating slash WGL
> Problem: Incorrect proposal mapping on the qn side (tbc ⚠️)

## Context

**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/29
**Fields**:

* Houston, we have a problem.: When creating &#34;Set Working Group Lead Reward&#34; proposal
* Give us some details: ...I actually propose &#34;Slash Working Group Lead&#34;
* 
* 
* Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/24b19e0d-df9a-4f7d-b9d8-087308524dd5-annotated_f39b6c88-a989-4b7f-9359-ae36aaa0941e.png?etag=0dd97815c1be64a557976aac8cb883f5)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/24b19e0d-df9a-4f7d-b9d8-087308524dd5-annotated_f39b6c88-a989-4b7f-9359-ae36aaa0941e.png?etag=0dd97815c1be64a557976aac8cb883f5)_

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2166x1093
**[Open #38 in Usersnap](https://app.usersnap.com/l/feedback/92bd1b24-545a-42ad-90c0-75e13a56ef3a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201903815018253) by [Unito](https://www.unito.io)

**Comment by WRadoslaw** [comment]
> Potentially fixed in: #2340

Confirmed
