### ISSUE TITLE
[USERSNAP] Hiring lead Proposal was created with wrong application

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2385]
## Scope
* [ ] Wrong application got selected when hiring lead proposal was created 

> similar issues of mismatch are on proposal types 

## Context
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/38
**Fields**:

* Houston, we have a problem.: Hiring lead Proposal was created with wrong application
* Give us some details: I selected a storage lead application when creating this proposal but it was selected another completely different application.
* The proposal was created with a forum application.

extrinsics
#83028

ProposalDetailsOf
{
  FillWorkingGroupLeadOpening: {
    opening_id: 0
    successful_application_id: 0
    working_group: Forum
  }
}

* Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3ab90db8-7c0b-412a-a8b9-670e6d12eabc-annotated_fdf2e276-80c0-47fa-a523-e8dfd5c14b47.png?etag=e4eb64651f327f1f17bbc049e9d66115)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3ab90db8-7c0b-412a-a8b9-670e6d12eabc-annotated_fdf2e276-80c0-47fa-a523-e8dfd5c14b47.png?etag=e4eb64651f327f1f17bbc049e9d66115)_

**Browser**: Chrome 98 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1244x1324
**[Open #43 in Usersnap](https://app.usersnap.com/l/feedback/2b441217-b509-4cb7-a37e-4c229579662e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201905668007024) by [Unito](https://www.unito.io)

**Comment by freakstatic** [comment]
Proposal link:
https://pioneer-2.vercel.app/#/proposals/preview/38

**Comment by freakstatic** [comment]
![Screenshot from 2022-03-02 00-23-57](https://user-images.githubusercontent.com/7486476/156272590-d838ec3c-c8c6-4750-bba6-80a2dd4ddacb.png)

**Comment by dmtrjsg** [comment]
Duplicate of #2340
