### ISSUE TITLE
Bounty Funding Expired Period

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2393]
## Scope
* [ ] Add Bounty Funding Expired stage, if no contributions were made
* [ ] Cancel button is visible for creator
* [ ] Cherry is withdrawn by the creator

[Figma link](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=325%3A150830)

[Handbook link](https://joystream.gitbook.io/testnet-workspace/system/bounties#cancel-bounty)

Context:

![Screenshot 2022-03-02 at 19.53.25.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/eec62cf0-a81c-4018-85a6-cb61286ca268)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201909448342567) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Blocked to be (re-tested) by mappings fix on QN side (Lezsek) and Runtime..

**Comment by mnaamani** [comment]
Fixed in bounty mappings
