### ISSUE TITLE
Application to opening: staking amount in side panel is taken from proposal instead of opening (not blocking)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2394]
## Context 

Staking amount shown in application flow for opening  is incorrect, and seems to be taken from proposal staking requirements (at the time of creating proposal to create this opening) instead of opening data.

See where the cursor is for the object to get fixed
 
![Screenshot 2022-03-03 at 10.52.20.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/29ede87b-6ff3-4818-83f0-2c2c9d0f73ee)

## Scope

- Show staking required on the application, that was specified during the respective opening creation (in this field)
<img width="1293" alt="Screenshot 2022-04-07 at 13 47 00" src="https://user-images.githubusercontent.com/93924525/162202144-3314c669-9ddc-4a76-9a7c-ff7c4c2da193.png">

**Comment by singulart** [comment]
@dmtrjsg I can't assign issues, can you check my permissions, please?

**Comment by oleksanderkorn** [comment]
@dmtrjsg  Should the staking shown here?
<img width="194" alt="image" src="https://user-images.githubusercontent.com/9252017/164997967-91e3cab7-3b0a-42a2-881f-e07a8330f954.png">

Or in the same place as before, but the correct amount?
<img width="161" alt="image" src="https://user-images.githubusercontent.com/9252017/164997990-5085a7e6-d536-4886-a3dc-77943a0e2ae2.png">

**Comment by dmtrjsg** [comment]
@oleksanderkorn

Thank you for your question! 

Re where to show: 

- Side panel (under "Stake required" label)
- Pre-populated input field (with minimum value)

**Comment by singulart** [comment]
JSG please re-review.

**Comment by singulart** [comment]
Validated on Staging, works as expected. 
<img width="1257" alt="Screenshot 2022-04-30 at 00 32 41" src="https://user-images.githubusercontent.com/7863785/166072008-5fa29868-e093-4083-8501-b77a9a54b224.png">
