### ISSUE TITLE
Voting flow results in blank page when started w/o membership pre-selected

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2403]
https://www.loom.com/share/bef5e8c5c16c4bcc9b18b4532762c3c9

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201976998546833) by [Unito](https://www.unito.io)

**Comment by bwhm** [comment]
This was still the case for me on chrome.

**Comment by dmtrjsg** [comment]
Fixed, looking good!
