### ISSUE TITLE
Active Applications counter on opening card

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2404]
## Scope

- [ ]  Opening list applications counter needs to show only active applications

## Details

**Taken at**: https://pioneer-2.vercel.app/#/working-groups/forum
**Fields**:
- Houston, we have a problem.: This application was withdrawn
- Give us some details: Three options:
1. Leave as is (there was an application)
2. Count the active application only
3. Include an additional field for withdrawn applications

I&#39;d say 1 or 2.
- -
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/301f0f0c-a14b-4ba4-837a-962e72a4635d-annotated_69ffc6b9-0806-44df-abd4-0c62923d096e.png?etag=e2c9c00db965c847e0781a7946f77c18)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/301f0f0c-a14b-4ba4-837a-962e72a4635d-annotated_69ffc6b9-0806-44df-abd4-0c62923d096e.png?etag=e2c9c00db965c847e0781a7946f77c18)*

**Browser**: Chrome 98 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2560x1338
**[Open #44 in Usersnap](https://app.usersnap.com/l/feedback/46f29e86-829f-4e22-b56e-f9abceb78c20?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by adovrodion** [comment]
Bounty link: https://dao.joystream.org/#/bounty/preview/53

**Comment by traumschule** [comment]
`opening.hiring` used [OpeningDetails.tsx](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx#L49) doesn't contain the number of withdrawn applications, only [current and limit](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/working-groups/types/WorkingGroupOpening.ts#L52).
How much effort is it to update the fragments?

**Comment by WRadoslaw** [comment]
Fixed by #3732
