### ISSUE TITLE
Bounty Tabs content: Works/ Winners/ Slashed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2413]
Displaying Winners and Slashed Workers for bounties:

- [x]  content of winners tab needs to be re-done based on designs [FIGMA>](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=319%3A145491)
- [x] Second tab needs to be "Slashed" and display slashed entrants and their slashed amount
[Link to Figma ](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=328%3A157317)
- [x] Show contents of work Tab  [FIGMA> ](https://www.figma.com/file/jZwIoaxOkTxNFMJNzssBgv/Bounty?node-id=289%3A192155)
- [ ] ⚠️ re-test if Terminated bounties display winners/ losers/ slashed correctly.

![Screenshot 2022-03-03 at 19.58.01.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/3ea4af1e-3766-4a70-85cd-122a00a59490)

**Comment by polikosi** [comment]
Winners page displayed right:
![win](https://user-images.githubusercontent.com/80429191/168305370-b6c709e8-7860-41b6-b66b-2e2796760e00.png)

Works Tab displayed right:
![works tab](https://user-images.githubusercontent.com/80429191/168305528-9d398b13-cece-461c-98fe-099e275c3823.png)

Slashed page not right:
1. Slashed amount isn't displayed 
2. Rationale isn't displayed
3. In the sidebar does not display what were slashed
![slashed](https://user-images.githubusercontent.com/80429191/168307201-d86378de-6849-4b67-b804-2512eef36ccc.png)

**Comment by dmtrjsg** [comment]
1. Rationale

Agreed to show rationale re-using this design pattern:

<img width="1138" alt="Screenshot 2022-05-17 at 09 16 05" src="https://user-images.githubusercontent.com/93924525/168763966-80d01c0e-bfdc-48d0-b9fe-7b3a4ff15c16.png">

NB: Rationale is a single text input that applies to all entries for bounty judgement.

2. Slashed amount (this is always = full stake of applicant) we will try and display it
3. Description will not be provided for each candidate/ not part of the runtime design

**Comment by dmtrjsg** [comment]
@WRadoslaw 

Copy:

"
You won the bounty!
Oracle judgement chose your work as winning. You can now recover your stake and claim reward!
"

"Your submission did not win.
You can withdraw your stake now and try next time!"

"You got slashed!
Your stake is now burned."

**Comment by dmtrjsg** [comment]
+ pls ⚠️ re-test if Terminated bounties display winners/ losers/ slashed correctly. As per 3105.

**Comment by polikosi** [comment]
Won displayed right:
![Screenshot_90](https://user-images.githubusercontent.com/80429191/172146251-dfc7c5ee-ca89-4903-ae5b-447db06273af.png)

Works Tab displayed right:
![Screenshot_91](https://user-images.githubusercontent.com/80429191/172146462-5ecc9a5c-531e-43c8-b0a4-5fa0909e4a9f.png)

Slashed displayed right:
![Screenshot_92](https://user-images.githubusercontent.com/80429191/172146559-34f14752-e642-4242-ab43-c321af82460a.png)

Not win displayed right:
![Screenshot_93](https://user-images.githubusercontent.com/80429191/172147008-14670971-8256-461a-8a7d-50b8963a6ef7.png)

⚠️ Terminated bounties don't display winners/ losers/ slashed correctly
![Screenshot_94](https://user-images.githubusercontent.com/80429191/172147523-11e6715a-8b8a-4d8a-af35-ecd5a2942d31.png)

**Comment by dmtrjsg** [comment]
fix applied

**Comment by polikosi** [comment]
verified on https://pioneer-2-git-fix-show-tab-on-terminated-bounty-joystream.vercel.app/#/bounty/past
works as expected:
![Screenshot_104](https://user-images.githubusercontent.com/80429191/173192005-d0078de7-0a6f-4700-9790-6aa8ec28df1e.png)


verified on https://dao-git-fix-show-tab-on-terminated-bounty-joystream.vercel.app/#/working-groups
works as expected:
![Screenshot_105](https://user-images.githubusercontent.com/80429191/173192078-d5929d31-de61-4fe6-a1c5-66c448e36e28.png)
