### ISSUE TITLE
[USERSNAP] Transaction failed when applying for Forum WG lead position

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2417]
**Taken at**: https://pioneer-2.vercel.app/#/working-groups/forum
**Fields**:
- Houston, we have a problem.: Transaction failed when applying for Forum WG lead position
- Give us some details: Unknown - tried it twice
- Unknown - tried it twice
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a3beea7c-b8e6-401e-8f41-4e5ff4cf9769-annotated_026b9968-4065-4908-88f3-69b2a5f1f7e7.png?etag=59f7f36e3810e4bdb2487d082152cfb7)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a3beea7c-b8e6-401e-8f41-4e5ff4cf9769-annotated_026b9968-4065-4908-88f3-69b2a5f1f7e7.png?etag=59f7f36e3810e4bdb2487d082152cfb7)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1319
**[Open #45 in Usersnap](https://app.usersnap.com/l/feedback/ac409c20-5223-4643-a1e6-78b943c02272?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
appears to be related to this:
![image](https://user-images.githubusercontent.com/50830161/156679805-62686d9d-3251-4481-983a-c30cc44a767e.png)

**Comment by bwhm** [comment]
Hey @mochet 
It appears as though you made this work ~100 blocks later, so I assume it was a user error?
- If yes - please close.
- If no - please share how you succeeded?

**Comment by mochet** [comment]
> Hey @mochet It appears as though you made this work ~100 blocks later, so I assume it was a user error?
> 
> * If yes - please close.
> * If no - please share how you succeeded?

I remember trying to submit this multiple times with the same failure.
The applying member was `tom-62` and the stake account was `tom-68`

I succeeded via manual extrinsic submission of the same information:
* Submitting via extrinsics:
			* Added relationship: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F3.87.51.41.nip.io%2Fws-rpc#/explorer/query/0x0e72eac2f73cf0117b3f75d0d86642f986e745ec2e548868e1e134b60c1f0df4
			* Confirmed relationship: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F3.87.51.41.nip.io%2Fws-rpc#/explorer/query/0x8f01d0dc309f0e9dba1b04d71635450076465a4763eee35ceaed28d294011a04
			* Applied: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F3.87.51.41.nip.io%2Fws-rpc#/explorer/query/0x712eababfa868f835c76464780ebf2cafa1e052ea50c4c84c99c47cc3bdbb69b

**Comment by mochet** [comment]
@bwhm I think I may have a possible idea for why this happened. Perhaps when you reset all the stake relationships, it assumed the invitation had already been sent from the staking account, when it hadn't been?
That's at least what it looks like happened in the transaction link to me.

**Comment by dmtrjsg** [comment]
To be retested.

**Comment by mochet** [comment]
> To be retested.

This has basically been replicated here: https://github.com/Joystream/pioneer/issues/2512

Don't know which issue to close so will leave it up to you--the newer one has more details

**Comment by mochet** [comment]
* Distribution
	* Apply: 140
	* stake: 140
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xc74ffdb04583e0fd411775eadac296ce97faa165f2c3df7b4c608bcd9bbdec28
* Content
	* Apply: 141
	* Stake: 141
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xda1001c106c3890273580714dbf16b6e9ee8464e9a3f9a817db9b2a7e5096e14
* Forum
	* Apply: 142
	* Stake: 142
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x82611f6534ee45465f782567dc903247ff8018185fb618c824ed885ccbf0db65
* Gateway
	* Apply: 143
	* Stake: 143
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xe6600d1ffeeb5352302a40758f2652be06f795e7857a08965996528d2e954c1b
* Storage
	* Apply: 144
	* Stake: 144
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xaa9b91458ac582bb63217890707b89d93a4383143037a7395bf2eab0731a47db
	* Trying with different stake
		* Apply: 144
		* Stake: 145
		* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x0645e41b87fdf4d0776b74fb20915dd917c2587eaf2f7b8ceb89eb066781587e
* Operations Alpha
	* Doesn't load in Pioneer
* Operations Beta
	* Doesn't load in Pioneer
* Operations Gamma
	* Doesn't load in Pioneer
