### ISSUE TITLE
[USERSNAP] Operations groups (alpha, beta, gamma) openings/ about/ history tabs - eternal loading

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2418]
**Taken at**: https://pioneer-2.vercel.app/#/working-groups/operations-alpha
**Fields**:

* Houston, we have a problem.: Cannot load the &#34;information&#34; page of any of the operations group
* Give us some details: The page seems to be stuck at loading forever. It affects the alpha, gamma and beta working group
* no idea...
* Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bc3c511a-a1bd-44ba-8092-e3816fd54d09-annotated_c8b441a1-4038-432a-9382-67bb9128c6dd.png?etag=448cebc048fe0cb7d4bb8d53132ad11f)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bc3c511a-a1bd-44ba-8092-e3816fd54d09-annotated_c8b441a1-4038-432a-9382-67bb9128c6dd.png?etag=448cebc048fe0cb7d4bb8d53132ad11f)_

**Browser**: Chrome 98 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1372x1297
**[Open #46 in Usersnap](https://app.usersnap.com/l/feedback/57c1e533-3c95-49cf-a059-bc4fc1763ac2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201934987680368) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
Suggesting `olympia` label for this issue, it is critical.

**Comment by mnaamani** [comment]
Resolved
