### ISSUE TITLE
[USERSNAP] Text says "opening to cancel" instead of "select applicant to hire" (Fill WG lead proposal for forum WG)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2419]
## Scope

- [ ] update placeholder copy for _opening_ selection to "Choose opening to fill"
- [ ] update application copy to "Choose application"

______________

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Text says &#34;opening to cancel&#34; instead of &#34;select applicant to hire&#34; (Fill WG lead proposal for forum WG)
- Give us some details: Text says &#34;opening to cancel&#34; instead of &#34;select applicant to hire&#34; (Fill WG lead proposal for forum WG)
- Text says &#34;opening to cancel&#34; instead of &#34;select applicant to hire&#34; (Fill WG lead proposal for forum WG)
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e2e21f13-5b47-4be9-bc9a-03d200f44ded-annotated_7edf4cf0-7869-489c-b9cd-683f325172ff.png?etag=a5fb19e3cb033258f046c37522b35467)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e2e21f13-5b47-4be9-bc9a-03d200f44ded-annotated_7edf4cf0-7869-489c-b9cd-683f325172ff.png?etag=a5fb19e3cb033258f046c37522b35467)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #47 in Usersnap](https://app.usersnap.com/l/feedback/6bd8261a-7f10-44cd-ad1d-eb8a8f4d4764?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by singulart** [comment]
@dmtrjsg can this be moved to ready for test?

**Comment by dmtrjsg** [comment]
@singulart yep, can be tested on staging. all tickets with label:stabilisation4 are ready for test!

**Comment by polikosi** [comment]
Verified on staging.  Test evidences below: 
![Screenshot_5](https://user-images.githubusercontent.com/80429191/167164467-7147f3a7-c5ad-4659-8473-ae5d54667aea.png)
