### ISSUE TITLE
[USERSNAP] No option to edit post, only edit thread (maybe)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2420]
**Taken at**: https://pioneer-2.vercel.app/#/forum/thread/1
**Fields**:
- Houston, we have a problem.: No option to edit post, only edit thread (maybe)
- Give us some details: Some posts aren&#39;t editable, so I am not sure if this is intended behavior or not.
- Some posts aren&#39;t editable, so I am not sure if this is intended behavior or not.
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/fb29f1c9-a821-4b91-98b5-ae9baf8e68df-annotated_cb48de9c-5b78-45e9-8e30-71ae80cdbc6f.png?etag=28ad0014c85e2673b4d3ed9094af8378)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/fb29f1c9-a821-4b91-98b5-ae9baf8e68df-annotated_cb48de9c-5b78-45e9-8e30-71ae80cdbc6f.png?etag=28ad0014c85e2673b4d3ed9094af8378)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #48 in Usersnap](https://app.usersnap.com/l/feedback/01a5607e-36b1-4a47-b061-b9d7a62b0329?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
This can be closed--creating a different issue as this isn't a fault
