### ISSUE TITLE
[USERSNAP] history of edits to a post doesn't show the original version of the post

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2421]
- [ ] Show original post in the history of post edits

[FIGmA > ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=6577%3A157605)

Preview:

<img width="971" alt="Screenshot 2022-05-04 at 17 12 45" src="https://user-images.githubusercontent.com/93924525/166724711-4c2f6295-35be-4641-8a97-c00cd2d2de81.png">

__________________

**Taken at**: https://pioneer-2.vercel.app/#/forum/thread/1
**Fields**:
- Houston, we have a problem.: history of edits to a post doesn&#39;t show the original version of the post
- Give us some details: history of edits to a post doesn&#39;t show the original version of the post
- history of edits to a post doesn&#39;t show the original version of the post
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6b0b6eba-c957-4daa-9f0a-a73f79b8eb5d-annotated_ae53057f-0cc9-43b5-831a-1bc1b7a0fd17.png?etag=33f8bd7f1c09dcb1942f74e0705ff124)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6b0b6eba-c957-4daa-9f0a-a73f79b8eb5d-annotated_ae53057f-0cc9-43b5-831a-1bc1b7a0fd17.png?etag=33f8bd7f1c09dcb1942f74e0705ff124)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #49 in Usersnap](https://app.usersnap.com/l/feedback/0ee76cb9-6a37-4529-b487-6e4b6150c462?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/37
wss://34.230.5.182.nip.io/ws-rpc

Works as expected

<img width="1255" alt="Снимок экрана 2023-01-30 в 16 06 00" src="https://user-images.githubusercontent.com/46903215/215499323-223fb4ce-b66f-4660-8838-29f7e3a2be80.png">

**Comment by chrlschwb** [comment]
Is the Thread history feature disabled?

**Comment by thesan** [comment]
> Is the Thread history feature disabled?

No it's available. See: https://pioneer-2.vercel.app/#/forum/thread/99?post=1170 (the network should be set to Mainnet).

![image](https://user-images.githubusercontent.com/6571453/227501300-5bb885a6-2d0f-46b2-a1ca-8233a2aa3d7f.png)

I'm closing it. Maybe it was some temporary bug on `dev`.

That said IMO you shouldn't need to pick a membership to see the post history of edits.
