### ISSUE TITLE
[USERSNAP] Wrong working group on "update budget proposal" for operations

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2422]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Wrong working group on &#34;update budget proposal&#34; for operations
- Give us some details: When a operations working is selected the proposal is created with the Forum WG instead of the operations one
- The extrinsic submitted has the wrong WG 

{
  member_id: 124
  title: Update gamma budget
  description: gamma
  staking_account_id: 5HeQGqdsFPNaSD32vZcUsqYoamy2EyXhr2u9toebfcRSJGQ5
  exact_execution_block: null
}
ProposalDetailsOf
{
  UpdateWorkingGroupBudget: [
    8.0000 MJOY
    Forum
    Positive
  ]
}
- Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7b50b771-8f32-4dec-b1ef-1fb594da56b8-annotated_5944dfe3-ed02-4e17-9152-c7a75b32e713.png?etag=5d7fa4642666e3b2c38add356aa0410f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7b50b771-8f32-4dec-b1ef-1fb594da56b8-annotated_5944dfe3-ed02-4e17-9152-c7a75b32e713.png?etag=5d7fa4642666e3b2c38add356aa0410f)*

**Browser**: Chrome 98 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1372x1297
**[Open #50 in Usersnap](https://app.usersnap.com/l/feedback/ec4bd18c-32bd-4eb4-9a7f-251795da9203?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
This is critical

**Comment by dmtrjsg** [comment]
This looks like an issue we'd need to retest after https://github.com/Joystream/pioneer/issues/2376 is merged (currently on code review, merge ETA = tomorrow (8March)

@stepien4soft @thesan FYI
