### ISSUE TITLE
Posts with bullet points sometimes include a ">" character

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2425]
- [ ] Fix alignment of Bullet points and show them as dots.

This uses external lib (ck editor) we want to add a fix on our end **(upd REAct markdown)** as opposed to tempering with the ck editor lib.

@Dev ⚠️  do not spend more than 3 SP on this. Speak to WGl and @thesan if this turns to be harder than expected.

______
**Taken at**: https://pioneer-2.vercel.app/#/forum/thread/1
**Fields**:
- Houston, we have a problem.: Forum: posts with bullet points sometimes include a &gt; character
- Give us some details: Forum: posts with bullet points sometimes include a &gt; character
- Forum: posts with bullet points sometimes include a &gt; character
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/100b6e50-597b-46ca-833c-b41f482713c4-annotated_91ae9694-42bd-4b69-918f-42b482f56cc4.png?etag=d59a40e8aa924c3399aeb4306988372b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/100b6e50-597b-46ca-833c-b41f482713c4-annotated_91ae9694-42bd-4b69-918f-42b482f56cc4.png?etag=d59a40e8aa924c3399aeb4306988372b)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #53 in Usersnap](https://app.usersnap.com/l/feedback/8dda6c94-5a20-45b0-8a0b-29e3af44a786?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by singulart** [comment]
Requires testing

**Comment by ivanturlakov** [comment]
Tested on staging

The bullet points looks good
<img width="1440" alt="Снимок экрана 2022-06-14 в 11 40 15" src="https://user-images.githubusercontent.com/46903215/173534360-d0ecee04-d51a-4e1c-8620-4a811f101ac8.png">
