### ISSUE TITLE
[USERSNAP] WG> Openings: "Currently Staking" Widget shows wrong number

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2427]
**Taken at**: https://pioneer-2.vercel.app/#/working-groups/openings
**Fields**:
- Houston, we have a problem.: Working groups: Currently Staking is wildly incorrect
- Give us some details: Working groups: Currently Staking is wildly incorrect
- Working groups: Currently Staking is wildly incorrect
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8956ba1b-9f83-4bd4-a616-03c7d69b1af3-annotated_761ce13f-1c73-4a96-9b27-6b313f75c477.png?etag=3b662bb23cd03200f93618c2d4f3398a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8956ba1b-9f83-4bd4-a616-03c7d69b1af3-annotated_761ce13f-1c73-4a96-9b27-6b313f75c477.png?etag=3b662bb23cd03200f93618c2d4f3398a)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #55 in Usersnap](https://app.usersnap.com/l/feedback/55b293f8-7b5c-472c-b653-e9a3501e8739?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Resolved here > https://github.com/Joystream/pioneer/issues/2539

**Comment by singulart** [comment]
Tested here: https://pioneer-2-git-fork-oleksanderkorn-bugfix-total-819f70-joystream.vercel.app/

**Comment by dmtrjsg** [comment]
@singulart we'd need to test on https://dao-git-staging-joystream.vercel.app/.. And also FYI on labels:

<img width="353" alt="Screenshot 2022-04-11 at 21 06 01" src="https://user-images.githubusercontent.com/93924525/162823054-c96f038b-6034-4ca1-8193-42d8bdce3c81.png">

**Comment by dmtrjsg** [comment]
@singulart pls check the overall process for broader reference [here >](https://miro.com/app/board/uXjVOAJpORw=/)

**Comment by singulart** [comment]
Adding labels requires some special permissions?

**Comment by dmtrjsg** [comment]
This may require the "collaborator" access, and the permissions in GH are managed by @bwhm.

**Comment by dmtrjsg** [comment]
@singulart in the meantime, pls feel free to add the outcome of the test as a _simple comment and move the ticket to the right lane in the Project 55 + assign to @dmtrjsg _

**Comment by singulart** [comment]
Staging test Evidence 

<img width="1005" alt="Screenshot 2022-04-14 at 12 26 39" src="https://user-images.githubusercontent.com/7863785/163356217-6da19476-5ed5-4941-bb7a-bfd6939ef8db.png">
