### ISSUE TITLE
[USERSNAP] Forum/Global: After cancelling a transaction in polkadot-js, some buttons don't work

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2434]
**Taken at**: https://pioneer-2.vercel.app/#/forum/category/2
**Fields**:
- Houston, we have a problem.: Forum/Global: After cancelling a transaction in polkadot-js, some buttons don&#39;t work
- Give us some details: Only shown is the &#34;add new thread&#34; button but I think I also encountered this elsewhere, will update if I find other examples
- Only shown is the &#34;add new thread&#34; button but I think I also encountered this elsewhere, will update if I find other examples
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/198767b5-1ab9-45a6-b587-4d6507ef2445-annotated_dda1e0c7-0aae-41e4-8ccf-866ef850f6c6.png?etag=d55587babb114c04f03466f28ee5c96a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/198767b5-1ab9-45a6-b587-4d6507ef2445-annotated_dda1e0c7-0aae-41e4-8ccf-866ef850f6c6.png?etag=d55587babb114c04f03466f28ee5c96a)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #61 in Usersnap](https://app.usersnap.com/l/feedback/003ba133-9f47-4e2c-ac81-ca15cfca1a74?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
I forgot to highlight the button, but its the `Add New Thread` button in the top right. If I click it after cancelling it doesn't do anything.

**Comment by mochet** [comment]
Closing as this behaviour exists on https://polkadot.js.org/ as well so is probably a wallet problem.
