### ISSUE TITLE
Forum:Clicking Replied post which is located on the Same Page loads Pioneer again

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2440]
# Scope
this is a fix

* [ ] Implement anchors for forum posts and replies.  and upon click move screen focus to the anchor link instead of reloading if link is on the same page.

:warning:  there's already an anchor system in place.

________--

**Taken at**: https://pioneer-2.vercel.app/#/forum/thread/5?page=2
**Fields**:

* Houston, we have a problem.: Forum: clicking a replied post which is located on the same page loads Pioneer again
* Give us some details: This should use anchors and not have to reload entirely (in an ideal world)
* This should use anchors and not have to reload entirely (in an ideal world)
* Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5f430dc8-b424-43eb-8146-ca0d5f401c20-annotated_e646e0f8-e96f-4917-9c9d-9a2a8bbd0719.png?etag=552a917846362dcb175e9f8338979a00)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5f430dc8-b424-43eb-8146-ca0d5f401c20-annotated_e646e0f8-e96f-4917-9c9d-9a2a8bbd0719.png?etag=552a917846362dcb175e9f8338979a00)_

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #67 in Usersnap](https://app.usersnap.com/l/feedback/c2ac91d1-ba41-401e-9880-c44bf97984d3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464664511746) by [Unito](https://www.unito.io)

**Comment by polikosi** [comment]
works as expected

https://user-images.githubusercontent.com/80429191/205079576-02070570-fdbd-4ef2-9c63-dc690d168817.mp4
