### ISSUE TITLE
Add "previous step" button to Application for role

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2445]
- [ ] Add previous step button to opening application flow

**Taken at**: https://pioneer-2.vercel.app/#/working-groups/gateway
**Fields**:
- Houston, we have a problem.: Applying for a role doesn&#39;t have a &#34;previous step&#34; button
- Give us some details: I can&#39;t go back to correct something from the previous step (&#34;Stake&#34;)
- There is no button to the previous step
- Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/cf898ca1-eb97-41ac-8b8b-64a1b6463151-annotated_8a7b8b41-7ed5-49af-b12f-cb4cdc6fbabe.png?etag=a6a7eadf337e50afc1d0916cb3403bb0)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/cf898ca1-eb97-41ac-8b8b-64a1b6463151-annotated_8a7b8b41-7ed5-49af-b12f-cb4cdc6fbabe.png?etag=a6a7eadf337e50afc1d0916cb3403bb0)*

**Browser**: Chrome 98 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1372x1297
**[Open #72 in Usersnap](https://app.usersnap.com/l/feedback/fa518ad0-f909-4817-8ac5-f2b5fc9d99b7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
this is minor, can be added later on

**Comment by ytdbuolf** [comment]
Accepted for issue #2445

**Comment by freakstatic** [comment]
@singulart please assign
