### ISSUE TITLE
[USERSNAP] Add pagination to past proposals (>50 ID are not visible)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2446]
## Scope

- [ ] Add pagination to proposals, 
- [ ] For current and past proposals > paginate by 10

## Tech 
___
**Taken at**: https://pioneer-2.vercel.app/#/proposals/past
**Fields**:
- Houston, we have a problem.: Past proposal list doesn&#39;t have pagination
- Give us some details: I can&#39;t check proposals over ID 50 (without using filters)
- There is no pagination controls to go the next proposals. Also I think the proposals should be ordered by descending order of the created block / created date, so that newer proposals appear first.
- Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8674f567-030a-4d1c-b754-fdc921023810-annotated_1d0807d3-8607-4d29-8735-a9c379b8513b.png?etag=eb6ad31c42022918686077bf534162a2)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8674f567-030a-4d1c-b754-fdc921023810-annotated_1d0807d3-8607-4d29-8735-a9c379b8513b.png?etag=eb6ad31c42022918686077bf534162a2)*

**Browser**: Chrome 98 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1372x1297
**[Open #73 in Usersnap](https://app.usersnap.com/l/feedback/836ff4e6-fd6c-41c6-9246-9ea46da62597?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
* Sorting of proposals covered in this issue: https://github.com/Joystream/pioneer/issues/2294
* Pagination is a problem and have verified it exists.
