### ISSUE TITLE
App crashes in Tor Browser

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#2454]
[Tor Browser](https://www.torproject.org/) is a privacy enhanced Firefox patch that refuses to load Pioneer:

> Loading failed for <script> with ..livesession..

> Cookie has been rejected as third-party.

> DOMException: The operation is insecure.

![](https://cdn.discordapp.com/attachments/942165812054220872/949454341570428948/pioneer2-tbb.png)

**Comment by dmtrjsg** [comment]
Livesession is a user sesion tracking app, which the product team will be using to enhance user experience and work on app improvements. Related Privacy policy and cookies consent will be added at a later stage.
