### ISSUE TITLE
[USERSNAP] Incorrect staking amount displayed for all Leads and Workers

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2459]
**Taken at**: https://pioneer-2.vercel.app/#/working-groups/distribution
**Fields**:
- Houston, we have a problem.: Incorrect staking amount displayed for all Leads
- Give us some details: The actual amount staked was 50k.
- This amount is the same as the stake for creating the  Create Lead Opening Proposal.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dd543ccb-9874-4976-b873-998e40f05b59-annotated_14101d7d-7cb9-43a8-9815-2800add39dbf.png?etag=4bc576eae3425cb2f20f377e929bb614)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dd543ccb-9874-4976-b873-998e40f05b59-annotated_14101d7d-7cb9-43a8-9815-2800add39dbf.png?etag=4bc576eae3425cb2f20f377e929bb614)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 1920x1200
**Browser size**: 1920x1000
**[Open #77 in Usersnap](https://app.usersnap.com/l/feedback/37454b37-a22d-4bef-a08e-126d23acd01a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
It turns out to be the case for workers as well...
