### ISSUE TITLE
[USERSNAP] Invite a member: Selecting an option on the member field doesn't keep the option selected

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2461]
**Taken at**: https://pioneer-2.vercel.app/#/profile/memberships
**Fields**:
- Houston, we have a problem.: Invite a member: Selecting an option on the member field doesn&#39;t keep the option selected
- Give us some details: When I select a member on `inviting member` field It get&#39;s selected internally but the field is not updated
- The field isn&#39;t being updated when an option is selected
- Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ff014f12-9402-4dd4-8914-1f9c9b9c7268-annotated_fd8ae1a7-c4fa-468d-b7f3-eb86eb8cb571.png?etag=711f1c194acc7bb7c762f21199984247)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ff014f12-9402-4dd4-8914-1f9c9b9c7268-annotated_fd8ae1a7-c4fa-468d-b7f3-eb86eb8cb571.png?etag=711f1c194acc7bb7c762f21199984247)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1244x1324
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/630138e0-2a1d-4b02-9b76-4e86a6d484b3_screen_recording_d7581eb0-0fb1-436c-a899-7c6d62f59978.webm?etag=215e73be45c620b347b1c21471cbfee4)**
**[Open #79 in Usersnap](https://app.usersnap.com/l/feedback/a7becff5-fafd-467c-8f12-19f8a7f26476?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
Closing as duplicate / very closely related to: 
* https://github.com/Joystream/pioneer/issues/2359
* https://github.com/Joystream/pioneer/issues/2331
