### ISSUE TITLE
[USERSNAP] Gracing Time Left not showing on proposals

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2464]
## Scope

- [ ] Display gracing period duration on proposal details page

## Design

[Link to Figma Gracing PerioD Display Mockups >](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=235%3A6343)

PReview of mockups:

<img width="499" alt="Screenshot 2022-03-07 at 19 03 36" src="https://user-images.githubusercontent.com/93924525/157100706-1965075f-459f-4ea4-9a29-04d90906b3a0.png">

____________________

**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/85
**Fields**:
- Houston, we have a problem.: Proposal view: Memb. Inv. Quota grace period does not show
- Give us some details: The grace period of this proposal is `43,200 blocks` or 3 days.
Doesn&#39;t seem to show this calculation like the other proposals do.
- Probably hasn&#39;t been tested with proposals with such high grace periods.
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/215563a0-cc89-4c8e-b3b2-330713d673ec-annotated_1364ebdf-4fca-4bd0-a883-994c0bd66902.png?etag=bcfbd90b130cf47fd55f2408e59f4b3b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/215563a0-cc89-4c8e-b3b2-330713d673ec-annotated_1364ebdf-4fca-4bd0-a883-994c0bd66902.png?etag=bcfbd90b130cf47fd55f2408e59f4b3b)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1945x1237
**[Open #82 in Usersnap](https://app.usersnap.com/l/feedback/1b5e51eb-d4f0-4ec0-8953-762355f29484?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
Although its a bug, its not completely mission critical.

I suspect all other proposals that will have longer grace periods will also have this same issue.

**Comment by polikosi** [comment]
verified on staging. Test evidence below: 
![Screenshot_98](https://user-images.githubusercontent.com/80429191/172361255-58fd285e-5cb3-47e3-80a3-9cc6853b8233.png)
![Screenshot_99](https://user-images.githubusercontent.com/80429191/172361318-e3fa0425-df78-4ff8-afdf-6df431f47e77.png)
