### ISSUE TITLE
[USERSNAP] Proposals: Set Max Validator Count has a wrong field type

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2467]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Proposals: Set Max Validator Count has a wrong field type
- Give us some details: The amount field is asking for a JOY unit which doesn&#39;t make sense for a &#34;max validator count&#34; value
- The field &#34;type&#34; was wrong attributed
- Discrod Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ea366150-cfc6-4915-a2c6-928d422cc623-annotated_68985b55-54b7-4d7c-947e-54800fd7907e.png?etag=4535fc12004074f3abdd45ef42f85631)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ea366150-cfc6-4915-a2c6-928d422cc623-annotated_68985b55-54b7-4d7c-947e-54800fd7907e.png?etag=4535fc12004074f3abdd45ef42f85631)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1244x1324
**[Open #85 in Usersnap](https://app.usersnap.com/l/feedback/9fa87ebd-1d84-4dde-8360-e41fd4403325?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
closed because this is closely related to: https://github.com/Joystream/pioneer/issues/2469
