### ISSUE TITLE
[USERSNAP] Proposals: Should "remember" which account was used for staking the last time a proposal was made by a membership

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2468]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Proposals: Should &#34;remember&#34; which account was used for staking the last time a proposal was made by a membership
- Give us some details: Proposals: Should &#34;remember&#34; which account was used for staking the last time a proposal was made by a membership
- Proposals: Should &#34;remember&#34; which account was used for staking the last time a proposal was made by a membership
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f085058c-2284-403d-9f32-5cdd944c493b-annotated_34b87fd6-4cbe-4129-a192-0f1a685c41ef.png?etag=7471f704bd1e0033be4de28b986a861e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f085058c-2284-403d-9f32-5cdd944c493b-annotated_34b87fd6-4cbe-4129-a192-0f1a685c41ef.png?etag=7471f704bd1e0033be4de28b986a861e)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1858x1148
**[Open #86 in Usersnap](https://app.usersnap.com/l/feedback/8a8b8713-8767-4bab-a45b-56e0a402637a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
This is a somewhat minor issue because the same staking account cannot be used to create more than one proposal at a time.
