### ISSUE TITLE
[USERSNAP] Overview: New user page shows weird info

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2472]
**Taken at**: https://pioneer-2.vercel.app/#/overview
**Fields**:
- Houston, we have a problem.: Overview: New user page shows weird info
- Give us some details: Overview: New user page shows weird info
- Overview: New user page shows weird info
- Discrod Handle: tomato:9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8e4c028c-ff83-4bb9-939b-fad13bc1ab6c-annotated_8c189b24-a00b-49a3-a385-61d8f2764ea5.png?etag=fa994c28385b7e2c23825ccafc25ff5d)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8e4c028c-ff83-4bb9-939b-fad13bc1ab6c-annotated_8c189b24-a00b-49a3-a385-61d8f2764ea5.png?etag=fa994c28385b7e2c23825ccafc25ff5d)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1858x1148
**[Open #89 in Usersnap](https://app.usersnap.com/l/feedback/dff61621-c89c-4909-ab92-686ab000fc4c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
Relatively minor issue.
