### ISSUE TITLE
Cannot create proposal with Closed Discussion Mode

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2474]
## Scope

- [x] Fix the closed discussion mode creation on proposal
>Pioneer takes User ID instead of Thread ID 

ℹ️  See details in cpmments

________________
VERY DETAILED EXPLANATION IS HERE>
- #2493 

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Proposals: Transaction for changing proposal thread to &#34;closed&#34; discussion failing
- Give us some details: Will include technical explanation in GitHub response
- Will include technical explanation in GitHub response
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/44f9a56a-898d-4fef-9a24-fe017446c68e-annotated_a91b1ad8-e7fd-4cbc-b5a3-404cc54d8849.png?etag=cddc069853c20dbf9e8747f624e79f84)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/44f9a56a-898d-4fef-9a24-fe017446c68e-annotated_a91b1ad8-e7fd-4cbc-b5a3-404cc54d8849.png?etag=cddc069853c20dbf9e8747f624e79f84)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1644x1148
**[Open #91 in Usersnap](https://app.usersnap.com/l/feedback/a90752f8-65a8-4e39-b1d5-3c32dfbf6f95?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
What appears to be happening is that the transaction generated by Pioneer is using `member ID` for all fields:
![image](https://user-images.githubusercontent.com/50830161/156947523-dee6e30b-c7cd-45f8-a207-be3c677c0ffd.png)

Context:
* I am member 72
* Thread that was actually created was `ThreadID: 102`
* Proposal ID: 102
![image](https://user-images.githubusercontent.com/50830161/156947610-9d4a1875-0625-439e-84d8-bee704de9494.png)



Console output:
```Transaction error: ExtrinsicFailed
on network: wss://3.87.51.41.nip.io/ws-rpc
in block: 0xcf5a89e69e4ce596bae5b0f4d0f812eff3d146af41f70398a27a567e7a934511
more details at: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xcf5a89e69e4ce596bae5b0f4d0f812eff3d146af41f70398a27a567e7a934511```

Verified a 2nd time:
https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xe6f27cb768dd1a420509cb7a59ced1b8bc6401f1c5bb8a60682dcc827ff7e0bd

**Comment by mochet** [comment]
This is critical for `closed discussion` or `whitelists` to work for any users.

**Comment by mochet** [comment]
Tested this and it works fine (except it allows for more users to be added than the maxwhitelist value is, resulting in a failure transaction)
- I tried with a signal proposal, 6 on whitelist: success
- I tried with a slash proposal, 1 on whitelist: success
- I tried with a signal proposal, 60+ on whitelist: TX failure (https://polkadot.js.org/apps/?rpc=wss://18.207.235.254.nip.io/ws-rpc#/explorer/query/0x573f8a861daf6b8fce16de4a0969f7e1db568613b336bbde920de506e68ea2b6)

**Comment by polikosi** [comment]
![photo_2022-04-27_13-50-08](https://user-images.githubusercontent.com/80429191/165502448-e9fad955-2a98-4574-b41e-f62cc04bd0dc.jpg)
![photo_2022-04-27_13-50-26](https://user-images.githubusercontent.com/80429191/165502454-bf94ab96-fe40-48c9-8458-07cfc1a35291.jpg)
