### ISSUE TITLE
[USERSNAP] Proposal: making a comment on proposal is successful, but doesn't detect QN

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2475]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/85
**Fields**:
- Houston, we have a problem.: Proposal: making a comment on proposal is successful, but doesn&#39;t detect QN
- Give us some details: (waited quite a while)
SSIA
- (waited quite a while)
SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/02aa2a06-ed2d-4116-9f3e-58feb5b8cecf-annotated_f196dd41-e8df-4ca5-a3c9-755d974fbc70.png?etag=afdec6fb85960bc9eef681999ee1ef1c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/02aa2a06-ed2d-4116-9f3e-58feb5b8cecf-annotated_f196dd41-e8df-4ca5-a3c9-755d974fbc70.png?etag=afdec6fb85960bc9eef681999ee1ef1c)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 2161x1148
**[Open #92 in Usersnap](https://app.usersnap.com/l/feedback/3bf97c93-f01f-473b-aa92-4d828ba44cec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
this ended up working fine, probably just QN was misbehaving
