### ISSUE TITLE
[USERSNAP] Cannot edit editable post

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2476]
## Scope

- [ ] Fix editing editable post on proposal
- [ ] This [bug] also makes the "delete reply" button identify the wrong post ID  - _What appears to be happening is that threadId and postId are swapped around in the transaction generated by Pioneer_
- [ ] Update types on Pioneer to prevent this from happening ⚠️
- [ ] Update the tests to track params in transactions

ℹ️ More info in comments

__________________

**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/85
**Fields**:
- Houston, we have a problem.: Proposal: Discussion post that is editable fails due to bad transaction
- Give us some details: SSIA will explain in GH reply
- SSIA will explain in GH reply
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e8172091-65f3-41a9-8207-b35a017427ab-annotated_b27362f6-289f-40f1-a744-aa4904a6cfb2.png?etag=3b5e005c4f572b14fc61b793bfb9ec15)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e8172091-65f3-41a9-8207-b35a017427ab-annotated_b27362f6-289f-40f1-a744-aa4904a6cfb2.png?etag=3b5e005c4f572b14fc61b793bfb9ec15)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1250x1148
**[Open #93 in Usersnap](https://app.usersnap.com/l/feedback/c3381c6e-5bac-4815-ba5c-13e81da8f45c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
What appears to be happening is that `threadId` and `postId` are swapped around in the transaction generated by Pioneer:
![image](https://user-images.githubusercontent.com/50830161/156948294-fd2b8261-a3ce-4fe2-ba7d-ba08d6ad7c8e.png)

(this was for `proposal 85` and it was `post 2`

Console output:
```
Transaction error: ExtrinsicFailed
on network: wss://3.87.51.41.nip.io/ws-rpc
in block: 0x3621dfce3f5878f8b1e6799532dfe5d272c49eb42b6d0666cd8c3a8302536f72
more details at: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x3621dfce3f5878f8b1e6799532dfe5d272c49eb42b6d0666cd8c3a8302536f72
t.<computed> @ 4a3bd40c437654e3b689.js:2
```

Failed TX link:
https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x3621dfce3f5878f8b1e6799532dfe5d272c49eb42b6d0666cd8c3a8302536f72

**Comment by traumschule** [comment]
just had the same editing a proposal post.

=> [transaction failed](https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/explorer/query/0x09007b1a702a33e5f19e327c2fc16546f87046f9659d2246068010946c858172)
![editpost](https://user-images.githubusercontent.com/31551045/164917105-cea608af-133b-4f2f-b790-6df2542030ff.png)
