### ISSUE TITLE
[USERSNAP] Proposals: Discussion: edit reply button only gives one line WYSIWYG editor instead of a text box

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2477]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/5
**Fields**:
- Houston, we have a problem.: Proposals: Discussion: edit reply button only gives one line WYSIWYG editor instead of a text box
- Give us some details: SSIA - screenshot/report button took too long to show actual issue, including better screenshot in GH comment.
- SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3090bc3c-6447-4645-80ea-c393589b270d-annotated_5b3e5ccb-a719-4ecf-8789-1370aa854bd2.png?etag=11da4720f96822931519ec706f647e7f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3090bc3c-6447-4645-80ea-c393589b270d-annotated_5b3e5ccb-a719-4ecf-8789-1370aa854bd2.png?etag=11da4720f96822931519ec706f647e7f)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1767x1148
**[Open #94 in Usersnap](https://app.usersnap.com/l/feedback/570da2c5-41ea-4783-bf79-ce41a7441293?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
This issue is really minor

- a 1 line post will get a 1 line WYSIWYG text box
![image](https://user-images.githubusercontent.com/50830161/156949088-c0acdc2a-1e97-4b1e-bdc7-44a919b289ab.png)

- a multiline post will get a multiline WYSIWYG text box
![image](https://user-images.githubusercontent.com/50830161/156949113-6c4b8075-a841-4e1f-9e0d-405fc8d6bc7c.png)

**Comment by mochet** [comment]
Closing because a user can just enter new lines by hitting enter.
