### ISSUE TITLE
[USERSNAP] Proposals: Discussion - opening edit mode for 3 posts and submitting only one generates bad TX

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2478]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/5
**Fields**:
- Houston, we have a problem.: Proposals: Discussion - opening edit mode for 3 posts and submitting only one generates bad TX
- Give us some details: 1. 3 edit boxes open (including one that is known to generate bad tx)
2. only submit 2nd edit box (should submit good tx)
3. tx failed
- 1. 3 edit boxes open (including one that is known to generate bad tx)
2. only submit 2nd edit box (should submit good tx)
3. tx failed
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0a2fa563-d903-435c-80f2-d104c810ced3-annotated_0dee6d3e-6383-4a73-b8bf-c671bffe8de2.png?etag=207badc2809ecab466b0d2df466e819b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0a2fa563-d903-435c-80f2-d104c810ced3-annotated_0dee6d3e-6383-4a73-b8bf-c671bffe8de2.png?etag=207badc2809ecab466b0d2df466e819b)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1898x1148
**[Open #95 in Usersnap](https://app.usersnap.com/l/feedback/bd103f40-e13b-4311-88a6-ff6d8405eb52?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
failed tx: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xc5bc54067bc3fc37113804e65c2ccb2dfda09c127cb542be30c552efed39fdb9

**Comment by mochet** [comment]
closing as heavily related to https://github.com/Joystream/pioneer/issues/2476
