### ISSUE TITLE
[USERSNAP] Proposals: Closed Discussion mode does not indicate who is on the whitelist

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2480]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/91
**Fields**:
- Houston, we have a problem.: Proposals: Closed Discussion mode does not indicate who is on the whitelist
- Give us some details: Users should be able to see who was whitelisted for a particular proposal&#39;s comments
- NA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a4067e67-6953-41b3-93c4-dad0f1d2aca0-annotated_3cefdd17-bc0a-4270-a98e-3548a83d2d7c.png?etag=0adae6c46c2d3dfd15054a74843507be)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a4067e67-6953-41b3-93c4-dad0f1d2aca0-annotated_3cefdd17-bc0a-4270-a98e-3548a83d2d7c.png?etag=0adae6c46c2d3dfd15054a74843507be)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 2415x1148
**[Open #97 in Usersnap](https://app.usersnap.com/l/feedback/6a6b43ad-0a59-4937-935e-58d04db20d6c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/#/proposals/preview/52
wss://34.230.5.182.nip.io/ws-rpc

### Proposal creator
<img width="1213" alt="Снимок экрана 2023-01-06 в 15 15 14" src="https://user-images.githubusercontent.com/46903215/211019720-c7515be2-79e8-4171-b17f-e27ce604e009.png">

### Not whitelisted user
<img width="1216" alt="Снимок экрана 2023-01-06 в 15 15 45" src="https://user-images.githubusercontent.com/46903215/211019969-3834a21f-337b-47c3-a00f-887fa7f3261f.png">

### Whitelisted user
<img width="1214" alt="Снимок экрана 2023-01-06 в 15 16 19" src="https://user-images.githubusercontent.com/46903215/211020079-b2cebba7-1022-4ff5-aaa5-21cfd5521af9.png">
