### ISSUE TITLE
Bounty [too many] Entrants ... 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2487]
- [ ] instead of passing the entrants, the app passes the mocks

______

URL: https://dmitry-pioneer.vercel.app/#/bounty/preview/9

![Screenshot 2022-03-07 at 20.23.46.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/1a7c6968-0885-45fe-8d19-7eef228b71f5)

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
![Screenshot_12](https://user-images.githubusercontent.com/80429191/168077202-3aade3ca-1f20-4bf4-af48-f66db60c15e5.png)
