### ISSUE TITLE
[USERSNAP] I can add Current CMs to whitelist

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2492]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/85
**Fields**:
- Houston, we have a problem.: I can add Current CMs to whitelist
- Give us some details: I don&#39;t think I should be.
- -
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/38f90309-6a4e-4dd8-a84a-aeb59a1f7889-annotated_5561967b-4970-4e77-b034-f4b39ee2eca4.png?etag=5d872b08ced72cb35aa067bc23987476)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/38f90309-6a4e-4dd8-a84a-aeb59a1f7889-annotated_5561967b-4970-4e77-b034-f4b39ee2eca4.png?etag=5d872b08ced72cb35aa067bc23987476)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2859x1608
**Browser size**: 2144x1117
**Labels**: enhancement
**[Open #101 in Usersnap](https://app.usersnap.com/l/feedback/7cc74dda-3bac-44fb-ab16-b975b7ede7d2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
I was allowed, which started me thinking - #2493
