### ISSUE TITLE
Display custom WG Opening Title: list, deets, application, fill wg proposal flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2501]
## Context

We are extending the fields on the metaprotocol for the opening, adding Opening Title in this ticket:
- #2395 

## Scope

Display Opening Title

<img width="615" alt="Screenshot 2022-03-09 at 09 15 59" src="https://user-images.githubusercontent.com/93924525/157410691-05ed29cb-ac96-4563-931b-2b4f6de60afc.png">

**Comment by dmtrjsg** [comment]
Suspect, the name of the issue was not correct, but the AC was.. Just tested:

Expected to see Custom Opening Title on _opening_ card (not proposal🤦‍♂️ )

<img width="1465" alt="Screenshot 2022-03-21 at 17 43 28" src="https://user-images.githubusercontent.com/93924525/159333984-77560122-527c-4b93-bd03-d7cb8c0b3035.png">
<img width="1404" alt="Screenshot 2022-03-21 at 17 43 35" src="https://user-images.githubusercontent.com/93924525/159333997-2868a655-cf18-4b78-a8d0-7bc50fbf4a6d.png">
<img width="624" alt="Screenshot 2022-03-21 at 17 47 45" src="https://user-images.githubusercontent.com/93924525/159334003-3cc2c4b0-3e3a-44d4-981c-df0b00f9cbcf.png">
<img width="1331" alt="Screenshot 2022-03-21 at 17 48 40" src="https://user-images.githubusercontent.com/93924525/159334008-17f0d71b-74c2-471a-a874-30f322596ecf.png">

**Comment by singulart** [comment]
[PASSED] Display custom Opening title on the Opening List card (in collapsed and expanded views)
<img width="1440" alt="Screenshot 2022-04-30 at 00 38 37" src="https://user-images.githubusercontent.com/7863785/166073320-b54fa3cb-a8ec-4ded-8c64-7a50e9a2d14b.png">


[PASSED] Display custom title on the Opening Details Page
<img width="906" alt="Screenshot 2022-04-30 at 00 38 45" src="https://user-images.githubusercontent.com/7863785/166073260-12251f2e-80bd-4ce0-9784-d3f534b3b9d4.png">

[FAILED] Display custom title on the Application / Opening Link from Applicant profile
<img width="466" alt="Screenshot 2022-04-30 at 00 40 59" src="https://user-images.githubusercontent.com/7863785/166073208-028c708e-1f9b-4427-ba4d-79214e034105.png">


[PASSED]Display custom title on the Fill WG lead Opening Proposal
<img width="732" alt="Screenshot 2022-04-30 at 00 45 20" src="https://user-images.githubusercontent.com/7863785/166073267-9d0d9776-ba3e-4f78-91d2-cd6dcd440ec3.png">
