### ISSUE TITLE
Rename WG names

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/pioneer#2502]
### Context
----
![image.png](https://images.zenhubusercontent.com/61b33b1e8ddbc86c62bdcd28/d8d85900-f825-43e4-bb94-96dac97cf3a1)

**Comment by dmtrjsg** [comment]
@stepien4soft just for convenience listing all proposal types to cover.. In addition to Proposals:
-  Create WGL opening 
- Fill WGL opening
- Slash Working Group Leader

We need to display updated names in all related WG proposals:
- Cancel WG lead opening
- Decrease WG Lead stake
- Terminate WG lead
- Set WG Lead Reward


- Update WG Budget
