### ISSUE TITLE
[USERSNAP] Mistakenly clicking "Cancel" on the signer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2504]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Mistakenly clicking &#34;Cancel&#34; on the signer
- Give us some details: I am now unable to:
- try clicking &#34;Create Proposal&#34; again
- go back, in an attempt to re-trigger (or edit if it wasn&#39;t a misclick)
- -
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e82b0368-66e0-4555-b351-ae06e535666f-annotated_3f73de17-65e8-4a44-aa58-8c8515cc1e81.png?etag=9207497d11eb5b08a9322d41b47ebc8e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e82b0368-66e0-4555-b351-ae06e535666f-annotated_3f73de17-65e8-4a44-aa58-8c8515cc1e81.png?etag=9207497d11eb5b08a9322d41b47ebc8e)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2560x1304
**Labels**: enhancement
**[Open #104 in Usersnap](https://app.usersnap.com/l/feedback/307417fc-78c7-488a-9f7d-575376cbd742?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
This issue is basically the same as https://github.com/Joystream/pioneer/issues/2434

The same behavior exists on polkadot.js.org so I am not sure if Pioneer can fix this.

**Comment by dmtrjsg** [comment]
Closing for same reasons as described here: https://github.com/Joystream/pioneer/issues/2434#issuecomment-1058775287a
