### ISSUE TITLE
[USERSNAP] Withdraw candidacy tooltip - "Lorum Ipsum"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2507]
## Scope

- [ ] Update the copy in the modal to. 

"Caution, this action is irreversible. Once you withdraw your candidacy, you will not be able to apply again with this account in the same election cycle, while still incurring the transaction costs for applying and withdrawing candidacy."

## Context

**Taken at**: https://pioneer-2.vercel.app/#/election
**Fields**:
- Houston, we have a problem.: Withdraw candidacy tooltip - &#34;Lorum Ipsum&#34;
- Give us some details: Should have real text
- -
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d0b169cb-1bf9-4671-967d-3caa43f39a19-annotated_deff4522-229f-4ca2-b1df-dd90c6100e3b.png?etag=61680be303c1143ea0f0d54ff2881aef)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d0b169cb-1bf9-4671-967d-3caa43f39a19-annotated_deff4522-229f-4ca2-b1df-dd90c6100e3b.png?etag=61680be303c1143ea0f0d54ff2881aef)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2560x1240
**Labels**: enhancement
**[Open #105 in Usersnap](https://app.usersnap.com/l/feedback/8783cdf5-7a1b-424d-92d0-8a172bff3227?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/election
wss://44.201.112.198.nip.io/ws-rpc

<img width="1183" alt="Снимок экрана 2022-11-10 в 14 10 50" src="https://user-images.githubusercontent.com/46903215/201088479-befc0612-a51c-4b5e-b658-627ce929336c.png">
