### ISSUE TITLE
Submit work Modal small copy upd

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2509]
**Scope:**
- [ ] Add small line of copy "Remember to add link to your work."
- [ ] change "Entry description" to "Description of Completed Work"

**Design:**
Link to [Figma for styles is here>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=7117%3A172961)

**Preview:**

![Screenshot 2022-03-09 at 21.36.07.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/14dbff10-84f4-4f20-a708-66ee5bd98268)

**Comment by MattAugustynowicz** [comment]
@dmtrjsg Looks goood! 🌟
We had such patterning for example [here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=7117%3A172961) :))

**Comment by talentdev0807** [comment]
@talentdev0807

**Comment by polikosi** [comment]
Verified on staging. Test evidence below:
![Screenshot_27](https://user-images.githubusercontent.com/80429191/169646769-1b325aae-88e7-433c-8cad-70386a083a20.png)
![Screenshot_26](https://user-images.githubusercontent.com/80429191/169646776-1e94b170-7b47-458d-a0f0-828279cc3dd8.png)
