### ISSUE TITLE
[USERSNAP] WG opening: Apply with stake as own account generates fail tx

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2512]
**Taken at**: https://pioneer-2.vercel.app/#/working-groups/openings/membershipWorkingGroup-3
**Fields**:
- Houston, we have a problem.: WG opening: Apply with stake as own account generates fail tx
- Give us some details: SSIA
- SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6252539c-1fb1-4641-b96c-5d431ce05290-annotated_a8132b11-cbba-444b-8764-e3f7ce3f2009.png?etag=78f4accdc599a9510c2195ea1b8bc2a2)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6252539c-1fb1-4641-b96c-5d431ce05290-annotated_a8132b11-cbba-444b-8764-e3f7ce3f2009.png?etag=78f4accdc599a9510c2195ea1b8bc2a2)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1850x1176
**Labels**: bug-critical
**[Open #107 in Usersnap](https://app.usersnap.com/l/feedback/8f34f463-b043-433a-9d5e-d62adf1507cb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
* apply (attempt 1)
		* invalid transaction: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x30ffc4609e6615b9bb9c83bc35c1db47200e4c02341100f581a4c81174a043f6
		* Staking account for membership doesn't exist.
		* Stake was removed after initial application was attempted, will retry.
	* apply (attempt 2)
		* invalid transaction: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xb79a3e3a8ef5225b895cd14d31335c66d72746cbc9f7a25c829d6f5e8e24ecf0
		* Same issue as above
	* apply (attempt 3)
		* user: tom61
		* 0 locks
		* balance `free: 249.9000 kJOY`
		* 0 staking relationships
		* invalid transaction: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x84914da4c56d3b21338abdbfabbbedd1155720c9cf26a555266ae04c50191129
		* same issue as above.

**Comment by mochet** [comment]
* apply (attempt 4)
		* user: tom61
			* `free: 249.9000 kJOY`
		* stake: test_5
			* never used before, initial balance set to 50k
			* https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F3.87.51.41.nip.io%2Fws-rpc#/explorer/query/0x0c2480dd709e1a08e295bd9ea694c1014effac71faa75c9a3cec2dbf29540ba7
			* `free: 50.0000 kJOY`
		* invalid transaction: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xd36fb297be57187b86b2fcf5187774b43a1a96c433f55ad3acce67426e363a7f

This issue is the same as https://github.com/Joystream/pioneer/issues/2417

Problem: When applying for the Membership + Forum WG Lead roles, Pioneer is not making a stake relationship. It is just attempting to apply without any staking relationship.

**Comment by mochet** [comment]
Same applies for all WGs

* Distribution
	* Apply: 140
	* stake: 140
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xc74ffdb04583e0fd411775eadac296ce97faa165f2c3df7b4c608bcd9bbdec28
* Content
	* Apply: 141
	* Stake: 141
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xda1001c106c3890273580714dbf16b6e9ee8464e9a3f9a817db9b2a7e5096e14
* Forum
	* Apply: 142
	* Stake: 142
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x82611f6534ee45465f782567dc903247ff8018185fb618c824ed885ccbf0db65
* Gateway
	* Apply: 143
	* Stake: 143
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xe6600d1ffeeb5352302a40758f2652be06f795e7857a08965996528d2e954c1b
* Storage
	* Apply: 144
	* Stake: 144
	* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0xaa9b91458ac582bb63217890707b89d93a4383143037a7395bf2eab0731a47db
	* Trying with different stake
		* Apply: 144
		* Stake: 145
		* Pioneer failed: https://polkadot.js.org/apps/?rpc=wss://3.87.51.41.nip.io/ws-rpc#/explorer/query/0x0645e41b87fdf4d0776b74fb20915dd917c2587eaf2f7b8ceb89eb066781587e
* Operations Alpha
	* Doesn't load in Pioneer
* Operations Beta
	* Doesn't load in Pioneer
* Operations Gamma
	* Doesn't load in Pioneer

**Comment by mochet** [comment]
closing as the other issue is where this problem was originally described https://github.com/Joystream/pioneer/issues/2417
