### ISSUE TITLE
[USERSNAP] Proposals: WG Lead Reward doesn't show current lead reward

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2515]
- [ ] Display current reward amoun

⚠️  to be done together with #2514 

**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: Proposals: WG Lead Reward doesn&#39;t show current lead reward
- Give us some details: SSIA
- SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b252abb0-e8e3-411d-8210-39d0f9e288ec-annotated_2eee2fe4-29d3-40d9-a2b0-d2046250785c.png?etag=421fd4c12be2b57287f4f4f25e2bfd3c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b252abb0-e8e3-411d-8210-39d0f9e288ec-annotated_2eee2fe4-29d3-40d9-a2b0-d2046250785c.png?etag=421fd4c12be2b57287f4f4f25e2bfd3c)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1850x1176
**Labels**: enhancement
**[Open #110 in Usersnap](https://app.usersnap.com/l/feedback/bac2c673-3c16-4aca-b234-93dc1c78ed71?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by MattAugustynowicz** [comment]
We can show this in the same way we arrange content during creating bounty - showing a disabled input with the current reward amount and an active fillable placeholder with a new reward next to it.

[👉 Figma Link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8850%3A309464)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/9f3310ff-a525-4d80-adc6-c925dad2fbd0)

**Comment by dmtrjsg** [comment]
@MattAugustynowicz agreed on the blue box

**Comment by MattAugustynowicz** [comment]
[👉 Same link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8850%3A309464)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/76015fb1-e192-434e-8605-45b1f5548026)

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
![lead_rewards](https://user-images.githubusercontent.com/80429191/168583247-4a632881-b9dd-4758-8f06-22b20414fcb2.png)
