### ISSUE TITLE
[USERSNAP] Pioneer skips `member.addStakingAccountCandidate` when applying for an opening

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2518]
**To-do**

- [ ] Add validation for sufficient funds on staking account for APPLY TO OPENING
"Choose an account with sufficient balance to proceed".
- [ ] If add staking account fails (any reason), Pioneer on second attempt to do this transaction, should do add_stake_candidate again as step 1 of the transaction.
______________
**Taken at**: https://pioneer-2.vercel.app/#/working-groups/content
**Fields**:
- Houston, we have a problem.: Pioneer skips `member.addStakingAccountCandidate` when applying for an opening
- Give us some details: With a &#34;fresh&#34; membership, I tried setting a `stakingAccount` without any tokens on it -&gt; `addStakingAccountCandidate` failed.

I transferred tokens to it, and re-tried. Pioneer now assumes this relationship exists, and &#34;skips&#34; ahead to `confirmStakingAccount` which then, of course, also fails.
- -
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c32ac886-0e73-4286-96af-38dd785d28d8-annotated_0126981b-cfcc-4011-8cf8-7631e0250417.png?etag=d9a6d7c81fed0942991437e9bc6dbb6c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c32ac886-0e73-4286-96af-38dd785d28d8-annotated_0126981b-cfcc-4011-8cf8-7631e0250417.png?etag=d9a6d7c81fed0942991437e9bc6dbb6c)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 1920x1000
**Labels**: bug-critical
**[Open #112 in Usersnap](https://app.usersnap.com/l/feedback/d61f65d6-b159-41cf-a85e-772db4b4c3b7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
`member.addStakingAccountCandidate` fails:
![Screen Shot 2022-03-10 at 11 17 28](https://user-images.githubusercontent.com/35237943/157641074-59f0edcf-a21a-4b9d-a3ef-6fda4ef0b5ca.png)

`member.confirmStakingAccount` fails.
![Screen Shot 2022-03-10 at 11 18 20](https://user-images.githubusercontent.com/35237943/157641264-db061d0b-eade-4303-afbb-32e8e5d9d1ef.png)

**Comment by dmtrjsg** [comment]
@bwhm  we cannot reproduce this one using Pioneer, as the accounts with insufficient funds are filtered out from selection. Assigning to you to try again pls?

**Comment by dmtrjsg** [comment]
@bwhm closed this issue as validations are now all in place.. :) 

@thesan @WRadoslaw  also FYI
