### ISSUE TITLE
[USERSNAP] Runtime upgrade propsal sends an empty blob?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2519]
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/165
**Fields**:
- Houston, we have a problem.: Runtime upgrade propsal sends an empty blob?
- Give us some details: After making a runtime proposal (wasm size ~2.9MB), I noticed the transaction looked small in polkadot-js. Checked the proposal details, and downloaded a 1b empty file....
- _
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2c3b254d-f7ff-4205-9f52-f7031947bafe-annotated_882e4e21-6974-415d-a1d8-784d8e51545a.png?etag=a6d2b3f7ffd23e2a06bb6325b64373eb)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2c3b254d-f7ff-4205-9f52-f7031947bafe-annotated_882e4e21-6974-415d-a1d8-784d8e51545a.png?etag=a6d2b3f7ffd23e2a06bb6325b64373eb)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 1920x1000
**Labels**: bug-non-critical
**[Open #113 in Usersnap](https://app.usersnap.com/l/feedback/b8293fa9-0d10-4a7c-89ad-dbdc64fa81a4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
Confirmed. I know created the proposal in polkadot-js. When looking at the proposal in pioneer, and downloading the file, it's all good.

So only creation isn't working.

**Comment by bwhm** [comment]
Not high priority. In practice, we make all of these proposals.

**Comment by freakstatic** [comment]
Resolved on:  https://github.com/Joystream/pioneer/pull/4674
