### ISSUE TITLE
Show bound account <> membership info

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2521]
![Screenshot 2022-03-10 at 19.44.44.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/eba9bcb5-b36d-4b09-90e4-c2d46cfc701b)

<img width="1195" alt="Screenshot 2022-03-10 at 19 45 47" src="https://user-images.githubusercontent.com/93924525/157742680-55de185e-eee3-4526-9721-d7b8ee338b8e.png">

<img width="1197" alt="Screenshot 2022-03-10 at 19 45 50" src="https://user-images.githubusercontent.com/93924525/157742686-82a67025-9e1c-42b6-9428-8199c6b1ae95.png">

**Comment by MattAugustynowicz** [comment]
[Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8659%3A265223)

I would suggest adding to account locks only "bound to" information with the membership and a possible infotip describing why the lock appeared and a link to our gitbook.

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/c0bf5391-2da3-4509-8f6a-d779289080bd)

On the membership details I would show in a similar way to how we show other accounts add the category "bound account" 

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/be447d87-70e2-40d0-bbd7-718df513afb6)

**Comment by RafalPloszka** [comment]
Waiting for https://github.com/Joystream/joystream/issues/3729 to finish this issue

**Comment by polikosi** [comment]
Verified on staging. Test evodence below:

![Screenshot_100](https://user-images.githubusercontent.com/80429191/172361737-6690db58-7021-4594-acae-0d2fe821787b.png)
![Screenshot_101](https://user-images.githubusercontent.com/80429191/172361720-94682db1-20fe-4e80-a4a6-052235166a6f.png)
