### ISSUE TITLE
Bounty details page: Period Length is Static

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2523]
## Scope
- [ ] Show countdown timer in blocks like council period instead of unlimited.

## Problem

current widget does not show countdown in real time

![Screenshot 2022-03-10 at 20.10.43.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/055bc7da-51f1-4b3d-ba77-bd09c1babdab)

## Tech Approach

1️⃣  use the same component as in Elections

<img width="389" alt="Screenshot 2022-04-21 at 12 23 00" src="https://user-images.githubusercontent.com/93924525/164447927-4d570f9c-bae4-481c-a425-7ad401848bc9.png">
<img width="1034" alt="Screenshot 2022-04-21 at 12 23 24" src="https://user-images.githubusercontent.com/93924525/164447933-02a3d13b-8680-4c62-add9-5c3d54904fa1.png">

**Comment by ivanturlakov** [comment]
Tested on staging.

The countdown timer in blocks was added.

https://user-images.githubusercontent.com/46903215/169807125-0343dcc0-ca92-49f0-9689-bbda1ca3b7b6.mov
