### ISSUE TITLE
Pioneer doesn't let me use my `Bound Staking Account` deposit for election staking.

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2536]
I should be allowed to use this for `council.announceCandidacy`. The runtime does, as "shown" below.

![Screen Shot 2022-03-12 at 16 18 28](https://user-images.githubusercontent.com/35237943/158023849-b1446e6d-a00d-4f52-8e43-95cce19c6b75.png)

Without trying, I assume the same is the case for voting.

**Comment by dmtrjsg** [comment]
@bwhm  thanks for raising. What do you mean by "pioneer doesn't let" - 
Account is not available in the list of drop downs/ not identified when you paste the address to the field?

**Comment by traumschule** [comment]
This election i was able to use total validation stake + transferable balance as staking account for voting.
