### ISSUE TITLE
My Applications shows incorrect info

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2537]
<img width="1668" alt="Screen Shot 2022-03-13 at 00 04 09" src="https://user-images.githubusercontent.com/35237943/158038056-ab5ca827-f0a7-4baf-9716-5ec16a0bce2e.png">

- For the active opening, the result should be "Pending" or something.
- For the past opening, the member was actually hired.
- The stake was 5000JOY for all

I later tested with an applicant that wasn't hired, and it also shows "No"

**Comment by singulart** [comment]
Failed verification. 

The `withdrawn` application is shown as `Pending`, which is not correct. 

<img width="1190" alt="Screenshot 2022-04-29 at 00 22 36" src="https://user-images.githubusercontent.com/7863785/165848316-2fba5342-39f7-4ebc-b86d-a4720f6da2f9.png">
<img width="503" alt="Screenshot 2022-04-29 at 00 23 43" src="https://user-images.githubusercontent.com/7863785/165848328-55451210-fa8e-4e49-87b6-511424679972.png">

**Comment by dmtrjsg** [comment]
Show "Withdrawn"
