### ISSUE TITLE
working-groups/* issues

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2539]
## Scope

Sub-Issues to fix

1️⃣ 
**Context:** Pioneer FE creates the WGL opening correctly when done via GUI proposal flow; while on CLI creation of openings is possible via CLI, where the rule of setting the default hiring limit is not implemented. 
**To-do:**
- If the limit is not specified (on creating opening via CLI), display default limit as 1 on the opening card and details views. SP -1.

2️⃣ 
**Context:** described in the report below
**To-do:**
- [ ] Currently Staking amount to be fixed. 
🛠️ Tech tips:  Use the `sumStakes` function for this widget.
 SP - 1
 
⛔  **Out of scope**
 
- #2913 

________

Although the whole opening/application/hiring process has been improved significantly, there are still a few issues:

![Screen Shot 2022-03-13 at 12 37 07](https://user-images.githubusercontent.com/35237943/158057567-b0d74670-426e-409c-8770-39c450300578.png)
- When not setting a target, it defaults to 2. This **may** be ok for the "Worker" openings (although I don't think it's the best), for Lead openings, it makes no sense.
- "Currently Staking" (I'm currently staking for 5 roles - 5k for each) seems to be a set of the stake amounts, without a separator:
   - `[5000,5000,5000,5000,5000]`
   - displayed:
      - without  "," as the thousand separator
      - a space as stake separator
      - () for omitted due to not enough space
  - `(5000 500)0 5000 5000 5000`

![Screen Shot 2022-03-13 at 12 41 27](https://user-images.githubusercontent.com/35237943/158057710-648d06a9-fd00-45b4-8dc9-4d439ba2c908.png)

- Also shows the `staked` amount as 100JOY and not hired, despite all of all but Storage Worker with ID 1 being hired.

ref #2537

**Comment by polikosi** [comment]
✅If the limit is not specified (on creating opening via CLI), display default limit as 1 on the opening card and details views.
![image](https://user-images.githubusercontent.com/80429191/205722624-2e5a00c4-be95-4269-b926-d408161cadaf.png)
![image](https://user-images.githubusercontent.com/80429191/205722926-08ec8f37-99bf-4ad2-84c7-a0fdd48e9dfb.png)

⚠️I'm currently staking  5k tjoy for 1 roles it is not displaying
![image](https://user-images.githubusercontent.com/80429191/205724847-4ba5a3cf-45dc-49a5-9aa2-2b84bacbec0c.png)

shown my stake 5k and status hired (I was hired for this role)
![image](https://user-images.githubusercontent.com/80429191/205726119-b40e5edf-88af-4fa3-8bdc-63860c30657e.png)
