### ISSUE TITLE
`/#/council/past-councils`: Clicking on a previous council returns blank page

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2541]
![Screen Shot 2022-03-13 at 16 04 12](https://user-images.githubusercontent.com/35237943/158065966-f110b5bc-9bc1-4994-a935-08a3415db3c5.png)

The first (bottom) is not a real Council as it's before a Council was actually set. 
That works fine:
![Screen Shot 2022-03-13 at 16 02 38](https://user-images.githubusercontent.com/35237943/158065947-25f35d26-363e-4b7f-a12c-6a400bc123c2.png)

However, when selecting the actual elected Council, I get a blank page.

⚠️  Snap not installed on this deployment. Link: 
- https://pioneer-2-content-staging.vercel.app/#/council/past-councils
- https://pioneer-2-content-staging.vercel.app/#/council/past-councils/6NFKKcUvc

<img width="749" alt="Screenshot 2022-03-14 at 14 44 45" src="https://user-images.githubusercontent.com/93924525/158196272-8eb59ab2-93e0-4471-80d6-6c03a086d61e.png">

**Comment by singulart** [comment]
Works on Prod <img width="813" alt="Screenshot 2022-04-14 at 12 00 37" src="https://user-images.githubusercontent.com/7863785/163351465-6ba9fac3-5cdb-4e7a-878a-dc18e329a35b.png">
