### ISSUE TITLE
Recovering election candidacy stake shows Voting Stake in the sign transaction And Transfer modal.

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2543]
when `staking_account` != `membershipController`
_________

🆕 ..Let's re-purpose this issue 

## To-do

1. Updating the copy of signing modal headline text to 

"You intend to recover 11,000 JOY stake:"

2. Show _Candidacy stake_ instead of _Voting stake_  for it to be precise. Here we also need to show the correct icon

## Context

<img width="565" alt="Screenshot 2022-03-15 at 12 26 11" src="https://user-images.githubusercontent.com/93924525/158377397-d08acabe-38df-4916-8221-056e9ab83a46.png">

**Comment by dmtrjsg** [comment]
...https://github.com/Joystream/pioneer/issues/2535

**Comment by bwhm** [comment]
I can confirm it worked for me now! I guess it was a mistake on my part. Either, I tried unlocking too soon, or something else... Sorry about that.

I hate to be that guy (that injects something else when wrong), but the copy was somewhat off:
![Screen Shot 2022-03-15 at 13 07 59](https://user-images.githubusercontent.com/35237943/158375118-cc10c6eb-9285-4d17-8684-1b6224b2c002.png)
![Screen Shot 2022-03-15 at 13 08 07](https://user-images.githubusercontent.com/35237943/158375142-e7324ecb-d4b3-484c-881f-a81d41603df9.png)

**Comment by dmtrjsg** [comment]
Let's re-purpose this issue 

1. Updating the copy of signing modal headline text to 

"You intend to recover 11,000 JOY stake:"

2. Show _Candidacy stake_ instead of _Voting stake_  for it to be precise. Here we also need to show the correct icon

**Comment by dmtrjsg** [comment]
Retested
