### ISSUE TITLE
Adding any image as bounty image looks "bad" on bounty details page

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2544]
- [ ] Limit max width and keep the resolution

![Screen Shot 2022-03-13 at 18 38 50](https://user-images.githubusercontent.com/35237943/158072051-0175b74b-3b66-4dd6-8235-8f018ca728b7.png)

**Comment by thesan** [comment]
@RafalPloszka please add a `max-width: 100%;` too. The page layout is broken for me on: https://dao-git-dev-joystream.vercel.app/#/bounty/preview/1?network-config=https://3.95.67.177.nip.io/network/config.json (especially if you reduce the width of the window)

![Screenshot from 2022-04-01 14-35-41](https://user-images.githubusercontent.com/6571453/161264520-4f0c58a1-7b7f-4ff1-9bf1-99af3761e09b.png)

**Comment by singulart** [comment]
Tested on staging 
<img width="794" alt="Screenshot 2022-04-14 at 16 30 12" src="https://user-images.githubusercontent.com/7863785/163403132-95260ba0-a439-4f92-8f9d-8e9777631532.png">

**Comment by singulart** [comment]
<img width="647" alt="Screenshot 2022-04-14 at 16 43 00" src="https://user-images.githubusercontent.com/7863785/163403449-59e76e16-6226-4349-94d1-11df55b7c6a1.png">
