### ISSUE TITLE
[USERSNAP] Bounty: Link/Image/Title don't link to bounty

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2555]
**Taken at**: https://pioneer-2.vercel.app/#/bounty/current
**Fields**:
- Houston, we have a problem.: Bounty: Link/Image/Title don&#39;t link to bounty
- Give us some details: You should be able to click these to go to the bounty details
(I&#39;m going to be making a lot of bounty issues I am guessing as I&#39;m just getting into this system, I&#39;ll review them all after posting them)
- You should be able to click these to go to the bounty details
(I&#39;m going to be making a lot of bounty issues I am guessing as I&#39;m just getting into this system, I&#39;ll review them all after posting them)
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7863ae60-29bd-42fa-8703-46edc93243ba-annotated_5d15380f-4c58-452d-9967-8eb6f187904d.png?etag=c1db660d14155df5c8455260eddf6261)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7863ae60-29bd-42fa-8703-46edc93243ba-annotated_5d15380f-4c58-452d-9967-8eb6f187904d.png?etag=c1db660d14155df5c8455260eddf6261)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1579x1174
**Labels**: enhancement
**[Open #115 in Usersnap](https://app.usersnap.com/l/feedback/30206337-da41-45f7-8a5c-3111d8a3f2fb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Thanks for starting to test the Bounties module, suggest to review these existing issues to avoid duplicates en-masse:

#2390 
#2529 
#2520
#2523 
#2545 
#2546 
#2488 
#2510

**Comment by dmtrjsg** [comment]
Covered here > https://github.com/Joystream/pioneer/issues/2220

**Comment by mochet** [comment]
> Thanks for starting to test the Bounties module! @mochet, suggest to review these existing issues to avoid duplicates en-masse:
> 
> #2390 #2529 #2520 #2523 #2545 #2546 #2488 #2510

Will do! Thanks for making me aware
If there's anything that can be done to improve reported issues or if there is any better way to understand already reported issues more than happy to do so
