### ISSUE TITLE
Add new membership created confirmation modal to self-service flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2558]
### Scope

- [ ] New membership confirmation modal to the New membership creation". 
- [ ] Headline copy "New membership created! Your account is credited with JOYs to help you get started, and cover transaction fees for voting, forum and open discussions participation."
- [ ] CTA on modal takes user to https://dmitry-pioneer.vercel.app/#/profile/memberships (page refreshed in the back and updated list is shown.

Preview of modal sample

![Screenshot 2022-03-18 at 15.19.48.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/ced9c188-a196-4618-9cc8-a12cf1bc593a)
____
See current walk through recording  [[Loom Videoi]>(https://www.loom.com/share/8004e137b6cc4ca19ebe96177d716d2e)

**Comment by dmtrjsg** [comment]
TO-DO:

Not cache my members <-

**Comment by polikosi** [comment]
Actual result:

https://user-images.githubusercontent.com/80429191/165548302-328bbd15-9549-4f82-ad67-5cb12da50643.mp4

![ticket#2558(1)](https://user-images.githubusercontent.com/80429191/165548323-4c589a95-d0fd-4803-9fd7-356aaf6dd1a7.jpg)
![ticket#2558](https://user-images.githubusercontent.com/80429191/165548333-32b6f8ec-3f9e-4d9e-a527-4a26aa919f61.jpg)
:
