### ISSUE TITLE
[USERSNAP] Bounty oracle selection: Unable to select self as oracle

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2559]
- [ ] Allow creator of bounty to select oneself as Oracle

⚠️  to be done with 
https://github.com/Joystream/pioneer/issues/2577

**Taken at**: https://pioneer-2.vercel.app/#/bounty/current
**Fields**:

* Houston, we have a problem.: Bounty oracle selection: Unable to select self as oracle
* Give us some details: SSIA
This feature works in runtime and is somewhat of a significant use case--a person creating a bounty and also judging it to get a task they want done completed.
* SSIA
This feature works in runtime and is somewhat of a significant use case--a person creating a bounty and also judging it to get a task they want done completed.
* Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b4d0bc50-3147-45b8-841a-dff9eadb44ff-annotated_6e654ad7-0281-4767-a40b-89a28c0f527b.png?etag=8c3bbe0597bb65d353b90454ac036ea5)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b4d0bc50-3147-45b8-841a-dff9eadb44ff-annotated_6e654ad7-0281-4767-a40b-89a28c0f527b.png?etag=8c3bbe0597bb65d353b90454ac036ea5)_

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1891x1174
**Labels**: bug-non-critical
**[Open #117 in Usersnap](https://app.usersnap.com/l/feedback/9d91242c-c284-438c-861c-57e87bee65f0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201976815343411) by [Unito](https://www.unito.io)

**Comment by mochet** [comment]
Example where this type of bounty was created: https://pioneer-2.vercel.app/#/bounty/preview/4
