### ISSUE TITLE
Separate Text sizes to different styled components

### ISSUE THREAD

**Issue by ClumsyVlad** [Joystream/pioneer#256]

**Comment by jodator** [comment]
@ClumsyVlad – FYI: I've made a refactor to have single `<Button>` component which can be controlled by setting props.

Th e first case for this was here: [https://github.com/Joystream/pioneer/pull/261/files#diff-3ffe98b2a07eedea01c6ba588d28538ac9bc99c9e0e29d4079b4ea681ad603a9.](https://github.com/Joystream/pioneer/pull/261/files#diff-3ffe98b2a07eedea01c6ba588d28538ac9bc99c9e0e29d4079b4ea681ad603a9.)

I don't recall if we need the same for Text (there might be a different problem though).
