### ISSUE TITLE
[USERSNAP] Bounties: Contribute funds field crashes page if - (minus) character is used

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2561]
- [ ] update the component that is used for input of this value to match the one that is used for funds transfer

`InputNumber`

-------------

**Taken at**: https://pioneer-2.vercel.app/#/bounty/preview/4
**Fields**:
- Houston, we have a problem.: Bounties: Contribute funds field crashes page if - (minus) character is used it crashes if you insert a - character in front of the number.
- Give us some details: SSIA - it goes to a white page
- SSIA - it goes to a white page
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a319e032-bb0d-4b46-8aff-fc72b5253124-annotated_6b616e49-9d57-4152-9838-78c0d5c48d9d.png?etag=348a7244b517d03177df061fc2fcef00)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a319e032-bb0d-4b46-8aff-fc72b5253124-annotated_6b616e49-9d57-4152-9838-78c0d5c48d9d.png?etag=348a7244b517d03177df061fc2fcef00)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1891x1174
**Labels**: bug-non-critical
**[Open #119 in Usersnap](https://app.usersnap.com/l/feedback/10912e97-d880-4e33-9fab-a0c5697851b4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
Verified on staging.
Validation of the input field works well.
Attempting to enter/paste any characters other than numbers causes the cursor to move to the end of the line.

https://user-images.githubusercontent.com/46903215/168258093-eb1002aa-c720-4b16-8df7-a78316961fd5.mov
