### ISSUE TITLE
Bounties: Contribute (first) to "Perputual" lacks info

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2562]
Would be nice to know what has been contributed already, and what the target is.

![Screen Shot 2022-03-14 at 23 04 41](https://user-images.githubusercontent.com/35237943/158269298-5e2189e8-02f8-4324-8bde-baa238fbf4fb.png)

To test: if the same is true after a contribution has been received.

**Comment by dmtrjsg** [comment]
Agreed! and already captured>

-  https://github.com/Joystream/pioneer/issues/2408
