### ISSUE TITLE
Bounties: Can't withdraw entrant stake

### ISSUE THREAD

**Issue by bwhm** [Joystream/pioneer#2566]
## Scope

- [ ] Implement withdraw stake instead of withdraw funding for the case where Worker withdraws after Bounty failed and is in Withdrawal period

__________________

## Problem
Pioneer tries to withdraw funding.

![Screen Shot 2022-03-14 at 23 18 57](https://user-images.githubusercontent.com/35237943/158270609-d5d8d2fd-2dba-4574-b169-fb03af573f42.png)
![Screen Shot 2022-03-14 at 23 19 56](https://user-images.githubusercontent.com/35237943/158270614-4c202f5a-af52-4350-81d8-7d1cfb56ecf4.png)
![Screen Shot 2022-03-14 at 23 20 02](https://user-images.githubusercontent.com/35237943/158270617-de99aa71-219b-4ea5-bed4-c0b0b7ce6f9a.png)

**Comment by dmtrjsg** [comment]
will be covered in a separate issue>

- [ ] Refetch QN after stake withdrawn

Fixed, but QN does not refresh after it, leaving Withdraw CTA, so second attempt results in an error/


<img width="539" alt="Screenshot 2022-03-22 at 20 14 59" src="https://user-images.githubusercontent.com/93924525/159568459-b63adb52-c3af-4a02-bd16-ef48393eb06a.png">
