### ISSUE TITLE
Design Icons For Operations Working Groups

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2582]
We need separate icons for Operations WGs

Alpha - Builders
Beta - HR
Gamma - Marketing

https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=199%3A1252

**Comment by MattAugustynowicz** [comment]
[👉 Figma link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=199%3A1252)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/cb079f01-11d9-49b1-af44-6e2d68024098)
