### ISSUE TITLE
Splitting Cherry Fully among all contributors

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2583]
## Context
There was an edge case with splitting cherry equally, which supposedly was done here: 
https://github.com/Joystream/pioneer/issues/1938#issuecomment-1022078720

Reportedly this case is handled differently, so we need to look into it again
https://github.com/Joystream/pioneer/issues/2568#issuecomment-1069165149

## Scope

:question: Does system.KilledAccount & balances.DustLost, result in 1 Joy burned and there are no other implications.

I will confirm with Martin and close this issue if no further change is required.

**Comment by bwhm** [comment]
Yes.

Any account with less than 10JOY will get "purged" - as that is the "existential deposit". Example:
1. create new account
2. send 10 to said account
   - This triggers TWO events:
     1. `balances.Transfer`; and
     2.  `balances.Endowed` -> `An account was created with some free balance. [account, free_balance]`
3. transfer 1 away from it
   - This triggers THREE events:
     1. `balances.Transfer`,
     2. `system.KilledAccount` -> `An [account] was reaped. `
     3. `balances.DustLost` -> `An account was removed whose balance was non-zero but below ExistentialDeposit, resulting in an outright loss. [account, balance] `

**Comment by bwhm** [comment]
![Screen Shot 2022-03-16 at 15 46 53](https://user-images.githubusercontent.com/35237943/158618560-c1f93c38-4b0f-4d9a-be99-3b04a3a679d5.png)
![Screen Shot 2022-03-16 at 15 47 04](https://user-images.githubusercontent.com/35237943/158618572-dac696f3-a3ee-40cd-a98b-8de03043701d.png)
![Screen Shot 2022-03-16 at 15 47 28](https://user-images.githubusercontent.com/35237943/158618584-0629c455-f77b-473d-829a-7288bf177145.png)

**Comment by dmtrjsg** [comment]
Thinking worth to retest the originating use case once this setting is off.
