### ISSUE TITLE
Refetch QN after reveal vote

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2593]
## Context

Add button "Back to candidates" to reveal confirmation and when clicked, refetch qn to show updated progress on revealed candidate vote

https://www.loom.com/share/def23cc4a93e4bfd9c0f072c47a747ea

**Comment by dmtrjsg** [comment]
😞  QN did not refetch for me this time>
https://www.loom.com/share/7ddcbb356ae24b6ca0261090ebe1a71a

**Comment by ivanturlakov** [comment]
Tested on staging.

QN did not refetch.

1 

https://user-images.githubusercontent.com/46903215/169658376-26406055-4dec-435f-81ca-977456632e18.mov



2

https://user-images.githubusercontent.com/46903215/169658330-3201bf4c-a837-4494-b1ad-b4561373abea.mov

3

https://user-images.githubusercontent.com/46903215/169658336-51d97027-b598-4da3-8fa6-fa1896407c37.mov
