### ISSUE TITLE
Update validation copy on "Create WGL opening" Proposal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2601]
Update the validation copy of the top field  to ... equal or greater than {{execution constraint value}}

![Screenshot 2022-03-21 at 10.06.17.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/ec1bcb26-fe0a-4dfe-91fa-c1c591aca792)

**Comment by adovrodion** [comment]
Bounty link: https://dao.joystream.org/#/bounty/preview/64

**Comment by polikosi** [comment]
testedm on: https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json
![image](https://user-images.githubusercontent.com/80429191/205290531-ca8f3677-e440-4c6c-9d8e-9f80670027cf.png)
