### ISSUE TITLE
Error on announce work entry

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/pioneer#2607]
## Problem
___

When trying to announce entry on bounty and picking staking account that isn't connected to the member, after connecting account with member, announce transaction results in error. Even tho I was able to create proposal with same account/member pair [transaction](https://polkadot.js.org/apps/?rpc=wss://3.95.67.177.nip.io/ws-rpc#/explorer/query/0x74fd88ae65f690db3d60d2ce2e7bbb07fc0c55d35e9e64ba6d82b73a1ef343de)

![image.png](https://images.zenhubusercontent.com/61b33b1e8ddbc86c62bdcd28/b015d414-1d07-4652-b2dd-106e1c330c3a)

___
[Staking tx](https://polkadot.js.org/apps/?rpc=wss://3.95.67.177.nip.io/ws-rpc#/explorer/query/0x28f05a325fecec192213198719173f1568bce93e434938452701f66ae367c744)

[Announce tx](https://polkadot.js.org/apps/?rpc=wss://3.95.67.177.nip.io/ws-rpc#/explorer/query/0x32f80f320dc7046ea92d1c93146a5f576c46bf0eb8402ca57c3e5a226a6b1587)

**Comment by dmtrjsg** [comment]
Same problem reported when re-testing https://github.com/Joystream/pioneer/issues/2546

**Comment by dmtrjsg** [comment]
resolved in 2546
