### ISSUE TITLE
Bounties images reset with page refresh

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2617]
![Screenshot 2022-03-22 at 18.18.00.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/3d88ca1a-f19c-47a5-99c2-54767531d393)

**Comment by dmtrjsg** [comment]
Read to be merged to Prod!

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:

https://user-images.githubusercontent.com/80429191/165588059-64d8fc41-995d-4445-a5a8-6f778c23a0ab.mp4
