### ISSUE TITLE
Refetch qn after voted

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2618]
Context:

We need to extend the same approach as we did for #2593, to casting the vote. 

Actual result: Clicking on CTA in voting confirmation modal does not do anything
Expected result:
- [ ] Modal closes, 
- [ ] QN refetches and 
- [ ] My votes tab is shown with counter 
- My votes can always be visible, 
- No counter required for zero, 
- Show empty page placeholder copy for opened my votes tab. ⚠️ Use custom copy  "Your votes will be shown in this list. Single member can vote multiple times with different accounts." 

+
- [ ] I suggest to update CTA to "Back to Candidates" and keep the user on the same page (pun intended :P)

**References**

**Modal in question:**
![Screenshot 2022-03-22 at 18.32.53.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/b709798a-5672-49b9-b1c8-6c10179aab3e)

**My openings empty state**
<img width="671" alt="Screenshot 2022-03-22 at 18 38 16" src="https://user-images.githubusercontent.com/93924525/159553071-b2cceb89-5e5b-4e77-abcf-7f8e480fecc5.png">

**Comment by ivanturlakov** [comment]
Tested on staging.

https://user-images.githubusercontent.com/46903215/169553350-24711f1c-4f92-4472-a427-ca75630c85b4.mov

The candidate card is not updated. The "Voted" label and "Vote again" text on the button appears only after reloading the page.

My votes counter has been updated, but if you open the tab it is empty
<img width="1440" alt="Снимок экрана 2022-05-20 в 17 40 42" src="https://user-images.githubusercontent.com/46903215/169553467-280874f0-0ab0-4f73-a1ea-84ecc8c2b570.png">


After refreshing the page my votes are visible
<img width="1440" alt="Снимок экрана 2022-05-20 в 17 52 06" src="https://user-images.githubusercontent.com/46903215/169555419-d3f959ca-693f-4637-8648-7e0a13fa57f5.png">
