### ISSUE TITLE
[USERSNAP] GraphQL error: missing column loading candidacynotemetadata

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2644]
**Taken at**: https://dao.joystream.org/#/overview
**Fields**:
- Houston, we have a problem.: GraphQL error: missing column loading candidacynotemetadata
- Give us some details: route: overview
 
```
56dbd8f….js:2 GraphQL error 
Array(1)
0:
extensions:
code: &#34;INTERNAL_SERVER_ERROR&#34;
exception:
code: &#34;42703&#34;
file: &#34;parse_relation.c&#34;
length: 119
line: &#34;3349&#34;
message: &#34;column 31j5uSKVPm.undefined does not exist&#34;
name: &#34;QueryFailedError&#34;
parameters: [{…}]
position: &#34;457&#34;
query: &#34;SELECT \&#34;candidacynotemetadata\&#34;.\&#34;id\&#34; AS \&#34;candidacynotemetadata_id\&#34;, \&#34;candidacynotemetadata\&#34;.\&#34;header\&#34; AS \&#34;candidacynotemetadata_header\&#34; FROM \&#34;candidacy_note_metadata\&#34; \&#34;candidacynotemetadata\&#34; LEFT JOIN \&#34;candidacy_note_set_event\&#34; \&#34;31j5uSKVPm\&#34; ON \&#34;candidacynotemetadata\&#34;.\&#34;id\&#34; = \&#34;31j5uSKVPm\&#34;.\&#34;note_metadata_id\&#34; WHERE \&#34;candidacynotemetadata\&#34;.\&#34;deleted_at\&#34; IS NULL GROUP BY \&#34;candidacynotemetadata\&#34;.id HAVING COUNT(\&#34;31j5uSKVPm\&#34;.\&#34;note_metadata_id\&#34;) = COUNT(CASE WHEN \&#34;31j5uSKVPm\&#34;.\&#34;undefined\&#34; = $1 THEN 1 ELSE NULL END) AND COUNT(\&#34;31j5uSKVPm\&#34;.\&#34;note_metadata_id\&#34;) &gt; 1 LIMIT 50&#34;
routine: &#34;errorMissingColumn&#34;
severity: &#34;ERROR&#34;
[[Prototype]]: Object
[[Prototype]]: Object
locations: [{…}]
message: &#34;column 31j5uSKVPm.undefined does not exist&#34;
path: [&#39;candidacyNoteMetadata&#39;]
```
- Discrod Handle: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/37cee4a5-afb3-4838-8c4b-e9c3b2d179e6-annotated_aab2430b-a5ae-497b-b41f-ef7dc5545b59.png?etag=a836661b49a7c300ecbad4f30cee8167)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/37cee4a5-afb3-4838-8c4b-e9c3b2d179e6-annotated_aab2430b-a5ae-497b-b41f-ef7dc5545b59.png?etag=a836661b49a7c300ecbad4f30cee8167)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2124x624
**Labels**: bug-non-critical
**[Open #123 in Usersnap](https://app.usersnap.com/l/feedback/4e174062-b16e-4a91-87ef-55d2ad4521f5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
see logged error screenshot in #2646

**Comment by singulart** [comment]
Tested on prod
<img width="1006" alt="Screenshot 2022-04-14 at 16 02 27" src="https://user-images.githubusercontent.com/7863785/163396206-3d0b7324-1c83-458e-9250-383b672501f1.png">
