### ISSUE TITLE
overview: rejected proposals number keeps spinning

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#2646]
Route overview: rejected proposals number keeps spinning
![graphql-503-proposalsConnection](https://user-images.githubusercontent.com/31551045/159870261-f3840c64-e692-440f-8ced-f6b600ab49e0.png)

```
GraphQL error 
Array(1)
0:
extensions: {code: 'INTERNAL_SERVER_ERROR'}
locations: Array(1)
0:
column: 3
line: 2
[[Prototype]]: Object
length: 1
[[Prototype]]: Array(0)
message: "Can't find operator 0"
path: ['proposalsConnection']
[[Prototype]]: Object
length: 1
```

**Comment by dmtrjsg** [comment]
**Test Environment:** https://dao-git-staging-joystream.vercel.app/#/overview
**Network Details:** 
Network:

wss://3.95.67.177.nip.io/ws-rpc

Query Node:

https://3.95.67.177.nip.io/query-node/server/graphql

Faucet:

https://3.95.67.177.nip.io/member-faucet/register
**Expected Result** Rejected proposals widget on Overview Module view for guest users (when member not chosen), display actual number of rejected proposals.
**Actual Result:** Proposals number displayed in the widget
<img width="1013" alt="Screenshot 2022-04-01 at 18 54 56" src="https://user-images.githubusercontent.com/93924525/161317407-1b6bd5fc-b6db-4530-ae1a-6056c3edb5a4.png">
