### ISSUE TITLE
Council Widget Card - Title markup improvement

### ISSUE THREAD

**Issue by 0x2bc** [Joystream/pioneer#2647]
## Scope

Bring the widget in-line with designs:

- [x] Extend title to two lines
- [x] Wrap with ".. in the end based on fixed width

Applies to:
Overview: guest user mode council widget

⚠️ Contained in: packages/ui/src/common/constants/styles.ts

Name of the relevant part is "DotsTwoLine"

## Design
Figma: https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=5440%3A156643

_____________
Some words are overlapping the other elements in the Olympia interface. Please check it

![Image](https://i.imgur.com/3GPNVzW.png)

**Comment by talentdev0807** [comment]
@talentdev0807
