### ISSUE TITLE
[USERSNAP] mistake

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2648]
**Taken at**: https://dao.joystream.org/#/bounty/current
**Fields**:
- Houston, we have a problem.: mistake
- Give us some details: should be &#34;нет баунти, соответствующиХ критериям поиска&#34;
- spelling mistake
- Discrod Handle: swasilenko#9850

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7e2b389e-1754-4547-86be-e3044770adae-annotated_48905b06-d314-4acd-b226-53aeb349a384.png?etag=7a41757b7df39025c71d17b09d6f6f97)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7e2b389e-1754-4547-86be-e3044770adae-annotated_48905b06-d314-4acd-b226-53aeb349a384.png?etag=7a41757b7df39025c71d17b09d6f6f97)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 1792x1120
**Browser size**: 1668x982
**Labels**: enhancement
**[Open #125 in Usersnap](https://app.usersnap.com/l/feedback/4f45ad5a-2f1e-46ab-9ca3-992107cdadb7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
✅ Checked on `Joystream:dev`

<img width="1401" alt="Снимок экрана 2022-12-02 в 13 07 20" src="https://user-images.githubusercontent.com/46903215/205279737-d975bcd5-d981-495d-810a-93dd55c23664.png">
