### ISSUE TITLE
Clarify why `Recoverable Balance` is lower than staked balance

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#2649]
The accounts page looks really good!

Things can be improved:
- the tooltip for `Recoverable Balance` is in Latin
- the tooltip for `Total Locked Balance` links to page that requires login https://app.gitbook.com/o/-M-C0Rf1ILeSmMugzduG/s/-M-C0W9924TH_Qp2jnDV/key-concepts/staking#locks
- while you are on it: receive and send buttons could get a tooltip too
- It is not clear the me as a user why recoverable balance is 10M less than staked amount (as council candidate)
- candidate stake is displayed as fully recoverable but (if my assumption is correct) and 1) 10M of candidate stake were reused as validator stake then recoverable candidate stake should be shown as 10M less. otherwise please explain.
![olympia-recoverable-balance](https://user-images.githubusercontent.com/31551045/159875487-59c2d6d4-851f-4c97-88bf-4923a38eb501.png)
- when recovering balance explain the effects, in this case that the candidacy would be withdrawn
![olympia-recover-balance](https://user-images.githubusercontent.com/31551045/159875506-c66a2b4c-9a15-4e53-86de-08458bb58744.png)

## References

Some is explained in issue comments and needs to be put in tooltips.
https://github.com/Joystream/pioneer/issues/790#issuecomment-870438120
https://github.com/Joystream/pioneer/issues/946#issuecomment-937682289
https://github.com/Joystream/pioneer/pull/934
https://github.com/Joystream/pioneer/issues/303

**Comment by dmtrjsg** [comment]
Thanks for raising. Here council lock should not be recoverable, this is already been addressed. 

Relevant tickets addressing various points raised here:
- #2363 
- #2300
