### ISSUE TITLE
Missing working group subtitles

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2650]
Basically this from the design. Seems like low hanging fruit that would help a lot with clarity

![Screenshot 2022-03-24 at 09 57 42](https://user-images.githubusercontent.com/437292/159879614-c2d7d7af-dfbd-4026-8093-1763fc951101.png)

currently it looks like this

![Screenshot 2022-03-24 at 09 58 08](https://user-images.githubusercontent.com/437292/159879694-dcbb2df7-32bf-4418-b4c0-9ede37159918.png)

**Comment by dmtrjsg** [comment]
Sure thing! was raised already but slipped away in the heat of everything else. closing this one and pointing to original>
 
- #2599
