### ISSUE TITLE
[USERSNAP] Blank screen

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2651]
## Scope

**Desktop:**
- [x] Do not serve blank screen in browsers incompatible with Polkadot JS extensions. Simply put allow users on Safari, Edge etc to browse app in read-me. 

 @stepien4soft pls don't forget to update the copy in the modal on step 1:
 
<img width="530" alt="Screenshot 2022-03-29 at 09 49 20" src="https://user-images.githubusercontent.com/93924525/160572709-53a8eb8d-48ab-4db7-a670-4dcefa13e9e7.png">

Mobile
- [x]  For mobile browsers serve a banner>
Discord URL > https://discord.com/invite/DE9UN3YpRP
Homepage URL >  https://www.joystream.org/

## Designs
[FIGMA> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8561%3A264038)

__________________

**Taken at**: https://dao.joystream.org/
**Fields**:
- Houston, we have a problem.: Blank screen
- Give us some details: Was told it was supposed to link me to download for pioneer
- Broken link
- Discrod Handle: THELOST+UNFOUNDS

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f6d4eda6-1388-4d82-b110-107419533e0c-annotated_3429e01b-ad38-4816-8ecf-8919a94e4455.png?etag=59eccf0c96f5ab98fc5e0bb3294fa6bc)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f6d4eda6-1388-4d82-b110-107419533e0c-annotated_3429e01b-ad38-4816-8ecf-8919a94e4455.png?etag=59eccf0c96f5ab98fc5e0bb3294fa6bc)*

**Browser**: Safari 15 (iOS)
**Screen size**: 428x926
**Browser size**: 428x752
**[Open #126 in Usersnap](https://app.usersnap.com/l/feedback/36eb1b9a-66c1-42ae-8e0c-6191c53ff4d7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
The app probably crashed. Can you post details from Console please (ctrl shift i).

**Comment by dmtrjsg** [comment]
@traumschule Safari isn't supported at the moment. Chrome and Firefox only.

**Comment by singulart** [comment]
<img src="https://i.imgur.com/xkgFJs8.png"/>
