### ISSUE TITLE
[USERSNAP] Election module

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2652]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Election module
- Give us some details: When applying for election to the council - you can do it twice, by accident. The application cannot be submitted without filling in all the necessary fields. But after you sign the transaction for the first time, the window with the requirement to sign it continues to hang on the screen. And if you click &#34;sign&#34; again - instead of a completed application for election to the council - there will be an empty candidate page)
- It is necessary that after the successful signing of the application to the council, the form that requests a signature disappears from the screen.
- Discrod Handle: chiffah#7922

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/96b9317a-464b-448a-ba32-d7c1d82c256c-annotated_27ebdbb6-d2df-416a-a518-c95882b524aa.png?etag=3e4b1efabedc7700dbf53a4dbf2a9e7d)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/96b9317a-464b-448a-ba32-d7c1d82c256c-annotated_27ebdbb6-d2df-416a-a518-c95882b524aa.png?etag=3e4b1efabedc7700dbf53a4dbf2a9e7d)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x722
**Labels**: bug-non-critical
**[Open #127 in Usersnap](https://app.usersnap.com/l/feedback/b12f8eb6-f8e6-45eb-af0d-6e816b017520?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by polikosi** [comment]
tested on: https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json
✅Everything works as expected. The form that requests a signature disappears from the screen.
