### ISSUE TITLE
[USERSNAP] sort members

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2654]
**Taken at**: https://dao.joystream.org/#/members
**Fields**:
- Houston, we have a problem.: sort members
- Give us some details: staked, slashed, terminated
- so far only sortable by ID
- Discrod Handle: l1dev

Out of scope (impossible):

- [ ]  balance

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a7a67605-f468-47a1-b4e0-63d833e51867-annotated_62f535e9-95b2-45aa-90d2-f80967a08285.png?etag=9312df93872982036c79ecfe1ae9fe17)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a7a67605-f468-47a1-b4e0-63d833e51867-annotated_62f535e9-95b2-45aa-90d2-f80967a08285.png?etag=9312df93872982036c79ecfe1ae9fe17)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2124x1081
**Labels**: enhancement
**[Open #129 in Usersnap](https://app.usersnap.com/l/feedback/16830683-ad64-41d5-af80-0315c93910a0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
just realized is sortable by handle too.

also balance overflow >8 digits:
![balance-overflow](https://user-images.githubusercontent.com/31551045/159887968-4cfc7282-2031-4bba-aab7-d3cf342c7eb2.png)
![balance-overflow2](https://user-images.githubusercontent.com/31551045/159888286-3dca2bb0-3e63-4b86-b267-c0ef749096d4.png)

**Comment by dmtrjsg** [comment]
Skipping for rn, as QN does not have this info for the time being.
