### ISSUE TITLE
Search member by key

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#2657]
![member-search-by-key](https://user-images.githubusercontent.com/31551045/159895112-eede6bd7-6314-4004-a063-aadb78d4e0d3.png)

**Comment by polikosi** [comment]
Verified on staging. Test evidence below:
✅ Search member by key:
![Screenshot_134](https://user-images.githubusercontent.com/80429191/177140001-2a46e987-b485-46fb-854c-fc47aa5a06c3.png)


🚫finding members by ID:
![Screenshot_136](https://user-images.githubusercontent.com/80429191/177140321-8d751d26-a411-4415-9c99-8dbef74e9ac3.png)
![Screenshot_135](https://user-images.githubusercontent.com/80429191/177140326-df2d490d-5bfa-438a-bdec-51d299437bd6.png)

**Comment by singulart** [comment]
I don't think searching by ID was required. May be requested via a separate ticket, though. Considering this as PASSED QA
