### ISSUE TITLE
Update faucet link

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#2658]
https://18.234.141.38.nip.io/member-faucet/register => 404
![settings](https://user-images.githubusercontent.com/31551045/159895981-3063beb0-f500-47b4-8d26-8c19a24bebc5.png)

**Comment by mnaamani** [comment]
This is working as expected. The endpoint expects an HTTP `POST`. To test do a simple "invalid" request, by not passing any JSON input in the request, and you should get an error back:

```sh
curl -X POST https://18.234.141.38.nip.io/member-faucet/register 
{"error":"InvalidAddress"}
```

**Comment by mnaamani** [comment]
I was planning to udpate the url to `https://olympia-faucet.joystream.org/member-faucet/register` ..

**Comment by mnaamani** [comment]
Just in case it wasn't obvious this is not a site that is mean to be visited by a human in the browser, rather it is an API endpoint used by pioneer when creating the new memberships.

**Comment by traumschule** [comment]
Yes, my expectation was a QN-like design.
