### ISSUE TITLE
[USERSNAP] "See my vote" button is not responding

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2667]
Scope:

- [x] Fix closing the modal when CTA from conf is clicked; When user clicks outside of the modal
- [x] Rename CTA from see my vote to "Back to candidates." 

_____________

**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: &#34;See my vote&#34; button is not responding
- Give us some details: After casting my vote, I tried clicking the button but not responding.
- I am not really sure
- Discrod Handle: Jen4#8632

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4b694460-692c-4aa9-a92d-8f35401eb60f-annotated_cbf465f8-548b-4495-9942-1ffe1699776b.png?etag=c42f737004944e9b80bdf2a7b9ab8282)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4b694460-692c-4aa9-a92d-8f35401eb60f-annotated_cbf465f8-548b-4495-9942-1ffe1699776b.png?etag=c42f737004944e9b80bdf2a7b9ab8282)*

**Browser**: Chrome 99 (macOS Sierra)
**Screen size**: 1440x900
**Browser size**: 1440x749
**Labels**: bug-non-critical
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/11c5bef9-7f4f-456d-a1f9-490bac15ad95_screen_recording_d3b256ec-f219-4fb6-95dc-8e33fbe4f81d.webm?etag=bb2138d4dbc0399bad08951d40221cec)**
**[Open #134 in Usersnap](https://app.usersnap.com/l/feedback/9ce8de3c-ee43-4e0e-8a74-39ad8e7f5ee5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by RafalPloszka** [comment]
I believe it has been already done in https://github.com/Joystream/pioneer/pull/2628
