### ISSUE TITLE
Can't withdraw stake after withdrawing contribution with the same member

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2669]
Contributors who also announced work cannot withdraw Stake.

.if judgement expired, work entry status does not change to passed. This is the reason for why button does not display.

Expected result:

IF Judgement Expired OR bounty failed (Judgement = no winners)

for user who both contribnut4ed and announced work entry

Two separate CTAs:
- [ ] Contribution withdrawable  (WS)
- [ ] Stake withrdrawable (WS)

..after both withdrawn bounty moves to terminated status (assuming no other withdrawals are due)

**Comment by dmtrjsg** [comment]
if judgement expired, work entry status does not change to passed. This is the reason for why button does not display.
