### ISSUE TITLE
Wrong entrant stake value in the add entry modal

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2672]
- [x] When the bounty entrant stake is set to e.g 200 the Announce Entry modal will still display 100 (which is currently the min entrant stake const).

- [x]  I'm not sure about the withdraw stake/reward modal.

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
Claim reward:
![Screenshot_6](https://user-images.githubusercontent.com/80429191/167627391-fdc0b85f-261a-4a2d-b15e-a350a587b1bc.png)
Announce work entry:
![Screenshot_7](https://user-images.githubusercontent.com/80429191/167627405-d70ddea6-1527-486b-bc3e-5d2fb92cc851.png)
Announce work entry:
![Screenshot_8](https://user-images.githubusercontent.com/80429191/167627419-e4f6e723-5719-417b-a0c8-96678ea3eb75.png)
Withdraw stake
![Screenshot_9](https://user-images.githubusercontent.com/80429191/167627429-40cab464-cce2-4663-b75a-ee41cbffd78c.png)
