### ISSUE TITLE
[USERSNAP] Member creation fee

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2673]
**Taken at**: https://dao.joystream.org/#/profile/memberships
**Fields**:

* Houston, we have a problem.: Member creation fee
* Give us some details: As far as I know the member creation in the new network is free. But I could be wrong
* Under &#34;My Profile&#34; when you create a new member through +Add Membership it says that you have to pay 100 tokens to create a member
* Discord Handle: adovrn#1094

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ecd392e3-407d-4776-bab4-65cbdaf4c55d-annotated_15a46e8f-1e7e-4aff-8e4f-ddfcb696d46f.png?etag=fa8ace5d7baf5147faeda76f31615fa8)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ecd392e3-407d-4776-bab4-65cbdaf4c55d-annotated_15a46e8f-1e7e-4aff-8e4f-ddfcb696d46f.png?etag=fa8ace5d7baf5147faeda76f31615fa8)_

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**Labels**: bug-non-critical
**[Open #135 in Usersnap](https://app.usersnap.com/l/feedback/9c29c5f1-ca44-4586-b99f-4bc18002f4f3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203225889327621) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@bwhm is this a runtime param which we are seeking to update?

**Comment by mochet** [comment]
I think this can be closed.
Memberships were never free and the `100 tJOY` has I believe always been the correct fee.

The user is creating a new membership without using the faucet so as far as I can see all of this behavior is 100% correct.

**Comment by traumschule** [comment]
It's < 17 JOY on Carthage and there's a faucet. Please reopen if you think it's still a problem.

![carthage-fee](https://user-images.githubusercontent.com/31551045/200429316-d38c5c92-c1ed-400d-a4a5-fec29566bbc8.png)
