### ISSUE TITLE
[USERSNAP]  Remove referrer from faucet membership creation flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2675]
## Context

In case of membership purchased from Faucet, the referrer is not accepted. So we are making the decision to remove it from the onboarding modal.

## Scope

- [ ] Remove referrer from onboarding flow

Out of scope
- [ ] #3520
___________

**Taken at**: https://dao.joystream.org/#/profile
**Fields**:
- Houston, we have a problem.: There is no way to specify the person who invited you
- Give us some details: I think the user at this point should be able to specify who invited him
- When connecting to Pioneer for the first time, the user cannot specify the person who invited him/her.
- Discord Handle: adovrn#1094

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ca67f4f0-844d-4f47-b7ad-6f8ad8a1f449-annotated_e07957ce-00e4-433e-b825-d9b840d4f3f3.png?etag=2fa99eb5f37f3f4ee0242b0e175e6e3f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ca67f4f0-844d-4f47-b7ad-6f8ad8a1f449-annotated_e07957ce-00e4-433e-b825-d9b840d4f3f3.png?etag=2fa99eb5f37f3f4ee0242b0e175e6e3f)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**Labels**: bug-critical
**[Open #137 in Usersnap](https://app.usersnap.com/l/feedback/e17e1ca2-ab21-448f-984c-c47beb105b50?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
After a quick look seems line [register](https://github.com/Joystream/membership-faucet/blob/27da282dafc8e3d4a127ee58ef0baa9a36c82be5/src/register.ts#L20) method on membership faucet endpoint doesn't support `referrer_id` as `buyMembership` does.

**Comment by bedeho** [comment]
´buy_membership` does support providing a referrer, see here

https://github.com/Joystream/joystream/blob/master/runtime-modules/membership/src/lib.rs#L420

where the parameter `BuyMembershipParameters` is as follows 

https://github.com/Joystream/joystream/blob/master/runtime-modules/membership/src/lib.rs#L202

```Rust
/// Parameters for the buy_membership extrinsic.
#[derive(Encode, Decode, Default, Clone, PartialEq, Debug, Eq)]
pub struct BuyMembershipParameters<AccountId, MemberId> {
    /// New member root account.
    pub root_account: AccountId,

    /// New member controller account.
    pub controller_account: AccountId,

    /// New member handle.
    pub handle: Option<Vec<u8>>,

    /// Metadata concerning new member.
    pub metadata: Vec<u8>,

    /// Referrer member id.
    pub referrer_id: Option<MemberId>,
}
```

However, the _faucet_ (which is not the runtime) may need to be augmented possibly, I think @thesan should probably be familiar with how it works.

**Comment by dmtrjsg** [comment]
@mnaamani  are you aware of the corresponding Runtime issue or should I raise it? ty

**Comment by bedeho** [comment]
My last comment explains that there is no need for anything new on the runtime, perhaps I am misunderstanding something here?

**Comment by dmtrjsg** [comment]
@thesan pls advise.
