### ISSUE TITLE
WG tooltips

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2680]
## Scope
- [ ] For each WG add tooltip, which links to gitbook for each working group:

☝️ Placement of tooltip
In the end of the title:

<img width="495" alt="Screenshot 2022-10-07 at 17 38 10" src="https://user-images.githubusercontent.com/93924525/194567018-d0d3facb-d486-425e-ac9a-88906a183e60.png">

☝️ Copy of tooltip

"Learn more about this group [External link icon]"

Hyperlinks to:
[Storage>](https://joystream.gitbook.io/testnet-workspace/system/storage)
[Content >](https://joystream.gitbook.io/testnet-workspace/system/content-directory)
[Builders>](https://joystream.gitbook.io/testnet-workspace/system/builders)
[Distribution>](https://joystream.gitbook.io/testnet-workspace/system/storage#distributor)
[Marketing>](https://joystream.gitbook.io/testnet-workspace/system/marketers)
[Human Resources](https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/human-resources-score)
[Membership>](https://joystream.gitbook.io/testnet-workspace/testnet/council-period-scoring/human-resources-score)

Design prompt:
<img width="199" alt="Screenshot 2022-10-07 at 17 41 56" src="https://user-images.githubusercontent.com/93924525/194567673-80d6afee-1327-40ec-9e1d-194fd59b92c7.png">

**Comment by polikosi** [comment]
tested on: https://pioneer-2-git-mainnet-joystream.vercel.app/?network-config=https://34.230.5.182.nip.io/network/config.json#/working-groups

⚠️Add link for App working group 
![image](https://user-images.githubusercontent.com/80429191/206449991-20763e7e-ffa4-4e96-bfa9-c5b4068733c8.png)

✅on dev: https://dao-git-dev-joystream.vercel.app/#/working-groups
everything is good
![image](https://user-images.githubusercontent.com/80429191/206450380-34adbfe6-9ab2-4da1-8102-e0fdee695063.png)
