### ISSUE TITLE
[USERSNAP] Vertical scroller on empty screen

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2689]
## Context

In the guest user sign up flow, when the Sign up modal in the top of the screen is visible, the vertical scroll appears where it should not (without any polkadot accounts created/visible/ recognised by the browser)

## Scope

Make the onboarding modal top bar function as a sticky header - when user is scrolling the page the panel is affixed to the top of the page and scrollable content goes underneath it.

__________
**Taken at**: https://dao.joystream.org/#/election/past-elections
**Fields**:
- Houston, we have a problem.: Vertical scroller on empty screen
- Give us some details: There is a vertical scroller, which seems to be generated due ot the &#34;Become a member&#34; header, despite there not being any content on the screen.
- Not sure
- Discord Handle: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b6e5ac8c-9757-460f-865f-a4df9f0cafed-annotated_b7e3d549-9f87-4db5-a1a2-f1b84febb109.png?etag=6be0fbbf15211442b42835eaccf46943)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b6e5ac8c-9757-460f-865f-a4df9f0cafed-annotated_b7e3d549-9f87-4db5-a1a2-f1b84febb109.png?etag=6be0fbbf15211442b42835eaccf46943)*

**Browser**: Firefox 98 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1765x812
**Labels**: bug-non-critical
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/eb8a81ce-d6ea-4d19-a187-909f43902736_screen_recording_0faa9b50-ae03-4b8f-938b-730e189b58f9.webm?etag=1445932010a799e0730890d0d94473c5)**
**[Open #143 in Usersnap](https://app.usersnap.com/l/feedback/9d4e83f1-3eb6-4de0-b6ae-29061993dc70?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by talentdev0807** [comment]
I would like work on this ticket

**Comment by talentdev0807** [comment]
This bug comes from adding `Become a member`  header
Originally, main boday height is 100%, it is natural to have scroll when we add it on top screen
So, I made `Become a member` header as sticky header

**Comment by ivanturlakov** [comment]
Tested on staging.
MacOS Big Sur, latest versions Firefox/Safari/Chrome.

Without items
https://user-images.githubusercontent.com/46903215/168779938-b358cc4c-5344-40df-80e0-2e3d7e044db0.mov

With items
https://user-images.githubusercontent.com/46903215/168780390-a9b505ea-abe7-4fd1-af5c-140a64b1c84e.mov
