### ISSUE TITLE
[USERSNAP] "Popular threads" links does not work

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2692]
## Scope

On Forum Overview tab:

- [ ] redirect from Popular Threads to Particular Thread shown in the widget (now takes to Forum homepage)
- [ ] Remove "Top Threads" tab from Forum UI until its build
- [ ]  Link forum thread from My threads Overview widget needs the same adjustment (fix links)

## Tech Guidelines

 That's how the links look like rn https://dao.joystream.org/#/forum/thread/:id/24 but NEEDS to be (https://dao.joystream.org/#/forum/thread/24)

__

**Taken at**: https://dao.joystream.org/#/forum/overview
**Fields**:
- Houston, we have a problem.: &#34;Popular threads&#34; links does not work
- Give us some details: Just work
- Links to the posts from &#34;Popular threads&#34; redirect to the main forum page insteed of the exact posts.
- Discord Handle: Ilich#3455

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/63d1a675-fbaf-469e-8afc-4eea849fcf51-annotated_557b2903-3e35-45ca-8cf2-51d6c8406e75.png?etag=fcab76e8efddd4a33a41c3e6340e84ad)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/63d1a675-fbaf-469e-8afc-4eea849fcf51-annotated_557b2903-3e35-45ca-8cf2-51d6c8406e75.png?etag=fcab76e8efddd4a33a41c3e6340e84ad)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 2560x1440
**Browser size**: 1707x865
**Labels**: bug-non-critical
**[Open #146 in Usersnap](https://app.usersnap.com/l/feedback/11f206b3-21b6-44ca-9185-db54bf4ef669?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by adovrodion** [comment]
Bounty link: https://dao.joystream.org/#/bounty/preview/79

**Comment by ivanturlakov** [comment]
Tested on staging

Threads links work well

https://user-images.githubusercontent.com/46903215/175565158-4fbd0b36-1d18-4435-ac6f-f5e15347a455.mov
