### ISSUE TITLE
[USERSNAP] GraphQL error on Submit work For Bounties

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2700]
- [ ] This issue is about the counter of works submitted widget during working period. RN not working

**Taken at**: https://dao.joystream.org/#/bounty/preview/2
**Fields**:
- Houston, we have a problem.: GraphQL error
- Give us some details: &#39;INTERNAL_SERVER_ERROR&#39; message: &#34;column 6ufMB7XopT.undefined does not exist&#34;
- path: [&#39;workSubmittedEventsConnection&#39;]
- Discord Handle: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/58b465f1-7609-480a-af1d-fa896344359f-annotated_74cde6e3-6892-4d91-a06d-a214a3a4ae83.png?etag=b00f5d32cd71ef897931a19506962568)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/58b465f1-7609-480a-af1d-fa896344359f-annotated_74cde6e3-6892-4d91-a06d-a214a3a4ae83.png?etag=b00f5d32cd71ef897931a19506962568)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1190x543
**Labels**: bug-non-critical
**[Open #153 in Usersnap](https://app.usersnap.com/l/feedback/9d552ece-75ac-4478-a59e-fe4ec2794a27?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
```
GraphQL error
extensions: {code: 'INTERNAL_SERVER_ERROR', exception: {…}}
message: "column 6ufMB7XopT.undefined does not exist"
path: ['workSubmittedEventsConnection']
```
query:
> "SELECT COUNT(DISTINCT("worksubmittedevent"."id")) AS "cnt" FROM "work_submitted_event" "worksubmittedevent" LEFT JOIN "bounty_entry" "6ufMB7XopT" ON "worksubmittedevent"."entry_id" = "6ufMB7XopT"."id" WHERE "6ufMB7XopT"."undefined" = $1 AND "worksubmittedevent"."deleted_at" IS NULL"

![graphql-workSubmittedEventsConnection](https://user-images.githubusercontent.com/31551045/160358282-5b92aec6-2d23-4b90-b28e-2a6badf94554.png)

**Comment by dmtrjsg** [comment]
Tested, works :)
