### ISSUE TITLE
[USERSNAP] Parse markdown in Posts, Applications, Profiles

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2712]
## Scope

Add markdown interpretation in all fields initially created with CK Editor (Description/ Forum posts etc)

- [ ] Interpret internal identifiers
- [ ] external links
- [ ] headings in text fields
- [ ] Line breaks

⚠️  We do not use markdown in Field form Entries (like titles etc..)
__________
**This should cover all text fields, but specifically:**

- Proposal/ bounty discussion
- Forum post
- ~Widgets with text shown in them~
- Application
- proposals descriptions
- proposal rationales
- wg roles applications
- election candidates 
- bounty descriptions #3218 
- work submitted
- Oracle rationale for judgement

Out of scope:

- Widgets with text shown in them

## Context
____

**Taken at**: https://dao.joystream.org/#/working-groups/openings/operationsWorkingGroupAlpha-1
**Fields**:
- Houston, we have a problem.: Parse markdown in Posts, Applications, Profiles
- Give us some details: There are several places where user can input text but markdown links and headings are usually not interpreted.
- This is a downgrade from previous Pioneer.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/061695b3-cdae-4e23-b44a-7945a7410038-annotated_c8d11cac-774e-45bc-84c7-e5aa7f351d45.png?etag=b54b9d58e8990b4cae665c375683247a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/061695b3-cdae-4e23-b44a-7945a7410038-annotated_c8d11cac-774e-45bc-84c7-e5aa7f351d45.png?etag=b54b9d58e8990b4cae665c375683247a)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2390x1216
**Labels**: enhancement
**[Open #159 in Usersnap](https://app.usersnap.com/l/feedback/4d567d1d-21cf-4a08-a6f7-e997f69872e7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
> in the future we need an algorithm that will analyze what percentage of the video will be watched by the viewer.  For example from 20 seconds. [discord](https://discord.com/channels/811216481340751934/812345044094156811/971745437218385940)

> Our view counts are very primitive at the moment, and anyone can easily create thousands of views without much effort really. There is an open question on how this data will be stored in the future - currently we just keep this in Orion's DB but in the future there will be multiple Orion's instances and they probably want to share this data with each other. It also would be useful for the council to have some view stats to act upon. We had some early ideas like separate, permissioned blockchain just for gateway operators but that's a bit far in the future atm [discord](https://discord.com/channels/811216481340751934/812345044094156811/971774064962195466)

**Comment by singulart** [comment]
The component used at Joystream as WYSIWYG editor (CK Editor) has an open issue https://github.com/ckeditor/ckeditor5/issues/2321 that is exactly about being able to paste md content to a text area and then seeing that text as html. I am not sure if Joystream Builders are in the position to fix any downstream components issues, such as the above. For now I am closing this issue as `Won't Fix`

**Comment by thesan** [comment]
@singulart @talentdev0807 I tried to clarify the description a bit, but this issue is not about parsing markdown in CK editor. It's about using `<MarkdownPreview />` component to parse the markdown on the app, e.g here:

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/061695b3-cdae-4e23-b44a-7945a7410038-annotated_c8d11cac-774e-45bc-84c7-e5aa7f351d45.png?etag=b54b9d58e8990b4cae665c375683247a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/061695b3-cdae-4e23-b44a-7945a7410038-annotated_c8d11cac-774e-45bc-84c7-e5aa7f351d45.png?etag=b54b9d58e8990b4cae665c375683247a)*

We mentioned CK Editor because it's hard to know which fields are markdown vs plain text (they're all `String`s in the QN schema), thus the fields that are initially created with CK Editor are those that should be parse in other places with `<MarkdownPreview />`

**Comment by talentdev0807** [comment]
When it comes to talk about <MarkdownPreview>, it is just for converting markdown to React JSX to display it on web page
so if the input of <MarkdownPreview> is wrong I mean it is not a Markdown format, we will get wrong result
The input of <MarkdownPreview> comes from CK Editor

**Comment by traumschule** [comment]
The input for existing posts should come from the QN / chain. [My suggestion](https://discord.com/channels/811216481340751934/812344874099277824/973945988173684796): If Markdown parser succeeds display that otherwise render with CK.

**Comment by oleksanderkorn** [comment]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/9252017/171059669-a7b2c70b-581d-4baf-a8b4-a97fb0552016.png">
Text which comes to MarkdownPreview is escaped with backslash.

**Comment by polikosi** [comment]
⚠️  Proposal discussion:
strikethrough, block quote and bulleted list don't work correctly
![Screenshot_65](https://user-images.githubusercontent.com/80429191/171842099-e5742b73-0018-4d0e-898e-777f9a2d6dc2.png)
![Screenshot_66](https://user-images.githubusercontent.com/80429191/171842109-38c74eac-b9aa-4d1b-a371-82a4d4f7ea27.png)

Bounty discussion:

⚠️  Forum post:
strikethrough, block quote and bulleted list don't work correctly
![Screenshot_63](https://user-images.githubusercontent.com/80429191/171841149-e4a89488-f421-4d4b-b8c6-c4ef9b05c4cb.png)
![Screenshot_64](https://user-images.githubusercontent.com/80429191/171841197-c660848b-71ca-44cf-92e6-09bcf414b646.png)



Widgets with text shown in them:

🚫 Application:
![Screenshot_67](https://user-images.githubusercontent.com/80429191/171842694-ad26ece7-78a6-4302-bd73-745dd4f73405.png)


⚠️ Proposals descriptions:
strikethrough, block quote and bulleted list don't work correctly
![Screenshot_69](https://user-images.githubusercontent.com/80429191/171843102-f3a66b46-bb90-4adb-8c26-da0cd79344ad.png)
![Screenshot_70](https://user-images.githubusercontent.com/80429191/171843331-e45039db-896e-4b5c-aedf-09f593254168.png)



⚠️Proposal rationales:
strikethrough, block quote and bulleted list don't work correctly
![Screenshot_68](https://user-images.githubusercontent.com/80429191/171843088-fffaeff4-be36-4bff-91aa-f7a3123c83e0.png)
![Screenshot_71](https://user-images.githubusercontent.com/80429191/171843455-ac84211d-42fa-4182-b96d-ebad406ab736.png)


🚫 WG roles applications:
![Screenshot_72](https://user-images.githubusercontent.com/80429191/171843601-bd04cf24-ba77-4d2d-a5b8-cb4557db33ea.png)


⚠️Election candidates:
strikethrough, block quote and bulleted list don't work correctly
![Screenshot_73](https://user-images.githubusercontent.com/80429191/171843996-4fe03b74-668a-4d6c-ac3a-473eb136fd8d.png)
![Screenshot_74](https://user-images.githubusercontent.com/80429191/171844347-22b1f5ad-9869-402c-a2cd-c4464a5d8e1d.png)

Bounty descriptions:

Work submitted:

Oracle rationale for judgement:

**Comment by dmtrjsg** [comment]
⚠️ pls address all areas outside of Bounties module, since it is being deprecated very soon in the light of new version upgrade later.

**Comment by dmtrjsg** [comment]
@polikosi it certainly did make total sense at the time of writing it up and grooming, but cannot connect the dots now. Pls skip this point and I will mark this as a strike-through and out of scope. Thank you for asking!
