### ISSUE TITLE
Working Groups: Narrow page width hides Apply Button from view

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2723]
It seems that ones with more description text are affected by this.

Example:
![image](https://user-images.githubusercontent.com/50830161/160678561-9dbbe6c0-0e72-47f2-a4c7-278e74a6cc11.png)

From the HR page the same problem also happens:
![image](https://user-images.githubusercontent.com/50830161/160678741-b7cd234e-a3de-4d2b-b7cd-6108df8ce394.png)

**Comment by dmtrjsg** [comment]
This will be addressed in #1794, which is currently not supported. Thank you for raising!
