### ISSUE TITLE
[USERSNAP] Cant submit my applications to work group, i got error

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2727]
- [ ] Submit working group application

**Taken at**: https://dao.joystream.org/#/working-groups/storage
**Fields**:
- Houston, we have a problem.: Cant submit my applications to work group, i got error
- Give us some details: Transaction must be finished
- I have no idea. Try to do it on 2 browsers.  Link from console: https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944/#/explorer/query/0x05b84ada9d4d09dd79684471fb2904b9d369e361bea3a1681367f551bc4b014c
- Discord Handle: GodsHunter | DOUBLE TOP#5319

<img width="659" alt="Screenshot 2022-03-30 at 08 50 00" src="https://user-images.githubusercontent.com/93924525/160779827-34c30491-9fea-4c12-92ef-e463d8f47e23.png">

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1f03a148-35af-4342-955b-5c55c1805cfd-annotated_f51d785d-ffe5-4a96-a1ba-469eb75a470a.png?etag=d420a80eb19defcfe81353bfb1e08996)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1f03a148-35af-4342-955b-5c55c1805cfd-annotated_f51d785d-ffe5-4a96-a1ba-469eb75a470a.png?etag=d420a80eb19defcfe81353bfb1e08996)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1365x901
**Labels**: bug-non-critical
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/82d6c388-606a-423b-9e41-a60094993671_screen_recording_f1c5f6eb-f2a0-48e1-a865-3237b6176bff.webm?etag=0f2828a2ca396056bc3452223c0b7a33-2)**
**[Open #163 in Usersnap](https://app.usersnap.com/l/feedback/5f0b249c-aa75-411f-8695-41e85dc5fc5e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment]
I'm pretty sure this is the cause of the issue:
- The user used the staking account to vote, so it has a lock  - `balances.locks(5CSuu4WFADz7afhcjbEDbErQ6774uSk4cmrWzXz5kxRftKpN)`
- Pioneer assumes the user has already made the `members.addStakingAccountCandidate` extrinsic.
  - however, `referendum.vote` doesn't require, or prompt that
  - unlike most locks, this means that `members.stakingAccountIdMemberStatus(5CSuu4WFADz7afhcjbEDbErQ6774uSk4cmrWzXz5kxRftKpN)` is empty

My guess is that pioneer checks  `balances.locks` when deciding whether to include the `members.addStakingAccountCandidate` extrinsic, but not `members.stakingAccountIdMemberStatus(5CSuu4WFADz7afhcjbEDbErQ6774uSk4cmrWzXz5kxRftKpN)`.

It has to do both. The former to check whether the requested account has any rivalrous stakes, but also the latter to confirm that the relationship exists.
