### ISSUE TITLE
Withdraw modal on withdrawing entry (w/o submitted work)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2730]
- [ ] Need to for the withdraw work we need to determine specific entry for the selected member and has tobe done Async to show withdraw modal on first click

**Comment by ivanturlakov** [comment]
Tested on staging.
"Problem experienced before: withdrawal modal was not triggered after selecting a member starting from guest view."
@dmtrjsg Did I understand correctly, that this is the case where there was a problem?

https://user-images.githubusercontent.com/46903215/169279116-6c6eed75-d48b-4889-ad31-01aa550a3a9d.mov
