### ISSUE TITLE
[USERSNAP] Better broken image link placeholder

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2737]
Scope:

- [ ] Make bounty image optional, if not provided> Show Joystream logo recipe
- [ ] Show broken link image for broken links.

__

**Taken at**: https://dao.joystream.org/#/bounty/current
**Fields**:
- Houston, we have a problem.: Better broken image link placeholder
- Give us some details: broken image link looks bad
- No handling of broken image URLs
- Discord Handle: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dce3a427-7ef6-433a-8fb3-10eb72fac10d-annotated_e977ae01-ccc0-435c-8045-fe38b88afaba.png?etag=e04bafb9ad1204e128be2ec811825185)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dce3a427-7ef6-433a-8fb3-10eb72fac10d-annotated_e977ae01-ccc0-435c-8045-fe38b88afaba.png?etag=e04bafb9ad1204e128be2ec811825185)*

**Browser**: Firefox 98 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1568x1229
**Labels**: bug-non-critical
**[Open #168 in Usersnap](https://app.usersnap.com/l/feedback/d5f476d9-36d3-4628-a001-4b6def605c97?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by MattAugustynowicz** [comment]
[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=7117%3A192853)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/e996c5a8-33f9-4c71-b6b1-2a03afe4613b)

**Comment by dmtrjsg** [comment]
⚠️  Ignore the bag icon on the Gabiel avatar

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
![Screenshot_13](https://user-images.githubusercontent.com/80429191/168266839-28686b9b-3558-4de7-87a8-a0e6b8eef4c2.png)
