### ISSUE TITLE
[USERSNAP] Stuck at "Waiting for extension" after applied for Elections

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2744]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Stuck at &#34;Waiting for extension&#34; after applied for Elections
- Give us some details: After applying for the election and filling my password on the polkadot extension it remain waiting for the authorization from the extension
- It didn&#39;t detect that I submitted the transaction on the polkadot extension
- Discord Handle: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/aa5f6cde-12ad-4536-9e82-65cf39eb2669-annotated_32ff5fc9-c7d6-43f6-9aa9-c868b3592e01.png?etag=cf13c5ea99d80498becbbbcbb97aea45)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/aa5f6cde-12ad-4536-9e82-65cf39eb2669-annotated_32ff5fc9-c7d6-43f6-9aa9-c868b3592e01.png?etag=cf13c5ea99d80498becbbbcbb97aea45)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1244x1236
**Labels**: bug-non-critical
**[Open #171 in Usersnap](https://app.usersnap.com/l/feedback/d9ec609b-3426-4569-9f25-6d26e0245ab8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by freakstatic** [comment]
The application was submitted but a lot of information was missing, like the bullet points, banner image and description

**Comment by dmtrjsg** [comment]
@freakstatic thanks for raising! Is it still possible to share the link to polkadot block details?

**Comment by traumschule** [comment]
Already got used to reload at this point :)

**Comment by dmtrjsg** [comment]
@traumschule  Not for long hehe ;) we're deploying QN refetch fixes so it should be smooth and reliable soon 🚀
