### ISSUE TITLE
Critical: Pioneer needs to show the blockheight that the QN is sync'd to somehow

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2762]
# Problem
The Query Node on the active testnet appears to be down. Pioneer is currently showing proposals that have already been voted on, people are revealing votes and **this is a really bad situation.**

Using query node commands, I believe the Query Node has been down for ~potentially `12 or more hours` ~(!). EDIT: The Query Node was down for more than 18 hours before it was even reported

New and old users alike have not noticed this, because of a variety of reasons which include:
* No one on the testnet actively tracks the status of the QN (that I am aware of) to see when it is down (this will be solved soon)
* I'm probably one of the "oldest" users on the testnet, and although I am not an expert I can't even tell if the Query Node is down. I'm using a variety of queries to figure out what is going on and unable to get a clear answer as to what block the query node last recorded chain information.
* The Indexer node says everything is up to date and `insync`
![image](https://user-images.githubusercontent.com/50830161/161374163-53c4eae0-fbdf-4589-8606-4eefd24ad443.png)

In general, the Query Node has proven to be unreliable at times and although it is improving, it is highly important for users to be easily able to understand when the Query Node is actually down. Joystream is still a testnet, but they should have access to this information easily so that troubleshooting and information can flow far more easily.

# Solution
On the settings page on Pioneer, the following should be shown:
- The latest blockheight from the Query Node
- The latest blockheight from the Indexer Node
- (ideally) the latest blockheight from the Joystream validator network

**Comment by traumschule** [comment]
Possibly also a log tail if there were errors?

**Comment by dmtrjsg** [comment]
@traumschule @mochet thanks for raising this guys!

Pls see issues for reference:

- #2342 
- #2538  
- #2738
