### ISSUE TITLE
[USERSNAP] Misleading Roles tab

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2770]
- [ ] Rename tab to "Working Groups Roles"
___

**Taken at**: https://dao.joystream.org/#/council
**Fields**:
- Houston, we have a problem.: Misleading Roles tab
- Comment: Roles tab on a member preview only list working group roles, not being in the council for example, so it should be renamed Working Group Roles
- Bad title
- Feedback: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/39ff8e66-88ec-44b6-9a66-d534b14e1160-annotated_f0a78b7f-0ee4-411f-8e51-7d18ab6c30cc.png?etag=ea6d9736fd2fc40899f80f58ac58c83b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/39ff8e66-88ec-44b6-9a66-d534b14e1160-annotated_f0a78b7f-0ee4-411f-8e51-7d18ab6c30cc.png?etag=ea6d9736fd2fc40899f80f58ac58c83b)*

**Browser**: Firefox 98 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1591x1096
**[Open #179 in Usersnap](https://app.usersnap.com/l/feedback/d74e5dad-75bc-4e5d-8c58-be354e00b28b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@traumschule can you pls elaborate on :

<img width="371" alt="Screenshot 2022-04-07 at 10 41 58" src="https://user-images.githubusercontent.com/93924525/162170681-7e0f02b3-296f-4866-8819-06e993acdf81.png">

**Comment by traumschule** [comment]
if i had thee wishes
- show DECIDING proposals on Council View
- show truncated rationale preview for each
- show current vote status for each (if any show number of APPROVE / REJECT / ABSTAIN votes)

**Comment by adovrodion** [comment]
Bounty link: https://dao.joystream.org/#/bounty/preview/63
