### ISSUE TITLE
AddBountyModal - validation refactor

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/pioneer#2774]
Context
Goal of this issue is to clean up the validation logic on Bounty modals to help further development/bug resolving for any developer involved

Scope
Purpose of refactor is to remove doubled validation on each modal and stick only to the Yup one. For UX/UI side everything should be the same, this issue is some way is a pre-cursor to the https://github.com/Joystream/pioneer/issues/2802 and is about improving speed and ease of future community development.

Corresponding PR: https://github.com/Joystream/pioneer/pull/2775

**Comment by singulart** [comment]
Moving back to backlog as this has no underlying PR

**Comment by singulart** [comment]
Verified on https://pioneer-2-git-fix-announce-entry-validation-joystream.vercel.app/
