### ISSUE TITLE
SubmitJudgementModal - validation refactor

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2780]
Context
Goal of this issue is to clean up the validation logic on Bounty modals to help further development/bug resolving for any developer involved

Scope
Purpose of refactor is to remove doubled validation on each modal and stick only to the Yup one. For UX/UI side everything should be the same, this issue is some way is a pre-cursor to the https://github.com/Joystream/pioneer/issues/2802 and is about improving speed and ease of future community development.

**Comment by singulart** [comment]
How is this Ready for Test without any PR? Moving back to backlog..

**Comment by dmtrjsg** [comment]
@singulart  https://github.com/Joystream/pioneer/pull/2814 here it is ;)

<img width="962" alt="Screenshot 2022-04-11 at 19 51 50" src="https://user-images.githubusercontent.com/93924525/162809285-b03509f1-9734-4ec2-875d-4ae51fc55d77.png">
