### ISSUE TITLE
[USERSNAP] Forum: Make title stays visible

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2785]
**Taken at**: https://dao.joystream.org/#/forum/thread/16?post=61
**Fields**:
- Houston, we have a problem.: Forum: Make title stays visible
- Comment: Cosmetic: when scrolling down navigation and thread title need to stay visible.
- They scroll away.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6788b3bf-3b00-4792-b360-dfff2a1c3d04-annotated_29bc6774-d2a2-45b7-9b85-a4682c8387e9.png?etag=e68ffe36519b703974ca0e525568168c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6788b3bf-3b00-4792-b360-dfff2a1c3d04-annotated_29bc6774-d2a2-45b7-9b85-a4682c8387e9.png?etag=e68ffe36519b703974ca0e525568168c)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2390x1216
**[Open #182 in Usersnap](https://app.usersnap.com/l/feedback/f59e47a6-1f6e-4f77-b070-7f95e8b83440?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Maybe even first post? Could make sense for some threads.

**Comment by MattAugustynowicz** [comment]
For now, let's add a shadow to the top bar when scrolling. 

[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9126%3A329404)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/2843f13e-3113-4db1-9fc5-3e41319ebb71)
