### ISSUE TITLE
[USERSNAP] Hide button on Proposals and Proposal Preview

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2787]
- [ ] Fix the issue - hide "vote" button when proposal vote is already casted for a given member.
_____
**Taken at**: https://dao.joystream.org/#/proposals/preview/47
**Fields**:
- Houston, we have a problem.: Hide button on Proposals and Proposal Preview
- Comment: Check if Councilor voted on the proposal and hide if so.
- Suggests voting twice is possible.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9be70733-b5fb-4b19-84ba-9b1455676b32-annotated_5063e784-f915-48af-be4c-3abb065fea96.png?etag=7babc5151f55e560c72b18a49f81b9a4)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9be70733-b5fb-4b19-84ba-9b1455676b32-annotated_5063e784-f915-48af-be4c-3abb065fea96.png?etag=7babc5151f55e560c72b18a49f81b9a4)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1190x665
**[Open #183 in Usersnap](https://app.usersnap.com/l/feedback/45f6c4f7-82ab-4f04-a070-3e57db29b333?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Mentioned `Vote` buttons for illustration:
![Proposals](https://user-images.githubusercontent.com/31551045/161622352-9698f243-5b61-445e-b199-2f82b4b0a37e.png)

Similar: `Recover` button when [stake is locked after election](https://discord.com/channels/811216481340751934/812344657794301972/960250075412561991)

**Comment by traumschule** [comment]
i noticed the status is loaded from chain and now the button disappears after a while. :+1:

**Comment by singulart** [comment]
@traumschule please pick this one up.

**Comment by polikosi** [comment]
Verified on staging. Test evidence below. 

The "vote" button is hidden.
![Screenshot_127](https://user-images.githubusercontent.com/80429191/174884459-78fc2525-db2a-428b-a073-06753cb66a6a.png)
![Screenshot_126](https://user-images.githubusercontent.com/80429191/174884474-184bec14-b389-49c4-8b0e-914f0f2c4795.png)

**Comment by polikosi** [comment]
Verified on staging. Test evidence below:
✅the button isn't hidden
![Screenshot_137](https://user-images.githubusercontent.com/80429191/177141116-437b750f-e463-4242-b4eb-6ec2ba8bcc2e.png)
