### ISSUE TITLE
Candidate BP are hardcoded

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2793]
## Context

Fix candidate bullet points to be displayed correctly in the voting modal

## Scope

**Expected Result:** Candidate-submitted bullet points displayed in the "Vote For Candidate" modal 
**Actual Result:** Rn the input for candidate Bullet Points (see image from details) is hardcoded from designs

## Additional info
https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/d97830a4-e04c-4545-854d-e80a2373fb9c

## Technical Approach

- Find the hook that fetches that specific data
- Proceed to the schema of the hook and check if you have access to this data on Graph QL
- Add this data to entity in `council.graphql`
- Regenerate Queries following [this documentation](https://github.com/Joystream/pioneer/blob/dev/docs/README.md#adding-queries)
- Update casting and types
- Apply the changes to the component displaying the BP

**Comment by singulart** [comment]
@traumschule This had been assigned to you a while ago. Do you have ETA or progress update on this?

**Comment by freakstatic** [comment]
the QN part doesn't seem to be required anymore since the bullets appear in the applications list
![image](https://user-images.githubusercontent.com/7486476/178850901-c7379578-2fb9-4e2e-a8b0-a7ef5bad0034.png)

**Comment by gyroflaw** [comment]
Hi advorn this is gyroflaw.
Please assign this issue to me

**Comment by adovrodion** [comment]
Bounty was created - https://dao.joystream.org/#/bounty/preview/107

**Comment by singulart** [comment]
Assigned to @gyroflaw
