### ISSUE TITLE
Candidate Description Field - add text wrapping

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2794]
Expected Result: Text input is wrapped the candidate description text area box

Actual result: Text wrapping (moving text to next line if hitting horisontal constraint of the input field) is not enabled, so it goes out of bounds and breaks candidate preview details (sliding drawer on the right hand side)

:video: > https://www.loom.com/share/f26da4e3e5f240a98e2ed66f4e98c223

Preview:
<img width="542" alt="Screenshot 2022-04-05 at 13 05 30" src="https://user-images.githubusercontent.com/93924525/161750071-c0427ecb-2335-4715-9c86-a8ad50eec74e.png">

**Comment by ivanturlakov** [comment]
✅ Tested on Staging


https://user-images.githubusercontent.com/46903215/194115206-baecc51a-7dcc-4df1-bcbe-4d82faeeb335.mov
