### ISSUE TITLE
Profile: Improve `Recoverable Balance` column

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#2807]
1. [ ] Sorting by recoverable balance has no effect / ignores vested tokens.
2. [ ] Show vested total and and claimable.
3. [ ] Add voting stake to total recoverable when no longer locked.
4. [ ] Clarify total recoverable.

## Part 4

I do not understand this screen, specifically `Recoverable Balance`. [Raised here](https://discord.com/channels/811216481340751934/910968995379822633/960484575312773151)
- It is not clear how each stake contributes to total recoverable balance. Why are only 8.7M recoverable?
- There should be a recover button for all stakes (possibly disabled) or a short explanation why it is not recoverable (eg. `locked for proposal`, `locked for candidate`, `activate nomination *Unbond*`, etc.).
- Tooltips for details if suitable.

![](https://cdn.discordapp.com/attachments/812344657794301972/960217105326833764/profile.png)

[Response](https://discord.com/channels/811216481340751934/910968995379822633/960830912256426074):
> "Do you know what does the sum for Recoverable Balance mean, 8M from what?"
> - recoverable balance is smth that you staked before but now the underlying process is over so you can recover (meaning transfer funds from module acc to your member's role or staking acc.)

**Comment by traumschule** [comment]
Ref: https://github.com/Joystream/pioneer/issues/2649#issuecomment-1077862588

**Comment by dmtrjsg** [comment]
This is been worked on right at the moment, feel free to check in on the progress of this task next week:  
- #2300

**Comment by traumschule** [comment]
What is X: `200,000 + 5,533.38 - X = 200,562.46`
![cm-difference](https://user-images.githubusercontent.com/31551045/204184404-3f1c38d4-ebad-4809-8b43-8208c97cc972.png)
