### ISSUE TITLE
Cancelling membership creation signing should not stop it from being re-triggerable

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2815]
## Context 
Once membership creation flow is cancelled on the last stage, new membership button stops working, and so do other modals. 

https://www.loom.com/share/4729d10fee334974960e3551f7f902fd

## Refactoring scope

- [ ] We don't handle this for all transactions outside of bounties.
- [ ] State in xmachine is not handled by sript or by user-click
- [ ] Must be done globally  
- [ ] + Refactor bounties in-line with this approach

## Technical Guidelines

this was already fixed in #3264 Pls use the same approach here

**Comment by WRadoslaw** [comment]
Resolved by modal refactor

**Comment by traumschule** [comment]
Just a quick QA check.

**Comment by dmtrjsg** [comment]
This was tested by @WRadoslaw and its merged on dev.
