### ISSUE TITLE
WG Openings do not show `leave_unstaking_period`

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2819]
Connected with: https://github.com/Joystream/pioneer/issues/2818

# Problem
Example opening, does not show the `leave_unstaking_period` anywhere in the UI:
![image](https://user-images.githubusercontent.com/50830161/162249162-98d9f6a1-46a1-4acf-8e14-b522d2cf56da.png)

# Solution
Every WG opening should include this information, since if they resign from a role it has a much more heavy impact than just affecting stake. They will remain present in the role until the `leave_unstaking_period` has actually finished.

**Comment by dmtrjsg** [comment]
will address in 
- #2818
