### ISSUE TITLE
Create WG opening isn't clear enough on what `leave_unstaking_period` does

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2821]
## Scope

- [x] Update title to "Role cooldown period"
- [x] Add headline text (between title and input) - Period where candidate remains in the role with full access after resigning
- [x] Update copy of tooltip to . "Role cooldown period, also referred to as "unstaking period" sets a block count, during which the most recent member is retained in the role, but staking status is set to unstaking - where final removal of worker and staking lock occurs after leaving unstaking period.
Link >"

- [x] link to git book in tooltip pointing to: [Link >](https://joystream.gitbook.io/testnet-workspace/system/working-groups#leave-worker-role)

__

This needs to be improved or reworded so it is much clearer that the person will remain in the role, if they resign, up until the unstaking period is over.
I would even suggest that the title of the field `Leaving Unstaking Period` is reworded or given further explanation in parenthesis to ensure the importance of this field is clearer to users. 

![image](https://user-images.githubusercontent.com/50830161/162255273-945ddcee-eec3-4d2f-ac65-a94b93fae2ab.png)

**Comment by traumschule** [comment]
The proposal effectively means `Block lead position by leaving for X blocks`. Self-firing is still the *more friendly* option.

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
![Screenshot_17](https://user-images.githubusercontent.com/80429191/168806476-def03e40-81f1-427b-9170-872a668820c0.png)
![Screenshot_16](https://user-images.githubusercontent.com/80429191/168806502-7f426e77-b7b3-4a45-9f87-3aebe47acecd.png)
Link in tooltip correct
![image](https://user-images.githubusercontent.com/80429191/168806929-2a69fa46-5c1a-4187-b07c-42f76fbde090.png)
