### ISSUE TITLE
Add link to Polkadot apps

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2823]
⚠️ Validating if we need two separate links to validators / nominators.

### Scope
Add link  to 

* [x] onboarding flow 
* [x] settings
* [x] link on block numbers to specific number preview (linked #1993 )

Suggested Copy: "Some operations for nomination and validation are only supported via Polkadot.js App. Check Joystream test network explorer."

:information_source:  link to Joystream explorer will be pointing to : 

https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/explorer
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org%3A9944#/explorer

### Context
- - -
We should have a link to a version on of Polkadot apps, which allows people to do all the validation and nomination stuff, as well as a block explorer, as requested here
https://discord.com/channels/811216481340751934/813361923172335648/961888072734244874

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202816092179171) by [Unito](https://www.unito.io)

**Comment by MattAugustynowicz** [comment]
I propose that we could add our infoboxes components with the relevant information and a Polkadot icon

1️⃣ Onboarding Flow
[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=5441%3A168962)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/33006ec6-0527-461b-88c8-b6e98b007eb9)

2️⃣ Settings
[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8187%3A231780)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/bcb79602-7fc5-4eda-be3b-52c023d5a8bf)

**Comment by dmtrjsg** [comment]
Nice work! Only comment is for the overlay in the first screen to take the full width of the page, aligning the copy centrally.

**Comment by dmtrjsg** [comment]
Agreed to extend the guest view explainer to the bottom and find an organic place for the info box

**Comment by MattAugustynowicz** [comment]
According to the discussion and after having checked a few variants, let's stretch the box to its full width, while the texts are aligned to the left. I am also in favor of making the dark background stretch to the full height of the window :)

[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8808%3A429385)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/119b6404-4a7c-442f-8b3d-cd8789e07a5d)

**Comment by bedeho** [comment]
Tbh. I think we probably could use a link in the side menu, rather than in the settings. Someone asked again about this, and its not clear they would have gone into Settings, nor that it was part of onboarding, because they were not very new: https://discord.com/channels/811216481340751934/813361923172335648/970979260917489694

**Comment by dmtrjsg** [comment]
@MattAugustynowicz perhaps worth adding a tooltip-style pop-out panel? Re placing I guess best to be addressed together with /after #2738 since both (potentially) address bottom section of TopNav menu..

**Comment by toiletgranny** [comment]
@dmtrjsg Since, apparently, part of the task has already been done by Mateusz, assuming it was good to go, I focused only on the part about adding the Polkadot Explorer link to the side navigation. 

My recommendation is to have it added as another menu item, with a small icon on the right-hand side to communicate that (a) it's an external link, and (b) that it's going to be opened in a new browser tab.

![CleanShot 2022-08-23 at 16 32 18](https://user-images.githubusercontent.com/35307309/186185634-6ae9b310-4e34-4530-bfe3-b0b1a48bcd09.png)

Because the list of menu items was quite lengthy already, I also recommend introducing a subtle enhancement to the way we treat vertical scrolling inside of the menu items container. All changes, including the new Polkadot Explorer menu item, and provisional documentation for the overflow treatment, can be reviewed in Figma — https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10920%3A1070884

**Comment by toiletgranny** [comment]
Action item: add a tooltip "Some operations for nomination and validation are only supported via Polkadot.js App" upon hovering the Explorer menu item in the side nav.

**Comment by dmtrjsg** [comment]
⚠️ Validating if we need two separate links to validators / nominators.

**Comment by polikosi** [comment]
Verified on wss://54.172.154.45.nip.io/ws-rpc



The design is slightly different than expected which is provided in figma
Actual:
![image](https://user-images.githubusercontent.com/80429191/191495733-32da4076-e653-4771-b886-80570f1b7150.png)


Expected:
![image](https://user-images.githubusercontent.com/80429191/191495579-74a3e240-75bc-4ff7-a52a-75c78577c817.png)


As for me, it is not necessary to make 2 links to validators / nominators.
But as a new user on Polkadot, it may be necessary.
