### ISSUE TITLE
The claim reward modal doesn't show the entrant stake amount

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#2825]
Expected result:

Modal shows and details the actual amount "cashed out" by bounty winners, which is the reward (already shown before) + the amount their entries stake.

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
![Screenshot_11](https://user-images.githubusercontent.com/80429191/167859210-f4c374ee-b12f-4b93-bc07-30d877f1851b.png)
