### ISSUE TITLE
[USERSNAP] Election stakes are not reusable

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2826]
## Scope

- [ ] Make voting stake re-usable in accordance with [this case (voting in previous election with this stake](https://joystream.gitbook.io/testnet-workspace/system/council#submit-sealed-vote)

____

**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Election stakes are not reusable
- Comment: Stakes currently locked for a candidate cannot be reused in the following election.
- a speculative mix of
- runtime: recovering stake fails with `referendum.UnstakingForbidden` (see linked block)
- pioneer2 does not offer the locked stake for voting
- QN: possibly wrong data somewhere?

Reported by the council: https://discord.com/channels/811216481340751934/812343711870091285/961950038383267880
- Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/explorer/query/0x21ea694a15d7bbe02ae84660e6d5dea1c2df9dde4098c36579524c153da72832
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2562188d-498c-4516-bcc1-be1b1ba8d5d4-annotated_ee7fc227-d80f-4096-a14c-8748fea13e80.png?etag=40e2e1b3711cb677cdb5850d98634926)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2562188d-498c-4516-bcc1-be1b1ba8d5d4-annotated_ee7fc227-d80f-4096-a14c-8748fea13e80.png?etag=40e2e1b3711cb677cdb5850d98634926)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2868x798
**[Open #188 in Usersnap](https://app.usersnap.com/l/feedback/41b6b1dc-aaf0-414f-8cb3-3a10bd2191cc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
addressed here https://github.com/Joystream/pioneer/pull/2788#discussion_r845886734 (requested changes)

**Comment by traumschule** [comment]
Please reopen. The current behavior is wrong. Stakes need to be reusable for the current election but they are not.

Just be clear: This ticket is not about recovering the stake.

**Comment by traumschule** [comment]
Maybe this is due to a new runtime limitation but before Olympia it was possible to reuse stakes that are locked for a currently residing council member in an election for the next council. It is possible that pioneer just blocks this option and the stakes can be used for voting via extrinsic.

**Comment by dmtrjsg** [comment]
Expected behaviour: voting lock from previous election is not blocking the vote in current election round. User is not required to recover it to vote for other candidates (in diff election rounds)

**Comment by traumschule** [comment]
Accounts that voted for a winner last election are still hidden in voting modal (account dropdown `Select account for Staking`) in current election.

**Comment by singulart** [comment]
@dmtrjsg somehow this issue isn't labeled, no SP estimate added. I wonder if it's even okay for Builder to spend time on it..

**Comment by dmtrjsg** [comment]
@singulart this one is JSG Dev stream, so let's just focus on the issues in Project55 if we have capacity to address the pioneer bugfixing backlog ;)

Let's discuss the process once again later today as scheduled in the calendar.
