### ISSUE TITLE
[USERSNAP] When I click 'Latest Threads' -  moderated post is appeared with wrong counter

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2830]
## Scope

Fix the counter on moderated threads.

Acceptance criteria:
- [ ] Moderated post shouldn't appears in 'Latest Threads' Category. 
- [ ] Counter of threads should exclude moderated.

______________
**Taken at**: https://dao.joystream.org/#/forum/latest-threads
**Fields**:
- Houston, we have a problem.: When I click &#39;Latest Threads&#39; -  moderated post is appeared with wrong counter
- Comment: Moderated post shouldn&#39;t appears in &#39;Latest Threads&#39; Category. Counter should works properly.
- -

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/10b67dde-bf45-462e-beaa-3b3f2d0f71c3-annotated_b3e0622a-fe02-4f98-abc2-586243782de4.png?etag=21612209eb769828d5e84bbe3a1a5595)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/10b67dde-bf45-462e-beaa-3b3f2d0f71c3-annotated_b3e0622a-fe02-4f98-abc2-586243782de4.png?etag=21612209eb769828d5e84bbe3a1a5595)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1422x677
**[Open #191 in Usersnap](https://app.usersnap.com/l/feedback/4d353b62-dd15-4fd9-9982-bf6eb8ce2c80?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by singulart** [comment]
Related to https://github.com/Joystream/pioneer/issues/2884 

Not a duplicate, as the issue 2884 is due to deletion, not moderation action

**Comment by dmtrjsg** [comment]
will be resolved in https://github.com/Joystream/pioneer/issues/2831 @singulart closing this one as duplicate and thank you for the note above 👆
