### ISSUE TITLE
[USERSNAP] When I click on Overview. Moderated thread is appeared and counter doesn't work properly

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2831]
## Scope

- [ ] Exclude moderated threads out of Overview widget
- [ ] Exclude moderated threads from latest threads counter

**Taken at**: https://dao.joystream.org/#/forum/overview
**Fields**:
- Houston, we have a problem.: When I click on Overview. Moderated thread is appeared and counter doesn&#39;t work properly
- Comment: -
- -

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/cbb553be-de5c-42b9-9205-0f342ad89b3f-annotated_4c7c1b5f-869c-4f2f-9008-de9fe48a1426.png?etag=63a8b0cbf235d52f451627b9f95a6cc2)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/cbb553be-de5c-42b9-9205-0f342ad89b3f-annotated_4c7c1b5f-869c-4f2f-9008-de9fe48a1426.png?etag=63a8b0cbf235d52f451627b9f95a6cc2)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1422x677
**[Open #192 in Usersnap](https://app.usersnap.com/l/feedback/937e20c0-1610-4f7c-8009-b86ed1626847?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by secretgir1** [comment]
**to reproduce defect follow the instruction:**

1. Add new thread (e.g. test thread)
2. Moderate this thread using CLI  - I used this command - **forum:moderateThread - c (category ID) - t (thread ID) -r ("reason")**
3. Go to Forum Overview Tab
![image](https://user-images.githubusercontent.com/106246396/170255687-5c02f9ed-b3b5-475f-9789-eb1c06c6e1c0.png)
4. Thread is displayed with replies counter -1.

**Comment by talentdev0807** [comment]
@talentdev0807

**Comment by polikosi** [comment]
verified on prod https://dao.joystream.org/#/forum/
Test evidence below: 
![Screenshot_79](https://user-images.githubusercontent.com/80429191/171872372-76390d3c-7499-46a3-b65b-3ca339315a52.png)
![Screenshot_78](https://user-images.githubusercontent.com/80429191/171872381-f9f447d1-a451-4a2e-a447-6edad169e7a8.png)
![Screenshot_77](https://user-images.githubusercontent.com/80429191/171872389-229150d6-b3ba-45dd-9272-fdc7e4661ab2.png)
