### ISSUE TITLE
[USERSNAP] Storage providers application page shows wrong information about applicants

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2833]
## Scope

- [ ] Ensure QN is not returning 2 applicants
- [ ] Fix underlying problem in Pioneer

**Taken at**: https://dao.joystream.org/#/working-groups/openings/storageWorkingGroup-6
**Fields**:
- Houston, we have a problem.: Storage providers application page shows wrong information about applicants
- Comment: Each applicant should be displayed only once.

This screen shows user isonar twice. But CLI command shows only one application from user isonar:

```
Current Group: storageProviders


________________ Opening details _________________


 Opening ID                    6
 Opening type                  Regular
 Created                       #143716
 Reward per block              -


_________________ Staking policy _________________


 Stake amount                  52.0000 kJOY
 Unstaking period              43,200 blocks


____________________ Metadata ____________________


{
    description: null,
    shortDescription: null,
    hiringLimit: null,
    applicationDetails: null,
    applicationFormQuestions: [


    ]
}


________________ Applications (2) ________________


 ID     Member      Role Acc            Reward Acc          Staking Acc
 ────── ─────────── ─────────────────── ─────────────────── ───────────────────
 13     isonar      5HT8Mt...8XmjFy     5HT8Mt...8XmjFy     5Dr9aa...bp353H
 14     ppx2022     5HGfi1...gxEC6H     5Dc8ai...Bb89wa     5HGfi1...gxEC6H
```
- Not sure
- Feedback: singulart

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ee8dcb59-797b-4af2-bbc8-f3eddd160b2f-annotated_8fc53313-2ead-49f1-aafd-a7f5ddc38a4b.png?etag=73371ad7d23efe9e69de5f082259465c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ee8dcb59-797b-4af2-bbc8-f3eddd160b2f-annotated_8fc53313-2ead-49f1-aafd-a7f5ddc38a4b.png?etag=73371ad7d23efe9e69de5f082259465c)*

**Browser**: Chrome 100 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1600x794
**[Open #194 in Usersnap](https://app.usersnap.com/l/feedback/38e2c73f-d27f-4da9-9a4b-63159c8ff9ec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Potentially same reasons as in
#2753

**Comment by secretgir1** [comment]
Accepted for development

**Comment by freakstatic** [comment]
@dmtrjsg doesn't seems to be a problem of pioneer. It's just showing what the QN returns.

QN:
```
{
  "data": {
    "workingGroupOpenings": [
      {
        "id": "storageWorkingGroup-6",
        "applications": [
          {
            "id": "storageWorkingGroup-12",
            "applicant": {
              "handle": "isonar"
            },
            "stakingAccount": "5GeaH8AGR3DC34NrcVrzimkBWUBqdJiW7sTGAG4nodt47zpH"
          },
          {
            "id": "storageWorkingGroup-13",
            "applicant": {
              "handle": "isonar"
            },
            "stakingAccount": "5Dr9aaiVxp4SujDUSqZdvQBAWmNQ15ixerk6hVdCyEbp353H"
          },
          {
            "id": "storageWorkingGroup-14",
            "applicant": {
              "handle": "ppx2022"
            },
            "stakingAccount": "5HGfi1n8R9xvfBYqjR4vASG82bVirargMvTigkopycgxEC6H"
          },
          {
            "id": "storageWorkingGroup-15",
            "applicant": {
              "handle": "MannyK"
            },
            "stakingAccount": "5EPFVczgT4Vdwgt1Vt7yu8GaxyTLxLrWNaiARatdzncRifnY"
          },
          {
            "id": "storageWorkingGroup-16",
            "applicant": {
              "handle": "yyagi"
            },
            "stakingAccount": "5FpWd9kfvLjsRZfdswnedHPkfLxHk1vAkmm9qDYuYDnGaQws"
          },
          {
            "id": "storageWorkingGroup-17",
            "applicant": {
              "handle": "julysakenew"
            },
            "stakingAccount": "5GbKfCLhfSEMQ8UCZY4EPs1McLnAbpH9yrcQGKxgGi3ris7m"
          }
        ],
        "updatedAt": "2022-04-10T10:51:42.000Z"
      }
    ]
  }
}
```

Chain:
Application 12:
{
  role_account_id: 5C4hrfjw9DjXZTzV3MwzrrAr9P1MJhSrvWGWqi1eSuyUpnhM
  reward_account_id: 5C4hrfjw9DjXZTzV3MwzrrAr9P1MJhSrvWGWqi1eSuyUpnhM
  staking_account_id: 5C4hrfjw9DjXZTzV3MwzrrAr9P1MJhSrvWGWqi1eSuyUpnhM
  member_id: 0
  description_hash: 
  opening_id: 0
}

Application 13:
{
  role_account_id: 5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy
  reward_account_id: 5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy
  staking_account_id: 5Dr9aaiVxp4SujDUSqZdvQBAWmNQ15ixerk6hVdCyEbp353H
  member_id: 2,182
  description_hash: 0x0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8
  opening_id: 6
}


As you can see something strange happen in Opening 12 because the opening_id is 0. it seems that the event on the block is right but what was saved on the chain is not not :thinking: 

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Folympia.joystreamstats.live%2Frpc#/explorer/query/153326
`ApplyOnOpeningParameters
{
  member_id: 2,182
  opening_id: 6
  role_account_id: 5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy
  reward_account_id: 5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy
  description: 
  stake_parameters: {
    stake: 52,000
    staking_account_id: 5GeaH8AGR3DC34NrcVrzimkBWUBqdJiW7sTGAG4nodt47zpH
  }
}`

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Folympia.joystreamstats.live%2Frpc#/explorer/query/159250
```
{
  member_id: 2,182
  opening_id: 6
  role_account_id: 5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy
  reward_account_id: 5HT8Mty5U5hFKVwv24uFswX2e41vurU3F5rkLMoETR8XmjFy
  description: 
  stake_parameters: {
    stake: 52,000
    staking_account_id: 5Dr9aaiVxp4SujDUSqZdvQBAWmNQ15ixerk6hVdCyEbp353H
  }
}
```

**Comment by freakstatic** [comment]
after some more investigation I notice that the Application 12 has the status "ApplicationStatusWithdrawn"
```
            "id": "storageWorkingGroup-12",
            "applicant": {
              "handle": "isonar"
            },
            "stakingAccount": "5GeaH8AGR3DC34NrcVrzimkBWUBqdJiW7sTGAG4nodt47zpH",
            "status": {
              "__typename": "ApplicationStatusWithdrawn"
            }
          }
```
so this issue can probably be solved by not showing the applications that were withdrawn

**Comment by ivanturlakov** [comment]
Tested on staging ✅

> so this issue can probably be solved by not showing the applications that were withdrawn 

Two applications are pending from ivant

<img width="1206" alt="Снимок экрана 2022-07-26 в 12 53 57" src="https://user-images.githubusercontent.com/46903215/180980680-03c84875-845f-4dc6-909e-dfbde0b67906.png">
<img width="762" alt="Снимок экрана 2022-07-26 в 12 54 45" src="https://user-images.githubusercontent.com/46903215/180980694-d617c173-31de-484e-82a4-5bac0aefae91.png">

Application id=12 has been withdrawn

<img width="1207" alt="Снимок экрана 2022-07-26 в 12 59 26" src="https://user-images.githubusercontent.com/46903215/180980692-ccff2b6b-c5c8-4406-afc1-64b7058737e1.png">
<img width="755" alt="Снимок экрана 2022-07-26 в 13 00 30" src="https://user-images.githubusercontent.com/46903215/180980688-103c4238-db12-4616-8396-4d9c6417caf6.png">
