### ISSUE TITLE
[USERSNAP] Lead apperance

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2837]
### Scope
- [ ] Fix avatars to display in circles on WG cards
see reported screenshot for details

⛔ Out of scope:
- [ ] #2839
_________

**Taken at**: https://dao.joystream.org/#/working-groups
**Fields**:
- Houston, we have a problem.: Lead apperance
- Comment: 1. Seems like avatars are not being displayed as proper circles in all cases
2. If possible it would be great if it was possible to show the lead membership name here without having to hover. There is not a ton of space, but would be useful
- bug or bad design
- Feedback: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/57418ff2-13c7-4aee-9b16-18e576b6c2a7-annotated_2d827bb5-0efa-45b6-845a-b9d2ac2d5906.png?etag=bd6f1520fd5ba7af24cae0d00adc7f28)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/57418ff2-13c7-4aee-9b16-18e576b6c2a7-annotated_2d827bb5-0efa-45b6-845a-b9d2ac2d5906.png?etag=bd6f1520fd5ba7af24cae0d00adc7f28)*

**Browser**: Firefox 99 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1744x1142
**[Open #197 in Usersnap](https://app.usersnap.com/l/feedback/d78d9d78-18c6-4fa1-bfad-43e4aa798818?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by polikosi** [comment]
1. Avatars displayed normal ✅
2. The lead membership name is not displayed without hovering the cursor 🚫

![Screenshot_3](https://user-images.githubusercontent.com/80429191/166770732-35f7987e-cdb9-4b1a-a6f4-5dfef4869b8b.png)
