### ISSUE TITLE
Display member handle underneath member avatar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2839]
**Scope:**
- Add column headers instead of labelling each field
- Add WG lead memberHandle display
- Get rid of on hover modal, show pointing finger cursor and on click show member details sliding out panel
➕ bonus: for working group description wrap text without breaking the word with hyphon "-"

[Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8846%3A346877)

**Comment by MattAugustynowicz** [comment]
If I had to suggest another solution, I think it's presented nicely inside the WG. That is, showing the avatar itself with the indicator icon and the information about being a leader on the hover. We can show our placeholder and the appropriate message for the lack of a leader. 

[👉 Figma link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8770%3A399918)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/ab4a585d-1174-4789-8033-90057947de4c)

**Comment by dmtrjsg** [comment]
@MattAugustynowicz I would prob suggest to put an alt version that satisfies the underlying request and then we can compare pros/cons?

<img width="766" alt="Screenshot 2022-04-22 at 11 28 38" src="https://user-images.githubusercontent.com/93924525/164694549-6ec7f765-2bf5-4af3-a5ad-b45da69a1c92.png">

I think the goal here is to help network ops mgt and since memebers are known by member handle, rather than avatar, saving a click/ need to go to each wg to address them in "bulk/ or sequence" may be suboptimal.

**Comment by MattAugustynowicz** [comment]
Sure, I haven't delved into #2837. In that case, by all means, let's similarly show the leaders as we have on the other tables.  The moment we click on them, let's show this drawer coming out of the right side with the details. We can also use the leader icon here to link this visually to the member's function and to other screens where this is shown similarly (for example, inside the WG). Let's also add headers above the tables to make arranging the content more manageable and readable.

[👉 Figma Link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8846%3A346877)

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/95480823/165292336-dc1e103e-da6d-4dc9-9b8b-af00df49986b.png">

**Comment by ivanturlakov** [comment]
Verified on staging.
All of the proposed changes were successfully implemented.

https://user-images.githubusercontent.com/46903215/168986734-3ec2f356-252c-49f1-b445-68bdd60430de.mov
