### ISSUE TITLE
[USERSNAP] Stake overflow on Members page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2844]
**Taken at**: https://dao.joystream.org/#/members
**Fields**:
- Houston, we have a problem.: Stake overflow on Members page
- Comment: Stake is overflowing in TOTAL STAKED column
- UI bug
- Feedback: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7f0ccc3a-a866-44a5-8d68-c09c2791af82-annotated_2f15e37b-126c-4d98-91fb-8f1277113e92.png?etag=613e53f81227bba6333527efe6730fb6)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7f0ccc3a-a866-44a5-8d68-c09c2791af82-annotated_2f15e37b-126c-4d98-91fb-8f1277113e92.png?etag=613e53f81227bba6333527efe6730fb6)*

**Browser**: Firefox 99 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1951x1213
**[Open #203 in Usersnap](https://app.usersnap.com/l/feedback/905519fd-c9ab-4163-9952-6d41504fb410?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
![total_staked](https://user-images.githubusercontent.com/80429191/166715808-c7dd05b2-179c-468d-95c1-26e637f030a7.png)

**Comment by polikosi** [comment]
1. Inscriptions are superimposed
2. There is no horizontal scroll at the bottom

![1](https://user-images.githubusercontent.com/80429191/166782868-fc957fc5-d5b0-4908-8fa4-fc53777df96a.jpg)

Size: 1024 x 600

**Comment by singulart** [comment]
@dmtrjsg re: 👆🏻- this looks like a separate issue.
