### ISSUE TITLE
[USERSNAP] A better broken avatar handler

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2846]
If image fails - show joystream Avatar (same as not).
Implement in all places where avatar appears

--
**Taken at**: https://dao.joystream.org/#/members
**Fields**:
- Houston, we have a problem.: A better broken avatar handler
- Comment: Avatars are stored exogenous to Joystream infrastructure, so it may fail, we should render in a more pleasant way.
- &lt;this field is almost never useful when reporting bugs I find, reconsider its utility&gt;
- Feedback: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0e2a0614-47ac-465a-ae55-1e3f3d6497f9-annotated_56abe9e3-21a3-4cc5-bc5e-18f86ae03505.png?etag=68b7d36559405f465aba4d3d55a3a063)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0e2a0614-47ac-465a-ae55-1e3f3d6497f9-annotated_56abe9e3-21a3-4cc5-bc5e-18f86ae03505.png?etag=68b7d36559405f465aba4d3d55a3a063)*

**Browser**: Firefox 99 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1951x1213
**[Open #205 in Usersnap](https://app.usersnap.com/l/feedback/8009f47d-6a42-4141-9337-6f975d3ac549?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:
![crashed_photo](https://user-images.githubusercontent.com/80429191/166717643-9d52b008-5c14-4736-901e-148e1f2203c0.png)
![crashed_photo2](https://user-images.githubusercontent.com/80429191/166717661-804aa766-599e-4c7e-8806-f252576a3451.png)
