### ISSUE TITLE
[USERSNAP] "Not voted" section in Proposal view won't expand

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2849]
## Scope

- [ ] Fix expanding the Not Voted section by clicking the chevron in Current Proposals
- [ ] Hide the chevron that expands the field on past proposals

Out of scope:
- [x] #2941

## Tech Guidelines

Fetch council elected at the time when this proposal was / then check filter which council is not in the votes.

<img width="317" alt="Screenshot 2022-04-22 at 12 27 29" src="https://user-images.githubusercontent.com/93924525/164705913-982b2b45-7c8e-471a-b9b1-b67c89de5895.png">

____
**Taken at**: https://dao.joystream.org/#/proposals/preview/84
**Fields**:
- Houston, we have a problem.: &#34;Not voted&#34; section in Proposal view won&#39;t expand
- Comment: Section should expand and show non-voted CMs
- Not sure
- Feedback: isonar#5236

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/084c5403-d6f1-427a-81c4-e8e99ca806d6-annotated_414120bf-c336-4dd0-af96-e73fc7b8885c.png?etag=a0e968dcdd1e69487d6bad2d05d1ad1e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/084c5403-d6f1-427a-81c4-e8e99ca806d6-annotated_414120bf-c336-4dd0-af96-e73fc7b8885c.png?etag=a0e968dcdd1e69487d6bad2d05d1ad1e)*

**Browser**: Chrome 100 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1600x794
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/344a22c3-adb5-4310-a977-98cd03c27905_screen_recording_6a45bade-678d-4eb6-9e3a-3cc1cf65d754.webm?etag=aed556f8c574b09400e8bf13e646c523)**
**[Open #208 in Usersnap](https://app.usersnap.com/l/feedback/31b6530c-3786-4331-83cf-7ba79a495968?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by singulart** [comment]
See screen recording, the screenshot isn't informative

**Comment by polikosi** [comment]
Verified on staging. 
Current proposal: everything works as it should
![Screenshot_96](https://user-images.githubusercontent.com/80429191/172352041-5ac745e4-edb5-4403-94b8-9430a14adc65.png)

Past proposal: everything works as it should
![Screenshot_97](https://user-images.githubusercontent.com/80429191/172352466-9be7c44f-d455-4362-b0db-bc337f780250.png)
