### ISSUE TITLE
[USERSNAP] 'Next' button is outside of the screen when pasting large text.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2864]
**Scope**

- [ ] Make new Thread Modal scrollable

_____________

**Taken at**: https://dao.joystream.org/#/forum/category/8
**Fields**:
- Houston, we have a problem.: &#39;Next&#39; button is outside of the screen when pasting large text.
- Comment: When I paste large text I expect the scroll bar to appear and I want to see the &#39;Next&#39; button below.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/08d203ce-7173-415c-b010-dedaa9224ffd-annotated_30fe93f0-e04b-416f-a092-5c58e2dcfb9a.png?etag=183f849b3be4b92e48e9bdfe1ee19543)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/08d203ce-7173-415c-b010-dedaa9224ffd-annotated_30fe93f0-e04b-416f-a092-5c58e2dcfb9a.png?etag=183f849b3be4b92e48e9bdfe1ee19543)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1422x677
**[Open #211 in Usersnap](https://app.usersnap.com/l/feedback/8342791b-2adf-461a-8261-9746fb802564?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by talentdev0807** [comment]
@talentdev0807

**Comment by polikosi** [comment]
Verified on staging. Test evidences below:

https://user-images.githubusercontent.com/80429191/168774340-b3d2bb34-9fa8-4094-a40f-3a8fce052ce6.mp4
