### ISSUE TITLE
Goodwill warning banner

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2879]
## Context

From time to time, there will be some sort of reason a deployed Pioneer instance is not working properly. I know we are planning some developer related features to allow for diagnostics around this, but also having some consumer facing banner or something warning that "right now things aint working that well, being worked on", can help buy some goodwill when we run into trouble. It can be a manual thing that can be triggered on infrastructure side, and ideally it would not require rebuilding the app. Would require some very light design work.

## Scope

@design
- [ ] design overlay to be shown on all pages  (see context for details)

@dev
- [ ] Enabled/disabled wo rebuilding the app

**Comment by dmtrjsg** [comment]
@bedeho is requirement of "w/o rebuilding the app?" is strict?

Dev team grooming brought up a suggestion to add an env variable and let vercel to handle the deployment if env file change is "triggered"? (redeployment is easy with Vercel)

**Comment by bedeho** [comment]
No I guess that is fine for now :)

**Comment by traumschule** [comment]
Implemented: #3680
