### ISSUE TITLE
Requirements for a Pioneer Backend

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2880]
# Background

Currently Pioneer does not have a user centric backend, by which I mean that it has services that would provide different responses for different users. In fact, the only stateful component is QN, which has no application user state at all. This limits user experience that can be provided for users, such as storing user specific off-chain data across devices, or delivering notifications by email.

# Proposal

Introduce a new backend that provides member level services, in particular binding an email address to the membership, which satisfies the following

- A member can create a representation of themselves in the backend by authenticating a challenge response signing step with their controller (but not on-chain transation). During this step the user can associate an e-mail with their membership, stored in the backend.
- Reading or writing to any state associated with a member will require authenticating using a signature with the current controller account (but not on-chain transation). Once authenticated, a token should be provided such that the user can do subsequent actions against the API without having to sign each time, e,g:
  - Email has to be verified for notifications to work, both during creation or after an edit, and there should be an endpoint that communicates that status of this verification.
  - There should be an email to retry the verification.
  - Updated an email address.
  - Verify an email address using a verification string.
- Uses GraphQL.
- An operator endpoint for simply listing all membership representations and their basic information.

This service also needs a name!

**Comment by dmtrjsg** [comment]
@bedeho Its a great idea! notifications are very important to get right in order for the platform to tick. I am v supportive of this, great to sync up on how we can get some synergies from going this direction for Atlas team. 

Once we are through with the stabilisation Phase, we shall def have this one as a candidate for this year's roadmap! Converting to epic and adding to Product Backlog for now to be triaged later!

**Comment by traumschule** [comment]
This was recently [discussed in #council](https://discord.com/channels/811216481340751934/812343711870091285/1065210519977459793) channel when the opinion came up that pioneer has reduced relevance compared to other apps, specifically to notify about key chain indicators.
QN do not notify. I outlined following functionality to be integrated with https://l1.media as community resource:
- set up email aliases for member@l1.media based on on-chain identities
- every member can change the associated email forward address via pioneer membership setting
- login to mailbox via [roundcube interface](https://roundcube.net/) (PHP though)
- alternatively: email notification settings for event subscriptions at `events.l1.media` (or similar) and authentication via wallet
- set alerts for whatever you are interested in (open for concrete ideas)

If this aligns with your expectation i can prioritize this approach.

**Comment by bedeho** [comment]
1. I'm afraid I technically did not understand this description, how it works, how Pioneer would or would not be changed, and how it relates to the presence of this backend.
2. I don't think this is the right place to unpack a design for another system, it sidetracks the Pioneer discussion here, at best one can link to it, but you are best off actually creating some sort of public repo of some kind for this other infra, where discussion and specs can be posted.

**Comment by chrlschwb** [comment]
@thesan 
Here are the things I think should be included in the backend database.
Are the social profiles stored on-chain? I don't they should be. So they should be encrypted and go to the backend DB.
I have chosen email and discord as mandatory because email is needed for notifications and discord is needed for retrieval of members data on discord activity.

- Joystream membership ID
- Social profiles
-- email (mandatory)
-- discord (mandatory)
-- twitter
-- telegram
-- facebook
-- youtube
-- matrix
-- Irc
-- wechat
-- whatsapp
-- hyperlink

**Comment by bedeho** [comment]
> Are the social profiles stored on-chain? I don't they should be.

They are, this is a metadata standard.

> I have chosen email and discord as mandatory because email is needed for notifications and discord is needed for retrieval of members data on discord activity.

You are conflating notifications for the purpose of private usage of a product, from public contact information, these are totally distinct. The mail I may choose to have as part of the public profile on chain is something I _choose_ to publish, and it may be a throwaway account not associated with my primary usage. Perhaps there needs to be better warning in pioneer when people provide social metadata, but that does not imply it should not exist.

Email for the purpose of receiving notifications associated with use of Pioneer has to do with my private usage of that product, and getting timely and expedient information, not for anyone in the world to be able to contact me on that email.

> retrieval of members data on discord activity.

It does not make sense to change behavior of Pioneer, which by the way does not apply to whatever people could chose to do manually if they wish, in order to satisfy a specific project that someone has. Going down that road will lead to chaos. Pioneer is its own product, and it's there to empower the user, not constrain the user. If people do not wish to provide certain metadata, trying to force them is futile.
