### ISSUE TITLE
[USERSNAP] Forum text too hard to read

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2886]
**Taken at**: https://dao.joystream.org/#/forum/thread/50
**Fields**:
- Houston, we have a problem.: Forum text too hard to read
- Comment: Its really hard to read, and it may be that contrast is not that good either. Compare for example readability of this page with a Medium post? It&#39;s night and day.

So I think we need to have a design review of what to do about this.
- Feedback: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9f551e47-14a7-4d5b-af7c-a6e80726d25c-annotated_0b25ab43-b9f5-4d4c-9814-cc3624d7f6e9.png?etag=7ce0940e31fd62a791a069397f1db217)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9f551e47-14a7-4d5b-af7c-a6e80726d25c-annotated_0b25ab43-b9f5-4d4c-9814-cc3624d7f6e9.png?etag=7ce0940e31fd62a791a069397f1db217)*

**Browser**: Firefox 99 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1578x1185
**[Open #218 in Usersnap](https://app.usersnap.com/l/feedback/1fe19533-097f-4b1c-a972-4abb2741e10e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
#2734 @bedeho we've already taken this to design, so fresh version will be ready for review early-mid next week!

Closing this one as duplicate and rest assured we'll get it sorted 💪

**Comment by bedeho** [comment]
Sorry, if I repeat myself, its not because I'm complaining about lack of progress, it's because I forgot :D

**Comment by dmtrjsg** [comment]
@bedeho  ofc ofc surely that was implied!  ..thought you'd still be interested to know the eta, thanks for the comment tho, appreciated 💟
