### ISSUE TITLE
[USERSNAP] Update proposal status after voting

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2896]
**Scope**

- [ ]  Refetch QN after voting on proposal LEADING to proposal status upd

___

**Taken at**: https://dao.joystream.org/#/proposals/preview/112
**Fields**:
- Houston, we have a problem.: Update proposal status after voting
- Comment: Pioneer1 was more accurate on this because it used chain state directly. pioneer2 does not catch that proposal status updated after someone voted.

This makes it necessary to manually reload the page :(
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3a962748-3eaa-4aa8-a2bc-75b11371518a-annotated_6a74ebcd-5d19-42d9-95f6-2c6595fd5849.png?etag=fbd8ec362374284a5436fbdd6f35653b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3a962748-3eaa-4aa8-a2bc-75b11371518a-annotated_6a74ebcd-5d19-42d9-95f6-2c6595fd5849.png?etag=fbd8ec362374284a5436fbdd6f35653b)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2390x1216
**[Open #221 in Usersnap](https://app.usersnap.com/l/feedback/0b4c12d3-fc8b-4e53-9572-8d6b3d457b14?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
Tested on staging

Proposal metrics and status are dynamically updated after each vote
<img width="1199" alt="Снимок экрана 2022-06-15 в 21 20 46" src="https://user-images.githubusercontent.com/46903215/173898645-4af02914-f4be-4e84-a79c-fcf945ea7479.png">
<img width="1193" alt="Снимок экрана 2022-06-15 в 21 21 52" src="https://user-images.githubusercontent.com/46903215/173899622-73569cef-d6c1-4ef4-b4f9-580302714245.png">
<img width="1198" alt="Снимок экрана 2022-06-15 в 21 24 14" src="https://user-images.githubusercontent.com/46903215/173899627-b976b083-5e9a-4bca-8602-a4e8f33b5ef6.png">
<img width="1192" alt="Снимок экрана 2022-06-15 в 21 25 16" src="https://user-images.githubusercontent.com/46903215/173898716-421aa86b-d64b-41f4-9ad8-6402710bdfe8.png">
