### ISSUE TITLE
[USERSNAP] Please wait makes we want to quit

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2905]
[READ COMMENTS]

@dmtrjsg commented on [Tue Apr 12 2022](https://github.com/Joystream/pioneer/issues/2848)

**Taken at**: https://dao.joystream.org/#/proposals/current
**Fields**:
- Houston, we have a problem.: `Please wait` makes we want to quit
- Comment: Every time clicking &#34;Add New Proposal&#34; i have to wait 30s. Then it shows me this dialogue again. Stop it!
- Tell what it is doing, check later if possible. Waiting times in pioneer are generally beyond acceptable.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2f04275c-d47f-4fa2-84a8-364b8be6761e-annotated_7190aff0-e9e7-4cb9-b6d6-201968637886.png?etag=10c73fbde6c77e746c65cc077e51fb19)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2f04275c-d47f-4fa2-84a8-364b8be6761e-annotated_7190aff0-e9e7-4cb9-b6d6-201968637886.png?etag=10c73fbde6c77e746c65cc077e51fb19)*

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2868x1460
**[Open Joystream/joystream#207 in Usersnap](https://app.usersnap.com/l/feedback/896915bc-d361-48da-8e43-5eb65361588d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

---

@traumschule commented on [Tue Apr 12 2022](https://github.com/Joystream/pioneer/issues/2848#issuecomment-1096245920)

>  Then it shows me this dialogue again.
This in this case was the "Creating proposals is too dangerous for you" screen. I NEVER want to see that again.

---

@nanaPa6oTaeT commented on [Tue Apr 12 2022](https://github.com/Joystream/pioneer/issues/2848#issuecomment-1097201957)

You are not alone=). There are many of us
![2](https://user-images.githubusercontent.com/87755694/163050907-ae9e7ef3-a73a-47f2-bfd1-302b7532a2a7.png)
![3](https://user-images.githubusercontent.com/87755694/163050922-91c5cfa7-33bf-4651-ab26-3b66af4b0ccb.png)
.

---

@oleksanderkorn commented on [Wed Apr 13 2022](https://github.com/Joystream/pioneer/issues/2848#issuecomment-1098358711)

When I was testing my fixes for new proposals creations, I hated this modal!

**Comment by dmtrjsg** [comment]
@thesan 👀 .. really nice summary of initiatives here, with most already known and added to backlog, but some are still to be planned for.. Tagging you here before this gets back to grooming with the team.

**Comment by thesan** [comment]
@traumschule thank you for this summary. As @dmtrjsg wrote we are already working on some of these e.g improving the form validation. 

About this particular long loading time on the proposal page it turns out to be due to a particularly slow chain query in the [`useHasMemberVotedOnProposal`](https://github.com/Joystream/pioneer/blob/a1caf38d7e265e37688e62db8e1285ad691173a8/packages/ui/src/proposals/hooks/useHasMemberVotedOnProposal.tsx) hook, which is send for each current proposal and end up overloading the chain connection completely. It happens on the proposal page when a member is picked. In addition reloading the page doesn't cancel the queries properly which causes long `Connecting to Joystream node` after it.

Similarly most long waiting time are caused by chain query/transaction and not the QN. Waiting for transactions is acceptable but IMO to improve performance Pioneer should rely on QN as much as possible to fetch information.

**Comment by dmtrjsg** [comment]
>For modals currently every step does its own checks which slows down every time before being able to click next because it does some opaque checks.

- it would be great if you could provide a code snippet that is behind the behaviour you are describing, as it will help us to work on this point; or if you can point to the modal / particular step that takes longer than expected due to the checks you mentioned.

>move all checks to the last screen when user actually wants to sign the transaction.

Actually, we are now working on bringing all validation to last step or a-sync like for transaction fees  #2876 

> Avoid blocking the user from doing something else after sending a transaction. 

Opening a ticket to address that :https://github.com/Joystream/pioneer/issues/2918

> I never know if displayed information is current

.. all info is current when the Buttons are showing for the user (we deliberately hid the button and show it only for "correct" states as part of debugging). We are using Apollo for this, so should not be a problem, but we will double check! Pls feel free to have a look at this PR> https://github.com/Joystream/pioneer/pull/2741

>The funniest bug i saw so far: when applying to an opening user can click Next while opening form data is loaded from the QN, effectively avoiding to fill the form.

Raising this as a bug.

Overall @traumschule thanks for all your points, with respect to making all points actionable we'd need more specific details, screenshots or (code snippet) so that we can discuss the solution in details.

**Comment by dmtrjsg** [comment]
Also, this one is being addressed rn: https://github.com/Joystream/pioneer/issues/2919

(unavailable chain for >1min after selecting membert)

**Comment by dmtrjsg** [comment]
Parking latest convo on this issue here for info:

<img width="816" alt="Screenshot 2022-04-27 at 15 14 09" src="https://user-images.githubusercontent.com/93924525/165538980-e36d6878-1c69-4f6d-9c7a-0386f2ce60ce.png">
