### ISSUE TITLE
Set Modals Width to Medium on Bounties

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2911]
**Context**
Width of all bounty modals (apart from Create Bounty) is set to Medium.

Medium size modal is already used for most processes. Originally Bounty modals listed below were using Large (the one that is used for proposals, with a side-panel showing the steps in a multi step transaction.)

In this ticket all bounty modals, _apart from create Bounty_ are using medium size modal. Only Bounty Module flows impacted.

**Scope of QA:**
Review if the following modals use medium modal:

- contribute to bounty
- announce work entry
- submit work
- submit oracle judgement
- withdrawals (in case of won/lost)

**Additional info:**

Example of medium modal: 
<img width="1008" alt="Screenshot 2022-05-04 at 11 57 53" src="https://user-images.githubusercontent.com/93924525/166670369-7ab1b091-ecd3-4738-9081-3803fea7f67d.png">

**Comment by polikosi** [comment]
So, 
- contribute to bounty - not ok, at the size of 1536 x 754 only a particle of the button is visible, the scroll is absent (attached screnshot)
![contribute_modal_without_button](https://user-images.githubusercontent.com/80429191/166937185-8fb81b02-b0f2-46f1-a011-d1137805c671.png)

- announce work entry - ok
- submit work - not ok, at the size of 1536 x 754 the button is not visible, the scroll is absent (attached screnshot)
![submit_work_without_button](https://user-images.githubusercontent.com/80429191/166936831-455a183a-86ae-4d74-88ad-719689fe88d5.png)

- submit oracle judgement - ok 
- withdrawals - ok
