### ISSUE TITLE
Fixing Workers Status and Staked Amount on past applications

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2913]
## Scope
- [ ] Display correct status of worker (hired vs not hired) in the past applications list 
- [ ] Display correct staked amount in the past applications list

Out of scope:
(other points from the context section of this issue) https://github.com/Joystream/pioneer/issues/2539

## Context
________

Although the whole opening/application/hiring process has been improved significantly, there are still a few issues:

![Screen Shot 2022-03-13 at 12 37 07](https://user-images.githubusercontent.com/35237943/158057567-b0d74670-426e-409c-8770-39c450300578.png)
- When not setting a target, it defaults to 2. This **may** be ok for the "Worker" openings (although I don't think it's the best), for Lead openings, it makes no sense.
- "Currently Staking" (I'm currently staking for 5 roles - 5k for each) seems to be a set of the stake amounts, without a separator:
   - `[5000,5000,5000,5000,5000]`
   - displayed:
      - without  "," as the thousand separator
      - a space as stake separator
      - () for omitted due to not enough space
  - `(5000 500)0 5000 5000 5000`

![Screen Shot 2022-03-13 at 12 41 27](https://user-images.githubusercontent.com/35237943/158057710-648d06a9-fd00-45b4-8dc9-4d439ba2c908.png)

- Also shows the `staked` amount as 100JOY and not hired, despite all of all but Storage Worker with ID 1 being hired.

ref #2537

**Comment by dmtrjsg** [comment]
@traumschule ready to be assigned for QA

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/working-groups/openings
wss://34.230.5.182.nip.io/ws-rpc

### ⚠️ Display correct status of worker (hired vs not hired) in the past applications list. 
User is not hired(**ApplicationStatusRejected**) but **Status is Pending** 

There is a specific issue created #3856

<img width="1212" alt="Снимок экрана 2022-12-02 в 14 32 08" src="https://user-images.githubusercontent.com/46903215/205293925-4deaee4c-cbd7-4731-82f5-a58fec3d743d.png">
<img width="1214" alt="Снимок экрана 2022-12-02 в 14 32 33" src="https://user-images.githubusercontent.com/46903215/205293931-97616d7f-3b9c-456c-b074-b7dcae7651dc.png">

### ✅ Display correct staked amount in the past applications list(I'm currently staking for 2 roles - 5k for each)
<img width="1210" alt="Снимок экрана 2022-12-02 в 15 13 19" src="https://user-images.githubusercontent.com/46903215/205300844-a6c98ee7-c44b-436b-9dac-bdf303f37034.png">

### ✅ Currently Staking(I'm currently staking for 2 roles - 5k for each)
<img width="918" alt="Снимок экрана 2022-12-02 в 15 13 43" src="https://user-images.githubusercontent.com/46903215/205300855-dedab7ad-6512-44ac-9459-0b2eb2aea348.png">

### ✅ When not setting a target => 1 Hiring limit for the Lead position by default
<img width="916" alt="Снимок экрана 2022-12-02 в 14 00 38" src="https://user-images.githubusercontent.com/46903215/205288396-951c8b8f-6fe6-4bfd-a3b9-17dff4f2d860.png">
