### ISSUE TITLE
[USERSNAP] Show recently approved proposals

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2914]
**Taken at**: https://dao.joystream.org/#/proposals/current
**Fields**:
- Houston, we have a problem.: Show recently approved proposals
- Comment: I want to see recently decided proposals with one click or even better on the same page.

Workaround to filter, select last week, apply filter does not show all so one has to adjust days manually to include today/yday.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c1f4c362-44a3-468b-b58d-7f4d0ee006b9-annotated_c8be23c8-4a41-41af-ae58-983f538341e3.png?etag=5625592a75af00222c18fd19bba35e77)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c1f4c362-44a3-468b-b58d-7f4d0ee006b9-annotated_c8be23c8-4a41-41af-ae58-983f538341e3.png?etag=5625592a75af00222c18fd19bba35e77)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2390x1216
**[Open #225 in Usersnap](https://app.usersnap.com/l/feedback/f893401e-9a4d-473c-bf0d-ffc19a41e115?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@traumschule we're adding #2294, would that solve the problem? Thinking _adding a shortcut_ for "yesterday" and "last 3 days" instead of past 6 months and year may also be worth it? lmk

**Comment by traumschule** [comment]
That'll help. The page is mostly empty and could show deciding on top and 10+ latest approved below (newest first).

**Comment by dmtrjsg** [comment]
@traumschule handled by "past proposals" tab, so since the functionality is present / goal is achievable closing this one for now. 

May be addressed as part of broader optimisation.

**Comment by traumschule** [comment]
>  handled by "past proposals" tab, so since the functionality is present / goal is achievable closing this one for now.
goal is not achieved yet:
- `Past` still shows proposals 1..60
- takes three more clicks to see `Last Week`
- but also `Last Week` filter misses some proposals that were approved latest
- to see proposals approved this term one has to set dates in the calendar manually
- as consul i need to see all proposals relevant for this term (currently deciding on top and approved below)

> adding a shortcut for "yesterday" and "last 3 days" instead of past 6 months and year may also be worth it?

A shortcut for `This term` would do it.
