### ISSUE TITLE
Past Proposals: Remember last search

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2915]
## Scope

- [ ] Create a layer on top of all filtered lists
- [ ] Store latest filter settings in session cookies

Lists affected
- [ ] Past proposals
- [ ] Bounties (all tabs)

## Technical guidance
Use session storage to store the state of the filters

⚠️ BETTER SUITED FOR MORE EXPERIENCED PIONEER DEVELOPER

## Context

**Taken at**: https://dao.joystream.org/#/proposals/past
**Fields**:
- Houston, we have a problem.: Past Proposals: Remember last search
- Comment: STR: Spend some time to adjust your filters, apply, select a proposal, go back - result: search is forgotten and you have to start over.

Intended behavior:
- Automatically restore last search parameters
- remember latest search in browser store
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/40cbb446-2b60-4b47-a408-ba15ca369332-annotated_785b1a11-486c-4c00-b8bd-f2ae0d85e737.png?etag=51376648257343b33a0bad289175ae4e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/40cbb446-2b60-4b47-a408-ba15ca369332-annotated_785b1a11-486c-4c00-b8bd-f2ae0d85e737.png?etag=51376648257343b33a0bad289175ae4e)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2390x1216
**[Open #226 in Usersnap](https://app.usersnap.com/l/feedback/d5ba0ad3-1ead-4e6c-bfcf-890384e2e05c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Why was this closed without comment?

**Comment by dmtrjsg** [comment]
@traumschule hey my bad, we wanted to address this on a broader level and point this issue to it, but pickup this one up and repurposing for that matter  😎

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/past
wss://54.163.55.37.nip.io/ws-rpc

https://user-images.githubusercontent.com/46903215/202440620-4396e571-a3eb-4b0f-82a9-a6c3d8265d1e.mov

<img width="1440" alt="Снимок экрана 2022-11-17 в 13 54 51" src="https://user-images.githubusercontent.com/46903215/202440636-89d01e65-3b2c-47bc-a5ea-a818c58be346.png">
