### ISSUE TITLE
Proposal Loading Time fix

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2919]
About this particular **long loading time on the proposal page** it turns out to be due to a particularly slow chain query in the useHasMemberVotedOnProposal hook, which is send for each current proposal and end up overloading the chain connection completely. It happens on the proposal page when a member is picked. In addition reloading the page doesn't cancel the queries properly which causes long Connecting to Joystream node after it.

**Comment by ivanturlakov** [comment]
Verified on staging.

The process of creating the proposal went smoothly.
After selecting an account, there is a slight delay before the next step button becomes active.

https://user-images.githubusercontent.com/46903215/167621509-d4509db0-cf79-449c-903c-71bcc208b0de.mov
