### ISSUE TITLE
Wrong tooltip in AVG STAKE

### ISSUE THREAD

**Issue by singulart** [Joystream/pioneer#2929]
## Scope

- [ ] Update tooltip link and copy

"Average stake size by members undertaking the roles of workers and the lead in this group. [external link icon]" 

links to https://joystream.gitbook.io/testnet-workspace/system/working-groups?q=lock#staking

<img width="199" alt="Screenshot 2022-10-07 at 17 41 56" src="https://user-images.githubusercontent.com/93924525/194568250-48f2530e-31d0-4ae6-9693-b3c0724fc2a0.png">

## Context

Where the bug was found: https://dao.joystream.org/#/working-groups/builders

Actual result:
The tooltip seen in `AVG STAKE` reads: "If funds are insufficient over payout periods, the working group can incur a debt, which is owed to workers." - this is not relevant information. Apparently this was simply copy-pasted from  `WORKING GROUP DEBT` tooltip. 

Expected result: the tooltip should present the explanation about the "Average Stake". 

<img width="442" alt="Screenshot 2022-04-27 at 17 09 43" src="https://user-images.githubusercontent.com/7863785/165538192-40cefac9-823b-4d9c-87db-66a3e2394994.png">

**Comment by polikosi** [comment]
tested on https://dao-git-fork-gyroflaw-fix-avg-stake-tooltips-joystream.vercel.app/#/working-groups/membership

![image](https://user-images.githubusercontent.com/80429191/199027453-7f90b079-10a3-4a85-af57-554b61e84a9d.png)

https://joystream.gitbook.io/testnet-workspace/system/working-groups?q=lock#staking
this link goes to this page
![image](https://user-images.githubusercontent.com/80429191/199027815-18a4aa7e-6fe7-4251-ab40-613b8e0ce598.png)

@dmtrjsg 
maybe need to update the link?

**Comment by dmtrjsg** [comment]
@gyroflaw pls kindly upd the link to : https://joystream.gitbook.io/testnet-workspace/system/working-groups#staking

**Comment by gyroflaw** [comment]
Ok, I will fix it

**Comment by polikosi** [comment]
nice, works as expected
link: https://joystream.gitbook.io/testnet-workspace/system/working-groups#staking
![image](https://user-images.githubusercontent.com/80429191/202410436-d57c24be-f6db-45b7-9a24-5921b8391c00.png)
