### ISSUE TITLE
Remove the empty space when no Upcoming openings

### ISSUE THREAD

**Issue by singulart** [Joystream/pioneer#2930]
Suggesting to collapse or even completely remove the empty area in Upcoming Openings, if there isn't any.. It creates a visual void in the middle of the screen ;) 

<img width="920" alt="Screenshot 2022-04-27 at 17 15 02" src="https://user-images.githubusercontent.com/7863785/165539229-fa307e54-2310-46fd-b5a1-961342a46282.png">

**Comment by dmtrjsg** [comment]
resolved in #2705
