### ISSUE TITLE
Missing counters in "Past elections results"

### ISSUE THREAD

**Issue by singulart** [Joystream/pioneer#2933]
Scope:

- Display past election counts for all candidates

______

Steps to reproduce:  During the Election stage, open candidates' view. 
Actual result: Observe `0` for all "Past elections results" blocks.
**Expected Result:** data from past elections should be displayed.

<img width="866" alt="Screenshot 2022-04-28 at 12 35 06" src="https://user-images.githubusercontent.com/7863785/165724858-624ab8b5-c252-4121-be3d-c34d7149aa58.png">

**Comment by ivanturlakov** [comment]
Tested on staging

Past election results are displayed for all candidates
<img width="1440" alt="Снимок экрана 2022-06-08 в 18 54 48" src="https://user-images.githubusercontent.com/46903215/172663336-040f3642-2242-4cb0-946c-8f443db9ee77.png">
<img width="1440" alt="Снимок экрана 2022-06-08 в 18 55 50" src="https://user-images.githubusercontent.com/46903215/172663347-5693328a-450a-48c2-9239-6c1f9e429231.png">
