### ISSUE TITLE
SIMPLE Image safety

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2936]
@ Design

For all places where images are shown:

* [ ] Add a "report" or similar sort of button which does not do anything on-chain, but simply allows user to send a ping.
(council candidates/ bounties/ forum posts)
* [ ] Same for all places where markdown preview
* [ ]  :new: Blacklisted images are shown as default placeholder + label "Image moderated".
___

@ Dev

* [ ] Markdown preview can host this component for text inputs
* [ ] On hover all components that have image in it will show "report" button
* [ ] On click the link to the image is sent to an API endpoint 
* [ ] API endpoint is configurable
* [ ] This asset link is also added to a config file, which acts like a blacklist, and this content is excluded. 

:warning: Tech implementation of where to capture:

* [ ] Api request to configurable form

:warning: Tech implementation of images curation/ enforce the decision to put image down:

* [ ] blacklist of images in config on app build

Implement for places:

* [ ] candidacy banner
* [ ] any images
* [ ] markup preview everywhere
* [ ] for member avatar images put a flag to report on the member details (drawer)

Context:

* https://github.com/Joystream/joystream/issues/3685

>Allow app host to maintain a separate resource blacklist (URLs & data objects), which ideally can be updated by operator without taking app offline.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203124163511812) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Alright, @dmtrjsg, designs for this are ready to be reviewed. :)

https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10844%3A416233

Hopefully, it goes without saying that although the flow of reporting an image has been visualized based on a forum thread, the presence of the report button, its alignment, tooltip, and interactions should be the same wherever there's an image that users can report.

**Comment by dmtrjsg** [comment]
@toiletgranny just added a condition to show a fallback image for Moderated Images especially in the markdown

This is how moderated forum posts look like:
- https://github.com/Joystream/pioneer/issues/3165 (figma link there)

**Comment by toiletgranny** [comment]
Assuming that, unlike with moderated posts, we do not want to let others see the original image, and that the moderator can provide rationale behind removing an image, here's the design for this: https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10852%3A550596

**Comment by thesan** [comment]
Image blacklisting workflow:
1. User click the report button -> the image is posted to e.g an Airtable base containing reported urls
2. An admin check the reported images and decide which one to move to the blacklisted table
3. The admin re-trigger pioneer deployment
4. If a `BLACKLIST_ENDPOINT` env is set and returns a list of urls (a JSON in the case of Airtable), these new urls are now available on this new Pioneer build.

**Comment by bedeho** [comment]
This looks fine, except that it should not _require_ the Pioneer operator to use AirTable, they should be able to capture the information however they want, so the easiest would literally be to just allow operator to specify some arbitrary URL where user is sent via a new window, and that window can be whatever the operator wants (google form, airtable form, retool form connected with Airtable, IRC channel, wahtever). IF content is bad enough that people want to report, this experience will suffice.

**Comment by dmtrjsg** [comment]
Agreed to start with Discord and Airtable support and see how POST params would need to be extended to be move universal (support google spreadsheets etc).

**Comment by dmtrjsg** [comment]
@thesan pls add the comments on how to set up / test the endpoint on where the report goes.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app
wss://54.172.154.45.nip.io/ws-rpc

### Candidacy profile preview
<img width="531" alt="Снимок экрана 2022-09-23 в 16 04 20" src="https://user-images.githubusercontent.com/46903215/192010908-7c81d52a-e959-43b3-83ca-be6d01f5f041.png">

### Candidacy profile > Report
<img width="537" alt="Снимок экрана 2022-09-23 в 16 15 15" src="https://user-images.githubusercontent.com/46903215/192011097-fb7ce519-a030-4dcd-9a1c-8f25d5f59fba.png">

### Report modal > Proceed
<img width="921" alt="Снимок экрана 2022-09-23 в 16 14 50" src="https://user-images.githubusercontent.com/46903215/192011063-a269eee7-3b1c-4c67-aae8-77bd1582d8c0.png">

### Redirect to airtable
<img width="393" alt="Снимок экрана 2022-09-23 в 16 14 30" src="https://user-images.githubusercontent.com/46903215/192011003-23d2b9ae-77ed-4270-a8d6-c31d238acb86.png">

### Forum post preview
<img width="1262" alt="Снимок экрана 2022-09-23 в 17 05 25" src="https://user-images.githubusercontent.com/46903215/192011156-63f64470-df65-4284-9dc0-93188c6b76bd.png">

### Forum post > Report
<img width="1148" alt="Снимок экрана 2022-09-23 в 19 57 22" src="https://user-images.githubusercontent.com/46903215/192013276-d0e64d74-8042-4fb5-868f-57c7ce829ce8.png">

### Report modal > Proceed
<img width="910" alt="Снимок экрана 2022-09-23 в 17 05 53" src="https://user-images.githubusercontent.com/46903215/192011176-4c9cf66c-0a21-46a1-9c14-3af3fe3a3fec.png">

### Redirect to airtable
<img width="393" alt="Снимок экрана 2022-09-23 в 16 14 30" src="https://user-images.githubusercontent.com/46903215/192011003-23d2b9ae-77ed-4270-a8d6-c31d238acb86.png">

### Reported img removed by moderator
<img width="791" alt="Снимок экрана 2022-09-23 в 17 06 27" src="https://user-images.githubusercontent.com/46903215/192011192-c263463c-402d-47aa-867e-d7d8cc465f5f.png">

**Comment by thesan** [comment]
@ivanturlakov thank you.
Both images appeared on the table:
![image](https://user-images.githubusercontent.com/6571453/192019952-805285de-7cc7-480e-acbd-7b4c78bb961c.png)

I approved (i.e blacklisted) them and started the redeployment

**Comment by ivanturlakov** [comment]
@thesan thanks! blacklisted imgs removed

### Forum post
<img width="721" alt="Снимок экрана 2022-09-23 в 20 44 25" src="https://user-images.githubusercontent.com/46903215/192027057-8cdaeec1-8858-466b-bbae-f81f6d855d2f.png">

### Candidate profile
<img width="1146" alt="Снимок экрана 2022-09-23 в 20 43 55" src="https://user-images.githubusercontent.com/46903215/192027297-91d4ad38-5a64-4c82-b296-838c85c999c8.png">
<img width="532" alt="Снимок экрана 2022-09-23 в 20 42 32" src="https://user-images.githubusercontent.com/46903215/192027299-ddd90385-d63d-40f9-b61c-ca073f7bfa00.png">

**Comment by dmtrjsg** [comment]
Ready to be tested on the carthage branch!

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/members


https://user-images.githubusercontent.com/46903215/194710361-dbdbda73-bd4f-4bb3-bdb2-ae47fc4abe91.mov
