### ISSUE TITLE
Placeholder Screens for Accounts and Memberships for New users

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2948]
## Context

If wallet is not authorised, or  accounts are not created/ hidden or connected accounts have no membership for Joystream..

Accounts Page is blank and

Memberships Page has Lorem ipsum outdated message

<img width="1252" alt="Screenshot 2022-08-17 at 18 36 56" src="https://user-images.githubusercontent.com/93924525/185205695-38b021e0-b73e-4d5e-ab58-6830fce68ffd.png">

## Scope
- [ ] hide My profile side nav menu item if Account is not connected with the App
- [ ] Update the lorem ipsum copy on Memberhsip page when none of the connected accounts have associated memberships

"Membership is required for participation in the DAO activities and beneficial for accumulating the stats and reputation within the community."

#### Originating Ticket:
______________
- - -
**Taken at**: https://dao.joystream.org/#/profile/memberships
**Fields**:

* Houston, we have a problem.: Loading....
* Comment: There are many parts of the app that jus Load.... forever if you go to it the first time, without an extension or anything setup.
* Feedback: bedeho

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/574f7f5a-bd07-4c5d-b01c-4b24af22c34e-annotated_df45a6bd-8670-41e7-9919-9c33e6fe7e2c.png?etag=2b5c367202eeea2276b693cf48e38246)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/574f7f5a-bd07-4c5d-b01c-4b24af22c34e-annotated_df45a6bd-8670-41e7-9919-9c33e6fe7e2c.png?etag=2b5c367202eeea2276b693cf48e38246)_

**Browser**: Chrome 100 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1518x948
**[Open #231 in Usersnap](https://app.usersnap.com/l/feedback/d6ca21dd-b552-41bd-b0ad-b3e5d947e2f4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202555711975362) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
So I figured out what this was. I apparently did have an extension installed that worked, called Talisman, but it opened on one of my other screens behind other windows, which in honesty also happens to the normal signer, and so I just did not know what was going on. In Atlas we have something  bit more sophisticated to at least alert the user that we did not interact with the installed extension in a timely manner, that could have solved this, as it would have reminded me of what was going on.

![Screenshot 2022-04-30 at 12 26 23](https://user-images.githubusercontent.com/437292/166101818-94513424-b487-43e8-b460-f290c3cb5d0a.png)

**Comment by bedeho** [comment]
A better solution in both products would be to actually have a specific state just for this particular stage of the interaction, which shows some nice dialog reminding the user of what is now going on. Can also be useful even if the above was not a problem.

**Comment by bedeho** [comment]
On Atlas I get this _after_ the interaction worked, but that's too late

![Screenshot 2022-04-30 at 12 28 35](https://user-images.githubusercontent.com/437292/166101880-a999e8b9-2852-4102-9162-179238b85dcc.png)
.

**Comment by dmtrjsg** [comment]
Checked after wrapping polkadot into webworker, only accounts page is loading, but the ticket is still valid, with the need of prompting users to check extension dialogue window, that may be shown outside of the browser window. 
 
<img width="1280" alt="Screenshot 2022-07-05 at 18 06 53" src="https://user-images.githubusercontent.com/93924525/177380446-6fe53222-2245-4db7-b8fa-52ae8aa2f994.png">

**Comment by dmtrjsg** [comment]
Re Extension waiting in the other screen, this is covered in Pioneer already:
<img width="556" alt="Screenshot 2022-08-17 at 18 44 50" src="https://user-images.githubusercontent.com/93924525/185207241-f92b534f-971e-418f-9e60-31f3ccbf44c1.png">

**Comment by toiletgranny** [comment]
@dmtrjsg A few clarifying questions irt the scope:

1. A common pattern is hiding parts of the app that require the user to be signed in. In this case, it would translate to hiding the "My Profile" for users that haven't connected their wallets. The implementation effort is substantially lower. Would you be interested in doing that instead? 
2. > Add placeholder messages to Membership and Accounts Tabs with CTAs which would be compatible with Wallet selection / account creation/ membership purchase flow
    - Not sure I understand what does compatibility with wallet selection / account creation mean in this context in the context of this placeholder message.
    - Where can I go through the "membership purchase flow" in the app? I couldn't find it anywhere in Figma.

**Comment by dmtrjsg** [comment]
@toiletgranny 

1. For this one, yeah could do, but would not this be less motivating to actually create membership?
2. you can create new wallet and try it on dao.joystream.org

**Comment by toiletgranny** [comment]
Having discussed it with @dmtrjsg and @kdembler earlier today, we agreed to proceed with hiding the tab.

**Comment by dmtrjsg** [comment]
@toiletgranny 

When the app is loading and signer is connecting we cannot really tell if there is a membership or not, so it will be jumpy with each refresh an on first load. Perhaps we could have another go at this ticket?

cc @kdembler

**Comment by toiletgranny** [comment]
@dmtrjsg Oh, that's a spot-on observation. Frankly speaking, I feel a bit embarrassed for not realizing it earlier. I'll punish myself later.

Anyway, I think the ultimate solution for this would be not keeping any dynamic links so high-up in the side nav, and, for example, moving the "My Profile" page link to the bottom section, which is already all about your active profile/membership. This would, however, take a bit more time to explore and implement, so I figured that going with the placeholder makes the most sense for now.

And so, here's the design for this. I based it on the recently implemented placeholder screen for the Bounty page, to ensure consistency. I imagine the contents of the placeholder for the My Profile page remain the same across all tabs at the top.

https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10951%3A432394

**Comment by dmtrjsg** [comment]
@toiletgranny 

All g buddy, it was all three of us on the call and we all blanked on it, which is totally fine, assuming the volume of issues we are churning through 👌 😉 


So just to re-iterate we have four states:
1. Account not connected
2. Connected but no active membership exists
3. Membership exists but you logged out of it (can re-use the same copy as on 2)
4. Logged in with membership (nothing to do here)

For accounts tab we only need 1 and 2; 
For memberships tab we only need to cover 2 and 3.

**Comment by dmtrjsg** [comment]
Link to figma> https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10962%3A433202

**Comment by polikosi** [comment]
⚠️the "My Profile" tab is not hidden in any case
tested here - wss://3.92.226.32.nip.io/ws-rpc


**1. Wallet not connected**
Pages:

- My accounts
![image](https://user-images.githubusercontent.com/80429191/193552613-ec8b87cf-1881-42b2-ae5f-65d65e358fdb.png)

- My meberships
![image](https://user-images.githubusercontent.com/80429191/193552659-d9d20de0-62c7-4b68-a539-9e7a0019dfbb.png)

**2. Wallet coneected without active meberships**

- My accounts
![image](https://user-images.githubusercontent.com/80429191/193553091-f38d0ff3-fc7c-4d6a-9a3e-c9dd85310ced.png)

- My meberships
![image](https://user-images.githubusercontent.com/80429191/193553125-83a8a534-3676-4d22-8761-421f5b69c2d8.png)

**3. Membership exists but logged out of it**

- My accounts
![image](https://user-images.githubusercontent.com/80429191/193553462-d239aa0e-c7eb-4b96-8a40-3c2119144909.png)

- My meberships
![image](https://user-images.githubusercontent.com/80429191/193553498-7a81d1fa-e273-4c5f-af66-90891d5211a0.png)

**4. Logged in with membership**

- My accounts
![image](https://user-images.githubusercontent.com/80429191/193553847-12a328b9-fda8-4f38-8c81-da3c500e4295.png)

- My meberships
![image](https://user-images.githubusercontent.com/80429191/193553882-16b1febc-dd67-4750-b643-bc12971c77c7.png)
