### ISSUE TITLE
QN issue: created bounties do not get displayed in pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2965]
![Screenshot 2022-05-04 at 12.02.24.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/fbeefaa1-8faa-491f-93bb-80f17ec5963e)

ℹ️  **TXID:**

https://polkadot.js.org/apps/?rpc=wss://18.207.235.254.nip.io/ws-rpc#/explorer/query/0x2e67651a382f449bff5fb2b1d213397c87dd86320fdf538cf86ab510a3491c82

**Comment by polikosi** [comment]
https://polkadot.js.org/apps/?rpc=wss://18.207.235.254.nip.io/ws-rpc#/explorer/query/0x2e67651a382f449bff5fb2b1d213397c87dd86320fdf538cf86ab510a3491c82

the transaction is successful, but the bounty is not displayed

**Comment by dmtrjsg** [comment]
Cannot reproduce any longer after network update. Closing for the time being :)
