### ISSUE TITLE
Copy for Notifications snack bar: 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2970]
Pls see original linked ticket for context. we just need a way to show/ wrap long text in notiff snack bars.

" Opening {{name}} is accepting applications. Apply now."⚠️  Please prepare an example for cases, when working group name is very long 55 characters) @MattAugustynowicz

**Comment by MattAugustynowicz** [comment]
For longer opening names with up to 55 characters, please show the whole phrase. This is not a common case, plus we already have cases of notifications that take up even more space than this one 

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/5eec013a-511a-49df-a4f6-ecbc3694b6c5)
