### ISSUE TITLE
UX bug sending a application to the bounty

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#2976]
![image](https://user-images.githubusercontent.com/84832436/166938255-75ae21df-ebde-45f5-98d8-aa551b98fa5f.png)
After clicking on the "Announce Entry" button, the page opens with the wrong size.
To see the right button (Announce Work Entry), you must zoom out of the page.
We need to resize (scale) this page (window)

**Comment by dmtrjsg** [comment]
@adovrodion what's your screen dimensions and zoom level (100%?) when you are experiencing these issues? 

Any other modals that were troublesome? Would be good to address them all in a single go..
