### ISSUE TITLE
Back button on openings/# leads to nothing if referrer is empty

### ISSUE THREAD

**Issue by eikebartels** [Joystream/pioneer#2977]
To reproduce: 

Open new tab and open https://dao.joystream.org/#/working-groups/openings/operationsWorkingGroupAlpha-9 
press the back button 
![image](https://user-images.githubusercontent.com/767979/166952236-436797d4-821d-4871-92bd-affc2877e4e0.png)

Expected behaviour:
👉 ✅ Option 2: Button leads to list page https://dao.joystream.org/#/working-groups/openings 

Actually behaviour: 
Button leads to empty tab page

**Comment by traumschule** [comment]
use solution suggested in #3768

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-staging-joystream.vercel.app/#/working-groups/openings
wss://34.230.5.182.nip.io/ws-rpc

Works as expected

https://user-images.githubusercontent.com/46903215/210771130-e192852a-eddc-4f3a-8e85-16dc20631c08.mov
