### ISSUE TITLE
Idea: Generalise wallet/signer 

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2978]
Same as this: https://github.com/Joystream/atlas/issues/1971

**Comment by bedeho** [comment]
That is probably a good idea, wallet support should be rolled out in both apps at the same time, as a user may create a membership in one app and want to use it in the other.

**Comment by dmtrjsg** [comment]
Going with [Talisman Implementation](https://github.com/Joystream/pioneer/issues/3212) first
