### ISSUE TITLE
`My votes` shows wrong numbers for `My Stake`

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#2985]
## Scope:

- [ ] Display stake that was added by voting via logged in member in my votes

NB: "My Stake" that was candidate stake[ is addressed here> ](https://github.com/Joystream/pioneer/issues/2795)

## Details

https://dao.joystream.org/#/election -> My Votes

`My Stake` shows the candidate's own stake. As voter i am only interested how much i voted.

**Comment by polikosi** [comment]
tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://44.201.112.198.nip.io/network/config.json

![image](https://user-images.githubusercontent.com/80429191/199518754-a2bd4c4d-c717-43d7-a25e-7908f77f89a2.png)


I staked from this acc (candidate8) 1k tjoy but it shows 10k tjoy
![image](https://user-images.githubusercontent.com/80429191/199519758-afbf0098-de89-41c9-ac12-14420f1313b8.png)

I staked from this acc (candidate9) 10k tjoy and it shows  10k tjoy
![image](https://user-images.githubusercontent.com/80429191/199519083-81e83201-9723-4f67-8a76-d7b57ce820f7.png)

**Comment by polikosi** [comment]
tested on: https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

"My votes" shows correct numbers for "My Stake"
![image](https://user-images.githubusercontent.com/80429191/204287646-cd1a75fe-fa4b-4137-baf3-9804bb73ee7c.png)
