### ISSUE TITLE
[USERSNAP] can't recover stake

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2988]
**Taken at**: https://dao.joystream.org/#/profile
**Fields**:
- Houston, we have a problem.: can&#39;t recover stake
- Comment: clicking the Recover button under the accounts in my profile should move my recoverable balance back into my account
- Feedback: Eclipsingbinary#7338

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/69b7a1d2-2792-4d25-b659-fb55027a9431-annotated_089934a8-8bc9-430e-aebe-a2ae01623724.png?etag=d1ad2cf02f9d02d73dc7f24431a4ce86)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/69b7a1d2-2792-4d25-b659-fb55027a9431-annotated_089934a8-8bc9-430e-aebe-a2ae01623724.png?etag=d1ad2cf02f9d02d73dc7f24431a4ce86)*

**Browser**: Chrome 101 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x937
**[Open #241 in Usersnap](https://app.usersnap.com/l/feedback/440ea461-f4e4-4510-9226-07c2541d073e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
Some additional info:
- I tried this and also had the same problem, most of the time the section would just collapse and sometimes it wouldn't but it still wouldn't bring up any prompt
- There were no errors in the browser console

**Comment by dmtrjsg** [comment]
We've done the overhaul of entire stake recovery, so this issue is now outdated. Closing.

**Comment by dmtrjsg** [comment]
For reference: #2300
