### ISSUE TITLE
Countdown in the Bounty

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#2993]
Can you make a countdown for each bounty, like in the Council section? That would be more convenient than what we have now. I'm sure that without such a countdown we'll have bounties with no submissions.
In the first screenshot the time of the bounty is coming to an end, but it still shows 3 days 
![image](https://user-images.githubusercontent.com/84832436/167300638-f098b56f-011c-4b02-bbbb-5afa81435426.png)
![image](https://user-images.githubusercontent.com/84832436/167300645-b1eae5e4-10dd-487d-a9ce-004a06f0bcd5.png)
I believe we need it.

**Comment by adovrodion** [comment]
@dmtrjsg Thank you! I think this has already been done.

**Comment by dmtrjsg** [comment]
Nice1 @adovrodion
