### ISSUE TITLE
Closed Bounties -  whitelisted members cannot announce work entry (and other actions)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2997]
ER: Whitelisted (Closed) bounty accepts contributions, work entries announcement and submitting work for whiltelisted members:

AR: Whitelisted memebers cannot announce entry

![Screenshot 2022-05-09 at 10.46.07.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/8089c9e6-e85a-45d6-af0a-2ff740e4561f)

**Comment by dmtrjsg** [comment]
@RafalPloszka can you pls JUST CHECK (not do the task) if this has similar issue with QN mappings as one with proposals

**Comment by RafalPloszka** [comment]
> @RafalPloszka can you pls JUST CHECK (not do the task) if this has similar issue with QN mappings as one with proposals

@dmtrjsg this is a different problem. In https://github.com/Joystream/pioneer/issues/2481 whitelist wasn't returned at all (`null` instead). Here it's available, retrieved properly, a whitelisted member can (I mean clickable button + no validation error) announce entry, but the error occurs during the transaction.

**Comment by polikosi** [comment]
verified on staging. Tets evidence below:

https://user-images.githubusercontent.com/80429191/172434915-6e657a2c-0d46-4dc4-bf38-91ebb74f5086.mp4
