### ISSUE TITLE
Display role details

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#300]
@[figma](https://www.figma.com/file/QSpueQlOQKGbiHig2harPy/Working-groups?node-id=1080%3A4838716)

Display role details:
- display role accounts, dashboard info 
- display role activities
- display role actions: see application, view opening, leave a postion

**Comment by jodator** [comment]
The updated design is here: [https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=1740%3A92222.](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=1740%3A92222.)

This view might be tricky, so a little heads up:

1.  The account role should be probably very close to that displayed in the "My Accounts" view. There are hooks to display balances (at least total :shrug: as we didn't implement "locked", etc AFAIR).
2.  There are button links to:
    1.  Application (id should be fetched from the query node) -> you'll need to open an application preview modal
    2.  Opening (the same -> from the query node) -> use react-router to open the opening
    3.  Other buttons can be without action for now
3.  The badges are: group name | lead / regular (`isLead`) | worker id ;)

The dashboard can be stubbed for now with static stubs.

The role activities should display a stub as in other components.

**Comment by jodator** [comment]
@DevNikita16 For the issue to be closed we still need:

1.  Better Application link with the Worker (ideally the worker should be generated together with the application). But that's a minor issue and can be skipped if work on that would consume much time.
2.  Buttons on the page should be:
    1.  Change Role account (:white\_check\_mark:)
    2.  A button to move funds (This can be removed and implemented together with #305 - so only remove the button for now)
    3.  Change reward account (:white\_check\_mark: )
3.  The dashboard is missing proper values (ie next payout in...)
4.  Different role states:
    1.  [unstaking](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=1753%3A10723) (display that the account is in unstaking phase
    2.  [ended role](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=1753%3A13189) (different badges, info that a role has ended) no leave role button 
    3.  [slashed role](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=1753%3A11599) (we might need to check how to assert this state)

**Comment by DevNikita16** [comment]
@jodator Do we already have possibility to handle unstaking phase?

**Comment by jodator** [comment]
> @jodator Do we already have possibility to handle unstaking phase?

I'm researching this ATM. For now, let's focus on other things.

**Comment by jodator** [comment]
Let's close this one - there are still some things missing. However, in other components as well. I'll gather them all in a separate issue.
