### ISSUE TITLE
Allow to easilly update the currency symbol

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3004]
Follow up to #2789

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631393738373465313931333731316266316636616433312f38363530646366632d626665342d346237362d386661352d346236393037316532343931](https://user-images.githubusercontent.com/6571453/167462146-4316311e-5616-42e7-b765-6ab61a5a881b.png)

**Comment by dmtrjsg** [comment]
Superseded by #2531
