### ISSUE TITLE
Display activity details

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#301]
@[figma](https://www.figma.com/file/QSpueQlOQKGbiHig2harPy/Working-groups?node-id=1636%3A2158308)

Display activity detail

**Comment by jodator** [comment]
Comments on which activity to handle:

*   https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=1405%3A69471

**Comment by p-sad** [comment]
Designs distinguish between budget increase and decrease, but that can't be discerned from a single event.
It is possible to infer it from a collection of past events, but not sure how to implement it for activities in an efficient matter.

**Comment by p-sad** [comment]
* Approach I took so far (events 1:1 activities) may actually be insufficient, seeing that a `StatusTextChangedEvent` can contain both a Status Changed activity _and_ zero or more Upcoming Openings.
* The design of "Reward amount changed" activities is vague and I'm wondering if it's on purpose, considering that the event specifies the monthly reward of a specific worker of a specific group, meaning that the generic design doesn't communicate any useful information — unless it will only be seen in Role preview (of a specific role)

Other than "Reward amount changed" and "Upcoming Opening", the Working Group activities are pretty much laid out
