### ISSUE TITLE
AnnounceCandidacy validation refactor

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/pioneer#3017]
Refactor the `AnnounceCandidacy` modal as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by singulart** [comment]
missing description

**Comment by polikosi** [comment]
Verified on staging. 

Announce candinancy. 
![Screenshot_33](https://user-images.githubusercontent.com/80429191/170512607-8b09c99b-db75-4c7e-a3ed-b647038d0464.png)

Candidate profile
![Screenshot_34](https://user-images.githubusercontent.com/80429191/170512897-f1840ba3-514a-416d-982b-0885037b6db8.png)

Candidate summary
![Screenshot_35](https://user-images.githubusercontent.com/80429191/170513389-b8dc416f-73e4-464b-882c-318161adc852.png)

Finish
![Screenshot_36](https://user-images.githubusercontent.com/80429191/170513478-9a782f36-6e51-4d5e-a1c1-bb67ae89ce44.png)
![Screenshot_37](https://user-images.githubusercontent.com/80429191/170513616-dab2cf4f-5e02-47c1-9bdf-80c33ecf3a42.png)
![Screenshot_38](https://user-images.githubusercontent.com/80429191/170514258-1b4834ed-1e10-493f-9096-70c22a87a0df.png)

TX
https://polkadot.js.org/apps/?rpc=wss://3.235.196.1.nip.io/ws-rpc#/explorer/query/0xcebee4116b7930214b818d021416978a4ab8f4c98f72df5210f3376f25cda30d
