### ISSUE TITLE
VoteForCouncilModal validation refactor

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#3019]
Refactor the `VoteForCouncilModal` modal as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by singulart** [comment]
missing description

**Comment by ivanturlakov** [comment]
Tested on staging.

The fields are validated correctly

https://user-images.githubusercontent.com/46903215/170729920-260e6edd-63ff-4e50-84f9-48d5dcfcf5ec.mov

The transaction gets sent with the parameter set in the modal
<img width="1440" alt="Снимок экрана 2022-05-27 в 18 06 16" src="https://user-images.githubusercontent.com/46903215/170730191-3135429f-1152-4511-a661-f231b2d4d49f.png">

Here I entered a value that exceeds my balance, the transaction will result in an insufficient balance error. It will be good to tell the user about it in the first step.

https://user-images.githubusercontent.com/46903215/170731899-466dec37-fa93-4cd7-9317-17d359b24e8a.mov

**Comment by singulart** [comment]
@ivanturlakov I am marking this as success. Please create a separate ticket with your finding about balance validation. Thanks!

**Comment by dmtrjsg** [comment]
@singulart thank you for your steering 🙏 , cannot agree more on the approach to try and remain within the scope of Acceptance criteria and raise tangential/ related issues as separate bugs 🐞
