### ISSUE TITLE
Council announcement wording

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3021]
Issue for #2699

> Technically `have been` is only correct [while](http://www.differencebetween.net/language/difference-between-were-and-have-been/) they are elected - it is likely the notification will disappear until next election finished,
> 
> If you like we could drop it altogether (`5 councilors elected to the council` or `New council elected`).

**Comment by ivanturlakov** [comment]
Verified on staging.
**Corrected to "New council elected."**
<img width="1213" alt="Снимок экрана 2022-05-16 в 12 05 35" src="https://user-images.githubusercontent.com/46903215/168558846-8931f865-f1bc-4893-bbe3-5b073003b897.png">
