### ISSUE TITLE
Tooltip: Handle vs Name improvements

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#3024]
## Scope

Add tooltips to create membership flow and new member flow. 

- [ ] Handle
This is your username that will be displayed in most of the places where you perform actions that others see, such as forum posts, present yourself as council candidate or create a new proposal. Think of it as a public name. Handles are unique.

- [ ] Name
Name: This is your name, which is separate to your handle. It will only be displayed on the membership details pages. SomeDAO participants choose to use their real names, while others choose to use their nicknames. Name does not have to be unique.

## Context
This language seems to be causing a lot of questions from the community, it would be good to have them include an example explaining the difference.

**Comment by dmtrjsg** [comment]
Noted!

Will take care of this together with all other tooltips. The best place for this is Creation of Membership modal and displaying member details.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/settings
wss://34.230.5.182.nip.io/ws-rpc

<img width="1148" alt="Снимок экрана 2022-12-02 в 12 46 51" src="https://user-images.githubusercontent.com/46903215/205276035-9d1307c9-12e3-4d97-9d03-2e1dbef3fae7.png">
<img width="1145" alt="Снимок экрана 2022-12-02 в 12 46 24" src="https://user-images.githubusercontent.com/46903215/205276039-15bb8412-9960-4742-b502-ec26fb3f73fe.png">
