### ISSUE TITLE
Incorrect window size - Bounty > Contribute

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#3025]
## Scope
- [ ] Change the styling on the modal to support good centering and sizing

___

![image](https://user-images.githubusercontent.com/84832436/168036624-565c284e-08cd-4717-b2ff-7c4ca17df345.png)
I open the Bounty page and click "Contribute"
An incorrectly sized window opens. The "Contribute" button in the new window appears cropped.

<img width="1004" alt="Screenshot 2022-06-08 at 16 39 45" src="https://user-images.githubusercontent.com/93924525/172585531-83a0ff2f-40f9-4f1f-8c50-a64ce3de51a9.png">

**Comment by freakstatic** [comment]
@singulart please assign

**Comment by ivanturlakov** [comment]
Tested on staging

Screenshots were taken on MacBook 13"

Perhaps the good solution for window positioning was implemented on Add New Proposal window and could be used here too.

<img width="1438" alt="Снимок экрана 2022-06-21 в 13 02 19" src="https://user-images.githubusercontent.com/46903215/174774506-454d9cb2-cb34-4e1d-9125-04e5038c02b7.png">
<img width="1440" alt="Снимок экрана 2022-06-21 в 13 04 34" src="https://user-images.githubusercontent.com/46903215/174774533-c113eed9-a4b6-463d-99a3-ede1df26d3f1.png">
<img width="1440" alt="Снимок экрана 2022-06-21 в 13 05 21" src="https://user-images.githubusercontent.com/46903215/174774539-2ffc2e22-04a7-41bd-b2bc-16f15411cfa6.png">

**Comment by ivanturlakov** [comment]
Retested on https://pioneer-2.vercel.app/

<img width="1440" alt="Снимок экрана 2022-06-23 в 12 10 28" src="https://user-images.githubusercontent.com/46903215/175263354-eb5ac8e5-ace0-4792-844d-a40fc5521f75.png">

**Comment by ivanturlakov** [comment]
Tested on staging

<img width="1440" alt="Снимок экрана 2022-07-12 в 16 23 49" src="https://user-images.githubusercontent.com/46903215/178500371-e277ca5e-cdd5-4649-9bd9-84a67143ea46.png">
