### ISSUE TITLE
[USERSNAP] Update election view when stage changes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3038]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Update election view when stage changes
- Comment: After announcing period ended the timer jumps to `remaining length: 1d : 2 min` but stage is still `Announcing` and no vote button.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7b0f3a23-dc10-46dc-ba71-034c3bff7525-annotated_0e1d89cb-2df0-447e-ba08-6049c692cec4.png?etag=e2696a80f62ca38dccf9a3750d89e014)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7b0f3a23-dc10-46dc-ba71-034c3bff7525-annotated_0e1d89cb-2df0-447e-ba08-6049c692cec4.png?etag=e2696a80f62ca38dccf9a3750d89e014)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1190x1216
**[Open #250 in Usersnap](https://app.usersnap.com/l/feedback/1d5a5cdd-d8ea-4d09-94a9-358291ed6fdb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
Tested on staging.

Election view updating:

Announcing period
<img width="1440" alt="Снимок экрана 2022-06-08 в 17 34 18" src="https://user-images.githubusercontent.com/46903215/172644849-20b64331-88f3-4245-900a-20217cf3452e.png">


Voting period
<img width="1440" alt="Снимок экрана 2022-06-08 в 17 34 38" src="https://user-images.githubusercontent.com/46903215/172644995-53353c38-002f-484a-b1a6-626bab000dc5.png">
