### ISSUE TITLE
Member Accounts : Locks

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3043]
task for acc lock page and eta on release

**Comment by ivanturlakov** [comment]
@dmtrjsg could you add a scope for QA?

**Comment by dmtrjsg** [comment]
@ivanturlakov sure, the underlying info and broader context is covered here: 
- https://github.com/Joystream/pioneer/issues/2300

This specific task shall address displaying the locks info and release time ETA based on block duration of underlying processes:

[Figma Link](urlhttps://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8759%3A393512)

<img width="801" alt="Screenshot 2022-06-13 at 13 45 59" src="https://user-images.githubusercontent.com/93924525/173295231-ba00b306-0d43-493d-be54-470a3bdb0b8a.png">


Suggested scope of QA work is to test the ETA of lock release across all processes. This is a pretty big task.

**Comment by dmtrjsg** [comment]
The locks recovery times are handled in:
- https://github.com/Joystream/pioneer/issues/3109
