### ISSUE TITLE
IncreaseWorkerStake validation refactor

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#3046]
Refactor the `IncreaseWorkerStake` modal as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by singulart** [comment]
missing description

**Comment by polikosi** [comment]
verified on staging.
![Screenshot_30](https://user-images.githubusercontent.com/80429191/170489036-831a83cc-6ae1-47c5-a8a9-e1d13fc497fd.png)
Use CLI 
![Screenshot_32](https://user-images.githubusercontent.com/80429191/170489059-9c701377-de95-4987-80d6-844c946d8614.png)

![Screenshot_31](https://user-images.githubusercontent.com/80429191/170489084-b1e3e4f9-8d73-4d63-9ad4-3669b098acbe.png)

**Comment by polikosi** [comment]
LOCKED BALANCE
![Screenshot_40](https://user-images.githubusercontent.com/80429191/170967461-f44449de-9655-4b9c-9cb6-c528042ea8f7.png)

Minimum stake
![Screenshot_41](https://user-images.githubusercontent.com/80429191/170967603-456b91b8-6048-4255-9a5c-cc4434e8fd43.png)

Slash the worker 
![Screenshot_42](https://user-images.githubusercontent.com/80429191/170967664-1f3a7376-7d9f-45fa-9d61-2203654419b5.png)


https://user-images.githubusercontent.com/80429191/170968516-6525916c-cd50-4f81-96f8-9988dbd78324.mp4

TX 
https://polkadot.js.org/apps/?rpc=wss://3.235.196.1.nip.io/ws-rpc#/explorer/query/0xfce39c8aad67fe949721c520e748594585c2dd9b9d1cea6175a57ced3e65c411
