### ISSUE TITLE
AddNewProposal validation refactor

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#3047]
Refactor the `AddNewProposal` modal as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by ivanturlakov** [comment]
Tested on staging

Staking account validation bug

https://user-images.githubusercontent.com/46903215/172883286-de3e1dcc-2e5b-48cb-854d-0b22f1eeb22c.mov


Trigger field validation behavior

https://user-images.githubusercontent.com/46903215/172884682-5b4570f7-6904-40b9-ad8e-ebabc8323ca5.mov


Perhaps the validation should take into account the current value?
<img width="1440" alt="slash-wg-lead" src="https://user-images.githubusercontent.com/46903215/172885599-695685ac-3e44-409b-978a-bb824f219526.png">
<img width="1440" alt="decrease-wg-lead-stake" src="https://user-images.githubusercontent.com/46903215/172885607-65dd4ed7-f54b-4276-bd69-e90f49ddde57.png">
<img width="1440" alt="update-wg-budget" src="https://user-images.githubusercontent.com/46903215/172885616-7a70a8bd-4977-43e8-a0fc-b41f4207eff8.png">

**Comment by dmtrjsg** [comment]
Prevent from posting number out of range and Add under-copy to the input field "Amount must be greater than 0 and less than current stake."

**Comment by dmtrjsg** [comment]
@ivanturlakov ready to be retested. Fix merged.

**Comment by ivanturlakov** [comment]
Tested on staging

Bugs are fixed 

https://user-images.githubusercontent.com/46903215/174822654-55952e8d-51c2-4147-a444-8ae731229aa0.mov


https://user-images.githubusercontent.com/46903215/174822848-986bae4f-dd18-4b24-802f-452f8fc2251d.mov

<img width="1255" alt="Снимок экрана 2022-06-21 в 17 18 02" src="https://user-images.githubusercontent.com/46903215/174822971-bb5b3093-12fa-4237-90e8-bffa51a93b5b.png">
<img width="1253" alt="Снимок экрана 2022-06-21 в 17 16 12" src="https://user-images.githubusercontent.com/46903215/174822977-66d89a2a-01d4-4433-bb93-b480e2e4fc27.png">
<img width="1262" alt="Снимок экрана 2022-06-21 в 17 15 19" src="https://user-images.githubusercontent.com/46903215/174822981-e4405cb9-b6ef-4145-9dbb-3e16878e5cb5.png">
