### ISSUE TITLE
VoteForProposal validation refactor

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#3048]
Refactor the `VoteForProposal` modal as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by WRadoslaw** [comment]
Good point, handled in #3111. Thanks!

**Comment by singulart** [comment]
Marking this as success. Reported finding to be addressed separately as per the comment above
