### ISSUE TITLE
BuyMembershipModal

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#3050]
Refactor the `BuyMembershipModal` as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by dmtrjsg** [comment]
@singulart was this tested after the latest PR was merged 8 days ago?

**Comment by ivanturlakov** [comment]
Tested on staging


The fields are validated correctly
The transaction gets sent with the parameter set in the modal

Special characters are not allowed


https://user-images.githubusercontent.com/46903215/174829088-baf88657-e6b5-4e66-9d63-a9252f338fa1.mov
