### ISSUE TITLE
UpdateMembership

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#3053]
Refactor the `UpdateMembership` modal as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by WRadoslaw** [comment]
#3067

**Comment by ivanturlakov** [comment]
Tested on staging.

The fields are validated correctly
The transaction gets sent with the parameter set in the modal

Member choosed for editing
<img width="1440" alt="Снимок экрана 2022-05-26 в 14 14 04" src="https://user-images.githubusercontent.com/46903215/170480253-f98c88c1-02d9-4583-be3f-0ee6dd612660.png">

Editing
<img width="956" alt="Снимок экрана 2022-05-26 в 14 15 03" src="https://user-images.githubusercontent.com/46903215/170480314-7d13e2d7-e2ee-4e78-92e3-84b0f00f4c08.png">

Frontend after editing. The fields marked in red were not updated untill page refreshed.
<img width="1440" alt="Снимок экрана 2022-05-26 в 14 20 27" src="https://user-images.githubusercontent.com/46903215/170480355-fd90209d-3b49-4d65-808a-ecb81c98d25a.png">

Transaction details
<img width="1410" alt="Снимок экрана 2022-05-26 в 14 22 01" src="https://user-images.githubusercontent.com/46903215/170480375-4214ca3b-5221-4cd1-b65f-001833a25822.png">
