### ISSUE TITLE
CreateThread

### ISSUE THREAD

**Issue by stepien4soft** [Joystream/pioneer#3054]
Refactor the `CreateThread` modal as part of the #2802 epic.

## Dev scope
- [x] Refactor fields validation
- [x] Manage the form state with React Hook Form instead of XState

## QA scope
- [ ] The fields are validated correctly
- [ ] The transaction gets sent with the parameter set in the modal

**Comment by ivanturlakov** [comment]
Tested on staging.

The fields are validated correctly but allow special characters.
The transaction gets sent with the parameter set in the modal.
<img width="1268" alt="Снимок экрана 2022-06-03 в 16 48 59" src="https://user-images.githubusercontent.com/46903215/171868381-119d397c-e9ab-4ce8-b5ad-9729bc430dc9.png">
<img width="1207" alt="Снимок экрана 2022-06-03 в 16 55 09" src="https://user-images.githubusercontent.com/46903215/171868474-48157e1d-be59-402d-82b9-4408ef69a16c.png">

**Comment by dmtrjsg** [comment]
@ivanturlakov we concluded its acceptable for the forum threads.
