### ISSUE TITLE
Create an opening

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#306]
## Context

As a Working group Lead user must be able to create an opening for workers via GUI and not CLI

## Scope

Create opening:
- [x] Add a button to create opening that is only shown to the WGL to the WG openings page:
<img width="1303" alt="Screenshot 2022-11-01 at 15 06 44" src="https://user-images.githubusercontent.com/93924525/199219845-0edacacf-b319-45da-809b-40ad10738e3e.png">
- [ ] Button starts the flow for new openings which is based on the metaprotocol schema and create opening extrinsic
- [ ] Re-use the design pattern from the WGL opening

View opening:
- [x] Once opening is created, display opening in the openings list
- [x] Opening details page must have the appropriate widgets (analogous to WGL opening)

Apply: 
- [x] Apply to opening similar to how WGL does it

**Comment by traumschule** [comment]
The lead opening proposals are implemented.

Additionally leads need to create worker openings with a similar form but without proposal. So far this is only possible via CLI.
- Add `working-groups/modals/AddOpening` with a form based on the according proposal form.
- option to upload a template json (like `-i` in the CLI)
- option to backup form input
- add / reuse hook to submit transaction with similar UI to sign and to track progress
- any changes needed for activities?

**Comment by traumschule** [comment]
please correct. took this on to give leads easier access, also with regards to the now fixed cli error. def some swag to @mnaamani for the [quick response](https://discord.com/channels/811216481340751934/812343711870091285/1046103098202005514)! https://github.com/Joystream/joystream/pull/4468

**Comment by traumschule** [comment]
I am not working on this and won't anytime soon, sorry.
