### ISSUE TITLE
Create Proposal for Channel Payouts

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3073]
## Context

Details are covered here:
- [ ] https://github.com/Joystream/pioneer/issues/2934

ℹ️ DM: in my head this shall broadly follow [this pattern](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=210%3A13897) for runtime upgrade, with some light touch validation thrown in, without going on an channel-specific level, since number of channels can be very (very-very) large ℹ️ 

### Key Challenges:
☝️ 1️⃣  _If a channel owner was promised e.g. 10 in a given proposal, but did not cash it out, then they could be promised any new value in the next one, say 5, and this would be a permanent loss without recourse. It is in other words at the discretion of the council to properly update what a channel is owed over time if the channel does not cash out. This is largely a moot point in practice, because it is to begin with at the discretion of the council what to pay out in any proposal regardless, at least as a technical matter.

☝️ 2️⃣  A cash-out proposal does not need to address what all channels are owed, it can only cover a subset, or event be empty. For anyone not mentioned, this is equivalent to being owed 0.

☝️  These parameters can also be changed in the proposal. While they can be changed they don't have to. E.g. member can only change one parameter and keep all else unchanged. The Payload is not mandatory for the proposal execution either.

<img width="959" alt="Screenshot 2022-05-18 at 15 29 51" src="https://user-images.githubusercontent.com/93924525/169066550-eee5eafc-9500-4602-8cdf-1a821f8ff821.png">

### User Story: as Pioneer Member I want to create proposal for Channel Payouts

⚠️ **assumption about operations:** Presumably proposal description will be pointing to the related Incentives programme rules and perhaps some sort of an External Tool for incentives scheme scoring inputs so proposal creator will have access to it.  

**Acceptance criteria:**

- [ ] Follows proposals pattern with general and specific parameters. Here, in this issue we only focus on the variation for the specific parameters
- [ ] Accepts JSON as input for the specific parameters
Proposal Specific Params:
ChannelID
Payout
Rationale
- [ ] Validation error on bad file format after uploading (Payout payload cannot be processed. Please check the file format and extension and try again.)
- [ ] ⚠️ importantly: Allows to update the parameters from point 3 in the context section, also r[eferenced here> ](https://github.com/Joystream/joystream/issues/3263)

>The only validation  that is technically feasible and ROI justified would be:
- [ ] Add parameter values

https://github.com/Joystream/joystream/issues/3263

### Out of scope 

- [ ] Hash input
- [ ] Link to tool input

- [ ]  Next date of payout for channel owners convenience. Would be good to entertain an idea of adding the next estimated payout proposal date as metaprotocol input. this would help to set expectations on atlas wrt next payout. This is a nice to have  and a discussion point for the time being
- [ ] Preview of summary: X accounts to be paid; Y accounts are paid 0; Z accounts to be paid 0 even though they did not claim (getting slashed)
channels Paid/ Unpaid/; this time: Y channels
- [ ] Validation error on empty rationale for non-0 payouts
- [ ] Validation on Budget Feasibility? ⚠️  TBC Display current budget of the working group which is responsible for payouts and total payouts as % of that groups budget.

**Comment by dmtrjsg** [comment]
@thesan qq

[Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9707%3A378598)

<img width="706" alt="Screenshot 2022-06-09 at 14 20 02" src="https://user-images.githubusercontent.com/93924525/172788492-7cebee29-0151-4bee-b0a4-9c71123c0973.png">

**Comment by MattAugustynowicz** [comment]
[👉 Figma User Story Here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9707%3A376114)

Several screens remain in the form of wireframes, as we do not have these views in Figma, while they are ready and implemented for other proposals

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/6b430c0c-ec8a-4fd3-a873-9f9b674697ec)

**Comment by dmtrjsg** [comment]
Discussed on the morning standup and some changes required to design and runtime:

1. Commitment field - optional > Not adding to the create proposal 
2. Payload hash string. Pioneer will generate it automatically > remove input from designs, but it will need to show on the proposal when viewed in Pioneer to help council with validating that payload is correct.
4. Create Metaprotocol task for these two fields on QN
- https://github.com/Joystream/joystream/issues/4458
5. Credit content WG budget update > No parameter on the Channel payouts proposal extrensic. So unless added will result in 2 diff proposals that need to be voted on separately. Separate task on Runtime.
- https://github.com/Joystream/joystream/issues/4459
6. QN for this separate. 
- https://github.com/Joystream/joystream/issues/4460

**Comment by dmtrjsg** [comment]
@thesan can you pls provide the steps on how to test this proposal, including the CLI part and the actual commands one needs to run to generate payload.

**Comment by dmtrjsg** [comment]
The `IPFS hash` and `size of the payload` needs to be provided to the chain on proposal creation. 



ℹ️ Files:

This one is original JSON with payout
https://raw.githubusercontent.com/Joystream/joystream/ephesus/cli/examples/content/ChannelPayoutsVector.json

This one has a merkle tree (after CLI processing)
https://raw.githubusercontent.com/Joystream/joystream/ephesus/cli/examples/content/ChannelPayoutsPayload.json

**Comment by thesan** [comment]
AFAIK the proposal calls the [`update_channel_payouts`](https://github.com/Joystream/joystream/blob/b46faf05e502956c9841f28e20b8472195875580/runtime-modules/content/src/lib.rs#L1521) extrinsic, which take the parameter [`UpdateChannelPayoutsParameters`](https://github.com/Joystream/joystream/blob/b46faf05e502956c9841f28e20b8472195875580/runtime-modules/content/src/types.rs#L802):
```rs
pub type UpdateChannelPayoutsParameters<T> = UpdateChannelPayoutsParametersRecord<
    ChannelPayoutsPayloadParameters<T>,
    BalanceOf<T>,
    <T as frame_system::Config>::Hash,
>;
```

- With [`ChannelPayoutsPayloadParameters`](https://github.com/Joystream/joystream/blob/b46faf05e502956c9841f28e20b8472195875580/runtime-modules/content/src/types.rs#L766) and [`UpdateChannelPayoutsParametersRecord`](https://github.com/Joystream/joystream/blob/b46faf05e502956c9841f28e20b8472195875580/runtime-modules/content/src/types.rs#L778):

   ```rs
   #[cfg_attr(feature = "std", derive(Serialize, Deserialize))]
   #[derive(Encode, Decode, Clone, PartialEq, Debug, Eq, TypeInfo)]
   pub struct ChannelPayoutsPayloadParametersRecord<AccountId, Balance> {
       pub uploader_account: AccountId,
       pub object_creation_params: DataObjectCreationParameters,
       pub expected_data_size_fee: Balance,
       pub expected_data_object_state_bloat_bond: Balance,
   }

   pub type ChannelPayoutsPayloadParameters<T> =
       ChannelPayoutsPayloadParametersRecord<<T as frame_system::Config>::AccountId, BalanceOf<T>>;

   #[cfg_attr(feature = "std", derive(Serialize, Deserialize))]
   #[derive(Encode, Decode, Clone, PartialEq, Debug, Eq, TypeInfo)]
   pub struct UpdateChannelPayoutsParametersRecord<ChannelPayoutsPayloadParameters, Balance, Hash> {
       pub commitment: Option<Hash>,
       pub payload: Option<ChannelPayoutsPayloadParameters>,
       pub min_cashout_allowed: Option<Balance>,
       pub max_cashout_allowed: Option<Balance>,
       pub channel_cashouts_enabled: Option<bool>,
   }
   ```

- Finally [`DataObjectCreationParameters`](https://github.com/Joystream/joystream/blob/b46faf05e502956c9841f28e20b8472195875580/runtime-modules/storage/src/lib.rs#L655):
   ```rs
   /// Parameters for the data object creation.
   #[cfg_attr(feature = "std", derive(Serialize, Deserialize))]
   #[derive(Encode, Decode, Clone, PartialEq, Eq, Debug, TypeInfo)]
   pub struct DataObjectCreationParameters {
       /// Object size in bytes.
       pub size: u64,
   
       /// Content identifier presented as IPFS hash.
       pub ipfs_content_id: Vec<u8>,
   }
   ```

**Comment by dmtrjsg** [comment]
Updates:
- [ ] Use Payload.json (and not vector)
- [ ] When file is uploaded display on the same page where proposal specific parameters are provided two values computed from the payload file:
Size of Payload
Payload Hash
- [ ] Remove note on max upload size of 3mb
