### ISSUE TITLE
Vote on Channel Payout Proposal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3075]
### Context

Same as in 
-  #3073 

### Scope

As a Council Member I want to vote on Channel Payout Proposal

Acceptance criteria:
- [ ] Follows [general pattern of proposal designs](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=338%3A12916)

**Comment by MattAugustynowicz** [comment]
These screens remain in the form of wireframes, as we do not have these views in Figma and we need only change the text content of the left column, I hope it's not a problem 🙌

[👉 Vote on Proposal](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9707%3A376533)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/dd1e4f24-cc0d-447d-b755-a9fa4381aaeb)

[👉 Vote on blocked proposal](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9731%3A376900)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/84a6e8ed-1fa5-4cae-bdec-bca72552ca01)![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/0df18eb5-fc93-4d68-9d21-ab325875cd0a)

**Comment by bedeho** [comment]
Why would there be any design or engineering needed for _voting_ on a specific proposal? Isn't all of this 100% generic across proposal types?

**Comment by dmtrjsg** [comment]
Proposal voting is generic indeed, its only the `proposal details page` with params placed into widgets required design. Looks like Matt put this e2e journey together for completeness back in the days..
