### ISSUE TITLE
[USERSNAP] Forum crash on category 9

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3096]
**Taken at**: https://dao.joystream.org/#/forum/category/9
**Fields**:
- Houston, we have a problem.: Forum crash on category 9
- Comment: Better without `TypeError: Expected &#34;id&#34; to match &#34;[^\/]+?&#34;, but received &#34;&#34;`
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/050c0bd3-f587-450f-addc-ea22cf4c4d84-annotated_d8bcccdf-3f1e-4029-a37f-f823a48a9fd0.png?etag=a87d0d2e13240693d031f88592d7e216)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/050c0bd3-f587-450f-addc-ea22cf4c4d84-annotated_d8bcccdf-3f1e-4029-a37f-f823a48a9fd0.png?etag=a87d0d2e13240693d031f88592d7e216)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1269x641
**[Open #259 in Usersnap](https://app.usersnap.com/l/feedback/81dd1d14-d1f9-4003-84dd-488ca71032bd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
```
react-dom.production.min.js:216
TypeError: Expected "id" to match "[^\/]+?", but received ""
    at index.js:212:15
    at E (react-router.js:261:32)
    at LatestPost.tsx:25:30
    at ro (react-dom.production.min.js:157:137)
    at Go (react-dom.production.min.js:180:154)
    at Fo (react-dom.production.min.js:178:169)
    at zd (react-dom.production.min.js:274:157)
    at Su (react-dom.production.min.js:250:347)
    at Du (react-dom.production.min.js:250:278)
    at _u (react-dom.production.min.js:250:138)
```
![forum-crash](https://user-images.githubusercontent.com/31551045/169654076-61528577-397d-4279-b353-afd6f96aa884.png)

**Comment by dmtrjsg** [comment]
Cannot reproduce. Maybe a QN hickup..
