### ISSUE TITLE
Council: Sort by `Vote Power` + history

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3098]
From https://github.com/Joystream/pioneer/pull/2791#issuecomment-1121125529

1. sort candidates by `vote power`
2. Either of
- show **failed candidates** on Council page - maybe grayed in the same list or below with a heading `Not Elected`
- Past Councils -> Council Members: add `vote power` and failed candidates
- verify that just elected council shows on **Past Elections** (to compare vote power of all candidates)
3. option to review former candidates' bullet points, image and program
- like **Election View** during an election but
- for past terms and
- with `final vote power`.
5. Does anyone have an idea how to better debug similar issues in the future from within pioneer https://github.com/Joystream/joystream/issues/3530#issuecomment-1120361999
![election6-mismatch](https://user-images.githubusercontent.com/31551045/169663440-f5a604b0-3df7-4b2f-a451-ad4963e00a48.png)

**Comment by dmtrjsg** [comment]
@traumschule thanks for raising, but for the future, let's pls try and keep the scope of raised issues within tasks that can be moved down the pipeline and handed over in dev 😇 

For this issue:

Sorting candidates by votes -> already implemented:
<img width="1087" alt="Screenshot 2022-06-06 at 17 51 59" src="https://user-images.githubusercontent.com/93924525/172147403-e365f254-614f-4a93-8860-227655252170.png">


issues raised: 
- https://github.com/Joystream/pioneer/issues/3189
- https://github.com/Joystream/pioneer/issues/3190
