### ISSUE TITLE
[USERSNAP] Openings: Minimal Stake value on pages is highly incorrect

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3100]
**Taken at**: https://dao.joystream.org/#/working-groups/openings/operationsWorkingGroupAlpha-3
**Fields**:
- Houston, we have a problem.: Openings: Minimal Stake value on pages is highly incorrect
- Comment: The actual min. stake for this role is 2m tJOY

This bug exists on all lead and worker openings that 
I checked
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7d20080c-cb01-4dd3-bc0c-2e854fd3d01d-annotated_ee3a2d7e-5218-4b0c-b16c-a4bed1a222f6.png?etag=96eba513bbad6ab27625b97637bb58ee)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7d20080c-cb01-4dd3-bc0c-2e854fd3d01d-annotated_ee3a2d7e-5218-4b0c-b16c-a4bed1a222f6.png?etag=96eba513bbad6ab27625b97637bb58ee)*

**Browser**: Chrome 101 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1452x1329
**[Open #261 in Usersnap](https://app.usersnap.com/l/feedback/f579e876-7e81-407b-a7f5-38c993a77c26?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
It appears the current value is being taken from the WGs budget

**Comment by freakstatic** [comment]
Fixed here: https://github.com/Joystream/pioneer/pull/3101
it was done by a community builder so appreciate if this can receive the `community-dev` label :smile:

**Comment by freakstatic** [comment]
@thesan can you move this to project 55?

**Comment by freakstatic** [comment]
@singulart already made a PR for this, can you assign me?

**Comment by polikosi** [comment]
Verified on staging. Test evidence below:
Minimal stake is 2000 tjoy
![Screenshot_76](https://user-images.githubusercontent.com/80429191/171850936-e26a8832-ae9e-4c9f-bde2-61f46dcf06d9.png)
![Screenshot_75](https://user-images.githubusercontent.com/80429191/171850941-899f6dd1-302c-4162-a85e-cf8d8030dd83.png)
