### ISSUE TITLE
"Terminated" Bounty doesn't show information

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#3105]
My understanding is that the Bounty goes to the "Past" section, from which all the stakes have been taken. 
![image](https://user-images.githubusercontent.com/84832436/169906678-f891343b-04c8-4090-be90-0c3eca33b713.png)
On the main page, these bounties have "SUCCESSFUL" status.
![image](https://user-images.githubusercontent.com/84832436/169907245-16bea182-b34c-414e-9afb-a9e54dfdd18b.png)
But if you go to the bounty itself, the status "Terminated" is shown
![image](https://user-images.githubusercontent.com/84832436/169907530-9a61dcb3-d3e3-42db-b46e-32b53e3bb8c3.png)
And the problem is that "Terminated" bounties do not show "Winners" and "Slashed" sections. The "Winners" section has valuable information with the date the bounty was judged.
Question: should it work like this? Or is it a bug?

![image](https://user-images.githubusercontent.com/84832436/169907854-7960e0e1-0873-44d3-80fe-ab1a4d45eac4.png)
This is what the bounty looks like, from which all the stakes have not yet been taken

Bounty for example: https://dao.joystream.org/#/bounty/preview/38

**Comment by dmtrjsg** [comment]
@adovrodion thanks for raising the question! 

Long story short, the Terminated status would probably benefit from better naming on the user end to avoid confusion, but this is the final status -always. Can be terminated-failed, terminated-successful, and terminated- funding. 

Here's a link to the V1 bounties state machine: https://joystream.gitbook.io/testnet-workspace/system/bounties#stage

The status display name is already added to the filters, but not to the bounty details page> 
<img width="331" alt="Screenshot 2022-06-06 at 16 54 32" src="https://user-images.githubusercontent.com/93924525/172138978-6ee81c59-816a-4e98-b789-1c1f4a41fba7.png">

NB: ⚠️ Bounties v2 will most probably get included into subsequent releases of network, and while the issue of lack of clarity on statuses will remain, it is more likely we will address all bounty enhancements / fixes in a single go. 

[Winners and Losers](https://github.com/Joystream/pioneer/issues/2413) are addressed in this fix, so I understand that should help. 

Closing this issue on the basis of the above comments.
