### ISSUE TITLE
Add LockRecoveryTime logic

### ISSUE THREAD

**Issue by RafalPloszka** [Joystream/pioneer#3109]
Add logic to LockRecoveryTime component for locks:

- [x] BountyLockItem
- [x] CouncilCandidateLockItem
- [x] CouncilorLockItem
- [x] ProposalLockItem
- [x] WorkingGroupLockItem

Out of scope: 

- [x] BoundAccountLockItem, InvitationLockItem - no way to know when lock will be recoverable
- [x] VoteLockItem - recovery time can vary depending on whether candidate will win

**Comment by ivanturlakov** [comment]
Tested on staging

**BountyLockItem**
Entrant stake 1,000tJOY
26min = 16min(working period) + 10min(judging period)
<img width="1440" alt="Снимок экрана 2022-06-14 в 18 07 50" src="https://user-images.githubusercontent.com/46903215/173612714-86614e6f-7fcc-4bbf-9e80-24d9c90d3fc8.png">
<img width="1440" alt="Снимок экрана 2022-06-14 в 18 07 30" src="https://user-images.githubusercontent.com/46903215/173612753-b47811ac-7892-4596-b1a2-4482ece8a89f.png">


**CouncilCandidateLockItem**
Candidate stake 11,000tJOY
1d 23h = 23h(voting) + 24h(revealing)
<img width="1440" alt="Снимок экрана 2022-06-14 в 18 16 12" src="https://user-images.githubusercontent.com/46903215/173614690-6f2609c1-a2a7-4713-89e6-f66c09b26f29.png">
<img width="1440" alt="Снимок экрана 2022-06-14 в 18 17 07" src="https://user-images.githubusercontent.com/46903215/173614864-e9544d10-3d7d-49f2-afb1-4e6106d36e38.png">


**CouncilorLockItem**
Voting period
<img width="1440" alt="Снимок экрана 2022-06-14 в 18 22 51" src="https://user-images.githubusercontent.com/46903215/173615736-b7ae5f09-320d-4513-8901-1302c92d878d.png">

**Comment by dmtrjsg** [comment]
Fixes addressed here: 
- https://github.com/Joystream/pioneer/issues/3276

**Comment by dmtrjsg** [comment]
Remains to be fixed:

**Functional**

- [ ] Fix CouncilorLock time in voting period
- [ ] For Proposals: copy logic from Proposal details page
- [ ] For Workers: Closed opening - fix for both recovery time and on the opening page

For open opening-  display "Based on hiring decision"
For worker actively in the role, the lock will remain for as long as the worker in the role. 
For closed opening - if candidate rejected (not hired) -> do not display anything and show "Recover" CTA
For closed opening - if candidate is hired -> lock depends on duration of role ⚠️ TBC

⚠️ For WG lead - > there is time after they are slashed that is called smth like "cooldown", which we need to factor in ☝️ 

For timed opening - calculate based on 

**+ Cosmetic** 

1️⃣ (buttons copy alignment):
<img width="292" alt="Screenshot 2022-06-23 at 12 20 32" src="https://user-images.githubusercontent.com/93924525/175287456-ffaf19f9-21fe-4fe5-acb6-1bf34b9711d1.png">

2️⃣ 
Remove "Olympia Network"  label from the block info on lock date

3️⃣ 

Display "Unrecoverable" for invitation Lock
Display "Unrecoverable" for Bound staking account Lock

**Comment by ivanturlakov** [comment]
Tested on staging

Based on Dmitry`s list

_**Fix CouncilorLock time in voting period: > Council Period Countdown***_

<img width="1440" alt="Снимок экрана 2022-07-01 в 14 37 38" src="https://user-images.githubusercontent.com/46903215/177153367-7b2c2642-6b0e-490a-a210-89040022efc5.png">

Elected

<img width="1171" alt="Снимок экрана 2022-07-04 в 15 36 37" src="https://user-images.githubusercontent.com/46903215/177156435-443f3894-7391-4c1d-8a32-23508f248661.png">


Fix for Voting: < (Voting Period + Revealing Period + Council Time)*

<img width="1172" alt="4d_show_election_404_1" src="https://user-images.githubusercontent.com/46903215/177153661-322393f6-73d4-4833-905d-0ce94fa52998.png">

For Proposals: copy logic from Proposal details page

<img width="1169" alt="Снимок экрана 2022-07-01 в 14 15 57" src="https://user-images.githubusercontent.com/46903215/177153947-de1c7577-6741-4d9f-a0df-b5acfc87dfd4.png">

For Workers: For open opening- display "Based on hiring decision"

<img width="1172" alt="Снимок экрана 2022-07-01 в 17 41 23" src="https://user-images.githubusercontent.com/46903215/177154213-91128cc7-6def-4687-8a86-b2024dc7ac1b.png">

_**For Workers: For closed opening - if candidate rejected (not hired) -> do not display anything and show "Recover" CTA**_

<img width="1172" alt="Снимок экрана 2022-07-04 в 15 28 00" src="https://user-images.githubusercontent.com/46903215/177154896-105900fa-d704-4134-b175-da433ac4d8cd.png">


For Workers:For closed opening - if candidate is hired -> "Recoverable after released from role"

<img width="1172" alt="Снимок экрана 2022-07-04 в 14 15 52" src="https://user-images.githubusercontent.com/46903215/177155297-827997fe-18fd-4b6f-a6b8-63d4357bd910.png">



buttons copy alignment

<img width="1174" alt="Снимок экрана 2022-07-01 в 17 42 45" src="https://user-images.githubusercontent.com/46903215/177155694-86a09ca1-7cda-4dc9-b408-2053b84facb3.png">




Display "Unrecoverable" for invitation Lock
Display "Unrecoverable" for Bound staking account Lock

<img width="1166" alt="Снимок экрана 2022-07-01 в 14 12 08" src="https://user-images.githubusercontent.com/46903215/177155843-b47828ea-3fe1-4b31-b059-11a3f4a57443.png">

**Comment by dmtrjsg** [comment]
@RafalPloszka two points left to address here

For Workers: For closed opening - if candidate rejected (not hired) -> do not display anything and show "Recover" CTA
Fix CouncilorLock time in voting period: > Council Period Countdown* + Tooltip "Recoverable if not elected"

**Comment by dmtrjsg** [comment]
+ Copy in the eta field to use same block info
