### ISSUE TITLE
Placeholder screen for disabled bounties

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#3114]
Since people have become used to bounties, yet they are disabled, we should retain it in the side-menu and instead fill the main screen with some sort of explainer message saying that V2 version is coming soon.

Its unclear if we need this for `Carthage` as we in principle may end up using V1 bounty module there still, to not disrupt HR working group too badly.

* [ ] Bounties v2 is coming soon <- we need to design it [DESIGN WORK]
* [ ] Disable Bounties v1 [DEV WORK]

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202349046738247) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@bedeho Bounties module is operational afaik (subj to QN bugs that have been raised and being fixed). 

I will keep this issue in the "new issues" pipeline for the time being, with the view to clarify it around us all focussing on Carthage.

**Comment by bedeho** [comment]
Moving this issue to `Carthage` scope due to this https://github.com/Joystream/joystream/issues/3881.

**Comment by bedeho** [comment]
> will Bounties v1 be disabled on runtime level with MainNet launch? Or remain operational up until replaced with fully functioning v2?

It will be disabled not only on mainnet, but even in `Carthage`, talked to Martin, and he said the social ramifications of this change were not severe, so its a good idea in order to just further simplify things.

**Comment by dmtrjsg** [comment]
Let's go with this version + Copy update
 
 "Bounties module is coming back soon!"
 
 We are working on the necessary upgrades for the much loved Bounties module to be released shortly! Stay Tuned!
 
 
<img width="679" alt="Screenshot 2022-06-23 at 14 06 39" src="https://user-images.githubusercontent.com/93924525/175305778-d6ecfb02-23e6-4ae9-a3e7-f1c1f9ebb6f1.png">

**Comment by dmtrjsg** [comment]
@WRadoslaw sorry to bother, but we need to upd the page as per this comment: 
https://github.com/Joystream/pioneer/issues/3114#issuecomment-1164389387
