### ISSUE TITLE
Log out from currently selected membership button

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3120]
**Context:**
Feature of keeping the memebrship as signed in on browser page refresh

from  https://github.com/Joystream/pioneer/issues/2645
has an open PR>
https://github.com/Joystream/pioneer/pull/3113

**Scope:**
- [ ] Add sign-out flow designs (button and modal)

**Comment by MattAugustynowicz** [comment]
[👉 Figma link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9470%3A343505)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/da1c8bf9-3e7b-4acf-a3aa-ed747a7a58a3)

In my opinion, a modal with confirmation is not necessary here. It is rather difficult to missclick here, and logging in again does not require a password so it takes half a second. Nevertheless, I leave this screen

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/07f252e3-b2fd-4075-8efd-555d8af9cab9)
