### ISSUE TITLE
Sufficient Balance Check for Staking Account when Stake is a dynamic input > minimum requirement

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3131]
## Context

Identified no validation on staking acc balance where staking is user-input and above minimum value:
https://github.com/Joystream/pioneer/issues/3019#issuecomment-1139730525

## Scope

- [ ] Add validation on the staking account and show the error message for the account selected
(Insufficient balance) using existing field-level validation warning
- [ ] Wording: "Selected staking account has insufficient balance to complete this transaction."
- [ ] Apply the above to Vote for Council Modal as per [this comment](https://github.com/Joystream/pioneer/issues/3019#issuecomment-1139730525)

**Comment by traumschule** [comment]
I looked at the code and this seems to be implemented in https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/common/utils/validation.tsx#L163
Please re-test.

**Comment by polikosi** [comment]
tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://44.201.112.198.nip.io/network/config.json
✅ works as expected


**Applying for role**
![image](https://user-images.githubusercontent.com/80429191/199508215-b79aa494-f246-4d5c-a19b-4f9fe6ad851d.png)
**Creating new proposal**
![image](https://user-images.githubusercontent.com/80429191/199508644-7b321a9e-a53a-4081-8ac8-c18223a29c1f.png)
**Announce candidacy**
![image](https://user-images.githubusercontent.com/80429191/199508780-7ca2971d-0eb3-42c0-b26e-6af46a4c9993.png)
![image](https://user-images.githubusercontent.com/80429191/199509103-f8714a4e-44b9-442f-a9d8-6e5c88a274d8.png)
**Vote for council**
![image](https://user-images.githubusercontent.com/80429191/199513469-30e8292e-4228-4d69-9036-1dbae807208c.png)

**Comment by dmtrjsg** [comment]
@polikosi @traumschule we should not display the current balance in the validation error. The error should be "Insufficient funds to cover staking amount."

**Comment by traumschule** [comment]
@polikosi please test this once more

**Comment by polikosi** [comment]
tested on https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json
Applying for role
![image](https://user-images.githubusercontent.com/80429191/205282922-e63d2814-5da0-401a-afb1-7e915349bd9c.png)

Announce candidacy
![image](https://user-images.githubusercontent.com/80429191/205286323-d3e33b02-c5b8-48e4-9759-6ada96936589.png)

Vote for council
![image](https://user-images.githubusercontent.com/80429191/205283286-4f69ba0f-ef00-4cde-b3a2-c02a0ddc4829.png)
