### ISSUE TITLE
VoteForCouncilModal voter balance validation

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#3132]
In general, validation works well. 
One finding. In case the user entered a value that exceeds the balance, the Next Step button appears active and the transaction will result in an insufficient balance error. Would be good if we validate this field in the first step)

https://user-images.githubusercontent.com/46903215/170731899-466dec37-fa93-4cd7-9317-17d359b24e8a.mov

**Comment by dmtrjsg** [comment]
already raised here: #3131
