### ISSUE TITLE
UpdateMembership

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#3133]
## Scope

- [ ] Add refetching of Membership details on side panel (on the left) 
- [ ] and MemberId in the membership module

__________
Some frontend items(marked red) did not update after the transaction was executed.

Member choosed for editing
<img width="1440" alt="Снимок экрана 2022-05-26 в 14 14 04" src="https://user-images.githubusercontent.com/46903215/170480253-f98c88c1-02d9-4583-be3f-0ee6dd612660.png">

Editing
<img width="956" alt="Снимок экрана 2022-05-26 в 14 15 03" src="https://user-images.githubusercontent.com/46903215/170480314-7d13e2d7-e2ee-4e78-92e3-84b0f00f4c08.png">

Frontend after editing. The fields marked in red were not updated untill page refreshed.
<img width="1440" alt="Снимок экрана 2022-05-26 в 14 20 27" src="https://user-images.githubusercontent.com/46903215/170480355-fd90209d-3b49-4d65-808a-ecb81c98d25a.png">

Transaction details
<img width="1410" alt="Снимок экрана 2022-05-26 в 14 22 01" src="https://user-images.githubusercontent.com/46903215/170480375-4214ca3b-5221-4cd1-b65f-001833a25822.png">

**Comment by traumschule** [comment]
From my research to update the left sidepane call `setActive(member)` on state.machine('success')
``` ts
// memberships/modals/UpdateMembershipModal/UpdateMembershipModal.tsx
import { useMyMemberships } from '../../hooks/useMyMemberships' 
const { members, setActive, active } = useMyMemberships()

...

if (state.matches('success')) {
  setActive(member) // <-- here
  return <UpdateMembershipSuccessModal onClose={hideModal} member={member} />
```
This *should* automatically update `My Profile` as well.

Just confirming there's no better way, @dmtrjsg @thesan

**Comment by dmtrjsg** [comment]
@traumschule Hey will be okay to go like that 👌 , thanks for driving it by us!

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/profile/memberships
wss://34.230.5.182.nip.io/ws-rpc

You still need to refresh the page to see the changed data

https://user-images.githubusercontent.com/46903215/205452159-6e1b25b5-d69c-4a59-b25c-ea65eb98904c.mov

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/profile/memberships
wss://34.230.5.182.nip.io/ws-rpc

All items were updated successfully

https://user-images.githubusercontent.com/46903215/209116893-1ed365dc-d9e9-425e-98b4-f615f247fcd9.mov
