### ISSUE TITLE
Testnet Info (FM) Banner

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3141]
**Context:**
Reduced version follow up for the FM banner with a view to simplify and expedite this feature.

**Scope:**
- [ ] Banner shows for all users upon landing to Pioneer (any page)
- [ ] Do not show this again checkbox
- [ ] Setting stored in local storage
- [ ] Links from Copy pointing to the right pages on Gitbook
- [ ] "Speak with Community Integrators" points to Discord channel with integrators -> https://discord.gg/nmWPBJNT5x

**Out of scope**
- [ ] Learn more pointing to https://www.joystream.org/start-here/what-is-joystream

**Designs:**

[LINK TO FIGMA> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9470%3A334167)

⚠️  we only need to implement this screen:

<img width="834" alt="Screenshot 2022-06-02 at 12 59 30" src="https://user-images.githubusercontent.com/93924525/171563053-e4673a2f-6e6f-4cb9-a1b9-404e1ee81cd4.png">

**Additional Details / Copy**

H1: Joystream currently runs on Testnet!

Para: 
___

Testnet participants [earn](https://joystream.gitbook.io/testnet-workspace/testnet/testnet-rewards) a combination of our testnet token [$tJOY](https://joystream.gitbook.io/testnet-workspace/testnet/usdtjoy), and allocation of our mainnet token $JOY (which will come to life upon mainnet launch).

$tJOY can be [converted](https://www.joystream.org/cashout/) to BCH, (Bitcoin cash cryptocurrency) immediately, whereas $JOY will be allocated shortly after mainnet launch, assuming the contributor has reached the [Founding Member ](https://joystream.gitbook.io/testnet-workspace/testnet/founding-member-program#stages)status, buy accruing $15k USD worth of $JOY.

$tJOY balances have no relationship to mainnet $JOY balances, there will be no conversion of any kind.

_🇺🇸 US residents are not eligible for JOY tokens._

___
~Before the project is launched on Mainnet, Earn [$tJOY](https://joystream.gitbook.io/testnet-workspace/testnet/usdtjoy), the native asset of Testnet, through undertaking various [roles and activities ](https://joystream.gitbook.io/testnet-workspace/testnet/testnet-rewards) available right now. $tJOY balances have no relationship to mainnet $JOY balances, there will be no conversion of any kind. $tJOYs earned can only be exchanged to cryptocurrency BCH (Bitcoin Cash) at the [exchange rate](https://www.joystream.org/cashout/), which JSGenesis attempts to keep stable. JOY tokens, Mainnet coin, allocated among some of our highest quality community members in recognition of their contributions to the project. Get a verified membership and become a [Founding Member](https://joystream.gitbook.io/testnet-workspace/testnet/founding-member-program) to benefit from this programme. _🇺🇸 US residents are not eligible for JOY tokens._~

Primary: "Speak with Community Integrators" -> Discord

**Comment by MattAugustynowicz** [comment]
@dmtrjsg @mrexpat imo "get started" should direct [here](https://www.joystream.org/start-here/what-is-joystream). This will show users how to cooperate with Joystream, and they will be redirected to discord once they have read the "tutorial." Directly putting the user on discord may not be entirely clear

**Comment by dmtrjsg** [comment]
@MattAugustynowicz how about?

Primary: Learn More -> videos on marketing website
Secondary: Speak with Community Integrators -> Discord

__imo nothing works better than speaking with a live person in terms of CR ..

**Comment by dmtrjsg** [comment]
@MattAugustynowicz thank you, looking good!

**Comment by mrexpat** [comment]
> @mrexpat, pls share the URL and UTM for the discord channel with intgrators. NB: https://support.discord.com/hc/en-us/articles/115001542132-Custom-Invite-Link

They use the #start-here channel - here's the invite link (also available in the onboarding CTA) - https://discord.gg/nmWPBJNT5x

**Comment by mrexpat** [comment]
> @MattAugustynowicz how about?
> 
> Primary: Learn More -> videos on marketing website Secondary: Speak with Community Integrators -> Discord
> 
> __imo nothing works better than speaking with a live person in terms of CR ..

I say just go with the 1 CTA and have it go to discord.. we can send the right onboarding videos to the right person based on chatting with them

**Comment by mrexpat** [comment]
IMO, the paragraph could clarify more that users earn both tJOY and JOY by participating (if they verify).

I would go more along the lines of

--

Testnet participants earn a combination of our testnet token $tJOY, and allocation of our mainnet token $JOY (which will come to life upon mainnet launch).

$tJOY can be converted to cash immediately, whereas $JOY will be allocated shortly after mainnet launch, assuming the contributor has reached the minimum verification limit to receive their allocation ($10k worth of $JOY).

--

I think this is a shorter, and easier to understand description. I am not sure whether $JOY allocations are unlocked based on verification, or becoming FM.. and also am not sure about the $10k figure I put :)

**Comment by dmtrjsg** [comment]
@WRadoslaw copy is finalised!

Testnet participants [earn](https://joystream.gitbook.io/testnet-workspace/testnet/testnet-rewards) a combination of our testnet token [$tJOY](https://joystream.gitbook.io/testnet-workspace/testnet/usdtjoy), and allocation of our mainnet token $JOY (which will come to life upon mainnet launch).

$tJOY can be [converted](https://www.joystream.org/cashout/) to BCH, (Bitcoin cash cryptocurrency) immediately, whereas $JOY will be allocated shortly after mainnet launch, assuming the contributor has reached the [Founding Member ](https://joystream.gitbook.io/testnet-workspace/testnet/founding-member-program#stages)status, buy accruing $15k USD worth of $JOY.

$tJOY balances have no relationship to mainnet $JOY balances, there will be no conversion of any kind.

_🇺🇸 US residents are not eligible for JOY tokens._

**Comment by mrexpat** [comment]
small typo should be "by accruing $15k USD worth of $JOY"
