### ISSUE TITLE
CI false positive

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3148]
Problem: Individual test keeps on randomly timing out.

Slow tests/test suites should be addressed more depth by #2798. But in the meantime the jest `testTimeout` should be increased globally.

**Comment by ivanturlakov** [comment]
Jest testTimeout has been increased

<img width="1440" alt="Снимок экрана 2022-06-10 в 12 42 21" src="https://user-images.githubusercontent.com/46903215/173039229-9ad9e519-8395-42c2-8f70-49903466b954.png">

@dmtrjsg if there is a wider context, could you add some description for QA?
