### ISSUE TITLE
Working groups milestone

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#315]
# Introduction

![Screenshot 2021-03-25 at 08 47 09](https://user-images.githubusercontent.com/247363/112496078-bfeb4b00-8d84-11eb-9b6e-1330ad802e3b.png)

Working Group is one of the bigger Pioneer subsystems. It enables Pioneer users to get an overview of the Joystream working groups and participate in working group internal affairs.

# Goals

The goals below represent the full Working Groups subsystem for any member role (non-member, member, worker, and working group leader).

The Working Group leader is considered an advanced role and might not be critical for an MVP. Working group leader actions might be implemented as CLI commands.

Goals 1-6 seem essential for a broader audience, while goals 7-8 might be implemented later.

1.  Enable non-member to get an overview of a Working Groups subsystem
2.  Enable non-member to get a status of a given working group
3.  Enable member to apply for an open position
4.  Enable member to manage own applications
5.  Enable worker to manage own roles
6.  Enable worker to manage locked balances
7.  Enable working group leader to create and manage openings
8.  Enable working group leader to manage workers

# Goals details

Each goal has a work scope with links to GH tickets. Tickets with :purple\_circle: (and "epic" label) are considered to require ~1 week of work). The rest of the tickets should require a 0.5-1 day of work each.

## 1\. Working Groups subsystem overview

The entry page for the Working Groups subsystem allows any member or a non-member user to get an overview of working groups and understand what's happening.

### Work scope

*   Implement the working groups' subsystem overview page (#287) :purple\_circle: 
*   Display list of all the working groups (#288)

### Work scope

*   Display working group dashboard and openings (#289) :purple\_circle: 
*   Display working group about tab: information and current workers (#290)
*   Display working group history: past openings and activities (#291)

### Work scope

*   Display open position preview (#292) :purple\_circle: 
*   Apply for a position flow (#293) :purple\_circle: 

### Work scope

*   Display "my applications" tab in working groups overview (#294)
*   Display application preview (#295)
*   Allow member to withdraw application (#296)

### Work scope

*   Display "my roles" tab in working groups overview (#297) :purple\_circle: 
*   Display the "roles" tab in the member profile (#298)
*   Allow member to leave a position (#299)
*   Display role details (#300)
*   Display activity details (#301)

### Work scope

*   Allow member to recover balance (#302)
*   Display account's locks and recoverable balance (#303)
*   Change role and reward accounts (#304)
*   Move funds to the locked account (#305)

The scope for goals 7 & 8 was not yet defined. All the issues are empty placeholders.

### Work scope

*   Allow working group leader to create an opening (#306)
*   Allow working group leader to close an opening (#307)
*   Allow working group leader to select a winner (#308)

### Work scope

*   Allow working group leader adjust periodic pay to a worker (#309)
*   Allow working group leader to terminate a worker (#310)
*   Allow working group leader to slash a worker (#312)
*   Allow working group leader to manage stake (#311)

---

### Integration

*   Explore joystream-node API for available queries and extrinsic.
*   Working group data structure from the query-node.
*   Off-chain metadata structure ([https://github.com/Joystream/joystream/issues/2245](https://github.com/Joystream/joystream/issues/2245))

---

# Steps after this milestone

Below are parts of the Pioneer 2.0 application that is used by other subsystems and should be implemented during or right after Working Groups.

### Notification subsystem

The notification subsystem displays notifications for the member from other subsystems:

*   Transaction status (if the user closed the "wait for transaction" modal).
*   Notify on open opening (the "Notify me when it's open" button on upcoming opening)
*   Working group role changes, opening application status changes, etc.
*   Forum mentions.

**Comment by bedeho** [comment]
Phenomenal summary, looks good!

**Comment by jodator** [comment]
Open issues that was cut out of the milestone:

Allow member to recover balance (#302)

7\. Managing working group openings

*   Allow working group leader to create an opening (#306)
*   Allow working group leader to close an opening (#307)
*   Allow working group leader to select a winner (#308)

8\. Managing working group workers

*   Allow working group leader adjust periodic pay to a worker (#309)
*   Allow working group leader to terminate a worker (#310)
*   Allow working group leader to slash a worker (#312)
*   Allow working group leader to manage stake (#311)
