### ISSUE TITLE
Forum: Landing Page - Main Tab - Latest Threads

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3151]
## Context
UX facelift of Forum Module

## Designs Preview

[LInk to Figma> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A333164)

Thread Card
![](https://user-images.githubusercontent.com/93924525/171571255-9eed3d5d-d6b8-4ece-acd9-73d52d6c0219.png)

Latest Threads

![](https://user-images.githubusercontent.com/93924525/171567397-0032aefd-4979-40ba-b188-ba30d285c603.png)

## Scope
:one:   **Latest Threads Carousel.**

AC: 

* [ ] Newest on the left
* [ ] Show all threads in the carousel 
* [ ] Load first X depending on page width 
* [ ] Chevron click loads a full set of new cards to take full screen width
* [ ] Loading with skeleton ([refer to loading states design](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=5011%3A133032))

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464660556485) by [Unito](https://www.unito.io)

**Comment by Funnydev1031** [comment]
Hello. I confirmed my task.

**Comment by singulart** [comment]
Assigned to @Funnydev1031

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json



https://user-images.githubusercontent.com/46903215/204791555-d5b1b1a4-4bdc-4e98-8bfa-eceeb957cbbc.mov


⚠️ @dmtrjsg `text-overflow: ellipsis;` could be applied for long thread titles(as on member handle), if we have a time

<img width="1197" alt="Снимок экрана 2022-11-30 в 14 09 16" src="https://user-images.githubusercontent.com/46903215/204793153-635e9362-48d9-4d93-b395-2c8ee3683465.png">
