### ISSUE TITLE
Forum - My threads Tab

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3152]
## Context
UX facelift of Forum Module

## Designs Preview

![](https://user-images.githubusercontent.com/93924525/172781259-fc187779-7bb3-434a-b653-29894325773d.png)

[LInk to Figma> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9550%3A349072)

## Scope
**My threads Tab**

AC

* [ ] Section name My threads
* [ ] Display all threads as individual cards (basically filter by creator)
* [ ] Show threads counter in a pill on tab 
> MattAugustynowicz pls update the designs to include it
* [ ] Sorty by date starting with newest on top
* [ ] Show number of replies (same design as threads on homepage)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464580928170) by [Unito](https://www.unito.io)

**Comment by MattAugustynowicz** [comment]
[👉 Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9550%3A349072)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/0496a057-1791-4243-bc39-cfa3b8d55c70)

**Comment by dmtrjsg** [comment]
My threads would be only posted by selected member, so also need to remove filtering :)

**Comment by MattAugustynowicz** [comment]
@dmtrjsg You are right, for a moment I thought there would be threads from all our memberships :)

[👉 Figma link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9550%3A349072)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/11008029-039f-4d32-b91c-ba2d094ea19e)

**Comment by secretgir1** [comment]
Hey @dmtrjsg 
Some questions to AC:
-- Could you please explain in more details what did you mean here:
" Show threads counter in a pill on tab"?
-- Also " Display all threads as individual cards (basically filter by creator)" - My Threads Tab will be displayed just my personal threads isn't it? Can't understand why should it be filtered by creator if we have just one creator here.

**Comment by dmtrjsg** [comment]
Sure @secretgir1 

>Show threads counter in a pill on tab"?
We display the number of threads contained in that tab as a "pill" label with the counter:
<img width="88" alt="Screenshot 2022-07-15 at 16 46 02" src="https://user-images.githubusercontent.com/93924525/179259192-85f857ce-bd3a-4f11-a68d-5bf049c0b708.png">

We do not display "0" in the pill.

> basically filter by creator

You are correct, this was more of a clarification point. This tab only contains own threads.

**Comment by secretgir1** [comment]
@dmtrjsg  thanks

**Comment by secretgir1** [comment]
Accepted. Ready for development.

**Comment by Palllke2015** [comment]
I'd like to work on this task

**Comment by singulart** [comment]
Assigned to @Palllke2015

**Comment by Palllke2015** [comment]
@dmtrjsg Should we have Pagination here?

**Comment by dmtrjsg** [comment]
@Palllke2015 Was not part of this issue, but will add to the backlog as enhancement.

**Comment by polikosi** [comment]
verified on https://dao-git-fork-palllke2015-feature-forum-my-threads-joystream.vercel.app/#/forum/my-threads

 Section name "My thread"
![Screenshot_159](https://user-images.githubusercontent.com/80429191/180660606-95bcf869-646e-404b-b2f5-880826c1b74a.png)

 Display all threads as individual cards (basically filter by creator)
![Screenshot_161](https://user-images.githubusercontent.com/80429191/180660757-55fa7468-f915-46bb-bac7-76ecaf1a7e2c.png)

 Show threads counter in a pill on tab
![Screenshot_162](https://user-images.githubusercontent.com/80429191/180660782-696bf9e0-e555-43ec-bcda-37ef8a0806d5.png)


 Sorty by date starting with newest on top
![Screenshot_163](https://user-images.githubusercontent.com/80429191/180660795-ce548e3b-e0ef-43b1-af76-4ef00fdf29ee.png)


 Show number of replies (same design as threads on homepage)
![Screenshot_164](https://user-images.githubusercontent.com/80429191/180660850-2102e37f-aecd-4e91-b175-bc1eac185175.png)

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

✅ Section name My threads
✅ Display all threads as individual cards (basically filter by creator)
✅ Sorty by date starting with newest on top
✅ Show number of replies (same design as threads on homepage)
⚠️ Threads counter on tab is missed

<img width="1213" alt="Снимок экрана 2022-11-30 в 16 22 40" src="https://user-images.githubusercontent.com/46903215/204820764-edf7dc5e-e172-469b-b034-56921db45d0e.png">

**Comment by dmtrjsg** [comment]
Will add counter as a separate issue! Thanks @ivanturlakov for a fast turnaround 🙏 
- #3910
