### ISSUE TITLE
Forum Activity Drawer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3155]
## Context
UX facelift of Forum Module

## Designs Preview

[Link to Figma> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A337918)

![](https://user-images.githubusercontent.com/93924525/171613632-355a2b78-b01c-4d6f-a301-c1e68315ee80.png)

## Scope
* [ ] Activity drawer [hidden behind button](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A336816)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464608524638) by [Unito](https://www.unito.io)

**Comment by secretgir1** [comment]
Accepted. Ready for development.

**Comment by polikosi** [comment]
![image](https://user-images.githubusercontent.com/80429191/204894263-4a41a4a5-1290-4dc4-a9be-9259242a7904.png)

![image](https://user-images.githubusercontent.com/80429191/204894164-87650a13-0a99-4bb9-b8e2-07c5ace6cc5a.png)
