### ISSUE TITLE
Forum Landing Page - Main Tab - categories

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3157]
## Context
UX facelift of Forum Module

## Designs 

[Link to Figma >](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=8966%3A319910)

This page > https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A333164

## Scope
**Categories Section on Main Forum Tab**

![](https://user-images.githubusercontent.com/93924525/171575443-6a0a2770-8beb-4859-9688-86bf39c85565.png)

AC: 

* [ ] Header - Categories
* [ ] Order of categories is hard-coded with fixed positioning
* [ ] Top 8 categories for the build:

1. Working Groups
. ~Bounties~  :warning:  Hide Bounties from Forum
1. Marketing
1. Development
1. Validators 
1. Discussions
1. Help & Support

* [ ] ~Show all button expands the rest of the categories:~

1. Content Creators
1. Creatives
..
1. Governance
1. Grants and Funding
1. Education
1. Atlas Feedback
1. Lounge

* [ ] New categories get added to the bottom of the list

Out of scope ⛔ : 
- [ ] #3364

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464581204491) by [Unito](https://www.unito.io)

**Comment by secretgir1** [comment]
Hi @dmtrjsg 

Could you please provide link for this page in figma?

**Comment by dmtrjsg** [comment]
@secretgir1 sure, [here's the link>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A333164)

Will also review other tickets in this epic and do the same if needed.

**Comment by secretgir1** [comment]
> @secretgir1 sure, [here's the link>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9364%3A333164)
> 
> Will also review other tickets in this epic and do the same if needed.

It would be nice if you provide design of see all button, the rest is understandable, thanks.

**Comment by dmtrjsg** [comment]
@secretgir1 thanks for the question! 

I've isolated this AC to a separate issue and added to the backlog for design team. This will be done in a few weeks time as we are busy on smth else on Atlas rn. 

- https://github.com/Joystream/pioneer/issues/3364

please feel free to proceed showing all categories (with the order specified in the description)

**Comment by polikosi** [comment]
✅Header - Categories

✅Order of categories is hard-coded with fixed positioning
All new categories get added to the bottom of the list.

Categories
![image](https://user-images.githubusercontent.com/80429191/204901920-fcff106d-bf4e-427a-b75f-8c52892a293c.png)


✅New categories get added to the bottom of the list
Added new category "Governance"
![image](https://user-images.githubusercontent.com/80429191/204899790-19347196-46d1-41f7-9658-9d7d9af7b046.png)
![image](https://user-images.githubusercontent.com/80429191/204899959-e888437b-43de-4602-94a2-068f9da372c0.png)
