### ISSUE TITLE
Forum: Watchlist Threads

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3162]
## Context
Forum UX update

## Design

[LInk to Figma> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9639%3A354609)

## Scope
* [ ] Watchlist tab
* [ ] Counter of threads in the tab as pill 
> MattAugustynowicz pls upd the designs to include the above
* [ ] Hover on thread card shows remove from watchlist
* [ ] Remove from watchlist action

:information_source:

thread card is described here - #3183

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464606651656) by [Unito](https://www.unito.io)

**Comment by MattAugustynowicz** [comment]
[👉 Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9639%3A354609)

I think it would be better if this page were a separate tab. We have a simple filtering by which we could choose the author of the post we have in the watchlist, additionally like on the main page we can see the categories in pills and the number of replies on the tile. I think we can add on the hover state the possibility of immediate removal of a given post from the watchlist

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/d18539ab-2fb2-45fa-8168-13f3817af040)

**Comment by dmtrjsg** [comment]
@MattAugustynowicz 

Re filters, on the watchlist I would not worry about it as the amount of threads on watchlist would not be overwhelming for average user. Sorting with latest on top  without possibility to change it I think should suffice. @MattAugustynowicz pls remove filters from here.

**Comment by MattAugustynowicz** [comment]
Resolved ✅

👉 [Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9639%3A354609)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/63fc5eeb-7ea7-42a2-b5c2-41f24d6e41da)

**Comment by secretgir1** [comment]
Accepted. Ready for development.

**Comment by dmtrjsg** [comment]
Duplicates and implemented in 
- https://github.com/joystream/pioneer/issues/3642

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

✅ Watchlist tab
⚠️ Counter of threads in the tab is missed.
✅ Hover on thread card shows remove from watchlist
✅ Remove from watchlist action

https://user-images.githubusercontent.com/46903215/205011862-b7d5f966-3032-4d84-81c9-2b384b8cd4a7.mov

**Comment by dmtrjsg** [comment]
Assigning to @thesan to conver the paginator to slider. This work will span all sliders.

**Comment by traumschule** [comment]
> Duplicates and implemented in #3642
