### ISSUE TITLE
Forum: Reply to thread in a modal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3163]
## Context
Forum UX facelift

## Design

[Link to Figma>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9639%3A351739)

## Scope
Replying to thread

* [ ] Reply to thread triggers new modal if member logged in
* [ ] Reply modal contains original message in the header)
* [ ] Guest user prompted to choose membership automatically
* [ ] Once thread is posted, screen anchors to the newly posted thread
* [ ] We do not change the place where reply shows as part of this ticket
* [ ] Same as above for new threads

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464609354383) by [Unito](https://www.unito.io)

**Comment by MattAugustynowicz** [comment]
[👉 Figma link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9553%3A351140)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/282dd0fe-34d6-4fcb-b09d-ac6fde48cc6b)


![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/7274d9ed-c096-4e16-bf9e-af75c2668359)

**Comment by dmtrjsg** [comment]
@MattAugustynowicz Thanks for putting this together, few more questions: 

<img width="471" alt="Screenshot 2022-06-08 at 13 04 00" src="https://user-images.githubusercontent.com/93924525/172543452-95818ebc-a374-4311-b3bd-90747f1b9ce2.png">

<img width="266" alt="Screenshot 2022-06-08 at 13 05 03" src="https://user-images.githubusercontent.com/93924525/172543485-b7405aef-20c3-4d69-a1ac-14f137b50164.png">

**Comment by MattAugustynowicz** [comment]
@dmtrjsg If you reply by clicking on the "reply" icon then you will always quote some statement, so you will have this view.

If, on the other hand, you want to add a post in this topic but not reply directly to someone's message, then it is natural that you will first read the replies below (to be sure you are not duplicating a question or thought) and then reply using the frame we currently have at the bottom.

As for adding a new one (here I assume you meant a thread, not a post) I would have to ask you to send a screenshot of what it currently looks like, or transfer 40 tJOY to my account, so I can see what it looks like. Classically in figma this has not been designed :)

**Comment by secretgir1** [comment]
Accepted. Ready for development.

**Comment by BeardKoda** [comment]
Started Development.

**Comment by singulart** [comment]
Moved back to To-Do

**Comment by polikosi** [comment]
✅Reply to thread triggers new modal if member logged in
✅Reply modal contains original message in the header
![image](https://user-images.githubusercontent.com/80429191/206438969-a54bfa14-559c-461c-ab05-73ca752398bc.png)
✅Guest user prompted to choose membership automatically
✅Once thread is posted, screen anchors to the newly posted thread
✅We do not change the place where reply shows as part of this ticket
 Same as above for new threads

https://user-images.githubusercontent.com/80429191/206441387-220f1152-d08d-425e-81b0-1ad050d1517c.mp4
