### ISSUE TITLE
[USERSNAP] Past Elections: Shows incorrect blockheight for "Election Ended at"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3168]
## Scope
- [ ] Fix the page to show election ended blockheight, and not started (as right now).

___
**Taken at**: https://dao.joystream.org/#/election/past-elections
**Fields**:
- Houston, we have a problem.: Past Elections: Shows incorrect blockheight for &#34;Election Ended at&#34;
- Comment: SSIA
The blockheights shown are for when the announcing period started rather than when an election ended.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/38e9cbed-35b0-49de-9c05-15a7501c6b8c-annotated_acb7412f-e672-4008-bab7-9359993456b2.png?etag=6d6fb52367d270d54d2c7682e5e7bfa8)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/38e9cbed-35b0-49de-9c05-15a7501c6b8c-annotated_acb7412f-e672-4008-bab7-9359993456b2.png?etag=6d6fb52367d270d54d2c7682e5e7bfa8)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1320x1187
**[Open #269 in Usersnap](https://app.usersnap.com/l/feedback/ad0ce5fe-84dd-48d0-9ecf-f940904f8aad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Please test this with #3808 [Carthage deployment](https://dao-git-fork-traumschule-fix-past-elections-3168-joystream.vercel.app/#/election/past-elections) and verify `ended at` block:
`query { electionRounds { cycleId createdAt updatedAt endedAtTime endedAtBlock } }`
```
    "electionRounds": [
      {
        "cycleId": 1,
        "createdAt": "2022-11-10T14:05:48.001Z",
        "updatedAt": "2022-11-25T15:28:00.001Z",
        "endedAtTime": "2022-11-25T15:28:00.001Z",
        "endedAtBlock": 216001
      },
      {
        "cycleId": 2,
        "createdAt": "2022-11-25T15:28:06.000Z",
        "updatedAt": "2022-11-25T15:28:06.000Z",
        "endedAtTime": null,
        "endedAtBlock": null
      }
    ]
```

![carthage-elections](https://user-images.githubusercontent.com/31551045/206608576-8fa0658c-03e7-4f21-892c-6c9a1cdc6a0e.png)

**Comment by thesan** [comment]
I tested it in production with `34.230.5.182.nip.io`:

![Screenshot from 2022-12-20 12-55-05](https://user-images.githubusercontent.com/6571453/208663146-55d80d02-6489-496e-8a75-af68dbd6d6a5.png)


![Screenshot from 2022-12-20 13-06-16](https://user-images.githubusercontent.com/6571453/208663559-4cc16762-64ce-4f59-b624-a212f85fbe57.png)

So I'm closing it for now.
