### ISSUE TITLE
[feature request] Improved thread creation process

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3169]
**Taken at**: https://dao.joystream.org/#/forum/category/11
**Fields**:
- Which feature are you missing?: Improved thread creation process
- What problem would that solve for you?: The current workflow or &#34;performance&#34; as in what happens on screen when creating a thread or post is not very appealing, feels brittle that content could be  lost.
- the sign modal should keep the inserted content visible

- replace &#34;You have successfully created a thread.&#34; popup
- make sure no content is lost on outside click =&gt; ask to leave or auto-save as draft in local storage
- once user decided to create and sign all needed info about the new thread is available to show a solid **preview** of the thread with an indicator that this is a preview and the transaction is about to be verified
- this enables the user to draft a new post in the to be created thread
- Share your Github or Discord so we can get in touch: l1dev

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**[Open #12 in Usersnap](https://app.usersnap.com/l/feedback/9263a3b4-a3b0-4a15-a18c-5e9e325b62a9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
not in scope of #3054 but related. if accepted this would probably require a new design for thread preview or at least how to indicate that display is preliminary until transaction finalizes.

**Comment by dmtrjsg** [comment]
We do have this already in the pipe as part of overall Forum UX facelift:>

https://github.com/Joystream/pioneer/issues/3163
