### ISSUE TITLE
[USERSNAP] Past Councils: "Proposals Rejected" is incorrect

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3177]
**Taken at**: https://dao.joystream.org/#/council/past-councils
**Fields**:
- Houston, we have a problem.: Past Councils: &#34;Proposals Rejected&#34; is incorrect
- Comment: SSIA
Numbers don&#39;t add up.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/790d1c66-c3f3-4615-ae09-0771eb456a53-annotated_2492723e-6745-43e7-8f9a-307280279700.png?etag=0bf98a9811e37b7b0e12e5df76eeadf4)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/790d1c66-c3f3-4615-ae09-0771eb456a53-annotated_2492723e-6745-43e7-8f9a-307280279700.png?etag=0bf98a9811e37b7b0e12e5df76eeadf4)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1547x1194
**[Open #272 in Usersnap](https://app.usersnap.com/l/feedback/51b25331-e8b0-4608-9ffa-b7f404651027?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
lgtm, please verify
https://dao.joystream.org/#/council/past-councils
https://dao.joystream.org/#/council/past-councils/00000001 => Proposals (12 rejected)
![rejected](https://user-images.githubusercontent.com/31551045/205923107-1fd37a39-3628-4d89-9540-e1db60cbefeb.png)

**Comment by ivanturlakov** [comment]
✅ Tested on https://pioneerapp.xyz/#/council/past-councils/00000002

Looks correct to me

<img width="1210" alt="Снимок экрана 2023-01-27 в 14 46 34" src="https://user-images.githubusercontent.com/46903215/215092701-c6cf79a8-4823-4f00-9f57-ddb98f42a059.png">

### Approved=38 Rejected=12
### Quantity as per the list below

<img width="1210" alt="Снимок экрана 2023-01-27 в 14 58 29" src="https://user-images.githubusercontent.com/46903215/215092709-aa1b90f7-f432-49b8-8f82-0f96c4bcfcac.png">
