### ISSUE TITLE
[USERSNAP] Forum: Unable to reply to thread

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3191]
**Taken at**: https://dao.joystream.org/#/forum/thread/197
**Fields**:
- Houston, we have a problem.: Forum: Unable to reply to thread
- Comment: SSIA
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c9219540-fd0a-4a24-8456-6724878b9481-annotated_49169fe0-19da-479a-a628-094ecbb4f323.png?etag=17baaf4159f39a315aa6e45e6d452178)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c9219540-fd0a-4a24-8456-6724878b9481-annotated_49169fe0-19da-479a-a628-094ecbb4f323.png?etag=17baaf4159f39a315aa6e45e6d452178)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1319
**[Open #275 in Usersnap](https://app.usersnap.com/l/feedback/2d9a3788-a6cc-4f40-acf0-b9235b3cf7d0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
Thanks to @freakstatic for noticing this:

it has the status
`ThreadStatusRemoved`

**Comment by dmtrjsg** [comment]
This thread was removed hence one cannot reply to such a thread.
