### ISSUE TITLE
We need thumbnails to show up when sharing on Social Media

### ISSUE THREAD

**Issue by Delranchorecipes** [Joystream/pioneer#3202]
When I try to share Joystream video links the thumbnails don’t show up. They only show half the time on facebook and 0% of the time on other social platforms where I share them.  Pinterest, google search, reddit, etc.

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/atlas #2828](https://github.com/Joystream/atlas/issues/2828) via [**ZenHub**](https://www.zenhub.com/)
