### ISSUE TITLE
Remove network name from the blockheight widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3203]
## Scope
* [ ] Remove Network name from this widget  from all places in the app
* [ ] Currently widget used on Forum

![Screenshot 2022-06-08 at 16.12.48.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/81218492-9063-4ad6-a0f9-f0d0b7448daa)

## Technical Guidelines
A good start would be to delete `NetworkType` from [@/common/types/Block.](https://github.com/Joystream/pioneer/blob/4253b73a6e7493cf90c7b030c23561941649ea58/packages/ui/src/common/types/Block.ts) and removing `network` from all the `queries/xxx.graphql` files, and then removing the network fields by following all the typescript errors.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202444165016487) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@thesan can you hide this behind a flag and create a ticket to show it once we are on mainnet? I think we should not release it with "Mainnet" before it actually happens as users will get confused ..

**Comment by polikosi** [comment]
Verified on https://dao-5i7qbhq9l-joystream.vercel.app/#/profile.
Network name is hidden.

Member profiles:
![Screenshot_145](https://user-images.githubusercontent.com/80429191/178809229-08cc0a94-f2c9-44b1-a1c4-6f6d874297c0.png)


Forum thread header and replies:
![Screenshot_150](https://user-images.githubusercontent.com/80429191/178809090-4814ccd7-c927-4300-b752-3c617a8495f5.png)

Application:
![Screenshot_147](https://user-images.githubusercontent.com/80429191/178808774-5cc5c922-f41f-4a2e-ab1d-eda7e55b56c9.png)

Openings:
![Screenshot_148](https://user-images.githubusercontent.com/80429191/178808641-fdd33e0c-443a-4a8e-ac8a-6018edf10ba5.png)

Bounty:
![Screenshot_149](https://user-images.githubusercontent.com/80429191/178808560-21dbb147-d8a6-4c49-88a3-6860ae7affd8.png)

**Comment by polikosi** [comment]
tested on staging. Network name is hidden.
