### ISSUE TITLE
Proposal to only update min/max cashout limits

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3208]
![](https://user-images.githubusercontent.com/93924525/172807512-f6827cff-751a-43c2-8359-1a7cdf809948.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202419262938520) by [Unito](https://www.unito.io)

**Comment by MattAugustynowicz** [comment]
[👉 Figma Link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9741%3A372154)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/b73cc5ef-6e57-472b-9fd8-c863f2afc163)

**Comment by bedeho** [comment]
Please confirm whether there is actually a distinct proposal for this, my memory is that there is just one "mega" proposal that allows the council to simultaneously chose whether to update, or not, the full suite of variables associated with payouts, including the payout Merkle root itself, but there is a least a 22% chance I am wrong.

**Comment by dmtrjsg** [comment]
@bedeho we did not build it just yet.. the way it was designed that min/max can be updated via the "mega' proposal flow as the only params, but smth tells me there was a specific request to ONLY update min/max. It's not too late to just skip this task as we have not started yet in Pioneer, still awaiting QN side full review and merge..

**Comment by bedeho** [comment]
>  the way it was designed that min/max can be updated via the "mega' proposal flow as the only params

Why? that is just redundant, because sometime you will want to do both at the same time, so just the one proposal with everything configurable would cover all bases.

**Comment by dmtrjsg** [comment]
Sure thing!

**Comment by dmtrjsg** [comment]
Ok just confirmed :) closing this issue as such 👍
