### ISSUE TITLE
 Talisman Wallet / Signer Designs

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3212]
## Context
Originating Issue

* https://github.com/Joystream/atlas/issues/1971

Atlas Design ticket:

* https://github.com/Joystream/atlas/issues/2817

:art: [Figma link:](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in?node-id=511%3A56665)

Spike: - https://github.com/Joystream/pioneer/issues/3239

:information_source:  Product Website: https://talisman.xyz/

## Scope
* [ ] Design adaptation to make Pioneer work with Talisman or Polkadot Wallets

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202420568577596) by [Unito](https://www.unito.io)

**Comment by MattAugustynowicz** [comment]
[👉 Figma Page here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9876%3A383547)

We changed the first screen showing three specific wallets and updated the message + we're changing the CTA from "join us" to "connect wallet."

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/35e6e849-dd8f-4466-af02-f671b9b82c41)

When we select one of the visible CTAs, a modal opens with the list of plugins. We see the "Install plugin" button if we don't have the extension. If the plugin is installed, the CTA changes to "Select Wallet."

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/75606723-dd4c-4d63-915d-fe269dc21739)

After selecting the installation of the plugin, we go through the process dedicated to a particular wallet, which usually takes place in a new tab of our browser.

Then we see a screen that prompts us to create an account at this point + several screens with validation of the plugin - the user could have rejected the plugin at the very beginning. We will then show a text about turning it on, or as other plugins allow us to do, such as Talisman - directly click on the link and go to the appropriate screen. The scenarios were covered in the Figma file and described with comments.

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/39eb1bfa-957f-4205-a1ac-c07d1b686903)

The next step is to connect the account (where only the copy was changed) + the membership creation screen.

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/c6933e51-8595-4f04-b16a-7a5fe59df9cc)

The final part of this shuffle is how the platform behaves once logged in. At this point, we can either disconnect the wallet or change it directly. Adam noted that the first option would be much better, so I'm leaning towards that while I'm leaving both versions in Figma for possible later business decisions.

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/f4ed4ba1-317e-48e3-b397-922bbb81cdf9)

**Comment by dmtrjsg** [comment]
@toiletgranny the very first issue from Pioneer for your capable hands :) 

We'd need to update the onboarding flow modal served to users w/o connected wallet based on the comment below:

 About the flow, Atlas don’t have the same issue as we do, since they first make user pick a wallet before deciding whether to take them through onboarding or just login as normal user.  I would be behind doing the same for Pioneer. RN it’s already done (when user visit page, there is Connect Wallet button, after selection if user don’t have acc/member, onboarding will show with adequate step). If you agreed with me, I believe that only thing left to handle is wallet disconnect CTA and removing install wallet step from onboarding.

**Comment by toiletgranny** [comment]
@dmtrjsg @stepien4soft, guys, my apologies, I thought I got it at the end of our Friday afternoon call, but, honestly... the more I look at the designs and messages from Radek, the more I'm getting back to where I started, meaning: I can't understand what seems to be the problem and why can't this be implemented the way Matt had prepared it.

Instead, while reviewing the designs, I started having doubts about other unrelated parts of the flow. So I left two questions for you in Figma.

---

I don't want to waste any more time staring into the screen and hoping for the "aha" moment to come in, reviewing everything repeatedly. So how about this:
1. @dmtrjsg, can I ask you to share your entire conversation with Radek with me? The snippet you pasted above and the other one I got on Slack from you seem to be missing something in-between (maybe I'm wrong). Perhaps if I could look at your entire uninterrupted conversation, this may help me connect the dots in my head.
2. @stepien4soft, let me have a weekend to clear up my head and start fresh on Monday. How about you and I sync again sometime before noon if you're available? 10:30, 11 AM?

---

Also, @dmtrjsg, you asked me to see if it's possible to bring this experience more closely to what we just did in Atlas. This is certainly possible but would require redefining the Pioneer sing-in flow from scratch, I'm afraid. I'm thinking of 1-2 days of work, including the review process in-between and dev handoff. Now, knowing that some amount of time and effort already went into preparing this (both design and development, as we learned earlier today) and that there are other things on our plate before the main net, I'm not sure if this is something you'd like us to do right now. If so, please let me know, and I'd be more than happy to do it.

**Comment by dmtrjsg** [comment]
@toiletgranny thanks for sharing.

My thinking was very simple (and I think it is okay to show the onboarding modal for all users whose wallet is not connected). I think it is important to entice users to do it with explanation of benefits so the changes from Matt's designs can be minimal, namely:

1. The modal will be shown to all users whose wallet is not recognised (even if they have had an account before, but it is disconnected)
2. CTA on the modal would be Connect Wallet 
3. The first step would also be called connect wallet (if connected, this would be shown as completed)
>right now it says install polkadot extension
4. CTA from the modal would need to summon the wallet selection menu
5. Pls update the style of the action points in the wallet to look a little less crude (only if its is a quick work)
____

Conversation with Radek:

<img width="584" alt="Screenshot 2022-06-24 at 15 42 01" src="https://user-images.githubusercontent.com/93924525/175559447-2caaa5ee-3ce4-4336-9831-af3b592a70f1.png">
<img width="576" alt="Screenshot 2022-06-24 at 15 43 10" src="https://user-images.githubusercontent.com/93924525/175559451-bd5e3c98-1d58-400d-b745-680a57741793.png">
<img width="599" alt="Screenshot 2022-06-24 at 15 43 21" src="https://user-images.githubusercontent.com/93924525/175559456-6fc4f802-c288-4325-bab5-c9b511456775.png">

**Comment by toiletgranny** [comment]
Dima, just so you know, I can't change this issue's assignee or the column, so I'd kindly ask you to do that for me when you have a moment. 🙏

**Comment by dmtrjsg** [comment]
Agreed to corrections:
- Static overlay on top of the screen for not-signed in users, stepper flow only shows in the flow modals
- Extension blocking the app must be shown on step 2
- Welcome back toaster shown to users, whose account is saved in local storage
<img width="553" alt="Screenshot 2022-07-08 at 12 09 19" src="https://user-images.githubusercontent.com/93924525/177981192-134b75db-83e9-4a30-a88e-36e0e9e54ada.png">
- Only disconnect wallet will be implemented, change wallet not required

ℹ️ for QA
NB: design flow in the bottom of the Figma page is missing stepper indication, this is incorrect 🔴 :
<img width="238" alt="Screenshot 2022-07-08 at 12 10 48" src="https://user-images.githubusercontent.com/93924525/177981391-d4adafeb-e789-47bd-b331-b92ec43417f4.png">

All modals shown with the progress bar component ✅ :
<img width="464" alt="Screenshot 2022-07-08 at 12 11 12" src="https://user-images.githubusercontent.com/93924525/177981422-d16457c6-bce0-4d47-b846-1bdec0ec8a73.png">
