### ISSUE TITLE
Forum: Tx progress on post/ thread updating 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3224]
## Scope
* [ ] Show the bottom right modal with tx progress when updating post / thread

NB: Waiting times on categories/ threads pages will be reduced as a product of UX pages revamp

### Out of scope:

* Polling is covered ina. diff ticket
* Caching is done already
* #3029 will make all pages load faster

### Context
- - -
**Taken at**: https://dao.joystream.org/#/forum/thread/242
**Fields**:

* Which feature are you missing?: Forum waiting times
* What problem would that solve for you?: The overall experience in the forum is still a bit bumpy or at least slowed down
* waiting time when opening forum to see all categories
* waiting time on every category and thread
* waiting time when posting or editing a page to click `Sign and Submit`
* when updating an existing post the `Save` button lacks indication that it is being save like `Saving ..` or `Signing`
Pioneer1 had long waiting times too and was solved with caching. The forum structure can be fetched once, saved to local storage and updated based on timestamp or actual chain events.
* Share your Github or Discord so we can get in touch: l1dev

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**[Open #19 in Usersnap](https://app.usersnap.com/l/feedback/158aa5fa-7409-464f-9d63-43a879737c42?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202464662586045) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@traumschule thanks for raising, we will add this to the Forum UX facelift epic.

**Comment by singulart** [comment]
@dmtrjsg The description is a bit unclear. How does this relate to the forum thread cited?

**Comment by dmtrjsg** [comment]
@singulart 

Thank you for asking, indeed there was a typo in the scope section.. When we triaged it, it seemed like the only part that was missing is the transaction progress indicator modal, that is shown in the bottom right corner of the transaction as other points are covered by different issues. I think this should be done / checked in the very end of the module redesign, as improved page structure should also increase the speed of page load.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

Works as expected

https://user-images.githubusercontent.com/46903215/205016937-c4e9e95c-f14b-4ec7-9d3b-f89cf7b0d5bd.mov

<img width="1209" alt="Снимок экрана 2022-12-01 в 11 29 42" src="https://user-images.githubusercontent.com/46903215/205017023-efb111e7-7bad-403d-ba26-5e39421ae888.png">
