### ISSUE TITLE
[USERSNAP] Past Councils > Working Groups: all data is wrong

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3225]
**Taken at**: https://dao.joystream.org/#/council/past-councils/0000000a
**Fields**:
- Houston, we have a problem.: Past Councils &gt; Working Groups: all data is wrong
- Comment: SSIA
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/efd1c1b2-6984-46ab-b230-80575b8c673d-annotated_12a2b2ea-dd96-46b6-a9b8-fc2842411f45.png?etag=26089cfb927f671bae2cd670193f6f78)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/efd1c1b2-6984-46ab-b230-80575b8c673d-annotated_12a2b2ea-dd96-46b6-a9b8-fc2842411f45.png?etag=26089cfb927f671bae2cd670193f6f78)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1556x1206
**[Open #276 in Usersnap](https://app.usersnap.com/l/feedback/ace8b081-914a-4365-9a8b-0b9579887c24?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by chrlschwb** [comment]
Is this issue still standing?

**Comment by ivanturlakov** [comment]
Tested on https://pioneerapp.xyz/#/council/past-councils/00000003
Mainnet

@chrlschwb Looks like still standing
Pls check this screen(BWG stats)
Looks wrong to me
BTW the last two columns always = 0

<img width="1211" alt="Снимок экрана 2023-02-02 в 14 12 54" src="https://user-images.githubusercontent.com/46903215/216321973-8af8cfc3-c14c-4760-9c05-e2a049132564.png">
