### ISSUE TITLE
Incorrect display of comments in a proposal

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#3236]
## Scope

- [ ] Use block count for sorting

 ⚠️ if this fails then the issue is with Hydra - post the results of attempt to comments
__________

During the discussion it was possible to find out that the proposal does not correctly display more than 15 comments - https://dao.joystream.org/#/proposals/preview/274

The 16th comment moved up the discussion. You can see from the time in the screenshot that it is located incorrectly
![image](https://user-images.githubusercontent.com/84832436/173680270-5512977b-3af3-4443-8cd7-4fe41bca7746.png)

**Comment by ivanturlakov** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/#/proposals/preview/41
wss://34.230.5.182.nip.io/ws-rpc

Got an error while adding 2nd comment (after transaction execution)
<img width="1439" alt="Снимок экрана 2022-12-08 в 12 32 25" src="https://user-images.githubusercontent.com/46903215/206425457-f3aa3030-fdd9-415d-87ed-ec5e85a2fe4e.png">

**Comment by thesan** [comment]
@ivanturlakov  this should be fixed by #3965

**Comment by ivanturlakov** [comment]
✅ Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/#/proposals/preview/47
wss://34.230.5.182.nip.io/ws-rpc

For sorting used a blocks counter
⚠️ The latest comments are on top of the list

<img width="923" alt="Снимок экрана 2022-12-10 в 12 59 22" src="https://user-images.githubusercontent.com/46903215/206851805-a5f2137c-586e-4c51-97a3-9023643451b4.png">

**Comment by traumschule** [comment]
> The latest comments are on top of the list

Do you think that should be changed?

**Comment by ivanturlakov** [comment]
> Do you think that should be changed?

No, just noticed that the display chronology was changed. I think this is a subjective thing and the community will let us know if anything needs to be changed 👍
