### ISSUE TITLE
Create a separate storybook  FEES component (fee + tootip) 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3240]
## Context

- https://github.com/Joystream/pioneer/issues/2898
- https://github.com/Joystream/pioneer/issues/2531

## Scope

Mirror this implementation: 
- https://github.com/Joystream/atlas/issues/2277

- Design Fees component to be included to transaction signer and to footer of all modals with user inputs
- Fees shown in JOY. For small fees < 0.01 JOY, we show "< 0.01 JOY"
- On hover tooltip shows

**Comment by MattAugustynowicz** [comment]
[👉 Figma Link here](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9966%3A406759)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/7a6a8aa8-5c1c-4f8c-b0aa-f04af250a670)

![image.png](https://images.zenhubusercontent.com/61f04aadb8abb13c0fc2e178/cbaebef7-6c28-4efc-94bd-ac4d1abc6e7d)
