### ISSUE TITLE
[USERSNAP] Validation error when editing a membership

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3243]
## Scope

Update validation checks on membership handle
- [ ] Check handle availability with QN before throwing error

## OUT OF SCOPE
- [ ] #3263

This modal was addressed in this PR: 
- https://github.com/Joystream/pioneer/pull/3088

______

**Taken at**: https://dao.joystream.org/#/profile/memberships
**Fields**:
- Houston, we have a problem.: Validation error when editing a membership
- Comment: I wanted to edit my membership, but whatever new handle I would type in, the app would always reject it saying it&#39;s already taken, when I&#39;m sure it isn&#39;t
- Feedback: Klaudiusz

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/03701bff-1187-4498-b4fe-89d4f29646c3-annotated_8bf42355-c99a-4dca-a4e2-4aec23961480.png?etag=e9fa01b3eb278a3d020bc4652c94629b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/03701bff-1187-4498-b4fe-89d4f29646c3-annotated_8bf42355-c99a-4dca-a4e2-4aec23961480.png?etag=e9fa01b3eb278a3d020bc4652c94629b)*

**Browser**: Chrome 102 (macOS Catalina)
**Screen size**: 1728x1117
**Browser size**: 1670x976
**[Open #279 in Usersnap](https://app.usersnap.com/l/feedback/ccc928c3-94c7-491c-b605-43faec488dc5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
Tested on staging.

Membership handle availability check works well

https://user-images.githubusercontent.com/46903215/174583368-66f776d0-36a9-4419-9f9b-031b6dd50343.mov

Spaces and special characters are still acceptable

https://user-images.githubusercontent.com/46903215/174585221-305f8d0c-e47a-49e7-9bfe-2fa65c5064bb.mov
