### ISSUE TITLE
Incorrect display of subcategories in the forum

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#3245]
## Scope
- [ ] Move the date stamp a few PX above so that the text does not overlap with the long string in the bottom of this card

## Context
![image](https://user-images.githubusercontent.com/84832436/173929616-ff4e14ba-7c7c-47f8-971f-7f62ebf97751.png)
It looks a little blurry. I think you should increase the distance a little bit.

**Comment by dmtrjsg** [comment]
Cancelling since Forum is redesigned now and awaiting dev
