### ISSUE TITLE
Loss of tJOY in the application

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#3251]
## Scope

- [ ] Fix recovering the role staking after role was closed via proposal. 

Add a button to "recover lock" and follow the general designs for it

Out of scope:
- [x] Fix showing past openings closed via proposal. Opening that was closed via proposal is missing in the openings history of given WG. (resolved in -https://github.com/Joystream/pioneer/issues/3348)

## Context

There have been complaints from users that their tJOYs are missing somewhere in the staking.
https://discord.com/channels/811216481340751934/812345044094156811/984719368673976350
https://discord.com/channels/811216481340751934/815192060276506664/984516585404366898

And today the consuls were recreating the openings for the group leaders' positions. 
The opening had application from user. One user wrote back that he did not get tJOY back after closing the opening through proposal. The tokens are considered blocked in the wallet.
Also, the opening that was closed to the councils through proposal does not appear in the history of the group openings.

**Comment by traumschule** [comment]
are the tokens burned or locked? a screenshot or wallet address would help to debug.

**Comment by adovrodion** [comment]
> are the tokens burned or locked? a screenshot or wallet address would help to debug.
@traumschule 
![image](https://user-images.githubusercontent.com/84832436/174251717-6b77d658-9af9-453b-8efa-cdc065f0b035.png)

5FdtkcMwGtPWH7bX7tLto39SxTG5zwyxBCXfXcmFHykCHp74
5D5K5fmQoxC2aubHM7DwPUntHEEJvdkprDwPxicbDJbcvxMF

**Comment by dmtrjsg** [comment]
@thesan to check if there is an extrensic to recover apply on opening stake for this action..

**Comment by dmtrjsg** [comment]
@adovrodion do we have any info on what specific role was cancelled via proposal?

**Comment by adovrodion** [comment]
@dmtrjsg This openings:
https://dao.joystream.org/#/working-groups/openings/operationsWorkingGroupGamma-6 
https://dao.joystream.org/#/working-groups/openings/contentWorkingGroup-12

**Comment by dmtrjsg** [comment]
When someone applies to application and application is cancelled via proposal - runtime does not pick it up and staking amount gets locked for eternity. Reclaim staking amount exrensic does not exist, so is not supported for the working groups. 

There is only withdrawal of the application, but if the application is closed it is unclear how this can be done. Our (pioneer team) assumption is that staking needs to be automatically returned. 

Right now user can only withdraw application for the active opening. 

Action: we need to test if application can be withdrawn for the closed opening. And adjust FE if that resolves it. 

To be continued.

**Comment by adovrodion** [comment]
@dmtrjsg Is there anything I can do to help at this stage? We would like to return the tokens to the users as soon as possible

**Comment by traumschule** [comment]
The remaining scope here is to withdraw stakes for closed openings. WDYT about a recover button near the stake field on `ApplicationsList`?
```
<OpenItemSummaryColumn>
          <TextInlineBig>
            <TokenValue value={application.stake} />
            {isRecoverable && <RecoverButton memberId={memberId} lock={lock} address={address} isRecoverable={true} />}
          </TextInlineBig>
          <Subscription>Staked</Subscription>
        </OpenItemSummaryColumn>
```

**Comment by dmtrjsg** [comment]
@traumschule let's go with this! I think we can try and go without design based on common understanding and reusing some of the patterns that already exist..  I we can then review the PR on preview branch and curate from there 👍

**Comment by dmtrjsg** [comment]
Adding to community pipeline now..

**Comment by thesan** [comment]
Just to keep track of the code most of this feature was implemented in #3671

@traumschule would removing the `!past` in [@/working-groups/components/ApplicationsList.tsx:98](https://github.com/Joystream/pioneer/pull/3671/files#diff-8ae3c0d7a70d8bdabe946ed0ccaeab41843614c22c68484017def470e098ef08). Solve the use case you're referring too ?

**Comment by polikosi** [comment]
tested on https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://3.92.226.32.io/network/config.json

Apply to opening
![image](https://user-images.githubusercontent.com/80429191/200587221-9861366f-e9c2-4275-9a1a-522432e0c1e2.png)
[TX](https://polkadot.js.org/apps/?rpc=wss://3.92.226.32.nip.io/ws-rpc#/explorer/query/0xb1143b6373e30416e6763bae943f670e50b1355661da772f5e1054934ad0139a)

Locked balance for this opening
![image](https://user-images.githubusercontent.com/80429191/200588151-8c09b1cd-e043-416c-a280-be2839246860.png)

Voted for the proposal to cancel the application
[TX](https://polkadot.js.org/apps/?rpc=wss://3.92.226.32.nip.io/ws-rpc#/explorer/query/0x0de68ecd87d8f88b22fc62aeaf7f8ee4444c660d431c4a24a63f42ef9cb7f9c2)

After canceling the application, I cannot withdraw the stake, it is locked

https://user-images.githubusercontent.com/80429191/200589294-1e044fc3-4aed-4bf0-9d95-b231b27de710.mp4

**Comment by polikosi** [comment]
apply to forum worker (candidate-8, candidate-9)
![image](https://user-images.githubusercontent.com/80429191/205736531-ae561969-9721-4792-a891-13285a9cd2f9.png)
Hired candidate-8 to forum worker
![image](https://user-images.githubusercontent.com/80429191/205736000-0d10a49a-0e89-4f2e-8dfe-fba5ed301e89.png)
candidate-9 can't withdraw the stake
candidate-8 can withdraw the stake
![image](https://user-images.githubusercontent.com/80429191/205736398-163cc05f-b954-4698-821b-8a27233989f8.png)
