### ISSUE TITLE
[Crash] Submitting an application to a curators opening it's showing a blank page  

### ISSUE THREAD

**Issue by freakstatic** [Joystream/pioneer#3254]
When applying to the opening of the curators group ID: 15 a blank page is displayed in the last modal step

Console error:
![image](https://user-images.githubusercontent.com/7486476/174273641-820cf6bf-50f6-4075-9f37-57207a872c44.png)
![image](https://user-images.githubusercontent.com/7486476/174278337-babc65b9-3640-4bd6-8ea9-42ca21361eb6.png)

https://dao.joystream.org/#/working-groups/openings/contentWorkingGroup-15

**Comment by freakstatic** [comment]
also I'm not sure if this should be empty
![image](https://user-images.githubusercontent.com/7486476/174274668-36da3ba5-4d59-473c-9602-cae9bbf62654.png)

**Comment by traumschule** [comment]
i asked the lead - questions were left out intentionally, just seems pioneer doesn't expect that?

**Comment by dmtrjsg** [comment]
@WRadoslaw pls look into this one as a high-prio..

<img width="759" alt="Screenshot 2022-06-20 at 10 44 56" src="https://user-images.githubusercontent.com/93924525/174574669-dc27a7af-e880-44d1-bdf6-7ccb3a91530c.png">
