### ISSUE TITLE
Going back to the "Applying for role" previous step disable the "Next Step" button

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3255]
The "Next Step" button is re-enabled once a field get unfocused (i.e `onBlur`).
This will become a problem after #3249 (the PR for #2445) gets merged

**Comment by polikosi** [comment]
verified on staging. test evidence below:

https://user-images.githubusercontent.com/80429191/175606754-dce3f99d-7fbb-4558-8b94-22da0cc23982.mp4
