### ISSUE TITLE
[USERSNAP] I didn't get my NFT sale payment on Atlas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3258]
**Taken at**: https://play.joystream.org/video/26854
**Fields**:
- Houston, we have a problem.: I didn&#39;t get my NFT sale payment on Atlas
- Comment: I sold an NFT on 14th of June priced 1M tJOY but i didn&#39;t get the payment. It has been 5days. I mantioned it on the discord &#34;bug channel&#34; and they said this is a bug they seen for the frist time to be refunded by Martin. 
My polkadot Adress : 5Dh8Lw11DPxmVE5GsFFoBvBHU7XFkdoLh2MzuoK5Sh6r9Aws
- Feedback: Ömer_ÖzdemirTR#5183

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0b1af04c-5533-4b41-b905-0390c3b38179-annotated_3c51acb1-5c02-4b64-933c-b67f9d671e1c.png?etag=251b13f8416c048a4cad39af17e42c71)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0b1af04c-5533-4b41-b905-0390c3b38179-annotated_3c51acb1-5c02-4b64-933c-b67f9d671e1c.png?etag=251b13f8416c048a4cad39af17e42c71)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x722
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/a3f16313-3a71-4a24-8c6f-f6d8cedfd026_screen_recording_7ded5de8-08a4-47ba-8788-a2286b7d5abb.webm?etag=202eb44247c4b42492a07cc4e46bbb96-2)**
**[Open #283 in Usersnap](https://app.usersnap.com/l/feedback/56c1cfa3-58dc-479e-b699-9d18f4e594a5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@bwhm FYI am closing this issue since all relevant comms were done on Discord.

**Comment by bwhm** [comment]
The screenshot is slightly misleading, as the video id for the NFT is not [26854](https://play.joystream.org/video/26854), but:

```
videoId / nftId: 26856

issued NFT (VideoUpdated): #1134267
for sale: (NftSellOrderMade): #1134304
sold: #1180147
```

3% (30k) was paid to creator as royalty, the rest was burned...

Sending 970k to the account!

**Comment by bwhm** [comment]
https://polkadot.js.org/apps/#/explorer/query/0x7ea80df2a4c13a8734d92f2f52a5cc6a569f075fdf77e61047035c386a6019d8
