### ISSUE TITLE
Add validation "Spaces and special characters are not supported"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3263]
## Context
https://github.com/Joystream/pioneer/issues/3243

## Scope

- [ ] Add validation "Spaces and special characters are not supported" for membership handle create/update.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/profile/memberships
wss://34.230.5.182.nip.io/ws-rpc

⚠️ Edit membership Modal: Spaces and special characters are still acceptable

https://user-images.githubusercontent.com/46903215/204344841-035b93ea-7f15-43f9-a9c7-ad28165d5ac6.mov

**Comment by traumschule** [comment]
Looks like the [pattern](https://github.com/Joystream/pioneer/pull/3809/files#diff-e35b4cf2f7bc578a0885b19d7589d929f60454c51f7e36145b7bdce93a7b45d1R75) `/^[a-zA-Z0-9_.-]*$/` is not strict enough and allows whitespaces.

**Comment by traumschule** [comment]
Closing as complete, tested on https://pioneerapp.xyz and 
https://dao-git-dev-joystream.vercel.app.
