### ISSUE TITLE
Delete and Edit buttons are shown on removed thread pages

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3266]
The delete and edit button still show on `ThreadStatusRemoved` threads. Clicking them results in a failed transaction

These button also incorrectly show when the thread creator is not selected. See https://github.com/Joystream/pioneer/issues/2817#issuecomment-1163133211

https://user-images.githubusercontent.com/46903215/175046190-bf14410f-46a4-40df-81c1-596f09bfc4b1.mov

**Comment by gyroflaw** [comment]
Please assign this task to me.

**Comment by gyroflaw** [comment]
Hi @singulart , I reproduce the process, but the error you mentioned wasn't occurred, please check https://www.loom.com/share/29e3ce8f7769472998be641938aa23bf.

**Comment by singulart** [comment]
@gyroflaw I think you need to check this with **two** different use accounts!

**Comment by gyroflaw** [comment]
I just created PR, please check https://github.com/Joystream/pioneer/pull/3630
@singulart

**Comment by dmtrjsg** [comment]
@gyroflaw  Here I am a little confused as to what was done/ attempted?

Currently the delete button still shows on the thread next to the title, which when clicked results in the error. At the same time the first post cannot be deleted. 


<img width="1396" alt="Screenshot 2022-10-17 at 16 59 54" src="https://user-images.githubusercontent.com/93924525/196183798-be2bb674-53da-4c42-a4fd-45b1862eea8a.png">
<img width="951" alt="Screenshot 2022-10-17 at 16 59 56" src="https://user-images.githubusercontent.com/93924525/196183810-703f6f19-4baf-4308-862f-dcf95e5bf726.png">


@thesan can you advise on why it is not possible to delete the first post?

**Comment by gyroflaw** [comment]
I will take a look of this issue
