### ISSUE TITLE
Wrong group names

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3268]
## Scope
- [ ] The correct implementation was done in  [packages/ui/src/common/helpers.ts](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/common/helpers.ts#L25); function called `nameMapping`, we need to do the same in the other files

Expected result:
- more DRY code
- `operationsWorkingGroupBeta` resolves to "HR"
- `operationsWorkingGroupGamma` resolves to "Marketing"
- `#/working-groups/operationsWorkingGroupAlpha` re-routes to `#/working-groups/builders` (and analogues)

Supported routes:
- /#/working-groups/openings/apps-0
- /#/working-groups/openings/gatewayWorkingGroug-0 => `apps-0`
- /#/working-groups/openings/builders-0
- /#/working-groups/openings/operationsWorkingGroupAlpha-0 => re-routes to `builders-0`
- /#/working-groups/openings/hr-0
- /#/working-groups/openings/operationsWorkingGroupBeta-0 => `hr-0`
- /#/working-groups/openings/marketing-0
- /#/working-groups/openings/operationsWorkingGroupGamma-0 => `marketing-0`

## Context
Found 3 files where Marketing (Beta) and HR (Gamma) are swapped. Also note wrong Builders in `locks.ts`.

Looks like the error was introduced in https://github.com/Joystream/joystream/issues/3119
Corrected in https://github.com/Joystream/joystream/pull/3136#issuecomment-1033595381 (see [Sumer KPI: 38.III-1 New Working Groups](https://blog.joystream.org/sumer-kpis/#38.III-1))

https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/working-groups/model/workingGroupName.ts
      case 'hr':
        return 'operationsWorkingGroupBeta'
      case 'marketing':
        return 'operationsWorkingGroupGamma'

https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/common/helpers.ts#L44
case 'Operations Beta':
      return 'Human Resources working group is responsible for integrating new members greeting, onboarding, catalyzing and nurturing, as well as managing bounties.'
    case 'Operations Gamma':
      return 'Marketing group is responsible for increasing the outreach, sharing the content from the platform with the world, spreading the news about platform development, new members acquisition and overall growth.'

https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/working-groups/types/locks.ts
  operationsWorkingGroupGamma: 'Builders Worker',
  operationsWorkingGroupBeta: 'HR Worker',
  operationsWorkingGroupAlpha: 'Marketing Worker',

**Comment by adovrodion** [comment]
Bounty was created: https://dao.joystream.org/#/bounty/preview/133

**Comment by dmtrjsg** [comment]
@traumschule pls assign to qa 

cc @polikosi @ivanturlakov

**Comment by ivanturlakov** [comment]
Pls, elaborate on what testing scenario should be used here. 
Also cant reach testing env https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://54.163.55.37.nip.io/network/config.json
=> We’ll be right back!

**Comment by traumschule** [comment]
This needs work. I updated the description a few days back to change current behavior (re-labeling) to re-route long chain section to public descriptor. Disregard if you think it's fine. Sorry for the delay!

**Comment by ivanturlakov** [comment]
#3957

**Comment by traumschule** [comment]
Closing as duplicate, JSG will take care of it.
