### ISSUE TITLE
Vote for council modal. Add validation error msg. 

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#3270]
## Scope
- [ ] Display the validation error on staking amount field. "Insufficient amount on the selected account. Choose different account, or reduce the staking amount."

## Context

Tested on staging

> We need to show the validation error underneath the account selector "Insufficient funds".

[#2361 ](https://github.com/Joystream/pioneer/issues/2361#issuecomment-1161424863)

https://user-images.githubusercontent.com/46903215/174826176-560e54b4-f9a3-45dc-9261-b52ecfc8d11a.mov

**Comment by WRadoslaw** [comment]
Will be covered by #3319
