### ISSUE TITLE
[feature request] Forum: tooltip to show full thread title

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3273]
## Scope

 - [ ] Truncate thread title after 2 lines 
 - [ ] Show full thread name on hover over on title in the tooltip
 
## Guidance

 > "Radosław" add this line of code to the title component for truncation:
truncateLines={2}

## Context

**Taken at**: https://dao.joystream.org/#/forum/category/11
**Fields**:
- Which feature are you missing?: Forum: tooltip to show full thread title
- What problem would that solve for you?: Can&#39;t see full thread titles, want to hover mouse and see the full thread title.
- Share your Github or Discord so we can get in touch: tomato#9464

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 3440x1440
**[Open #22 in Usersnap](https://app.usersnap.com/l/feedback/21b38c92-781e-4fc1-9ed0-063bb3394674?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203239316151657) by [Unito](https://www.unito.io)

**Comment by adovrodion** [comment]
Bounty was created: https://dao.joystream.org/#/bounty/preview/159

**Comment by traumschule** [comment]
@mkbeefcake please check this one

**Comment by polikosi** [comment]
tested on https://dao-git-fork-mkbeefcake-fix-tooltipshowthreadtitle-joystream.vercel.app/#/forum/category/1
✅
![image](https://user-images.githubusercontent.com/80429191/199026205-7e8bb637-9f8b-4630-af5f-b00996821a44.png)

**Comment by traumschule** [comment]
(would assign @mkbeefcake but lack permission. @dmtrjsg @mnaamani)
