### ISSUE TITLE
Fix LockTimeRecovery

### ISSUE THREAD

**Issue by RafalPloszka** [Joystream/pioneer#3276]
Scope:

- [ ] Fix CouncilorLock time in voting period
- [ ] For Proposals: copy logic from Proposal details page
- [ ] Do not show (or should it be recoverable?) recovery time for Closed opening - fix for both recovery time and on the opening page

**Comment by dmtrjsg** [comment]
@RafalPloszka closing this ticket for the follow up PR raised against original ticket - https://github.com/Joystream/pioneer/issues/3109
