### ISSUE TITLE
Harcoded value in `@/memberships/components/MemberProfile/MemberRoleToggle.tsx`

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3287]
The value of "Earned in 24h" in [@/memberships/components/MemberProfile/MemberRoleToggle.tsx#L76](https://github.com/Joystream/pioneer/blob/f5d7b3d140e9fde9be0141556f83f48717b8293a/packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx#L76) is harcoded.

_Originally posted by @thesan in https://github.com/Joystream/pioneer/pull/3265#discussion_r905960783_

**Comment by dmtrjsg** [comment]
Already fixed with reduced function that is calculating it
