### ISSUE TITLE
[USERSNAP] "Add proposal" button is being hidden

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3294]
**Taken at**: https://dao.joystream.org/#/proposals/current
**Fields**:
- Houston, we have a problem.: &#34;Add proposal&#34; button is being hidden
- Comment: Even with a council member account selected the &#34;add proposal&#34; button disappears after the page loads
- Feedback: freakstatic#0197

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/11f8f764-9f79-4570-9fc5-87ec7701b11d-annotated_f54a46a1-958f-4afa-9a0f-61c766026725.png?etag=e8a5c13409def1c2b992f48a93bf1cc5)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/11f8f764-9f79-4570-9fc5-87ec7701b11d-annotated_f54a46a1-958f-4afa-9a0f-61c766026725.png?etag=e8a5c13409def1c2b992f48a93bf1cc5)*

**Browser**: Chrome 102 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1244x1324
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/0bb62fdc-4044-4ae3-b44f-5514134713b0_screen_recording_2a4e8133-6883-4810-b51d-a77f00fc13d3.webm?etag=e0da9602c162dd9ba9ae24fb127b8313)**
**[Open #289 in Usersnap](https://app.usersnap.com/l/feedback/56617c7c-8d23-4d40-8ced-bdad151dbdb7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
realted to https://github.com/Joystream/pioneer/issues/2787?

**Comment by dmtrjsg** [comment]
@freakstatic and @traumschule is that reproduce-able right now?

Just checked on prod:

<img width="1412" alt="Screenshot 2022-06-27 at 09 26 47" src="https://user-images.githubusercontent.com/93924525/175894855-84a823b7-d935-4701-a48a-4282298ef39b.png">

**Comment by freakstatic** [comment]
@dmtrjsg yeah can't reproduce right now.. could it be related with the election have failed to get applicants? Because I remember that's what happen when the bug appeared
