### ISSUE TITLE
Tooltips on Account Creation - Root and Controller Accounts

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3297]
## Scope
- Update tooltips on root and controller accounts in the create membership flow, and everywhere where they are selected.

![Screenshot 2022-06-27 at 15.20.12.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/6abf33ef-23a4-4ebd-84b3-33bf3f8cfd92)

tootlip for root acc:
Root account is the primary account associated with the membership. It cannot be changed. Root account is used to sign transactions of associating a controller account with the membership. While it is possible to use the same account as Root and Controller, it is not advisable to do so and for security purposes. Best practice is to keep it offline all the time unless your controller is compromise and you need to replace it.

tooltip for controller acc:
Controller account is the account which is used to sign most of the transactions, such as bonding a staking account, posting to forum, creating proposals or making a simple transfer to a different account. Controller account can be changed, and this transaction can only be signed by membership root account.

**Comment by polikosi** [comment]
root account:
