### ISSUE TITLE
Storage of Avatar Images internally (as opposed to asking for URL) 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3299]
## Context
Ensure less friction and better experience for all users, since avatar image via URL come with many problems. Atlas team is building a simple back end service

* https://github.com/Joystream/atlas/issues/2885

And corresponding adjustments to the onboarding flow 

* https://github.com/Joystream/atlas/issues/2884

## Scope
* [ ] Update the membership creation and editing flows in favour of uploaded avatars
* [ ] Update the modal to Edit Membership
* [ ] Existing [file uploader](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9707%3A378598)

## Info
![](https://user-images.githubusercontent.com/93924525/185081953-f9a7688f-cc88-471f-85b5-fbf0c704cb2b.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203143384618923) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Alright, @dmtrjsg, designs for both the Create and Edit Membership dialogs can be found here: https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10799%3A567889

Notes: 
1. Naturally, I started off trying to re-use existing patterns and components in Pioneer, but the only component for uploading files that I have found ("Dropzone") felt excessive when put in the context of (a) uploading a single image file to be used as an avatar, and (b) inside of a dialog and not a full-page experience.
2. Because of the above, instead of using a "Dropzone" component, I went for a classic [HTML file input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) (styled). 
3. To an engineer implementing this: make sure not to miss the error & loading states designs.

**Comment by dmtrjsg** [comment]
@toiletgranny Agreed! 


I guess preview is also not needed here, I bet you thought about it already.. Perhaps its safe to remove the drop zone variant by this time as Choose file is perfect :)

**Comment by dmtrjsg** [comment]
@toiletgranny can we pls add small preview in a circle pls for the avatar

**Comment by toiletgranny** [comment]
If we can spend a bit more time on this, then sure! I updated the designs, and here they are — https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10804%3A577502

**Comment by dmtrjsg** [comment]
@kdembler is the backend built already? Is there a place where we could use it for our mirroring feature dev?

**Comment by kdembler** [comment]
Yep, yep, there is an instance at https://atlas-services.joystream.org/avatars

To upload you run a POST:
```ts
  const formData = new FormData()
  formData.append('file', croppedBlob, `upload.${croppedBlob.type === 'image/webp' ? 'webp' : 'jpg'}`)
  const response = await axios.post<{ fileName: string }>(AVATAR_SERVICE_URL, formData, {
    headers: {
      'Content-Type': 'multipart/form-data',
    },
  })
```
As a response, you get back an object with single field called `fileName` that will give you the name of the uploaded file and then you can just request it with https://atlas-services.joystream.org/avatars/fileName

**Comment by dmtrjsg** [comment]
Discussed the implication on the design of the Externally managed Pioneer which is unlikely to point to Atlas for Avatar Storage. 

As a fallback scenario when the Backend URL is undefined for this module, the modal will still have Avatar URL variation.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/
wss://3.92.226.32.nip.io/ws-rpc


https://user-images.githubusercontent.com/46903215/193000884-062b1068-cdc7-41cb-8460-7b7b106ce2c4.mov

**Comment by dmtrjsg** [comment]
@ivanturlakov sorry to hear that, pls try here: https://44.201.112.198.nip.io/network/config.json

**Comment by ivanturlakov** [comment]
@dmtrjsg same results on https://pioneer-2.vercel.app/

**Comment by dmtrjsg** [comment]
Will need to sync up with @thesan to advise, thanks for trying will come back to you asap!

**Comment by dmtrjsg** [comment]
@ivanturlakov pls test this on Cartahge env, and we will update the config for env to include the avatar service now. 

the env will be [44.201.112.198.nip.io](http://44.201.112.198.nip.io/)

Will be ready in an hour

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/
wss://44.201.112.198.nip.io/ws-rpc

✅ Creating via faucet
✅ Add Membership/New Member
✅ Edit Membership

<img width="771" alt="Снимок экрана 2022-10-12 в 12 41 57" src="https://user-images.githubusercontent.com/46903215/195314617-7fd7eac8-15a2-4233-a134-0256b33892d7.png">
<img width="770" alt="Снимок экрана 2022-10-12 в 12 42 27" src="https://user-images.githubusercontent.com/46903215/195314610-5f040516-9776-49ff-96b9-ae5ccc4f875f.png">
<img width="1184" alt="Снимок экрана 2022-10-12 в 12 45 52" src="https://user-images.githubusercontent.com/46903215/195313762-b0354513-f0f4-49e5-b25a-2317ff026ae7.png">

### If file size > 1M
<img width="878" alt="Снимок экрана 2022-10-12 в 13 09 54" src="https://user-images.githubusercontent.com/46903215/195315889-39dda4d1-4952-46e6-9d55-75cd77c3ac26.png">


img path: https://atlas-services.joystream.org/avatars/b3ebb15e-4366-4a13-86c6-a9b376e7eb22.jpeg

**Comment by dmtrjsg** [comment]
@WRadoslaw what's the max size we allow? We need to add to the validation error. Max file size allowed is X mb.

**Comment by dmtrjsg** [comment]
Supreseded by 
- https://github.com/Joystream/pioneer/issues/3657

So good to be released as is for the time being
