### ISSUE TITLE
Smoke testing: Members and Transfers

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3301]
ℹ️ Playground config details: https://54.172.154.45.nip.io/network/config.json
Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Current council size is set to 1; WG leads are pre-hired with each WG has 1 worker; Alice account has JOY balances.

☝️ For each workflow make a note of the fees displayed **_on each_** step of the modal, and final fees both on Pioneer AND double-check via Polkadot.js app. Document transaction fees values for each step below in the comments, following this format [CSV-esque]: Process name; Pioneer Sign Transaction Modal Trx Fee Estimate; Actual fees checked in Polkadot.JS app; 

High Level test Scenarios

- [ ] create membership for new empty account (with faucet)
- [ ] create membership for existing account 
- [ ] update membership
- [ ] Invite member
- [ ] make simple transfer between members
- [ ] bind account to member (via creating Signal proposal, signing the first step (binding account) and cancelling the last step of the transaction signer flow which creates actual proposal)

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/

Process name; Pioneer Sign Transaction Modal Trx Fee Estimate; Actual fees checked in Polkadot.JS app;
Create membership for new empty account (with faucet); -; -;
Create membership for existing account; 0.18; 1,770,141,845;
Update membership; 0.61; 6,057,706,150;
Invite member; 0.24; 2,387,811,197;
Simple transfer between members; 0.09; 895,022,164;
Bind account to member (via creating Signal proposal, signing the first step (binding account) and cancelling the last step of the transaction signer flow which creates actual proposal); 0.12; 1,234,098,969;


### Detailed notes:

**Create membership for existing account(new polkadot acc created and deposited 20 tJOY)**
Creation fee - 16.67 tJOY
Transaction fee - 0.18 tJOY
Chain - amount: u128 - 166,666,666,600
Chain - amount: u128 - 1,770,141,845
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xaa8edc8bbae64a9f7cfb2be2f641e5c2a2f0dd71a9a5d96aec4b1cf217f42030
After member creation balance = 3.16 tJOY, no locks

**Update membership**
Transaction fee - 0.61 tJOY
Chain - amount: u128 - 6,057,706,150
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x3bf73fb9b6128138f8ac0fcbf254ba33ed4159ee048fa777c912bf123d50f25c

**Invite member**
Transaction fee - 0.24 tJOY
Chain - amount: u128 - 2,387,811,197
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x1df7fcc348ec1377bba8523a13ec4252ea6925e2a16d8a2c1dc9978b04a03aff


**Transfer tokens**
Authorize transaction - 0.09 tJOY
Chain - amount: u128 - 895,022,164
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xbd109a9f861fe62aa0e49cbb2c88445cc71f7d433c213e9ba49815cb484ff6de


**Bind account to member(via creating Signal proposal, signing the first step (binding account) and cancelling the last step of the transaction signer flow which creates actual proposal)**
Transaction fee - 0.12 tJOY
Chain - amount: u128 - 1,234,098,969
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x3871a913b6737ef0c90015d706914dda989b5f4a160f160c2361b81193c6fa8f
Locked balance - 33.33 tJOY
