### ISSUE TITLE
Carthage testing: WG and Proposals Light

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3302]
ℹ️ Playground config details: https://54.172.154.45.nip.io/network/config.json
Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Current council size is set to 1; WG leads are pre-hired with each WG has 1 worker; Alice account has JOY balances.

☝️ For each workflow make a note of the fees displayed **_on each_** step of the modal, and final fees both on Pioneer AND double-check via Polkadot.js app. Document transaction fees values for each step below in the comments, following this format [CSV-esque]: Process name; Pioneer Sign Transaction Modal Trx Fee Estimate; Actual fees checked in Polkadot.JS app; 

High level scenarios:

Validate the proposal workflow wrt WGLs management:
- [ ] terminate WGL (NB: cooldown times may apply here, meaning you may not be able to replace WGL instantly, but only after the seat becomes vacant)
- [ ] create WGL opening via Proposal
- [ ] apply to opening
- [ ] withdraw application
- [ ] fill WGL opening via Proposal
- [ ] slash WGL
- [ ] reduce/ increase award
- [ ] reduce stake for WGL 

As WGL for any workgroup (CLI, ask @singulart if unsure how to do it):
- [ ] create opening
- [ ] apply to opening
- [ ] fill opening
- [ ] slash worker
- [ ] terminate worker

**Comment by dmtrjsg** [comment]
@singulart this one can be tested without any blockers. Pls feel free to assign.

**Comment by polikosi** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/

Process name; Pioneer Sign Transaction Modal Trx Fee Estimate; Actual fees checked in Polkadot.JS app;

- **Terminate WGL**
Create proposal
Creation fee - 0.13 tJOY
Chain - amount: u128 - 1,313,895,381
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x9e97e1435eaaecb87a134b3d8b5e5a871b22444ce48e8a257e4d633ba5670701
Vote
Creation fee - 0.07 tJOY
Chain - amount: u128 - 737,356,292
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x952d83591f6b6e81373dc12079ed17f434ba62d270d41aa26e20a19151e97dc1

- **create WGL opening via Proposal**
Creation fee - 0.15 tJOY
Chain - amount: u128 - 1,474,058,755
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x53271f55c7fd49ff286be1cf87e01745970a2948532f136f6999131c530fe99e

- **apply to opening**
Creation fee - 0.12 tJOY
Chain - amount: u128 - 1,257,292,135
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x4c4fa711552a2670bcc69198b86ac941fbedfb1e7c40a9f603ac54133ee362a4

- **withdraw application**
Chain - amount: u128 - 735,502,985
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x1e5d7e0da5f141582de7e8f9e002f89c17621a2706824a590fd37303f6d9b132

- **fill WGL opening via Proposal**
Create proposal
Creation fee - 0.13 tJOY
Chain - amount: u128 - 1,283,923,143
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x6177e02df0db0103d5da8104d7425e4d8c25ae548fa9cd666cdaa91a7c6fac57
Vote 
Creation fee - 0.07 tJOY 
Chain - amount: u128 - 740,495,389
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xe164fe96038272937b9bbe0e136da4f020ec37dca58c9ae3ed73e10794873401

- **slash WGL**
Create proposal
Creation fee - 0.13 tJOY
Chain - amount: u128 - 1,309,377,563
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x41113893888b5ebafb11f6dfd1fd2f76560e2e6cf49063309267c27ea39030fd
Vote 
Creation fee - 0.07 tJOY 
Chain - amount: u128 - 737,123,976
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x5594a2c742496da993bc89dee3b5543aad60c1e336f3375fbdc39be85fbe7a29

- **reduce award**
Create proposal
Creation fee - 0.13 tJOY
Chain - amount: u128 - 1,313,901,989
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x07216eb8fcceefc8ad1a608cf69983d06d2d3ffbac783c17fc955889e707f0c8
Vote 
Creation fee - 0.07 tJOY 
Chain - amount: u128 - 737,082,221
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x059be0c6579f8391ebe0f11f8d65058beceb56c1ae0bd9f5156533dc7d9c2593

- **increase award**
Create proposal
Creation fee - 0.13 tJOY
Chain - amount: u128 - 1,313,818,448
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x2a2f7a1353d44791c02df3b7f40f0f471b6581631150f877858fbb404e09737a
Vote 
Creation fee - 0.07 tJOY 
Chain - amount: u128 - 740,389,769
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x8c0d774f0848e16beaf91d65e476a811f9c4617022c1912026bbec0c07a95ded

- **reduce stake for WGL**
Create proposal
Creation fee - 0.13 tJOY
Chain - amount: u128 - 1,308,609,504
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xad91a913c4ec85aa46232fd7b8498417274e165fc1948cedc7b494897c1c1d4a
Vote 
Creation fee - 0.07 tJOY 
Chain - amount: u128 - 737,031,886
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xe6707fc6535bda9fa8ecdb72447db4923a670f7ec94ac18ce1129ede2b849308

**CLI**
- **create opening**
Creation fee - 98.806 mJOY
Chain - amount: u128 - 988,059,002
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x1f2b1343b0a3b54934238f4dce4b6f7c43f207a1dcbe6fb977bbc2c1d8b2636c

- **apply to opening**
Creation fee - 124.3767 mJOY
Chain - amount: u128 - 1,243,763,260
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x6af565315cf87e7d023293a716d1578d980dcbdb3fca90ad9a72ec0c46563d54

- **fill opening**
Creation fee - 1.1093 JOY
Chain - amount: u128 - 11,093,028,803
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x1c40ea44923194d8f18ed9890066b53f775d2dc86a077f8c71614c780e21e363

- **slash worker**
Creation fee - 77.1717 mJOY
Chain - amount: u128 - 771,716,658
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xc88a9b20ca54c82881ad109c3e91c7d5c5eca1c1de9f728905de28c5e6695ff1

- **terminate worker**
Creation fee - 92.5024 mJOY
Chain - amount: u128 - 925,022,060
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x54ac40d4d5e6dfe1065ed176c456e113d96f645c8264e1ca721ed4ad4badc204

**Comment by dmtrjsg** [comment]
@polikosi nicely done ✅ 💪

**Comment by dmtrjsg** [comment]
@polikosi question: does Pioneer show 77.1717 mJOY in some cases just as you reported in the respective processes?

**Comment by polikosi** [comment]
@dmtrjsg i thought it was 77.1717 mJOY = 0.07 JOY
did i get it wrong?
Pioneer show Creation fee - 0.07 tJOY per Vote

**Comment by dmtrjsg** [comment]
@polikosi that should be correct, but when you are covering CLI was tx fees displayed in very large numbers of base denomination coins (aka HAPI since recently, where 10^n HAPI = 1JOY), or was it actually displaying mJOY. That was the question. Thank you 🙏

**Comment by polikosi** [comment]
@dmtrjsg I have this photo, maybe it explains it all

last line
![image](https://user-images.githubusercontent.com/80429191/184142888-b7b2c035-7c7c-4edf-ac26-33e879057c60.png)

**Comment by dmtrjsg** [comment]
@polikosi very much so thanks a mil!
