### ISSUE TITLE
Carthage testing: Council and Election

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3303]
ℹ️ Playground config details: https://54.172.154.45.nip.io/network/config.json
Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Current council size is set to 1; WG leads are pre-hired with each WG has 1 worker; Alice account has JOY balances.

☝️ For each workflow make a note of the fees displayed **_on each_** step of the modal, and final fees both on Pioneer AND double-check via Polkadot.js app. Document transaction fees values for each step below in the comments, following this format [CSV-esque]: Process name; Pioneer Sign Transaction Modal Trx Fee Estimate; Actual fees checked in Polkadot.JS app; 

High level scenarios:

☝️ Go through a successful election cycle in Pioneer, by using the minimum values. Ensure: Minimum values (# CM slots + 1 announces, # CM slots votes) is sufficient

1st round:
- [ ]  Create 2x council candidate applications (>2, as current playground)
- [ ] Vote
- [ ] Reveal
- [ ] Recover candidate stake from losing candidate
- [ ] Recover voting stake for council candidate that did not win election
 
2nd round:
- [ ] Reapply with both accounts from 1st round, make the other one win (here  no need to document fees, as already captured above)
- [ ] Recover council stake from council member from 1st round
- [ ] Recover voting stake used for council member
- [ ] View history past council and past election tabs and check if all info display reflects actions from the test steps above

**Comment by polikosi** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/

Process name; Pioneer Sign Transaction Modal Trx Fee Estimate; Actual fees checked in Polkadot.JS app;

1st round:

- **Create 2x council candidate applications (>2, as current playground)**
Candidate 1
_Announce candidacy_
Creation fee - 0.15 tJOY
Chain - amount: u128 - 1,516,229,268
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x48dee02eac5f78b11337163deab6edda6dd2390fb29013b5dc92916a7504c42f
_Set candidacy note_
Creation fee - 0.09 tJOY
Chain - amount: u128 - 940,354,394
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x0571edaaa142adae48e81cb704c93ba8fb53c9a0fa5c43ba9a1ec92d345b2380

Candidate 2
_Announce candidacy_
Creation fee - 0.54 tJOY
Chain - amount: u128 - 5,379,299,330
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x02dd7983075964b026b51f72aa048a8c0d9ff8359330a2b6652b665f72582d0f
_Set candidacy note_
Creation fee - 0.09 tJOY
Chain - amount: u128 - 940,322,075
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xfae16c2cc0e5f59991e21f7020f9d2a27c6f16a757e6ade171a7b4476e7e7499

Candidate 3
_Announce candidacy_
Creation fee - 0.54 tJOY
Chain - amount: u128 - 5,378,438,782
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x1024baef4531dee74d5b3867f0b5ece37f1290e69b97092991459eb24ebac59e
_Set candidacy note_
Creation fee - 0.09 tJOY
Chain - amount: u128 - 940,272,644
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xee787d4d4a8b41ed73c227d1c772749f84c96709612274ef4c6e11d0858c4f36

- **Vote**
Candidate 1
Creation fee - 0.12 tJOY
Chain - amount: u128 - 1,171,717,471
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x0f983967b49752b09e92129aeea8f4b80b924e708aaad8e65c64fee3e2757976

Candidate 2
Creation fee - 0.12 tJOY
Chain - amount: u128 - 1,171,676,911
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x21fe97e5bddfca115966e3021c430c0ff1b8bedbf28bccd2995e6710d7c64927


- **Reveal**
Candidate 1
Creation fee - 0.12 tJOY
Chain - amount: u128 - 1,173,146,554
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xd7754bbf19b28becf5ff8af41d821d03174bdce44ab1ace7508174ef480792ab

Candidate 2
Creation fee - 0.12 tJOY
Chain - amount: u128 - 1,173,165,916
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x228541124f9955ef949934134e1750edc7ee91d14e04658a5727f0debe1c9fd2

- **View history**
Past election:
![Screenshot_170](https://user-images.githubusercontent.com/80429191/182163152-86f48bb0-659f-4783-9264-c7cce14d9d52.png)

Past councils:
![Screenshot_171](https://user-images.githubusercontent.com/80429191/182167049-0fb74c14-b699-4c3a-a93e-3e1c9731168f.png)

- **Recover candidate stake from losing candidate**
Creation fee - 0.11 tJOY
Chain - amount: u128 - 1,064,095,187
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x367c6a7a941d3fba8e9979ff67b496c4f10edd64f59e9d1dc1e223f20b594c46

- **Recover voting stake for council candidate that did not win election**
Creation fee - 0.1 tJOY
Chain - amount: u128 - 1,016,842,371
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x96db6c7dabb973514771d76f66317e25814fd9745f5805fcc47b1633bb7e0490

2nd round:

- **Reapply with both accounts from 1st round, make the other one win (here no need to document fees, as already captured above)**

- **Recover council stake from council member from 1st round**
It was automatic when a new consul was elected

- **Recover voting stake used for council member**
Creation fee - 0.1 tJOY
Chain - amount: u128 - 1,013,885,126
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x2741f20d187d6fe2c489df72bb2c5bcc06d034c0a872a9852b10f37dbc57c09a
