### ISSUE TITLE
Smoke testing: Forum

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3304]
ℹ️ Playground config details: https://54.172.154.45.nip.io/network/config.json
Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Current council size is set to 1; WG leads are pre-hired with each WG has 1 worker; Alice account has JOY balances.

☝️ For each workflow make a note of the fees displayed **_on each_** step of the modal, and final fees both on Pioneer AND double-check via Polkadot.js app. Document transaction fees values for each step below in the comments, following this format [CSV-esque]: Process name; Pioneer Sign Transaction Modal Trx Fee Estimate; Actual fees checked in Polkadot.JS app; 

⚠️  YOU WOULD NEED THIS FOR ACTING AS PRE-EXISTING WGL. SEE MANUAL ON HOW TO DO IT 👇 :
![MAnual on loggin in as WGL](https://user-images.githubusercontent.com/93924525/181734088-3861c637-34f8-47bd-bb71-60568008186b.jpg)

High level scenarios

As forum WGL:
- [ ] Create category
- [ ] Create subcategory
- [ ] Delete subcategory
- [ ] Delete Category
- [ ] Moderate the post (as WGL for Forum)

Regular member:
- [ ] create thread
- [ ] post to thread
- [ ] edit post
- [ ] reply

**Comment by singulart** [comment]
Test report: https://www.notion.so/joystream/Report-Smoke-testing-Forum-4e55316df35c4d94b0f2380dadf20b46
