### ISSUE TITLE
Prohibit editing and deleting proposal discussion posts

### ISSUE THREAD

**Issue by singulart** [Joystream/pioneer#3308]
Bad faith CMs may use editing feature (and ability to remove posts, for that matter) to cover things up and distort the perception of proposals discussions. 

In my humble opinion, proposals discussion should be made completely immutable. The below example shows that CMs (not necessarily acting in bad faith) use this feature quite extensively: 

<img width="256" alt="Screenshot 2022-06-28 at 11 25 24" src="https://user-images.githubusercontent.com/7863785/176131522-c13228fd-0096-4208-99f8-a4f3959c2821.png">

**Comment by dmtrjsg** [comment]
@bedeho would this require runtime change? What's your view on this feature request.

**Comment by bedeho** [comment]
> In my humble opinion, proposals discussion should be made completely immutable. The below example shows that CMs (not necessarily acting in bad faith) use this feature quite extensively:

Editing is clearly very useful in some cases also, so it's not clear cut. I see two ways of dealing with this
1. Just make it simple and have no editing ever, and then people have to make a second post to signal an edit.
2. Try to introduce some UI level treatment of showing edits were done.

I could see 1 being better.

> would this require runtime change? What's your view on this feature request.

It would, but I think we should not touch this really, we should make a metaprotocol version of it, rather can trying to work with the pure runtime version we have now. There is already an issue for this, so I will add a remark about this

https://github.com/Joystream/joystream/issues/2934

**Comment by traumschule** [comment]
Changing pioneer won't affect what can be done on chain.
