### ISSUE TITLE
Unable to withdraw stake from failed bounty

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#3309]
https://user-images.githubusercontent.com/80429191/176146957-75e83f16-cf6c-49f2-914b-c7a48e958c4c.mp4

![image](https://user-images.githubusercontent.com/80429191/176147036-c0d1ee28-b885-402c-9352-31f72cdab5f9.png)
TX: https://polkadot.js.org/apps/?rpc=wss://3.235.196.1.nip.io/ws-rpc#/explorer/query/0xf1011544f163eed15a89149ff54050c149f744a7c37ac9cec73d1f4870e6502d

**Comment by dmtrjsg** [comment]
@WRadoslaw this one looks pretty strange.. runtime side issue?

**Comment by WRadoslaw** [comment]
Not sure, I'm unable to open `tx` link and video doesn't really help 😞

**Comment by dmtrjsg** [comment]
@polikosi are they all failing like this? Is this reproducable on staging as well? 

The block details not helping much:
<img width="1160" alt="Screenshot 2022-07-11 at 09 10 55" src="https://user-images.githubusercontent.com/93924525/178218543-d67dd618-dddf-45d0-b0fe-2378a3ab29a2.png">

**Comment by polikosi** [comment]
I never saw it again. I think it was a momentary mistake.
I think that this ticket can be closed.
