### ISSUE TITLE
QA task: test Talisman for Pioneer on preview branch

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3336]
## Scope
- [ ] quick test of Talisman implementation for Pioneer on preview branch would be helpful

Can be tested here> https://pioneer-2-6zm2fsfi7-joystream.vercel.app/#/profile
Or here
![image](https://user-images.githubusercontent.com/93924525/177991453-b06bb14d-5344-410d-8659-a1c895356580.png)

Relevant PR:
https://github.com/Joystream/pioneer/pull/3327

Originating Issue link:
- https://github.com/Joystream/pioneer/issues/3239 
⚠️ pls read comments in the very bottom of the issue for latest updates/ comments on design

**Comment by ivanturlakov** [comment]
Tested on https://pioneer-2-6zm2fsfi7-joystream.vercel.app/#/working-groups

QN didn’t update after member created
<img width="1440" alt="after_member_created-1" src="https://user-images.githubusercontent.com/46903215/178254585-1bf16c9c-d718-43f8-acfe-54aea4652920.png">

Acc details after member created
<img width="1173" alt="after_member_created_acc" src="https://user-images.githubusercontent.com/46903215/178254806-4ca98cb9-9f16-48fc-8346-512e077a8383.png">



**Minor design issues**

[Figma link](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=9914%3A421256)

Text alignment (no accs connected), 1-2-3 bullets size
<img width="1216" alt="existing_ext_no_accs_connected" src="https://user-images.githubusercontent.com/46903215/178253437-44e11131-acb3-4a35-8b92-02f879341ee9.png">


Btn text (acc connected)
<img width="1438" alt="existing_ext_acc_connected" src="https://user-images.githubusercontent.com/46903215/178253728-beb07dfe-4883-49e8-8951-a9688a0c3df0.png">

Text alignment & icon color
<img width="972" alt="text_alignment_icon_color" src="https://user-images.githubusercontent.com/46903215/178254151-f208be90-ca60-4280-910c-da500db12f62.png">

**Comment by dmtrjsg** [comment]
@ivanturlakov pls elaborate on the button text point (acc connected)

**Comment by ivanturlakov** [comment]
> pls elaborate on the button text point (acc connected)

@dmtrjsg It's about the text on the buttons, the design provides for the text - "Connect Wallet" (on the screenshot - "Join Now" and "Continue"). 

Perhaps after connecting the account, the text should change to "Join now" or "Continue"... sorry for the confusion 🙂

**Comment by dmtrjsg** [comment]
@thesan @WRadoslaw to discuss this 

Agreed, the buttons should always have "Connect wallet". 

Once wallet chosen and account is connected:

if memebrship for this wallet exists: Show membership card with name and avatar (like right now)
if membership does not exist for wallet: Show select membership (where existing accounts shown, and "Create membership" option is in the bottom)
