### ISSUE TITLE
[USERSNAP] Minutes-long delay picking up QN transaction

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3337]
**Taken at**: https://dao.joystream.org/#/proposals/preview/354
**Fields**:
- Houston, we have a problem.: Minutes-long delay picking up QN transaction
- Comment: After voting on a proposal further voting is blocked for several minutes.
- Feedback: l1

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/df06a04b-86ff-4692-b48f-d2a500718d84-annotated_1bfa71fb-9e53-4a8b-855f-fed4666377ce.png?etag=e2644df0b25f44749d2cb648499e2e84)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/df06a04b-86ff-4692-b48f-d2a500718d84-annotated_1bfa71fb-9e53-4a8b-855f-fed4666377ce.png?etag=e2644df0b25f44749d2cb648499e2e84)*

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2868x1459
**[Open #296 in Usersnap](https://app.usersnap.com/l/feedback/46c50e94-b1a2-450c-906c-13ca7e9bd1ea?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
it could be that related to websocket disconnects

**Comment by polikosi** [comment]
tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://44.201.112.198.nip.io/network/config.json

as for me all works fine

https://user-images.githubusercontent.com/80429191/199512224-7caefe49-9d7f-40dd-a7d8-9e7d246ce1b9.mp4

**Comment by traumschule** [comment]
Closing as not reproducible.
