### ISSUE TITLE
When creating a bounty, a thread is created in the wrong forum category

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#3341]
## Problem

Issue identified to be a Query node issue. Pioneer uses the following query to fetch the "Bounties" forum category: https://raw.githubusercontent.com/Joystream/pioneer/aa9aef7db06cb103257078bee2fc67d2efedc216/packages/ui/src/bounty/hooks/useBountyForumCategory.ts However, this query return random categories :) 

## Implication on Pioneer

![image](https://user-images.githubusercontent.com/84832436/178145327-dd0ce8a1-cdff-4b44-92cd-5ec2c84c88aa.png)
![image](https://user-images.githubusercontent.com/84832436/178145341-53a91140-b524-4a4f-aed0-d740b672df1b.png)
I think this is a pioneer mistake.

![image](https://user-images.githubusercontent.com/84832436/178145370-545347ec-dd8b-4823-9eee-2437b356f818.png)
![image](https://user-images.githubusercontent.com/84832436/178145427-460957f6-868b-4a58-b26b-64fa71bc1edd.png)
Previously, when creating a bounty, a thread on the forum was created in the "Bounties" category - https://dao.joystream.org/#/forum/category/1

**Comment by singulart** [comment]
https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944/#/explorer/query/1667890 wrong category ID is being sent in the extrinsic

**Comment by singulart** [comment]
Issue identified to be a Query node issue. Pioneer uses the following query to fetch the "Bounties" forum category: https://raw.githubusercontent.com/Joystream/pioneer/aa9aef7db06cb103257078bee2fc67d2efedc216/packages/ui/src/bounty/hooks/useBountyForumCategory.ts However, this query return random categories :)

**Comment by dmtrjsg** [comment]
Moving this issue to QN board.

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/joystream #4081](https://github.com/Joystream/joystream/issues/4081) via [**ZenHub**](https://www.zenhub.com/)
