### ISSUE TITLE
Creation date and time is not displayed for a Forum Thread

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#3347]
Hello guyz:

I just noticed this possible improvement or addition in Joystream Pioneer.
If you create a new Forum Thread and open it, the date and time of creation of the thread is not shown.
Whereas if you reply on that thread, the date and time of reply thread is shown in the right side.

Please see picture on link below for easy illustration...
https://drive.google.com/file/d/1m9l8nQgA-pHohckhKUT8eqKM9Te-UxlG/view?usp=sharing

I suggest Joystream Pioneer be improved by adding creation date and time of a forum thread.
Possibly on upper right side of the thread same with reply.

Thank you

**Comment by dmtrjsg** [comment]
Adding to community backlog 

xcc
@secretgirl1

**Comment by adovrodion** [comment]
Bounty was created: https://dao.joystream.org/#/bounty/preview/270

**Comment by Songoku1691** [comment]
Wow! This will be great if that feature is added on next version of Pioneer.

**Comment by polikosi** [comment]
verified wss://44.201.112.198.nip.io/ws-rpc

✅date and time added
![image](https://user-images.githubusercontent.com/80429191/194062631-4ea88035-7ccc-4282-a874-1cacde8b91c7.png)
