### ISSUE TITLE
Caching and Polling: Forum module

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3352]
## Context

As part of the overall caching and polling work (- https://github.com/Joystream/pioneer/issues/2311) Forum was left out of scope with a view to do it after the redesign work is done

This ticket addresses caching and polling for Forum

⚠️ Frequency is defined here: https://github.com/Joystream/pioneer/pull/3221

## Scope

⚠️ Do after the respective pages from #3029 are ~completed~ merged

* [ ] Create a hook to enable polling "useRefetchQueries" (already used in Bounty.tsx, packages/ui/src/app/pages/Council/Council.tsx and Election..)
* [ ] Implement caching and polling for the redesigned forum module

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

⚠️ Latest threads didn't update
✅ Categories
✅ Watchlist
⚠️ Thread page didn't update
✅ Archived
