### ISSUE TITLE
Right side of proposal page is outside of the screen

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#3353]
## Scope

- [ ] Make sure all components on a page fit to a page on smaller screens (13 inch)

⚠️ we are suggesting not to wait till the #1794 epic design is finished, and suggesting to fix this one by reducing the width and white space in the table. 

## Context

Tested on prod
MacBook 13`
Latest Chrome

Proposal page
<img width="1440" alt="Снимок экрана 2022-07-13 в 13 10 59" src="https://user-images.githubusercontent.com/46903215/178709823-22d52df9-0050-4cd1-920a-1ac189ee8277.png">

**Comment by vrrayz** [comment]
I'd like to take this up.

**Comment by vrrayz** [comment]
I just made a PR for this here => https://github.com/Joystream/pioneer/pull/4146

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/current

<img width="1440" alt="Снимок экрана 2023-03-05 в 15 21 18" src="https://user-images.githubusercontent.com/46903215/222963061-df9e679b-d06c-4af2-a836-8d9eb158d356.png">
