### ISSUE TITLE
WG Application Interchanging of Answers Bug

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#3362]
Hello Guys:

I would like to report this bug or error when applying in WG opening. This occurs when you skip questions and return to answer them back. You will notice that answers interchange. I hope this will be fixed. Please watch video below that I made to illustrate the issue.

https://play.joystream.org/video/27072

Thank you

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/joystream #4060](https://github.com/Joystream/joystream/issues/4060) via [**ZenHub**](https://www.zenhub.com/)

**Comment by thesan** [comment]
We tried to reproduce the application q1 -> q3 -> q2. But it did not reproduce the issue. Maybe it has been unknowingly fixed on Pioneer or the QN.

In case it reappear later here's the transaction details (for the application shown on the video):

  | 4912 84
-- | --
signer | eac9c2cdca925bfb73631a1359ae8f0df5ec37b5f0b7f37346d35d39043c6375
signature | 01   b8752055e84281223222c6a44484387125dde6e1374253df0e39ff6d221b505ef93ca41f245d7c1e1ada9ee3f7dc23694811ce2e104758e554ba48180e7cef8a
era | 01
  | 4000000000000000
  | 2600000000000000
nonce | a104
tip | 00
callIndex | 0100
calls | 08
callIndex | 130d
memberId | 080d000000000000
stakingAccountId | eec3ba029346f56803ef08682fbebc7a0e1919723cb5d23a0227f92bdd99e441
callIndex | 2401
memberId | 080d000000000000
openingId | 1700000000000000
roleAccountId | eac9c2cdca925bfb73631a1359ae8f0df5ec37b5f0b7f37346d35d39043c6375
rewardAccountId | eac9c2cdca925bfb73631a1359ae8f0df5ec37b5f0b7f37346d35d39043c6375
description | e90d   0a06474d54202b380a204a616e7561727920323032322c204d6179626520372f313020486168616861210a26456e676c697368202d20466169726c7920476f6f640a0a46696c6970696e6f202d20476f6f640aa5064920616d20612063727970746f20656e74687573696173742e2049207573656420746f2062652061206d6f64657261746f7220696e20612070726576696f7573204e46542067616d652070726f6a6563742e20492077617320616c77617973206174207461736b20696e206d616b696e67207468652067726f757020636861742061637469766520616e64206d616b696e67206d656d6265727320656e67616765642e20492072656d656d626572204920776f756c6420616c77617973207468696e6b206f662077617973206f6e20686f7720746f206d616b65206d656d6265727320616374697665206f6e63652074686579206265636f6d652069646c6520486168616861210a0a526567617264696e67204a6f7973747265616d2c20492068617665206265656e206865726520666f7220666577206d6f6e74687320616e64204920616c776179732068616e672d6f757420696e20646973636f72642e20446973636f726420686173206265656e206d79206d6f7374207573656420617070207269676874206e6f7720286e6f742046616365626f6f6b2c2054696b746f6b206f7220496e7374616772616d292e205468657265206172652074696d65732c204920636f756c6420616c7761797320736565206e6577206d656d6265727320636f6d696e6720696e20616e64206a6f696e2e20492077616e7420746f206772656574207468656d207468652073616d652074696d652074686579206a6f696e20627574204920636f6e74726f6c206d7973656c662062656361757365204920756e6465727374616e6420697473206a6f62206f6620485220616e64207468657920686176652070726f63656475726520746f20666f6c6c6f772e20486168616861210a0a5768656e204920636865636b6564205747206f70656e696e672c2074686572652773207374696c6c206e6f20776f726b6572206f70656e696e672e20427574204920616c7265616479206170706c696564206a75737420736f207768656e206974206265636f6d657320617661696c61626c65204920636f756c6420626520636f6e7369646572656420616c72656164792ec2a00a0a5468616e6b73e280a6
stake | a8610000000000000000000000000000
stakingAccountId | eec3ba029346f56803ef08682fbebc7a0e1919723cb5d23a0227f92bdd99e441
link | [#/extrinsics/decode/0x010008130d080d000000000000eec3ba029346f56803ef08682fbebc7a0e19197](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org%3A9944%2F#/extrinsics/decode/0x010008130d080d000000000000eec3ba029346f56803ef08682fbebc7a0e1919723cb5d23a0227f92bdd99e4412401080d0000000000001700000000000000eac9c2cdca925bfb73631a1359ae8f0df5ec37b5f0b7f37346d35d39043c6375eac9c2cdca925bfb73631a1359ae8f0df5ec37b5f0b7f37346d35d39043c6375e90d0a06474d54202b380a204a616e7561727920323032322c204d6179626520372f313020486168616861210a26456e676c697368202d20466169726c7920476f6f640a0a46696c6970696e6f202d20476f6f640aa5064920616d20612063727970746f20656e74687573696173742e2049207573656420746f2062652061206d6f64657261746f7220696e20612070726576696f7573204e46542067616d652070726f6a6563742e20492077617320616c77617973206174207461736b20696e206d616b696e67207468652067726f757020636861742061637469766520616e64206d616b696e67206d656d6265727320656e67616765642e20492072656d656d626572204920776f756c6420616c77617973207468696e6b206f662077617973206f6e20686f7720746f206d616b65206d656d6265727320616374697665206f6e63652074686579206265636f6d652069646c6520486168616861210a0a526567617264696e67204a6f7973747265616d2c20492068617665206265656e206865726520666f7220666577206d6f6e74687320616e64204920616c776179732068616e672d6f757420696e20646973636f72642e20446973636f726420686173206265656e206d79206d6f7374207573656420617070207269676874206e6f7720286e6f742046616365626f6f6b2c2054696b746f6b206f7220496e7374616772616d292e205468657265206172652074696d65732c204920636f756c6420616c7761797320736565206e6577206d656d6265727320636f6d696e6720696e20616e64206a6f696e2e20492077616e7420746f206772656574207468656d207468652073616d652074696d652074686579206a6f696e20627574204920636f6e74726f6c206d7973656c662062656361757365204920756e6465727374616e6420697473206a6f62206f6620485220616e64207468657920686176652070726f63656475726520746f20666f6c6c6f772e20486168616861210a0a5768656e204920636865636b6564205747206f70656e696e672c2074686572652773207374696c6c206e6f20776f726b6572206f70656e696e672e20427574204920616c7265616479206170706c696564206a75737420736f207768656e206974206265636f6d657320617661696c61626c65204920636f756c6420626520636f6e7369646572656420616c72656164792ec2a00a0a5468616e6b73e280a6a8610000000000000000000000000000eec3ba029346f56803ef08682fbebc7a0e1919723cb5d23a0227f92bdd99e441)

**Comment by traumschule** [comment]
[Reported again](https://discord.com/channels/811216481340751934/812344874099277824/1060144403441786951)
