### ISSUE TITLE
Pioneer Logo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3365]
## Scope
- [x] Logo for Pioneer
>- https://github.com/Joystream/atlas/issues/2512
- [x] Powered by Joystream
- [x] Link to Github

![Screenshot 2022-07-18 at 12.42.51.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/85b61a98-6fff-4e8e-a738-709a76bd78dc)

**Comment by dmtrjsg** [comment]
@toiletgranny pls add figma link + powered by Joystream addition. 

We are going forward with option 1 from iteration 2. The one yourself and Bedeho liked more.

**Comment by toiletgranny** [comment]
@dmtrjsg right, sorry, this ticket wasn't meant to be in this column as we haven't picked the logo yet. All of the things you mentioned will be here once I finish working on this! 🫡

**Comment by toiletgranny** [comment]
Alright, here I come with the links:
1. To an engineer implementing this: to export Pioneer logo in a desired color variant, size and format, use the below Figma link. Also, this is were favicon and iOS/Android icons can be found: https://www.figma.com/file/3hnTi8QWyHDOtkZENhjxjB/Pioneer-Brand?node-id=22%3A9469
2. I updated the Sidebar component in Figma to swap the JS logo with a Pioneer one, and to add the "Powered by Joystream" caption at the bottom (along with the GitHub repo link). Design can be found here: https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=748%3A78336
    - Please note that you might still be seeing many designs with the Joystream logo in the Sidebar, in the Figma file with Pioneer designs. This is because, from what I can see, the Sidebar component has been detached multiple times across many pages in Figma, and fixing this in older designs would take a significant amount of time. I'm assuming that keeping legacy Figma designs up-to-date in that regard is not our priority at the moment, so I'm not fixing this as part of this issue. Let me know if you'd like to have it addressed now.
    - To an engineer implementing this: please make sure to enable comments visibility in Figma to see links for both the Joystream and GitHub logos, as well as to [check out this frame](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=697%3A6297) with hover colors preview for the newly added elements.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/

**Logo (link to /working-groups)**
<img width="508" alt="Снимок экрана 2022-09-22 в 13 35 11" src="https://user-images.githubusercontent.com/46903215/191725229-aa58a83f-2ea0-4e55-af6d-c6b0c9de2ec0.png">


**Footer info (link to https://www.joystream.org/ & https://github.com/Joystream/pioneer in a new browser tab.)**
<img width="225" alt="Снимок экрана 2022-09-22 в 13 42 28" src="https://user-images.githubusercontent.com/46903215/191726606-09c95f54-c157-4aed-b800-141e9281b056.png">

<img width="226" alt="Снимок экрана 2022-09-22 в 13 36 43" src="https://user-images.githubusercontent.com/46903215/191725517-c82fb4a7-48fc-4f59-b929-2986ceabfea4.png">
