### ISSUE TITLE
Search Member by ID

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3369]
## Context

Follow up use case originating from this comment: 
- https://github.com/Joystream/pioneer/issues/2657#issuecomment-1173671702

## Scope

- [ ] Enable searching member by ID

**Comment by traumschule** [comment]
duplicate of #3390 #2032 (implemented)

![member search](https://user-images.githubusercontent.com/31551045/197021700-d65abd16-0244-4ad0-9d95-e305e0b1f676.png)
