### ISSUE TITLE
[USERSNAP] Proposals: vote modal respawns

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3380]
**Taken at**: https://dao.joystream.org/#/proposals/preview/404
**Fields**:
- Houston, we have a problem.: Proposals: vote modal respawns
- Comment: for some reason the modal disappears, reappears resetting inserted text.
this is a regression and worked some months ago.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c95f295e-f7db-4c24-959b-3ef73094e1d0-annotated_51065ecc-0eca-4337-8a49-170ef86fe330.png?etag=d19d2a69eee51b445a851b6967b01937)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c95f295e-f7db-4c24-959b-3ef73094e1d0-annotated_51065ecc-0eca-4337-8a49-170ef86fe330.png?etag=d19d2a69eee51b445a851b6967b01937)*

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2868x1459
**[Open #302 in Usersnap](https://app.usersnap.com/l/feedback/a1b33df3-0e76-453f-89b8-23e1f367776a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@traumschule is it possible to provide a video capture of this? Anything in console? 

Does it happen only once, or every x seconds? Resetting inserted text, meaning rationale for voting gets deleted on page refresh?

**Comment by traumschule** [comment]
yes, text is reset to empty. can happens multiple times while typing, quite probably because of a code change that lets the modal (re)spawn.
