### ISSUE TITLE
[USERSNAP] Proposals: Processing tx forever

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3381]
**Taken at**: https://dao.joystream.org/#/proposals/preview/404
**Fields**:
- Houston, we have a problem.: Proposals: Processing tx forever
- Comment: for some reason the tx isn&#39;t picked up which makes voting on multiple proposals cumbersome (requires page reload).
this is a regression and worked some months ago.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/cb62587c-dff4-46c4-bbe9-5bbe2b796089-annotated_4559c1e2-2d09-4f13-afb6-6790380b41eb.png?etag=30f076c5bc33479b8eed316a37ab1344)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/cb62587c-dff4-46c4-bbe9-5bbe2b796089-annotated_4559c1e2-2d09-4f13-afb6-6790380b41eb.png?etag=30f076c5bc33479b8eed316a37ab1344)*

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2868x1459
**[Open #303 in Usersnap](https://app.usersnap.com/l/feedback/17ccb2dc-c2aa-4d98-bc8c-24a7b8122e90?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@traumschule to clarify, are you saying that after the tx is successful the app does not allow you to vote on next proposal without the reload? Or tx takes a long time? 

What do you mean by "tx not picked up"?

**Comment by traumschule** [comment]
yes, the first. it is supposed to catch when the tx block finalizes - maybe a QN issue?

**Comment by WRadoslaw** [comment]
Will be fixed by #3475
