### ISSUE TITLE
Add visual presentation of FM status

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#3387]
## Context
Support this: https://github.com/Joystream/joystream/issues/3931

As part of bootstrapping the state of Carthage and mainnet, the set of initial members with FM status must be identified on-chain, the purpose of this issue to describe the extrinsic for the creation of such founding members.

We need a way to display this status in Pioneer

## Scope

@Design * [x]  new icon for council members

@ Dev 

* [x] Indicate status of "founding member" for qualifying members with "Flag" icon. 
* [x] Use the new icon for Council members (this one> [ ] instead of Checkbox)
* [x] Checkbox icon will not be used, safe to comment it out
* [x] Fix filter by council members and founding members 
* [x] Add tooltips on hover on members filter (for founding and council members)

 LInk to [ [new icons for council member, and founding member] ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=1405%3A76675)

## Design
![Screenshot 2022-07-25 at 15.22.32.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/7a53fa59-8b83-4242-8c74-7e5eb5fd8800)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202812960932389) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/185613831-7cc20ac3-94b3-49b3-81f1-27e4329cc062.png)

Tasked with designing an icon indicating a Council Member, naturally, I started off by reviewing how council or council members are visually represented through icons in Pioneer right now (the top row in the above image). The good news is that consistency is definitely there, in terms of the idea. The bad news is that this idea is... quite unfortunate to be squeezed into a 16x16px icon. 

I gave it a shot and came up with three options to choose from, it's the third icon in the circle next to the member name. @dmtrjsg, my recommendation would be to go with option 2.

**Comment by bedeho** [comment]
1. while the council and a council member are two distinct ideas, pretty nuts how many variations are present 🤯 
2. agree, 2 is simpler, icons are already very crowded.

**Comment by toiletgranny** [comment]
@WRadoslaw The new icon can be exported here: https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10852%3A551972

@dmtrjsg May I also suggest, on the Members tab, to add tooltips for each icon/button under the "Member type" section in the filters bar?

**Comment by polikosi** [comment]
⚠️there is no founding member yet
![image](https://user-images.githubusercontent.com/80429191/192146458-e6c8d017-a884-47b6-9ceb-6d7d7ad96594.png)
✅Council members
![image](https://user-images.githubusercontent.com/80429191/192146823-e33af809-3e4a-4957-a119-ade135882bd0.png)
✅Filter filter by council members and founding members
![image](https://user-images.githubusercontent.com/80429191/192146977-07311784-53fc-4460-a733-bc114d1651a9.png)
✅ tooltips on hover on members filter (for founding and council members)
![image](https://user-images.githubusercontent.com/80429191/192147031-5b7d53dd-a3b8-4b37-b3ce-6f7230b99fc6.png)
![image](https://user-images.githubusercontent.com/80429191/192147036-4e139575-6f4b-45f9-8b2e-80d7bc665cd2.png)
![image](https://user-images.githubusercontent.com/80429191/192147046-cbcfb970-908a-491c-a6d3-024d114b405f.png)
