### ISSUE TITLE
Remove Testnet Banner

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3400]
Remove this banner:

![](https://user-images.githubusercontent.com/93924525/181470872-c0398c8a-78a3-49a3-8a2d-92f471ab55dd.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203143438951371) by [Unito](https://www.unito.io)

**Comment by polikosi** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/
wss://34.230.5.182.nip.io/ws-rpc

✅ Testnet banner doesn't appear
