### ISSUE TITLE
Validation crashes due to large JOY amounts

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3402]
SSIA

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202682200705554) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
@thesan could you elaborate on how to reproduce this bug?

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.154.45.nip.io/network/config.json

According to the changed files, I tested the validation in:

✅ Transfer tokens Modal
✅ Proposal trigger field
✅ Creating new proposal: Create Working Group Lead Opening
✅ Creating new proposal: Set Initial Invitation Count
✅ Creating new proposal: Set Referral Cut
✅ Creating new proposal: Set Max Validator Count
✅ Applying for role Modal
