### ISSUE TITLE
Testing Vesting

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3404]
## Info

Related issue in Pioneer
- #2959 

:warning: Document transaction fees values for each step below in the comments, following this format:
Process name; CLI estimate: x JOY;  Pioneers step1;... StepX of the flow; Pioneer Sign Transaction Modal; Actual fees checked in Polkadot.JS app;

Playground config details: https://54.172.154.45.nip.io/network/config.json
Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Pioneer gh issue for vesting: https://github.com/Joystream/pioneer/issues/2959
Pioneer Designs: https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10540%3A406413 

### Scenarios
Try for a worker (or Lead) in any group.

* [x] In polkadot-js, create a new (staking) account and make a `vesting.vestedTransfer()` of say 0.1 JOY for some amount to this new account. If at height `#n`:
  * locked: 1*10^9 u128 ($JOY 1)
  * perBlock: 100 u128
  * startingBlock: `n+20`
* [ ] Setup this account as a staking account for a member, and try to use it for applying to a role. Stake with 0.09 full amount (ex fees)
  * You may need to free some tokens, through `vesting.vest()`, for transaction fees. 
* [ ] Assuming success:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* [ ] Do a `vesting.vest()`:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* Slash the Worker for half the stake.
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
* Quit and unstake the Worker. Once done:
  * How does a `system.account()` "look"?
  * How does the `balances.totalIssuance()` "look"?
  * How much can you transfer to ANOTHER account (`x` tokens, with `y` fees)
  
- [ ] Verify that that you can’t transfer funds that are locked in vesting
- [ ] Verify cannot claim more funds than unlocked in vesting

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202687862556549) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Pioneer Ticket: https://github.com/Joystream/pioneer/issues/2959

**Comment by dmtrjsg** [comment]
@singulart pls feel free to assign

**Comment by lkskrn** [comment]
<img width="1823" alt="image" src="https://user-images.githubusercontent.com/3365614/184243210-1e8c591b-d160-4ae1-8544-06900025bd62.png">
@dmtrjsg i am getting `system.ExtrinsicFailed vesting.AmountLow` when i try to send `vesting.vestedTransfer()` transaction.

**Comment by oleksanderkorn** [comment]
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/9252017/184243587-e9729848-8307-4889-93cb-9a1c63f0e1e4.png">
@dmtrjsg i am getting `system.ExtrinsicFailed vesting.AmountLow` when i try to send `vesting.vestedTransfer()` transaction.

**Comment by oleksanderkorn** [comment]
Worked with higher lock amount:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/9252017/184244955-5b7e1ead-d7d3-45e4-8280-616f835f1bb1.png">

**Comment by oleksanderkorn** [comment]
Step 2: `vesting.vest()` successful:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3365614/184245855-6b32c6f7-1092-43c9-891b-7d68eb5e4905.png">

**Comment by oleksanderkorn** [comment]
Created more vestings:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/9252017/184247466-1af101d3-6d93-42af-a3aa-9d8d29ef32c2.png">

**Comment by dmtrjsg** [comment]
@oleksanderkorn Can you pls try all of the scenarios listed in the description? 

⚠️ Very important to test this one > 
- [ ] Verify that that you can’t transfer funds that are subject to vesting.

@singulart this ticket is not ready just yet imho.

**Comment by oleksanderkorn** [comment]
@dmtrjsg From UI it is blocked:
17000 JOY available to claim, balance shows 27 JOY.
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/9252017/184974100-33cdcb71-4aee-4d67-853f-9dddd25f46b1.png">

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/9252017/184974254-412c00d1-d191-454f-a5c6-e40bd3a098f6.png">

Balance in polkadot shows full amount:
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/9252017/184974412-80f68428-5ec0-45ea-9d73-fa507ef077d3.png">


Attempt to send more then available in pioneer JOY failed:
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/9252017/184975042-cfdab4be-8103-4903-9098-aae8b54bdc83.png">

Logs:
```
sending 0x3d02844cc62b878a606548b9b2f66fbd62d74a23da57be248316bb12124279e0dcbd3501fce6a45ed8166c1159c7a30c4da74406863577d907e9ae3a91337898eab8af1eb760581cfedd9db3e54779e19a52375145136d5ff59c3b636ea481e73b1fea8b850210000500acc72375af7d04c43706d7f0e684e837c789eeb5d3704bb3dffbaffdf4ff08310b802b1e580001
main.4f04f360.js:19 signAndSend: status :: {"events":[],"status":{"ready":null},"txHash":"0x4f0d7d7e50f797676e8dd1bc4d1e116e2eb8bb79b425cee09024613938c3e98d"}
main.4f04f360.js:19 signAndSend: status :: {"dispatchError":{"module":{"index":5,"error":"0x01000000"}},"dispatchInfo":{"weight":157000000,"class":"Normal","paysFee":"Yes"},"events":[{"phase":{"applyExtrinsic":1},"event":{"index":"0x0508","data":["j4T4GwB1bsdpim1u6h6uV1z6p9YzscbaTzyq8tRhXDiMUawaP",684361642]},"topics":[]},{"phase":{"applyExtrinsic":1},"event":{"index":"0x0507","data":["j4VdDQVdwFYfQ2MvEdLT2EYZx4ALPQQ6yMyZopKoZEQmXcJrT",136872329]},"topics":[]},{"phase":{"applyExtrinsic":1},"event":{"index":"0x0001","data":[{"module":{"index":5,"error":"0x01000000"}},{"weight":157000000,"class":"Normal","paysFee":"Yes"}]},"topics":[]}],"status":{"inBlock":"0x0192a3ea630753edff6310820ea9abbf9827bc953fce1e9de248edc33d0b7c0d"},"txHash":"0x4f0d7d7e50f797676e8dd1bc4d1e116e2eb8bb79b425cee09024613938c3e98d","txIndex":1}
```

Attempt to send 23 JOY Successful:
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/9252017/184976014-60f423f3-eb5d-4a59-9abe-f2e389ad64ed.png">

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/9252017/184976052-ff602059-49c1-41ff-8d7f-3c1e69783951.png">

**Comment by dmtrjsg** [comment]
@oleksanderkorn 

Awesome, thanks a mil for double checking this case 🙌 

Re staking and slashing, any chance to test that as well?:
<img width="564" alt="Screenshot 2022-08-16 at 21 25 54" src="https://user-images.githubusercontent.com/93924525/184978501-32d871fd-7cba-40ac-a6a3-5252527c1a6a.png">

**Comment by oleksanderkorn** [comment]
Created new membership with staking account and sent vested transfer on it:
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/9252017/184982690-8cdc2b5d-50cf-487c-9c82-bf59335dcd0b.png">

**Comment by dmtrjsg** [comment]
@oleksanderkorn thank you for the effort, looking good!

@bwhm cc
