### ISSUE TITLE
Carthage Testing: Proposals Advanced

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3407]
## Context

ℹ️ Playground config details: https://54.172.154.45.nip.io/network/config.json
Pioneer Instance: https://dao-git-carthage-joystream.vercel.app/
Current council size is set to 1; WG leads are pre-hired with each WG has 1 worker; Alice account has JOY balances.

## Test Scenarios
For each of the below, ensure:
- Your changes are executed on chain
- The proposers stake is:
  - freed (if approved)
  - freed minus fee (if rejected/expired/vetoed)
  - slashed (if slashed)
- Note down fees, and compare pioneer estimate to polkadot-js actual
**All the below should be tested in Pioneer**
- [ ] Go through the full "Hire Leads" flow. Hire: Curator, Membership, Forum, Storage, Distribution. All with:
  - some reward
  - "short unstaking"
  - make the opening application (descriptions, questions etc.) different for comparing fees. Note down what you did, the size and the fees.
  Ensure:
  - groups are named correctly
  - openings are rendered correctly
  - applications are presented correctly
  Once done -> Notify testers of [Storage and Distribution](#storage-and-distribution)
- [ ] Update Working Group Budget (for all relevant groups)
  - Use varying amounts, so that:
    - Curator group will not be able to pay the Leads "full" reward
    - Forum group will able to pay the Leads "full" reward exactly (need to calculate expected reward based on hiring block and [payout schedule](https://github.com/Joystream/joystream/blob/431031155d073f9a65f929abef5ebe441999ebf7/runtime/src/lib.rs#L1079)).
    - Storage group gets nothing
    - Distributor groups gets enough for Lead + 2-3 workers for a few days
    - Membership lots, so that members can be created through the faucet
    - After the above is approved, try making a proposal for MORE than what the council has in its budget.
      - Check that budgets and rewards are displayed and processed correctly (in pioneer and the QN) ref. [payout schedule](https://github.com/Joystream/joystream/blob/431031155d073f9a65f929abef5ebe441999ebf7/runtime/src/lib.rs#L1079)
- [ ] Signal
  - Check rendering (☝️ meaning if you create this proposal, all of the parameters/ attributes are displayed correctly on the proposal details page; and on Proposal Voting Modal)
- [ ] Funding Request
  - Create in pioneer, with 1 recipient
  - Create in polkadot.js or script with >1 recipient
    - Check rendering and execution
- [ ] Set Councilor Reward
  - Check rendering and execution
- [ ] Set Membership Price
  - Check rendering and execution
  
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202685572184605) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
⚠️ Funding Request proposal is blocked by: https://github.com/Joystream/pioneer/issues/3453.

The rest we could get started on @singulart pls feel free to assign

**Comment by singulart** [comment]
In test by IvanT

**Comment by ivanturlakov** [comment]
### Funding Request
Blocked by #3453 











### Update Working Group Budget (for all relevant groups)
Blocked by #3504



### Hire Leads Flow - Ok

**Create WG Lead Opening Proposal**
Fees:
Proposal type ~0.18
Staking account ~0.1
Fees reflect text fields(title, rationale, description, application process, questions) symbols amount: ~ 0.03/100chars
Pioneer estimate = Polkadot-js actual
Rendering - Ok
* The proposers stake is:
    * freed (if approved) Ok
    * freed minus fee (if rejected/expired/vetoed) (-8.34)/(-8.34)
    * slashed (if slashed) (-1666,67)

**Fill WG Lead Opening Proposal**
Fees:
Proposal type ~0.18
Staking account ~0.1
Fees reflect text fields(title, rationale) symbols amount: ~ 0.03/100chars
Pioneer estimate = Polkadot-js actual
Rendering - Ok
* The proposers stake is:
    * freed (if approved) Ok
    * freed minus fee (if rejected/expired/vetoed) - (-8.33)/(-8.33)
    * slashed (if slashed) (-833.34)

**Terminate WG Lead Proposal**
Fees:
Proposal type ~0.17
Staking account ~0.1
Fees reflect text fields(title, rationale) symbols amount: ~ 0.03/100chars
Pioneer estimate = Polkadot-js actual
Rendering - Ok
* The proposers stake is:
    * freed (if approved) Ok
    * freed minus fee (if rejected/expired/vetoed) - (-8.33)/(-8.34)
    * slashed (if slashed) (-833.33)




### Signal - Ok
Proposal type 0.57
Fees reflect text fields(title, rationale) symbols amount: ~ 0.03/100chars
General parameters 0.58 0.61 0.62
Chain 6,229,932,299
Rendering - Ok
* Your changes are executed on chain - Ok
* The proposers stake is:
    * freed (if approved) - Ok (-0.23)
    * freed minus fee (if rejected/expired/vetoed) - Ok rjctd(-8.56) - expired(-8,33)
    * slashed (if slashed) Slashed 416.9 Ok
* Note down fees, and compare pioneer estimate to polkadot-js actual - Ok




### Set Councilor Reward - Ok
Fees reflect text fields symbols amount: ~ 0.03/100chars
Proposal type 0.53
General parameters 0.19 0.21
Chain 2,138,842,987
Rendering - Ok
* Your changes are executed on chain - Ok
* The proposers stake is:
    * freed (if approved) - Ok(proposal-created-approved imp)
    * freed minus fee (if rejected/expired/vetoed) - exp (-8,33) - rjctd(-8,34)
    * slashed (if slashed) - Ok
* Note down fees, and compare pioneer estimate to polkadot-js actual - Ok




### Set Membership Price - Ok
Fees reflect text fields symbols amount: ~ 0.03/100chars
Proposal type 0.44
General parameters 0.17 0.19
Chain 1,919,386,595
Rendering - Ok
* Your changes are executed on chain - Ok
* The proposers stake is:
    * freed (if approved) - Ok(proposal-created-approved imp)
    * freed minus fee (if rejected/expired/vetoed) - rjctd(-8.33) - exp(-8.34)
    * slashed (if slashed) - Ok
* Note down fees, and compare pioneer estimate to polkadot-js actual - Ok

**Comment by dmtrjsg** [comment]
@ivanturlakov nice work 💪
