### ISSUE TITLE
Carthage Testing: Creation

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3414]
### Context and Playground Deets

Originating issue:
- #3403 

⚠️  Staging Network details covered in this issue: 
- ~https://github.com/Joystream/pioneer/issues/3484~

> https://atlas-next.joystream.org/network/config.json

### Creation
* [ ] Create at least channels 6 with 2 videos in each
  * Make sure they are received by a (storage) liason and included in the "correct" amount of storage buckets and upon request
  * Make sure they are included in the "correct" amount of distribution buckets and upon request, "distributed"

⚠️ related ticket to test allocation: 
- #3412 
- #3413 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202685466449296) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@kdembler pls advise if we need a separate Atlas instance to the one you guys are using to execute on the above in context of WG leads testing scenarios

**Comment by kdembler** [comment]
In theory there shouldn't be an issue with using our playground for these testing scenarios _but_ our playground is a very simple setup. It contains only a single storage worker, single distribution worker, single distribution bucket and single storage bucket. So the testing concerning assigning correct amount of buckets would be very limited. It would be better to use some proper staging network that has more advanced setup

**Comment by singulart** [comment]
> In theory there shouldn't be an issue with using our playground for these testing scenarios _but_ our playground is a very simple setup. It contains only a single storage worker, single distribution worker, single distribution bucket and single storage bucket. So the testing concerning assigning correct amount of buckets would be very limited. It would be better to use some proper staging network that has more advanced setup

What's the branch you build Carthage flavor of Atlas from? Builder may try spinning up the Atlas on their own.

**Comment by kdembler** [comment]
it's `carthage`: https://github.com/Joystream/atlas/tree/carthage

**Comment by dmtrjsg** [comment]
@singulart staging network ready: 
- https://github.com/Joystream/pioneer/issues/3484

Ticket can be assigned.

**Comment by dmtrjsg** [comment]
@kdembler  pls advise how to proceed here:

<img width="540" alt="Screenshot 2022-08-17 at 19 39 44" src="https://user-images.githubusercontent.com/93924525/185217573-f6e07aa4-6385-4219-8127-a5c6c6c9fe72.png">

<img width="739" alt="Screenshot 2022-08-17 at 19 39 46" src="https://user-images.githubusercontent.com/93924525/185217564-9df89340-7db5-40de-a99b-f333b5e561a2.png">

[LInk to discord](https://discord.com/channels/811216481340751934/910968995379822633/1009500718954197092)

**Comment by dmtrjsg** [comment]
My bad, the chain wasn't configured to do this test. 

Pls try on this one: https://atlas-next.joystream.org/network/config.json

**Comment by polikosi** [comment]
@dmtrjsg hi, how I can verified it 
 ```
Make sure they are received by a (storage) liason and included in the "correct" amount of storage buckets and upon request
Make sure they are included in the "correct" amount of distribution buckets and upon request, "distributed"
```

**Comment by polikosi** [comment]
https://atlas-76qgel2nr-joystream.vercel.app/member/candidate-13?tab=About

**1 channel (candidate 13):**

first video :
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xc87aefdcf86fdf54ce94df97d5f7881154a51c93e9ad695203f2bb43d1599666
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x8bd795782466ea6db5d4e9c8c6e77409334bc30d0abbd6f6dfda3b025575ad03


second video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x32b7365360810c1821c929aa6a4c8d4086510246df59cac580c9cd05223b1971
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x84dc66b99c9481af575a9314aee2ee15b4fda07cacab0298cea1b0f9ffcdab69


**2 channel (candidate-13):**
create channel:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xc9879c7394e15af7b290584cebcb935641c005ed7d15a642f0105e41e742d7ac
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x551800402dcd6b24c65f596c4d4a4dc093ffcdd9ad673ea0cf2f0f78e93b4891

first video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x736e09eb33549277eb9ee3793437a0f3165323217c64b2e42905dd1d37187343
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x89e0ae3c61ddf91d3d5aae0f0ba728fdce035b24cded8619499293a13edb39f8

second video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x0dc6e4c839ca4d704cb14620e76688745b119d273b001d7a7a0872760e7f4ada
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x5e41cd816ba486d122495c053938c06bee68961341dade41926c86018acd51c3

**3 channel (candidate-13):**
create channel:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x7702c46a6e06596bd05a9363b64acdaed82778a8254e8ad32b0244579d74838e
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xdf5cd11226bcc91120b9dcaa9ad3005ac1b452169fa4dcacaf2f7fa08f36b29b

first video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x10143910b39eb7b6bc2d35c7b375d69c8918bd262d3acd73d2f99e6503e90d9a
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x5991bb440a5ba156c1828292dc8ff09d9ec128fe2c130da90ab4a5dd7a245e5b

second video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x302409e50f1df806f8cf3e876daf861255560fedc7ad6461dbde06f52717ec50

**4 channel (candidate-13):**
create channel:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x5c84f9ad4aa7313de969374ba1858455f3d673173b1427742057b962a5377021
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xb9e910f4fe1d01ee09d756de714dc05270f57c73136a6da57cc990868c340c82

first video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x93527857865e1b2207887e9ef4fe4eb2e1e795a61e755cd15ba65bfc9101e78f
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x8912ba995defa1cabae82399e3a2abd1fd75c11881580d9732ac77c44e8b5506

second video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x33e9b4a5c8064cc34db27dba7205058d7cea3dfb9c998ab5fb99787aca3b95bd
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xf98d26d04c1eaf8be064eab9505b423203a1d4aa7e736f898b63333e0f50c2a3

the third video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x540f420d8a540d9804ef62d9cf589b4821c2e76587b84d1344b6ba26a2b11a61
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x804d53962f1f22a67ddbd0bd2f46f766cf7c153e1cd52f7b9a92bf1a56a237e1

**5 channel (candidate-13):**
create channel:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x675f45a8c058d14239631655499ad5f44f1a70b4039e9ddada02bf289c0c081d
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x7811138687c03164a81d3f627b8a5ca203c477e85d9ee954f69d6f7a12bdc9cc

first video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x06118ab3e129b5839fd325c24b51825508073699f4d8eb9bc032d9ecf11c4812
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x96a24a7bfdb50ad582c18d7488f58b13324366873129edc21a1e9c402238cd62

second video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xe2fdb7853fe0151d73af3194e936b3d13692b75800ade362fe594dfd2e4b54e0
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xcca5c789a8acc23d5021a2789bf8783095d24a0bb326d145330ed4d2df235f3b

the third video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x0a900fa7a9ffb0ac48bf5591f9cd33329f3bc742d5d7676111f21ba9f1e6e913
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x513b2507cc8281b140c72fbea7fd5761fe52e1b65d9e783843522e2c3e9f1249

**6 channel (candidate-13):**
create channel:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x939cfbe45df724a5218b8fb33c2a46bc2099dd5883715695f9521ec6af5ec2b8
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x47c4cc325bcce062502934709bdd514536dd4bcb57bd7a4a1218236a08a67d91

first video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x4d263dbf9ef69ac5741b3e4f13e6a196cd10e924137f905dc1ea08410bd295fa
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x9602acd3eb4d81a3edee1f6aa8a78bddb77ac3d5aa76d4c5de98257c565f0feb

second video:
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x4dccdede93f130ca30e41bbb541310478182e0777ea0fc5d06db6224d2336d2c
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x93b4ff579ca108a832903f6634f51a91b38ade5f34bb0402c2fed10e7633ae72
