### ISSUE TITLE
QN didn’t update after new account created

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#3422]
Tested on https://dao-git-carthage-joystream.vercel.app

Action: Create membership for a new empty account (with faucet)
- QN didn’t update after transaction success, membership shows up only after page reload

**Comment by ivanturlakov** [comment]
Guys, pls give me a tip on how to test it, because I am already created one account with a faucet

**Comment by WRadoslaw** [comment]
I would create new account in extension and hide accounts with already existing memberships, that way Pioneer should think that you are a newcomer. Btw make sure to have 0 balance on this newly created account @ivanturlakov

**Comment by ivanturlakov** [comment]
@WRadoslaw thx, tried this approach, and also tried using VPN but still got a faucet error
<img width="1440" alt="Снимок экрана 2022-08-20 в 15 44 23" src="https://user-images.githubusercontent.com/46903215/185747008-72420bdc-a4ba-46a4-8144-7ee22a3632c2.png">

@dmtrjsg are we all right with the https://54.172.154.45.nip.io/member-faucet/register?
