### ISSUE TITLE
Create free membership/Add Membership modals. "Member Name" field validation.

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#3423]
Tested on https://dao-git-carthage-joystream.vercel.app/

"Member Name" field doesn't allow spaces, so user cant input "John Doe"

<img width="797" alt="Снимок экрана 2022-07-30 в 13 20 39" src="https://user-images.githubusercontent.com/46903215/181906065-de8feb2f-c5d6-4d7a-9abc-1f17ed396f58.png">

**Comment by dmtrjsg** [comment]
Handle should not allow spaces -> show validation message "Spaces not allowed"
Member name should allow for spaces

**Comment by ivanturlakov** [comment]
Tested on staging ✅

<img width="798" alt="Снимок экрана 2022-08-16 в 16 29 50" src="https://user-images.githubusercontent.com/46903215/184891887-2c41c19d-324b-4627-b0e4-3da7c726d9b9.png">
<img width="917" alt="Снимок экрана 2022-08-16 в 16 30 24" src="https://user-images.githubusercontent.com/46903215/184891893-b8b3dad3-ed54-42ac-9bfd-9b9a9287f402.png">
