### ISSUE TITLE
[USERSNAP] Fill Distributors WG Lead: Wrong group and candidate in a proposal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3425]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/16
**Fields**:

* Houston, we have a problem.: Fill Distributors WG Lead: Wrong group and candidate in a proposal
* Comment: The proposal created should have the correct group and candidate.
* Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x9da2cf7e89253a4e320e55bea9a561ee60c0337c700952b7f70f98e68ae99745
* Feedback: GH: oleksanderkorn DS: lkskrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8724a4f9-a430-4501-b008-d5e12a9f057b-annotated_b1e725e6-f729-4209-bb08-6e8ffd55c4a2.png?etag=d6be99aceac52d311f281e775364c092)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8724a4f9-a430-4501-b008-d5e12a9f057b-annotated_b1e725e6-f729-4209-bb08-6e8ffd55c4a2.png?etag=d6be99aceac52d311f281e775364c092)_

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1920x1200
**Browser size**: 1920x674
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/2128a706-49c6-44a9-ae76-6a313cb76b0e_screen_recording_48176bd5-1f15-4810-9b2d-457b9cb17417.webm?etag=daa903f5fcb96986238a7207a810f8d5)**
**[Open #310 in Usersnap](https://app.usersnap.com/l/feedback/ea098793-5a25-4d53-9474-841eb747f46a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202697168564799) by [Unito](https://www.unito.io)

**Comment by WRadoslaw** [comment]
Will be fixed by #3441
