### ISSUE TITLE
[USERSNAP] Proposal to fill Lead opening shows wrong opening

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3429]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/20
**Fields**:

* Houston, we have a problem.: Proposal to fill Lead opening shows wrong opening
* Comment: 1. Create an opening to fill Storage Lead role

1. Chose correct opening and a person
1. Sign and submit
1. Observe the opening data shows the wrong opening and the wrong candidate (Forum)

It seems that Pioneer sends wrong extrinsics data

* Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/43995
* Feedback: isonar

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1b40dc23-0e42-4f23-80c0-a5fccf31c7dd-annotated_73b77a41-37b6-4216-9be4-36f341ad0708.png?etag=eb483f64becaab8f3d0a2073c3c27177)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1b40dc23-0e42-4f23-80c0-a5fccf31c7dd-annotated_73b77a41-37b6-4216-9be4-36f341ad0708.png?etag=eb483f64becaab8f3d0a2073c3c27177)_

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1512x982
**Browser size**: 1512x791
**[Open #311 in Usersnap](https://app.usersnap.com/l/feedback/67e23913-1e7c-43c6-bc82-e993483b27ac?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202697217271323) by [Unito](https://www.unito.io)

**Comment by freakstatic** [comment]
@dmtrjsg this seems a regression bug 
https://github.com/Joystream/pioneer/issues/2340

**Comment by WRadoslaw** [comment]
Will be fixed by #3441
