### ISSUE TITLE
[USERSNAP] Pioneer crashing when opening election page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3431]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/election
**Fields**:

* Houston, we have a problem.: Pioneer crashing when opening election page
* Comment: Getting an empty page and the following error on the console
Error: Number can only safely store up to 53 bits

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/89d64b45-08b5-475b-9e1d-5dddc72e6013-annotated_423aa1d9-7a7d-4a33-b98d-926a7575fbd7.png?etag=7ad6073c958dc8372b204cecc52054a2)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/89d64b45-08b5-475b-9e1d-5dddc72e6013-annotated_423aa1d9-7a7d-4a33-b98d-926a7575fbd7.png?etag=7ad6073c958dc8372b204cecc52054a2)_

**Browser**: Chrome 103 (Linux)
**Screen size**: 2560x1440
**Browser size**: 1244x1324
**[Open #313 in Usersnap](https://app.usersnap.com/l/feedback/5e18de8e-7f8a-4843-bff6-7d8099f71665?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202808293211279) by [Unito](https://www.unito.io)

**Comment by freakstatic** [comment]
![image](https://user-images.githubusercontent.com/7486476/182004536-e1f5ccae-b518-4976-839b-f2af0d90eec2.png)

**Comment by freakstatic** [comment]
Some debug information provided by @lkskrn

![image](https://user-images.githubusercontent.com/7486476/182007492-678fe133-0f4f-4703-8a95-1fc46a5fc3c7.png)

**Comment by freakstatic** [comment]
Example of one election where the crash is happening:
https://dao-git-carthage-joystream.vercel.app/#/election/past-elections/0000006i

**Comment by ivanturlakov** [comment]
Tested on staging

<img width="1440" alt="Снимок экрана 2022-08-16 в 17 02 34" src="https://user-images.githubusercontent.com/46903215/184899573-f3a98f48-d522-4045-a25e-288c8ba737f7.png">

Example of one election where the crash is happening on the Revealing stage:
https://dao-git-carthage-joystream.vercel.app/#/election/past-elections/0000012y

Steps to reproduce:
1. Go to an election, Add 2 candidates (Alice and someone else)
2. Vote for Alice 1 000 000
3. Reveal your vote

**Comment by dmtrjsg** [comment]
Ready to be retested

**Comment by ivanturlakov** [comment]
✅ 👍 Tested on https://dao-git-carthage-joystream.vercel.app/#/election/past-elections/0000017f
<img width="1206" alt="Снимок экрана 2022-08-19 в 00 32 09" src="https://user-images.githubusercontent.com/46903215/185500057-e213d1d5-1d11-49d1-be42-3cb4f8fb5cfb.png">
