### ISSUE TITLE
Carthage still shows "tJOY" token

### ISSUE THREAD

**Issue by freakstatic** [Joystream/pioneer#3432]
In Carthage tJOY will not exist anymore but it's being used all over pioneer. It should be replaced by "JOY"

**Comment by freakstatic** [comment]
An example of the /#/profile page

![image](https://user-images.githubusercontent.com/7486476/182007166-2f87d1fc-c855-405e-82cb-de400611e7b3.png)

**Comment by dmtrjsg** [comment]
@freakstatic I think we are adding the denomination for now since we are on testnet, and JOYs will be shown only with mainnet release.
