### ISSUE TITLE
[USERSNAP] the "proposal" page does not open after clicking on the proposal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3436]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/36
**Fields**:
- Houston, we have a problem.: the &#34;proposal&#34; page does not open after clicking on the proposal
- Comment: the &#34;proposal&#34; page does not open after clicking on the proposal
- Feedback: git - polikosi

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2502e2a8-21f8-4b16-942f-73a0f10e5796-annotated_a8248f54-d6ba-4d2a-8d5d-e493349e7bb4.png?etag=8bf738a99c5ea3397b12760e0480d4d4)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2502e2a8-21f8-4b16-942f-73a0f10e5796-annotated_a8248f54-d6ba-4d2a-8d5d-e493349e7bb4.png?etag=8bf738a99c5ea3397b12760e0480d4d4)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x754
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/aa68d3a8-cadb-4fb0-82a5-9e5f4d7eb2aa_screen_recording_a2caa0aa-b680-4340-acee-4cc0112c823e.webm?etag=ecceadfb6bf58dad0de30cf8bb836d42)**
**[Open #316 in Usersnap](https://app.usersnap.com/l/feedback/77441382-f4f4-4cf7-a67c-91eb37777951?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
<img width="794" alt="Screenshot 2022-08-01 at 09 07 30" src="https://user-images.githubusercontent.com/93924525/182102888-31a4d29a-0b62-408a-9a5e-b211df93472a.png">

**Comment by polikosi** [comment]
Verified on https://dao-git-carthage-joystream.vercel.app/

Work as expected
![Screenshot_181](https://user-images.githubusercontent.com/80429191/184297208-c6b969e5-7e9b-40e5-8f06-8b010814b67b.png)
