### ISSUE TITLE
[USERSNAP] I have 4 invites on my balance. Trying to transfer 2 invites and validation fails with "You only have > 0.01 invites left."

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3440]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/profile/memberships
**Fields**:

* Houston, we have a problem.: I have 4 invites on my balance. Trying to transfer 2 invites and validation fails with &#34;You only have &gt; 0.01 invites left.&#34;
* Comment: It is expected that the transfer is possible with a sufficient balance.
* Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/46aeb7a5-8355-4397-a68f-318074140be6-annotated_2edc7b38-b146-4264-a4e0-ea3e5f19fcbd.png?etag=ba927c839617b6bc9ff3eee6626995d9)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/46aeb7a5-8355-4397-a68f-318074140be6-annotated_2edc7b38-b146-4264-a4e0-ea3e5f19fcbd.png?etag=ba927c839617b6bc9ff3eee6626995d9)_

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x789
**[Open #318 in Usersnap](https://app.usersnap.com/l/feedback/0dea13b0-7574-4578-bb03-e925ba18aec0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202701178255690) by [Unito](https://www.unito.io)

**Comment by singulart** [comment]
Verified on https://dao-git-carthage-joystream.vercel.app/#/profile/memberships, works as expected.

Separate issue https://github.com/Joystream/pioneer/issues/3486 reported.
