### ISSUE TITLE
Remaining period timer doesn't update on the Election page

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3443]
SSIA

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/
wss://34.235.154.53.nip.io/ws-rpc

### ✅ Announcing period
<img width="1189" alt="Снимок экрана 2022-10-04 в 17 27 45" src="https://user-images.githubusercontent.com/46903215/193854652-d2f1d672-5543-4069-82f5-73c58b7eda00.png">
<img width="1183" alt="Снимок экрана 2022-10-04 в 17 39 08" src="https://user-images.githubusercontent.com/46903215/193854646-faaf6483-6f03-454a-82af-d066a7e65412.png">

### ✅ Voting period
<img width="1194" alt="Снимок экрана 2022-10-04 в 17 43 03" src="https://user-images.githubusercontent.com/46903215/193854645-c2723b3d-9554-48a6-aed0-15833946e713.png">
<img width="1183" alt="Снимок экрана 2022-10-04 в 17 44 55" src="https://user-images.githubusercontent.com/46903215/193854642-81f45edf-26d4-4c9f-9248-7fa4ad994fe9.png">

### ✅ Revealing period
<img width="1183" alt="Снимок экрана 2022-10-04 в 17 52 55" src="https://user-images.githubusercontent.com/46903215/193854640-63670937-4085-4d66-8caf-71dde37ac4b6.png">
