### ISSUE TITLE
[USERSNAP] Error & white screen when creating proposal(signal)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3449]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/proposals/current
**Fields**:

* Houston, we have a problem.: Error &amp; white screen when creating proposal(signal)
* Comment: Page keep working
* Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xed2e0a4e42e8160c060919e521fcd835eea544369b9bef93e4594c31a7b79831
* Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d2a1d11c-4c8f-4433-b96e-43267b67f11d-annotated_a5bbf9bd-a25e-4247-a629-abffc718f44e.png?etag=ab7763f25aec2c7f7c36047a80345a8a)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d2a1d11c-4c8f-4433-b96e-43267b67f11d-annotated_a5bbf9bd-a25e-4247-a629-abffc718f44e.png?etag=ab7763f25aec2c7f7c36047a80345a8a)_

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x293
**[Open #319 in Usersnap](https://app.usersnap.com/l/feedback/29212a8d-a67a-4e24-8c8d-130d6fd6dbb6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202704974190024) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
<img width="1440" alt="Снимок экрана 2022-08-01 в 19 45 52" src="https://user-images.githubusercontent.com/46903215/182201108-a3ed7fc9-cba7-446e-aa4d-a7f97cb7545f.png">

**Comment by dmtrjsg** [comment]
Resolved by #3447
