### ISSUE TITLE
[USERSNAP] Funding proposal transaction fails

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3453]
## Scope

QA:

- [ ] ⚠️ this ticket needs to be retested on the newest playground:

>https://54.172.204.195.nip.io/network/config.json](https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.204.195.nip.io/network/config.json)

## Context

**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/proposals/current
**Fields**:

* Houston, we have a problem.: Founding proposal transaction fails
* Comment: Expecting created proposal
* Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x8e857868d196d8592a0cb4515b94e2eeafae5f4b31344099cf0efdb1d6a555c1
* Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/532992a2-1d96-4d27-bd4d-a46a60d1f1c5-annotated_4d4c1e27-8d43-41f8-8b21-1788ac6ef0cd.png?etag=f621caee27ee0441a82779931123690b)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/532992a2-1d96-4d27-bd4d-a46a60d1f1c5-annotated_4d4c1e27-8d43-41f8-8b21-1788ac6ef0cd.png?etag=f621caee27ee0441a82779931123690b)_

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x531
**[Open #320 in Usersnap](https://app.usersnap.com/l/feedback/a7c29ae2-2594-40d7-a204-5368076c7492?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202705820155406) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
<img width="1440" alt="Снимок экрана 2022-08-02 в 13 23 28" src="https://user-images.githubusercontent.com/46903215/182353844-ba0cc1e9-c5b5-4a9e-9fdb-a9ada16cd37f.png">

**Comment by WRadoslaw** [comment]
This might be runtime bug. 

I traced the origin on the error in runtime and it is getting thrown in two cases ⬇️ 
```
                    ensure!(
                        funding_request.amount != Zero::zero(),
                        Error::<T>::InvalidFundingRequestProposalBalance
                    );

                    ensure!(
                        funding_request.amount <= <BalanceOf<T>>::from(MAX_SPENDING_PROPOSAL_VALUE),
                        Error::<T>::InvalidFundingRequestProposalBalance
                    );
  ```

1. When funding balance is zero
2. When funding balance exceed the `MAX_SPENDING_PROPOSAL_VALUE` which is set to 
`const MAX_SPENDING_PROPOSAL_VALUE: u32 = 50_000_000_u32;`

But after introducing the decimals even 1 tJOY (which is `10_000_000_000`) exceeds this value. Currently user has to input value less than `0.05` for proposal to execute (I might've missed one zero :D)

Funding request of 100 BDH that went through: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xfa0ea176ed340cb061baf87548214316e2832cc467c475a858dfce23527ea779

**Comment by dmtrjsg** [comment]
[Raised comment,](https://joystreamworkspace.slack.com/archives/C03JXJZC9FT/p1659457384830259) awaiting feedback to proceed.

**Comment by bedeho** [comment]
Seems correct @WRadoslaw , feel free to open a PR where this value is increased. I would expect there to be lots of issue like this with all nominal value constraints relating to proposals, such as min stake, max stake, etc.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.154.45.nip.io/network/config.json

Stuck on validation, any amount fails
<img width="1258" alt="Снимок экрана 2022-08-17 в 13 43 30" src="https://user-images.githubusercontent.com/46903215/185099937-1af54fec-5e6d-442c-b7e4-7ae6abbd1a5c.png">

**Comment by ivanturlakov** [comment]
upd

Validation works well now, but the initial error still occurs
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x066f89380b9ecfe94796beb2794df233c42ccd94fe4036f3c5e167ad060d0934

**Comment by dmtrjsg** [comment]
Retested, "Transaction failed" message shown:

https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x8c46549f0d1cef555829fb18f4a85185f3ee6e3582251a9238c5ec84d2ebe0ff

**Comment by dmtrjsg** [comment]
Tested on wss://atlas-next.joystream.org/ws-rpc
