### ISSUE TITLE
[USERSNAP] Announce candidacy transaction fails

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3456]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/election
**Fields**:
- Houston, we have a problem.: Announce candidacy transaction fails
- Comment: Announce candidacy transaction success
- Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xf3ab5fc1ed60f48633edee9eedf2589b278882b619fb62e97a98a8fac0849fab
- Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e21d849a-fdcd-41a2-b0a3-59c9f152dfed-annotated_1150afc2-fa6b-4d4a-b1bf-d825cf03434f.png?etag=4520d19d9f13787dc2fce59346d60c7c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e21d849a-fdcd-41a2-b0a3-59c9f152dfed-annotated_1150afc2-fa6b-4d4a-b1bf-d825cf03434f.png?etag=4520d19d9f13787dc2fce59346d60c7c)*

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x531
**[Open #321 in Usersnap](https://app.usersnap.com/l/feedback/24942804-9eaa-4df4-a381-2165a3454b7f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
<img width="1440" alt="Снимок экрана 2022-08-02 в 17 12 38" src="https://user-images.githubusercontent.com/46903215/182396568-8d686b7e-9bac-4b1d-9ed9-7fb6adb0cc7c.png">

**Comment by dmtrjsg** [comment]
@ivanturlakov 

The account you are using is not bound to the member, how did you manage to do it? CLI or Pioneer? (see one from PIoneer for Member12 (pased to URL) and one in the polkadot.js)

<img width="760" alt="Screenshot 2022-08-05 at 09 34 05" src="https://user-images.githubusercontent.com/93924525/183037610-29513b21-f76b-4e99-a6b5-15c7653b67b7.png">

We are puzzled as per how did you select the unbound account and confirmed it?

**Comment by ivanturlakov** [comment]
@dmtrjsg

I just tried to announce candidacy and everything went well, without errors

>The account you are using is not bound to the member, how did you manage to do it? CLI or Pioneer? (see one from PIoneer for Member12 (pased to URL) and one in the polkadot.js)

I definitely did that in Poiner. The referral is Alice, I probably created it through the faucet
<img width="1184" alt="Снимок экрана 2022-08-05 в 13 06 55" src="https://user-images.githubusercontent.com/46903215/183056451-65ee6bab-17da-4725-8ac2-93bf501236de.png">


Maybe that's the reason
<img width="546" alt="Снимок экрана 2022-08-05 в 13 16 38" src="https://user-images.githubusercontent.com/46903215/183057152-deb7a17e-2e95-45d8-aa18-56a98c726edb.png">
<img width="548" alt="Снимок экрана 2022-08-05 в 13 17 03" src="https://user-images.githubusercontent.com/46903215/183057158-641e2941-3249-4d88-8ca0-10a3a8195e27.png">

**Comment by dmtrjsg** [comment]
@ivanturlakov none of this account was a the staking acc that caused the error. if you can reproduce it with the video rec we can try and debug, but without hardly so.

Closing for now as "cannot reproduce".
