### ISSUE TITLE
[USERSNAP] Council page error after council reward changed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3457]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/council
**Fields**:
- Houston, we have a problem.: Council page error after council reward changed
- Comment: ...
- Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/deb04408-5e74-4154-81a6-2989df6ae144-annotated_e7ccbbb8-9bfb-4885-88a7-65106019305c.png?etag=6d8633817db2f10b1a4f16fc17b87553)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/deb04408-5e74-4154-81a6-2989df6ae144-annotated_e7ccbbb8-9bfb-4885-88a7-65106019305c.png?etag=6d8633817db2f10b1a4f16fc17b87553)*

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x361
**[Open #322 in Usersnap](https://app.usersnap.com/l/feedback/afb66439-dd49-45ce-96bd-906866dbf1bb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
<img width="1438" alt="Снимок экрана 2022-08-02 в 17 50 58" src="https://user-images.githubusercontent.com/46903215/182405198-ed39533f-0d3b-47bc-aa46-cdb0525cb923.png">
it happened after this proposal executed https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/47

**Comment by ivanturlakov** [comment]
Tested on staging ✅

<img width="1208" alt="Снимок экрана 2022-08-16 в 16 17 08" src="https://user-images.githubusercontent.com/46903215/184889392-2849df21-35a5-4550-a943-55f1af980d26.png">
<img width="1208" alt="Снимок экрана 2022-08-16 в 16 17 18" src="https://user-images.githubusercontent.com/46903215/184889407-d9242bfb-f753-43d2-a983-b93173c2d2f1.png">
