### ISSUE TITLE
Hide rationale from Slash and Decrease WGL stake details.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3458]
## Context

https://github.com/Joystream/pioneer/issues/3397#issuecomment-1202813480

## Scope
As a temp measure
- [ ] remove the rationale from "View more" tab on Decrease and Slash WGL Proposal Activities > view more
- [ ]Update "Slashed by" to "Reduced by" in the details section"

![Screenshot 2022-08-02 at 16.26.43.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/a3934923-f678-465c-aac2-ff34b58e6021)

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/working-groups
wss://44.201.112.198.nip.io/ws-rpc



<img width="551" alt="Снимок экрана 2022-11-09 в 14 03 09" src="https://user-images.githubusercontent.com/46903215/200899383-6782c647-8c6e-4d55-b434-4ec666d993f8.png">

### ⚠️ Stake increased but title says - Slashed
<img width="534" alt="Снимок экрана 2022-11-09 в 18 26 50" src="https://user-images.githubusercontent.com/46903215/200899395-277f91f7-62be-4d35-ba7d-626772f41306.png">

<img width="286" alt="Снимок экрана 2022-11-09 в 19 26 14" src="https://user-images.githubusercontent.com/46903215/200899402-a394034a-eb19-4f34-8f82-60f9c212f07c.png">

**Comment by polikosi** [comment]
Decrease Working Group Lead Stake
![image](https://user-images.githubusercontent.com/80429191/205280641-6d5719ef-91d3-4228-902e-31f570e4adae.png)

Slash Working Group Lead
Can't open "Read more"
https://user-images.githubusercontent.com/80429191/205281834-0b3a6cca-5c2c-47e3-934d-830131f722fb.mp4

**Comment by traumschule** [comment]
My bad, forgot about my own PR above. Please test with https://dao-git-fork-traumschule-fix-wgl-activities-3458-joystream.vercel.app/

**Comment by mkbeefcake** [comment]
I see. This link is maintenance, so I just checked the code. It looks like good, and I will go to the next issue. 

> My bad, forgot about my own PR above. Please test with https://dao-git-fork-traumschule-fix-wgl-activities-3458-joystream.vercel.app/

**Comment by thesan** [comment]
@traumschule @mkbeefcake while Pioneer is in maintenance all the `dao.` environement won't be available but the `pioneer2.` still work. E.g this issue could be QA at: https://pioneer-2-git-fork-traumschule-fix-wgl-activit-9c9b61-joystream.vercel.app/

However since it's now merged on the `dev` branch, it's better to do the QA on https://pioneer-2.vercel.app/

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/#/working-groups/openings
wss://34.230.5.182.nip.io/ws-rpc

### Stake increased
<img width="242" alt="Снимок экрана 2023-01-07 в 14 13 14" src="https://user-images.githubusercontent.com/46903215/211150116-8a1956e9-e056-4086-8a8c-d826184c2df0.png">
<img width="326" alt="Снимок экрана 2023-01-07 в 14 11 35" src="https://user-images.githubusercontent.com/46903215/211150068-35900355-e434-4e37-b984-d7bf9b8efc54.png">


### Stake reduced
<img width="233" alt="Снимок экрана 2023-01-07 в 14 16 08" src="https://user-images.githubusercontent.com/46903215/211150198-9ffbed81-7b30-4c4d-835e-c45e9dff3fa0.png">
<img width="313" alt="Снимок экрана 2023-01-07 в 14 16 48" src="https://user-images.githubusercontent.com/46903215/211150216-4800b5ed-f0e7-4bae-8435-79a7fdfd92af.png">

### Decrease Working Group Lead Stake
<img width="243" alt="Снимок экрана 2023-01-07 в 14 26 06" src="https://user-images.githubusercontent.com/46903215/211150544-e95de8c7-52b6-4f8d-a887-86e2864de746.png">
<img width="323" alt="Снимок экрана 2023-01-07 в 14 26 15" src="https://user-images.githubusercontent.com/46903215/211150546-a091e6e8-dbcb-4005-86d5-2b2d34d2495e.png">


### Slash Working Group Lead
<img width="248" alt="Снимок экрана 2023-01-07 в 14 27 38" src="https://user-images.githubusercontent.com/46903215/211150634-79bf0bc9-0b43-4b10-85ee-47901b546352.png">
<img width="310" alt="Снимок экрана 2023-01-07 в 14 27 54" src="https://user-images.githubusercontent.com/46903215/211150637-bb82fdd6-cdd0-47e4-9a8b-e3ca6327403d.png">
