### ISSUE TITLE
Bug comments on the forum

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#3462]
https://dao.joystream.org/#/forum/thread/649?post=1263
![image](https://user-images.githubusercontent.com/84832436/183053626-6fe200be-22e4-437c-ac86-b2579a3b2cab.png)
The forum comment moves to the top of the page. Perhaps this is because the main post is being edited

**Comment by chrlschwb** [comment]
I don't think this issue stand anymore.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/37
wss://34.230.5.182.nip.io/ws-rpc

No issues found with standard actions

<img width="1440" alt="Снимок экрана 2023-01-26 в 17 21 21" src="https://user-images.githubusercontent.com/46903215/214875034-eb3e5cfa-7fef-42cb-9624-07fad22ce0d2.png">
