### ISSUE TITLE
Fix deleted sub-category display in Pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3464]
## Context
Forum smoke testing results" https://joystream.notion.site/Report-Smoke-testing-Forum-4e55316df35c4d94b0f2380dadf20b46

⚠️ pls point the PR to Carthage branch

## Scope
* [ ] Fix erroneous display of deleted subcategory in Forum

![Screenshot 2022-08-05 at 13.41.16.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/e3034fd5-201a-4d3c-896d-4a5c3d1d303f)-

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202727563990196) by [Unito](https://www.unito.io)

**Comment by singulart** [comment]
SP estimate is missing

**Comment by dmtrjsg** [comment]
@singulart added

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.154.45.nip.io/network/config.json

Category "Test subcategory" has been created in "test".

<img width="1183" alt="Снимок экрана 2022-08-29 в 15 37 26" src="https://user-images.githubusercontent.com/46903215/187203745-6cfd35db-8f12-4dde-b56b-067145854b60.png">
<img width="1180" alt="Снимок экрана 2022-08-29 в 15 38 16" src="https://user-images.githubusercontent.com/46903215/187203755-caa84900-5380-42c1-abe7-ccbd6176bf88.png">


Category "Test subcategory" has been deleted in "test".

<img width="1183" alt="Снимок экрана 2022-08-29 в 15 39 56" src="https://user-images.githubusercontent.com/46903215/187203759-029f8f8a-1928-4628-a0ee-c4ef09dc98fb.png">
<img width="1181" alt="Снимок экрана 2022-08-29 в 15 40 11" src="https://user-images.githubusercontent.com/46903215/187203768-8daf55af-40ef-4ffa-bee9-6d80fb7d7c7a.png">
