### ISSUE TITLE
Testing that 100% locked funds from faucet can be used for starting as Pioneer Member

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3468]
⚠️ blocked by> 
- https://github.com/Joystream/pioneer/issues/3487

Current faucet config does not allocate sufficient funds to test Proposal creation scenario.

## Scope
Verify that even just using invitation funds, that are 100% locked (except for fees), we can do basic operations in Pioner because those actions include value payments above and beyond fees, for example bloat bonds and storage fees. 

Very that fresh members with funds obtained exclusively from faucet:

* [x] Can create new membership (for unregistered account and receive JOY allocations)
* [x] 🆕 ~Can~ Cannot invite other members (invitation from faucet accs must be 0) 
* [x] 🆕 Cannot purchase new memberships
* [x] Can post to forum - can create uneditable post - [tx](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xce56d83ebf07cb6c13974ea3f2200d53d62506f382778eb7d4ef788ad2b3c9a2)
* [x] Can create proposal (⚠️  To test proposals please Use Alice account to transfer more than 400 JOY (minimum staking req for Signal) via `giftMembership` extrinsic.)
* [x] Can vote for candidates to council

:warning: Playground to test on: ~https://54.242.207.183.nip.io/network/config.json~ 
🆕 https://atlas-next.joystream.org/network/config.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202735901165096) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@singulart pls feel free to assign

**Comment by singulart** [comment]
@dmtrjsg How to obtain "invitation" funds?

**Comment by dmtrjsg** [comment]
@singulart By creating new membership with Faucet, sorry config dns seem to have been updated since to: https://atlas-next.joystream.org/network/config.json

**Comment by polikosi** [comment]
@dmtrjsg I've never been to the WGL forum but I can try

**Comment by dmtrjsg** [comment]
@polikosi upd:
1. Invitation lock should not be possible to use for inviting other members. To test this pls Approve proposal to "Increase Invitation WG funds". 
2. Invitation lock should not be possible to use for posting to forum rn as we are still working on the fix for it to cover bloat bond fees and storage fees. So this scenario would need to be retested at later stage.

**Comment by dmtrjsg** [comment]
⚠️ Just re-tested for network:  /https://atlas-next.joystream.org/network/config.json (54.242.207.183)
<img width="901" alt="Screenshot 2022-08-15 at 10 55 22" src="https://user-images.githubusercontent.com/93924525/184615405-419b3c80-d4bb-4d12-99dd-115864277ea8.png">
<img width="774" alt="Screenshot 2022-08-15 at 10 55 08" src="https://user-images.githubusercontent.com/93924525/184615408-149fceec-3351-47b3-9ef1-3d47bd162a78.png">
<img width="586" alt="Screenshot 2022-08-15 at 10 54 56" src="https://user-images.githubusercontent.com/93924525/184615410-866e3f93-90b2-4cf8-a7fc-8c432b2e4f35.png">

☝️ Tried for network: https://34.238.255.182.nip.io/network/config.json Membership for brand new account was created successfully. 

@singulart it should not be possible to use invitation lock for purchasing new memberhsips (meaning "+Add Membership") for an account that already has membership.

Raised this issue to address messaging upd: 
- https://github.com/Joystream/pioneer/issues/3497

**Comment by dmtrjsg** [comment]
🚫  Forum thread cannot be created with Invitation Lock:

<img width="481" alt="Screenshot 2022-08-16 at 12 58 28" src="https://user-images.githubusercontent.com/93924525/184874326-9742d691-1c06-4ff7-a57e-96654a8aba4a.png">

[12:15](https://joystreamworkspace.slack.com/archives/D03HLABA8MA/p1660648535157219)
[https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x1d54bf5c92bb215c5e[…]595dc4a1111b20c9714f1687323fc5bb14768](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x1d54bf5c92bb215c5eebf4f1bb3595dc4a1111b20c9714f1687323fc5bb14768)

**Comment by dmtrjsg** [comment]
⚠️ To test proposals please Use Alice account to transfer more than 400 JOY (minimum staking req for Signal) via `giftMembership` extrinsic. 

Current faucet config does not allocate sufficient funds to test Proposal creation scenario.

**Comment by dmtrjsg** [comment]
@polikosi 
 
 The faucet default amount of invitation lock has been increased to 5000 Joy. This should be enough to test proposals. 
 
 Please feel free to proceed :)

**Comment by polikosi** [comment]
I can't create a new account here https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://atlas-next.joystream.org/network/config.json
![image](https://user-images.githubusercontent.com/80429191/185960396-5449ff08-52b8-4ac4-9207-19d252beee20.png)

**Comment by polikosi** [comment]
**- Can create acc** 

![image](https://user-images.githubusercontent.com/80429191/186110322-0f3f6277-69ed-435b-9635-805114f5a8c2.png)

**- Cannot invite other members (invitation from faucet accs must be 0)**

![image](https://user-images.githubusercontent.com/80429191/186110601-aff1813a-db79-4e85-9cb9-244f547a5c6c.png)
![image](https://user-images.githubusercontent.com/80429191/186110635-af675828-c5be-449b-ab85-54b455a1eb93.png)

**- Cannot purchase new memberships**

![image](https://user-images.githubusercontent.com/80429191/186111597-74616a46-c056-4a98-8bfa-25b6ce72f916.png)

**- Can post to forum - can create uneditable post [TX](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x8293d4300abd0a600f812aa77a05ce034c5e39e69ca1d7ea08068d777d2a03d3)**

![image](https://user-images.githubusercontent.com/80429191/186112116-505e9701-a024-4acb-8882-4ea233027146.png)

**- Can create proposal**

Signal [TX](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x4fbaf21f5092a451d7bf436a5f6d478e95354def38978cfe0f98f4043133cd00):
![image](https://user-images.githubusercontent.com/80429191/186112766-ebb062cf-4f93-4f59-9d78-61ea37e82b99.png)

Create Working Group Lead Opening [TX](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x4575cd78d5272c92d33346311ec0f01f86cb8a8e1c6a9f46cfb2074d23fd980b)
![image](https://user-images.githubusercontent.com/80429191/186115057-c4611f7b-f5c6-4eef-aa87-21d1609d433b.png)

- **Can vote for candidates to council**
[TX](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x3ad6c6be8d6f7fd0b99a1fec110c489fa78024a28ce115de068b53da3f9c69e3)
![image](https://user-images.githubusercontent.com/80429191/186117966-dd5d6d09-fbb0-4891-a7a0-d8a948436efd.png)

**Comment by dmtrjsg** [comment]
@polikosi Nice work man, thanks for the retest  ✅  great to see it all works nicely 👍
