### ISSUE TITLE
[USERSNAP] Forum: cannot search for numbers

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3470]
## Scope

- [ ] Add a message "Minimum of three characters is required" as a normal validation error.
- [ ] Fix the bug of entering 3 into the field, and the reducing input to 2 chars, the validation will pass, but needs to work

## Context
**Taken at**: https://dao.joystream.org/#/forum/category/16
**Fields**:
- Houston, we have a problem.: Forum: cannot search for numbers
- Comment: The following don&#39;t work:
- Searching for a number (i.e. 18)
- Searching for a date that is put in title fields (i.e. 13.07)

Both return no results and page doesn&#39;t seem to indicate it even attempted to search.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3a0c971-5df1-475f-9caa-34b1125675aa-annotated_db8ca673-b88d-48b8-8411-90720e0f192d.png?etag=2bb28d880151a7e3e7a538282e75500e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3a0c971-5df1-475f-9caa-34b1125675aa-annotated_db8ca673-b88d-48b8-8411-90720e0f192d.png?etag=2bb28d880151a7e3e7a538282e75500e)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1640x1325
**[Open #323 in Usersnap](https://app.usersnap.com/l/feedback/964fc9f0-c118-44f1-9d45-5fbc83d83978?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203238414106362) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
THe aggregation right now happens on the client and there is a limit of 500 results. Searching for 2 characters would not bring the good results, but we can remove this check.. 

Suggest to add a message "Minimum of three characters is required"

**Comment by oleksanderkorn** [comment]
@dmtrjsg when and where should we show the validation message?

**Comment by oleksanderkorn** [comment]
@dmtrjsg agree

**Comment by dmtrjsg** [comment]
@oleksanderkorn pls re-upl the image :)

**Comment by oleksanderkorn** [comment]
> @oleksanderkorn pls re-upl the image :)

done :)

**Comment by ivanturlakov** [comment]
Tested here #3635
