### ISSUE TITLE
[USERSNAP] Forum > user profile: "Blog Posts" should be "Forum Posts"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3471]
**Taken at**: https://dao.joystream.org/#/council
**Fields**:
- Houston, we have a problem.: Forum &gt; user profile: &#34;Blog Posts&#34; should be &#34;Forum Posts&#34;
- Comment: SSIA
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/495be386-435b-4a25-8d59-326e9537565d-annotated_de2f365d-51ca-437f-ace9-5f5800ed5760.png?etag=4061b51f7f4b200a0ae5564122ff2e2b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/495be386-435b-4a25-8d59-326e9537565d-annotated_de2f365d-51ca-437f-ace9-5f5800ed5760.png?etag=4061b51f7f4b200a0ae5564122ff2e2b)*

**Browser**: Chrome 103 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1543x1325
**[Open #324 in Usersnap](https://app.usersnap.com/l/feedback/874edb56-9689-4045-9a17-302161f0cf69?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by adovrodion** [comment]
Bounty was created: https://dao.joystream.org/#/bounty/preview/685

**Comment by polikosi** [comment]
verified here wss://44.201.112.198.nip.io/ws-rpc
✅
![image](https://user-images.githubusercontent.com/80429191/194054259-c0b4d898-21f3-4d4d-ab98-912302a92a3a.png)

**Comment by polikosi** [comment]
✅Everything is good. Works as expected
![image](https://user-images.githubusercontent.com/80429191/194147863-293609b9-67b0-46fb-9fdd-9d02dd7fddbf.png)
