### ISSUE TITLE
[USERSNAP] Incorrect opening link in the account locks section.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3480]
## Scope

- [ ] Link to My Applications Tab
- [ ] Rename to "Show Openings"

NB: ⚠️ there is no possibility to link to the specific opening.

**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/profile
**Fields**:
- Houston, we have a problem.: Incorrect opening link in the account locks section.
- Comment: ...
- Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/463a5ace-683c-4d29-8bf8-d28d203ed67e-annotated_a728f9e3-6ec6-483b-b90f-678ce9158b10.png?etag=85522a12cb23758f840719901c64b4fc)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/463a5ace-683c-4d29-8bf8-d28d203ed67e-annotated_a728f9e3-6ec6-483b-b90f-678ce9158b10.png?etag=85522a12cb23758f840719901c64b4fc)*

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x789
**[Open #326 in Usersnap](https://app.usersnap.com/l/feedback/69aec505-0005-447d-8cd8-28eba7caadad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
https://user-images.githubusercontent.com/46903215/183645206-1bd25716-d1ac-48a2-9dbd-ecb7aafc92e7.mov

<img width="1210" alt="Снимок экрана 2022-08-09 в 15 19 47" src="https://user-images.githubusercontent.com/46903215/183645321-9027edb0-f665-40d6-84bb-1b42f07ac075.png">

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.154.45.nip.io/network/config.json


https://user-images.githubusercontent.com/46903215/185486115-cb18a7a2-28d8-466c-b4d5-a060017bee30.mov
