### ISSUE TITLE
Testing Vesting Locks are non-rivalrous and can also cover tx fees 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3495]
## Context

Testing the non-rivalrous nature of the vesting locks

⚠️ How to add vesting locks: https://github.com/Joystream/pioneer/issues/3404

## Scope

Test that Vesting locks can be used for 
1. Creating membership
2. Council candidate
3. Voting on candidates
4. Proposal Staking
5. Transaction fees

For this we'd need to have a membership with only _locked in vesting_ balances and nothing else.

**Comment by dmtrjsg** [comment]
@oleksanderkorn since you've done a fantastic work on the 
#3404 taking the liberty to suggest for you to take on this ticket. 

cc @singulart

**Comment by oleksanderkorn** [comment]
@dmtrjsg sure i can pick this one !

**Comment by oleksanderkorn** [comment]
Created empty account with only vested balance:
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/9252017/185478929-67fa3d4d-bc45-4fb8-a8ce-084a3926f7ee.png">

1. Create membership

Cannot be done with vested token, UI is blocked:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/9252017/185479077-5710c2f3-321e-4c43-9fe2-abbb1b3be1c3.png">

<img width="908" alt="image" src="https://user-images.githubusercontent.com/9252017/185479155-493e3c4f-e9eb-4025-9253-d48785ef193e.png">

**Comment by oleksanderkorn** [comment]
4. Creating proposal using vested balance seems to be not possible, last modal shows 0 balance, but before it shows locked balance:

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/9252017/185482275-98e75eb7-f63b-4ab5-a994-cc1e749627ca.png">

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/9252017/185482400-01727506-9058-4f0e-b3d7-b4224c461747.png">

<img width="917" alt="image" src="https://user-images.githubusercontent.com/9252017/185482485-3b4f5eb8-7fa0-47f6-b87a-405d29362bac.png">

**Comment by oleksanderkorn** [comment]
3. Vote for council candidate using only vested locked balance successful:
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/9252017/185485208-9768c11b-1086-44af-aa73-b75633a1d609.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/9252017/185485231-77b262a5-b677-4992-ad3b-b5ac2446b842.png">

<img width="938" alt="image" src="https://user-images.githubusercontent.com/9252017/185485298-46249101-3517-4d8f-9008-71ba91fe3aa0.png">

Logs:
```
Successful transaction: Withdraw, VoteCast, Deposit, ExtrinsicSuccess
on network: wss://54.172.154.45.nip.io/ws-rpc
in block: 0x62547f5891571b77eafde6e3057028ca18d1db32e8725e76e9daaef90dee5abb
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0x62547f5891571b77eafde6e3057028ca18d1db32e8725e76e9daaef90dee5abb
```

**Comment by oleksanderkorn** [comment]
5. Transaction fees:  Points 2, 3, 4 were successful also with transaction fee covered only by vested tokens.
Total vested balance was 20000, now its less, so transaction fees were deducted from the total:
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/9252017/185487338-5b7e7f71-7d72-40ab-8f92-a711f6279385.png">

**Comment by dmtrjsg** [comment]
Summary from Oleksanderkorn:

Noticed that membership cannot be created using vested balance, and proposal cannot be created. Apply to council & vote for council can be done using vested balance.

**Comment by dmtrjsg** [comment]
Issue raised off the back of this testing ticket:
- https://github.com/Joystream/pioneer/issues/3536

**Comment by dmtrjsg** [comment]
Nice work @oleksanderkorn thank you for the thorough results posting. 

Just heads up: there are some changes applied now on runtime codebase wrt to costs that will be coveted by Invitation and Vesting locks, and it is most likely that Vesting locks will only cover staking; so will be behaving like other non-rivalrous locks. 

I will update the relevant documentation and post it in a clear acceptance criteria way for the 2nd round of testing which is planned to kick off next week on Monday on a new staging env.
