### ISSUE TITLE
Selects are croped inside small modals

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3503]
## Context
![image](https://user-images.githubusercontent.com/6571453/184828536-dabce348-9f88-4818-a240-6f3eeff0bd91.png)

## Scope
- [ ] Update selects of accounts to go over the modal

❓ How to test
- Connect multiple accounts and try token transfer modal, see how selector goes over the modal border on upper z axis
- Test the same for any proposal creation (signal) or creation of opening and report results (regression test scenario)

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app

<img width="1013" alt="Снимок экрана 2022-08-19 в 13 02 17" src="https://user-images.githubusercontent.com/46903215/185633589-29983caa-f329-461f-adde-2d1a6dc6f4a2.png">
<img width="1254" alt="Снимок экрана 2022-08-19 в 16 46 31" src="https://user-images.githubusercontent.com/46903215/185633597-13a1ff02-8970-45ad-8818-923c7d15ed77.png">
<img width="1253" alt="Снимок экрана 2022-08-19 в 16 48 43" src="https://user-images.githubusercontent.com/46903215/185633604-c4a126dd-b667-47bd-95ec-3a9290cf282a.png">
