### ISSUE TITLE
[USERSNAP] Update Working Group Budget Proposal Execution Fail (any amounts))

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3504]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/128
**Fields**:

* Houston, we have a problem.: Update Working Group Budget Proposal Execution Fail (any amounts))
* Comment: Expecting that WG budget will be updated
* Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xf08d04b522a330c9ce504da14ed3f1f8fdfea2e9971b75d47434b3d6f3cccbe1

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8511d399-adab-4a6e-8092-3d13a2012660-annotated_bdc7371d-6772-48d5-9b30-281468bd4809.png?etag=7c874c313276389004c8b8719f1d1c33)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8511d399-adab-4a6e-8092-3d13a2012660-annotated_bdc7371d-6772-48d5-9b30-281468bd4809.png?etag=7c874c313276389004c8b8719f1d1c33)_

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x789
**[Open #330 in Usersnap](https://app.usersnap.com/l/feedback/486d5bea-466c-4d2a-9951-45dcadf2b893?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202806035736875) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
Transaction success
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xf08d04b522a330c9ce504da14ed3f1f8fdfea2e9971b75d47434b3d6f3cccbe1
Proposal execution failed
https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/127

**Comment by dmtrjsg** [comment]
So we've checked the execution constraints: 

☝️ ➕ If porposal is to increase WG, only check at the time of execution is for council to have sufficient budget
☝️ ➖ If proposal is to decrease WG budget, only check at the time of execution is that WG budget is sufficient to be decreased by stated amount.

Here's the extract from the runtime code:

<img width="466" alt="Screenshot 2022-08-18 at 10 02 13" src="https://user-images.githubusercontent.com/93924525/185357103-c4c7ce28-37a1-4fe8-ab4c-d2b956aab50d.png">

@WRadoslaw is there a way to check the state of council budget using the block height reported in the execution transaction?

And if that was insufficient, I could ask Ivan to re-test.

**Comment by WRadoslaw** [comment]
@dmtrjsg Yeah. Budget for council at block with hash (block of execution) 0xd54048dc318d6897c600b7484963df837c25b0032d54ce87accc73f18d72d83a was 10 in base unit. After denomination `0.000000001` tJOY, so update was way above budget.

**Comment by ivanturlakov** [comment]
@dmtrjsg @WRadoslaw I will try to update the council budget and retest

**Comment by ivanturlakov** [comment]
>I will try to update the council budget and retest
@dmtrjsg The proposal was successfully executed after the council budget increased 🙃
