### ISSUE TITLE
[USERSNAP] Set Councilor Reward Proposal. Rationale field rendering issue(shows 0x2a...).

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3505]
**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/131
**Fields**:

* Houston, we have a problem.: Set Councilor Reward Proposal. Rationale field rendering issue(shows 0x2a...).
* Comment: Expecting to see plain text in this field.
* Link to polkadot block: https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/131

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3893ae5a-26e2-4710-9fa4-6eb7beb7307a-annotated_678ca075-937b-4e1c-a6fd-301b4b58c1db.png?etag=cbae0bea4bbb93d89c75e764a22ba7db)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3893ae5a-26e2-4710-9fa4-6eb7beb7307a-annotated_678ca075-937b-4e1c-a6fd-301b4b58c1db.png?etag=cbae0bea4bbb93d89c75e764a22ba7db)_

**Browser**: Chrome 103 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x789
**[Open #331 in Usersnap](https://app.usersnap.com/l/feedback/bc2a61ef-51ee-4651-bdc9-a62a92ea0c1e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202808236743109) by [Unito](https://www.unito.io)

**Comment by WRadoslaw** [comment]
Same problem as #3418
