### ISSUE TITLE
Tooltips Update for Mainnet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3518]
## Context
Umbrella issue to fix all tooltips

This is a tracker issue, respective work needs to be done in the tasks provided below:

## Scope
* https://github.com/Joystream/pioneer/issues/3297
* https://github.com/Joystream/pioneer/issues/3024
* https://github.com/Joystream/pioneer/issues/2346
* https://github.com/Joystream/pioneer/issues/2847
* https://github.com/Joystream/pioneer/issues/2680
* https://github.com/Joystream/pioneer/issues/2929
* https://github.com/Joystream/pioneer/issues/2507
* https://github.com/Joystream/pioneer/issues/3479
* https://github.com/Joystream/pioneer/issues/3632
* https://github.com/Joystream/pioneer/issues/3670
* https://github.com/Joystream/pioneer/issues/3682

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203239098654174) by [Unito](https://www.unito.io)

**Comment by gyroflaw** [comment]
I am gyroflaw

**Comment by singulart** [comment]
Assigned to @gyroflaw

**Comment by traumschule** [comment]
Found some more. Few are labeled [ux](https://github.com/Joystream/pioneer/issues?q=is%3Aissue+is%3Aopen+tooltip+label%3Aux) but not all.
- #2520
- #3093
- #3273
- #3333
- #3690

**Comment by dmtrjsg** [comment]
⚠️ Bounty flow will be reviewed as part of v2 and we will adress the tooltips as part of this release so no need to address it rn. Ability to use markup has a low chance of making to mainnet, but its in the design backlog rn so will be addressed at the earliest opp subject to other priorities..
