### ISSUE TITLE
Change tJoy to JOY

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3527]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202829081590251) by [Unito](https://www.unito.io)

**Comment by polikosi** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/
wss://34.230.5.182.nip.io/ws-rpc
✅I couldn't find tJoy in Pioneer UI

**Comment by polikosi** [comment]
@traumschule @dmtrjsg  sorry, I find tJoy

I want to create a post with a zero account balance
![image](https://user-images.githubusercontent.com/80429191/206260196-796ebfaa-3461-41c7-a5f4-5d9042799e37.png)

**Comment by traumschule** [comment]
Please test again on https://dao-git-fork-traumschule-fix-tjoy-joystream.vercel.app

**Comment by thesan** [comment]
#3941 is now merged so it can be tested on: https://pioneer-2-git-mainnet-joystream.vercel.app/

**Comment by polikosi** [comment]
✅fixed on: https://pioneer-2-git-mainnet-joystream.vercel.app/
![image](https://user-images.githubusercontent.com/80429191/206431687-f58329dc-7154-43dc-acc7-1532f0315e6a.png)
