### ISSUE TITLE
Documentation: Vesting and Invitations Locks Coverage 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3535]
# Context

Review of the Invitation and Vesting Locks coverage wrt various costs is completed. We need to ensure this is validated on the newest staging env.

⚠️ Important notes 
* [🔗 Link to original reference](https://gist.github.com/Lezek123/7eb89937fcbffabefe73fede0b336943)
* Notable differences between Invitation and Vesting locks are marked with ☝️ 
* Transaction supported = costs are coverable by such lock
* Transaction unsupported = costs are not coverable by such lock
* Features not implemented on FE apps are marked with commenting out mark down, since this issue was mainly raised for the purpose of QA. Example below
> Not implemented.. but testable

______________
###  ✅  Transactions Supported Atlas
- **Standard transaction fees**
- **Bloat bonds**
    - Channel bloat bond (`content::create_channel`)
    - Video bloat bond (`content::create_video`)
    - Storage data objects bloat bond (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`)
- **Storage data size fee** (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`)
    
>Not implemented on Atlas yet, but testable via Polkadot app  
>- Creator token account bloat bond (`content::issue_creator_token`, `content::creator_token_issuer_transfer`, `project_token::join_whitelist`, `project_token::purchase_tokens_on_sale`, `project_token::transfer`)

### ⛔ Not supported Atlas
- **Nft auction bids** (`content::make_english_auction_bid`, `content::make_open_auction_bid`)
- **Nft payments** (`content::buy_nft`, `content::accept_incoming_offer`)
- **Channel swap payment** (`content::accept_channel_transfer`)
     -  **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()`)

>Not implemented on Atlas yet, but testable via Polkadot app       
           - **Transaction `tip`** 
     - **Creator token purchases** (`project_token::purchase_tokens_on_sale`)

    
###  ✅  Transactions Supported  Pioneer

   - Forum thread deposit (`forum::create_thread`)
   - Forum post deposit (`forum::create_thread`, `forum::add_post`)
   - **Staking**
    - Council candidate stake (`council::announce_candidacy`)
    - Staking account candidate stake (`membership::add_staking_account_candidate`)
    - Proposal stake (`proposals_codex::create_proposal`)
    - Referendum vote stake (`referendum::vote`)
    - Opening creation stake (`working_group::add_opening`)
    - Application/Worker stake (`working_group::apply_on_opening`, `working_group::increase_stake`)
    - Validator / nominator stake
    
###  ⛔ Not supported  Pioneer 
- **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()` )
- **Budget funding** (`council::fund_council_budget`, `working_group::fund_working_group_budget`)
- **Membership fee** (`membership::buy_membership`, `membership::gift_membership`)

>Not implemented on Pioneer yet, but testable via Polkadot app  
>- **Gifted member balances** (`membership::gift_membership`)
>- **Transaction `tip`** 

______________
### ✅  Atlas Transactions Supported
- nothing 🚫 

### ⛔ Not Supported
- **Standard transaction fees**
- **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()`)
- **Nft auction bids** (`content::make_english_auction_bid`, `content::make_open_auction_bid`)
- **Nft payments** (`content::buy_nft`, `content::accept_incoming_offer`)
- **Channel swap payment** (`content::accept_channel_transfer`)
- **Creator token purchases** (`project_token::purchase_tokens_on_sale`)
- ☝️ **Bloat bonds** 
    - Channel bloat bond (`content::create_channel`)
    - Video bloat bond (`content::create_video`)
    - Storage data objects bloat bond (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`)
    - Creator token account bloat bond (`content::issue_creator_token`, `content::creator_token_issuer_transfer`, `project_token::join_whitelist`, `project_token::purchase_tokens_on_sale`, `project_token::transfer`)
- ☝️**Storage data size fee** (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`) 

>Not implemented on Atlas yet, but testable via Polkadot app  
> - **Transaction `tip`**

### ✅  Pioneer Transactions Supported
- **Staking**
    - Council candidate stake (`council::announce_candidacy`)
    - Staking account candidate stake (`membership::add_staking_account_candidate`)
    - Proposal stake (`proposals_codex::create_proposal`)
    - Referendum vote stake (`referendum::vote`)
    - Opening creation stake (`working_group::add_opening`)
    - Application/Worker stake (`working_group::apply_on_opening`, `working_group::increase_stake`)
    - Validator / nominator stake
    
### ⛔ Not Supported
- **Standard transaction fees**
- **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()`)
- **Budget funding** (`council::fund_council_budget`, `working_group::fund_working_group_budget`)
- **Membership fee** (`membership::buy_membership`, `membership::gift_membership`)
- **Gifted member balances** (`membership::gift_membership`)
- ☝️**Bloat bonds**
    - Forum thread deposit (`forum::create_thread`)
    - Forum post deposit (`forum::create_thread`, `forum::add_post`)
>Not implemented on Pioneer yet, but testable via Polkadot app  
>- **Transaction `tip`**

**Comment by bedeho** [comment]
Note: also cover that invitation lock funds flow back to only the funding account, and that alternative funding sources allow having funds flow back to membership on a few extrinsics.

_feel free to delete this later_
