### ISSUE TITLE
Test that 100% tx fees are burned

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3568]
## Context
On testnet before Carthage 20% of tx fees used to go to validator workers reward. From Carthage and onwards to mainnet all 100% of tx fees will be burned. 

Here's the ticket implementing this change:
- Issue: https://github.com/Joystream/joystream/issues/4176
- PR: https://github.com/Joystream/joystream/pull/4199

## Scope
- [ ] Test that 100% of tx fees get burned by executing the scenarios below

ℹ️ how to test

- Setup Account X fund it from Alice (the block author)
- Record total issuance, and balance of Alice and X
- execute N balances:transfer() calls each with a tip T, transferring amount V to account Y
- - At end of the scenario (which should be completed before the end of an Era) the following should hold:
- - Alice Balance should have increased by (N * T) only
- - Account X balance decresed by (N * T + N * V + TotalTxFeesPaid)
- - Account Y balance equal to (N * V)
- - Total Issuance reduced by TotalTxFeesPaid

NB:
we can derive TotalTxFeesPaid by BalanceOf(X) - (N * T + N * V)
we can also simplify by transfering to self ie. X == Y and transferring zero balance, ie V == 0

**Comment by ivanturlakov** [comment]
Tested on https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/accounts

>Setup Account X fund it from Alice (the block author)
>Record total issuance, and balance of Alice and X

**Total issuance 20,000,169,880,920,933,415,342**
<img width="1064" alt="Снимок экрана 2022-09-09 в 19 59 48" src="https://user-images.githubusercontent.com/46903215/189403133-6e64f77f-2645-4ad5-8b9b-69295e1171ae.png">

**Alice balance 33,462.2680 JOY**
<img width="1011" alt="Снимок экрана 2022-09-09 в 19 58 21" src="https://user-images.githubusercontent.com/46903215/189403266-0edbc949-84f9-4226-aec9-b6fae15a8725.png">

**X balance 100.0000 JOY**
<img width="1017" alt="Снимок экрана 2022-09-09 в 19 58 37" src="https://user-images.githubusercontent.com/46903215/189403270-a61f3a2d-5d3a-427b-9804-42db3395a7cb.png">

>execute N balances:transfer() calls each with a tip T, transferring amount V to account Y

**N = 4, T = 5, V = 2, Y initial balance = 0**

>At end of the scenario (which should be completed before the end of an Era) the following should hold:
>Alice Balance should have increased by (N * T) only

✅ **33,462.2680 + (4 * 5) = 33,482.2680 JOY**
<img width="1010" alt="Снимок экрана 2022-09-09 в 20 12 05" src="https://user-images.githubusercontent.com/46903215/189406900-f3f24b0c-091b-4c6a-bf3a-9f1bbd828f66.png">

>Account X balance decresed by (N * T + N * V + TotalTxFeesPaid)

✅ **100 - (4 * 5 + 4 * 2 + 0.3028) = 71,6972**
<img width="1006" alt="Снимок экрана 2022-09-09 в 20 24 27" src="https://user-images.githubusercontent.com/46903215/189409334-033e0621-7aed-4024-99cb-34d753ab4c2d.png">

>Account Y balance equal to (N * V)

✅ **(4 * 2) = 8**
<img width="1014" alt="Снимок экрана 2022-09-09 в 20 26 02" src="https://user-images.githubusercontent.com/46903215/189409563-e485fdd1-ad6a-4cdd-92b5-f05ac57fb706.png">

>Total Issuance reduced by TotalTxFeesPaid

✅ **20,000,169,880,920,933,415,342 - 0.3028 = 20,000,169,880,917,905,499,785**
<img width="1044" alt="Снимок экрана 2022-09-09 в 20 27 30" src="https://user-images.githubusercontent.com/46903215/189409818-637369ec-a2aa-4c2c-a28e-b7352228b03b.png">

NB:
we can derive TotalTxFeesPaid by BalanceOf(X) - (N * T + N * V) **--> 100 - (4 * 5 + 4 * 2) = 72 - 71.6972 = 0.3028**
