### ISSUE TITLE
Refactor Memberships Modal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3572]
@ QA 

Test Create Membership on Carthage Branch. To test go through the app without! selected membrship and try to start the process. 

Success= membership selection modal is triggered automatically. 
Fail = membership modal is triggered where memebrship does not have to be selected to view side panel (application, council, opening details)

## Context
- #3522 Epic

## Scope

- [ ] Handling switch membership  in the global modal

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/working-groups
wss://44.201.112.198.nip.io/ws-rpc

The membership selection window works as expected. No problems were detected.
