### ISSUE TITLE
Test Invitation Lock coverage of Misc fees Pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3578]
## Context

2nd round of QA, Env details are in the Epic pls see 3577>
- https://github.com/Joystream/pioneer/issues/3577

Testing Invitation Lock Fees Coverage

## Scope
1️⃣ Ensure that 100% Invitation lock funds received from Faucet can only cover the following transactions:

###  ✅  Transactions Supported  Pioneer

   - Forum thread deposit (`forum::create_thread`)
   - Forum post deposit (`forum::create_thread`, `forum::add_post`)
   - **Staking**
    - Council candidate stake (`council::announce_candidacy`)
    - Staking account candidate stake (`membership::add_staking_account_candidate`)
    - Proposal stake (`proposals_codex::create_proposal`)
    - Referendum vote stake (`referendum::vote`)
    - Opening creation stake (`working_group::add_opening`)
    - Application/Worker stake (`working_group::apply_on_opening`, `working_group::increase_stake`)
    - Validator / nominator stake
    
2️⃣ Ensure that 100% Invitation lock funds received from Faucet cannot cover the following transactions:

###  ⛔ Not supported  Pioneer 
- **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()` )
- **Budget funding** (`council::fund_council_budget`, `working_group::fund_working_group_budget`)
- **Membership fee** (`membership::buy_membership`, `membership::gift_membership`)

**Comment by singulart** [comment]
Assigned to Ivan T#1098

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.204.195.nip.io/network/config.json

Unexpected behavior is marked with an ❗️

### Transactions Supported Pioneer

✅ Forum thread deposit (forum::create_thread)
**Create category via extrinsic**
https://dao-git-carthage-joystream.vercel.app/#/forum/category/1
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F54.172.204.195.nip.io%2Fws-rpc#/extrinsics/decode/0x170100504372656174652043617465676f72792054657374804372656174652043617465676f72792054657374204465736372697074696f6e
❗️ **Create thread via extrinsic (Only via extrinsics possible, UI throws - Insufficient Funds)**
https://dao-git-carthage-joystream.vercel.app/#/forum/thread/1
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F54.172.204.195.nip.io%2Fws-rpc#/extrinsics/decode/0x1706100000000000000001000000000000003c546872656164204d65746164617461284e657720546872656164

✅ Forum post deposit (forum::create_thread, forum::add_post)
❗️ **Create post via extrinsic (Only via extrinsics possible, UI throws - Insufficient Funds)**
https://dao-git-carthage-joystream.vercel.app/#/forum/thread/1?post=2
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2F54.172.204.195.nip.io%2Fws-rpc#/extrinsics/decode/0x170b0e00000000000000010000000000000001000000000000005c466f72756d20706f7374206465706f736974207465737400

**Staking**

✅ Council candidate stake (council::announce_candidacy)
✅ Staking account candidate stake (membership::add_staking_account_candidate)
**Tr1** Successful transaction: Withdraw, StakingAccountAdded, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x7a6e8804ba056f02b8af3c23659bbd18c6620c12ae9916c4a8a5dfe53d1b71a2
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x7a6e8804ba056f02b8af3c23659bbd18c6620c12ae9916c4a8a5dfe53d1b71a2
**Tr2** Successful transaction: Withdraw, StakingAccountConfirmed, ItemCompleted, NewCandidate, ItemCompleted, BatchCompleted, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xbc3560a900e9ee2e1228b76ec64ad69bbc7f8c5f8dd49fa0ee984be5faa13963
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xbc3560a900e9ee2e1228b76ec64ad69bbc7f8c5f8dd49fa0ee984be5faa13963
**Tr3** Successful transaction: Withdraw, CandidacyNoteSet, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xb0788fe24e0bdda54504cde86a366c2a23fc81895ce573cda8512000814316b8
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xb0788fe24e0bdda54504cde86a366c2a23fc81895ce573cda8512000814316b8 

✅ Proposal stake (proposals_codex::create_proposal)
https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/1 
Successful transaction: Withdraw, ThreadCreated, ProposalCreated, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xd59dcde4cef0dad65369c1defd4fc24a25e8714af568734071bcbae936dd7eef
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xd59dcde4cef0dad65369c1defd4fc24a25e8714af568734071bcbae936dd7eef

✅ Referendum vote stake (referendum::vote)
Successful transaction: Withdraw, VoteCast, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x733fc14ba7fb20071c4e050790be00713dfd61d1be5360a9a9e483382d7c591f
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x733fc14ba7fb20071c4e050790be00713dfd61d1be5360a9a9e483382d7c591f

 ✅ Opening creation stake (working_group::add_opening)
https://dao-git-carthage-joystream.vercel.app/#/working-groups/openings/forumWorkingGroup-2

 ✅ Application/Worker stake (working_group::apply_on_opening, working_group::increase_stake)
Successful transaction: Withdraw, AppliedOnOpening, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xdf22aaf833a5bf028ebe3f9ef42d51ddd0de00620fbd40265196a2f8243970bb
more details at: [https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xdf22aaf833a5bf02 8ebe3f9ef42d51ddd0de00620fbd40265196a2f8243970bb](https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xdf22aaf833a5bf028ebe3f9ef42d51ddd0de00620fbd40265196a2f8243970bb)

 ✅ Validator / nominator stake
<img width="1410" alt="validator_nominator_staking" src="https://user-images.githubusercontent.com/46903215/187910929-6b6f9cdd-d61f-4aae-887d-88c3faa81a41.png">
<img width="1183" alt="validator_nominator_staking_1" src="https://user-images.githubusercontent.com/46903215/187910934-3ffa0146-2fd0-4acf-89a1-2ceed3d4c53e.png">




### Not supported Pioneer
🚫 Transfers (balances::transfer, balances::transfer_keep_alive(), balances::transfer_all(tr sended, with val 0, fee charged) )
<img width="914" alt="Снимок экрана 2022-09-01 в 15 24 13" src="https://user-images.githubusercontent.com/46903215/187913122-43eff6bb-fa40-44a6-b103-f8a54bf6e443.png">

🚫 Budget funding (council::fund_council_budget, working_group::fund_working_group_budget)
🚫 Membership fee (membership::buy_membership, membership::gift_membership)

**Comment by dmtrjsg** [comment]
⚠️ 🔁   Retest is required for fixed bloat bonds:

For the account where 100% balance consists of invitation lock:
- [ ] Create thread
- [ ] Create post
- [ ] Edit post

**Comment by ivanturlakov** [comment]
Retested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://54.172.204.195.nip.io/network/config.json

**Used freshly created account where 100% balance consists of invitation lock**

✅ **Forum thread deposit (forum::create_thread)**
https://dao-git-carthage-joystream.vercel.app/#/forum/thread/3
Successful transaction: Withdraw, Withdraw, Deposit, NewAccount, Endowed, ThreadCreated, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x1977a2030a571ce0a2b2648d5bb5d3d078337ba55339b0f569786473ec964ab6
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x1977a2030a571ce0a2b2648d5bb5d3d078337ba55339b0f569786473ec964ab6

✅ **Forum post deposit (forum::add_post)**
https://dao-git-carthage-joystream.vercel.app/#/forum/thread/2?post=9
Successful transaction: Withdraw, Withdraw, Deposit, PostAdded, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0xbb50d57453dba46c4b3e7600c9b9a1369e6d85fd9a653e8692cebcead906e4f0
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xbb50d57453dba46c4b3e7600c9b9a1369e6d85fd9a653e8692cebcead906e4f0

✅ **Forum edit-post deposit (forum::edit_post)**
https://dao-git-carthage-joystream.vercel.app/#/forum/thread/3?post=8
Successful transaction: Withdraw, PostTextUpdated, ExtrinsicSuccess
on network: wss://54.172.204.195.nip.io/ws-rpc
in block: 0x76dbb7d9afdc8208b4ca8c4d541162e08e7b0833b06aa4db59d9e80ab517e2c4
more details at: https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x76dbb7d9afdc8208b4ca8c4d541162e08e7b0833b06aa4db59d9e80ab517e2c4
