### ISSUE TITLE
Test That Vesting Locks can only be used for staking Pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3581]
## Context

2nd round of QA, Env details are in the Epic pls see 3577>
- https://github.com/Joystream/pioneer/issues/3577

Testing Vesting Lock Fees Coverage

## Scope

1️⃣ Test that Vesting lock can be used for staking

### ✅  Pioneer Transactions Supported
- **Staking**
    - Council candidate stake (`council::announce_candidacy`)
    - Staking account candidate stake (`membership::add_staking_account_candidate`)
    - Proposal stake (`proposals_codex::create_proposal`)
    - Referendum vote stake (`referendum::vote`)
    - Opening creation stake (`working_group::add_opening`)
    - Application/Worker stake (`working_group::apply_on_opening`, `working_group::increase_stake`)
    - Validator / nominator stake

1️⃣ Test that Vesting lock cannot be used for any other transactions
    
### ⛔ Not Supported
- **Standard transaction fees**
- **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()`)
- **Budget funding** (`council::fund_council_budget`, `working_group::fund_working_group_budget`)
- **Membership fee** (`membership::buy_membership`, `membership::gift_membership`)
- **Gifted member balances** (`membership::gift_membership`)
- ☝️**Bloat bonds**
    - Forum thread deposit (`forum::create_thread`)
    - Forum post deposit (`forum::create_thread`, `forum::add_post`)

**Comment by polikosi** [comment]
@thesan Hi,I can't claim vested joy (Bob acc)
![image](https://user-images.githubusercontent.com/80429191/188080236-705d53c6-ad57-4292-b7b7-cdf69d3e1484.png)

![image](https://user-images.githubusercontent.com/80429191/188080145-a3c4822d-344b-47a5-a34d-00e325f79765.png)

**Comment by thesan** [comment]
@polikosi Bob not being able to recover the fund is expected because unlike the invitation lock, the vesting lock doesn't allow you to pay for transaction fees anymore. On `wss://54.172.204.195.nip.io/ws-rpc` Bob only has 10,000tJOY of vested fund and nothing more to afford transaction fees.

That being said, Pioneer should be clearer about what is going wrong. You shouldn't be able to start a transaction that you can't afford.

**Comment by polikosi** [comment]
**Staking**

- Council candidate stake (council::announce_candidacy)
![image](https://user-images.githubusercontent.com/80429191/188465147-13d3d8e7-57ba-47fa-8aee-fb6de82f2df3.png)
https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x53377f9c70cc9878f10dc04c7516f9b7eff471f75e5ca776e714bb9fcac78c3c


- Staking account candidate stake (membership::add_staking_account_candidate)
https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xd77dcd16b05675df97943ed121963c83330d586cd9abd7284063e99fd51a0612

- Proposal stake (proposals_codex::create_proposal)
https://dao-git-carthage-joystream.vercel.app/#/proposals/preview/13
![image](https://user-images.githubusercontent.com/80429191/188465496-c1d8c02f-60f9-4339-8a40-8f222786ed8a.png)
https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x689228c8ecfcca10c4cfb46a6c60079c77a336e5ef052d54b66cd6d56e397eca


- Referendum vote stake (referendum::vote)
https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0x150946c72ff6103e79ba4f63e969f4c80fbd6697657ac8e1f25c67257ec0ff2c


- Opening creation stake (working_group::add_opening)
https://dao-git-carthage-joystream.vercel.app/#/working-groups/openings/distributionWorkingGroup-3


- Application/Worker stake (working_group::apply_on_opening, working_group::increase_stake)
![image](https://user-images.githubusercontent.com/80429191/188476783-1b2a8362-996d-457b-bb69-dcca6dc61464.png)
https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xb6da1d5732c84a5ab20479a2effef29305c4857b3e47753ec70372be37053d97

- working_group::increase_stake
![image](https://user-images.githubusercontent.com/80429191/188478229-40d7f6b3-dc01-4b12-96ea-a9d022779adb.png)
https://polkadot.js.org/apps/?rpc=wss://54.172.204.195.nip.io/ws-rpc#/explorer/query/0xe9a1d04e8a9fdc7aecb6693489006f7b79722e682ae3b604cd43138fd1960cf9

- Validator / nominator stake
![image](https://user-images.githubusercontent.com/80429191/188479966-f6f22f50-8fae-4385-9532-8d3f2e2ca50d.png)
![image](https://user-images.githubusercontent.com/80429191/188480010-178906ad-a2fb-4d71-bc1f-0b888b56eab1.png)




⛔ Not Supported
Standard transaction fees
⛔- Transfers (balances::transfer, balances::transfer_keep_alive(), balances::transfer_all())
![image](https://user-images.githubusercontent.com/80429191/188466826-4af1b0d5-f5fe-425b-9a68-d7e00d218daa.png)



⛔- Budget funding (council::fund_council_budget, working_group::fund_working_group_budget)
![image](https://user-images.githubusercontent.com/80429191/188470730-28b3c6e2-5c48-46ac-986a-2f9b43fe37d6.png)

 working_group::fund_working_group_budget
![image](https://user-images.githubusercontent.com/80429191/188480225-9738c5ff-737c-4be3-bc59-2e561c95c8fb.png)
![image](https://user-images.githubusercontent.com/80429191/188480350-1cc25b98-a707-470e-b7ef-5f5664d2b6f4.png)



⛔- Membership fee (membership::buy_membership, membership::gift_membership)
![image](https://user-images.githubusercontent.com/80429191/188480871-c972ea6f-a570-4cee-ae21-fc0a831bd491.png)
![image](https://user-images.githubusercontent.com/80429191/188480938-2e2e1114-8d60-471b-a7b7-e7aa7b3a3eff.png)

⛔- Gifted member balances (membership::gift_membership)
![image](https://user-images.githubusercontent.com/80429191/188481167-ddd5e0a7-3ca8-4bd6-83c6-800a7d7996f5.png)
![image](https://user-images.githubusercontent.com/80429191/188481233-e6cc3f80-e583-4d3f-88f8-dc4f2a91eca7.png)

☝️Bloat bonds
Forum thread deposit (forum::create_thread)
Forum post deposit (forum::create_thread, forum::add_post)
![image](https://user-images.githubusercontent.com/80429191/188481803-7c79f900-b60a-4dc7-811f-135b50795077.png)

**Comment by dmtrjsg** [comment]
@polikosi 

Thanks for the effort 💪 great stuff!

After reviewing a few tx error codes with the team we wanted to ask you to provide some info on one case, and retest the other one, as evidence was insufficient:

1. ☝️ Gifted member balances: please provide the handle to the extrinsic, as the error code meant the field was left empty, but required..
2. Fees not supported: no evidence was provided, here pretty sure it is the case, but if you could share the details on how exactly did you test it, would help!.

Also just a small note, for tests like these when we are validating negative use case, please do try to provide the TX links, similar how you did that for Atlas testing ticket. Helps a lot to triage the results! 🙏

**Comment by polikosi** [comment]
Transferable balance = 0
![image](https://user-images.githubusercontent.com/80429191/189884071-e9eac799-250d-4f1c-8029-d18596d5e541.png)

- Gifted member balances (membership::gift_membership)
![image](https://user-images.githubusercontent.com/80429191/189885048-cb7c0f4c-15e9-42b2-9f63-aac212a2d3f4.png)


- Standard transaction fees
I can't transfer a joy
![image](https://user-images.githubusercontent.com/80429191/189898390-dbb0cd9d-e234-4dd9-9223-53d78761180e.png)

I can't create a proposal
![image](https://user-images.githubusercontent.com/80429191/189899240-84f6d769-a54a-4876-9ef0-629c96b6c7f2.png)

I can't announce candidacy
![image](https://user-images.githubusercontent.com/80429191/189899459-f0457465-9562-4e16-aaab-dad8f3b46d92.png)

**Comment by dmtrjsg** [comment]
@polikosi nice work, thanks a mil! Closing as completed ✅
