### ISSUE TITLE
[USERSNAP] Just voted for candidate. Show election button in account section leads to 404

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3585]
## Scope

- [ ] The problem probably stems from fact that election can be _past or present_

rn points to past election only

___

**Taken at**: https://dao-git-carthage-joystream.vercel.app/#/profile
**Fields**:
- Houston, we have a problem.: Just voted for candidate. Show election button in account section leads to 404
- Comment: Show election button leads to related election page
- Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7cd6ca64-8df7-4b64-ac17-64fd748e4c55-annotated_7b4bd1b0-97d6-4342-825c-d6b7efdad0da.png?etag=4caf875e6bb2d84d6ac4f9dc0464a99b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7cd6ca64-8df7-4b64-ac17-64fd748e4c55-annotated_7b4bd1b0-97d6-4342-825c-d6b7efdad0da.png?etag=4caf875e6bb2d84d6ac4f9dc0464a99b)*

**Browser**: Chrome 104 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x788
**[Open #332 in Usersnap](https://app.usersnap.com/l/feedback/c1ecdcdf-654e-407b-86ac-b341b9bdf623?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
Duplicate #3650
