### ISSUE TITLE
cant scroll down

### ISSUE THREAD

**Issue by Roglizer** [Joystream/pioneer#3604]
cant scroll down in the joystream app when trying to submit work or even when typing past a certain point it doesn't auto scroll you literally cant see what your typing anymore
[https://imgur.com/Rmngu4Q](url)
so your probably thinking oh just minimize the screen so yeah about that
[https://imgur.com/IUMpyfP](url)

**Comment by dmtrjsg** [comment]
Thank you for reporting, acknowledged.. @Roglizer does that prevent you from proceeding with the flow?

We are deprecating Bounties module with Carthage release soon, so unlikely to be fixed. Do you experience this in other modals as well?

**Comment by dmtrjsg** [comment]
@Roglizer we cannot reproduce and think that maybe one of your browser extenstions is messing with the CSS.
