### ISSUE TITLE
Pioneer Forum Search Engine

### ISSUE THREAD

**Issue by Goksel08** [Joystream/pioneer#3631]
Pioneer Forum Search Engine is not making searches with author names and times. If you enter a existing author name and click search button, got get no results at all.

![Bug01](https://user-images.githubusercontent.com/114411882/192287276-a3c4302d-e7cc-4f5b-91d6-a04f1e67a0b4.png)
![Bug011](https://user-images.githubusercontent.com/114411882/192287326-c2378e7b-03d4-4e2b-81c7-7a327620bfb1.png)

**Comment by dmtrjsg** [comment]
Already fixed, but will be released AFTER Carthage.
