### ISSUE TITLE
Missing Explanation Boxes

### ISSUE THREAD

**Issue by Goksel08** [Joystream/pioneer#3632]
* [ ] Recoverable balance is covered already in a diff issue
* [ ] Election round. "Ordinal number of the election round since the genesis block of the network. Learn more>" pointing to https://joystream.gitbook.io/testnet-workspace/system/council#election
* [ ] Minimal stake. "Minimum tokens required to be free from rivalrous locks to be able to stake for the application to this role. Learn more>" 
_Rivalrous locks_ hyperlinked to https://joystream.gitbook.io/testnet-workspace/system/accounts-and-staking#locks
_learn more_ hypelinked to https://joystream.gitbook.io/testnet-workspace/system/working-groups#staking

There are missing explanation box informations in the pioneer app. It is not a big of a deal but it looks unprofesional for a big DAO's governance main page.. We must fill them.
![Bug02](https://user-images.githubusercontent.com/114411882/192289281-50ea1606-4b14-403a-a606-910b5840eb51.png)
![Bug021](https://user-images.githubusercontent.com/114411882/192289308-ca773f8a-8cba-42b3-9fb0-ef6f93d86420.png)
![Bug022](https://user-images.githubusercontent.com/114411882/192289339-ccc0815f-9256-4c36-aec8-d11590099179.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203237693216484) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@Goksel08 nice, thank you for raising, will be addressed after Carthage release and before the mainnet 👍

**Comment by beeust** [comment]
I'm interested in this ticket, and please assign it to me!

**Comment by traumschule** [comment]
Thanks and welcome! Just to clarify you can ignore the first image, it's handled in #3738.

**Comment by gyroflaw** [comment]
And please provide for TOTAL INITIAL VESTING
![image](https://user-images.githubusercontent.com/83718263/206451436-3ea643c0-36de-46e7-9cbf-49e3632a9565.png)

**Comment by traumschule** [comment]
> And please provide tooltip for TOTAL INITIAL VESTING
You can skip that one for #3836.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-staging-joystream.vercel.app/

✅ Recoverable balance
<img width="719" alt="Снимок экрана 2023-01-04 в 13 49 46" src="https://user-images.githubusercontent.com/46903215/210549743-7639c3b4-faab-433b-aed1-34f9137a2689.png">

✅ Total Initial Vesting
<img width="1079" alt="Снимок экрана 2023-01-04 в 13 51 49" src="https://user-images.githubusercontent.com/46903215/210549749-6ba4a633-fb3c-4c1e-83c0-3c25e9d1bb14.png">

✅ Election round
<img width="1057" alt="Снимок экрана 2023-01-04 в 13 53 02" src="https://user-images.githubusercontent.com/46903215/210549752-5587e1a5-a038-4021-96de-4754bcbfa060.png">

✅ Minimal stake
⚠️ Missed - Rivalrous locks hyperlinked to https://joystream.gitbook.io/testnet-workspace/system/accounts-and-staking#locks
<img width="1440" alt="Снимок экрана 2023-01-04 в 13 53 59" src="https://user-images.githubusercontent.com/46903215/210549756-9b25fe7e-68bc-4e79-8de0-55ae3c4ed1c4.png">
