### ISSUE TITLE
Show election link points to 404

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3650]
## Context

Was raised in this issue
- https://github.com/Joystream/pioneer/issues/3612#issuecomment-1259501493

![Screenshot 2022-10-03 at 18.14.30.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/a487c114-d7c1-4724-82c3-071cec2ad17b)

![Screenshot 2022-10-03 at 18.14.25.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/a55271a6-7e1a-436d-83cb-9bdb7e287680)

## Scope

- Show elections should point to the list of candidates from the particular elections

**Comment by dmtrjsg** [comment]
to be tested on dev: https://dao-git-dev-joystream.vercel.app/#/profile

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/election
wss://3.92.226.32.nip.io/ws-rpc

Still get 404

btn link address - https://dao-git-dev-joystream.vercel.app/#/election/past-elections/3323
<img width="1440" alt="Снимок экрана 2022-10-29 в 21 16 59" src="https://user-images.githubusercontent.com/46903215/198847121-38236ca1-0ccf-49ce-8888-3b490aa8ab21.png">

<img width="447" alt="Снимок экрана 2022-10-29 в 21 26 32" src="https://user-images.githubusercontent.com/46903215/198847245-2bbc9f04-dd7b-4672-81bf-84285b8ad348.png">


actual page address - https://dao-git-dev-joystream.vercel.app/#/election/past-elections/000002kb
<img width="1439" alt="Снимок экрана 2022-10-29 в 21 18 01" src="https://user-images.githubusercontent.com/46903215/198847122-28b2a18e-5c24-4380-bdf9-67219a34e59e.png">

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/election/past-elections/00000005
wss://54.163.55.37.nip.io/ws-rpc


https://user-images.githubusercontent.com/46903215/203354470-0a74ea12-d70a-41d4-8239-fa16d5b0136f.mov
