### ISSUE TITLE
Downscale images before uploading to Atlas Avatar Service

### ISSUE THREAD

**Issue by kdembler** [Joystream/pioneer#3657]
AFAIK, currently when user creates a membership in Pioneer, they are asked to provide a file for their avatar and that file is uploaded to Atlas Avatar Service without any modification. However, it would be beneficial to first downscale that image to some reasonable size to ensure images don't get too big. Let's use the same params as Atlas uses: 192x192, webp format.

For reference, here's an article that descirbed how this can be done with Canvas API: https://imagekit.io/blog/how-to-resize-image-in-javascript/. And also relevant Atlas code (although we use library for cropping images, the export is done with Canvas as well): https://github.com/Joystream/atlas/blob/master/packages/atlas/src/components/_overlays/ImageCropModal/cropper.ts#L176-L184

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203106355891279) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://54.163.55.37.nip.io/network/config.json

Avatar didn't show up after a member created


<img width="888" alt="Снимок экрана 2022-11-16 в 17 41 36" src="https://user-images.githubusercontent.com/46903215/202227070-8f884082-8f7f-47f0-9c8c-a6de8d32995e.png">

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/settings
wss://34.230.5.182.nip.io/ws-rpc

### Create a New Membership
<img width="879" alt="Снимок экрана 2022-11-28 в 15 15 11" src="https://user-images.githubusercontent.com/46903215/204287705-391de103-60f5-4f51-acdc-54010f88ebaa.png">
<img width="528" alt="Снимок экрана 2022-11-28 в 15 17 39" src="https://user-images.githubusercontent.com/46903215/204288175-76a79d9e-2731-45bb-b0c7-8aabe986b24c.png">

### Source: 7kb jpeg 460*460

### Saved:  2kb webp 192*192

Path: https://atlas-services.joystream.org/avatars/f9ff9628-80f4-4a2b-8989-a9ba31259c4d.webp
