### ISSUE TITLE
[USERSNAP] `Recover` button does nothing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3663]
**Taken at**: https://dao.joystream.org/#/profile
**Fields**:

* Houston, we have a problem.: `Recover` button does nothing
* Comment: Trying to recover application stakes. They are displayed on `My Profile`, the `Recover` is visible and enabled. Clicking on it seemingly has no effect.

The log shows no error.

* Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6c836d9a-e998-4740-861b-08b42f160d4e-annotated_c4c01fc2-818d-4f2d-93bb-624327a37762.png?etag=2fe758c0ecb62dadf7441633235e0a39)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6c836d9a-e998-4740-861b-08b42f160d4e-annotated_c4c01fc2-818d-4f2d-93bb-624327a37762.png?etag=2fe758c0ecb62dadf7441633235e0a39)_

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1539x1459
**[Open #337 in Usersnap](https://app.usersnap.com/l/feedback/51281836-a255-4448-aae1-380b033f6d0f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203215092450599) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
NB: Notice that all losing applications are still around in order to allow recovering stake later.

**Comment by bedeho** [comment]
https://joystream.gitbook.io/testnet-workspace/system/working-groups#withdraw-application

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/profile
wss://44.201.112.198.nip.io/ws-rpc

### User applied for a role
<img width="1187" alt="Снимок экрана 2022-10-20 в 13 53 25" src="https://user-images.githubusercontent.com/46903215/196931061-ca6a0f5d-cf20-4cd7-a056-3ceb4184871d.png">

### Recovering
https://user-images.githubusercontent.com/46903215/196930947-28fcc047-7987-47c5-a635-8c7996ea9a7b.mov

<img width="1186" alt="Снимок экрана 2022-10-20 в 13 54 42" src="https://user-images.githubusercontent.com/46903215/196932903-f3b419f9-f7c1-415f-9943-650f9f2f3268.png">

### ApplicationStatusWithdrawn
<img width="1187" alt="Снимок экрана 2022-10-20 в 13 57 37" src="https://user-images.githubusercontent.com/46903215/196930940-9c85f5f8-8595-4952-9a87-b0f340ef3d4b.png">
