### ISSUE TITLE
Talisman signer does not popup

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#3664]
When I connect Talisman signer for the first time, one needs to enter the password and select the account, however, there is no popup that actually displays the wallet in this case, which will leave the user blocked, unable to make forward progress, and unaware that Talisman signer in a special signer authentication mode.

I am on Firefox Browser 105.0.1, OSX and Talisman v1.8.0.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203148958867444) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
we couldn't reproduce, but found a case where membership does not get disconnected when wallet does.

To reproduce:
- start with signed in membership (like alice)
- Disconenect wallet (Polkadot)
- connect with Talisman which does not have alice account
- see how CTAs to sign are blocked


We think that you've caught one of these cases ☝️ 

## Scope
- Disconnect membership when wallet is disconenected

**Comment by polikosi** [comment]
I think everything is working fine. What do yo think? WDYT @dmtrjsg



https://user-images.githubusercontent.com/80429191/200595131-dd473ffa-282b-4622-aa48-1bf1dae345c2.mp4

**Comment by dmtrjsg** [comment]
Yep all g! thanks for testing @polikosi 👍
