### ISSUE TITLE
[feature request] Withdraw application within pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3665]
**Taken at**: https://dao.joystream.org/#/working-groups/my-applications
**Fields**:

* Which feature are you missing?: Withdraw application within pioneer
* What problem would that solve for you?: Currently to withdraw an application (and recover funds) one has to use https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944

User wants to withdraw an application on the `My Applications` tab.
This should also automatically recover the stake (2nd tx).

Note recovering after manually withdrawing externally just failed for me: #3663

* Share your Github or Discord so we can get in touch: l1dev

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**[Open #25 in Usersnap](https://app.usersnap.com/l/feedback/00050de4-7672-4448-b1ab-51c1770140c3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203205871173145) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
We will consider linking the recover stake to withdraw application. Will this be possible for the opening that was already filled?

**Comment by polikosi** [comment]
✅the application was successfully withdrawn
![image](https://user-images.githubusercontent.com/80429191/197131843-f9eec0e0-ba4f-4300-b9eb-70734816ff06.png)
![image](https://user-images.githubusercontent.com/80429191/197132262-7b896a44-add6-45ee-a47a-459b84f0c15f.png)



@dmtrjsg maybe the application counter needs to be updated after the application is withdrawn?
![image](https://user-images.githubusercontent.com/80429191/197132659-7000dd0f-41c2-4218-a1e5-859d2fcae531.png)

**Comment by dmtrjsg** [comment]
@polikosi  thanks for testing this, re your question - I believe you are correct and the counter should reflect the amount of current applications. I'll have a chat with @WRadoslaw and we will decide if this can be fixed as a follow up PR or raised as separate issue 👍

**Comment by dmtrjsg** [comment]
We changed the UI a little to optmise the code, so now it has Status = [withdrawn, pending and hired].  Need to kindly retest this @polikosi 

Cc @traumschule

**Comment by polikosi** [comment]
works as expected. Status = [withdrawn, pending and hired] are displayed correctly

**Comment by traumschule** [comment]
Closing as implemented: it is actually possible to withdraw applications from active openings within pioneer, thanks all!
Withdrawing applications from closed openings should be fixed with the next release: https://github.com/Joystream/pioneer/issues/3251#issuecomment-1181452704
Counter follow-up: #2404 #3734
