### ISSUE TITLE
Tooltip for stake on signing modal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3670]
Tooltip for stake display in fees
![](https://user-images.githubusercontent.com/93924525/191486205-7fa4d5bf-8107-464b-8982-7205ffa7b1b7.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203257871157340) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
Hey @dmtrjsg, what shall it say?

**Comment by dmtrjsg** [comment]
@traumschule How about "Signing this transaction will result in the specified amount of JOY tokens staked for the chosen purpose, resulting in a rivalrous lock applied to this amount until the stake gets recovered."?

**Comment by dmtrjsg** [comment]
Hey quick note.. when the PR is merged to Dev let's not assign `carthage` label ;)

**Comment by polikosi** [comment]
stake is not displayed
![image](https://user-images.githubusercontent.com/80429191/205278281-ea62ddaa-eae9-41bf-84d2-0e5c9a4e0299.png)

**Comment by traumschule** [comment]
Ok good, then the tooltip works as expected, 3766 didn't change how the staking amount is displayed. Please create a new issue if it always just shows the dash.
