### ISSUE TITLE
CM stake display

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3675]
## Scope

- [ ] Sort candidates by stake (as opposed to by member handle)
- [ ] #3696

## Context

Assuming this is the latest version: https://dao-git-carthage-joystream.vercel.app/#/council

The table shows `VOTERS STAKE` (supposedly the sum of all votes' stakes) as `> 0.01`.

1. Candidate's **own stake** is displayed based on https://github.com/Joystream/pioneer/blob/ca9b298abbb45e157bcb734803345c34926933c9/packages/ui/src/council/components/councilList/CouncilListItem.tsx#L25

2. The amount is **smaller** (`<`) than 0.01. Format defined in https://github.com/Joystream/pioneer/blob/ab7b03cd9b068e01e9f383b0a0c89dd9fd8d402e/packages/ui/test/common/model/formatters.test.ts#L177

## Query

Sample to get vote stakes:
```
voteRevealedEvents (where: { inBlock_gte: $revealingStart }) {
  castVote { electionRoundId stake voteFor { memberId }
}
```

## Context

- #2685
- #2866
- #1418
- #1385

**Comment by dmtrjsg** [comment]
Hey @traumschule, had a little trouble parsing this.. can you pls re-iterate the problem statement? What's the expected behaviour and how does this impact the app?

**Comment by traumschule** [comment]
Hey!
1. In the linked version own and voters' stake were swapped. Seems fixed now in https://dao.joystream.org/#/council
2. Small amounts (11k) are displayed as '> 0.01' instead of '< 0.01'.
3. Sort candidates by stake (ought to be fixed before?)
