### ISSUE TITLE
Voting Modal is broken- blocks tests on Pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3684]
## Issue
The voting modal prevents user form voting, issue is detected on carthage. 

## Scope
* [ ] Fix voting modal, enable voting for candidates

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203149003942196) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
✅ Tested here #3609
