### ISSUE TITLE
Allow to re-use accounts with voting locks from previous election cycle without recovery.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3688]
## Scope
* [ ] In the staking account selector for voting display all accounts user has. 
* [ ] Apply same designs we used in proposals account selector to voting accounts with specificities:
Voting lock applied in previous elections can be reused in subsequent elections without recovering
Voting lock applied in current election cannot be reused in current election (show as greyed out with lock icon and tooltip). Tooltip copy: "
* [ ] :point_up: Add tooltip on hover "Voting lock applies to your staking account when vote is casted, preventing this account to be reused in the same election cycle again. To make the balances transferable again, you can recover this lock in my profile> [linking to accounts tab]."
* [ ] :point_up: :point_up: Do not block accounts with voting locks from previous elections to be used in current election. 
* [ ] Only the last lock can be recovered. Casting new vote automatically "overrides" the previous lock. [LInk to slack conv with confirmation](https://joystreamworkspace.slack.com/archives/C039XD9HKKL/p1665583869334289?thread_ts=1665581515.515139&cid=C039XD9HKKL)

## Context
**Taken at**: https://dao.joystream.org/#/election
**Fields**:

* Houston, we have a problem.: make all my stakes available for voting even if they have (vote) locks
* Comment: TODO: offer all stakes available for voting even if they have (vote) locks.

## Context
The stake used in the previous election is not available in this election.
It was used on a candidate who due to the known runtime bug received enough votes and stake but didn&#39;t get elected. However even if used on a winner it has to be available for selection in the next election.
The problem still is and it feels like i wrote this before that the UI tries to decide for me but gets it wrong. Do not hide stakes with existing vote locks from past elections/
Why does the lock expire 3d after the election vs on announcing like the handbooks [requires](https://joystream.gitbook.io/testnet-workspace/system/council#voting).
User needs to be able to decide and fail to learn.

* Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/afe2abd8-c53c-4d12-8581-3ec3b43ed49b-annotated_e68a119f-4cdb-4bb2-9561-633b1ff2f355.png?etag=44c1e767d72e47e27e5ba0b959359f13)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/afe2abd8-c53c-4d12-8581-3ec3b43ed49b-annotated_e68a119f-4cdb-4bb2-9561-633b1ff2f355.png?etag=44c1e767d72e47e27e5ba0b959359f13)_

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1428x1371
**[Open #340 in Usersnap](https://app.usersnap.com/l/feedback/4209310a-cde4-4f56-8b7e-37554c18793a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203206170229285) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
Please explain the 4d locking period. They ought to be available during announcing stage already.
![votestake](https://user-images.githubusercontent.com/31551045/195337126-a194ffa2-6f1d-4708-9149-de67ba8affd5.png)

So obviously me as a user gets easily confused what needs to be done: 1. Go to past votes 2. recover the stake 3. reopen vote screen

Do you have any ideas to explain that or at least add a hint in the modal?
Why is it not possible to reuse without unlocking?

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/election
wss://44.201.112.198.nip.io/ws-rpc

Accounts with voting locks from the previous election cycle can be reused without recovery

### Prev election cycle locks
<img width="1184" alt="Снимок экрана 2022-10-21 в 16 52 37" src="https://user-images.githubusercontent.com/46903215/197218853-88241a18-8ff9-4b97-8814-492c96f3d414.png">

### New election. First vote(c11 & c12 available) Voted 3333 tJOY for candidate 3
<img width="877" alt="Снимок экрана 2022-10-21 в 16 54 01" src="https://user-images.githubusercontent.com/46903215/197218168-82d63878-1d21-48b7-bc66-0b0bb597c7d7.png">

### New election. Second vote(only c12 available) Voted 3337 tJOY for candidate 6
<img width="881" alt="Снимок экрана 2022-10-21 в 16 55 49" src="https://user-images.githubusercontent.com/46903215/197218171-41e30362-bc80-4247-a15d-c7e24dd8e284.png">
<img width="1180" alt="Снимок экрана 2022-10-21 в 16 57 24" src="https://user-images.githubusercontent.com/46903215/197218174-5c7f6d8b-41f2-43e8-aade-75abc003a0ca.png">

### Locks updated
<img width="1188" alt="Снимок экрана 2022-10-21 в 16 57 57" src="https://user-images.githubusercontent.com/46903215/197218177-41d32684-baff-4837-9cf8-c2531dd34fc9.png">
