### ISSUE TITLE
Proposal title length prevents from creating and returns generic failure error code

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3689]
## Scope

- [ ] Limit length on proposal title on input
- [ ] Display validation error :Max of X characters allowed.

## Context

https://discord.com/channels/811216481340751934/812345044094156811/1029771650977251339

**Taken at**: https://dao.joystream.org/#/proposals/current
**Fields**:

* Houston, we have a problem.: I can&#39;t create a signal proposal
* Comment: Without error :)
* Link to polkadot block: https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/explorer/query/0x3060c9c99bcf326544463138523469017d3a7c1fedef58c512895a8c90ab700f
* Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d3020c46-31cd-4cc9-ad3c-3ca767349a1a-annotated_51aa56e3-4dd6-43d7-95c8-ecb7a75a115e.png?etag=2a4e06005300bb456f3c21de6a7ebe8c)
_[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d3020c46-31cd-4cc9-ad3c-3ca767349a1a-annotated_51aa56e3-4dd6-43d7-95c8-ecb7a75a115e.png?etag=2a4e06005300bb456f3c21de6a7ebe8c)_

**Browser**: Chrome 105 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 982x792
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/0d151927-0b05-40cd-8283-845e68d2963d_screen_recording_ebe358a3-2cc4-4d6b-8abd-a9d93c31b8a0.webm?etag=5701a9288633a9bc0f482bd7764312ed)**
**[Open #341 in Usersnap](https://app.usersnap.com/l/feedback/6abaa2bd-fe36-4fc9-b2f8-c5921bd9f61d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203150750336038) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Not reproduceable on Carthage. Will double check and deploy a hot fix if the issue turns out to be severe. 

@thesan @WRadoslaw fyi..

**Comment by WRadoslaw** [comment]
@dmtrjsg There is already length validation for the proposal title, so either we exceed the scope or this ticket can be closed
