### ISSUE TITLE
[USERSNAP] Account selector drop down tooltip must not scroll

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3690]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Account selector drop down tooltip must not scroll
- Comment: https://github.com/Joystream/pioneer/issues/3687

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/fd9040c5-90c2-42c0-84d5-460ce40afc11-annotated_9dcf11f7-52c2-438b-a669-8083358a0a7b.png?etag=fc6fe4be9159b784e8a111a7080b714a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/fd9040c5-90c2-42c0-84d5-460ce40afc11-annotated_9dcf11f7-52c2-438b-a669-8083358a0a7b.png?etag=fc6fe4be9159b784e8a111a7080b714a)*

**Browser**: Chrome 106 (macOS Catalina)
**Screen size**: 1512x982
**Browser size**: 1869x977
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/9dfdd583-93f1-4d5c-beaf-02d9edbcc98f_screen_recording_ad5aec10-ed79-4a37-a3d1-b5f42808edda.webm?etag=4b926f794c00b427caf4da7075b4c958)**
**[Open #342 in Usersnap](https://app.usersnap.com/l/feedback/24a696d9-f9be-440e-a22c-47cb76b8a0a1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by polikosi** [comment]
tested on: https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

Announce candidacy:

https://user-images.githubusercontent.com/80429191/204294398-d04d4fda-4a26-4314-8e46-2f31bb7f1137.mp4


Vote for council:

https://user-images.githubusercontent.com/80429191/204294348-087aeed3-7a74-4406-a9da-f683b79843d6.mp4

**Comment by polikosi** [comment]
tested on: https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

Announce candidacy:


https://user-images.githubusercontent.com/80429191/205291913-3bc56887-78fa-4f24-b960-1bc1d58b66d5.mp4


Vote for council:

https://user-images.githubusercontent.com/80429191/205291854-89780257-2be4-4685-b1a3-2e9f45078252.mp4

**Comment by traumschule** [comment]
Good enough for me.
