### ISSUE TITLE
[USERSNAP] Incorrect display of election results

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3695]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Incorrect display of election results
- Comment: isonar picked up his application but it still shows up on the page
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/77f37388-1418-445d-89e4-513189fc51b3-annotated_433051bd-9a63-4813-bb23-612a231b46a3.png?etag=6dc7d9bf27cae890170f6c4e2c33f7c3)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/77f37388-1418-445d-89e4-513189fc51b3-annotated_433051bd-9a63-4813-bb23-612a231b46a3.png?etag=6dc7d9bf27cae890170f6c4e2c33f7c3)*

**Browser**: Chrome 105 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/b27afdcb-43df-40d7-a398-fff7ee743de3_screen_recording_92c89003-fa3c-4b54-93ed-e9585c56b26f.webm?etag=16c9e5625a301e5280390f77b71e11f0)**
**[Open #343 in Usersnap](https://app.usersnap.com/l/feedback/b0e1c6a0-f7e1-4f33-b4b2-76bd7665c544?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@traumschule this one was hotfixed to prod, just added to QA lane on project 55 to get validated on the preview branch or production.

**Comment by thesan** [comment]
@traumschule @dmtrjsg this hotfix was also merged on `carthage` yesterday. So it might be better to test it there

**Comment by polikosi** [comment]
✅tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://44.201.112.198.nip.io/network/config.json

![image](https://user-images.githubusercontent.com/80429191/196775403-0ebf4e43-fbd3-4590-9211-15dd8bf01f40.png)
Candidate2 was withdraw

works as expected
![image](https://user-images.githubusercontent.com/80429191/196780197-458cd0a3-b364-4636-9d94-a3ff61c5e7c1.png)
