### ISSUE TITLE
Display small amounts as <0.01 JOY 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3696]
now everywhere is > 0.01 Joy

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203156893140931) by [Unito](https://www.unito.io)

**Comment by polikosi** [comment]
🚫tested on wss://44.201.112.198.nip.io/ws-rpc
I expected that in all situations the balance would be displayed <0.01
![image](https://user-images.githubusercontent.com/80429191/196934403-de49797d-1023-4781-b3de-37c108ed752e.png)

![image](https://user-images.githubusercontent.com/80429191/196934050-35e73bf1-b0f8-41d3-b0f3-16320d6f6de7.png)
![image](https://user-images.githubusercontent.com/80429191/196934105-6bbf0ae0-e105-4d30-90ac-defed984f701.png)

**Comment by dmtrjsg** [comment]
@WRadoslaw perhaps you could pick this one up?  I think it looks good on the modals and in the fee calc component, but some account balances are not shown correctly, pls see the test restuls.

**Comment by thesan** [comment]
@polikosi @dmtrjsg I'm not sure this is incorrect. `1.009 tJOY` would show has `1.01 tJOY` so it make sense to me that `0.009 tJOY` shows has `0.01 tJOY`. WDYT ?

**Comment by dmtrjsg** [comment]
@thesan I see that we are round it up in one case.. just to clarify if it goes 0.006 it shows as 0.01, but if it is 0.004 it shows as <0.01? 

In any case this is a very rare occasion to have actual balances display like it.. and we designed this for tx fess mostly as that's where it is likely to be shown more often, although with the latest weights also unlikely :)

**Comment by thesan** [comment]
> @thesan I see that we are round it up in one case.. just to clarify if it goes 0.006 it shows as 0.01, but if it is 0.004 it shows as <0.01?

Yes you can check this here: https://pioneer-2-storybook-git-carthage-joystream.vercel.app/?path=/story/common-tokenvalue--default&args=value:000+0040000000

**Comment by dmtrjsg** [comment]
We show approximate values everywhere so in this case (which will also be super rare to be displayed in the balances) the decision taken after discussing with the team to keep it like that. If it gets reported by any of the users we will look into reopening this again. Thanks guys for testing and raising this up!
