### ISSUE TITLE
Auto release of candidacy lock when using same membership with diff accounts in 2 elections

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3697]
## Context
There is also one peculiar behavior of announce_candidacy, I'm not sure if it affects Pioneer though. This is in a following scenario:
I announce candidacy in the 1st election, staking 100 JOY from staking_account_1
I lose the election
At this point I still have 100 JOY candidacy lock on staking_account_1
I announce candidacy in the 2nd election, staking 50 JOY from staking_account_2
The lock on staking_account_1 is automatically released

:warning: This is only if the member_id  is the same during 1st and 2nd election ofc

## Scope
- [ ] @ QA: validate that the above behaviour is correctly treated on Pioneer, meaning stake 1 is released automatically.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203156934675734) by [Unito](https://www.unito.io)

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/settings?network-config=https://44.201.112.198.nip.io/network/config.json

### Founded 2 accounts - c11, c12
<img width="1181" alt="Снимок экрана 2022-10-19 в 14 59 56" src="https://user-images.githubusercontent.com/46903215/196703835-15a7b06c-9dfa-434e-9d5e-5721eb4356dc.png">

### Membership c11 created
<img width="1180" alt="Снимок экрана 2022-10-19 в 15 00 08" src="https://user-images.githubusercontent.com/46903215/196703848-362215bf-8b49-4ded-97a2-d62c162510c8.png">

### Election 1: Member c11 announced candidacy and staked 1666.67 tJOY(from acc c11)
<img width="1184" alt="Снимок экрана 2022-10-19 в 15 07 06" src="https://user-images.githubusercontent.com/46903215/196703850-15513c8f-1998-40a8-845a-e41ac72589c7.png">
<img width="1183" alt="Снимок экрана 2022-10-19 в 15 07 41" src="https://user-images.githubusercontent.com/46903215/196703857-943d71d9-116d-4836-8a5e-d86b85dbab4e.png">
<img width="1184" alt="Снимок экрана 2022-10-19 в 15 34 04" src="https://user-images.githubusercontent.com/46903215/196703863-19649139-9a76-4bc9-8b8f-35fe917f2d20.png">

### Member c11 lost an election. Alice become a council
<img width="1180" alt="Снимок экрана 2022-10-19 в 15 41 48" src="https://user-images.githubusercontent.com/46903215/196703871-899f02a8-0ea6-4a8f-a581-9272f5742044.png">

### Election 2: Member c11 announced candidacy and staked 2666.67 tJOY(from acc c12)
<img width="1182" alt="Снимок экрана 2022-10-19 в 16 20 32" src="https://user-images.githubusercontent.com/46903215/196703874-e91466cd-8e66-4aaa-ab52-0d4ef4502902.png">

### ✅ Stake 1(Election 1 - 1666.67 tJOY) is released automatically for c11
<img width="1188" alt="Снимок экрана 2022-10-19 в 16 20 57" src="https://user-images.githubusercontent.com/46903215/196703878-6f3609e6-3ad1-48e7-b63a-c5073f292b34.png">
