### ISSUE TITLE
Revealing issue - unable to reveal more than 1 candidate on network 54.*

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3711]
## Context
During the QA test for:
* https://github.com/Joystream/pioneer/issues/3669#issuecomment-1281229788

On `54.227.116.57.nip.io` ( election `cycle_id: 713`) @ivanturlakov:
> 3 council seats
> 
> Trying to hold an election.
> For each candidate I vote from a new account (except the 4th).
> 1 - 1000
> 2 - 2000
> 3 - 3000
> 4 - 4000 (he votes for himself)
> 
> The stage of revealing the votes.
> There is an opportunity to reveal only the vote for the 3rd candidate.

On the QN only the 3rd vote was revealed:
```json
[
  {
    "votePower": "10000000000000",
    "castBy": "j4UGeAgkw76FXWmP34ZijA6rTiJaSqXHjEux6i3e7EvnmTyi2",
    "commitment": "0x30bddf42662e1db46e473d6a8a6253d630b261c716aa3ce88ffd485b47fd5cf9",
    "votecasteventcastVote": [ { "inBlock": 143409 } ],
    "voteFor": null
  },
  {
    "votePower": "20000000000000",
    "castBy": "j4SEEdc9wnZfVZ3mwcamS7ojmLBcLtYU5dopkXfRsi1285HuQ",
    "commitment": "0x803d040485c09c7c8ebe6405f441305fd24e0bafc8d96d35be95f192f223c120",
    "votecasteventcastVote": [ { "inBlock": 143417 } ],
    "voteFor": null
  },
  {
    "votePower": "30000000000000",
    "castBy": "j4SZd51TYDJLmcFvCq938CiseRGbqSyezXDWkPHPDbmBDw1oC",
    "commitment": "0x4e7c824d33bff598eb60a198c707aded587ed73235f76b65e501949e83017997",
    "votecasteventcastVote": [ { "inBlock": 143429 } ],
    "voteFor": { "memberId": "19" }
  },
  {
    "votePower": "40000000000000",
    "castBy": "j4Wtt8U69mpSiQmMSWrbU7bkcPnJqQeJjeV3Yh5XKtWMeDjqb",
    "commitment": "0x01d4d1e2353865558c73c507b310b92827b7d1884d938e52f31e13d7174de7bb",
    "votecasteventcastVote": [ { "inBlock": 143364 } ],
    "voteFor": null
  }
]
```

The issue comes from the local storage where `votes:713` is:
```json
[
  {
    "salt": "0x0da6dd89befa812cbb26acad55abfa7e536956c1394d7e2f93da3892f3cfea78",
    "accountId": "",
    "optionId": "19"
  },
  {
    "salt": "0x01beb29ba5901c94dd701e814473ab56914c3631caec495464f1cb3262e48b2c",
    "accountId": "j4SZd51TYDJLmcFvCq938CiseRGbqSyezXDWkPHPDbmBDw1oC",
    "optionId": "19"
  }
]
```

## Scope
* [ ] Resolve the bug

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1203189623921173) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@traumschule needs to be re-tested as all hypotheses we could think of ran out .. so we need to validate its a real issue before spending more time on this. Please feel free to assign to qa.

**Comment by thesan** [comment]
I might have figured out what happened

**Comment by ivanturlakov** [comment]
✅ Tested here https://github.com/Joystream/pioneer/issues/3613#issuecomment-1297210516
