### ISSUE TITLE
QN subscription is unreliable

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3722]
## Context

More and more often Pionneer takes a very long time or fail all together to connect to the QN `stateSubscription` both on the `Joystream-testnet` and `carthage` playgrounds. This happens also occasionally happens on the graphQL playground.

The direct consequence is that the transaction last step "Processing transaction" often never ends. Which result in issues like #3381 and #3662. Also it prevents the connectivity UI to accurately monitor the QN.

## Scope

- [x] #3723
- [x] ~#3724~
- [x] #3725
- [x] https://github.com/Joystream/pioneer/issues/3770

**Comment by dmtrjsg** [comment]
3724 - removed based on the changes that will be implemented on the QN side. 
3725 - may be removed after more tests are done
