### ISSUE TITLE
Introduce a changelog

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#3730]
Same as this https://github.com/Joystream/atlas/issues/3358.

**Comment by dmtrjsg** [comment]
Taking this to sprint to start from Carthage release.. @bedeho can you share a good example which you mentioned on the morning call a few days ago to be used as reference pls?

**Comment by bedeho** [comment]
Here is the raw file https://github.com/arvidn/libtorrent/blob/RC_2_0/ChangeLog, and this is how it is used in Github releases https://github.com/arvidn/libtorrent/releases.
