### ISSUE TITLE
 application counter needs to be updated after the application is withdrawn

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3734]
see https://github.com/Joystream/pioneer/issues/3665#issuecomment-1286540191
![](https://user-images.githubusercontent.com/80429191/197132659-7000dd0f-41c2-4218-a1e5-859d2fcae531.png)

**Comment by traumschule** [comment]
Let's test it once more please. https://github.com/Joystream/pioneer/issues/3665#issuecomment-1288516739

**Comment by polikosi** [comment]
tested on wss://44.201.112.198.nip.io/ws-rpc
✅works as expected

submitted an application
![image](https://user-images.githubusercontent.com/80429191/199506142-ad3f0d73-c6f4-4520-b04f-2fd4acda68a5.png)
the application has been withdrawn
![image](https://user-images.githubusercontent.com/80429191/199506198-c14bfda4-9468-4256-9fd9-8a1b8d35d3b8.png)

**Comment by traumschule** [comment]
Thanks!
