### ISSUE TITLE
All signer errors are reported as insuficent fees

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3762]
![image](https://user-images.githubusercontent.com/6571453/198108187-bde1ea5d-d076-46b6-839a-d8860ef20c31.png)

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-carthage-joystream.vercel.app/#/profile

Transaction interrupted

<img width="1422" alt="Снимок экрана 2022-11-03 в 12 01 24" src="https://user-images.githubusercontent.com/46903215/199694921-30f0c5e5-1775-4e3c-8f60-918651de1cd5.png">
<img width="1440" alt="Снимок экрана 2022-11-03 в 12 02 01" src="https://user-images.githubusercontent.com/46903215/199694622-80f28ea4-3147-4b68-9c09-6d33ba3e42a5.png">
