### ISSUE TITLE
Joystream Pioneer Forum Back Link

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#3768]
### Scope 
- [ ]  Add page number to the url so "back" in-app button brings to the right previous page in case of paginated prev page.

### Context

Hello Guys;

I observed a limitation in Joystream Pioneer Forum. I'm not sure if it's a bug (not working) or improvement (no feature of this function).
Please see this Atlas video: https://play.joystream.org/video/27767

You will notice I clicked a forum thread on Page 9 of a Category. When I clicked back, I assumed I would go back to Page 9 of Category. Instead, I was brought to Page 1. So if I want to check the next thread on that page, I will need to click again Page 9.

I hope I explained it well.

Thank you

**Comment by dmtrjsg** [comment]
Thanks you've explained it very well and extra points for the nice music 😄   I agree this is pretty annoying for a heavy Forum user..

**Comment by vrrayz** [comment]
I'll like to take this up as well. I just dropped a fix for [#2977](https://github.com/Joystream/pioneer/issues/2977) in this PR [here](https://github.com/Joystream/pioneer/pull/3798)

**Comment by vrrayz** [comment]
I just fixed this here #4147

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/category/1

This case works as expected


https://user-images.githubusercontent.com/46903215/222966435-c3f19996-532d-4333-b922-5f6ad44a55d4.mov



Also, I found another scenario with "back btn" bug #4215
