### ISSUE TITLE
Isolate localstorage writes from the forum tread watchlist

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3769]
Once #3719 will have made its way into `dev`. To prevent users from loosing some of their watchlist by adding threads from different browser tabs, it would be good to change these into something like:
```ts
setWatchlist((watchlist = []) => [...watchlist, threadId])
setWatchlist((watchlist = []) => watchlist.filter((id) => id !== threadId))
```

_Originally posted by @thesan in https://github.com/Joystream/pioneer/pull/3654#discussion_r1007942049_

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-staging-joystream.vercel.app/#/forum/watchlist
wss://34.230.5.182.nip.io/ws-rpc

Initial state
<img width="676" alt="Снимок экрана 2023-01-04 в 13 37 47" src="https://user-images.githubusercontent.com/46903215/210547601-547542a0-8c36-497e-a003-c3844b7d2729.png">

First three topics from the latest opened in a new tab each and were added to the watchlist
<img width="1051" alt="Снимок экрана 2023-01-04 в 13 38 18" src="https://user-images.githubusercontent.com/46903215/210547633-d761d68c-2b65-48f7-9726-b4cee738afcf.png">

Result
<img width="1437" alt="Снимок экрана 2023-01-04 в 13 39 30" src="https://user-images.githubusercontent.com/46903215/210547637-a204accf-ed7a-481b-a0f8-8abd0a7351fb.png">
