### ISSUE TITLE
Keep testnet after Carthage and Mainnet release

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3779]
## Scope
* Keep TestNet Autoconfig, Local and add Mainnet in the settings module
> it will not be called  Carthage, it will only be called testnet
* Make mainnet as default

> After checking the Etherium test networks, it does seem like they are operating with the naming convention of ETH on testnets as well. On Kova it was Kovan Ether KETH, while on Rinkeby it was just ETH.

## QA

Can be tested on: https://pioneer-2-git-mainnet-joystream.vercel.app/ where mainnet shoud be set to `34.230.5.182.nip.io`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203268493487179) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
To be clear this about the ability to connect to a staging network with same types? There could be complications to connect to say a Rhodes chain, except someone maintains an archival instance.

**Comment by dmtrjsg** [comment]
This is to preserve multiple networks support for Pioneer App, and keep the networks selectable in the settings menu. The test network will be auto-conf set up and we will always try to keep the version of the test network closest to the one launched to production.

Also, this issue is earmarked to be attempted by the JSG team.

**Comment by polikosi** [comment]
tested on: https://pioneer-2-git-mainnet-joystream.vercel.app/
![image](https://user-images.githubusercontent.com/80429191/206228423-3684647a-7e0d-42ee-9e46-ec6fa308cb2c.png)
![image](https://user-images.githubusercontent.com/80429191/206228464-3ffde15e-f2f3-4e19-bc40-a3294a21b857.png)
