### ISSUE TITLE
Add a button to refresh the `auto-conf` network config

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3799]
## Scope
- [x] Add button underneath the network selection ONLY when Auto-conf network is chosen
- [x] Remember the configuration URL  (so store it somewhere)
- [ ] Design of button

<img width="433" alt="Screenshot 2022-11-08 at 15 00 37" src="https://user-images.githubusercontent.com/93924525/200548011-64076dee-f6f3-4c4b-9d4e-505ada6cf9b3.png">

## Context
The config url will have to be saved and simply refetched when the button is pressed

**Comment by dmtrjsg** [comment]
decided to keep as-is since this is mostly a technical issue so acceptable
