### ISSUE TITLE
Add Chain Metadata For Signers

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3831]
![Screenshot 2022-11-14 at 14.33.41.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/91b50ec8-8d15-4152-8fdf-c32c5270198a)

![Screenshot 2022-11-14 at 14.33.46.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/3fa58349-8e6d-4042-b612-b593c6aefd68)

**Comment by traumschule** [comment]
Implementations
- 'outdated metadata' banner: https://github.com/polkadot-js/apps/blob/master/packages/page-accounts/src/Accounts/BannerExtension.tsx#L42
- Pioneer1: Settings > update metadata: https://github.com/Joystream/joystream/blob/giza/pioneer/packages/page-settings/src/useExtensions.ts#L47
- same in Polkadot-JS: https://github.com/polkadot-js/apps/blob/master/packages/page-settings/src/useExtensions.ts#L111
![](https://cdn.discordapp.com/attachments/1035124220012810280/1041822486318288937/update-metadata.png)

For pioneer2 the sidebar could have ⚠️ (or something more indicative of wallet context) with a tooltip.

**Comment by thesan** [comment]
This issue was tested in the PR: https://github.com/Joystream/pioneer/pull/3872#issuecomment-1557242827
