### ISSUE TITLE
Update TJoy to Joy in Pioneer UI since we are in Carthage Release already

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#3834]
Hello Guys:

I just observed on Pioneer UI. For Carthage release, I think we should be using Joy instead of TJoy.
Please see picture on link below...

https://discord.com/channels/811216481340751934/1035124220012810280/1041979345448730665

Thanks.

**Comment by kdembler** [comment]
Those are still testnet JOYs, they will become real JOYs only on mainnet

**Comment by Songoku1691** [comment]
Oh. Thanks for update Sir. In my Pioneer UI, I could see my joy token allocation already but unit is TJoy.

**Comment by thesan** [comment]
Right but I'm closing this now because this was taken care of on a different branch. Here are the original issues: #3400, #3527
