### ISSUE TITLE
Tooltips for Vesting Lock Widgets

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3836]
## Context

Missing tooltips:
![Screenshot 2022-11-15 at 15.45.40.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/35b26b4b-31ad-4202-b9fc-775e70b21ff3)

## Scope
- [ ] Upd tooltip for Total Initial Vesting

Total Initial vesting is the amount of tokens that are allocated to this account in the Genesis block, or via vesting transfer. From the very beginning this amount is fully locked, and some gets unlocked in accordance to vesting schedule. This is a sum of locked and all historically unlocked funds.

- [ ] Upd tooltip for Total Locked in Vesting

Total locked in vesting encapsulates all of the tokens from genesis allocation and vesting transfers that are subject to the vesting schedules. This amount gets reduced with every block in accordance to multiple combined vesting schedules each corresponding to a related vesting transfer which can be with its own terms.

**Comment by ivanturlakov** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/#/profile
wss://rpc.joystream.org:9944

✅ Upd tooltip for Total Initial Vesting
<img width="847" alt="Снимок экрана 2022-12-15 в 15 20 54" src="https://user-images.githubusercontent.com/46903215/207869533-f15c94a6-bbcf-4144-a6e8-0357421afc85.png">

✅ Upd tooltip for Total Locked in Vesting
<img width="1193" alt="Снимок экрана 2022-12-15 в 15 21 17" src="https://user-images.githubusercontent.com/46903215/207869608-bfd386a4-5b91-4df4-8fc6-804493d10ab2.png">
