### ISSUE TITLE
Rejected applicant is displayed as `Pending`

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3856]
Follow-Up to #2913 ([context](https://github.com/Joystream/pioneer/pull/3789#issuecomment-1317293382))

If an applicant wasn't hired display `Rejected` status.

![](https://user-images.githubusercontent.com/46903215/202234756-2722015b-9c35-4345-98f8-3027ebb9cb38.png)

![](https://user-images.githubusercontent.com/46903215/202234755-21167e2e-8f19-4cd6-ab91-0f8e9fd95909.png)

**Comment by thesan** [comment]
@ivanturlakov QA'ed this one on the PR deployment: https://github.com/Joystream/pioneer/pull/4033#issuecomment-1380217061
