### ISSUE TITLE
Fix balance used to validate the voting stake

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3869]
Voting: 
1. Transferable balance -> Total Balance
2. Validation message should be “Insufficient balance to cover staking amount provided.”

![image](https://user-images.githubusercontent.com/6571453/203023862-e10e036e-2a84-449c-ae96-382c600fb55c.png)

**Comment by traumschule** [comment]
Fixed in #3866 please review.

**Comment by traumschule** [comment]
Expected validation error is now: `Selected amount exceeds account balance.`

**Comment by polikosi** [comment]
tested on: https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json
![image](https://user-images.githubusercontent.com/80429191/204293757-e95ccf05-071c-408d-8db6-a19b7d4803a3.png)
