### ISSUE TITLE
When App is not connected to the chain, Onboarding modal cannot be opened

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3870]
## Context

When App is not connected to the chain, the wallet cannot be connected

## Scope
- [ ] Allow to start onboarding flow (Connect wallet part) even if the network is not connected

**Comment by traumschule** [comment]
discussed in #3804

**Comment by ivanturlakov** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/#/profile
wss://34.230.5.182.nip.io/ws-rpc

With account
https://user-images.githubusercontent.com/46903215/206441213-8465af2a-932c-48f4-a3a2-7dbff78ad00b.mov

Without account
https://user-images.githubusercontent.com/46903215/206441271-94df98a0-cb11-45d6-861b-ea550fe24a7e.mov
