### ISSUE TITLE
Votes can't be revealed although present in local store

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3873]
## Context

Votes are not displayed in my votes either.

![](https://cdn.discordapp.com/attachments/815192060276506664/1044638554527125514/image.png)

![](https://cdn.discordapp.com/attachments/815192060276506664/1044653635411382302/image.png)

[Report](https://discord.com/channels/811216481340751934/815192060276506664/1044634842324815962)

## QA

Go through an election, just to check that what was working still is. To really test the original issue more than 50 votes should be cast and all off them should show a revealed even before any of the other got revealed, which would be really time consuming.

**Comment by dmtrjsg** [comment]
This comment indicates that polkadot.js app usage experiences same problem: https://discord.com/channels/811216481340751934/815192060276506664/1044669116830724227

**Comment by dmtrjsg** [comment]
Root acc vote could be revealed but not the other ones.. even thought they are in the local storage

**Comment by traumschule** [comment]
Just tested on https://dao.joystream.org/#/election
![votes-not-shown](https://user-images.githubusercontent.com/31551045/203756494-224201b4-022a-458f-bce4-83f0edce7e89.png)

**Comment by thesan** [comment]
> Just tested on https://dao.joystream.org/#/election
> ![votes-not-shown](https://user-images.githubusercontent.com/31551045/203756494-224201b4-022a-458f-bce4-83f0edce7e89.png)
> 

@traumschule what's strange on this screenshot is that the "My votes" count is 0, so the votes aren't returned from the QN... Please could you pm me on discord one of the account which has a non revealed votes, so I can check wether the QN actually has a commitment for this account ?

**Comment by ivanturlakov** [comment]
✅ Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/#/election
wss://34.230.5.182.nip.io/ws-rpc

**Member 1 voted for Alice twice**
11 000 - root account
12 000 - another account

**Member 2 voted for IvanT**
10 000 - root account

**Total - 3 votes**

<img width="1211" alt="Снимок экрана 2022-12-07 в 12 04 50" src="https://user-images.githubusercontent.com/46903215/206152916-1bef003c-688b-4ff3-bfc4-72872a5dc18e.png">

**Was able to reveal all 3 votes without problems**
<img width="1194" alt="Снимок экрана 2022-12-07 в 12 09 02" src="https://user-images.githubusercontent.com/46903215/206152929-abbf883b-2acf-4ace-a2c6-941fdc1eaf9e.png">
<img width="1185" alt="Снимок экрана 2022-12-07 в 12 09 15" src="https://user-images.githubusercontent.com/46903215/206152935-b204119f-bf3b-4472-92ae-ecfbf14be818.png">

**Votes revealed**
<img width="1189" alt="Снимок экрана 2022-12-07 в 12 12 42" src="https://user-images.githubusercontent.com/46903215/206152938-d265caff-c3b5-4536-81d7-f062427b7c0e.png">

**Alice is a new council member**
<img width="906" alt="Снимок экрана 2022-12-07 в 12 19 12" src="https://user-images.githubusercontent.com/46903215/206152944-a6f586f1-daa1-4e4c-82c4-7dd333ba5985.png">
