### ISSUE TITLE
Handle governance blacklisting

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#3874]
https://github.com/Joystream/joystream/issues/2927

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203422525277066) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@ninja-fire we need the UX to inform user that this account cannot be used for voting as was added to the Governance-Blacklist.

**Comment by bedeho** [comment]
The simplest solution here may actually not require any design input: at the stage when the user is selecting an account to use when voting, all blacklisted accounts (which Pioneer can easily identify) will not be listed. Anyone so advanced as to use this will almost certainly either not have the account in their signer to begin with or at least know that they have self-imposed blacklisting. If we do this, designer needs to do nothing basically.
