### ISSUE TITLE
Carthage election stakes mismatch

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3883]
It was reported that the revealed / credited stake does not match the vote stake.

Vote stake 250k
![](https://cdn.discordapp.com/attachments/813361923172335648/1044699945497808987/image.png)

"Total stake" 150k
![](https://cdn.discordapp.com/attachments/813361923172335648/1044699701699678229/image.png)

Additionally there are multiple reports for problems revealing with pioneer / p-js Joystream/pioneer#3873

Kindly check if there is a bug in the new implementation.

## QA

Same as #3873 going through 1 complete election, and checking that everything still works is good enough IMO

**Comment by polikosi** [comment]
Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/#/election
wss://34.230.5.182.nip.io/ws-rpc

Good enough for me.
revealed all votes
![image](https://user-images.githubusercontent.com/80429191/206250385-61be532d-036f-4b08-aea7-1beda4f980a8.png)

**Comment by traumschule** [comment]
Considering #3881 a complete test would involve more than 50 (revealed) votes but let's assume it works.
