### ISSUE TITLE
Replace proposal Caution modal

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3884]
Suggestion to replace the disruptive `Caution` modal with a checkbox with warning and a tooltip to the left inside `AddNewProposal` modal footer which has a lot of free space.

![caution](https://user-images.githubusercontent.com/31551045/203790056-6a4214a8-e4b3-4ff8-9b8a-ca520736bb46.png)

![add-proposal-modal](https://user-images.githubusercontent.com/31551045/203790141-1c0d74f2-f0d6-4179-b60a-948422cd5570.png)

^ add here: [ ] I am aware of the possible risks associated with creating a proposal<sup>?</sup>

**Comment by dmtrjsg** [comment]
@traumschule there is a "do not show this again" control that should do the job ;) And this modal is aimed for the first time users only so we believe it does more good than harm 😇
