### ISSUE TITLE
[USERSNAP] incorrect text (latin words) once push withdraw button for Council election

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3895]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: incorrect text (latin words) once push withdraw button for Council election
- Comment: incorrect text (latin words) once push withdraw button for Council election

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/31bc076d-8bb5-4d31-9450-7b26c1933afd-annotated_040bc0e1-42a0-4eec-99d3-c4f9b9b57c58.png?etag=db3a04c20e69386a161d06676301d2e8)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/31bc076d-8bb5-4d31-9450-7b26c1933afd-annotated_040bc0e1-42a0-4eec-99d3-c4f9b9b57c58.png?etag=db3a04c20e69386a161d06676301d2e8)*

**Browser**: Chrome 107 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x747
**[Open #344 in Usersnap](https://app.usersnap.com/l/feedback/d1bb7bff-4ef2-43f3-b4a6-3ba41d8d91da?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Could be this reported [here](https://discord.com/channels/811216481340751934/815192060276506664/1046721663846338631)

![](https://cdn.discordapp.com/attachments/815192060276506664/1046721663535943720/image.png)

**Comment by dmtrjsg** [comment]
Let's update the highlighted text to "Please remember that this action is irreversible. By withdrawing your candidacy you will also withdraw your stake and will be able to apply to council election with this membership from the next round onwards."

**Comment by dmtrjsg** [comment]
@ivanturlakov @polikosi guys could you pls double check if re-applying is possible? thank you in advance..

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/election
wss://34.230.5.182.nip.io/ws-rpc

>if re-applying is possible? 

@dmtrjsg Yes, I was able to reapply in the current election cycle after withdrawing my prev application

<img width="1210" alt="Снимок экрана 2022-12-05 в 12 28 19" src="https://user-images.githubusercontent.com/46903215/205616403-c02e1290-b4bc-4646-bfbb-8968f75f1e91.png">

**Comment by traumschule** [comment]
Based on test result i changed the text to
>  Withdrawing a candidacy is irreversible however you can announce another one with the same account afterwards.
> This is currently the only way to edit bullet points and agenda.

Please correct. In general do you prefer the informal "you can" or "it is possible"?

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/election
wss://34.230.5.182.nip.io/ws-rpc

<img width="952" alt="Снимок экрана 2022-12-22 в 13 19 46" src="https://user-images.githubusercontent.com/46903215/209124052-6c16a634-612b-4375-bab5-8972b0d8966a.png">
