### ISSUE TITLE
successfully announced candidacy modal bug

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#3899]
https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

https://user-images.githubusercontent.com/80429191/204292341-c6bf1b03-0ed0-4afb-a426-e60bb951f56a.mp4

**Comment by polikosi** [comment]
same problem with the Proposals:

https://user-images.githubusercontent.com/80429191/204297029-fa6d1140-a58c-409b-b4cd-0d4a915413b5.mp4

**Comment by traumschule** [comment]
Thanks @polikosi. Confirm-close-confirmation (#3718) comes up after successful announcement / proposal creation and shouldn't.

**Comment by ivanturlakov** [comment]
I also often see this window in the wrong place #3907

**Comment by dmtrjsg** [comment]
@gyroflaw please feel free to proceed with this one and if a fast turnaround we can release as early as next week and before Pioneer relaunches after mainNet.

**Comment by dmtrjsg** [comment]
⚠️ We ony want to keep this conf modal when user closes the dialogue where transaction was not submitted. This was done not to loose the progress of typing up the text inputs for:

- council candidacy
- proposals
- forum posts
- openings 
- applications

**Comment by polikosi** [comment]
Tested on: https://pioneer-2-git-fork-gyroflaw-fix-close-confirm-22116c-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

✅ council candidacy
✅ proposals
✅ forum posts
✅ add post
✅ add new thread
✅ openings
✅ applications

**Comment by thesan** [comment]
The PR still needs a few adjustment
