### ISSUE TITLE
Update tooltip text Proposals>Preview>Discussion Open

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#3900]
Update tooltip text. Remove "Dolore magna anim eu nisi qui."
![image](https://user-images.githubusercontent.com/80429191/204300922-396f17d1-68df-4815-90a1-9d3e58d8bbb1.png)

**Comment by traumschule** [comment]
@dmtrjsg is there something smart to tell about the forum?

**Comment by dmtrjsg** [comment]
Open discussion is open for every member to comment on, while closed would only be available for council members, white-listed members and creator of the proposal.

**Comment by traumschule** [comment]
Update PR for 1.

**Comment by polikosi** [comment]
tested on: https://pioneer-2-p25kt19dq-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json
![image](https://user-images.githubusercontent.com/80429191/215533349-1c7e7f98-190b-4ad1-8033-847d2965c82d.png)
