### ISSUE TITLE
[USERSNAP] Proposal does not display the necessary information

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3902]
**Taken at**: https://dao.joystream.org/#/proposals/preview/40
**Fields**:
- Houston, we have a problem.: Proposal does not display the necessary information
- Comment: Set Membership Lead Invitation Quota Proposal.
Proposal for 100 invites.  The proposal, for some unknown reason, does not display this information.
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a11b689a-885e-4ab1-8f94-11d7bbe9aa69-annotated_dd308136-a45c-40e6-93b3-1747a9b53a56.png?etag=74a86b4b02667dad57137cfe9b2e295c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a11b689a-885e-4ab1-8f94-11d7bbe9aa69-annotated_dd308136-a45c-40e6-93b3-1747a9b53a56.png?etag=74a86b4b02667dad57137cfe9b2e295c)*

**Browser**: Chrome 107 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[Open #346 in Usersnap](https://app.usersnap.com/l/feedback/894a3d1e-150e-45d1-836f-fe8f9a4fd9ec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
@dmtrjsg do we have a design for this proposal type or is this possibly something for @ninja-fire?

**Comment by dmtrjsg** [comment]
To me it seems all we need here is to add a widget with header "Proposed New Quota" and the number in the widget body. Can be done design-free imho.. If you disagree pls feel free to assign to him :)

**Comment by traumschule** [comment]
Related: #2037

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/preview/51
wss://34.230.5.182.nip.io/ws-rpc

✅ Widget added
⚠️ The header says "COUNT" instead of "Proposed New Quota"

<img width="1209" alt="Снимок экрана 2023-01-03 в 12 47 42" src="https://user-images.githubusercontent.com/46903215/210343150-212d80b0-93b1-42d1-83cf-14a33704df78.png">
