### ISSUE TITLE
[feature request] Forum Category Description is cut

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3904]
**Taken at**: https://dao.joystream.org/#/forum
**Fields**:
- Which feature are you missing?: Forum Category Description is cut
- What problem would that solve for you?: Please check Forum Category with long description. It is cut. There is no way you can read the whole description. I hope it can be improved by putting &#39;Show More&#39; like feature.
- Share your Github or Discord so we can get in touch: songoku1691

<img width="548" alt="Screenshot 2022-11-29 at 17 51 47" src="https://user-images.githubusercontent.com/93924525/204546821-96a7afed-e72d-42fa-a3f0-c555b2f24a04.png">

**Browser**: Chrome 107 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1707x811
**[Open #27 in Usersnap](https://app.usersnap.com/l/feedback/e572521b-5040-4717-935b-89903a3e12c2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@ninja-fire one for you mate, let's add category description to the top of the page> 

<img width="667" alt="Screenshot 2022-12-02 at 17 54 09" src="https://user-images.githubusercontent.com/93924525/205308470-cc61ee76-2ec3-411b-b99e-c2be2c183bc1.png">

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/forum/category/18
wss://34.230.5.182.nip.io/ws-rpc

✅ Description added on the category page
⚠️ The description displays only 350 symbols/2 rows rest is hidden via CSS

https://user-images.githubusercontent.com/46903215/210341269-49dfabe0-9c0e-40ec-964f-602de32d0c15.mov

**Comment by thesan** [comment]
@ivanturlakov thank you. Fortunately it doesn't stop the release since even in this state its an improvement on what was before.

**Comment by traumschule** [comment]
Following @thesan's judgement this looks done, although there should be a way to expand longer descriptions somehow, @ivanturlakov?

**Comment by ivanturlakov** [comment]
@traumschule https://github.com/Joystream/pioneer/pull/3925/files#r1067399021

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/category/18

<img width="1210" alt="Снимок экрана 2023-01-12 в 13 37 38" src="https://user-images.githubusercontent.com/46903215/212057096-102ef46a-d73c-4c8a-974c-c142f6313743.png">

**Comment by chrlschwb** [comment]
This issue seems to be solved and ready for production
