### ISSUE TITLE
[feature request] Feedback Test

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3905]
**Taken at**: https://dao.joystream.org/#/working-groups/my-applications
**Fields**:
- Which feature are you missing?: Feedback Test
- What problem would that solve for you?: Trying to see how the feedback button works
- Share your Github or Discord so we can get in touch: Chaos77#8632

**Browser**: Chrome 107 (Windows 10)
**Screen size**: 2560x1080
**[Open #28 in Usersnap](https://app.usersnap.com/l/feedback/1fb2fce4-413e-4655-9d46-51807779aa7d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by chrlschwb** [comment]
Feedback feature working as expected
