### ISSUE TITLE
Refetching subcategories cards comes with spinners on every block

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3915]
## Context

Refetching subcategories cards comes with spinners on every block
![Screenshot 2022-12-02 at 17.50.02.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/60baafd7-f85a-4e4f-a81c-55f20931cd73)

Main branch (Staging env + 34. network)

## Scope
- [ ] Refetching should happen in the background and spinner should not show

**Comment by traumschule** [comment]
unable to reproduce on `dev`

**Comment by traumschule** [comment]
For some reason this does not happen with category 1.

**Comment by traumschule** [comment]
To be tested with https://dao-git-fork-traumschule-fix-refetch-categories-3915-joystream.vercel.app/
