### ISSUE TITLE
[feature request] Moderator List in Pioneer Forum is not showing Moderators with Access per Categories

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3922]
**Taken at**: https://dao.joystream.org/#/proposals/current
**Fields**:
- Which feature are you missing?: Moderator List in Pioneer Forum is not showing Moderators with Access per Categories
- What problem would that solve for you?: There is this &#39;Moderators:&#39; part in Pioneer Forum. I though forum moderators with access in that category will show? But it seems not showing anyone. I reviewed rhodes testnet, it didn&#39;t show either. Please see picture on this discord link: https://discord.com/channels/811216481340751934/1035125625482129448/1048967788817043466
- Share your Github or Discord so we can get in touch: songoku#1691

**Browser**: Chrome 107 (Windows 10)
**Screen size**: 1366x768
**[Open #30 in Usersnap](https://app.usersnap.com/l/feedback/964bf223-75bc-4db3-a1f6-38f56b57cf0d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Verify that QN query correctly fetches moderators.

![empty-mods](https://user-images.githubusercontent.com/31551045/205896504-c2bfde5a-b9db-406d-b960-0b747e97ca50.png)

**Comment by traumschule** [comment]
also raised [here](https://github.com/Joystream/pioneer/issues/3153#issuecomment-1333839278). QN response is fine. @mkbeefcake please check this out how they get lost.
```
{"data":{"forumCategories":[{"id":"1","title":"Joystream General","description":"General Discussion that is anything else about Joystream Ecosystem that doesn't fit better in other categories.","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
**"moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[]},{"id":"3","title":"Gleev (Online Video Platform)","description":"Discussion about video contents","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
"**moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[]},{"id":"4","title":"Governance","description":"Post Council Reports, Pre-Proposals and other Governance matters in here","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
**"moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[{"id":"8","title":"Council Reports","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"9","title":"Pre-Proposals","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}}]},{"id":"5","title":"Working Groups","description":"Post WG Plans, Reports, Summaries and other WG specifics in here","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
**"moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[{"id":"10","title":"Storage","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"11","title":"Content","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"12","title":"Forum","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"13","title":"Builders","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"14","title":"Apps","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}}]}]}}
```

**Comment by mkbeefcake** [comment]
> also raised [here](https://github.com/Joystream/pioneer/issues/3153#issuecomment-1333839278). QN response is fine. @mkbeefcake please check this out how they get lost.
> 
> ```
> {"data":{"forumCategories":[{"id":"1","title":"Joystream General","description":"General Discussion that is anything else about Joystream Ecosystem that doesn't fit better in other categories.","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
> **"moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[]},{"id":"3","title":"Gleev (Online Video Platform)","description":"Discussion about video contents","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
> "**moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[]},{"id":"4","title":"Governance","description":"Post Council Reports, Pre-Proposals and other Governance matters in here","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
> **"moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[{"id":"8","title":"Council Reports","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"9","title":"Pre-Proposals","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}}]},{"id":"5","title":"Working Groups","description":"Post WG Plans, Reports, Summaries and other WG specifics in here","status":{"__typename":"CategoryStatusActive"},"__typename":"ForumCategory",
> **"moderators":[{"id":"forumWorkingGroup-1","membership":{"id":"4183","handle":"gru-dev-membership","__typename":"Membership"},"__typename":"Worker"},{"id":"forumWorkingGroup-2","membership":{"id":"1116","handle":"joychain","__typename":"Membership"},"__typename":"Worker"}]**,"forumcategoryparent":[{"id":"10","title":"Storage","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"11","title":"Content","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"12","title":"Forum","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"13","title":"Builders","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}},{"id":"14","title":"Apps","__typename":"ForumCategory","status":{"__typename":"CategoryStatusActive"}}]}]}}
> ```

yes, i will check it

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/category/1
wss://34.230.5.182.nip.io/ws-rpc

The list of moderators is displayed on the category page

<img width="345" alt="Снимок экрана 2023-01-13 в 15 31 20" src="https://user-images.githubusercontent.com/46903215/212331578-7f9222fc-cf0d-4001-8446-3b19008942e4.png">
<img width="385" alt="Снимок экрана 2023-01-13 в 15 31 31" src="https://user-images.githubusercontent.com/46903215/212331584-18d25ba6-82cf-4ffb-9136-2abbd41b7021.png">
