### ISSUE TITLE
the stake amount is not displayed

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#3924]
the stake amount in the "Announce candidacy" page is not displayed
![image](https://user-images.githubusercontent.com/80429191/205640438-96c40c3d-6fb0-4d69-bcf0-356991a90d99.png)

https://github.com/Joystream/pioneer/issues/3670#issuecomment-1335079475

**Comment by dmtrjsg** [comment]
@traumschule pls feel free to assign

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/election/past-elections
wss://34.230.5.182.nip.io/ws-rpc

<img width="1186" alt="Снимок экрана 2022-12-23 в 12 35 40" src="https://user-images.githubusercontent.com/46903215/209321525-ba48c9a8-2fcf-4c88-8dbc-dfdfb2b9fd96.png">
<img width="1182" alt="Снимок экрана 2022-12-23 в 12 36 49" src="https://user-images.githubusercontent.com/46903215/209321531-74bb8b07-b1bd-4cfb-9976-541c2d721b5e.png">
