### ISSUE TITLE
Thread Preview is broken

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3928]
![thread-preview](https://user-images.githubusercontent.com/31551045/205873821-283a7c94-a50e-459a-953f-18ff4031c7c3.png)

Possibly related: #3716 (changes to `PreviewPostModal.tsx`)

**Comment by dmtrjsg** [comment]
@traumschule pls feel free to assign

**Comment by traumschule** [comment]
Didn't fully grasp all changes in #3716 and #3833, please check. cc @WRadoslaw

**Comment by chrlschwb** [comment]
display preview when create new post in forum.#4077

**Comment by traumschule** [comment]
Sorry, fixed in #3928

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/39
wss://34.230.5.182.nip.io/ws-rpc

Works as expected

### Thread Preview
<img width="1261" alt="Снимок экрана 2023-01-27 в 13 18 34" src="https://user-images.githubusercontent.com/46903215/215074263-979f422e-99a9-43f3-9319-9a03a0991b81.png">

### Thread Created
<img width="1211" alt="Снимок экрана 2023-01-27 в 13 19 45" src="https://user-images.githubusercontent.com/46903215/215074270-687da24d-164a-4003-8445-d27d233c0e8c.png">
