### ISSUE TITLE
Currently stake is not displayed

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#3930]
⚠️I'm currently staking  5k tjoy for 1 roles it is not displaying
![image](https://user-images.githubusercontent.com/80429191/205724847-4ba5a3cf-45dc-49a5-9aa2-2b84bacbec0c.png)

https://github.com/Joystream/pioneer/issues/2539#issuecomment-1338033731

**Comment by dmtrjsg** [comment]
@traumschule pls feel free to assign

**Comment by mkbeefcake** [comment]
![image](https://user-images.githubusercontent.com/69617937/207618418-baedbe5c-9535-49ef-90b0-1ff0b8c6f10b.png)
I checked this issue in my end by using latest dev branch. As you can see in attached screenshot, The total stakes are showed in the screen. so I can guess that this already fixed before and we can close this issue.
