### ISSUE TITLE
Update text on the Insufficient Funds

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#3940]
## Scope
- [ ] Translation  added to the JSON is there, but maybe there's a typo..

## Context
I want to create a post with a zero account balance
![image](https://user-images.githubusercontent.com/80429191/206260675-a9e9df6a-edcf-4773-b14a-e1fca52aa658.png)

**Comment by traumschule** [comment]
Does this happen for both en / ru language settings? If not please test #3942

**Comment by polikosi** [comment]
When I change the language, nothing happens, the page doesn't translate.
![image](https://user-images.githubusercontent.com/80429191/206432260-52fe8329-c00e-4faf-99c4-b04f00eca5ab.png)

**Comment by traumschule** [comment]
Makes sense: #1984

**Comment by thesan** [comment]
@polikosi this should have been be fixed by #3958

**Comment by polikosi** [comment]
tested on: https://pioneer-2-git-mainnet-joystream.vercel.app/#/settings
wss://34.230.5.182.nip.io/ws-rpc
![image](https://user-images.githubusercontent.com/80429191/209336240-70248f74-8b6d-425c-bb5d-67deb706bfb9.png)
