### ISSUE TITLE
Runtime Diff Scope

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#395]
#  Background

The Pioneer designs were based on the state of the Olympia runtime as of +6 months ago, but in the mean time, we are making changes to the live testnet runtime, currently `Antioch` and soon `Sumer`, which we know will have to be absorbed into Olympia, and which will have an impact on how Pioneer can work. This issue is intended to track such issues which have yet to be remedied in the design and implementation of Pioneer.

# Issues

_Add issues as they occur_

1. The assets for memberships, council candidacies and any other metadata which depends on assets, should use the storage system, not HTTP URLs. This will require chaning the flows for how these are composed, and possibly also some upload management tooling, as well as storage space management. 
2. As an extension of 2 we will likely want to introduce the idea of attachments to proposals, blogs posts, etc. that are stored on the storage system.
3. **TBD:** Reward payouts for working groups are going to be pull based, not push based.

**Comment by jodator** [comment]
According to Joystream/joystream#2345 the current runtime does not support:

*   upcoming openings
*   Working group debt
*   Opening applicants limit
