### ISSUE TITLE
Forum render issues

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3950]
Possibly related to #3833
```
Warning: React does not recognize the `isArchived` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isarchived` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

React does not recognize the `archivedStyles` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `archivedstyles` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

React does not recognize the `ignoreHover` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ignorehover` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at a
    at CategoryCard
    at ForumMain
```

Wonder if these should be `isArchive` which is used all over the forum?
```
forum/components/ThreadCard/ThreadCard.tsx:      isArchived={thread.status.__typename === 'ThreadStatusRemoved'}
forum/components/ThreadCard/ThreadCard.tsx:const Box = styled(GhostRouterLink)<{ isArchived: boolean }>`
forum/components/ThreadCard/ThreadCard.tsx:  ${({ isArchived }) => (isArchived ? `background-color: ${Colors.Black[50]}` : '')};
forum/constant/styles.ts:export const categoriesColLayout = (isArchived: boolean) =>
forum/constant/styles.ts:  isArchived ? '356px 77px 276px 212px' : '356px 77px 172px 144px 104px'
mocks/data/seedForum.ts:  const isArchived = __typename === 'ThreadStatusLocked'
mocks/data/seedForum.ts:  const event = isArchived
```

**Comment by mkbeefcake** [comment]
> Possibly related to #3833
> 
> ```
> Warning: React does not recognize the `isArchived` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isarchived` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> 
> React does not recognize the `archivedStyles` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `archivedstyles` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> 
> React does not recognize the `ignoreHover` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ignorehover` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     at a
>     at CategoryCard
>     at ForumMain
> ```
> 
> Wonder if these should be `isArchive` which is used all over the forum?
> 
> ```
> forum/components/ThreadCard/ThreadCard.tsx:      isArchived={thread.status.__typename === 'ThreadStatusRemoved'}
> forum/components/ThreadCard/ThreadCard.tsx:const Box = styled(GhostRouterLink)<{ isArchived: boolean }>`
> forum/components/ThreadCard/ThreadCard.tsx:  ${({ isArchived }) => (isArchived ? `background-color: ${Colors.Black[50]}` : '')};
> forum/constant/styles.ts:export const categoriesColLayout = (isArchived: boolean) =>
> forum/constant/styles.ts:  isArchived ? '356px 77px 276px 212px' : '356px 77px 172px 144px 104px'
> mocks/data/seedForum.ts:  const isArchived = __typename === 'ThreadStatusLocked'
> mocks/data/seedForum.ts:  const event = isArchived
> ```

can you let me know where i can check these warnings? 
I was on this link ; http://localhost:8080/#/forum, but couldn't find out this warning messages on Chrome inspectors.
