### ISSUE TITLE
Hide Languages tab from Settings

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3955]
![Screenshot 2022-12-09 at 15.21.08.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/7bf35430-7bad-48c4-b68c-d6d86d1a00dc)

**Comment by traumschule** [comment]
![nolang](https://user-images.githubusercontent.com/31551045/206744762-374b269f-7e37-40f7-9a5f-d07cb427aff5.png)

**Comment by polikosi** [comment]
✅ tested on: https://dao-git-dev-joystream.vercel.app/#/settings 
wss://34.230.5.182.nip.io/ws-rpc
![image](https://user-images.githubusercontent.com/80429191/209331076-54245446-690e-4bfe-ad36-ff2bc0bceb1f.png)
