### ISSUE TITLE
Wrong "View opening" link on the proposal page

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#3957]
## Scope
- [x] Reverse the naming of the working group applications so that they can work with Orignal OpeningID from the QN

## Context

The problem that the URL (the opening ID should be app-1):https://pioneer-2-git-mainnet-joystream.vercel.app/#/working-groups/openings/app-1

And currently it has https://pioneer-2-git-mainnet-joystream.vercel.app/#/working-groups/openings/appWorkingGroup-1
___

Tested on https://pioneer-2-git-mainnet-joystream.vercel.app/

<img width="916" alt="Снимок экрана 2022-12-09 в 15 14 30" src="https://user-images.githubusercontent.com/46903215/206710511-2cd028a2-97eb-4381-bb2a-932ddc81e49f.png">

View opening link(didn't opens) https://pioneer-2-git-mainnet-joystream.vercel.app/#/working-groups/openings/appWorkingGroup-1

Opening page https://pioneer-2-git-mainnet-joystream.vercel.app/#/working-groups/openings/apps-1

**Comment by ivanturlakov** [comment]
same here
<img width="748" alt="Снимок экрана 2022-12-09 в 15 17 34" src="https://user-images.githubusercontent.com/46903215/206711057-50ef89c6-095b-403c-9957-1ec86b37a20b.png">

**Comment by dmtrjsg** [comment]
This issue will be handled in the JSG team by @thesan thank you for reporting @ivanturlakov  🙏

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-fix-apps-opening-links-joystream.vercel.app/#/working-groups/openings
Mainnet

Links works as expected
