### ISSUE TITLE
`About member` field on Edit Membership modal is empty

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#3973]
## Scope
- [ ] Fix the bug of showing empty description in the edit member modal

## Context

The `Profile` drawer shows `About` correctly (except for markdown #3867), however the input field on the modal is empty.

![edit-membership](https://user-images.githubusercontent.com/31551045/207151688-cdf746e6-9bcb-4ded-9707-c7ac8e26f7e8.png)

**Comment by dmtrjsg** [comment]
Confirmed, the description is empty in the Edit mode.

**Comment by ivanturlakov** [comment]
@traumschule Indeed, the field is empty in edit mode
