### ISSUE TITLE
Fix icon on the Polkadot Block Explorer Menu item

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3974]
## Context

Explorer menu tab needs to match the designs

Expected:
Default mode:
![Screenshot 2022-12-13 at 14.00.37.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/5b341ae2-093f-4c89-ad26-205dbba7b603)

On Hover:
![Screenshot 2022-12-13 at 14.00.46.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/0891fa65-0376-4ff8-ba40-aa72822abaee)

Currently:
![Screenshot 2022-12-13 at 13.08.43.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/713b6697-7076-4887-9e77-0a6ee197ef6f)

## Scope

- [ ] Update Icon styling to match Figma designs

[Link to Figma > ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=9977%3A407524&t=jcJpTbfVIxdkeUYw-1)

**Comment by traumschule** [comment]
Please feel free to assign someone else.

**Comment by vrrayz** [comment]
Please I'd like to take up this issue
