### ISSUE TITLE
Accept non-ASCII proposal titles

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#3977]
Once Joystream/joystream#4493 is merged #3476 (which forbids non ASCII characters in proposal title) should be reversed

## QA

Create and view a proposal with non ASCII characters in its title and description.
NB the network used should includes Joystream/joystream#4493 which is the case for Mainnet but AFAICS not the case for `34.230.5.182.nip.io`. Maybe a local network could be the best option.

**Comment by polikosi** [comment]
tested on: https://dao-git-staging-joystream.vercel.app/#/settings?network-config=https://54.205.24.16.nip.io/network/config.json
![image](https://user-images.githubusercontent.com/80429191/219328710-99b61797-e4ca-428b-87e5-86a4f94487f5.png)
