### ISSUE TITLE
Empty vesting balances bug

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4000]
This would happen only sometime.
The following description is copied from the PR #3815 (which include the [fix](https://github.com/Joystream/pioneer/pull/3815/commits/b7b0cb4ff9b1aa3ab51f800262fe268512711506)):

- Handles mysteriously empty BN values and adds a helper `sumBN` in `common/utils/bn` to sanely summarize a pair.
- Reverts the previous try.

## Rationale

Prior `My Accounts` was prone to `num.clone is not a function` on chain connection depending on balances input:
![numclone](https://user-images.githubusercontent.com/31551045/200411348-c3590378-8b9c-4c04-991a-98cbd28a743b.png)

## Triage

With extra logging on-chain balances appear with extra `#bitLength: 128` property for `locked`, `transferable` and `locked` suggesting a similar code path.
![](https://cdn.discordapp.com/attachments/1035125653722365993/1039225804980240496/addBalances.png)

**Comment by polikosi** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/
wss://34.230.5.182.nip.io/ws-rpc
![image](https://user-images.githubusercontent.com/80429191/212056085-aef2bd8b-8af8-4995-a01d-5aea720053e7.png)

**Comment by chrlschwb** [comment]
@polikosi, is this ready for production?
