### ISSUE TITLE
[USERSNAP] Incorrect balance display

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4003]
**Taken at**: https://pioneerapp.xyz/#/members
**Fields**:
- Houston, we have a problem.: Incorrect balance display
- Comment: Incorrect balance display
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4f1cc757-527d-465f-aec8-635be341b506-annotated_1b499044-3e35-4c9c-a724-81803622931b.png?etag=6bb7a907e89f142ed08f4a58cc120fc6)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4f1cc757-527d-465f-aec8-635be341b506-annotated_1b499044-3e35-4c9c-a724-81803622931b.png?etag=6bb7a907e89f142ed08f4a58cc120fc6)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[Open #352 in Usersnap](https://app.usersnap.com/l/feedback/18225830-566c-4622-96be-da4d2bf0ff44?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bedeho** [comment]
We looked into the blockchain side of things, and we found the following.

1. It is indeed correct that this account, as of now (block 369,644) , namely `j4Wi2vwD3LoCHA7PfJ3Lwj6E2AS6WQk3Cy2VBhuqYtVHARKKC`, has the following very large lock

```Rust
// balances.locks: Vec<PalletBalancesBalanceLock>
[
  {
    id: vesting 
    amount: 499,999,647,432,000,000,004,435,718,006,040
    reasons: All
  }
]
```

and it also has two vesting schedules in the vesting pallet

```
//vesting.vesting: Option<Vec<PalletVestingVestingInfo>>
[
  {
    locked: 4,600,000,000,000
    perBlock: 437,595
    startingBlock: 1
  }
  {
    locked: 499,999,999,999,999,999,999,990,000,000,000
    perBlock: 1,000,000,000,000,000,000,000
    startingBlock: 1
  }
]
```
