### ISSUE TITLE
Remove the "Member" role

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4004]
Currently all members get a member role badge (for being a member).
![image](https://user-images.githubusercontent.com/6571453/210519346-c0b6ba2a-e268-4b80-a715-51291adc157e.png)

This is a virtual role created by Pioneer (not returned by the QN) and should probably be removed.

**Comment by chrlschwb** [comment]
The member role is displayed when the user doesn't belong to any workgroup or the council.
Removing it wouldn't be too much of a problem.

**Comment by polikosi** [comment]
tested on: https://dao-git-dev-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json

![image](https://user-images.githubusercontent.com/80429191/219305573-2127679d-c033-4608-bac3-815f14283f33.png)
