### ISSUE TITLE
[USERSNAP] Incorrect display of comments

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4007]
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/24
**Fields**:
- Houston, we have a problem.: Incorrect display of comments
- Comment: Perhaps the comments should go from top to bottom by publication date?
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b57b6c99-13b0-4a46-8cce-453dc0aee183-annotated_fc8a8994-a6fa-425d-b3f4-5bbd2b5f7069.png?etag=bc86c16734204dc75e2e69940eadc7ad)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b57b6c99-13b0-4a46-8cce-453dc0aee183-annotated_fc8a8994-a6fa-425d-b3f4-5bbd2b5f7069.png?etag=bc86c16734204dc75e2e69940eadc7ad)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[Open #353 in Usersnap](https://app.usersnap.com/l/feedback/b0501df4-020c-4779-972d-eb6023e32f7a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Thanks for raising, looks like opinions differ.
[discussed](https://github.com/Joystream/pioneer/issues/3236#issuecomment-1346329412) and [reverted](https://github.com/Joystream/pioneer/pull/3969#issuecomment-1366401685)

**Comment by chrlschwb** [comment]
do we close this issue if it's reverted?
