### ISSUE TITLE
[USERSNAP] description for proposals is incorrect

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4010]
**Taken at**: https://pioneerapp.xyz/#/proposals/current
**Fields**:
- Houston, we have a problem.: description for proposals is incorrect
- Comment: &#34;Update Working Group Budget&#34;&#39;s description should say otherwise.
- Feedback: chrlschwb

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2f733287-e096-4721-93f5-db805f28d4f6-annotated_76dda3ff-63f9-4b61-a1ba-e573d8f1486b.png?etag=2e370aed3e5e65b3b7eb0437d308501d)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2f733287-e096-4721-93f5-db805f28d4f6-annotated_76dda3ff-63f9-4b61-a1ba-e573d8f1486b.png?etag=2e370aed3e5e65b3b7eb0437d308501d)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #356 in Usersnap](https://app.usersnap.com/l/feedback/d38cedba-1206-4d5d-8c3b-8528a7e6258e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Update description to: 

Positive budget update gets debited from the council budget and credited to the group budget, otherwise the reverse.
--

**Comment by polikosi** [comment]
tested on: https://dao-git-staging-joystream.vercel.app/#/settings
wss://34.230.5.182.nip.io/ws-rpc
![image](https://user-images.githubusercontent.com/80429191/219304209-087faf19-9dcb-42f9-8069-495d7829ca55.png)
