### ISSUE TITLE
Transaction Status Modal freezes at Finalizing transaction status

### ISSUE THREAD

**Issue by gyroflaw** [Joystream/pioneer#4020]
# Steps to reproduce

1. Create a new account.
2. Transfer balance to the newly created.
3. Confirm the transaction in your wallet.

> As can see below image the transaction confirmed and the new account balance is 20, 000 JOY

![image](https://user-images.githubusercontent.com/83718263/210801361-6473d8b7-9d00-4f2d-9d06-785247c8f7d7.png)

**Comment by traumschule** [comment]
@ivanturlakov can you please try to reproduce

**Comment by ivanturlakov** [comment]
Can’t reproduce it, works as expected for me

**Comment by traumschule** [comment]
@gyroflaw Please test if it still happens for you sometimes and reopen..
