### ISSUE TITLE
Winner voting stakes are recoverable

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4036]
I noticed vote stakes for last election's winners are recoverable during `Announcing` (now).
By recovering (`Recover Stake` on `Past Votes`) the `referendum.StakeReleased` event is submitted successfully and the vote lock disappears.

Is this possibly because another bigger (staking) lock exists?

**Comment by Songoku1691** [comment]
This is the handbook link explaining voting procedure (shared by Sir Advorn on discord):
https://handbook.joystream.org/system/council#voting

"...Importantly, a vote which was devoted to a losing candidate can be freed the moment the election cycle is over, while a vote which was devoted to a winner can only be freed ****after the **announcing**** period** of the next election begins. The idea behind this asymmetry is to more closely expose the winners to the consequences of their decision."

Based on quoted statement above, Pioneer is working fine.

We can argue though that there is no consequences in the winners decision. To support this last statement, we can change **after the announcing period** to **after the voting or revealing period**.

**Comment by traumschule** [comment]
> We can argue though that there is no consequences in the winners decision.

Exactly :) The expected behavior was that stakes stay locked until the term actually ends (after revealing of the following election) but that's a runtime decision, not for Pioneer.
