### ISSUE TITLE
[USERSNAP] Wrong values in "My Roles" of "Working Groups"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4040]
**Taken at**: https://pioneerapp.xyz/#/working-groups/my-roles
**Fields**:
- Houston, we have a problem.: Wrong values in &#34;My Roles&#34; of &#34;Working Groups&#34;
- Comment: see image
- Feedback: chrlschwb

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/596c2696-017e-40cb-ab16-e4f8e1d51d40-annotated_2e9d198f-8c01-420d-af0e-41892f0a425b.png?etag=35649b6cacc14c7f364691fbd97a13da)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/596c2696-017e-40cb-ab16-e4f8e1d51d40-annotated_2e9d198f-8c01-420d-af0e-41892f0a425b.png?etag=35649b6cacc14c7f364691fbd97a13da)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #366 in Usersnap](https://app.usersnap.com/l/feedback/25eae03e-ea19-4c4d-94ce-f98bbb7467d9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by chrlschwb** [comment]
duplicate issue
