### ISSUE TITLE
[USERSNAP] Wrong values in "My Roles" tab

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4041]
**Taken at**: https://pioneerapp.xyz/#/working-groups/my-roles
**Fields**:
- Houston, we have a problem.: Wrong values in &#34;My Roles&#34; tab
- Comment: see image

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/95b67b59-e69c-487d-aa29-32488b3e9d03-annotated_86abc92b-213f-4c2a-8273-4c7671892ccc.png?etag=e88c6e6d10b1da3541d78daa4f3e7177)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/95b67b59-e69c-487d-aa29-32488b3e9d03-annotated_86abc92b-213f-4c2a-8273-4c7671892ccc.png?etag=e88c6e6d10b1da3541d78daa4f3e7177)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #367 in Usersnap](https://app.usersnap.com/l/feedback/e5ee8320-7913-4aba-9fcc-44ae4e96b8fa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by thesan** [comment]
@traumschule please keep the `high-prio` labels, even after a PR has been opened. It makes it easier to prioritize issues during the review and QA phase too.

**Comment by polikosi** [comment]
tested on: https://dao-git-fork-chrlschwb-fix-4041-myrolesvalues-joystream.vercel.app/#/settings?network-config=https://54.205.24.16.nip.io/network/config.json

it's ok for me
![image](https://user-images.githubusercontent.com/80429191/220595096-96ae2f30-365c-4dfc-9e58-25c91bd5ebca.png)
