### ISSUE TITLE
[USERSNAP] Council: Councilor Reward is either wrong or unclear

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4043]
**Taken at**: https://pioneerapp.xyz/#/council
**Fields**:
- Houston, we have a problem.: Council: Councilor Reward is either wrong or unclear
- Comment: The current amount shown can easily be read as 1.16 $JOY / 14,400 blocks but it is really not clear and the maths don&#39;t seem to add up if I use the QN to find this information manually.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4f624cd3-1673-40ac-9c6a-c5d2e01ea018-annotated_dbe8836c-a103-4c55-9ab3-826d495d3983.png?etag=ce76c2c0f72626cdc517a04eba2cbcd6)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4f624cd3-1673-40ac-9c6a-c5d2e01ea018-annotated_dbe8836c-a103-4c55-9ab3-826d495d3983.png?etag=ce76c2c0f72626cdc517a04eba2cbcd6)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1396x722
**[Open #368 in Usersnap](https://app.usersnap.com/l/feedback/83f33c52-3a80-42c1-8da8-5810864cb705?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
It should be noted that other parts of Pioneer clearly state the amount is per block:
<img width="194" alt="image" src="https://user-images.githubusercontent.com/50830161/211301233-24bbd0c3-d7cf-4876-b332-d362ecfecaf2.png">

**Comment by bedeho** [comment]
Per block generally is going to be too low, if there is a natural period, we should use that.

**Comment by mochet** [comment]
I suggest the following. To be used universally (since there is an inconsistency between WGs and council payments):
* Payments (per block)
* Payment period (payment is made after period has passed)

**Comment by bedeho** [comment]
@DzhideX confirmed that the value here is actually _per block_, so the UX is just super confusing here.
Seems to me there are various possible fixes here, the Pioneer team should review and decide.

**Comment by bedeho** [comment]
Another important point was rased: is this per council member or across all in total?

**Comment by traumschule** [comment]
This is also interesting: #2378

**Comment by bedeho** [comment]
Here is another one: https://discord.com/channels/811216481340751934/943152333427191859/1062680004628074518

I think we just need to stop displaying rewards per block or per period actually. People care about real world time intervals, like _monthly_. so lets just pick that as the rate everywhere in Pioneer, then if someone hovers or whatever, they can get the price paramter value, which would be then per block, or per payout period etc.

**Comment by dmtrjsg** [comment]
## Scope
- [ ] Display rewards in JOY per month

use statistics component for that : https://pioneer-2-storybook-joystream.vercel.app/?path=/story/common-statistics--statistic

Pass reward per block and make calculation in the component. 

ON hover in tooltip show 

Reward per week
Reward per council period
Reward per block

Using this pattern:

<img width="295" alt="Screenshot 2023-01-12 at 12 10 56" src="https://user-images.githubusercontent.com/93924525/212063358-1adccdf0-9c3d-415b-9e46-b9d8e3a9f673.png">

**Comment by mochet** [comment]
> Here is another one: https://discord.com/channels/811216481340751934/943152333427191859/1062680004628074518
> 
> I think we just need to stop displaying rewards per block or per period actually. People care about real world time intervals, like _monthly_. so lets just pick that as the rate everywhere in Pioneer, then if someone hovers or whatever, they can get the price paramter value, which would be then per block, or per payout period etc.

totally agree only replying to say that showing rewards on a weekly basis seems more logical based on possible volatility of the token value as well as some roles, such as the council, not lasting for a month.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/council
Mainnet

<img width="1150" alt="Screenshot 2023-04-03 at 13 38 57" src="https://user-images.githubusercontent.com/46903215/229486511-77df991d-0df6-4d36-bc6e-9ebee0ea8b05.png">

**Comment by kdembler** [comment]
Let's show reward per week but for a single council members, not for the full council, that's very confusing.
