### ISSUE TITLE
[USERSNAP] Proposals: create proposal view wraps lines

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4044]
**Taken at**: https://pioneerapp.xyz/#/proposals/current
**Fields**:
- Houston, we have a problem.: Proposals: create proposal view wraps lines
- Comment: I usually use a desktop. I am now using a desktop and as such the value (i.e. 100% or 72,000 blocks) is wrapped under each line.

My laptop resolution is 1440x900 and it seems to be bad design that the last value (which is the most important, &#34;constitutionality&#34; is hidden under a scroll bar)

Anyway, I think that there is enough unused screenspace but showing &#34;constitutionality&#34; is of pivotal importance yet isn&#39;t shown.

(FOR REFERENCE: the screenshot attached shows the &#34;parameters window&#34; scrolled down, which doesn&#39;t show with a scroll bar, i.e. no new user would ever know to scroll down in the first place)
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3fbdce8-8251-42f9-9051-ffc2e2f1f45f-annotated_dc6e9772-9d27-4c7b-9534-e5d93ff93362.png?etag=95d81103c42cd61090f183643df1d722)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3fbdce8-8251-42f9-9051-ffc2e2f1f45f-annotated_dc6e9772-9d27-4c7b-9534-e5d93ff93362.png?etag=95d81103c42cd61090f183643df1d722)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1396x722
**[Open #369 in Usersnap](https://app.usersnap.com/l/feedback/ae60f9b0-3e42-4136-ae98-2d93d37aa160?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by polikosi** [comment]
Tested on: https://dao-git-dev-joystream.vercel.app/#/settings
wss://34.230.5.182.nip.io/ws-rpc
1440x900
![image](https://user-images.githubusercontent.com/80429191/215055571-6a4f3982-76cd-4800-9fdc-2bee401933c7.png)

**Comment by traumschule** [comment]
@polikosi There are two attached PR, please test this on both and tell which works better to use. It's would also be possible to merge both to move up constitutionality and reduce newlines:
#4073: https://dao-git-fork-traumschule-fix-proposal-paramete-5fe472-joystream.vercel.app/
#4050: https://dao-git-fork-traumschule-patch-5-joystream.vercel.app/

I checked myself and only the second seems to work well per default. In general it's fine at 80% zoom and mid-term it may be worth to re-consider adapting the design for smaller screens.
![up](https://user-images.githubusercontent.com/31551045/215340050-98e0d9e9-956d-4e84-835a-b8914f36e5d3.png)

**Comment by polikosi** [comment]
tested on: https://dao-git-fork-traumschule-patch-5-joystream.vercel.app/#/settings?network-config=https://34.230.5.182.nip.io/network/config.json
1440x900
![image](https://user-images.githubusercontent.com/80429191/215763332-55aa2a81-6975-4235-a78b-45bbc8df0ebd.png)

1366х768
![image](https://user-images.githubusercontent.com/80429191/215763917-216cfa07-6bca-4d79-b85b-1c8d4536051e.png)


1280х720
![image](https://user-images.githubusercontent.com/80429191/215763791-3b0038dd-fbea-4558-b3b9-716980de48ee.png)
