### ISSUE TITLE
[USERSNAP] Proposals: "Constants" language use

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4046]
**Taken at**: https://pioneerapp.xyz/#/proposals/current
**Fields**:
- Houston, we have a problem.: Proposals: &#34;Constants&#34; language use
- Comment: I believe that &#34;parameters&#34; would be a better term in this case.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/db872e80-d979-4d40-8b03-4f9615976d7a-annotated_5eb3162b-354b-4ccd-8862-05083b440043.png?etag=c51ab0bc99d7404cfd4002bec95773ac)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/db872e80-d979-4d40-8b03-4f9615976d7a-annotated_5eb3162b-354b-4ccd-8862-05083b440043.png?etag=c51ab0bc99d7404cfd4002bec95773ac)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1396x722
**[Open #371 in Usersnap](https://app.usersnap.com/l/feedback/50a1c7df-70ca-407b-a359-b85e5ff94f57?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/current

"Constants" updated to "Parameters"

<img width="1255" alt="Снимок экрана 2023-01-26 в 17 33 27" src="https://user-images.githubusercontent.com/46903215/214878112-f2a57242-a2be-4c76-a853-f86511a99f87.png">
