### ISSUE TITLE
[USERSNAP] Invite A Member Modal bug

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4053]
**Taken at**: https://pioneerapp.xyz/#/profile/memberships
**Fields**:
- Houston, we have a problem.: Invite A Member Modal bug
- Comment: ...
- Feedback: Ivan T#1098

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4b65d834-97d2-4946-8f67-b1bf290f9e97-annotated_62ea49ef-38f0-453c-86d6-a6f961b00fbf.png?etag=7b74448d11e67af1e2be25e26a3a36bf)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4b65d834-97d2-4946-8f67-b1bf290f9e97-annotated_62ea49ef-38f0-453c-86d6-a6f961b00fbf.png?etag=7b74448d11e67af1e2be25e26a3a36bf)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x789
**[Open #373 in Usersnap](https://app.usersnap.com/l/feedback/eef45810-e233-44d9-802e-9f05514fd180?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-staging-joystream.vercel.app/#/profile/memberships
wss://34.230.5.182.nip.io/ws-rpc

Modal fixed
Works as expected

<img width="923" alt="Снимок экрана 2023-02-15 в 17 32 28" src="https://user-images.githubusercontent.com/46903215/219075478-5b303c27-a989-4497-8d24-e2f0298eed9b.png">
<img width="1183" alt="Снимок экрана 2023-02-15 в 17 33 44" src="https://user-images.githubusercontent.com/46903215/219075494-e31df41a-e6ae-40e2-a41e-5ea11e959431.png">
<img width="1182" alt="Снимок экрана 2023-02-15 в 17 34 29" src="https://user-images.githubusercontent.com/46903215/219075500-89c0b10a-6dae-4125-8dd9-3124adc6e6cf.png">
