### ISSUE TITLE
Voting Modal Tooltip typo

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/pioneer#4054]
Line 4
<img width="493" alt="Снимок экрана 2023-01-10 в 13 44 04" src="https://user-images.githubusercontent.com/46903215/211545385-232f58c3-cad1-428e-85dc-2e2958b85123.png">

**Comment by chrlschwb** [comment]
related PR #4055 merged to dev branch

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/election
wss://34.230.5.182.nip.io/ws-rpc

<img width="487" alt="Снимок экрана 2023-01-11 в 18 12 33" src="https://user-images.githubusercontent.com/46903215/211858168-2ff6456d-d1db-4f03-a053-0be79688735b.png">

Link to https://handbook.joystream.org/system/council
