### ISSUE TITLE
Council: Applicants page doesn't directly show member handle

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4057]
The field currently shown for applicants can be user customized, meaning a user could impersonate another user or something like that. While a user can find the handle of the applicant by clicking on it, in the event an applicant doesn't put their username it can be confusing for people.

It would be better to directly show the handle of the applicant.

Example of this being an issue: 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/50830161/211718412-5559fb83-0ab9-4cfb-924a-8cfcbd1d7c8b.png">

Ideally it should say the user handle ("Isonar" in this case)

Overall it seems better to leave this field for users to customize as they wish to and not require them to have to consider putting their handle in their application title/description

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/election
wss://34.230.5.182.nip.io/ws-rpc

Tooltip added - "alice"

<img width="418" alt="Снимок экрана 2023-02-13 в 21 31 13" src="https://user-images.githubusercontent.com/46903215/218556309-1fd5f7e5-2c7e-40d5-bcd7-b865e45ed1c3.png">
