### ISSUE TITLE
DISPLAY PREVIEW button is not working in Forum

### ISSUE THREAD

**Issue by jen4ph** [Joystream/pioneer#4062]
I wanted to see the preview of what I was trying to post in Forum. When I pressed it, the whole screen was greyed-out and cannot see any preview. 

![Screen Shot 2023-01-11 at 11 20 28 PM](https://user-images.githubusercontent.com/96877192/211845633-d817fad6-5bc5-4779-a9db-7fd2cb36f899.png)

**Comment by traumschule** [comment]
another duplicate of #3928
