### ISSUE TITLE
Design Pioneer Backend

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4085]
# Background

https://github.com/Joystream/pioneer/issues/2880

# Proposal 

Its probably best to start by designing a database schema and API for this service before starting to build, and then thinking careful in terms of the Pioneer end-user experience how will it will work.

**Comment by thesan** [comment]
I'm thinking of starting by focusing on the email notification side. The only api required for that are the:

- Authentication
- Member creation/update

The backend will check the QN to decide who should get notified, and email the members. This process will be run regularly by a scheduler. Later the api should provide a list of notifications to authenticated members.

Here's the database schema I should get started with (I omitted the id on each table):

```mermaid
erDiagram
    Member ||--o{ AccessToken: accessTokens
    Member ||--o{ Subscription: subscriptions
    Member ||--o{ Notification: notifications

    Member {
        string handle
        string controllerAccount
        string email "(optional)"
        boolean isEmailVerified
        boolean isHandleVerified
    }

    AccessToken {
        Member member
        string token
        int createdAt
        int ttl
    }

    Subscription {
        Member member
        string notificationType
        string entityId "(optional)"
        boolean isEnabled
        boolean shouldNotifyByEmail
    }

    Notification {
        Member member
        string notificationType
        string entityId "(optional)"
        boolean isSent
        boolean isRead
    }

    QueryNodeConsumer {
        integer latestConsumedBlock
    }
```

**Comment by bedeho** [comment]
Looks like a great start!

- Its not 100% clear what all entities and fields mean, is this possible to add? Some of the feedback may reflect my misunderstanding on this.
- Where is it reflected what roles, posts, threads, proposals, etc. a given member should or should not be notified about? 
- Don't you need API for also managing what type of things a particular user cares about, not just the ones you list? and also where is it stored what types of notifications a given member desires to receive nor not. So for example, a user may want to know about forums threads where they are mentioned, but that information is different from the information about what actual threads they are mentioned, where when a new post is made they would therefore want to know. You could go even further and allow a member to opt out of further mentions on a particular thread, despite them being mentioned. How this representation is managed is a bit unclear.
- Should the type parameters used be strings? is that safe or best clear enough?
- Why is member handle relevant? and what does it mean that is is verified
- What does it mean that a notification is read? I guess this is related to another question: is the `Notifications` entity for a notifiction sent by email, or somehow in Pioneer, or both?
- When you say that a scheduler runs regularly, does that mean it asks the QN something like "Give me all events that exist since a given block and before a given block", and then it gets a chronological list of events back, which are then processed one by one, and for each there is some sort of udpating of the backend database state, and possibly also a message to some other service to send out an email? If so, how do you manage the issue of dealing with possible faults, where perhaps you get a certain way through processing, and something goes bad (power outage) which means not all fetched events have actually been processed for the prupose of notifications, and so when starting back up you may risk eitehr missing or republishng notifications for old events.

**Comment by thesan** [comment]
> - Its not 100% clear what all entities and fields mean, is this possible to add? Some of the feedback may reflect my misunderstanding on this.

Yes I'll detail this a bit more

> - Where is it reflected what roles, posts, threads, proposals, etc. a given member should or should not be notified about? 

This is what I meant the `Subscription` for. Its `isEnabled` field should reflect whether the member should get notified. Also on this entity as well as on the `Notification`: `notificationType` represent "type of event" e.g new proposal, mention,...

> - Don't you need API for also managing what type of things a particular user cares about, not just the ones you list? and also where is it stored what types of notifications a given member desires to receive nor not. So for example, a user may want to know about forums threads where they are mentioned, but that information is different from the information about what actual threads they are mentioned, where when a new post is made they would therefore want to know. You could go even further and allow a member to opt out of further mentions on a particular thread, despite them being mentioned. How this representation is managed is a bit unclear.

Yes I'm planning to use `notificationType` for this. This is why this won't simply be the event type but each event type should be mapped to one to many notification type.

> - Should the type parameters used be strings? is that safe or best clear enough?

No you're right this should be defined types, but I haven't listed them yet

> - Why is member handle relevant? and what does it mean that is is verified

It's not really. I think the member id should be kept here, and members should be referred to by there names. Also members don't get "verified" I just got confused by the registration process which I'm not fully cleared on yet.

> - What does it mean that a notification is read? I guess this is related to another question: is the `Notifications` entity for a notification sent by email, or somehow in Pioneer, or both?

Both. `isRead` will be for notification Pioneer later

> - When you say that a scheduler runs regularly, does that mean it asks the QN something like "Give me all events that exist since a given block and before a given block", and then it gets a chronological list of events back, which are then processed one by one, and for each there is some sort of udpating of the backend database state, and possibly also a message to some other service to send out an email? If so, how do you manage the issue of dealing with possible faults, where perhaps you get a certain way through processing, and something goes bad (power outage) which means not all fetched events have actually been processed for the prupose of notifications, and so when starting back up you may risk eitehr missing or republishng notifications for old events.

I originally thought of including the block height in the `Notification` for this (and I forgot it), but `eventId` from the QN makes more sense. Combined with the `notificationType` they should be unique per members.

**Comment by bedeho** [comment]
Thank you for replying. I'm still not understanding how the following two are represented
1. Bedeho in general wants to receive notifications from threads where he has been mentioned, but Theo does not.
2. Bedeho specifically _should_ receive notifications from thread=67 when someone makes a post to it, because he has specifically was mentioned in that thread, but Theo should not, despite being mentioned there also.
3. Bedeho should not receive notifications from thread=68 when someone makes a post, despite being mentioned there, becuase he has "unsubcribede" from this specific thread.
4. Bedeho should not receive notifications from thread=69 when someone makes a post, because noone has mentioned him there.

I guess one meta question here is how @mentino notifictions should work. Do they just result in you getting notified when someone does a mention, or does they result in all notifications for anything related to that thread, for example on the forums or in a proposal thread. It seems like if you made the thread, certainly you should be notified (unless you opt out) for any new post, even if noone has mentioned you. What if you just made a post, should you then get notified? I think so.

I suggested an initial set of 9, now extended to 11, notifications to support, but I did not describe actively opting out or opting in to certain types of notifications. Do you think your current model works with all of these?
https://github.com/Joystream/pioneer/issues/4086#issue-1533271225

**Comment by thesan** [comment]
>    1. Bedeho in general wants to receive notifications from threads where he has been mentioned, but Theo does not.

This one currently would be represented by the `Subscription`:
| member | Bedeho |
|----:|---|
| notificationType | FORUM_POST_MENTION |
| entityId | null |
| isEnabled | true |
| shouldNotifyByEmail | true |

and this one:
| member | Theo |
|----:|---|
| notificationType | FORUM_POST_MENTION |
| entityId | null |
| isEnabled | false |
| shouldNotifyByEmail | false |

>    2. Bedeho specifically _should_ receive notifications from thread=67 when someone makes a post to it, because he has specifically was mentioned in that thread, but Theo should not, despite being mentioned there also.

This one would be:
| member | Bedeho |
|----:|---|
| notificationType | FORUM_POST_IN_WATCHED_THREAD |
| entityId | 67 |
| isEnabled | true |
| shouldNotifyByEmail | true |

>    3. Bedeho should not receive notifications from thread=68 when someone makes a post, despite being mentioned there, becuase he has "unsubcribede" from this specific thread.

This one is not supported by the current model I'll think more about it.

>    4. Bedeho should not receive notifications from thread=69 when someone makes a post, because noone has mentioned him there.

This is the default (if no `FORUM_POST_IN_WATCHED_THREAD` subscription was defined for Bedeho on post thread 69).

> I guess one meta question here is how @mentino notifictions should work. Do they just result in you getting notified when someone does a mention, or does they result in all notifications for anything related to that thread, for example on the forums or in a proposal thread. It seems like if you made the thread, certainly you should be notified (unless you opt out) for any new post, even if noone has mentioned you. What if you just made a post, should you then get notified? I think so.

I was thinking people could be notified when mentioned in a post, but as long as they don't reply they wouldn't get notified on every new post of the thread. But people who take part on thread (created it or replied) could get mentioned by default on every new post.

> I suggested an initial set of 9, now extended to 11, notifications to support, but I did not describe actively opting out or opting in to certain types of notifications. Do you think your current model works with all of these? [#4086 (comment)](https://github.com/Joystream/pioneer/issues/4086#issue-1533271225)

They are except for:
- (3): I'm not clear on this one.
- (4) is not currently supported. I guess it could be handled by adding a watch account table. But I'm thinking of starting with just an opt-in subscription for on the revealing stage.
