### ISSUE TITLE
[USERSNAP] Past Elections: Total staked value does not include vote stakes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4090]
**Taken at**: https://pioneerapp.xyz/#/election/past-elections
**Fields**:
- Houston, we have a problem.: Past Elections: Total staked value does not include vote stakes
- Comment: This value seems to only show the amount staked by the actual candidates which is quite a bit lower than what the total value staked by the platform users is when an election happens. By my count more than 70m $JOY was staked for this election.

Suggest to have 2 columns:
- Candidate stake amount
- Voter stake amount

There is then the question of whether this should only include successful candidates or ALL voter/applicant stake for the election in question
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8b765927-f4ba-4b96-a8a4-436e2efbca4b-annotated_08dd60ef-f081-4b52-b431-d5faa9d5a91d.png?etag=119d061a91dd7454bc22bd3835fb7e5b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8b765927-f4ba-4b96-a8a4-436e2efbca4b-annotated_08dd60ef-f081-4b52-b431-d5faa9d5a91d.png?etag=119d061a91dd7454bc22bd3835fb7e5b)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x761
**[Open #377 in Usersnap](https://app.usersnap.com/l/feedback/a12d3655-c3c5-4ba0-aecb-fc312efbe7db?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
I'd say including all would be better 👍

**Comment by polikosi** [comment]
tested on: https://pioneer-2-git-fork-goldwolf115-fix-past-elections-2-joystream.vercel.app/#/settings?network-config= https://3.73.121.180.nip.io/network/config.json

It looks good. 
✅ Added 2 columns:

Candidate stake amount
Voter stake amount

✅ Self stake - 200k
Voter 1 - 19.5kk
voter 2 - 90k
![image](https://github.com/Joystream/pioneer/assets/80429191/daac974f-1598-4e78-b211-07118a07fda0)

**Comment by chrlschwb** [comment]
release:1.9.0
