### ISSUE TITLE
Conduct `Ephesus` QA plan

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4099]
# Bacground

Basically do what was planned #4098

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203775713295855) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
duplicated of #4098

**Comment by bedeho** [comment]
This is not a duplicate: _making a plan_ is very different from _executing_ on the content of that plan, they are distinct, and each can require considerable amount of time and coordination.
