### ISSUE TITLE
[feature request] web3

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4101]
**Taken at**: https://pioneerapp.xyz/#/forum
**Fields**:
- Which feature are you missing?: web3
- What problem would that solve for you?: everything is fine. Let&#39;s get high

**Browser**: Yandex.Browser 22 (Windows 10)
**Screen size**: 1920x1080
**[Open #35 in Usersnap](https://app.usersnap.com/l/feedback/1c45786f-2b03-4355-8ef4-9ef80fd53357?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
yo
