### ISSUE TITLE
There is no any data in the category

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4102]
## Context

Sometimes the forum shows `There is no any data in the category` while loading which is wrong.
This is probably due to empty data being returned when the QN are unstable. In which case this is related to: #4108 and #4173.

## Scope

- [x] Fix the copy: `There is no any data in the category` → `There is no data in the category`.
- [x] Differentiate whether the data are empty due to the category being empty or due to a QN malfunction.

IMO debugging these kind of issues is easier with a local node (see: https://github.com/Joystream/pioneer/blob/dev/docs/testenv.md)

**Comment by dmtrjsg** [comment]
@traumschule can you pls add a screenshot?

**Comment by traumschule** [comment]
Disappears on itself just confusing.
![nodata](https://user-images.githubusercontent.com/31551045/215261580-1e380911-7487-4fdb-a8ce-979b090f4d71.png)

**Comment by dmtrjsg** [comment]
@traumschule sorry, what do you mean? How to replicate this screen? ( I could not)

<img width="1392" alt="Screenshot 2023-01-30 at 09 39 04" src="https://user-images.githubusercontent.com/93924525/215441445-58b62ff7-bbb0-44a0-9984-34c04c2c0ed2.png">

**Comment by sunny0714** [comment]
@chrlschwb I would like to work on this issue.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/forum/category/16
Mainnet

The message can be seen when you move from the main category to a subcategory that has threads

https://user-images.githubusercontent.com/46903215/229498114-acacbb33-56c8-4035-ad7f-0f438362a468.mov

**Comment by dmtrjsg** [comment]
@sunny0714 let's just remove this message, and show loading spinner instead> 

https://pioneer-2-storybook-git-carthage-joystream.vercel.app/?path=/story/workinggroup-loadingopenings--loading

**Comment by thesan** [comment]
I detailed the scope in the issue description :point_up:

**Comment by traumschule** [comment]
> Differentiate whether the data are empty due to the category being empty or due to a QN malfunction.

or due to loading. Wasn't aware that this happened because of empty QN result.

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/category/16
Mainnet

<img width="1440" alt="Screenshot 2023-05-01 at 16 11 38" src="https://user-images.githubusercontent.com/46903215/235456090-23420a5e-8b47-4851-978e-691e449de473.png">
