### ISSUE TITLE
Forum returns 404 for correct links

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4108]
Sometimes this happens and one has to open the same link again which then works.

STR
1. open a forum thread
2. edit the thread number in the address bar
3. hit enter
=> 404

**Comment by dmtrjsg** [comment]
Not enough info to triage..

**Comment by traumschule** [comment]
updated description, please try these steps to reproduce.

**Comment by dmtrjsg** [comment]
Just checked and it seems for existing threads it works correclty. 

Tried with 93,94,95. 

for non-existent threads it correctly shows 404. .

@traumschule Which ones dd you struggle with?|

**Comment by traumschule** [comment]
It's any thread. To reiterate the steps:
1. CTRL + l "https://pioneerapp.xyz/#/forum/thread/12" => Found
2. CTRL + l "https://pioneerapp.xyz/#/forum/thread/13" => Not found
2. CTRL + l "https://pioneerapp.xyz/#/forum/thread/13" => Found

Routing fails when the thread page / component is active and only works when jumping from another page/component like categories.

**Comment by traumschule** [comment]
Another way to reproduce this is to [open this post](https://pioneerapp.xyz/#/forum/thread/15?post=475) and click on any thread link.

**Comment by thesan** [comment]
Could be related to #4173

**Comment by traumschule** [comment]
> i wonder if we want a 404 page instead of routing back to /proposals for example?

**Comment by traumschule** [comment]
The problem seems to be that after changing the thread ID in the address bar `isLoading` stays false and `thread` is empty while the new one is being loaded. When the address changes, `isLoading` needs to be set `false`.
```
  useEffect(() => {
    if (!isLoading && !thread) {
      history.replace('/404')
    }
  }, [isLoading, thread])
```
in [`ForumThread.tsx`](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/app/pages/Forum/ForumThread.tsx#L62). Does this make sense?

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/12

Forum returns related pages for correct links
