### ISSUE TITLE
Multiple constitutionality proposals display upd

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4111]
## Context

At present proposals that need to undergo multiple constitutionality periods are displayed with multiple tabs. The future rounds of voting are disabled, while the last round is not represented in the tab. 

Here's an example: 
![Screenshot 2023-01-23 at 11.24.49.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/df639806-0cfd-44bc-9ca5-ba071dbe02a0)

## Scope
- [ ] Display all voting periods in tabs all the time with future ones disabled.
In the example provided above, 3 rounds exists, so all of them need to be shown in tabs. 1/3; 2/3; 3/3

- [ ] Add tooltip on hover to the disabled tabs:
Tooltip copy: "This proposal must undergo the voting of multiple consequent councils. The result of each council vote will be displayed in the separate tabs. For the proposal to be approved, each of the councils must approve it." 

- [ ] Add info banner to the active / past rounds of voting.
"The number of councils in that must approve the proposal in a row before it has its intended effect is more than 1. The overall execution of proposal will be triggered after the last council completes the voting. Outcomes of each council voting is displayed in a separate tab."

**Comment by chrlschwb** [comment]
Looks like this issue should be put on hold until there is another proposal with multiple constitutionalities.
I tried to create a test proposal for this purpose but encountered with a new issue.
#4202

**Comment by dmtrjsg** [comment]
This issue should be done together with
- #4201 

Before releasing

cc @chrlschwb

**Comment by dmtrjsg** [comment]
As discussed on the call, let's try and rename tab labels from 1/4; 2/4.. to Round 1, Round 2, Round 3, Round 4... For multiple constitutionality proposals.

@thesan fyi
