### ISSUE TITLE
Unabridged thread view

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4113]
The paginated view for threads stems mostly from the devops perspective to limit load on QN. For CM or anyone who wants to work with the forum and answer previous posts the paginated view is an unnecessary limitation. Two easy option to improve productivity:
- add toggle to see all posts in a thread (even if the page may get long)
- option to collapse/hide certain (from user perspective) less interesting posts (for example show decent "1 post hidden" line instead)
- option to save this thread specific setting in local storage for next visit

**Comment by dmtrjsg** [comment]
I can see how that can be annoying when you have 11 or 13 posts, but I don't think any of hte solutions added here are really viable. We could probably extend pagination to 20 per page, but let's consider if that is worth solving at this time while we have so many other things in-flight?

Also if you try to reply to someone you see their message in the preview, so we cannot get it where the problem really is with the replies specifically: 
<img width="889" alt="Screenshot 2023-01-27 at 12 33 37" src="https://user-images.githubusercontent.com/93924525/215088151-8f87216d-88b9-4a71-a222-98842f963c48.png">

**Comment by traumschule** [comment]
Ok. Traditional fora offer a way to select number of posts per page as another/simpler way to improve UX - up to you.
