### ISSUE TITLE
Connect Pioneer membership with social media like telegram or discord (for roles)

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#4115]
Suggestion: I would like to give a non-priority suggestion for Pioneer. I notice, roles in telegram group are manually assigned. I hope it could be automatically assigned.

Solution: When you create/edit membership n Pioneer, there is column to fill-up your social media. Maybe we can create code or bot to automatically give roles in telegram like admins (for HR) or Founding Member tags. This will prevent scam accounts because genuine profiles will have tags.

Thank you

**Comment by traumschule** [comment]
It could make sense to think this together with Joystream/joystream#4566 and #2880.

**Comment by dmtrjsg** [comment]
@Songoku1691 are you saying you want the Discord bot to check pioneer roles and assign them in discord or vice-versa?  

For the former we don't need pioneer at all. 

If the latter, I am not sure if that can get addressed as this level of automation requires external integration, maybe can be partially doable with the proper backend, but honestly the cost of implementation vs the benefit it brings is unlikely to get this prioritised in the coming future.

QueryNode would be the better option to look for the members status in pioneer..
