### ISSUE TITLE
Unhandled proposal creation error due to `ConflictingStakes`

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4118]
Expected: When proposal creation fails it is possible to return to the first step and choose another stake.

Observed
1. Fill `Create new proposal` modal. proceed to signing
2. Sign step takes a while to unlock => start working in another Pioneer tab and create a proposal with the same stake
3. After some minutes the first tab activates "Sign" button => Click and submit
4. Tx fails and "Previous Step" button has no effect.

![](https://cdn.discordapp.com/attachments/1035125691034910800/1067048624246226994/failed.png)

**Comment by dmtrjsg** [comment]
>start working in another Pioneer tab and create a proposal with the same stake

I don't think we can support handling this in a better way than it is done now 😬

**Comment by traumschule** [comment]
Created a new issue because it reappeared: #4188
