### ISSUE TITLE
[USERSNAP] wrong values in Council / Past Councils

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4121]
**Taken at**: https://pioneerapp.xyz/#/council/past-councils
**Fields**:
- Houston, we have a problem.: wrong values in Council / Past Councils
- Comment: The highlighted values seem incorrect

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ed0e8325-2ec2-42be-99dd-20ad2f3a5c9c-annotated_8d613170-1350-4c2d-9bd6-a8fb184b3695.png?etag=577bd3c43f507e5b3bc34af7b992508c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ed0e8325-2ec2-42be-99dd-20ad2f3a5c9c-annotated_8d613170-1350-4c2d-9bd6-a8fb184b3695.png?etag=577bd3c43f507e5b3bc34af7b992508c)*

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #382 in Usersnap](https://app.usersnap.com/l/feedback/de883db5-a428-40e2-9fd2-eedfd3920e5f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
high chance for this to be duplicate..

**Comment by traumschule** [comment]
It's related but instead of #3225 concerns the past councils overview page.

**Comment by mkbeefcake** [comment]
![image](https://github.com/Joystream/pioneer/assets/69617937/35fdb223-a409-4330-8753-54c34588fb62)
![image](https://github.com/Joystream/pioneer/assets/69617937/181d2ebf-ef5a-4c5a-b49c-7280d9d845c3)
![image](https://github.com/Joystream/pioneer/assets/69617937/efcb2e4e-0266-4c1c-ae7d-79e45f87d3ed)
Hello
@thesan 
While working on this issue, I checked Joystream's GraphQL server and Pioneer source code and GraphQL queries from Pioneer website. 
As you can check in attached images, in query-node code, there is no linked fields for destinationsList to details field.  and but pioneer frontend indicates the destinationsList field, so it is always NULL. 
I hope you confirm this

**Comment by chrlschwb** [comment]
"total spent" column should include the total of councilor reward + WG budget updates + funding proposals + channel payout rewards
