### ISSUE TITLE
Revealing vote tooltip is a bit unclear

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4153]
```
Vote for your own membership with the same account as used for council candidacy creation counts towards the progress. Please note, this will in a voting lock applied to this account, which may only be withdrawn in the end of the council period if you win the election and released immediately if your candidacy gets outvoted by others. Voting locks are non-rivalrous.
```
This is a bit unclear: 'counts towards the progress'

_Originally posted by @traumschule in https://github.com/Joystream/pioneer/pull/4047#discussion_r1065229003_

**Comment by dmtrjsg** [comment]
New copy is provided by community in the linked PR.

**Comment by traumschule** [comment]
https://dao-git-fork-traumschule-patch-9-joystream.vercel.app/
"Total stake of revealed votes from any of your accounts. Vote locks are non-rivalrous and may be recovered during the following announcing period in case the candidate got elected or are released immediately after revealing ends."

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-staging-joystream.vercel.app/#/election
wss://54.205.24.16.nip.io/ws-rpc

Tooltip updated: "Total stake of revealed votes from any of your accounts. Vote locks are non-rivalrous and may be recovered during the following announcing period in case the candidate got elected or are released immediately after revealing ends."

<img width="1201" alt="Снимок экрана 2023-02-22 в 16 21 06" src="https://user-images.githubusercontent.com/46903215/220649513-acfd734f-f668-485d-9013-1b9714cc2709.png">
