### ISSUE TITLE
Remove Past Election Blocktime tooltip

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4156]
Follow-up to #3808 (#3168):
> About the BlockInfo it's good to show "Block 1000" instead of "1000 Block". But since the network information is out of date (it should have been removed on the QN) I don't think there's a point having a tooltip here. This component should stick to the design. In addition lessInfo should be removed from the code. Finally maybe maybe the Link component could have a click handler with event.stopPropagation() but that's not very urgent (even now it's possible to right click "Open link in New Tab" to open the link.

**Comment by dmtrjsg** [comment]
Scope: 

1. Remove block tooltips
<img width="334" alt="Screenshot 2023-02-10 at 15 40 04" src="https://user-images.githubusercontent.com/93924525/218084048-4cd8c086-8f64-46f4-b89d-2c8ca6d54a9d.png">

<img width="292" alt="Screenshot 2023-02-10 at 15 40 14" src="https://user-images.githubusercontent.com/93924525/218084059-560233d7-8dbf-4078-970f-67fa3dea172e.png">

2. Upon hover show block/date as clickable
3. Upon click open block explorer in the new tab

**Comment by chrlschwb** [comment]
release:1.9.0
