### ISSUE TITLE
Forum Moderation not working

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#4161]
Hello Guys:

Yesterday, I created several forum threads to map the discord bots connection to forum categories. After mapping, I would like to delete the threads. However, I couldn't moderate the threads via CLI and even manually on forum. Please see this forum thread with photos and link to discord discussion: https://pioneerapp.xyz/#/forum/thread/160

Thanks

**Comment by traumschule** [comment]
@mochet please help to reproduce and describe steps.

**Comment by traumschule** [comment]
see https://github.com/Joystream/pioneer/issues/4249#issuecomment-1595819822
