### ISSUE TITLE
[USERSNAP] Forums: Clicking a tagger username just goes to member directory, not to the user's individual profile

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4169]
**Taken at**: https://pioneerapp.xyz/#/forum/thread/70?post=282
**Fields**:
- Houston, we have a problem.: Forums: Clicking a tagger username just goes to member directory, not to the user&#39;s individual profile
- Comment: SSIA
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9f7f2185-715b-430c-b8b9-1679efdb2a2a-annotated_4dbab806-561c-4a43-9846-71cc5d716b39.png?etag=8842392e67dc3a4635ef69824c8d35e5)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9f7f2185-715b-430c-b8b9-1679efdb2a2a-annotated_4dbab806-561c-4a43-9846-71cc5d716b39.png?etag=8842392e67dc3a4635ef69824c8d35e5)*

**Browser**: Chrome 109 (macOS Catalina)
**Screen size**: 1680x1050
**Browser size**: 1575x883
**[Open #388 in Usersnap](https://app.usersnap.com/l/feedback/d8603626-809d-4c65-95a0-6cbeaf433a14?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Link to individual profile -> open membership details in the side drawer
Link to proposal -> open proposal preview page in separate tab

**Comment by mochet** [comment]
This behavior has been changed so it does go to their profile. Closing.
