### ISSUE TITLE
[feature request] хороший проект

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4199]
**Taken at**: https://pioneerapp.xyz/#/forum/my-threads
**Fields**:
- Which feature are you missing?: хороший проект
- What problem would that solve for you?: Потому что этот проект принес общий объем средств примерно в 13 миллионов долларов при оценке в 60 миллионов долларов от более чем 30 инвесторов, среди которых Digital Currency Group (посевной раунд), Hypersphere, DefiAlliance и D1 Ventures.

Это потрясающе. Если это нехороший проект, у них нет причин вкладывать в него деньги.
- Share your Github or Discord so we can get in touch: andrey_versus#9191

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1366x768
**[Open #49 in Usersnap](https://app.usersnap.com/l/feedback/ced10fb8-1172-4992-bba1-57c27f94bf83?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
🤩 💯   totally agreed

**Comment by traumschule** [comment]
thanks for the feedback :wink: 
> Good project
> Because this project brought a total amount of funds about $ 13 million when estimated at 60 million dollars from more than $ 30, including Digital Currency Group (sowing round), Hypersphere, Defialance and D1 Ventures.
> It's amazing. If this is a bad project, they have no reason to invest in it.
