### ISSUE TITLE
Multiple Constitutionality Proposal Error in Council Display

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/pioneer#4201]
The original comment can be found here
https://github.com/Joystream/pioneer/pull/4119#issuecomment-1436096153

<img width="281" alt="r" src="https://user-images.githubusercontent.com/101491745/221137268-144b26b1-0a11-44cb-9c84-063f35439a8a.png">

**Comment by dmtrjsg** [comment]
We need to show  correct voters (correct council corresponding the the council term when the vote happened)  on each individual tab as we are managing multiple rounds for proposals via tabs.
