### ISSUE TITLE
Runtime Upgrade not possible via Pioneer Proposal

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/pioneer#4202]
I was going to create a runtime proposal in order to test issue #4111
But I couldn't get through with the proposal.

![image](https://user-images.githubusercontent.com/101491745/221139764-39507d64-8587-4624-8acd-48a44f224e0f.png)

**Comment by traumschule** [comment]
Did you upload a valid wasm?

**Comment by dmtrjsg** [comment]
There's a known bug for it associated with upgrade of substrate @mnaamani is dealing with this already but thank you for raising! 

Linking the issue here and closing this one.

- #4122
