### ISSUE TITLE
[feature request] Emoji

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4209]
**Taken at**: https://pioneerapp.xyz/#/forum
**Fields**:
- Which feature are you missing?: Emoji
- What problem would that solve for you?: It would be good to have Emoji&#39;s to express feelings and impression without writing.

**Browser**: Chrome 110 (Windows 10)
**Screen size**: 1920x1080
**[Open #50 in Usersnap](https://app.usersnap.com/l/feedback/27ab09ef-2b13-4179-a9fe-9fc1fa62ba65?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Scope: add emojis as special character as we don't need a separate plugin for it.

Here's the documentation for it: https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/1?post=7
wss://54.205.24.16.nip.io/ws-rpc

<img width="1065" alt="Screenshot 2023-05-01 at 15 56 21" src="https://user-images.githubusercontent.com/46903215/235454860-3b64242e-567b-4b01-b0df-3921ee416c36.png">
<img width="558" alt="Screenshot 2023-05-01 at 15 58 48" src="https://user-images.githubusercontent.com/46903215/235454871-6daf17df-d7c0-4ec5-a4bd-f0b2b28382d7.png">
