### ISSUE TITLE
[USERSNAP] Page crash

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4216]
**Taken at**: https://pioneerapp.xyz/#/working-groups/builders
**Fields**:
- Houston, we have a problem.: Page crash
- Comment: When I go to the history of the Builders WG openings the page crashes. White screen
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0d949575-1036-47b2-9928-6e581791af9b-annotated_fb50e55a-28c6-4bdc-946a-51a86428820f.png?etag=44348f26b8a36a2dc6cdbd0a8ecc2e64)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0d949575-1036-47b2-9928-6e581791af9b-annotated_fb50e55a-28c6-4bdc-946a-51a86428820f.png?etag=44348f26b8a36a2dc6cdbd0a8ecc2e64)*

**Browser**: Chrome 110 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[Open #399 in Usersnap](https://app.usersnap.com/l/feedback/524f6563-7c6f-4df1-949d-d817e09560ba?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Validated, related to 
#4034 

Needs fixing @chrlschwb please feel free to assign

**Comment by oleksanderkorn** [comment]
`data.workerRewardAmountUpdatedEvents` seems to be issing in the GraphQL Response:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/9252017/223544626-ee7de414-7aad-49be-97b6-3669ac8a6f45.png">
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/9252017/223544851-e081387b-5568-4b9d-a9b8-7d104753e70a.png">

**Comment by oleksanderkorn** [comment]
related issue:
https://github.com/Joystream/pioneer/pull/4190

**Comment by oleksanderkorn** [comment]
Found the commit with some related fixes which should help:
https://github.com/IlyaSmiyukha/pioneer/commit/9030bbdc8833d34f6579b5dfff5ac97c9b048b62

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/working-groups/builders
Mainnet

Page loads with no errors

<img width="1440" alt="Screenshot 2023-03-31 at 18 55 45" src="https://user-images.githubusercontent.com/46903215/229170774-9daf69a4-554f-4d99-8a0f-8930f46479f6.png">
