### ISSUE TITLE
Council payout does not display in Atlas Channel Payments Dashboard

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4222]
Proposal: https://dao-git-ephesus-joystream.vercel.app/#/proposals/preview/19

![Screenshot 2023-03-10 at 20.46.00.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/bcc1aadd-9638-44f0-a858-5fc36ce0550a)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1204155702599804) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment]
The link returns 404. Is this an atlas issue?

**Comment by dmtrjsg** [comment]
@traumschule no this is due to error in QN but applies to Payout PRoposal @thesan will work on this later today..

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/atlas #3929](https://github.com/Joystream/atlas/issues/3929) via [**Zenhub**](https://www.zenhub.com/)
