### ISSUE TITLE
[USERSNAP] Link button on proposals has absurd placement

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4246]
**Taken at**: https://pioneerapp.xyz/#/proposals/current
**Fields**:
- Houston, we have a problem.: Link button on proposals has absurd placement
- Comment: I&#39;m not sure its even needed, someone can just open the proposal and copy the URL, either way, placement now is clearly a bug.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8349ca13-f29e-407c-9363-ce19f0bfb3f9-annotated_06d976ca-0cfa-4d27-8407-9ea27ab02a35.png?etag=6489166ad46cd041797e5a5c152d149d)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8349ca13-f29e-407c-9363-ce19f0bfb3f9-annotated_06d976ca-0cfa-4d27-8407-9ea27ab02a35.png?etag=6489166ad46cd041797e5a5c152d149d)*

**Browser**: Firefox 110 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1460x1071
**[Open #401 in Usersnap](https://app.usersnap.com/l/feedback/c47d1599-dede-4549-a514-0233283b0b89?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
I suggest to remove this button: 
<img width="1083" alt="Screenshot 2023-03-20 at 19 04 54" src="https://user-images.githubusercontent.com/93924525/226381779-f976f6d2-8bea-46ab-a3ef-617b3332b2a7.png">

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/current
Mainnet

CopyButton removed

<img width="1145" alt="Screenshot 2023-03-31 at 18 43 57" src="https://user-images.githubusercontent.com/46903215/229168901-ed3dd921-50ea-4352-96b8-3d5ab152b69e.png">
