### ISSUE TITLE
[USERSNAP] Forum Post Delete Problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4249]
**Taken at**: https://pioneerapp.xyz/#/forum/thread/303
**Fields**:
- Houston, we have a problem.: Forum Post Delete Problem
- Comment: Please see details in Forum thread: https://pioneerapp.xyz/#/forum/thread/303
- Feedback: songoku#1691

**Browser**: Chrome 111 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1821x864
**[Open #402 in Usersnap](https://app.usersnap.com/l/feedback/15d917dd-1fe0-493b-9252-54c19bac6dab?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Relates to
- https://github.com/Joystream/pioneer/issues/4161

Should be fixed together

**Comment by traumschule** [comment]
According to our research it is not possible to delete posts that aren't marked editable by the author via state bloat bond. Non-editable posts or threads cannot be deleted.

**Comment by mochet** [comment]
> According to our research it is not possible to delete posts that aren't marked editable by the author via state bloat bond. Non-editable posts or threads cannot be deleted.

Yes AFAIK this is intended, the way that these forum posts are supposed to be deleted/hidden is via metaprotocol (again AFAIK).

**Comment by traumschule** [comment]
However it might be possible to mark them hidden? https://handbook.joystream.org/system/forum#editable-non-editable
> When a thread or post is being deleted it just indicates that you no longer want to edit it. To indicate that you want it to be hidden, similar to deletion in a classical forum, you need to set hidden to true.

**Comment by mochet** [comment]
> However it might be possible to mark them hidden? https://handbook.joystream.org/system/forum#editable-non-editable
> 
> > When a thread or post is being deleted it just indicates that you no longer want to edit it. To indicate that you want it to be hidden, similar to deletion in a classical forum, you need to set hidden to true.

I don't think this will work either. Basically a non-editable post doesn't exist in the state anymore, so the error that comes up when trying to do anything to it is that it doesn't exist.

I suppose maybe it is possible to change the runtime itself to ignore this error and let it successfully pass moderation actions against post numbers that don't exist, but that kind of change seems very extreme compared to implementing metaprotocol in this case and is far beyond my own personal knowledge (i.e. I don't even know if it would be possible)
