### ISSUE TITLE
[USERSNAP] Wrong "My contributed votes"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4250]
**Taken at**: https://pioneerapp.xyz/#/election/past-elections/00000007
**Fields**:
- Houston, we have a problem.: Wrong &#34;My contributed votes&#34;
- Comment: My contributed votes show the wrong value in the election history. Apparently, it only shows votes from 1 wallet. I think it should show all votes from all wallets
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/548aeb2e-8b44-42a9-842d-56b60350e028-annotated_32464b20-9dde-4c13-9bf2-a954a33df139.png?etag=470489f493c3bf08d0a4daf9d122815d)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/548aeb2e-8b44-42a9-842d-56b60350e028-annotated_32464b20-9dde-4c13-9bf2-a954a33df139.png?etag=470489f493c3bf08d0a4daf9d122815d)*

**Browser**: Chrome 111 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[Open #403 in Usersnap](https://app.usersnap.com/l/feedback/c0a58060-d72f-41da-a075-f538d4eab769?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Something seems to be wrong. I only see one vote for one candidate instead of 3.

**Comment by dmtrjsg** [comment]
@chrlschwb seems like a high-priority one, since it touches on elections.. but feel free to prioritise in-line with your rationale

**Comment by traumschule** [comment]
Could it be related to a hardcoded query limit? Because i also saw only one in `My Votes` although i had more.

**Comment by traumschule** [comment]
This bugs me every time.

**Comment by chrlschwb** [comment]
release:1.9.0
