### ISSUE TITLE
Email Templates Design for Pioneer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4252]
We need a very simple html template for the transactional emails

Header
Footer with links back to pioneer app and joystream.org

[Link to Pioneer Logo> ](https://www.figma.com/file/3hnTi8QWyHDOtkZENhjxjB/Pioneer-brand?node-id=22-9469&t=xxwhdMgYZ4BV1ZPc-0)

**Comment by KubaMikolajczyk** [comment]
The design for templates for emails are done ✅
https://www.figma.com/file/xpddKGxayX5O2orVAeUJUR/Pioneer%3A-Email-Templates?node-id=1%3A2&t=Yjb46paFCEFZWj81-1
