### ISSUE TITLE
QA : Ephesus Upgrade Community Testing

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/pioneer#4255]
This is the runtime proposal for Ephesus upgrade.
https://pioneerapp.xyz/#/proposals/preview/175

To ensure the successful upgrade, the BWG will perform QA testing of the expected new features.

This is the playground for the tests.
Pioneer: https://ephesus.joystreamstats.live
Atlas: TBA

Scope:
- Council Payout
https://www.notion.so/joystream/Gleev-Operation-2ee6319c7688464c8800ecbfa3b17abd?pvs=4#d764e54565da4362b4fba26787b8080b
- Direct Member Payment
https://www.notion.so/joystream/Gleev-Operation-2ee6319c7688464c8800ecbfa3b17abd?pvs=4#3e1bbfa185d1425c91fa5905fb9b9846
- Check sudo removal
- check constitutionality change
- governance blacklisting

**Comment by ivanturlakov** [comment]
### Constitutionality change

✅ Runtime Upgrade | Reduced to 2
✅ Set Max Validator Count | Reduced to 2
✅ Set Council Budget Increment | Reduced to 2

<img width="1407" alt="Screenshot 2023-03-24 at 13 27 06" src="https://user-images.githubusercontent.com/46903215/227510407-2fa7cdd8-3a4c-4ea5-b3ef-a2560c9248f7.png">
<img width="1079" alt="Screenshot 2023-03-24 at 13 27 56" src="https://user-images.githubusercontent.com/46903215/227510419-21301984-c6e7-4af4-9258-c4fa3f993e3b.png">

**Comment by ivanturlakov** [comment]
> * Check sudo removal

I have no idea how to check it 🤔

@traumschule @oleksanderkorn @freakstatic guys, could you advise?

**Comment by chrlschwb** [comment]
> > * Check sudo removal
> 
> I have no idea how to check it 🤔
> 
> @traumschule @oleksanderkorn @freakstatic guys, could you advise?

You could just check the block explorer and see if there is sudo extrinsic

**Comment by ivanturlakov** [comment]
### ✅ Check sudo removal

**Current Pioneer version**
https://pioneerapp.xyz
https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/extrinsics
<img width="1177" alt="Screenshot 2023-03-29 at 18 58 14" src="https://user-images.githubusercontent.com/46903215/228598637-8593db52-c1d2-4697-9152-2be41a841ce9.png">

**Ephesus** - Sudo removed
https://ephesus.joystreamstats.live/
https://polkadot.js.org/apps/?rpc=wss://ephesus.joystreamstats.live/rpc#/extrinsics
<img width="700" alt="Screenshot 2023-03-29 at 18 59 31" src="https://user-images.githubusercontent.com/46903215/228598793-e0ae6377-1654-4dca-b384-6293088c0981.png">

**Comment by traumschule** [comment]
I reread the [risk assessment](https://gist.github.com/bwhm/f0229ec577bac85feb7e351177fa8f8f#manual-tests) to make sure all changes are covered.

It mentions `Given the very few transactions (and queries) that have been change` but doesn't specify them so i have to assume those are out of scope.
=> It is unclear if those cause breaking changes to existing tooling. @bwhm please confirm and close.

> New Transactions Not Supported
> - The new updatePayoutProposal, and associated transactions (claiming etc.) are
> Claiming is supported in Atlas (and works well).

=> considered tested via atlas, OOS for pioneer

>  some *.*Remarks and referendum.optOutOfVoting, are
> Supported in the CLI (and working well).

=> considered tested via CLI, added to #3097 for pioneer integration

**Comment by bwhm** [comment]
Hey,

> It mentions Given the very few transactions (and queries) that have been change but doesn't specify them so i have to assume those are out of scope.

Complete list of extrinsics that are added or changed
### New
1.`referendum.optOutOfVoting`
   - blocks the address of the signer from **voting** on council members

### Changed
2. `content.updateChannelPayouts` (tested)
   - filtered by runtime version 1001, will not be by 2001
   - only callable through the proposal "Update Channel Payouts Proposal".
   - the extrinsic has **also** been changed
3. `members.memberRemark`
   - added an *optional*  payment.
   - QN only "cares" if the remark is encoded as a payment to a channel (or channel:video)

#### Trivially Changed
4. `members.inviteMember`
   - whereas the extrinsic itself is not changed, the event emitted now includes a reference to the invitation balance
   - only QN affected
5. `members.updateAccounts`
   - weights now calculated correctly.
6. `<wg>.workerRemarks`
7. `<wg>.leadRemark`
   - tweaked so runtime code is (as far as possible) the same as for *other* `*Remark` extrinsics.

### Removed
8. `sudo.*`
  - sudo pallet removed.
  - in practice, this also removes a lot of extrinsics that was only callable by `origin: root`, and not called by any proposals.
  - removing these extrinsics would mean a significant deviation from substrate, requiring lots of manual work for future substrate updates.
