### ISSUE TITLE
[USERSNAP] Too wide empty space

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4272]
**Taken at**: https://pioneerapp.xyz/#/forum/thread/318
**Fields**:
- Houston, we have a problem.: Too wide empty space
- Comment: More space should be given to the posts

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/327f596c-b3c7-4c5c-bc82-a2e3b06edd2a-annotated_27f7304c-53a7-41c9-a3bf-6b7aca7d40f0.png?etag=0873d427524c2e6ce858ed8fa583d144)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/327f596c-b3c7-4c5c-bc82-a2e3b06edd2a-annotated_27f7304c-53a7-41c9-a3bf-6b7aca7d40f0.png?etag=0873d427524c2e6ce858ed8fa583d144)*

**Browser**: Chrome 111 (Windows 10)
**Screen size**: 3840x2160
**Browser size**: 1366x657
**[Open #407 in Usersnap](https://app.usersnap.com/l/feedback/4b0558c2-25c9-4ae2-b38a-1b300b2a5a82?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by IlyaSmiyukha** [comment]
Not sure how wide it should be. Check pls the examples below:

1. full width 
2. 80% of content width
3. 80% of content width for post and textarea 

<img width="1057" alt="Screenshot 2023-03-29 at 17 51 03" src="https://user-images.githubusercontent.com/39830587/228587116-9d69b748-b4da-4121-8be1-8cbcef190532.png">
<img width="1057" alt="Screenshot 2023-03-29 at 17 50 28" src="https://user-images.githubusercontent.com/39830587/228587120-1505fb17-ca3a-4703-8608-5760e3068dbc.png">
<img width="1057" alt="Screenshot 2023-03-29 at 17 50 01" src="https://user-images.githubusercontent.com/39830587/228587124-3f8c009a-62b6-4990-bf31-e60ad982cdf5.png">

**Comment by traumschule** [comment]
Can we try 90%?

**Comment by IlyaSmiyukha** [comment]
Sure. 
<img width="1057" alt="Screenshot 2023-03-29 at 21 45 34" src="https://user-images.githubusercontent.com/39830587/228637675-e06967b5-d842-48ec-9904-dd45efa31aac.png">

**Comment by chrlschwb** [comment]
Let's put post and textarea both 90%.
@IlyaSmiyukha, please create a PR after that, let's get this merged asap.

**Comment by IlyaSmiyukha** [comment]
@chrlschwb Check pls this PR https://github.com/Joystream/pioneer/pull/4307

**Comment by thesan** [comment]
@IlyaSmiyukha @chrlschwb @dmtrjsg IMO I don't think it should be about a percentage.

If you have a lowres screen like in the 1366px screenshot you should get 100% but for wider screens a `max-width` can apply.

E.g on GitHub the `max-width` is 1280px (including 32px padding on each side):
![image](https://user-images.githubusercontent.com/6571453/228894922-68260c34-d3b7-42e0-b7c0-fd2f7351edd5.png)

I find it slightly small but since Pioneer has a sidebar I think `1280px` would be good (it would even be bigger than the current 60% width on my 2256px wide screen).

**Comment by IlyaSmiyukha** [comment]
@thesan I've just pushed changes. You can try it

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/370
Mainnet

Looks good 👍

<img width="1440" alt="Screenshot 2023-05-04 at 15 41 34" src="https://user-images.githubusercontent.com/46903215/236207825-806753d3-0284-42fa-8297-bac85eccfb64.png">
<img width="1440" alt="Screenshot 2023-05-04 at 15 42 30" src="https://user-images.githubusercontent.com/46903215/236207835-568eb171-ba99-4cb4-88fa-0b374286dfc4.png">
