### ISSUE TITLE
[backend] Write nicer html emails

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4274]
## Context

Since we want the solution to be email distribution platform agnostic, we want the HTML templates for emails to be passed as HTML to the email platform used by BE service, rather than configuring them on each platform individually. 

## Layout Design

[LInk to Figma>](https://github.com/Joystream/pioneer/issues/4252)  

## Scope
- [ ] Create HTM version of the template for the different notifications, using layout designs attached. 

1️⃣ Verify email

`Dear {Name},
Follow this link {ilnk back to the app} to verify your email for receiving transactional notifications from the Pioneer App.`

CTA = Verify email. 

Points back to Pioneer.

2️⃣  2.1 Council election stage updates: Election stage

`Hi {Name},
Election stage has now started. Follow the link to create council election candidacy.`

CTA = Create Candidacy

2️⃣  2.2 Council election stage updates: Voting stage

`Hi {Name},
Council elections voting stage has now started. Follow the link to vote for the council candidates.`

CTA = View Candidates

2️⃣  2.3 Council election stage updates: Revealing stage

```
Hi {Name},
Council elections revealing stage has now started. In case you voted, follow the link to reveal your votes.
```

CTA = Reveal votes

3️⃣  Forum/Direct mentions 

```
Hi {Name},
You've been mentioned in Forum thread: {Forum_thread_Name} by {handle_of_member_who_mentioned}. 

{Preview of message}
```

CTA = Reply on Forum

Points to the exact post where user was mentioned

4️⃣ Forum/Threads/EveryNewThreadCreated

`Hi {Name},
New forum thread was created in {Name_of_forum_category} Category.`

CTA = View on Forum

Points to thread

5️⃣  Forum/Threads/AllPostsInThreadIcreated

`Hi {Name},
New post was added to the {Name_of_thread} thread you created`

CTA = View on Forum

Points to thread

6️⃣ Forum/Threads/AllPostsAndRepliesInThreadsIposted

`Hi {Name},
New post was added to the thread where you posted: {Name_of_thread}.`

CTA = View on Forum

Points to post

## Technical suggestions

For emails, styles should be inline.

In my experience writing emails which look good regardless of the email client can be painful. So if it's not overkill [mjml](https://github.com/mjmlio/mjml) looks like a nice solution.

**Comment by ignazio-bovo** [comment]
After a call with @thesan I tried locally a combination of handlebars and mjml
Steps to reproduce:
``` sh
npm i mjml
npm i handlabar
```

run the following using `npx ts-node`

``` typescript
import { compile } from 'handlebars'
import fs from 'fs'
import path from 'path'
const mjml2html = require('mjml');

type RegisterEmailTemplateData = {
  link: string
  linkExpiryDate: string
  appName: string
}

const registerEmailContent = compile<RegisterEmailTemplateData>(
// this is xml which can be read from a file
  `<mjml>
    <mj-body>
      <mj-container>
        <mj-section>
          <mj-column>
            <mj-text>
              Hello, {{name}}!
            </mj-text>
          </mj-column>
        </mj-section>
      </mj-container>
    </mj-body>
  </mjml>
`
)
export function registerEmailData(templateData: RegisterEmailTemplateData) {
  const { html, error } = mjml2html(registerEmailContent(templateData));
  if (error) {
    console.error(error);
    return
  }
  return {
    subject: `Welcome to ${templateData.appName}!`,
    content: html,
  }
}

const res = registerEmailData({
  link: "http://www.example.com",
  linkExpiryDate: "2021-01-01",
  appName: "test APP"
})

console.log(res)

```

**Comment by thesan** [comment]
@ignazio-bovo thanks a lot for giving it a try :pray: . It looks good, and https://mjml.io/try-it-live/templates/basic should make writing the templates a lot easier.

@AnttoLion I think Pioneer should also have a folder dedicated to templates, like Orion [here](https://github.com/Joystream/orion/tree/8862b897a63366cd64114c8eeff6cad1717b001f/src/auth-server/emails/templates) (see the full PR https://github.com/Joystream/orion/pull/154). However since Pioneer already depends on lodash IMO using [`_.template`](https://lodash.com/docs/4.17.15#template) makes more sense than adding handlebars as another dependency.
