### ISSUE TITLE
Verified status: no visual representation in Pioneer UI

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4300]
Currently there is no visual representation of a user having the `verified: true` flag on their membership on Pioneer, this includes:
- Member directory
- Forums
- Proposals

I wouldn't say this is a high-priority thing to fix, but given the coming new Staking UI/UX and the fact that `jsgenesis` and `Gleev` memberships are now verified (https://pioneerapp.xyz/#/proposals/preview/219) this should ideally be implemented.

**Comment by dmtrjsg** [comment]
There are designs for this (icon): 
- https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=1405%3A76675&t=METypWLGzX3dVaJo-1
