### ISSUE TITLE
DWG: Assign bags to buckets

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4306]
As DWG lead i want to be able to assign non-empty channels to different buckets.

The UI should be able to show size for each bag (channel) and deselect some by clicking on it.
- show all buckets
- expandable list of channels for each

Because there are ten thousands of channels the UI needs to provide Buttons for shortcuts per bucket like 'Select all', 'Select none', 'Select non-empty' or accept a list of bag IDs (input field).

To apply selected changes after configuring all buckets lead can click "Apply". The new settings will be applied signing a batch tx (split into multiple blocks of one is not enough).

Query
```
query { channels (limit: 50000,orderBy:createdAt_ASC, where: { videos_some: {isPublic_eq: true} } ) {
  id videos {id}
}}
```

Relevant [JSS code](https://git.l1.media/JoystreamStats/jsstats/src/frontend/src/components/Distribution) and design:

![buckets](https://user-images.githubusercontent.com/31551045/228622038-eaf79feb-b88e-456c-8e02-d6eb23e957b0.png)

[Context](https://discord.com/channels/811216481340751934/933726271832227911/1090643290958872646)

**Comment by dmtrjsg** [comment]
Looks like this was meant to go to Joystream repo.. moving issue there 

cc @traumschule

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/joystream #4725](https://github.com/Joystream/joystream/issues/4725) via [**Zenhub**](https://www.zenhub.com/)
