### ISSUE TITLE
Add Grace Period to Proposal Preview Page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4319]
## Context

For time-sensitive proposals its important to show grace period for operations coordination. Currently grace period only shows to creator of proposal in the Create Proposal flow. 

## Scope
Add grace period to proposal details view
- [ ] Show grace period duration in time/ block
- [ ] Show Exact Block Number at which proposal executes

**Comment by thesan** [comment]
QA: https://github.com/Joystream/pioneer/pull/4478#issuecomment-1742762682

@ivanturlakov @chrlschwb thank you for taking care of the QA. But whenever possible (like here were the PR has already been merged on the `dev` branch) please test the issues on [pioneer-2.vercel.app](https://pioneer-2.vercel.app). (But obviously no need to re-test this one).
