### ISSUE TITLE
Clicking on mention member handles

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4320]
ER: Clicking on member handle from forum posts should open side bar (Like behavior from tooltip)
AR: Now it goes to /members

![Screenshot 2023-04-03 at 17.54.46.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/4a55ca21-fd1f-41dc-8e70-b9efa7cf34f3)

**Comment by devmaster54** [comment]
I fixed this issue and created a PR.
https://github.com/Joystream/pioneer/pull/4483
