### ISSUE TITLE
Validators list - Page and widgets

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4326]
## Context

- https://github.com/Joystream/pioneer/issues/4321

## Design

[Link to Figma> ](https://www.figma.com/file/tjad3r2EZJXRMFOELcxxNR/Validators?node-id=5%3A1550&t=jqHGNwf0jVupH08w-1)

Design Preview

![Screenshot 2023-04-05 at 19.26.03.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/c47af9fd-7f1f-4514-9656-595554d4ce5d)

## Scope
- [ ] Add Validators Module to the side menu
- [ ] Add validators list tab to the validators page
- [ ] Display info modal on first open on the page (keep the status in local storage when "do not show this again" is selected)
- [ ] Widgets: 
-- Validators State
-- Staking
-- Era 
-- Rewards
- [ ] Tooltips for each widget

**Comment by dmtrjsg** [comment]
**Validators:** 
1. Let's move that info to the table from the side bar: points, own stake, total stake. We achieve this by reducing the space taken by verification and active columns. 
2. Scrap Health
3. Add Validator Era points to the side bar as a chart

**Nominations**

1. Add stack and controller stash for each validator card
2. Add ERA selector, by default is most recent era. 

**Rewards History**

Comments TBD

**Comment by dmtrjsg** [comment]
1. Pls remove the APR from the widget, we will add it much later, there's no straightforward way to calculate it overall and average for all validators would not make much sense. 
2. Re Ideal staking, need to double check from @bwhm.. can you pls advice if this is available from the Epoch?

**Comment by chrlschwb** [comment]
1. How about just calculating like this:
APR = ( lastRewards * 4 * 365 ) * 100 / currentStaking

2. There is no "ideal staking" value on blockchain. It needs to be calculated somehow.

**Comment by traumschule** [comment]
Ideal stake is 50%, defined [here](https://github.com/Joystream/joystream/blob/master/runtime/src/lib.rs#L519). It's also on display [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org#/staking).
![overview](https://github.com/Joystream/pioneer/assets/31551045/34896e9e-6561-479b-93f7-4a0a4804e25f)

APR per nomination / validator can be determined depending on actual payout to that slot (`last_era_reward`) and split after commission (`C`) and stake percentage (`P`):
> last_reward = last_era_reward * C * P
>                     = 200 * (1 - 0.05) * (500 k / 2000 k) = 200 * .95 * .25 = 47.5
> APR = last_reward * 4 * 365 / own_stake
> 200 * .95 * .25 * 4 * 365 / 500000 = 0.1387

(simpliyfied) With deeper era history the result will be more correct.

**Comment by eshark9312** [comment]
how should I get the "total rewards" value?
It is hard to get the information about the eras beyond the 'history depth'.
To access the eras before the 'history depth', I should map the all blocks and get the hashes. It will take too much time to show the result in the page.
'history depth' is 120 (30days), and I can sum up the rewards according to those 120 eras.
What about changing the design: "Total" -> "Last Month", "Last" ->"Last Era"

**Comment by dmtrjsg** [comment]
From my pov its okay to show totals within the history depth available, e.g. 120 Eras. Re Changes in the designs sounds reasonable for me just not to overcomplicate the first version and help the expedience of the release.

**Comment by eshark9312** [comment]
Thanks, for your suggestions. 
I implemented all the requirements from you but the last one for adding `slot price` in Rewards widget. 
- How can I get `slot price`? is it the same as `lowest total stake` on [polkadot.js](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org#/staking) site?
- Is it relevant to add this to `Rewards` widget, which currently shows `Total` and `Last` rewards?
