### ISSUE TITLE
No trx hash or block # showing when transferring joy using Pioneer

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#4338]
A while ago, I transferred some joy to another wallet via Pioneer. When transfer is finished, UI showed transfer succeeded but no trx hash or block # provided. I suggest these data will show and can be copied so sender can inform recipient of transaction. This can be helpful esp. if the recipient doesn't remember balance of his/her wallet.

**Comment by dmtrjsg** [comment]
Just tested it and it shows: 

https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/explorer/query/0xecc81d77d72ce70e5bc885e2ca2de4aec0804bcd00e7b2a88ea1e9fd1ca7682f

<img width="581" alt="Screenshot 2023-04-14 at 13 37 07" src="https://user-images.githubusercontent.com/93924525/232008054-df77657c-39c5-45bf-8911-e9ae8bfe2d46.png">

**Comment by dmtrjsg** [comment]
@Songoku1691
