### ISSUE TITLE
Council/Election: pages should show how long the current council is expected to last for

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4340]
# Problem
The `Council` page on Pioneer doesn't show how long the currently elected council is expected to last for. This impacts users on whether or not they should submit a proposal or wait for the current term to end. The `Election` page also suffers from the same problem, but while it explains how long the current election `stage` is, it doesn't provide a new user any overall understanding of council/election cadence.

# Solution
Adapt the `Election in progress` status section to give some form of indication for how long the current council will possibly last for.
It should also show how long the current council has been elected for (as a new user I should be able to tell the general cadence of councils/elections without having to click through many sections--do they last a week, month or years?)
I would almost suggest that both the `Council` and `Election` page could have the same UI to indicate this.

**Comment by dmtrjsg** [comment]
Covered in 
- https://github.com/Joystream/pioneer/issues/4006
