### ISSUE TITLE
[USERSNAP] Council: CM Rewards unclear

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4345]
**Taken at**: https://pioneerapp.xyz/#/council
**Fields**:
- Houston, we have a problem.: Council: CM Rewards unclear
- Comment: This is unclear if it is per CM or for all CMs combined, it makes a lot more sense to show &#34;per CM&#34;.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/577cabb7-3bf1-45de-92b7-6749bf373e3d-annotated_58f845d3-687a-44ef-83d8-36233650e959.png?etag=76983e10f795825e45194aaa4d958e65)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/577cabb7-3bf1-45de-92b7-6749bf373e3d-annotated_58f845d3-687a-44ef-83d8-36233650e959.png?etag=76983e10f795825e45194aaa4d958e65)*

**Browser**: Chrome 112 (Linux)
**Screen size**: 3440x1440
**Browser size**: 1472x1009
**[Open #414 in Usersnap](https://app.usersnap.com/l/feedback/398e56bb-e4a5-4a51-94bc-e388ece03b1f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Update label to "Reward Per Councillor"

**Comment by mochet** [comment]
> Update label to "Reward Per Councillor"

The reward shown (based on my calculations) is actually the reward for all CMs, so the label + calculations would have to change.
