### ISSUE TITLE
GH pages deployments fails

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4347]
## Context

It always look like the last deployment failed:

![image](https://user-images.githubusercontent.com/6571453/231399329-e6db4e8e-ede4-41a6-9ad6-d0bfbfd8fb1b.png)

It's caused by these "gh-pages" deployment on Vercel:

![image](https://user-images.githubusercontent.com/6571453/231400195-beda3061-87c5-4333-9cd1-21c0ba1ec9fa.png)

## Scope

I'm not sure of the purpose of this deployment. Should it be fixed or remove ?

**Comment by traumschule** [comment]
[All green](https://github.com/Joystream/pioneer/deployments)

**Comment by thesan** [comment]
> [All green](https://github.com/Joystream/pioneer/deployments)

@traumschule TBH I'm not sure what happens exactly but even though the `gh-pages` workflow always succeeds it somehow triggers a Vercel deployment which always fails:
![Screenshot from 2023-06-15 18-19-47](https://github.com/Joystream/pioneer/assets/6571453/0127dd92-50d9-4bea-b513-b56b9b4eb11a)
Which makes sense since that branch hasn't been updated for years...

But I don't think this workflow is of any use anymore so we should probably remove it.
