### ISSUE TITLE
Proposal with Constitutionality 2 is not showing multiple tabs

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4348]
## Context
https://discord.com/channels/811216481340751934/1035125653722365993/1095732012914069664

## Details
![Screenshot 2023-04-12 at 19.32.00.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/4d159f5d-739c-4380-a73d-5a2dd3d5ea78)
![Screenshot 2023-04-12 at 19.32.08.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/9c1e9337-e88b-4342-ace9-7ef9b50f5115)

**Comment by thesan** [comment]
It looks like we forgot to update the condition to display the tabs in [`1.3.1`](https://github.com/Joystream/pioneer/releases/tag/v1.3.1).

It's still `proposal.status === 'dormant' || votingRounds.length > 1` so the tabs don't show during the first deciding stage.

**Comment by dmtrjsg** [comment]
Oh nice catch, thanks for triaging this so quickly! Let's try to patch it when we can 👍

**Comment by chrlschwb** [comment]
I will fix it in a moment.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-dev-joystream.vercel.app/#/proposals/current
wss://54.205.24.16.nip.io/ws-rpc

@chrlschwb do I use a correct env?

Proposal created
<img width="1153" alt="Screenshot 2023-05-01 at 15 48 50" src="https://user-images.githubusercontent.com/46903215/235453771-b86d0ece-5ba6-4520-9ece-6884cc248881.png">

404 when trying to open a proposal page
<img width="1440" alt="Screenshot 2023-05-01 at 15 48 27" src="https://user-images.githubusercontent.com/46903215/235453840-8001b075-259f-4b49-b5a4-5c9b50742168.png">

**Comment by chrlschwb** [comment]
What is this endpoint? wss://54.205.24.16.nip.io/ws-rpc
The error shows that "UpdateChannelPayoutProposal" which was introduced in Ephesus isn't recognized. I think the QN you are using is outdated.

**Comment by ivanturlakov** [comment]
Tested on 
https://pioneer-2-git-fork-chrlschwb-fix-4348-proposal-a7b1be-joystream.vercel.app/#/proposals/preview/289
https://dao-git-dev-joystream.vercel.app/#/proposals/preview/289
Mainnet

Error when trying to open a proposal page
<img width="1440" alt="Screenshot 2023-05-02 at 13 24 42" src="https://user-images.githubusercontent.com/46903215/235642858-91d9d40d-5c37-4cd7-874f-3554a54d61bf.png">

**Comment by chrlschwb** [comment]
@ivanturlakov the issue you are raising is irrelevant to 4348 as 4348 is addressing only a display issue while the new problem arises when creating a new proposal.

**Comment by chrlschwb** [comment]
https://dao-git-dev-joystream.vercel.app/#/proposals/preview/313
I have created a new proposal on mainnet to prove that the above issue is a QN issue which arises because you have created the proposal on testnet.

**Comment by ivanturlakov** [comment]
@chrlschwb anyway there is no chance to test 4348 untill this issue solved

**Comment by ivanturlakov** [comment]
✅ Tested on https://dao-git-fix-proposal-first-of-multi-round-joystream.vercel.app/#/proposals/preview/289
Mainnet

Works as expected

<img width="1440" alt="Screenshot 2023-06-02 at 15 32 39" src="https://github.com/Joystream/pioneer/assets/46903215/3e882bc4-0d6f-4d3b-a18f-86fd7a1834a6">
<img width="1440" alt="Screenshot 2023-06-02 at 15 33 54" src="https://github.com/Joystream/pioneer/assets/46903215/e8f46195-4043-4bb2-932d-a7a103653faa">
