### ISSUE TITLE
Bad background color in the tooltip

### ISSUE THREAD

**Issue by adovrodion** [Joystream/pioneer#4349]
Bad background color in the tooltip
![image](https://user-images.githubusercontent.com/84832436/231583312-ff7a0344-9903-4390-af87-bdc05602cc9b.png)
I think this is not the best background color for a tooltip with the current text color 
https://pioneerapp.xyz/#/proposals/preview/250

**Comment by dmtrjsg** [comment]
Already worked on by Chaos.. 
- #4258 

Same needs to apply to Proposals @chrlschwb
