### ISSUE TITLE
Joystream Block Explorer

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/pioneer#4367]
Current Joystream users rely on the polkadot js explorer which is not very user-friendly and also lacks important features that etherscan.io users are accustomed to.
Namely, we cannot search for addresses and view transaction histories like in other block explorers.
We need a new block explorer and the following are the basic requirements.

- A main page like https://etherscan.io/
  It should include a search by address/tx hash/block
- a block info page like https://etherscan.io/block/17123186
- a transaction info page like https://etherscan.io/tx/0xeabf5512a8341d273528b5c56b36cf2526753034b183b94545d00a7caf67e845
- an address info page like https://etherscan.io/address/0xffd0ecee885fcd2ebce0fec9add69bf1ed03194b

**Comment by dmtrjsg** [comment]
In our opinion worth linking this up with 
- #4373
