### ISSUE TITLE
Forum: truncated title

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4371]
URL: https://pioneerapp.xyz/#/forum/thread/360

With window tiling and half width thread titles are cut without overlay (`title` tag). However the full title is in the breadcrumb (harder to read).

It's obvious the buttons don't have to take that much space on narrow screens. For example only show their text on hover depending on breakpoints.

![titlecut](https://user-images.githubusercontent.com/31551045/235366380-ed4a3afe-57d2-4431-9777-e6c5b1ecd996.png)

**Comment by dmtrjsg** [comment]
That will be handled in the responsive design epic, which is already in progress with @Counsellor-sama 

so cancelling this issue to be superceded by 

#1794
