### ISSUE TITLE
Add Trust Wallet on Supported Wallets for Joystream

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/pioneer#4378]
Suggestion: Add Trust Wallet on Supported Wallets for Joystream

Reason: Trust Wallet is one of 2 most popular crypto wallets in the space. Its mostly used on EVM networks (like ethereum, smart chain...) but it started supporting non-EVM networks as well. I checked my TW app, I think they support Polkadot network also. It has a millions of users so it make sense to make it compatible with Joystream. It will play a vital role esp. in attracting users from different blockchains since they don't need to install new wallets anymore. It might also help in facilitating bridge from supported different networks. I imagine TW being the preferred wallet also for mobile version of Joystream dApps.

**Comment by dmtrjsg** [comment]
We've looked at it and seems like Trustwallet is yet to support Polkadot.. Tested with both Beta and Production extensions.

While there is a possibility to add custom networks, it did not seem like it was supporting Joystream when we tried:

<img width="439" alt="Screenshot 2023-05-12 at 14 30 29" src="https://github.com/Joystream/pioneer/assets/93924525/e938a9b4-b57f-41b5-b7e4-fbe75d81f19a">

@Songoku1691 fyi
