### ISSUE TITLE
Show balance on `Accounts` tab

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4379]
Show account balance on user profile sidebar (`Accounts` tab). The sidebar opens when user clicks on a member and helps to assess activity and reputation for example.

**Comment by dmtrjsg** [comment]
@traumschule added to design backlog, but just FYI there's already a total balance displayed for the members here: 
<img width="999" alt="Screenshot 2023-05-12 at 14 33 13" src="https://github.com/Joystream/pioneer/assets/93924525/c0ac0e1f-199f-465e-be93-a3853d6d6ef0">

**Comment by dmtrjsg** [comment]
Suggestion to display accounts balance here:

<img width="390" alt="Screenshot 2023-05-12 at 14 34 25" src="https://github.com/Joystream/pioneer/assets/93924525/ce007292-f63b-433c-8bd9-bd9e3cc00327">
