### ISSUE TITLE
UGRENT: Update block explorer link

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4389]
To this: https://calamar.app/joystream/

**Comment by traumschule** [comment]
I don't think that one is sufficient or even better.

**Comment by bedeho** [comment]
- if not sufficient, please state features you value, then at least with a specific list those can be contributed back to the open source code base.
- "not better": well, it certainly has indexing based on lots of things people want to like accounts and transactions, which the other one does not have, but what do you feel is missing? I agree there are tons of features in polkadotjs which are missing, but not as much as a block explorere per say. Subscan also would not have many of those, so seems we would need to link to both?

**Comment by traumschule** [comment]
Looks like so far this one only supports `Timestamp` events. Joystream was added in March (https://github.com/topmonks/calamar/pull/138). Do you know if anyone is working on support for other types?
Showing transactions paginated with deep history and being able to filter by event type plus full text search in method, section and data would be "better".

**Comment by mochet** [comment]
One limitation that Calamar block explorer has it that it cannot display balances or balance history. Polkadot-js cannot fully do this either but it can at least recognize the live balance of an account whereas Calamar cannot do this currently.

Some of the chains on Calamar seem to support balances so it would be interesting to understand what is stopping Joystream from having balance support.

**Comment by bedeho** [comment]
Agreed, but lets not have the perfect be the enemy of the good: Calamar is a block explorer in that it indexes blocks, accounts and transactions, this is the most important thing people want to know about. If we want more stuff, lets contribute it back to Calamar. Polkadotjs is really 10 things in one, but not a block explorer.

# Conclusion

1. We keep the current icon which links to polkadot.js, and call it "Chain Dashboard"
2. Above it we add a new icon, which will need to be made, and call it "Block Explorer", which links to Calamar.

**Comment by traumschule** [comment]
We could also show both as icons next to `Explorer`.
