### ISSUE TITLE
Proposals: Council Budget Increment not clear enough

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4392]
![image](https://github.com/Joystream/pioneer/assets/50830161/227c9fc8-fc34-496c-a13b-3a5c8c261a4d)

This really needs a better UI to explain what the parameter exactly is. The description of the proposal type says its the budget per council period but it would really help a lot to have this be clearer.

In terms of priority there are active discussions on adjusting this amount currently and I am concerned that a mistake could be made since this proposal type has not so far been used on mainnet.

**Comment by traumschule** [comment]
We could show [this description](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/proposals/model/proposalDescriptions.ts#L25) instead of `Set Council Budget Increment`.

**Comment by dmtrjsg** [comment]
Update label to 
`Tokens added to council budget every new period`

**Comment by traumschule** [comment]
Isn't `every new period` just as ambiguous if no one knows how long it is? Intuitively a budget period is a term but it means one day. Explained [here](https://pioneerapp.xyz/#/proposals/preview/345?post=482).
