### ISSUE TITLE
[USERSNAP] Exiting list in Markdown

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4395]
**Taken at**: https://pioneerapp.xyz/#/forum/thread/399
**Fields**:
- Houston, we have a problem.: Exiting list in Markdown
- Comment: It is not possible to exit a list in Markdown mode, e.g. when writing a forum post, by using the keyboard in any obvious way. I have to use the menu, and this took me forever to figure out. We should follow the UX standards on this.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0ddb8ca4-b85e-4d03-a5b9-86dec5ddb150-annotated_f49e272e-cf89-404c-a328-21035a8d774b.png?etag=4c4941979942b11fc30ca7d80f6b95d8)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0ddb8ca4-b85e-4d03-a5b9-86dec5ddb150-annotated_f49e272e-cf89-404c-a328-21035a8d774b.png?etag=4c4941979942b11fc30ca7d80f6b95d8)*

**Browser**: Firefox 113 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1691x1205
**[Open #417 in Usersnap](https://app.usersnap.com/l/feedback/3ebdd5ef-c8b8-4543-875d-5f6635196c64?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@bedeho we just checked it and if you add second line (like press enter two times) that exits the list. What interaction are you thinking about that'd make it more intuitive?

**Comment by bedeho** [comment]
Hmm, that was weird, I explicitly checked that the Github Markdown interaction did not work, but now it seems to. I guess perhaps I was having slow day :D, lets close this then and see if it becomes an issue in the future.
