### ISSUE TITLE
Balance: How to buy $JOY

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4398]
Upon listing it would be a good idea to show users how to buy or exchange $JOY. A link to an exchange would do for this.
This could probably be on the my profile/accounts page somewhere.

**Comment by dmtrjsg** [comment]
Agree with @mochet this should be given to designers as prio after they are done with the next milestone, depending on who gets freed up first.

Similar issue exists for Atlas, please speak to @dmtrjsg before designing this so we can coordinate on how this should be best implemented.

**Comment by dmtrjsg** [comment]
We have some tooltips explaining what Joy token is and how to buy it on Gleev. 

"JOY token is a native crypto asset of Joystream blockchain. It is used for platform governance, purchasing NFTs, trading creator tokens, and covering blockchain processing fees. They are listed on [MEXC](https://www.mexc.com/exchange/JOYSTREAM_USDT) exchange under "JOYSTREAM" ticker."

I think in case of Pioneer it may be useful to provide a link to the website: https://www.joystream.org/token

**Comment by dmtrjsg** [comment]
We have not implemented the same on Gleev yet..I am thinking along the lines of tooltips in all places where balances are shown, including total balance on the side nav. But please do feel free to suggest anything that you find suitable.

**Comment by msmadeline** [comment]
Updated designs: https://www.figma.com/file/vn1oXEDMFlqGXUxhCmKe1P/Joy-buy%2Fexchange?type=design&node-id=36-10968&mode=design&t=vXNHb7CUHtYCu5aT-4
