### ISSUE TITLE
Replace the amount unit from joy to joys

### ISSUE THREAD

**Issue by traumschule** [Joystream/pioneer#4422]
SSIA

**Comment by dmtrjsg** [comment]
its JOY:

https://coinmarketcap.com/currencies/joystream/

<img width="1099" alt="Screenshot 2023-06-12 at 20 27 40" src="https://github.com/Joystream/pioneer/assets/93924525/1d629540-af95-4ea5-af4c-cda2d1da545f">

**Comment by traumschule** [comment]
I want to send joy not joystream.
