### ISSUE TITLE
Update JOY tokens to JOY icon in the places where "JOYSTREAM" will be suboptimal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4429]
## Context

The ticker of the JOY tokens will be JOYSTREAM when listed next week so suggestion is to update it in Pioneer, where it is written in plain text and not shown as icon. 

## Scope

- [ ] Find and replace all places where JOY is written in plain text to JOYSTREAM icon
- [ ] In the tooltips rename JOY token to JOYSTREAM token

Examples:
- https://dao-git-fork-heinricholfert-fix-4422-unitjoy-joystream.vercel.app/#/working-groups
-![Screenshot 2023-06-13 at 12.03.45.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/ea5feffa-3673-4dbe-a984-55f45856341f) 
- 
<img width="939" alt="Screenshot 2023-06-13 at 12 11 47" src="https://github.com/Joystream/pioneer/assets/93924525/f172e567-db85-4f3f-a1af-791b621ef028">

<img width="1062" alt="Screenshot 2023-06-13 at 12 11 53" src="https://github.com/Joystream/pioneer/assets/93924525/5932f10b-c5dc-42b3-98c0-223e761c9de9">

**Comment by traumschule** [comment]
I'm not sure that's an enhancement. No one says "i voted 1M joystream". Do we have to adapt Pioneer at all, since the ticker "joystream" is easy to find anyway, even when someone searches for "JOY".
Actually agree with your former assessment that #4422 can be closed as well.

**Comment by dmtrjsg** [comment]
Agreed not to change the token in the App.
