### ISSUE TITLE
[USERSNAP] Не могу подключить кошелёк

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4459]
**Taken at**: https://pioneerapp.xyz/#/working-groups
**Fields**:
- Houston, we have a problem.: Не могу подключить кошелёк
- Comment: Здравствуйте! У меня kahockey2018@gmail.com не получается подключить кошелёк, зависает страница! У меня есть свой YouTube chanel: KAHOCKEY и мне хочется пользоваться вашим сервисом. Давайте решим эту проблему thes my address 14mYMRLC6ULc19FWC5oEDjwG57oinLJfUpC6MNPjJyjNhZoc

Надеюсь на сотрудничество.
С уважением,
KAHOCKEY
- Link to polkadot block: https://pioneerapp.xyz/#/working-groups
- Feedback: KAHOCKEY

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/501e555f-5f01-4294-9454-86d004da70c6-annotated_cbba79b5-5f3a-4d43-bf8a-0b07c2817ffd.png?etag=67184e97918d382cc15404be5e9502a8)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/501e555f-5f01-4294-9454-86d004da70c6-annotated_cbba79b5-5f3a-4d43-bf8a-0b07c2817ffd.png?etag=67184e97918d382cc15404be5e9502a8)*

**Browser**: Edge (Chromium) 109 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1490x746
**[Open #420 in Usersnap](https://app.usersnap.com/l/feedback/00c89080-7b8a-4755-b584-f368735679b7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Please communicate in english what you did and which problem you experienced. Thanks!

**Comment by dmtrjsg** [comment]
Issue was resolved
