### ISSUE TITLE
[feature request] НЕ МОГУ ПОДКЛЮЧИТЬ КОШЕЛЁК

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4460]
**Taken at**: https://pioneerapp.xyz/#/working-groups
**Fields**:
- Which feature are you missing?: НЕ МОГУ ПОДКЛЮЧИТЬ КОШЕЛЁК
- What problem would that solve for you?: Здравствуйте! У меня kahockey2018@gmail.com не получается подключить кошелёк, зависает страница! У меня есть свой YouTube chanel: KAHOCKEY и мне хочется пользоваться вашим сервисом. Давайте решим эту проблему thes my address 14mYMRLC6ULc19FWC5oEDjwG57oinLJfUpC6MNPjJyjNhZoc 
 
 
Надеюсь на сотрудничество.
С уважением,
KAHOCKEY
- Share your Github or Discord so we can get in touch: KAHOCKEY

**Browser**: Edge (Chromium) 109 (Windows 10)
**Screen size**: 1536x864
**[Open #54 in Usersnap](https://app.usersnap.com/l/feedback/74741d65-50f1-499f-9715-b7af3c0c8d64?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
same as #4459
