### ISSUE TITLE
[USERSNAP] Total Staked value incorrect

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4467]
**Taken at**: https://pioneerapp.xyz/#/election/past-elections
**Fields**:
- Houston, we have a problem.: Total Staked value incorrect
- Comment: Total staked value should display all staked tokens by the candidates as well as by the voters.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9e80cef4-d35b-4517-b0b9-00b59a4e023c-annotated_9d4c83d4-fb7d-456f-8c88-13ac471730c0.png?etag=32afa62b3e0d2931563f489921bcb10a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9e80cef4-d35b-4517-b0b9-00b59a4e023c-annotated_9d4c83d4-fb7d-456f-8c88-13ac471730c0.png?etag=32afa62b3e0d2931563f489921bcb10a)*

**Browser**: Chrome 114 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x657
**[Open #422 in Usersnap](https://app.usersnap.com/l/feedback/0042e7b1-8663-4e1c-a662-52bcc338b446?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
I think we wanted only the voters stake to be calculated as that's the one which defines the voting power. We may suggest to just add tooltip ("Total staked by voters. Candidate own staking is excluded" wdyt? @chrlschwb

**Comment by traumschule** [comment]
Similar to #4312
