### ISSUE TITLE
Too many queries on the forum category page 

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4484]
On category pages with large amounts of threads the amount of QN request quickly reaches the hundreds and keeps on rising. The QN is pretty responsive at the moment but after opening several category pages it starts to throttle and navigating the forum becomes painful.

IMO there shouldn't be that many queries it looks like a bug.

![Screenshot from 2023-07-31 09-51-32](https://github.com/Joystream/pioneer/assets/6571453/74439685-2acb-47af-be0a-2fde2c1985b0)

**Comment by thesan** [comment]
Suggestion:

The "last post" sections might be the most expensive part and "last activity" the close second. IMO instead of sending a lot of queries we could:
1. Sending a big query to get e.g the 500 latest post as well as their tread and direct category id.
2. Caching this query for a long time (maybe even a day).
3. The first occurrence of each subcategories is looked for in the 500 result then either the resulting post is shown or the section is left empty.
4. Do the same for threads for last activity.

Also showing 10 thread instead of 30 would help too.

Alternatively addressing https://github.com/Joystream/joystream/issues/2599 would solve this long term but it would take more work.

**Comment by mkbeefcake** [comment]
@thesan 
I have checked this issue 4484, 
By checking the source code, there were period call for [GetForumThreads, GetForumThreadsCount] graph query per 6 seconds. 
For example, in this attached screenshot, It contains 4 sub categories and 1 main category, so there happened almost (4 + 1) * 3 requests per each 6 seconds by apolloclient.refetchQueries to update the cache from the QN. 
Also per each thread, it calls ForumPost query to get the author of thread from QN, these increases the requests.
So these many requests happened.

**Comment by thesan** [comment]
@mkbeefcake thank you for checking it now makes sense why the number of queries keeps on growing.

However that's part of the bug:
1. Refetching `GetForumThreads` is just meant to keep the current category thread list up to date. But currently it also refetches all the `GetForumThreads` used to get the subcategory latest activity and the popular thread. The solution I proposed above would solve part of this problem too by not sending all of these `GetForumThreads` to begin with.
2. For the `GetForumThreadsCount` IMO it's also not worth keeping the subcategory thread count constantly up to date. Instead the only the current category's `GetForumThreadsCount` should be refetched every 6 seconds.

Also the refetch is only part of the problem, because there are ~50 queries send to load this page (4+1) * 3 + 1 posts query per current category thread (30 displayed at once) to get each of their latest post. This number of queries just to open a common page is already too high.

**Comment by mkbeefcake** [comment]
![image](https://github.com/Joystream/pioneer/assets/69617937/8a2dd756-1516-4b8c-9540-99ca1b28f557)
After fixed the issue 4485, There removed all forumPost requests for main category and sub categories. As you can see in the screenshot, it makes 42 requests for loading screen, 19 + 4 = 23 forumPost and (1 main + 4 subcategory) * sizeof(ForumThreads, ForumThreadsCount) = 10 requests twice and then go on 2 (ForumThreads, ForumThreadsCount) requests per 6 seconds. 

so at the loading time, the formula for requests are as following
ThreadsCount of main category + Subcategory count + (1 + subCategory count) * sizeof([GetForumThreads, GetForumThreadsCount]) * 2

I guess [GetForumThreads, GetForumThreadsCount] is twice called by refreshing the screen after wallet attached.
So at this moment, I guess there is most optimal code for 4484 issue, too

I hope you please check this once more and review this.
