### ISSUE TITLE
Forum: Category pages refreshing multiple times before loading

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4485]
# Problem
Example: https://pioneerapp.xyz/#/forum/category/8

Page will load and refresh multiple times. This happens on different browsers and with or without wallet extension present.

**Comment by dmtrjsg** [comment]
Possibly related to #4484

**Comment by mkbeefcake** [comment]
@thesan I have tried to fix the multiple refresh times for threadlist.
