### ISSUE TITLE
[USERSNAP] Broken lists

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4504]
**Taken at**: https://pioneerapp.xyz/#/forum/thread/551
**Fields**:
- Houston, we have a problem.: Broken lists
- Comment: 1) it does not work to indent multiple levels, this should not be limited
2) lists become light grey for some reason, making it hard to read

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9e082539-2f24-4989-bafc-2bd829305856-annotated_4d476966-8918-4723-8869-1ff3c85757b4.png?etag=451a69398245b3e69bc9f47640860b75)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9e082539-2f24-4989-bafc-2bd829305856-annotated_4d476966-8918-4723-8869-1ff3c85757b4.png?etag=451a69398245b3e69bc9f47640860b75)*

**Browser**: Firefox 116 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1597x993
**[Open #426 in Usersnap](https://app.usersnap.com/l/feedback/e9997500-c4fa-420a-a33e-ac4949368aff?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
The HTML does not show a list within the list. There's a possibility that QN broke the markdown. 

The library used to parse the markdown is unlikely to be the reason. 

Needs further investigation and fixing.

**Comment by mkbeefcake** [comment]
https://pioneerapp.xyz/#/forum/thread/595
@dmtrjsg  I have tried to create new thread with multiple depths and it looks like working. 
When I create sub-section, I used indent button on CKEditor, it works well.
I hope you can check it once more and give me feedback.
Regards
