### ISSUE TITLE
Candidacy stake recovery button not showing on `dev`

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#4505]
Candidacy stake recover button does not show: https://pioneer-2.vercel.app/#/profile?network-config=https://3.73.121.180.nip.io/network/config.json 
![image](https://github.com/Joystream/pioneer/assets/6571453/e71d2405-24a8-49f2-9733-ec7b1efa87a1)

**Comment by dmtrjsg** [comment]
Only shows for some users. Cannot reproduce on my machine :3

**Comment by thesan** [comment]
This was probably fixed
