### ISSUE TITLE
Settings: Allow for custom query node to be used

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4507]
## Problem
Currently, the values for query node and RPC node on the settings page are hardcoded into Pioneer.
![image](https://github.com/Joystream/pioneer/assets/50830161/76261e46-bf66-41c6-8b5c-748a68e4d5f8)

Recently we had two issues:
* All query nodes were broken due to a bug (that has since been fixed)
* Slow query node performance (which has still not been resolved)

Due to this, users may want to use alternative query nodes. While it is possible to spin up alternative instances of Pioneer with different QNs set, this is problematic since the opportunity for fraud/scamming is much higher.

## Solution
* Add a `custom` option that allows a user to input any Query Node that they want to.
* Include a warning about the potential for fraud by using 3rd party QNs

**Comment by dmtrjsg** [comment]
From my pov: 
1. Add an option to the drop down called "Custom"
2. When selected, render 3 separate input fields for URLs with labels: "Faucet", "RPC Node", "Query Node".  
3. The inputs require validation after submitted. So if URL does not resolve to the right place it would be smth like "Connection error". For individual endpoints.
4. When the custom option is selected, we'd need to add an info banner "Please beware that using 3rd party QN may result in fraud. Only use trusted providers."

**Comment by msmadeline** [comment]
@dmtrjsg @chrlschwb The designs for this issue are ready to be reviewed. ✔

📁Link to Figma setting changelog: https://www.figma.com/file/ZwWMTt8ZvEPmFekDHCBWe1/Custom-query-node?type=design&node-id=5-2720&mode=design&t=YcFFRuL2UVaisG61-4
