### ISSUE TITLE
Lists with same color

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4515]
For some reason, lists have a lighter grey color, which really seems like a bug more than anything. For example

![Screenshot 2023-09-02 at 09 35 28](https://github.com/Joystream/pioneer/assets/437292/f1ba8e73-12ff-4231-b5af-3f80f55b9fe2)

https://pioneerapp.xyz/#/forum/thread/572?post=4634

Lists are actually critical for making longer posts readable, so thees sort of issues are really costly. I have also made an issue about the lack of having multiple levels of indentation, so would just like to ask for that to be reviewed at some point also

**Comment by dmtrjsg** [comment]
@chrlschwb potential candidate for low effort high impact so suggesting higher prio.
