### ISSUE TITLE
Openings: Change the way rewards are displayed

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4516]
# Problem
Currently, Pioneer displays rewards for openings as follows:
![image](https://github.com/Joystream/pioneer/assets/50830161/29474d8d-3967-4860-9a86-1fc6496c3dd5)

Almost all of these rewards are basically "per day" and should just be changed to say that, because:
1. Nobody knows what the blocktime of Joystream is unless they've been around for a while. Certainly even if someone knows the blocktime, 14400 will not likely register as being 1 day.
2. There is not any significant material difference in stating that a reward is per 14450 blocks vs per 14460 blocks. It would take more than a year for it to matter.

# Solution
* For all openings, display the reward as `"Reward per day"`
* Ideally, integrate the USD market rate (but that is probably a separate matter)

**Comment by dmtrjsg** [comment]
We have a USD JOY rate feed service already used by Joystream.org and Atlas. Please ask @thesan for details before implementing.

**Comment by kdembler** [comment]
I would suggest that for now we use "Reward per week", I think it will make mental math easier than "Per day"
