### ISSUE TITLE
Pioneer types issues with CRT/nara deployment

### ISSUE THREAD

**Issue by ignazio-bovo** [Joystream/pioneer#4550]
When connecting to the pioneer via the crt deployment rpc we are facing:
<img width="923" alt="image" src="https://github.com/Joystream/pioneer/assets/51839739/8ad7b46a-68f8-4368-aa40-3babdc55963e">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205620196380307) by [Unito](https://www.unito.io)

**Comment by thesan** [comment]
Updated types env: https://dao-git-feature-crt-types-joystream.vercel.app/

**Comment by mkbeefcake** [comment]
@thesan 
Chaos asked to me to do this issue. so i tried to analyze the pioneer and joystream code. By following your guideline, I tried to update the @joystream/types to 4.0.0 and confirmed the changes.
I have tried to check this with wss://rpc.joystream.org:9944.
I guess I have to use another rpc endpoint for this and please let me know the RPC endpoint for this.
Thanks
