### ISSUE TITLE
Proposal type

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4557]
## Context
In Nara release we need to create a new type of propsal "CRT feature management"

## Scope

- [ ] Creating proposal: allows toggling frozen status of, currently, only project_token pallet.
- [ ] Proposal preview

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205620250036159) by [Unito](https://www.unito.io)

**Comment by thesan** [comment]
@dmtrjsg here's the updated feature description:
- #4897

**Comment by msmadeline** [comment]
Hello! I implemented the feedback on the CRT proposal. 
➡Here's the link: https://www.figma.com/file/oD3UTElt3yc4JJfPJv4dn3/Proposals?type=design&node-id=12-12032&mode=design&t=TzOBxhex0Sk3bNjj-4
