### ISSUE TITLE
Add link to new Exchange from "How to buy JOY tokens"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4582]
## Context
We are listed on Bitget exchange now  and need to link to it from Pionerr

## Scope
Add "BITGET" (link https://www.bitget.com/spot/JOYUSDT) to the list of exchanges

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU5DQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b69f1a78b5752c1c44d98e2701cad5e240d544d7/Screenshot%202023-10-17%20at%2014.54.39.png)

**Comment by chrlschwb** [comment]
The current design links Pioneer users to this page https://www.joystream.org/token/#exchanges
So if the joystream.org website is updated, I think Pioneer doesn't need an update

**Comment by dmtrjsg** [comment]
@chrlschwb I was talking about the banner on the profile page: 
https://pioneerapp.xyz/#/profile where we are listing the exchanges..  So worth adding BUYBIT there as well imho (pls see image)
