### ISSUE TITLE
[USERSNAP] Signal Proposal Text Area too small

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4586]
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/576
**Fields**:
- Houston, we have a problem.: Signal Proposal Text Area too small
- Comment: The signal proposal text should be displayed in a modal instead of a small sidebar

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6d460616-3dd0-48ef-9a66-c9a394342676-annotated_444820b9-649c-4415-9910-0e293ea5a7e8.png?etag=4d3c752cbede5b625030a85f0be74c45)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6d460616-3dd0-48ef-9a66-c9a394342676-annotated_444820b9-649c-4415-9910-0e293ea5a7e8.png?etag=4d3c752cbede5b625030a85f0be74c45)*

**Browser**: Chrome 118 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x963
**[Open #431 in Usersnap](https://app.usersnap.com/l/feedback/bb97912c-301e-48d3-aec1-0d3e042ee092?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Probably actual for some cases but not sure if that's getting high up in the prioritised list against other issues. I guess the design implied not using tables here and just a few paragraphs max..

**Comment by msmadeline** [comment]
@chrlschwb @thesan @dmtrjsg Hello I finished designing the correct version of the signal description side drawer. 
Here's the link ➡https://www.figma.com/file/oD3UTElt3yc4JJfPJv4dn3/Proposals?type=design&node-id=64-13353&mode=design&t=mx7G3QiEM9KclbCO-4
Here's a link to RWD ➡https://www.figma.com/file/oD3UTElt3yc4JJfPJv4dn3/Proposals?type=design&node-id=64-9140&mode=design&t=mx7G3QiEM9KclbCO-4

**Comment by thesan** [comment]
@msmadeline the `SM` to `XL` version look good but IMO the mobile ones could stay the same as on the current `responsive` branch e.g: https://dao-git-responsive-joystream.vercel.app/#/proposals/preview/596

![image](https://github.com/Joystream/pioneer/assets/6571453/22163ed4-eb00-4136-967b-26fe1edd9955)

It's actually easier to scroll the table left and right on mobile last time I tried, also side drawers in general have a lot of important information on them so I think they should stay visible on all devices.

**Comment by msmadeline** [comment]
Thank you for your feedback @thesan I already implemented it so please check it out. 
Here's a link ➡https://www.figma.com/file/oD3UTElt3yc4JJfPJv4dn3/Proposals?type=design&node-id=79-17374&mode=design&t=1hhFL2vwJRsXjfjE-4
cc: @chrlschwb

**Comment by thesan** [comment]
@msmadeline that's perfect! the modal header is way too big on the current Pioneer
