### ISSUE TITLE
Email notifications QA

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4606]
## Context
Parent issue (not full scope is implemented just yet - out of MVP only settings were not implemented)
- https://github.com/Joystream/pioneer/issues/4230

## Env to test on

Pioneer environment: https://dao-git-backend-joystream.vercel.app/

Network (go to Settings and select the "Custom" networks):
- Faucet: `https://3.73.121.180.nip.io/member-faucet/register`
- RPC node: `wss://3.73.121.180.nip.io/ws-rpc`
- Query node: `https://3.73.121.180.nip.io/query-node/server/graphql`
- Backend: `https://api-99tc.onrender.com`

## Scope

Modules:
- Forum mentions/ posts stc
- Election

To test:
- Opt-in in to notifications during sign up (new memebrship creation)
- Existing members will be prompted to share email for notificaitons
- Email verification
- Individual events results in email notifications
- Email notiffs assets and data is correct

Settings: 
- Not adjustable on individual level, individual notifications will not be displayed

Events:
:warning: notification on every new thread created is not implemented

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Y2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--713a58944dbc8162ebc0d9f873ff732ad65fe0d3/Screenshot%202023-10-27%20at%2014.08.41.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1o2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3bfb5c3aec83d9824aa4f1e76220797b0e1913a/Screenshot%202023-10-27%20at%2014.08.37.png)

**Comment by polikosi** [comment]
tested on "Custom" network: https://dao-git-backend-joystream.vercel.app/  

❌Opt-in in to notifications during sign up (new memebrship creation)
An error was received after click "Sign and authorize email"
![image](https://github.com/Joystream/pioneer/assets/80429191/3b13ce93-e0cc-4740-96ae-8a5fddbab831)

❌Existing members will be prompted to share email for notificaitons
The same problem. An error was received after click "Sign and authorize email"
![image](https://github.com/Joystream/pioneer/assets/80429191/eac6f330-e95e-4ee1-8706-55858bea4d51)

![image](https://github.com/Joystream/pioneer/assets/80429191/4c7292d0-20f0-44aa-b30e-52141d79ee34)

⚠️I can't test the following steps because I get an error on the previous steps and can't link the mail to my account
Email verification
Individual events results in email notifications
Email notiffs assets and data is correct

**Comment by thesan** [comment]
@mnaamani the error appears to come from SendGrid:
> The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements

**Comment by polikosi** [comment]
teste here : 
![image](https://github.com/Joystream/pioneer/assets/80429191/4cfa34d4-48d8-42c4-9166-949e45b7fa0c)

✅Opt-in in to notifications during sign up (new memebrship creation)
✅Existing members will be prompted to share email for notificaitons

**Election stage changes (announcing, voting, revealing):**
❌**Announcing Period**
Announced candinancy - 16:45 (block 3,414,942)
Recieved email - not received

**Voting period**
Voting - 16:54 (block 3,415,031)
Recieved email - 17:00 (⚠️delay 6 minutes. In my opinion, this is normal)

❌**Revealing Period**
Revealing - 17:04 (block 3,415,131)
Recieved email - It works in a strange way. I've received a "Revealing Period" email after another action. For example: I didn't receive a "Revealing Period" email, but when I send other notifications, such as "Forum Mentions", then I receive a "Revealing Period" email but don't recieve notifications "Forum Mentions".


❌**Forum Mentions**
❌**Forum replies to your posts**
I didn't recieved no one notifications about mention or replies.

**Comment by polikosi** [comment]
upd:
I received the "Mentions in the forum" and "The forum has replied to your posts" notifications in about an hour. 
⚠️I receive all the notifications at the same time, although I expected to receive them at different times.

**Comment by dmtrjsg** [comment]
@kdembler @thesan 
1. Looks like notificaitons arrive with delay? Should we increase the frequency of the cron job (other mechanism) that triggers them?
2. Some transitions did not result in notifications, so would be great to get that sorted. 

@polikosi  the Dev epic had link to Designs ([Figma>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=3600%3A73&t=LsnFZyLXE94cDQkb-1)) was everything okay from design implementation pov?

**Comment by polikosi** [comment]
> @polikosi the Dev epic had link to Designs ([Figma>](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-design?node-id=3600%3A73&t=LsnFZyLXE94cDQkb-1)) was everything okay from design implementation pov?


No, it wasn't.
no bell, no customize notifications.
![image](https://github.com/Joystream/pioneer/assets/80429191/1d502a8f-fb23-429e-9ce2-037eb5f51e12)

@dmtrjsg are you sure that I need test it here? 
![image](https://github.com/Joystream/pioneer/assets/80429191/85334ec2-c5b1-427f-af1a-eaa5468392f9)

**Comment by dmtrjsg** [comment]
@ivanturlakov the first version did not include customizable notifications and in-app notifications. Also opting in to notifications for new users signing up was done in a separate modal (not continuation of the stepped modal). 

Re env, yes that is the correct one. 

Its a challenging epic so we wanted to ship smth out faster, hence the small scope of MVP.

**Comment by thesan** [comment]
@polikosi about the scope:
- As @dmtrjsg mentioned above notifications customization have been taken off the MVP
- in-app notifications are not part of the MVP either.
- Finally it wasn't mentioned yet but the mute and watch features were also taken out of the MVP.
in-app notifications are part of the V1.2 (see: #4230). And I think the customization, watch, and mute features should be added to the next release (V1.1).

About the delay: I'm sorry I forgot to mentioned this in this issue description, but the emails are send in batch every 30min. I can imagine that this time is a bit long when testing so I can reduce it on this deployment. But is it too long for production too ? what do you think should be the cron job frequency @dmtrjsg ? Also @polikosi after accounting for this delay are there still some missing email notifications ?

**Comment by dmtrjsg** [comment]
> But is it too long for production too 
10 minutes would be okay I think. 

> Missing notifications

❌Announcing Period
Announced candinancy - 16:45 (block 3,414,942)
Recieved email - not received

Voting period
Voting - 16:54 (block 3,415,031)
Recieved email - 17:00 (⚠️delay 6 minutes. In my opinion, this is normal)

❌Revealing Period
Revealing - 17:04 (block 3,415,131)
❌ Revealing email - It works in a strange way. I've received a "Revealing Period" email after another action. For example: I didn't receive a "Revealing Period" email, but when I send other notifications, such as "Forum Mentions", then I receive a "Revealing Period" email but don't recieve notifications "Forum Mentions".

❌Forum replies to your posts
I didn't recieved no one notifications about mention or replies.
✅ Forum Mentions

**Comment by polikosi** [comment]
❌Announcing Period
Announced candinancy - 15:07
Recieved email - not receive
I checked this step three times. Out of 3 times, I did not receive any emails about this period.
⚠️I did not receive an email about the Announcing Period when 1 candidate was announced or none was announced. In both cases, I didn't receive an email about the Announcing Period
In my opinion, I should receive an email when the announcement period starts, not when someone announces the first candidate. @thesan @dmtrjsg 

✅Voting period
Start Voting - 15:15
Recieved email - 15:16

✅Revealing Period
Start Revealing - 15:25
Recieved email - 15:26

✅ Forum Mentions 
It works as expected.
❌Forum replies to your posts
I didn't recieved no one notifications about replies.

**Comment by dmtrjsg** [comment]
@thesan sure, let's raise the issue for QN separately and we can release without it. Not critical since will never happen on prod.

**Comment by polikosi** [comment]
> @thesan sure, let's raise the issue for QN separately and we can release without it. Not critical since will never happen on prod.

ok, great!)

And what about the "Forum replies" emails, has this been implemented yet? Can I test it?

**Comment by thesan** [comment]
> And what about the "Forum replies" emails, has this been implemented yet? Can I test it?

@polikosi I just created a PR for it :point_up_2:.

But before deploying it I'll try to figure out the issue with #4624, so that the last round of QA is based on the official Joystream image

**Comment by polikosi** [comment]
✅ Forum Mentions
✅Forum replies to your posts
It works as expected.
