### ISSUE TITLE
Apply for a role: Form

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#4628]
Apply for a role: Form
768px, 1024px, 1440px

![image](https://github.com/Joystream/pioneer/assets/80429191/790a7fbf-22e8-472d-b314-6260c912da03)
![image](https://github.com/Joystream/pioneer/assets/80429191/82be54bf-acaf-460b-8f18-897f69e26f10)
![image](https://github.com/Joystream/pioneer/assets/80429191/cfae1bdd-1276-4712-8515-1d377e8166cc)

**Comment by dmtrjsg** [comment]
@eshark9312 over to you sir
