### ISSUE TITLE
#1794 retest

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#4629]
tersted here: https://dao-git-fork-eshark9312-rwd-address-qa-issue-4609-joystream.vercel.app/

### Working Groups: Openings
**320px**
![image](https://github.com/Joystream/pioneer/assets/80429191/f9f10e6f-a938-4939-a5f8-4d4b1ba2e755)
**1024px**
Should be 2 columns and I don't have to scroll to the left to see "hiring"
![image](https://github.com/Joystream/pioneer/assets/80429191/47ec34bc-adf6-42d6-9010-e5e497a8ba88)
**1440px**
Should be 2 columns
![image](https://github.com/Joystream/pioneer/assets/80429191/5b4a488e-4a99-4801-a04b-bb600fb07aef)

### Working Groups: Expanded WG
**320px**
according to the design there should be 2 rows
![image](https://github.com/Joystream/pioneer/assets/80429191/c76cb57e-e2a3-4d67-bf60-39bbc5f43350)
**425px**
![image](https://github.com/Joystream/pioneer/assets/80429191/11f015db-948f-4954-8c37-e16310178599)
**768px**
there should be 2 rows and the "Apply now" button is visible 
![image](https://github.com/Joystream/pioneer/assets/80429191/0b0b404f-26fc-4734-8183-eb2cf48e7b1f)
Hiring should be visible
![image](https://github.com/Joystream/pioneer/assets/80429191/9b915cbf-c576-40a8-ba36-c7c5b0e5c143)
**1024px**
![image](https://github.com/Joystream/pioneer/assets/80429191/f8b6d5d7-37ca-4845-a40f-9b73a3c97cc8)
**1440px**
according to the design there should be 2 rows
![image](https://github.com/Joystream/pioneer/assets/80429191/6cebdcc2-bb80-4d92-ac61-cda939c0524c)

### Working Groups
**320px**
Table should be min 1123px. The same problem on 425px, 768px, 1024px
![image](https://github.com/Joystream/pioneer/assets/80429191/e085fce9-4b99-4d56-b1d3-4deb52baa369)

### Working Groups: My applications
**320px**
according to the design table should be min 794px. The same problem on 425px, 768px, 1024px
![image](https://github.com/Joystream/pioneer/assets/80429191/ce56a1c4-7129-487b-b9cd-17f84a2d1edd)

**1024px**
it should be in accordance with the design, i.e. the columns should be equal. The same problem on 320px, 425px, 768px, 1440px.
![image](https://github.com/Joystream/pioneer/assets/80429191/e5d44195-aa52-4c2c-b615-ba4439c2d3c1)

### Working Groups: My roles
**320px**
Table should be min 970px. The same problem on 425px, 768px, 1024px, 1440px. The same with past roles.
![image](https://github.com/Joystream/pioneer/assets/80429191/2c32bac8-dc0e-4d44-a1cd-e1f6c5b4ee0f)

**1024px**
according to the design there should be 2 columns.
![image](https://github.com/Joystream/pioneer/assets/80429191/ab6dd3a5-03cf-4f6b-946e-3083627c4f5b)

### Working Groups: Role

![image](https://github.com/Joystream/pioneer/assets/80429191/711633bc-5a4b-4342-90e2-b63e98216827)

**320px**
Account picker should use small variant. The same problem on 425px
![image](https://github.com/Joystream/pioneer/assets/80429191/8e5abfa0-8e4f-4d2b-a256-432e3910c959)

**768px**
Bottons should be below the header
![image](https://github.com/Joystream/pioneer/assets/80429191/9f10b0fe-5082-44b8-b2fa-69c711cf59df)

**1024px**
Bottons should be below the head. according to the design there should be 2 columns.
![image](https://github.com/Joystream/pioneer/assets/80429191/9bdd5e14-faac-448a-a07a-e9090b2f03b1)

### Working Groups: My application
**320px**
This modal shouldn't be displayed on this screen size. The same problem on 425px
![image](https://github.com/Joystream/pioneer/assets/80429191/74ac47c4-4a05-43ab-b5ac-970dfe9e997f)

**768px**
The same problem on 425px, 1024px, 1440px
![image](https://github.com/Joystream/pioneer/assets/80429191/4c679abb-212d-43ce-8133-b5476e376412)

### My roles: Opening
**768px**
according to the design Hired and All applications should be on the right side.
![image](https://github.com/Joystream/pioneer/assets/80429191/b705af04-8fd6-4839-84c8-0e1e76d57594)

**1024px**
there should be 2 columns. According to the design Hired and All applications should be on the right side.
![image](https://github.com/Joystream/pioneer/assets/80429191/b2faa4c6-6302-4f26-b5b5-f9c45fe6c79c)

### Single working group
**1024px**
Hiring should be visible
![image](https://github.com/Joystream/pioneer/assets/80429191/420efe6e-3da1-4d28-8e27-a5cd0e0d59ba)

**1440px**
there should be 2 columns.
![image](https://github.com/Joystream/pioneer/assets/80429191/e70a26f4-aec2-4440-9d0d-3ed5e338150e)

### Single working group: Expende WG
**768px**
there should be 2 rows and the "Apply now" button is visible. The same problem on 1024px
![image](https://github.com/Joystream/pioneer/assets/80429191/3ef577a9-256e-434c-ab19-0fce79fed476)

**1440px**
according to the design there should be 2 colomns.
![image](https://github.com/Joystream/pioneer/assets/80429191/2b47e2a6-0b3d-4cbf-8852-60be0bbd72af)

### Single working group: Learn more
**320px**
When the header is long, the text below does not fit, as shown in the screenshots
![image](https://github.com/Joystream/pioneer/assets/80429191/4b8fa4c7-665f-419d-9ce9-a7213178f97f)
![image](https://github.com/Joystream/pioneer/assets/80429191/07a7b319-e78f-4427-9a4b-37f0c869e834)

according to the design "Hired" and "All applications" should be below "Apply now". The same problem on 425px, 
![image](https://github.com/Joystream/pioneer/assets/80429191/7861d82c-99d7-4e44-8652-d8d53b7c7d9f)

**768px**
footer should be on the right side below cards. The same problem on 1024px,
![image](https://github.com/Joystream/pioneer/assets/80429191/f26e8e85-9f26-4e0c-b52c-e2dff7fa5281)

### Past openings
**1024px**
according to the design table shouldn't be scrollable horisontally
![image](https://github.com/Joystream/pioneer/assets/80429191/eb2be974-04fd-4efe-9468-957d55bb90d7)

### Apply for a role: bind account for staking
**768px**
![image](https://github.com/Joystream/pioneer/assets/80429191/8844e79f-bbbb-4b69-8ecf-6922bf0f57ce)

### Apply for a role: Staking
**768px**
Account picker should use small variant for: "Select account for Staking", "Select role account", "Select reward account"
![image](https://github.com/Joystream/pioneer/assets/80429191/b75ef511-a890-4e53-acbe-3e851ec4fc7f)
**1024px**
Account picker should use medium variant
![image](https://github.com/Joystream/pioneer/assets/80429191/7bbf0f75-b5a1-405f-af7b-af55c362aa3a)

### Apply for a role: Form
#4628 

_### Proposals_
### Proposal preview
**768px**
There should be a botton "Add new proposal". The same problem on 1024px
![image](https://github.com/Joystream/pioneer/assets/80429191/57dfba24-36f3-4016-aae1-09be75b327b2)

### Create proposal: Staking
**768px**
Account picker should use small variant.  I'm not sure it's a small variant.
![image](https://github.com/Joystream/pioneer/assets/80429191/8a51c9ca-3ce9-497c-a190-6ffbec41fa69)

### Create proposal: Specific parameters
**1024px**
![image](https://github.com/Joystream/pioneer/assets/80429191/3d39ff84-a019-449d-8100-0fdb0dab0cdb)

**1440px**
![image](https://github.com/Joystream/pioneer/assets/80429191/25eeaa10-eba5-4e03-b00e-062a4abd114b)

### Create proposal: Authorize Transaction
**768px**
according to the design, a long label should be displayed
![image](https://github.com/Joystream/pioneer/assets/80429191/e9c21c46-9ac4-4d04-8e8d-712e9fa57823)

### Proposal list: current
#4630 

### Proposal list: past
**1024px**
Filters should be horizontall
![image](https://github.com/Joystream/pioneer/assets/80429191/571a461e-dd20-4a4a-bb17-e0d78f28df76)

### Council page
**1024px**
Should be 2 colomns. The same problem on 1440px.
![image](https://github.com/Joystream/pioneer/assets/80429191/43b582bd-a251-41e5-be4a-a7e4dbb75aa9)

### Profile: Member Details
**320px**
This modal shouldn't be displayed on this screen size. The same problem on 425px  screen size
![image](https://github.com/Joystream/pioneer/assets/80429191/4a2827c8-c283-4241-b5d9-f0e54220b6ed)

### Profile: Accounts
**320px**
This modal shouldn't be displayed on this screen size. The same problem on 425px  screen size
![image](https://github.com/Joystream/pioneer/assets/80429191/5834b950-3ab9-4d5f-9fe9-6f084ba05d5c)

### Profile: Working Group Roles
**320px**
This modal shouldn't be displayed on this screen size. The same problem on 425px  screen size
![image](https://github.com/Joystream/pioneer/assets/80429191/f445f3fe-9ba9-4278-aa58-440b4c594805)

### Forum Post Readability
**320px**
Gap should be 16px
![image](https://github.com/Joystream/pioneer/assets/80429191/f2601253-42ac-49eb-8360-1cbb35dec4ef)

**1440px**
The horizontal and vertical gab between thread cards should be 24px
![image](https://github.com/Joystream/pioneer/assets/80429191/cf3c2cec-fa07-41d4-8189-4223d21913c0)

Gap categories cards should be 24px
![image](https://github.com/Joystream/pioneer/assets/80429191/63a44056-1aae-434c-90a6-c8b39cef907e)

### Forum: Thread
**768px**
#4631 

### Forum - Activities
⚠️The page crashes when click on the "Forum Activities" button.
![image](https://github.com/Joystream/pioneer/assets/80429191/47886c69-6eb4-4bbe-9a91-aa75f86b5db8)

### Forum: Watchlist
An icon visible on every page. Must be visible from 1024px.
![image](https://github.com/Joystream/pioneer/assets/80429191/c35b15f0-75d8-4312-9bfa-75424a01b256)

**320px**
Cards should be stacked vertically. The same problem on 425px
![image](https://github.com/Joystream/pioneer/assets/80429191/3116a562-d272-4139-81f9-094b8ce930d8)

**768px**
Cards should be in 2 columns. The same problem on 1024px, 1440px. 
![image](https://github.com/Joystream/pioneer/assets/80429191/319041c8-2a2e-48da-8b0c-aa5295850f1a)

### Forum: My threads
**320px*
Thread cards should be smaller.
![image](https://github.com/Joystream/pioneer/assets/80429191/9b721208-0722-485c-8c67-e1e6aa413a5c)

**768px**
Cards should be in 2 columns. The same problem on 1024px.
![image](https://github.com/Joystream/pioneer/assets/80429191/aa273cd3-1c8d-4e5f-9132-742346da279a)

**1440px**
Gap should be 24px.
![image](https://github.com/Joystream/pioneer/assets/80429191/497467b8-4aba-4030-bb8e-ea0684e79825)

### Forum: Category page
**320px*
Threads table should be 1024px
![image](https://github.com/Joystream/pioneer/assets/80429191/5c6d27d3-a3e8-44a2-bb46-23e81fdde162)

### Reply mode
**1024px*
The modal width should be 940px max. The same problem on 1440px.
![image](https://github.com/Joystream/pioneer/assets/80429191/507281d2-6b1f-4d89-afeb-3e27059a5252)

### Create a thread Modal
**1024px*
The modal width should be 940px max. The same problem on 1440px.

Settings
**320px**
It will be better if all network details are visible. The same on 425px.
![image](https://github.com/Joystream/pioneer/assets/80429191/53538046-7028-46b9-a36a-599552cd75d1)

**1440px**
Banner should be biger. 690px
![image](https://github.com/Joystream/pioneer/assets/80429191/b0fb799a-2409-427f-a432-ff720c7b373a)

**Comment by dmtrjsg** [comment]
@eshark9312 over to you sir

**Comment by polikosi** [comment]
@eshark9312 I apologize for the delay. These are the results of testing something I was unable to test earlier.
tested here - https://95.216.138.118.nip.io/pioneer/#/settings?network-config=https://95.216.138.118.nip.io/network/config.json


### Vote for Proposal
**768px**
Buttons should be staked vertically.
![image](https://github.com/Joystream/pioneer/assets/80429191/bbbffb66-91fc-4ae6-947d-5585b828d65f)

### Vote for Proposal: Success Modal



### Election
**320px**
Should be another variant of tis election progress (same problem on each screen). 
Should use the XXS variant of candidate card.
![image](https://github.com/Joystream/pioneer/assets/80429191/423e1546-3031-4a92-ab04-441634527dd4)

**768px**
The election stats shoud be in horizontal row. Should be another variant of tis election progress .
![image](https://github.com/Joystream/pioneer/assets/80429191/2167382c-49e5-4687-b21c-7b2e7df7beaf)


### Election: Voting results
According to the design, there shouldn't be "Backup votes" here, but I think they should be here. This "Backup votes" button is available on every screen.
![image](https://github.com/Joystream/pioneer/assets/80429191/37c74604-c444-4daa-85b0-6df4980dede3)

**320px**
According to the design, there shouldn't be "Revealed" button. This button is available on every screen.
![image](https://github.com/Joystream/pioneer/assets/80429191/51ddfabc-ef88-4666-8608-76a467ed951f)

**768px**
Cards should be staked horizontally in one raw.
![image](https://github.com/Joystream/pioneer/assets/80429191/cc74f747-d59f-4bbc-8f04-30c345ae601c)

**1024px**
According to design voting result should be use Extra large variant.
![image](https://github.com/Joystream/pioneer/assets/80429191/e863ddd7-7b3b-4a87-9610-2f4544082117)


### Restore votes modal
**1024px**
the modal width should be 940px. The same problem on 1440px
![image](https://github.com/Joystream/pioneer/assets/80429191/6b6ac795-dcca-4256-a30d-45126a66508e)

### Announce candidacy
**768px**
Sidebar should be set to 220px. Acoount picker should use small variant.
![image](https://github.com/Joystream/pioneer/assets/80429191/ed54e636-68a0-40c8-b33a-ce14e7c55cf4)

**1024px*
Should be medium variant.
![image](https://github.com/Joystream/pioneer/assets/80429191/c9d12ed2-cf35-4c42-a4b7-f9f9f49c7cb5)

### Announce candidacy: Reward account
**768px**
Sidebar should be set to 220px. I'm not sure it's a small variant.
![image](https://github.com/Joystream/pioneer/assets/80429191/6e7b10f2-3b8d-4588-8b4d-a8954ead8290)

**1024px*
Should be medium variant.
![image](https://github.com/Joystream/pioneer/assets/80429191/7491e0b4-512c-44b2-9e8d-2a9752377794)

### Announce candidacy: Candidate profile
**768px**
Sidebar should be set to 220px
![image](https://github.com/Joystream/pioneer/assets/80429191/967b18de-9d00-46c1-b0e9-8075f9e53450)
![image](https://github.com/Joystream/pioneer/assets/80429191/6348445d-7d2f-4f47-984e-bf352a44782e)

According to the design, there shouldn't be "Preview profile" button, but I think they should be here
![image](https://github.com/Joystream/pioneer/assets/80429191/6060f812-aa4d-49af-848e-afe870ec0b73)


### Candidacy profile preview
**768px**
The same problem on 1024px and 1440px.
![image](https://github.com/Joystream/pioneer/assets/80429191/f214f015-68dd-4610-8318-d7d9c93f1275)


### Announce candidacy step 1
**768px**
The step component should be minimized to show only the step you are on. The same problem on steps 2 and 3
![image](https://github.com/Joystream/pioneer/assets/80429191/ca0708b1-e7be-431a-b678-5f9b362de019)
