### ISSUE TITLE
Forum:Thread

### ISSUE THREAD

**Issue by polikosi** [Joystream/pioneer#4631]
The title of thread should be visible. There is enough space for this.
768px
![image](https://github.com/Joystream/pioneer/assets/80429191/7508d52b-e68b-499e-9ded-ea202f62f09c)

**Comment by dmtrjsg** [comment]
Already fixed in responsive web design feature. Thank you for raising tho!

**Comment by dmtrjsg** [comment]
@eshark9312  over to you sir

**Comment by eshark9312** [comment]
IMO it is not enough for "Test Multix For Joystream".
