### ISSUE TITLE
Why this button?

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4637]
What does this button do? If I just click it, it just opens a tray and then breaks, at least in FF

<img width="219" alt="Screenshot 2023-11-21 at 12 13 14" src="https://github.com/Joystream/pioneer/assets/437292/cd1cc24a-fd49-4120-a2e2-dc65bba74aa2">

Seems like it should be removed, the CTA makes no sense.

**Comment by dmtrjsg** [comment]
Already raised in
- https://github.com/Joystream/pioneer/issues/4649

The forum activities show the list of latest activities feed.
