### ISSUE TITLE
"Vote again" in my election votes brings up wrong candidate

### ISSUE THREAD

**Issue by kdembler** [Joystream/pioneer#4656]
https://github.com/Joystream/pioneer/assets/12646744/4fe04a37-4597-445d-872d-f9098f9c42a4

As seen on the recording, when clicking "Vote again" next to one of the candidates I have voted for actually opens a voting modal for a different candidate. This is quite risky because somebody could by mistake vote on someone they didn't want to

**Comment by kdembler** [comment]
Wow, created this report and still managed to vote for the wrong candidate 🤦

**Comment by dmtrjsg** [comment]
@chrlschwb looks like a higher prio, would be nice to get it sorted as part of hte support allowance.. If we don't have any allowance for support suggest to start with 10% of term capacity.
