### ISSUE TITLE
Votes: Past votes page is spamming the query node

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#4667]
# Problem
I have many votes and old votes, in order to release stake I must visit this page, for some period of time it displays strange behavior where the page continuously refreshes.
* During the refreshing the `"recover vote"` buttons don't function properly
* It is unclear how to stop it from refreshing except to recover the votes via the `My accounts` page 
* 
![image](https://github.com/Joystream/pioneer/assets/50830161/4dd4a24a-1c8c-4049-baeb-3e310df72981)

**Comment by dmtrjsg** [comment]
cc @chrlschwb

**Comment by mochet** [comment]
This behavior seems to have stopped happening

**Comment by mochet** [comment]
This behavior still happens and another user reported that it only happens with >100 votes (they found this out by disabling some of their addresses)
