### ISSUE TITLE
Show when member was created

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4672]
When I open a membership view panel, I want to see block and timestamp for when member was created, currently there is nothing like that.

![Screenshot 2023-12-04 at 15 22 31](https://github.com/Joystream/pioneer/assets/437292/1e3075d5-4849-4e22-9034-c1630fb141ef)

**Comment by dmtrjsg** [comment]
Agreed, in the meantime it is only available in the table view: 

<img width="557" alt="Screenshot 2023-12-08 at 15 12 31" src="https://github.com/Joystream/pioneer/assets/93924525/9320351e-95a6-456c-a8a5-9ee163c0977b">


## Scope
Add date created as data and block the membership was created to the side panel (member detailed view)
