### ISSUE TITLE
[USERSNAP] I am not able to scroll down on ymscreen with my view set at 90% zoom

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4678]
**Taken at**: https://pioneerapp.xyz/#/working-groups/builders
**Fields**:
- Houston, we have a problem.: I am not able to scroll down on ymscreen with my view set at 90% zoom
- Comment: To be able to scroll down and see more workers because at 90% view, I am not able to view all the workers.
- Feedback: codefikeyz

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bda07e8d-5249-499b-bea7-04fcd90cc65d-annotated_2cbacd52-f906-4476-bb63-86fdd2a47669.png?etag=5af02ee2f5fddbcd230735643747964b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bda07e8d-5249-499b-bea7-04fcd90cc65d-annotated_2cbacd52-f906-4476-bb63-86fdd2a47669.png?etag=5af02ee2f5fddbcd230735643747964b)*

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1517x723
**[Open #435 in Usersnap](https://app.usersnap.com/l/feedback/7cdfc0ec-15e8-441d-86d0-7c8fcf7d602c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by thesan** [comment]
Superseded by #4736
