### ISSUE TITLE
Enable browser extension wallet on mobile

### ISSUE THREAD

**Issue by chrlschwb** [Joystream/pioneer#4681]
While we worked on the RWD for Pioneer, we deliberately removed the possibility of using browser extension wallets on mobile.
Before wallet connect is implemented on Joystream, we would like to enable browser extensions on mobile for signing extrinsics.

This work should be done on top of this. https://github.com/Joystream/pioneer/issues/1794

**Comment by dmtrjsg** [comment]
Needs design

**Comment by thesan** [comment]
This was partially addressed in #4708.

One issue to keep in mind is that unlike the other mobile wallets, the SubWallet browser doesn't reduce the size of the viewport when the keyboard appears, as result on some of the modals to be enabled later people might have to type blind.

**Comment by kdembler** [comment]
Partially done as mentioned above. Closing in favor of https://github.com/Joystream/pioneer/issues/4729
