### ISSUE TITLE
Proposal Activities Not Updating

### ISSUE THREAD

**Issue by Codefikeyz** [Joystream/pioneer#4686]
**Taken at** https://pioneerapp.xyz/#/proposals/current

- Proposal activities stopped updating 6 months ago

![Screenshot_71](https://github.com/Joystream/pioneer/assets/123887455/816a45b1-1191-40e8-972b-55982521836d)

**Comment by mochet** [comment]
duplicate of https://github.com/Joystream/pioneer/issues/4673
