### ISSUE TITLE
Validate active member before action

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#473]
Most of the working group actions are executed in the context of active membership.

We should add those checks where appropriate, for instance:

*   applying for an opening

The app should either:

*   disable "apply for.. " type of buttons (probably a hint for the user would be beneficial
*   show info modal with "select" member action

This is also tied with the requirement of selecting a member before using the Pioneer app. We concluded that enforcing users to select a member on every page refresh might be cumbersome. However, we did not think that most of the actions in particular modules will require the user to select a member.

Either way, we also should allow any non-member to browse the app. So we might also need to show either "select member" or "buy membership" actions depending on whether the user has or has not any memberships.

**Comment by p-sad** [comment]
Checked all sections of the app; so far only applying for openings needs this, but it's good to keep it in mind going forward. I think making proposals will need a check like this, for example.
