### ISSUE TITLE
Make README prettier

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#477]
Could make the README slightly more appealing to new devs arriving, for example by having some nice glossy high resolution product screenshots and relevant badges. Here are some aspirational examples.
- https://github.com/webtorrent/webtorrent-desktop
- https://github.com/atom/atom

**Comment by jodator** [comment]
The main goal of the issue was to make README.md a bit more attractive. This was already done. The other aspects of making the README more helpful for new devs will be handled here: #1474
