### ISSUE TITLE
Luxor followups

### ISSUE THREAD

**Issue by kdembler** [Joystream/pioneer#4824]
https://github.com/Joystream/pioneer/pull/4816:
- Display the proposed amount to be reduced in proposal details

https://github.com/Joystream/pioneer/pull/4818
- Display the proposed damping factor in proposal details

**Comment by thesan** [comment]
> Display the proposed damping factor in proposal details

This is already done: https://pioneer-2-storybook-git-feature-luxorreward-cu-8291ab-joystream.vercel.app/?path=/story/pages-proposals-proposalpreview--set-era-payout-damping-factor

**Comment by traumschule** [comment]
Just created the proposal and both appear done the me as well: https://pioneerapp.xyz/#/proposals/preview/874

**Comment by thesan** [comment]
@traumschule yeah I addressed these in the original PRs and forgot to close the issue. Thank you for closing it.
