### ISSUE TITLE
Cannot edit forum posts on Pioneer 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4860]
Clicking on Edit post closes the overflow menu so posts are uneditable from UI

<img width="230" alt="Screenshot 2024-07-03 at 17 42 53" src="https://github.com/Joystream/pioneer/assets/93924525/8c76e188-ebc5-4ff0-bf30-f2a2f7891b92">

**Comment by kdembler** [comment]
Fixed by #4861
