### ISSUE TITLE
Implement breadcrumbs logic

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#490]
### Requirements

*   update the breadcrumbs logic
*   the last breadcrumb shouldn't be clickable

**Comment by p-sad** [comment]
To consider:
`use-react-router-breadcrumbs` can autogenerate crumbs, but some of these will point to routes that don't exist, e.g. `/working-groups/grouppreview/0` has a crumb pointing to `/working-groups/grouppreview`.

**Comment by p-sad** [comment]
Each breadcrumb will need a nice display text instead of route path part text, might want to use some kind of dictionary
Not sure how to translate object IDs to display text, will require telling the breadcrumbs component what entity the ID represents

**Comment by jodator** [comment]
> Each breadcrumb will need a nice display text instead of route path part text, might want to use some kind of dictionary  
> Not sure how to translate object IDs to display text, will require telling the breadcrumbs component what entity the ID represents

I think that this might be addressed by: [https://www.npmjs.com/package/use-react-router-breadcrumbs#route-config-compatibility.](https://www.npmjs.com/package/use-react-router-breadcrumbs#route-config-compatibility.) Additionally, using route config is also nice as we could have defined routes and breadcrumbs together.

Additionally, we might need to match WorkingGroup id/name to the path (the URL will be nicer).

So the routes for the working group could be:

```
/working-groups/storage
// or:
/working-group/storage


// instead of:
/working-groups/grouppreview/0
```
