### ISSUE TITLE
Use membersByHandle to search for members

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#499]
The Hydra API provides a dedicated search query that should be used to search members.

Info:

*   Query: `membersByHandle`
*   Output: `MembersByHandleFTSOutput`

This might be used for searching members in all member-related dropdowns.

**Comment by dmtrjsg** [comment]
Not needed for Overview as per Pawel.

**Comment by dmtrjsg** [comment]
@thesan do you know if this was already done?
look slike it!
