### ISSUE TITLE
Proposals milestone

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#539]
# Introduction

![](https://user-images.githubusercontent.com/247363/117768480-b9c90500-b232-11eb-9c66-9b2f45e5ece2.png)

The proposal system is the way changes to the platform state and policy are suggested, discussed, voted on by the council, and finalized as accepted or rejected.

*   [Proposals chapter](https://joystream.gitbook.io/joystream-handbook/governance/proposals) in the handbook
*   [Wireframes](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=518%3A25635)

# Goals

The proposals subsystem will allow users to:

1.  Browse active proposals
2.  Browse & search for past proposals
3.  Display proposal details
4.  Creating a proposal

The proposal catalog is not closed and implementing all of them might be a time-consuming task. However, a base layer for proposals should be created having in mind that:

*   A proposal has general and specific parameters.
*   The list of proposals can grow in time so we should try to make the proposal adding process easier.
*   The council's actions are not part of the milestone.

# Goals details

Each goal has a work scope with links to GH tickets.

*   Tickets with a :purple\_circle: (and "epic" label) are considered to require ~1 week of work).
    *   The rest of the tickets should require a 0.5-1 day of work each.
*   Tickets with a :warning: requires further research to estimate

### Integration, common components

*   Setup base proposals schema, mocks & queries #800 :purple\_circle:
*   Selected member component #838
*   Roles select #692
*   Calendar select component #584

### 1\. Browse active proposals

*   Proposals page #540
*   Current proposals list #541 , #583

### 2\. Browse past proposals

*   Past proposals filters #585 , #586

### 3\. Display proposal details

*   Base proposal page #801 :purple\_circle:
*   Vote's rationale #807
*   Discussion component #868 :purple\_circle:
*   Proposal stages #869

### 4\. Adding a proposal

*   Prerequest check #832
*   Proposal warning #833
*   Proposal type selection #834
*   Proposal required stake check #835
*   Stake step #836
*   General parameters – title & rationale #837
*   General parameters – trigger & discussion #839
*   Sign & send transaction #877

### 3\. Display specific proposal details

*   Funding request #870
*   Runtime upgrade #802
*   Create Working Group Lead opening #803
*   Decrease Working Group Lead stake #804
*   Slash Working Group Lead #805
*   Amend constitution #806 :purple\_circle: :warning: (Display diff might be time-consuming)

### 4\. Adding a specific proposal

*   Funding request #871
*   Runtime upgrade #872 :warning: (file upload might require specification)
*   Create Working Group Lead opening #873
*   Decrease Working Group Lead stake #874
*   Slash Working Group Lead #875
*   Amend constitution #876 :warning: (file upload might require specification)

**Comment by bedeho** [comment]
Phenomenal work here, just brilliant.

**Comment by jodator** [comment]
The tasks that were moved out of the scope are:

*   #876 
*   #806 

The "amend constitution" looks like a bigger task. We also do not handle other proposal types, which should be handled together.
