### ISSUE TITLE
Current proposals

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#541]
@[figma](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=533%3A10)

### Requirements

- display current / past tabs stubs
- prepare proposals list component (add storybook story for every new component)
- prepare Proposal interface
- add stub "proposal activities" component

### Implementaiton detials

We should start implementing the base components using storybook-first aproach and preparing the internal Proposal interface. All of the data should be fetched using hooks. Before we get the proper GraphQL schema we will stub data in hooks. The Hydra (GraphQL server) integration will be added later but the changes should be limited to the hooks internals. The hook API should be similar to the one created for the Working Groups or Memberships queries.

**Comment by jodator** [comment]
@thesan This issue can be split into multiple PRs.

**Comment by jodator** [comment]
You can also create a base hook to get the proposals, something like this:

```typescript
const useProposals = () => {
  const proposals: Proposal[] = [
    { id: 0, stage: 'DECIDING', type: 'Founding request', title: 'Lorem ipsum foo bar', proposer: { id: '0', ... } },
    { id: 1, stage: 'DORMANT', type: 'Founding request', title: 'Lorem ipsum foo bar', proposer: { id: '0', ... } },
  ]
  
  return {
    isLoading: false
    proposals
  }
}
```

This will make the upgrade to the GraphQL API a bit easier.

**Comment by jodator** [comment]
Ps.: see the updated designs for the proposals list: ([design](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=2599%3A109614)).

I think that the current proposals will have the same styles as the past. The only change is that the background of the current opening should be white. Similarly to [current](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=16%3A2266) / [past](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=257%3A16856) openings.

**Comment by thesan** [comment]
> You can also create a base hook to get the proposals, something like this:
> 
> ```ts
> const useProposals = () => {
>   const proposals: Proposal[] = [
>     { id: 0, stage: 'DECIDING', type: 'Founding request', title: 'Lorem ipsum foo bar', proposer: { id: '0', ... } },
>     { id: 1, stage: 'DORMANT', type: 'Founding request', title: 'Lorem ipsum foo bar', proposer: { id: '0', ... } },
>   ]
>   
>   return {
>     isLoading: false
>     proposals
>   }
> }
> ```
> 
> This will make the upgrade to the GraphQL API a bit easier.

Yes I will add a `useProposals` base hook when I'm just done with the component creation.

But currently there's no `title` attribute in the `Proposal` type should I add it ?

**Comment by jodator** [comment]
> Yes I will add a `useProposals` base hook when I'm just done with the component creation.

:+1: 

> But currently there's no `title` attribute in the `Proposal` type should I add it ?

Yep - I see that when you create a proposal a title must be set ([extrinsic](https://joystream.gitbook.io/joystream-handbook/governance/proposals#submit-proposal))

**Comment by jodator** [comment]
I think that this one is considered done :white\_check\_mark:

**Comment by thesan** [comment]
> I think that this one is considered done white_check_mark

Okay, I thought the "past tabs stub" was the page (which includes the filter and thus the DatePicker).

**Comment by jodator** [comment]
@thesan Yeah, I've created a more detailed steps for the Proposals milestone:

*   past proposals list: #583 
*   calendar select: #584 

etc
