### ISSUE TITLE
Dealing with deadlines overload

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#56]
As a member, possibly involved in lots of different roles, proposals, blog posts ,elections, etc. I may be facing lots of different timers that are simultaneously in flight, each of which may require me to do some action either before or after the timer in order to serve my interests. I would like to see an overview of all such events which are counting down that are relevant to me personally in one location, because otherwise I will need to go a chase down different areas of Pioneer

**Comment by dmtrjsg** [comment]
[deadlines in overview module> ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=4078%3A1619)

We need to see if basic filters+ sorting would suffice or a full page experience is required for managing deadlines. Usability tests of Overview module would be a good opening for dealing with this topic.
