### ISSUE TITLE
Implement Calendar select

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#584]
@[figma](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=1372%3A64930)

Prepare the calendar select component. This looks like that there might be some existing components to be used and restyled only. Check the existing solution and consult before implementation.

Only the Date select (without the Block select) for this task.

**Comment by thesan** [comment]
@jodator sorry I checked before starting but apart from the InputComponent (for the top part), I didn't find other components to from the project codebase reuse for this. Did I miss something ?

Also I had already started implementing a multirange slider which is now almost done.

**Comment by jodator** [comment]
> Also I had already started implementing a multirange slider which is now almost done.

Oh - let's keep it for now, but you can leave it in some sort of unfinished state if it needs polishing or adding logic.
