### ISSUE TITLE
Update select label styles & sizes

### ISSUE THREAD

**Issue by ClumsyVlad** [Joystream/pioneer#640]
https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=2599%3A109614

![image](https://user-images.githubusercontent.com/36150652/118962382-9bb38100-b965-11eb-85a1-cdf4c1bf8cef.png)

**Comment by jodator** [comment]
@ClumsyVlad is this still relevant or close?
