### ISSUE TITLE
Create a story for `<SelectMember />`

### ISSUE THREAD

**Issue by thesan** [Joystream/pioneer#757]

**Comment by jodator** [comment]
@thesan I'm merging the #749. However, [the Members' roles must a static list](https://github.com/Joystream/pioneer/pull/749#discussion_r646643219) of all available roles. This way you don't have to iterate over all members from the result.

The role's map can be taken from either: working groups (using `useWorkingGroups()` hook to get the names of working groups) and adding `isLead` option. Something along those lines:

```
interface Role {
  groupName: string
  isLead: boolean
}

const ROLES: Role = [
  { groupName: 'membership', isLead: true },
  { groupName: 'membership', isLead: false },
]
```

So, I'd like to ask you to change that in this issue as well.

**Comment by thesan** [comment]
> @thesan I'm merging the #749. However, [the Members' roles must a static list](https://github.com/Joystream/pioneer/pull/749#discussion_r646643219) of all available roles. This way you don't have to iterate over all members from the result.
> 
> The role's map can be taken from either: working groups (using `useWorkingGroups()` hook to get the names of working groups) and adding `isLead` option. Something along those lines:
> 
> ```
> interface Role {
>   groupName: string
>   isLead: boolean
> }
> 
> const ROLES: Role = [
>   { groupName: 'membership', isLead: true },
>   { groupName: 'membership', isLead: false },
> ]
> ```
> 
> So, I'd like to ask you to change that in this issue as well.

Thanks for mentioning the `useWorkingGroups()` I was not sure how to generate the role list properly.

I agree iterating through the members is not a good solution (especially since it only iterate through the current page). But I didn't touch this code because I was working on #692 at the same time and I should remove this code for this issue anyway.

If it's fine with you I will implement a hook `useAllMemberRoles()` hook in the PR for #692 which should be ready soon.

Also, sorry about your comment in #749 I thought you meant that we should wait for the schema upgrade.
