### ISSUE TITLE
Handle recoverable balance

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#790]
Follow-up for the #303:

*   Display recoverable balances
*   Allow recovering balance

See [solution 1](https://github.com/Joystream/pioneer/issues/790#issuecomment-937706768) for the implementation details.

**Comment by jodator** [comment]
AFAICS the recoverable balance is the "Staking for voting" kind. It can be removed when other locks are present.

**Comment by jodator** [comment]
OK, I've found out one bug in the code. The locks were using wrong ids for some actions. ATM I was able to create locks for:

*   staking candidate (11)
*   membership worker (09)
*   member invitation (10)

**Comment by jodator** [comment]
So AFAICS the only recoverable lock is Staking/Voting. The logic to recover balance is updated to handle this.

> \- recoverable balance: the amount by which the free balance can increase if one removes an idle lock. Idle locks are locks that are just present as a result of some staking in the past. The only such kind of lock is a lock for voting. Importantly, you may have an idle lock on an account but a recoverable balance of 0 on that account, this can happen if there is another lock on the same account which is at least as large, and so it still freezes all the funds, an nothing is recoverable. A user should probably still remove any idle locks, as they may cause inconvenience in the future anyway.

I've also found in the API releasing council candidacy stake. I've found two calls to release stake:  
1\. Referendum: (**`VotingLockId`**) API to release: **`api.tx.referendum.releaseVoteStake()`**  
2\. Candidacy: (**`CandidacyLockId`**) API to release: **`api.tx.council.releaseCandidacyStake()`**

**Comment by jodator** [comment]
So AFAICS the only recoverable lock is Staking/Voting. The logic to recover balance is updated to handle this.

> \- recoverable balance: the amount by which the free balance can increase if one removes an idle lock. Idle locks are locks that are just present as a result of some staking in the past. The only such kind of lock is a lock for voting. Importantly, you may have an idle lock on an account but a recoverable balance of 0 on that account, this can happen if there is another lock on the same account which is at least as large, and so it still freezes all the funds, an nothing is recoverable. A user should probably still remove any idle locks, as they may cause inconvenience in the future anyway.

I've also found in the API releasing council candidacy stake. I've found two calls to release stake:  
1\. Referendum: (**`VotingLockId`**) API to release: **`api.tx.referendum.releaseVoteStake()`**  
2\. Candidacy: (**`CandidacyLockId`**) API to release: **`api.tx.council.releaseCandidacyStake()`**

**Comment by jodator** [comment]
The `CandidacyLock` can be recovered as well as the API allows that. This one was used in the code to test the logic.

The `VotingLock` can't be released in batch as each vote release must be signed by a different account. This means we need to update the modal in order to:

*    use multi-transaction modal
*   gather all recoverable balances & create transactions for them

**Comment by jodator** [comment]
### Problem

Taking a look back at the designs of recovering balances I think that we need to redesign stake recovery because having a recover-all button might create an indeterminate number of transactions. This depends on the number of accounts with locks.

The below example is a bit exaggerated, but is possible:

*   A Pioneer user has 20 accounts
*   This user uses all of the accounts to cast a vote in a council election

We can easily create a set of 20 transactions to execute them one-by-one (similar to creating a proposal, etc) but because every transaction needs to be signed by a different account, thus requires a round-back to the extension to sign a transaction it:

*   would be cumbersome for many transactions
*   the UI is not ready for this – we'd assume 2-3 transactions to be handled in more complex steps, however, 4 or more would require a different indication of the progress.

## Possible solutions

1.  Remove the recover all button & add the recover lock button to the accounts page
2.  On the recover all modal display recover button that will recover given lock
3.  Combine both

### Ad. 1 Remove the recover all

![](https://user-images.githubusercontent.com/247363/136374721-3abbd26f-feb5-409b-a206-57687a369f3a.png)

In this variant, we add a "Recover" button on the recoverable lock info.

Cons:

*   might be a bit harder to discover (one must open the account info)
*   no place to recover all

Pros:

*   handling new recoverable locks will be quite straightforward
*   one button = one transaction = one signing process

### Ad. 2 Recover all modal changes

![](https://user-images.githubusercontent.com/247363/136375431-fd58c723-4a50-4a17-84d7-3bec5ced8f1b.png)

In this variant, we add "recover" buttons alongside every account. In this flow after click on the recover button, the user signs the transaction and waits for the outcome. Then the button changes to a disabled state and the user can recover the next balance.

Cons:

*   I'm not sure if this is the best UX as it looks complex and IMO doesn't bring much benefit over 1
*   This flow might be complicated to implement

Pros:

*   a place that allows the user to recover all recoverable stake
*   one button = one transaction = one signing process

### Ad. 3. Combine both

This just allows the user to recover balances using either of the buttons.

Cons:

*   Mostly cons of (2)
*   More work required to cover both

Pros:

*   easy to discover and give the user more freedom

**Comment by bedeho** [comment]
Sorry for the late reply here, but I think in that case, it is probably easier to just go with 1 for now as you say!

**Comment by jodator** [comment]
> Sorry for the late reply here, but I think in that case, it is probably easier to just go with 1 for now as you say!

Thank you for the confirmation. We'll start working on the first solution then.
