### ISSUE TITLE
Setup base Proposals mocks and queries

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#800]
The Proposal schema is almost ready – we should start working with the mocks close to the target API as soon as possible.

### Requirements:

- setup base Proposal types
- stub Proposals mocks
- intorduce queries to fetch:
  - current proposals
  - past proposals
  - a proposal

**Comment by DevNikita16** [comment]
`implements Event, BaseGraphQLObject` is not supported by our codegen or graphql

it should be replaced into `implements Event & BaseGraphQLObject`
