### ISSUE TITLE
Proposal: Amend Constitution

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#806]
@[figma](https://www.figma.com/file/pgNl83wgAub186krVkdiuo/Proposals?node-id=267%3A9603)

Handle proposals specific properties:

- [ ] New constitution preview
- [ ] Constitution preview component

Notes:

> The constitution is indeed an issue. I suggest we just allow people to provide their own HTTP URL where it lives, so no upload, same as avatars. Then when the consitution is being displayed, the Pioneer app should do hash verification that the resources loaded matches the latest constitution hash accepted. If someone loses or changes the external file, we can fix this later.

> When we integrate with the v2 storage system this will get solved, but we are better off doing all storage integrations at once across the app

**Comment by traumschule** [comment]
Closing this according to https://github.com/Joystream/pioneer/issues/4390#issuecomment-1558535152
