### ISSUE TITLE
Apply Council members filters in members search

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#858]
Handle the Council members filters:

![](https://user-images.githubusercontent.com/247363/122526338-77a59700-d01a-11eb-8714-c754c244e34f.png)

**Comment by oleksanderkorn** [comment]
Hi @jodator I am working on it as part of KPIs atm. 
Having bad request response from GraphQL endpoint when trying to filter members by `isCouncilMember_eq`:
```
message: "Variable \"$where\" got invalid value { isCouncilMember_eq: true }; Field \"isCouncilMember_eq\" is not defined by type MembershipWhereInput. Did you mean isFoundingMember_eq or isFoundingMember_in?"
```
As I can see, it is defined in the local schema, maybe the endpoint schema is not up to date?

**Comment by jodator** [comment]
> As I can see, it is defined in the local schema, maybe the endpoint schema is not up to date?

Hi @oleksanderkorn :wave: Yes, the schema on the testnet endpoint is outdated. The filtering should work with [mocks](https://github.com/Joystream/pioneer/blob/main/docs/mocks.md) though and running local joystream node.
