### ISSUE TITLE
Gather required activites filters

### ISSUE THREAD

**Issue by jodator** [Joystream/pioneer#882]
We need a list of screens or actions where we display events fetched from the Query Node in order to gather possible filters or groups. Let's focus on the currently touched systems for now:

- Memberships
- Working Groups
- Proposals

I think that some events may land in two or more categories, most likely in the main context and in the context of a member. But lets' check that.

**Comment by p-sad** [comment]
Below is a table containing events that appear as activities in the design. Included are also some objects referenced by each event - may have some importance, seeing how if these were to become more generic, they could use a common object ID to query them by.

Also, it seems that there is a significant overlap between Member and Worker activities. Most Member notifications concerning forum activities don't have any events implemented for them yet. A list of these can be found below the table.

| Event | Appears as an activity for | References |
| --- | --- | --- |
| Working Group | Worker | Proposal | Member Notif. | Working Group | Worker | Proposal | Application | Opening | Upcoming Opening | Member |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| ApplicationWithdrawnEvent | yes | yes |   |   | x |   |   | x |   |   |   |
| AppliedOnOpeningEvent | yes | yes |   | yes | x |   |   | x | x |   |   |
| BudgetSetEvent | yes |   |   |   | x |   |   |   |   |   |   |
| BudgetSpendingEvent | yes |   |   |   | x |   |   |   |   |   |   |
| LeaderSetEvent | yes |   |   |   | x | x |   |   |   |   |   |
| LeaderUnsetEvent | yes |   |   |   | x | x |   |   |   |   |   |
| StatusTextChangedEvent | yes |   |   |   | x |   |   |   |   | \[x\] |   |
| OpeningAddedEvent | yes |   |   |   | x |   |   |   | x |   |   |
| OpeningCanceledEvent | yes |   |   |   | x |   |   |   | x |   |   |
| StakeSlashedEvent | yes | yes |   | yes | x | x |   |   |   |   |   |
| StakeIncreasedEvent | yes | yes |   | yes | x | x |   |   |   |   |   |
| StakeDecreasedEvent | yes | yes |   | yes | x | x |   |   |   |   |   |
| WorkerExitedEvent | yes | yes |   | yes | x | x |   |   |   |   |   |
| WorkerStartedLeavingEvent | yes |   |   |   | x | x |   |   |   |   |   |
| OpeningFilledEvent \* | yes | yes |   | yes | x | \[x\] |   |   | x |   |   |
| TerminatedLeaderEvent | yes | yes |   | yes | x | x |   |   |   |   |   |
| TerminatedWorkerEvent | yes | yes |   | yes | x | x |   |   |   |   |   |
| WorkerRewardAccountUpdatedEvent |   | yes |   |   | x | x |   |   |   |   |   |
| WorkerRewardAmountUpdatedEvent |   | yes |   |   | x | x |   |   |   |   |   |
| ProposalCancelledEvent |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalCreatedEvent |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalDecisionMadeEvent |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalDiscussionPostCreatedEvent \*\* |   |   | yes |   |   |   | x |   |   |   | x |
| ProposalDiscussionPostDeletedEvent \*\* |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalDiscussionPostUpdatedEvent \*\* |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalDiscussionThreadCreatedEvent \*\* |   |   | yes |   |   |   | x |   |   |   | x |
| ProposalDiscussionThreadModeChangedEvent \*\* |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalExecutedEvent |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalStatusUpdatedEvent |   |   | yes |   |   |   | x |   |   |   |   |
| ProposalVotedEvent |   |   | yes | yes |   |   | x |   |   |   | x |
| PostAddedEvent |   |   |   | yes |   |   |   |   |   |   |   |
| PostReactedEvent |   |   |   | yes |   |   |   |   |   |   | x |

\*the OpeningFilledEvent contains workers hired

\*\*these events seem to have corresponding designs, but these designs are a bit difficult to understand

Member notifications that don't have an event yet:

*   mentioned on a post in a thread (maybe could be retrieved from post added event?)
*   member's post was replied to (maybe could be retrieved from post added event?)

**Comment by jodator** [comment]
I see that there's a dedicated issue for Hydra (link above), so we can close this research ticket.
