### ISSUE TITLE
Change the font

### ISSUE THREAD

**Issue by andybut** [Joystream/pioneer#979]
It is necessary to change the font because visually the letters "I" and small "L" do not differ (Il). This led to a problem with the decryption of the signature https://testnet.joystream.org/#/toolbox/sign.

**Comment by jodator** [comment]
Hi @andybut , first of all, sorry for the late reply.

This repository is dedicated to Pioneer 2.0 effort. The testnet you are referring to is using the polkadot/apps version (Pioneer 1).

That being said, the Pioneer 2.0 will use a different set of features. Some actions will be possible through the polkadot hosted walled as well, so you could c[reate a similar issue for them](https://github.com/polkadot-js/apps) (AFAICS they use the same font as in Pioneer 1).

**Comment by jodator** [comment]
Hi, I'm closing this issue for Pioneer 2.
